ayats = [
    {
        "arabic_text": "اقْرَاَ بِاسْمِ رَبِّكَ الَّذِى خَلَقَ",
        "urdu_text": "پڑھو (اے نبی) اپنے رب کے نام سے جس نے پیدا کیا",
        "persian_text": "بخوان به نام پروردگارت که آفرید",
        "english_text": "Read in the name of your Lord who created.",
        "transliteration": "Iqra' bismi rabbika allathee khalaq.",
        "verse_number": "1",
    },
    {
        "arabic_text": "خَلَقَ الْاِِنسَٰنَ مِنْ عَلَقٍ",
        "urdu_text": "جس نے انسان کو خون کے لوتھڑے سے پیدا کیا",
        "persian_text": "انسان را از علق آفرید.",
        "english_text": "Created man from a clinging substance.",
        "transliteration": "Khalaq al-insana min 'alaq.",
        "verse_number": "2",
    },
    {
        "arabic_text": "اقْرَاَ وَرَبُّكَ الْاَكْرَمُ",
        "urdu_text": "پڑھو اور تمہارا رب سب سے زیادہ کریم ہے",
        "persian_text": "بخوان و پروردگارت بزرگوارترین است.",
        "english_text": "Read, and your Lord is the Most Generous.",
        "transliteration": "Iqra' wa rabbuka al-akram.",
        "verse_number": "3",
    },
    {
        "arabic_text": "الَّذِى عَلَّمَ بِالْقَلَمِ",
        "urdu_text": "جس نے قلم کے ذریعے (علم) سکھایا",
        "persian_text": "که با قلم آموزش داد.",
        "english_text": "Who taught by the pen.",
        "transliteration": "Allathee 'allama bil-qalam.",
        "verse_number": "4",
    },
    {
        "arabic_text": "عَلَّمَ الْاِِنسَٰنَ مَا لَمْ يَعْلَمْ",
        "urdu_text": "انسان کو وہ کچھ سکھایا جو وہ نہیں جانتا تھا",
        "persian_text": "به انسان آموخت آنچه را که نمی‌دانست.",
        "english_text": "Taught man what he did not know.",
        "transliteration": "Allama al-insana ma lam ya'lam.",
        "verse_number": "5",
    },
    {
        "arabic_text": "كَلَّا اِِنَّ الْاِِنسَٰنَ لَيَطْغَىٰ",
        "urdu_text": "یقیناً انسان سرکشی کرتا ہے",
        "persian_text": "به یقین، انسان سرکشی می‌کند.",
        "english_text": "No! But indeed, man transgresses.",
        "transliteration": "Kalla inna al-insana layatgha.",
        "verse_number": "6",
    },
    {
        "arabic_text": "اَن رَّءَاهُ اسْتَغْنَىٰ",
        "urdu_text": "جب وہ اپنے آپ کو بے نیاز سمجھتا ہے",
        "persian_text": "هنگامی که خود را بی‌نیاز می‌بیند.",
        "english_text": "Because he sees himself self-sufficient.",
        "transliteration": "An ra'ahu istaghna.",
        "verse_number": "7",
    },
    {
        "arabic_text": "اِِنَّ اِِلَىٰ رَبِّكَ الرُّجْعَىٰ",
        "urdu_text": "یقیناً تمہارے رب ہی کی طرف واپس جانا ہے",
        "persian_text": "قطعاً بازگشت به سوی پروردگار تو است.",
        "english_text": "Indeed, to your Lord is the return.",
        "transliteration": "Inna ila rabbika al-ruj'a.",
        "verse_number": "8",
    },
]
[
    {
        "arabic_text": "اَرَاَيْتَ الَّذِى يَنْهَىٰ",
        "urdu_text": "کیا آپ نے اس شخص کو دیکھا جو روکتا ہے",
        "persian_text": "آیا دیدی آن کسی را که منع می‌کند؟",
        "english_text": "Have you seen the one who forbids?",
        "transliteration": "Ara'aita allathee yanha.",
        "verse_number": "9",
    },
    {
        "arabic_text": "عَبْدًا اِِذَا صَلَّىٰ",
        "urdu_text": "ایک بندے کو جب وہ نماز پڑھتا ہے؟",
        "persian_text": "بنده‌ای را هنگامی که نماز می‌خواند؟",
        "english_text": "A servant when he prays?",
        "transliteration": "Abdan itha salla.",
        "verse_number": "10",
    },
    {
        "arabic_text": "اَرَاَيْتَ اِِن كَانَ عَلَى الْهُدَىٰ",
        "urdu_text": "کیا آپ نے دیکھا اگر وہ ہدایت پر ہوتا",
        "persian_text": "آیا دیدی اگر او بر هدایت بود؟",
        "english_text": "Have you seen if he was upon guidance?",
        "transliteration": "Ara'aita in kana 'ala al-huda.",
        "verse_number": "11",
    },
    {
        "arabic_text": "اَوْ اَمَرَ بِالتَّقْوَىٰ",
        "urdu_text": "یا تقویٰ کا حکم دیتا؟",
        "persian_text": "یا به تقوا فرمان می‌داد؟",
        "english_text": "Or enjoins righteousness?",
        "transliteration": "Aw amara bi al-taqwa.",
        "verse_number": "12",
    },
    {
        "arabic_text": "اَرَاَيْتَ اِِن كَذَّبَ وَتَوَلَّىٰ",
        "urdu_text": "کیا آپ نے دیکھا اگر وہ جھٹلاتا اور منہ پھیرتا؟",
        "persian_text": "آیا دیدی اگر او تکذیب کرد و روی گرداند؟",
        "english_text": "Have you seen if he denies and turns away?",
        "transliteration": "Ara'aita in kaththaba watawalla.",
        "verse_number": "13",
    },
    {
        "arabic_text": "اَلَمْ يَعْلَم بِاَنَّ اللَّهَ يَرَىٰ",
        "urdu_text": "کیا اسے معلوم نہیں کہ اللہ دیکھ رہا ہے؟",
        "persian_text": "آیا نمی‌داند که خداوند می‌بیند؟",
        "english_text": "Does he not know that Allah sees?",
        "transliteration": "Alam ya'lam bianna Allaha yara.",
        "verse_number": "14",
    },
    {
        "arabic_text": "كَلَّا لَئِن لَّمْ يَنتَهِۦ لَنَسْفَعًا بِالنَّاصِيَةِ",
        "urdu_text": "ہرگز نہیں! اگر وہ باز نہ آیا تو ہم پیشانی کے بالوں سے پکڑیں گے",
        "persian_text": "نه! اگر دست برندارد، او را به پیشانی خواهیم گرفت.",
        "english_text": "No! If he does not desist, We will surely drag him by the forelock.",
        "transliteration": "Kalla la-in lam yantahi lanasfa'an bin-nasiyah.",
        "verse_number": "15",
    },
    {
        "arabic_text": "نَاصِيَةٍ كَٰذِبَةٍ خَاطِئَةٍۢ",
        "urdu_text": "جھوٹی، خطاکارکی  پیشانی",
        "persian_text": "پیشانی دروغ‌گو و گناهکار.",
        "english_text": "A lying, sinning forelock.",
        "transliteration": "Nasiyatin kathibatin khati'ah.",
        "verse_number": "16",
    },
    {
        "arabic_text": "فَلْيَدْعُ نَادِيَهُۥ",
        "urdu_text": "پھر وہ اپنے ساتھیوں کو بلائے",
        "persian_text": "پس یاران خود را بخواند.",
        "english_text": "Then let him call his associates.",
        "transliteration": "Falyad'u nadiyah.",
        "verse_number": "17",
    },
    {
        "arabic_text": "سَنَدْعُ الزَّبَانِيَةَ",
        "urdu_text": "ہم بھی عذاب کے فرشتوں کو بلائیں گے",
        "persian_text": "ما نیز فرشتگان عذاب را فرا خواهیم خواند.",
        "english_text": "We will call the angels of punishment.",
        "transliteration": "Sanad'u az-zabaniyah.",
        "verse_number": "18",
    },
    {
        "arabic_text": "كَلَّا لَا تُطِعْهُۥ وَاسْجُدْ وَاقْتَرِب",
        "urdu_text": "نہیں، آپ اس کی بات نہ مانیں اور سجدہ کریں اور قریب ہو جائیں",
        "persian_text": "هرگز اطاعت مکن و سجده کن و به او نزدیک شو.",
        "english_text": "No! Do not obey him, but prostrate and draw near.",
        "transliteration": "Kalla la tuti'hu wasjud waqtarib.",
        "verse_number": "19",
    },
]
