ayats = [
    {
        "verse_number": "1",
        "arabic_text": "عَبَسَ وَتَوَلَّىٰٓ",
        "urdu_text": "اسنے منھ بسور لیا اور پیٹھ پھر لی",
        "persian_text": "روی ترش کرد و روی گردانید",
        "english_text": "He frowned and turned away",
        "transliteration": "ʿAbasa wa tawallā",
    },
    {
        "verse_number": "2",
        "arabic_text": "اَن جَآءَهُ اَلْاَعْمٰى",
        "urdu_text": "کہ اس کے پاس ایک نابینا آیا",
        "persian_text": "از آن رو که نابینایی نزد او آمد",
        "english_text": "Because there came to him the blind man",
        "transliteration": "An jā’ahu al-aʿmā",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَمَا يُدْرِيكَ لَعَلَّهُۥ يَزَّكَّىٰٓ",
        "urdu_text": "اور تمہیں کیا خبر شاید وہ پاکیزہ ہو جائے",
        "persian_text": "و تو چه می‌دانی شاید او پاک شود",
        "english_text": "But what would make you perceive that perhaps he might be purified",
        "transliteration": "Wa mā yudrīka laʿallahu yazzakkā",
    },
    {
        "verse_number": "4",
        "arabic_text": "أَوْ يَذَّكَّرُ فَتَنفَعَهُ ٱلذِّكْرٰى",
        "urdu_text": "یا وہ نصیحت حاصل کرے اور نصیحت اس کو فائدہ دے",
        "persian_text": "یا پند گیرد، و پند به او سود رساند",
        "english_text": "Or be reminded and the remembrance would benefit him?",
        "transliteration": "Aw yadhdhakkaru fatanfaʿahu adh-dhikrā",
    },
    {
        "verse_number": "5",
        "arabic_text": "اَمَّا مَنِ اسْتَغْنٰى",
        "urdu_text": "لیکن وہ شخص جو بےپروا ہے",
        "persian_text": "اما آن کسی که خود را بی‌نیاز می‌پندارد",
        "english_text": "As for he who thinks himself without need",
        "transliteration": "Amma mani istaghnā",
    },
    {
        "verse_number": "6",
        "arabic_text": "فَاَنتَ لَهُۥ تَصَدَّى",
        "urdu_text": "آپ اسکی فکر میں لگے ہوے ہیں",
        "persian_text": "تو به او روی می‌آوری",
        "english_text": "To him you give attention",
        "transliteration": "Fa anta lahu taṣaddā",
    },
    {
        "verse_number": "7",
        "arabic_text": "وَمَا عَلَيْكَ اَلَّا يَزَّكَّىٰ",
        "urdu_text": "حلانکے آپ پر کوئی ذمیہ داری نہین ہے اگر وہ پاکیزہ نہ بھی بنے",
        "persian_text": "در حالی‌که بر تو نیست اگر او پاک نشود",
        "english_text": "Though there is no blame on you if he will not be purified",
        "transliteration": "Wa mā ʿalayka allā yazzakkā",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَاَمَّا مَن جَآءَكَ يَسْعَىٰ",
        "urdu_text": "اور جو تمہارے پاس دوڑتا ہوا آیا",
        "persian_text": "اما آن کسی که با شتاب به سوی تو آمد",
        "english_text": "But as for he who came to you striving",
        "transliteration": "Wa ammā man jā’aka yasʿā",
    },
    {
        "verse_number": "9",
        "arabic_text": "وَهُوَ يَخْشٰى",
        "urdu_text": "اور وہ ڈر بھی رہا تھا",
        "persian_text": "در حالی که می‌ترسید",
        "english_text": "While he fears [Allah]",
        "transliteration": "Wa huwa yakhshā",
    },
    {
        "verse_number": "10",
        "arabic_text": "فَاَنتَ عَنْهُ تَلَهّٰى",
        "urdu_text": "تو اس سے بےرخی برتتا ہے",
        "persian_text": "تو از او روی گردان هستی",
        "english_text": "From him you are distracted",
        "transliteration": "Fa anta ʿanhu talahhā",
    },
    {
        "verse_number": "11",
        "arabic_text": "كَلَّآ إِنَّهَا تَذْكِرَةٌ",
        "urdu_text": "یقیناً یہ قرآن ایک نصیحت ہے",
        "persian_text": "چنین نیست، بی‌گمان آن پندی است",
        "english_text": "No! Indeed, it is a reminder",
        "transliteration": "Kallā innahā tadhkirah",
    },
    {
        "verse_number": "12",
        "arabic_text": "فَمَن شَآءَ ذَكَرَهُۥ",
        "urdu_text": "جسکا جی چاہے قبول کر لے",
        "persian_text": "پس هر که خواهد آن را یاد کند",
        "english_text": "So whoever wills may remember it",
        "transliteration": "Faman shā’a dhakarah",
    },
    {
        "verse_number": "13",
        "arabic_text": "فِى صُحُفٍۢ مُّكَرَّمَةٍ",
        "urdu_text": "یہ معزز صحیفوں میں ہے",
        "persian_text": "در صحیفه‌هایی گرامی‌شده است",
        "english_text": "In honored sheets",
        "transliteration": "Fī ṣuḥufin mukarramah",
    },
    {
        "verse_number": "14",
        "arabic_text": "مَّرْفُوعَةٍۢ مُّطَهَّرَةٍۢ",
        "urdu_text": "جو بلند مرتبہ اور پاکیزہ ہیں",
        "persian_text": "بلند مرتبه و پاکیزه‌اند",
        "english_text": "Exalted and purified",
        "transliteration": "Marfūʿatin muṭahharah",
    },
    {
        "verse_number": "15",
        "arabic_text": "بِاَيْدِى سَفَرَةٍ",
        "urdu_text": "لکھنے والوں کے ہاتھوں میں ہیں",
        "persian_text": "به دست سفیرانی (فرشتگان)",
        "english_text": "Carried by the hands of messenger-angels",
        "transliteration": "Bi-aydī safarah",
    },
    {
        "verse_number": "16",
        "arabic_text": "كِرَامٍۢ بَرَرَةٍ",
        "urdu_text": "جو نیک اور باعزت ہیں",
        "persian_text": "نیکوکار و گرامی‌اند",
        "english_text": "Noble and righteous",
        "transliteration": "Kirāmin bararah",
    },
    {
        "verse_number": "17",
        "arabic_text": "قُتِلَ الْاِنسَانُ مَآ اَكْفَرَهُۥ",
        "urdu_text": "انسان اس بات سے مرا گیا کہ کس قدر ناشکرا ہو گیا ",
        "persian_text": "مرگ بر انسان! چه بسیار ناسپاس است",
        "english_text": "Cursed is man; how disbelieving is he!",
        "transliteration": "Qutila al-insānu mā akfarah",
    },
    {
        "verse_number": "18",
        "arabic_text": "مِنْ أَىِّ شَىْءٍ خَلَقَهُۥ",
        "urdu_text": "کس چیز سے اسے پیدا کیا؟",
        "persian_text": "از چه چیز او را آفرید؟",
        "english_text": "From what thing did He create him?",
        "transliteration": "Min ayyī shay’in khalaqah",
    },
    {
        "verse_number": "19",
        "arabic_text": "مِن نُّطْفَةٍ خَلَقَهُۥ فَقَدَّرَهُۥ",
        "urdu_text": "نطفہ سے اسے پیدا کیا، پھر اس کا اندازہ مقرر کیا",
        "persian_text": "او را از نطفه آفرید و اندازه‌اش را تعیین کرد",
        "english_text": "From a sperm-drop He created him and destined for him",
        "transliteration": "Min nuṭfatin khalaqahu faqaddarah",
    },
    {
        "verse_number": "20",
        "arabic_text": "ثُمَّ ٱلسَّبِيلَ يَسَّرَهُۥ",
        "urdu_text": "پھر اس کے لیے راستہ آسان کیا",
        "persian_text": "سپس راه را برای او آسان ساخت",
        "english_text": "Then He eased the way for him",
        "transliteration": "Thumma as-sabīla yassarah",
    },
    {
        "verse_number": "21",
        "arabic_text": "ثُمَّ اَمَاتَهُۥ فَاَقْبَرَهُۥ",
        "urdu_text": "پھر اسے موت دی اور قبر میں ڈالا",
        "persian_text": "سپس او را میراند و در گورش نهاد",
        "english_text": "Then He causes his death and provides a grave for him",
        "transliteration": "Thumma amātahu faaqbarah",
    },
    {
        "verse_number": "22",
        "arabic_text": "ثُمَّ اِذَا شَآءَ اَنشَرَهُۥ",
        "urdu_text": "پھر جب چاہے اسے دوبارہ زندہ کرے گا",
        "persian_text": "سپس هر گاه بخواهد او را زنده می‌گرداند",
        "english_text": "Then when He wills, He will resurrect him",
        "transliteration": "Thumma idhā shā’a ansharah",
    },
    {
        "verse_number": "23",
        "arabic_text": "كَلَّا لَمَّا يَقْضِ مَآ اَمَرَهُۥ",
        "urdu_text": "ہرگز نہیں، اس نے اسنے حکم خدا کو بلکل پورا نہیں کیا ہے",
        "persian_text": "نه، او هنوز آنچه را که مأمور شده انجام نداده",
        "english_text": "No! He has not yet accomplished what He commanded him",
        "transliteration": "Kallā lammā yaqḍi mā amarah",
    },
    {
        "verse_number": "24",
        "arabic_text": "فَلْيَنظُرِ الْاِنسَانُ اِلٰى طَعَامِهِۦٓ",
        "urdu_text": "پس انسان اپنے کھانے کی طرف دیکھے",
        "persian_text": "پس انسان باید به خوراک خود بنگرد",
        "english_text": "Then let man look at his food",
        "transliteration": "Falyanẓuril-insānu ilā ṭaʿāmih",
    },
    {
        "verse_number": "25",
        "arabic_text": "اَنَّا صَبَبْنَا الْمَآءَ صَبًّۭا",
        "urdu_text": "ہم نے خوب پانی برسایا",
        "persian_text": "ما آب را با شدت فرو ریختیم",
        "english_text": "We poured down water in abundance",
        "transliteration": "Annā ṣababnā al-mā’a ṣabbā",
    },
    {
        "verse_number": "26",
        "arabic_text": "ثُمَّ شَقَقْنَا اَلْأَرْضَ شَقًّا",
        "urdu_text": "پھر زمین کو اچھی طرح چیر دیا",
        "persian_text": "سپس زمین را شکافتیم",
        "english_text": "Then We split the earth in clefts",
        "transliteration": "Thumma shaqqaqnā al-arḍa shaqqā",
    },
    {
        "verse_number": "27",
        "arabic_text": "فَاَنۢبَتْنَا فِيهَا حَبًّا",
        "urdu_text": "پھر اس میں اناج اگایا",
        "persian_text": "و در آن دانه‌ها رویاندیم",
        "english_text": "And caused to grow within it grain",
        "transliteration": "Fa-anbatnā fīhā ḥabbā",
    },
    {
        "verse_number": "28",
        "arabic_text": "وَّ عِنَبًا وَقَضْبًا",
        "urdu_text": "اور انگور اور ترکاری",
        "persian_text": "و انگور و سبزی‌ها",
        "english_text": "And grapes and herbage",
        "transliteration": "Wa ʿinaban wa qaḍbā",
    },
    {
        "verse_number": "29",
        "arabic_text": "وَّ زَيْتُونًا وَّنَخْلًا",
        "urdu_text": "اور زیتون اور کھجوریں",
        "persian_text": "و زیتون و خرما",
        "english_text": "And olives and palm trees",
        "transliteration": "Wa zaytūnan wa nakhlā",
    },
    {
        "verse_number": "30",
        "arabic_text": "وَّحَدَآئِقَ غُلْبًا",
        "urdu_text": "اور گھنے باغات",
        "persian_text": "و باغ‌هایی پر از درختان انبوه",
        "english_text": "And gardens of dense shrubbery",
        "transliteration": "Wa ḥadā’iq ghalbā",
    },
    {
        "verse_number": "31",
        "arabic_text": "وَّ فَاكِهَةً وَّ اَبًّا",
        "urdu_text": "اور میوے اور چارہ",
        "persian_text": "و میوه‌ها و علف‌ها",
        "english_text": "And fruits and grass",
        "transliteration": "Wa fākihatan wa abbā",
    },
    {
        "verse_number": "32",
        "arabic_text": "مَّتاعًا لَّكُمْ وَ لِاَنْعَامِكُمْ",
        "urdu_text": "تمہارے اور تمہارے چوپایوں کے فائدے کے لیے",
        "persian_text": "برای بهره شما و چارپایانتان",
        "english_text": "As enjoyment for you and your livestock",
        "transliteration": "Matāʿan lakum wa li-anʿāamikum",
    },
    {
        "verse_number": "33",
        "arabic_text": "فَاِذَا جَآءَتِ اَلصَّآخَّةُ",
        "urdu_text": "پھر جب کان پھاڑ دینے والی آواز آئے گی",
        "persian_text": "پس زمانی که بانگ گوش‌خراش فرا رسد",
        "english_text": "But when there comes the Deafening Blast (i.e., the Day of Judgement),",
        "transliteration": "Fa-itha jaa'atis-saakhkhah",
    },
    {
        "verse_number": "34",
        "arabic_text": "يَوْمَ يَفِرُّ الْمَرْءُ مِنْ اَخِيهِ",
        "urdu_text": "جس دن آدمی اپنے بھائی سے بھاگے گا",
        "persian_text": "روزی که انسان از برادر خود می‌گریزد",
        "english_text": "The Day when a man will flee from his brother",
        "transliteration": "Yawma yafirru almar'u min akhīh",
    },
    {
        "verse_number": "35",
        "arabic_text": "وَاُمِّهِۦ وَاَبِيهِ",
        "urdu_text": "اور اپنی ماں اور اپنے باپ سے",
        "persian_text": "و از مادر و پدرش می‌گریزد",
        "english_text": "And from his mother and his father",
        "transliteration": "Wa ummihi wa abīh",
    },
    {
        "verse_number": "36",
        "arabic_text": "وَصَاحِبَتِهِۦ وَبَنِيهِ",
        "urdu_text": "اور اپنی بیوی اور اپنی اولاد سے",
        "persian_text": "و از همسر و فرزندانش می‌گریزد",
        "english_text": "And from his wife and his children",
        "transliteration": "Wa sāhibatihi wa banīh",
    },
    {
        "verse_number": "37",
        "arabic_text": "لِكُلِّ ٱمْرِىً مِّنْهُمْ يَوْمَئِذٍ شَانٌ يُغْنِيهِ",
        "urdu_text": "اس دن ہر آدمی کے لئے ایک خاص فکر ہوگی جو اسکے لئے کافی ہوگی",
        "persian_text": "هر کسی از آن‌ها آن روز کاری دارد که او را به خود مشغول می‌دارد",
        "english_text": "Every man, that Day, will have enough to make him careless of others",
        "transliteration": "Likulli imri’im minhum yawma’idhin sha’nun yughnih",
    },
    {
        "verse_number": "38",
        "arabic_text": "وُجُوهٌ يَّوْمَئِذٍ مُّسْفِرَةٌ",
        "urdu_text": "اس دن کچھ چہرے روشن ہوں گے",
        "persian_text": "در آن روز، چهره‌هایی تابناک خواهند بود",
        "english_text": "Some faces, that Day, will be bright",
        "transliteration": "Wujūhun yawma’idhin musfirah",
    },
    {
        "verse_number": "39",
        "arabic_text": "ضَاحِكَةٌ مُّسْتَبْشِرَةٌ",
        "urdu_text": "ہنستے ہوئے، خوشیاں مناتے ہوئے",
        "persian_text": "خندان و شادمان",
        "english_text": "Laughing, rejoicing at good news",
        "transliteration": "Ḍāḥikatun mustabshirāh",
    },
    {
        "verse_number": "40",
        "arabic_text": "وَوُجُوهٌ يَوْمَئِذٍ عَلَيْهَا غَبَرَةٌ",
        "urdu_text": "اور کچھ چہرے اس دن گرد آلود ہوں گے",
        "persian_text": "و چهره‌هایی در آن روز غبارآلود",
        "english_text": "And other faces, that Day, will have upon them dust",
        "transliteration": "Wa wujūhun yawma’idhin ʿalayhā ghabarah",
    },
    {
        "verse_number": "41",
        "arabic_text": "تَرْهَقُهَا قَتَرَةٌ",
        "urdu_text": "ان پر ذلّت چھایی ہوئی ہوگی",
        "persian_text": "تاریکی آن‌ها را خواهد پوشاند",
        "english_text": "Blackness will cover them",
        "transliteration": "Tarhaquhā qatarah",
    },
    {
        "verse_number": "42",
        "arabic_text": "اَولٰٓئِكَ هُمُ الْكَفَرَةُ الْفَجَرَةُ",
        "urdu_text": "یہ لوگ حقیقتاً کافر اور فاجر ہوں گے",
        "persian_text": "آنان کافران گناهکارند",
        "english_text": "Those are the disbelievers, the wicked ones",
        "transliteration": "Ūlā’ika humul-kafarah al-fajarah",
    },
]
