ayats = [
    {
        "verse_number": "1",
        "arabic_text": "يَسْئَلُونَكَ عَنِ الْاَنْفَالِ قُلِ الْاَنْفَالُ لِلّٰهِ وَ الرَّسُوْلِ فَاتَّقُوْا اللّٰهَ وَ اَصْلِحُوا ذَاتَ بَيْنِكُمْ وَ اَطِيْعُوا اللّٰهَ وَ رَسُولَهُ اِنْ كُنْتُم مُّؤْمِنِيْنَ",
        "urdu_text": "تجھ سے غنیمتوں کے بارے میں پوچھتے ہیں۔ کہہ دے: غنیمتیں اللہ اور رسول کے لئے ہیں۔ پس اللہ سے ڈرو اور آپس میں صلح کر لو اور اللہ اور اس کے رسول کی اطاعت کرو اگر تم ایمان والے ہو۔ ",
        "persian_text": "از تو دربارهٔ انفال (غنائم) مى‌پرسند، بگو: انفال از آنِ خدا و پیامبر است؛ پس از خدا پروا دارید و میان خود اصلاح کنید و از خدا و پیامبرش اطاعت نمایید اگر مؤمن هستید.",
        "english_text": "They ask you about the bounties (of war). Say, 'The bounties belong to Allah and the Messenger.' So fear Allah and set things right among yourselves and obey Allah and His Messenger, if you are believers.",
        "transliteration": "Yas’aloona ka 'anil anfaali qulil anfaalu lillaahi war Rasool; fattaqul laaha wa aslihoo zaata bainikum wa atee'ul laaha wa Rasoolahoo in kuntum mu'mineen.",
    },
    {
        "verse_number": "2",
        "arabic_text": "اِنَّمَا الْمُؤْمِنُونَ الَّذِينَ اِذَا ذُكِرَ اللّٰهُ وَجِلَتْ قُلُوْبُهُمْ وَ اِذَا تُلِيَتْ عَلَيْهِمْ اٰيٰتُهُ زَادَتْهُمْ اِيمَانًا وَّ عَلٰى رَبِّهِمْ يَتَوَكَّلُوْنَ",
        "urdu_text": "ایمان والے تو وہی ہیں کہ جب اللہ کا ذکر کیا جائے تو ان کے دل ڈر جاتے ہیں اور جب ان پر اس کی آیات تلاوت کی جاتی ہیں تو ان کا ایمان بڑھ جاتا ہے اور وہ اپنے رب پر بھروسہ کرتے ہیں۔ ",
        "persian_text": "مؤمنان تنها کسانى‌اند که چون نام خدا برده شود دل‌هایشان ترسان شود و چون آیات او بر آنان خوانده شود ایمانشان افزون گردد و بر پروردگارشان توکل کنند.",
        "english_text": "The believers are only those who, when Allah is mentioned, their hearts tremble, and when His verses are recited to them, it increases them in faith; and upon their Lord they rely.",
        "transliteration": "Innamal mu'minoonal lazeena izaa zukirallaahu wajilat quloobuhum wa izaa tuliyat 'alaihim aayaatuhoo zaadathum eemaananw-wa 'alaaa rabbihim yatawakkaloon.",
    },
    {
        "verse_number": "3",
        "arabic_text": "الَّذِيْنَ يُقِيمُوْنَ الصَّلٰوةَ وَ مِمَّا رَزَقْنٰهُمْ يُنْفِقُونَ",
        "urdu_text": "جو نماز قائم کرتے ہیں اور جو کچھ ہم نے انہیں دیا ہے اس میں سے خرچ کرتے ہیں۔ ",
        "persian_text": "همانان که نماز را برپا مى‌دارند و از آنچه به ایشان روزى داده‌ایم انفاق مى‌کنند.",
        "english_text": "Those who establish prayer and spend from what We have provided them.",
        "transliteration": "Allazeena yuqeemoona as Salaata wa mimmaa razaqnaahum yunfiqoon.",
    },
    {
        "verse_number": "4",
        "arabic_text": "اُوْلٰٓئِكَ هُمُ الْمُؤْمِنُوْنَ حَقًّا ۚ لَّهُمْ دَرَجٰتٌ عِنْدَ رَبِّهِمْ وَ مَغْفِرَةٌ وَّ رِزْقٌ كَرِيْمٌ",
        "urdu_text": "یہی لوگ حقیقی مومن ہیں۔ ان کے لئے ان کے رب کے پاس درجے ہیں اور بخشش ہے اور عزت کی روزی ہے۔ ",
        "persian_text": "آنان همان مؤمنان راستین‌اند. برایشان نزد پروردگارشان درجاتى است و آمرزشى و روزىِ بزرگوارانه.",
        "english_text": "It is they who are the true believers. For them are degrees with their Lord, forgiveness, and a noble provision.",
        "transliteration": "Ulaaa'ika humul mu'minoona haqqaa; lahum darajaatun 'inda rabbihim wa maghfiratunw-wa rizqun kareem.",
    },
    {
        "verse_number": "5",
        "arabic_text": "كَمَآ اَخْرَجَكَ رَبُّكَ مِن بَيْتِكَ بِالْحَقِّ وَ اِنَّ فَرِيْقًا مِّنَ الْمُؤْمِنِيْنَ لَكٰرِهُوْنَ",
        "urdu_text": "جیسے تیرا رب تجھے حق کے ساتھ تیرے گھر سے نکال لایا حالانکہ مومنوں کی ایک جماعت ناخوش تھی۔ ان علی)",
        "persian_text": "چنان‌که پروردگارت تو را به حق از خانه‌ات بیرون آورد، در حالى که گروهى از مؤمنان ناخشنود بودند.",
        "english_text": "It is just as when your Lord brought you out of your home in truth, while indeed, a party among the believers disliked it.",
        "transliteration": "Kamaa akhrajaka rabbuka min baita bilhaqqi wa inna fareeqam minal mu'mineena lakaarihoon.",
    },
    {
        "verse_number": "6",
        "arabic_text": "يُجَادِلُوْنَكَ فِى الْحَقِّ بَعْدَمَا تَبَيَّنَ كَاَنَّمَا يُسَاقُونَ اِلَى الْمَوْتِ وَ هُمْ يَنْظُرُوْنَ",
        "urdu_text": "وہ تجھ سے حق کے بارے میں جھگڑتے تھے بعد اس کے کہ وہ ظاہر ہو چکا تھا گویا کہ وہ موت کی طرف ہانکے جا رہے ہیں اور وہ اسے دیکھ رہے ہیں۔ ",
        "persian_text": "پس از آنکه حق بر آنان روشن شد، درباره آن با تو به جدال مى‌پرداختند، گویى که آنان را به سوى مرگ مى‌رانند و به آن مى‌نگرند.",
        "english_text": "They disputed with you concerning the truth after it had become clear, as if they were being driven toward death while they looked on.",
        "transliteration": "Yujaadiloona ka fil haqqi ba'da maa tabayyana ka annamaa yusaaqoona ilal mawti wa hum yanzuroon.",
    },
    {
        "verse_number": "7",
        "arabic_text": "وَ اِذْ يَعِدُكُمُ اللّٰهُ اِحْدَى الطَّآئِفَتَيْنِ اَنَّهَا لَكُمْ وَ تَوَدُّوْنَ اَنَّ غَيْرَ ذَاتِ الشَّوْكَةِ تَكُونُ لَكُمْ وَ يُرِيْدُ اللّٰهُ اَنْ يُّحِقَّ الْحَقَّ بِكَلِمٰتِهِ وَ يَقْطَعَ دَابِرَ الْكٰفِرِيْنَ",
        "urdu_text": "اور جب اللہ تم سے وعدہ کرتا تھا کہ دو گروہوں میں سے ایک تمہارے لئے ہے اور تم چاہتے تھے کہ غیر مسلح گروہ تمہارے لئے ہو، اور اللہ چاہتا تھا کہ اپنے کلمات سے حق کو ثابت کرے اور کافروں کی جڑ کاٹ دے۔ ",
        "persian_text": "و آن‌گاه که خداوند به شما وعده داد که یکى از دو گروه از آنِ شما خواهد بود و شما مى‌خواستید آن بى‌سلاح از آنِ شما باشد، و خدا مى‌خواست حق را به کلمات خود پایدار سازد و ریشه کافران را برکند.",
        "english_text": "And [remember] when Allah promised you one of the two groups would be yours, and you wished that the unarmed one would be yours. But Allah intended to establish the truth by His words and eliminate the disbelievers.",
        "transliteration": "Wa iz ya'idukumullaahu ihdaat taaa'ifatai annahaa lakum; wa tawaddoona anna ghaira zaatish shawkati takoonu lakum wa yureedullaahu an yuhiqqal haqq bi kalimaatihee wa yaqta'a daabiral kaafireen.",
    },
    {
        "verse_number": "8",
        "arabic_text": "لِيُحِقَّ الْحَقَّ وَ يُبْطِلَ الْبَاطِلَ وَ لَوْ كَرِهَ الْمُجْرِمُوْنَ",
        "urdu_text": "تاکہ اللہ حق کو ثابت کرے اور باطل کو مٹا دے، اگرچہ مجرموں کو ناگوار ہو۔ ",
        "persian_text": "تا حق را پایدار سازد و باطل را نابود کند، هر چند گناهکاران کراهت داشته باشند.",
        "english_text": "That He should establish the truth and abolish falsehood, even if the criminals disliked it.",
        "transliteration": "Liyuhiqqal haqq wa yubtilal baatila wa law karihal mujrimoon.",
    },
    {
        "verse_number": "9",
        "arabic_text": "اِذْ تَسْتَغِيْثُوْنَ رَبَّكُمْ فَاسْتَجَابَ لَكُمْ اَنِّى مُمِدُّكُمْ بِاَلْفٍۢ مِّنَ الْمَلٰٓئِكَةِ مُرْدِفِيْنَ",
        "urdu_text": "جب تم اپنے رب سے فریاد کرتے تھے تو اس نے تمہاری فریاد سن لی کہ میں تمہاری مدد ایک ہزار فرشتوں سے کروں گا جو ایک کے پیچھے ایک آئیں گے۔",
        "persian_text": "آن‌گاه که از پروردگارتان یارى مى‌خواستید و او به شما پاسخ داد که من شما را با هزار فرشته پیاپى یارى خواهم کرد.",
        "english_text": "When you sought help from your Lord, He answered you, 'Indeed, I will reinforce you with a thousand angels following one another.'",
        "transliteration": "Iz tastagheethoona rabbakum fastajaaba lakum annee mumiddukum bi alfin minal malaaa'ikati murdifeen.",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَ مَا جَعَلَهُ اللّٰهُ اِلَّا بُشْرٰى وَ لِتَطْمَئِنَّ بِهِ قُلُوْبُكُمْ ۚ وَ مَا النَّصْرُ اِلَّا مِنْ عِنْدِ اللّٰهِ ۚ اِنَّ اللّٰهَ عَزِيْزٌ حَكِيْمٌ",
        "urdu_text": "اور اللہ نے یہ مدد صرف خوشخبری کے طور پر رکھی اور تاکہ اس سے تمہارے دلوں کو اطمینان ہو جائے، اور مدد تو اللہ ہی کی طرف سے ہے۔ بے شک اللہ غالب حکمت والا ہے۔",
        "persian_text": "و خدا آن را جز بشارتى قرار نداد تا دل‌هایتان بدان آرام گیرد، و پیروزى جز از جانب خدا نیست؛ بى‌گمان خدا شکست‌ناپذیر و حکیم است.",
        "english_text": "And Allah made it not except as good tidings and so that your hearts would be assured thereby. And victory is not but from Allah. Indeed, Allah is Exalted in Might and Wise.",
        "transliteration": "Wa maa ja'alahullaahu illaa bushraa wa litatma'inna bihee quloobukum; wa man-nasru illaa min 'indillaah; innal laaha 'azeezun hakeem.",
    },
    {
        "verse_number": "11",
        "arabic_text": "اِذْ يُغَشِّيْكُمُ النُّعَاسَ اَمَنَةً مِّنْهُ وَ يُنَزِّلُ عَلَيْكُمْ مِّنَ السَّمَآءِ مَآءً لِّيُطَهِّرَكُم بِهِ وَ يُذْهِبَ عَنْكُمْ رِجْزَ الشَّيْطٰنِ وَ لِيَرْبِطَ عَلٰى قُلُوبِكُمْ وَ يُثَبِّتَ بِهِ الْاَقْدَامَ",
        "urdu_text": "جب وہ تم پر نیند غالب کر رہا تھا جو تمہارے لئے اس کی طرف سے امن تھی اور تم پر آسمان سے پانی اتار رہا تھا تاکہ اس کے ذریعے تمہیں پاک کرے اور تم سے شیطان کی گندگی کو دور کرے اور تمہارے دلوں کو مضبوط کرے اور اس سے تمہارے قدموں کو ثبات عطا کرے۔ ",
        "persian_text": "آن‌گاه که خواب سبکى را براى آرامش از جانب خود بر شما مستولى کرد، و از آسمان آبى بر شما فرو فرستاد تا شما را با آن پاکیزه سازد و پلیدى شیطان را از شما ببرد و دل‌هایتان را محکم گرداند و گام‌هایتان را استوار کند.",
        "english_text": "When He overwhelmed you with drowsiness [giving] security from Him and sent down upon you from the sky rain by which to purify you and remove from you the evil of Satan and to make steadfast your hearts and plant firmly your feet.",
        "transliteration": "Iz yughashsheekumun nu'aasa amanatan minhu wa yunazzilu 'alaikum minas samaaa'i maaa'al liyutahhirakum bihee wa yuzhiba 'ankum rijzash shaitaani wa liyarbita 'ala quloobikum wa yusabbita bihil aqdaam.",
    },
    {
        "verse_number": "12",
        "arabic_text": "اِذْ يُوْحِى رَبُّكَ اِلَى الْمَلٰٓئِكَةِ اَنِّى مَعَكُمْ فَثَبِّتُوْا الَّذِيْنَ اٰمَنُوا ۚ سَاُلْقِى فِى قُلُوْبِ الَّذِيْنَ كَفَرُوْا الرُّعْبَ فَاضْرِبُوا فَوْقَ الْاَعْنَاقِ وَ اضْرِبُوا مِنْهُمْ كُلَّ بَنَانٍ",
        "urdu_text": "جب تیرا رب فرشتوں کو وحی کر رہا تھا کہ میں تمہارے ساتھ ہوں، پس ایمان والوں کو ثابت قدم رکھو۔ میں کافروں کے دلوں میں رعب ڈالوں گا، تو تم ان کی گردنوں پر مارو اور ان کی ہر ایک انگلی کے پور پور پر ضرب لگاؤ۔ ",
        "persian_text": "و هنگامى که پروردگارت به فرشتگان وحى فرستاد: من با شما هستم، پس کسانى را که ایمان آوردند استوار دارید. به زودى در دل‌هاى کافران رعب مى‌افکنم، پس بر گردن‌ها بزنید و از آنان هر انگشتى را قطع کنید.",
        "english_text": "When your Lord revealed to the angels, 'I am with you, so strengthen those who have believed. I will cast terror into the hearts of those who disbelieved, so strike [them] upon the necks and strike from them every fingertip.'",
        "transliteration": "Iz yoohee rabbuka ilal malaaa'ikati annee ma'akum fasabbitul lazeena aamanoo; sa-ulqee fee quloobil lazeena kafarur ru'ba fazriboo fawqal a'naaqi wadriboo minhum kulla banaan.",
    },
    {
        "verse_number": "13",
        "arabic_text": "ذٰلِكَ بِاَنَّهُمْ شَآقُّوْا اللّٰهَ وَ رَسُوْلَهُ ۚ وَ مَنْ يُّشَاقِقِ اللّٰهَ وَ رَسُوْلَهُ فَاِنَّ اللّٰهَ شَدِيْدُ الْعِقَابِ",
        "urdu_text": "یہ اس وجہ سے ہے کہ انہوں نے اللہ اور اس کے رسول کی مخالفت کی، اور جو کوئی اللہ اور اس کے رسول کی مخالفت کرے تو بے شک اللہ سخت عذاب دینے والا ہے۔ ",
        "persian_text": "این بدان سبب است که آنان با خدا و پیامبرش دشمنى کردند؛ و هر که با خدا و پیامبرش دشمنى کند، بى‌گمان خدا سخت‌کیفر است.",
        "english_text": "That is because they opposed Allah and His Messenger. And whoever opposes Allah and His Messenger - indeed, Allah is severe in penalty.",
        "transliteration": "Zaalika bi-annahum shaaqqul laaha wa rasoolah; wa mai yushaaqqil laaha wa rasoolahoo fa innal laaha shadeedul 'iqaab.",
    },
    {
        "verse_number": "14",
        "arabic_text": "ذٰلِكُمْ فَذُوْقُوْهُ وَ اَنَّ لِلْكٰفِرِيْنَ عَذَابَ النَّارِ",
        "urdu_text": "یہ ہے (ان کا انجام) پس اسے چکھو اور بے شک کافروں کے لئے آگ کا عذاب ہے۔ (ترجمہ: حافظ سید فرمان علی)",
        "persian_text": "این است [کیفرشان] پس آن را بچشید، و همانا براى کافران عذاب آتش است.",
        "english_text": "That [is yours], so taste it. And indeed for the disbelievers is the punishment of the Fire.",
        "transliteration": "Zaalikum fazooqoohu wa annalil kaafireena 'azaaban naar.",
    },
    {
        "verse_number": "15",
        "arabic_text": "يٰٓاَيُّهَا الَّذِيْنَ اٰمَنُوٓا اِذَا لَقِيْتُمُ الَّذِيْنَ كَفَرُوْا زَحْفًا فَلَا تُوَلُّوْهُمُ الْاَدْبارَ",
        "urdu_text": "اے ایمان والو! جب تم کافروں سے جنگ میں ملو تو ان سے پیٹھ نہ پھیرنا۔ ",
        "persian_text": "اى کسانى که ایمان آورده‌اید! هنگامى که با کافران در میدان نبرد روبه‌رو شدید، به آنان پشت نکنید.",
        "english_text": "O you who have believed, when you meet those who disbelieve advancing [for battle], do not turn to them your backs.",
        "transliteration": "Yaaa ayyuhal lazeena aamanooo izaa laqeetumul lazeena kafaroo zahfan falaa tuwalloohumul adbaar.",
    },
    {
        "verse_number": "16",
        "arabic_text": "وَ مَنْ يُّوَلِّهِمْ يَوْمَئِذٍ دُبُرَهُٓ اِلَّا مُتَحَرِّفًا لِّقِتَالٍ اَوْ مُتَحَيِّزًا اِلٰى فِئَةٍ فَقَدْ بَآءَ بِغَضَبٍ مِّنَ اللّٰهِ وَ مَاْوٰهُ جَهَنَّمُ وَ بِئْسَ الْمَصِيْرُ",
        "urdu_text": "اور جو کوئی اس دن ان کو پیٹھ دکھائے گا مگر یہ کہ لڑائی میں ہٹ کر لڑنے کے لئے ہو یا کسی جماعت کی طرف جانے کے لئے، تو وہ اللہ کے غضب کے ساتھ پلٹا، اور اس کا ٹھکانا جہنم ہے، اور وہ بہت برا ٹھکانا ہے۔ ",
        "persian_text": "و هر کس در آن روز به آنان پشت کند، مگر آنکه براى نبرد کناره‌جویى کند یا به سوى گروهى رود، به خشم خدا بازگشته است و جایگاهش دوزخ است، و چه بد سرانجامى است.",
        "english_text": "And whoever turns his back to them on such a day - unless swerving [as a strategy] for war or joining [another] company - has certainly returned with anger from Allah, and his refuge is Hell - and wretched is the destination.",
        "transliteration": "Wa mai yuwallihim yawma-izinduburahooo illaa mutaharrifan liqitaal aw mutahaiyizan ilaa fi'atin faqad baaa'a bighadabin minal laahi wa maawaahu jahannam; wa bi'sal maseer.",
    },
    {
        "verse_number": "17",
        "arabic_text": "فَلَمْ تَقْتُلُوْهُمْ وَ لٰكِنَّ اللّٰهَ قَتَلَهُمْ ۚ وَ مَا رَمَيْتَ اِذْ رَمَيْتَ وَ لٰكِنَّ اللّٰهَ رَمٰى ۚ وَ لِيُبْلِىَ الْمُؤْمِنِيْنَ مِنْهُ بَلَآءً حَسَنًا ۚ اِنَّ اللّٰهَ سَمِيْعٌ عَلِيْمٌ",
        "urdu_text": "پس تم نے ان کو قتل نہیں کیا بلکہ اللہ نے ان کو قتل کیا، اور اے نبی آپنے سنگریزے نہیں پھینکے بلکی خدا نے پھینکے، تاکہ وہ ایمان والوں کو اپنی طرف سے اچھا امتحان دے، بے شک اللہ سننے والا جاننے والا ہے۔ ",
        "persian_text": "پس شما آنان را نکشتید، بلکه خدا آنان را کشت. و تو [اى پیامبر] هنگامى که افکندى، نیفکندى، بلکه خدا افکند، تا مؤمنان را به آزمایشى نیکو بیازماید. به راستى خدا شنواى داناست.",
        "english_text": "And you did not kill them, but it was Allah who killed them. And you threw not when you threw, but it was Allah who threw that He might test the believers with a good test. Indeed, Allah is Hearing and Knowing.",
        "transliteration": "Falam taqtuloohum wa laakinnal laaha qatalahum; wa maa ramayta iz ramaita wa laakinnal laaha ramaa; wa liyubliyal mu'mineena minhu balaa'an hasanaa; innal laaha samee'un 'aleem.",
    },
    {
        "verse_number": "18",
        "arabic_text": "ذٰلِكُمْ وَ اَنَّ اللّٰهَ مُوْهِنُ كَيْدِ الْكٰفِرِيْنَ",
        "urdu_text": "یہ (سب کچھ ہوا) اور بے شک اللہ کافروں کی تدبیر کو کمزور کرنے والا ہے۔ ",
        "persian_text": "این است [کار خدا] و بى‌گمان خدا مکر کافران را سست‌کننده است.",
        "english_text": "That [is so], and [also] that Allah will weaken the plot of the disbelievers.",
        "transliteration": "Zaalikum wa annal laaha muwhinu kaidil kaafireen.",
    },
    {
        "verse_number": "19",
        "arabic_text": "اِنْ تَسْتَفْتِحُوا فَقَدْ جَآءَكُمُ الْفَتْحُ وَ اِنْ تَنْتَهُوْا فَهُوَ خَيْرٌ لَّكُمْ وَ اِنْ تَعُوْدُوْا نَعُدْ وَ لَنْ تُغْنِىَ عَنْكُمْ فِئَتُكُمْ شَيْئًا وَّ لَوْ كَثُرَتْ وَ اَنَّ اللّٰهَ مَعَ الْمُؤْمِنِيْنَ",
        "urdu_text": "اگر تم فیصلہ چاہتے ہو تو فیصلہ تمہارے پاس آ گیا، اور اگر تم باز آ جاؤ تو یہ تمہارے لئے بہتر ہے، اور اگر تم پھر لوٹو گے تو ہم بھی لوٹیں گے، اور تمہارا گروہ تمہیں کچھ فائدہ نہیں دے گا خواہ وہ زیادہ ہی ہو، اور بے شک اللہ ایمان والوں کے ساتھ ہے۔ ",
        "persian_text": "اگر فتح مى‌خواستید، پس فتح براى شما آمد. و اگر باز ایستید، آن براى شما بهتر است. و اگر بازگردید، ما نیز باز مى‌گردیم، و گروه شما هر چند بسیار باشد، چیزى از شما بازنخواهد داشت. و بى‌گمان خدا با مؤمنان است.",
        "english_text": "If you [disbelievers] seek the decision - the decision has come to you. And if you desist, it is better for you; but if you return, We will return. And never will your [forces] avail you, however numerous they may be. And that Allah is with the believers.",
        "transliteration": "In tastaftehoo faqad jaaa'akumul fath; wa in tantahoo fahuwa khairul lakum; wa in ta'oodoo na'ud; wa lan tughniya 'ankum fi'atukum shai'anw-wa law kasurat; wa annal laaha ma'al mu'mineen.",
    },
    {
        "verse_number": "20",
        "arabic_text": "يٰٓاَيُّهَا الَّذِيْنَ اٰمَنُوٓا اَطِيْعُوا اللّٰهَ وَ رَسُولَهُ وَ لَا تَوَلَّوْا عَنْهُ وَ اَنْتُمْ تَسْمَعُوْنَ",
        "urdu_text": "اے ایمان والو! اللہ اور اس کے رسول کی اطاعت کرو اور اس سے روگردانی نہ کرو حالانکہ تم سنتے ہو۔ ",
        "persian_text": "اى کسانى که ایمان آورده‌اید! خدا و پیامبرش را فرمان برید و از او روى برنتابید در حالى که مى‌شنوید.",
        "english_text": "O you who have believed, obey Allah and His Messenger and do not turn from him while you hear [his order].",
        "transliteration": "Yaaa ayyuhal lazeena aamanoo atee'ul laaha wa rasoolahoo wa laa tawallaw 'anhu wa antum tasma'oon.",
    },
    {
        "verse_number": "21",
        "arabic_text": "وَ لَا تَكُوْنُوْا كَالَّذِيْنَ قَالُوْا سَمِعْنَا وَ هُمْ لَا يَسْمَعُوْنَ",
        "urdu_text": "اور ان لوگوں کی طرح نہ ہو جانا جنہوں نے کہا ہم نے سن لیا حالانکہ وہ سنتے نہیں۔",
        "persian_text": "و چون کسانى مباشید که گفتند: شنیدیم، و حال آنکه آنان نمى‌شنوند.",
        "english_text": "And do not be like those who say, 'We have heard,' while they do not hear.",
        "transliteration": "Wa laa takoonoo kallazeena qaaloo sami'naa wa hum laa yasma'oon.",
    },
    {
        "verse_number": "22",
        "arabic_text": "اِنَّ شَرَّ الدَّوَآبِّ عِنْدَ اللّٰهِ الصُّمُّ الْبُكْمُ الَّذِيْنَ لَا يَعْقِلُوْنَ",
        "urdu_text": "بے شک اللہ کے نزدیک سب جانداروں میں بدترین وہ بہرے، گونگے ہیں جو عقل نہیں رکھتے۔ ",
        "persian_text": "به یقین بدترین جنبندگان نزد خدا کران و گنگانى‌اند که خرد به کار نمى‌گیرند.",
        "english_text": "Indeed, the worst of living creatures in the sight of Allah are the deaf and dumb who do not use reason.",
        "transliteration": "Inna sharrad dawaaabbi 'indal laahis summul bukmul lazeena laa ya'qiloon.",
    },
    {
        "verse_number": "23",
        "arabic_text": "وَ لَوْ عَلِمَ اللّٰهُ فِيْهِمْ خَيْرًا لَّاَسْمَعَهُمْ وَ لَوْ اَسْمَعَهُمْ لَتَوَلَّوْا وَّ هُمْ مُّعْرِضُوْنَ",
        "urdu_text": "اور اگر اللہ ان میں کوئی بھلائی جانتا تو ان کو ضرور سنا دیتا، اور اگر ان کو سنا دیتا تو بھی وہ روگردان ہو کر پلٹ جاتے۔ ",
        "persian_text": "و اگر خدا در آنان خیرى مى‌دانست، هر آینه آنان را شنوا مى‌کرد. و اگر آنان را شنوا مى‌کرد، باز هم روى مى‌گرداندند و آنان اعراض‌کنندگان بودند.",
        "english_text": "Had Allah known any good in them, He would have made them hear. And if He had made them hear, they would still have turned away, while they were refusing.",
        "transliteration": "Wa law 'alimal laahu feehim khairal la asma'ahum; wa law asma'ahum latawallaw wa hum mu'ridoon.",
    },
    {
        "verse_number": "24",
        "arabic_text": "يٰٓاَيُّهَا الَّذِيْنَ اٰمَنُوْا اسْتَجِيْبُوا لِلّٰهِ وَ لِلرَّسُولِ اِذَا دَعَاكُمْ لِمَا يُحْيِيْكُمْ وَ اعْلَمُوْٓا اَنَّ اللّٰهَ يَحُوْلُ بَيْنَ الْمَرْءِ وَ قَلْبِهِ وَ اَنَّهُٓ اِلَيْهِ تُحْشَرُوْنَ",
        "urdu_text": "اے ایمان والو! اللہ اور رسول کی پکار پر لبیک کہو جب وہ تمہیں بلاتا ہے اس چیز کی طرف جو تمہیں زندگی بخشے، اور جان لو کہ اللہ انسان اور اس کے دل کے درمیان حائل ہو جاتا ہے، اور یہ کہ تم سب اسی کی طرف جمع کئے جاؤ گے۔",
        "persian_text": "اى کسانى که ایمان آورده‌اید! دعوت خدا و پیامبر را اجابت کنید هنگامى که شما را به آنچه زندگى مى‌بخشد مى‌خواند. و بدانید که خدا میان آدمى و دل او حایل مى‌شود، و اینکه شما به سوى او گردآورده مى‌شوید.",
        "english_text": "O you who have believed, respond to Allah and to the Messenger when he calls you to that which gives you life. And know that Allah intervenes between a man and his heart and that to Him you will be gathered.",
        "transliteration": "Yaaa ayyuhal lazeena aamanoo istajeeboo lillaahi wa lirrasooli izaa da'aakum limaa yuhyeekum wa'lamooo annal laaha yahoolu bainal mar'i wa qalbihee wa annahooo ilaihi tuhsharoon.",
    },
    {
        "verse_number": "25",
        "arabic_text": "وَ اتَّقُوْا فِتْنَةً لَّا تُصِيْبَنَّ الَّذِيْنَ ظَلَمُوْا مِنْكُمْ خَآصَّةً وَ اعْلَمُوْٓا اَنَّ اللّٰهَ شَدِيْدُ الْعِقَابِ",
        "urdu_text": "اور اس فتنے سے بچو جو تم میں سے صرف ظالموں ہی کو نہیں پہنچے گا، اور جان لو کہ اللہ سخت عذاب دینے والا ہے۔ ",
        "persian_text": "و از فتنه‌اى بترسید که تنها ستمکاران شما را در بر نگیرد، و بدانید که خدا سخت‌کیفر است.",
        "english_text": "And fear a trial which will not strike those who have wronged among you exclusively, and know that Allah is severe in penalty.",
        "transliteration": "Wattaqoo fitnatal laa tuseebannal lazeena zalamoo minkum khaaaassatanw wa'lamooo annal laaha shadeedul 'iqaab.",
    },
    {
        "verse_number": "26",
        "arabic_text": "وَ اذْكُرُوا اِذْ اَنْتُمْ قَلِيْلٌ مُّسْتَضْعَفُوْنَ فِي الْاَرْضِ تَخَافُونَ اَنْ يَّتَخَطَّفَكُمُ النَّاسُ فَاٰوٰكُمْ وَ اَيَّدَكُم بِنَصْرِهِ وَ رَزَقَكُم مِّنَ الطَّيِّبٰتِ لَعَلَّكُمْ تَشْكُرُوْنَ",
        "urdu_text": "اور یاد کرو جب تم تھوڑے تھے زمین میں دبے ہوئے، ڈرتے تھے کہ لوگ تمہیں اچک نہ لیں، پھر اس نے تمہیں پناہ دی اور اپنی مدد سے تمہیں تقویت بخشی اور پاکیزہ چیزوں میں سے تمہیں روزی دی تاکہ تم شکر کرو۔ ",
        "persian_text": "و به یاد آورید آنگاه که اندک بودید و در زمین ناتوان شمرده می‌شدید، می‌ترسیدید که مردم شما را بربایند؛ پس خدا شما را پناه داد و با یاری خود شما را نیرومند ساخت و از پاکیزه‌ها روزی داد، باشد که شکر کنید.",
        "english_text": "And remember when you were few and oppressed in the land, fearing that people might abduct you, but He sheltered you, supported you with His victory, and provided you with good things - that you might be grateful.",
        "transliteration": "Wazkurooo iz antum qaleelum mustad’afuona fil ardi takhaafoona ai yata khattafakumun naasu fa aawaakum wa aiyadakum binasrihee wa razaqakum minat taiyibaati la’allakum tashkuroon.",
    },
    {
        "verse_number": "27",
        "arabic_text": "يٰٓاٰيُّهَا الَّذِيْنَ آمَنُوْا لَا تَخُوْنُوْا اللّٰهَ وَ الرَّسُوْلَ وَ تَخُوْنُوْآ اَمٰنٰتِكُمْ وَ اَنْتُمْ تَعْلَمُوْنَ",
        "urdu_text": "اے ایمان والو! اللہ اور رسول کے ساتھ خیانت نہ کرو اور نہ اپنی امانتوں میں خیانت کرو حالانکہ تم جانتے ہو۔ ",
        "persian_text": "ای کسانی که ایمان آورده‌اید! به خدا و پیامبر خیانت مکنید و در امانت‌های خود خیانت نکنید در حالی که می‌دانید.",
        "english_text": "O you who have believed, do not betray Allah and the Messenger or betray your trusts while you know [the consequence].",
        "transliteration": "Yaaa ayyuhal lazeena aamanoo laa takhoonul laaha war Rasoola wa takhoonooo amaanaatikum wa antum ta’lamoon.",
    },
    {
        "verse_number": "28",
        "arabic_text": "وَ اعْلَمُوْا اَنَّمَا اَمْوَالُكُمْ وَ اَوْلَادُكُمْ فِتْنَةٌ وَ اَنَّ اللّٰهَ عِنْدَهُٓ اَجْرٌ عَظِيْمٌ",
        "urdu_text": "اور جان لو کہ تمہارے مال اور تمہاری اولاد ایک آزمائش ہیں اور یہ کہ اللہ کے پاس بڑا اجر ہے۔ ",
        "persian_text": "و بدانید که اموال و فرزندان شما جز آزمایشی نیستند و بی‌گمان پاداش بزرگ نزد خداست.",
        "english_text": "And know that your wealth and your children are but a trial and that Allah has with Him a great reward.",
        "transliteration": "Wa’lamooo annamaaa amwaalukum wa awlaadukum fitnatunw-wa annal laaha ‘indahoo ajrun ‘azeem.",
    },
    {
        "verse_number": "29",
        "arabic_text": "يٰٓاَيُّهَا الَّذِيْنَ آمَنُوْا اِنْ تَتَّقُوْا اللّٰهَ يَجْعَل لَّكُمْ فُرْقَانًا وَّ يُكَفِّرْ عَنكُمْ سَيِّاٰتِكُمْ وَ يَغْفِرْ لَكُمْ وَ اللّٰهُ ذُوْ الْفَضْلِ الْعَظِيْمِ",
        "urdu_text": "اے ایمان والو! اگر تم اللہ سے ڈرتے رہو تو وہ تمہارے لیے فرقان (حق و باطل میں فرق کرنے والی روشنی) بنائے گا اور تم سے تمہاری برائیاں دور کرے گا اور تمہیں بخش دے گا، اور اللہ بڑے فضل والا ہے۔ ",
        "persian_text": "ای کسانی که ایمان آورده‌اید! اگر از خدا پروا کنید، برای شما وسیله‌ای برای فرق میان حق و باطل قرار می‌دهد و گناهانتان را می‌زداید و شما را می‌آمرزد؛ و خداوند دارای فضل بزرگ است.",
        "english_text": "O you who have believed, if you fear Allah, He will grant you a criterion and will remove from you your misdeeds and forgive you. And Allah is the possessor of great bounty.",
        "transliteration": "Yaaa ayyuhal lazeena aamanoo in tattaqul laaha yaj’al lakum furqaananw-wa yukaffir ‘ankum saiyi aatikum wa yaghfir lakum; wallaahu zooo fadlin ‘azeem.",
    },
    {
        "verse_number": "30",
        "arabic_text": "وَ اِذْ يَمْكُرُ بِكَ الَّذِيْنَ كَفَرُوْا لِيُثْبِتُوْكَ اَوْ يَقْتُلُوْكَ اَوْ يُخْرِجُوكَ ۚ وَ يَمْكُرُوْنَ وَ يَمْكُرُ اللّٰهُ وَ اللّٰهُ خَيْرُ الْمٰكِرِيْنَ",
        "urdu_text": "اور جب کافر لوگ تمہارے خلاف تدبیر کر رہے تھے کہ تمہیں قید کریں یا قتل کریں یا نکال دیں، اور وہ تدبیریں کر رہے تھے اور اللہ تدبیر کر رہا تھا، اور اللہ سب سے بہتر تدبیر کرنے والا ہے۔ ",
        "persian_text": "و آنگاه را به یاد آور که کافران علیه تو مکر می‌ورزیدند تا تو را به بند کشند یا بکشند یا بیرون کنند؛ و آنان مکر می‌ورزیدند و خدا نیز مکر می‌ورزید؛ و خدا بهترین تدبیرکنندگان است.",
        "english_text": "And [remember, O Muhammad], when those who disbelieved plotted against you to restrain you or kill you or evict you. But they plan, and Allah plans. And Allah is the best of planners.",
        "transliteration": "Wa iz yamkuru bikal lazeena kafaroo liyusbitooka aw yaqtulooka aw yukhrijooka wa yamkuroona wa yamkurul laahu wallaahu khairul maakireen.",
    },
    {
        "verse_number": "31",
        "arabic_text": "وَ اِذْ تُتْلَىٰ عَلَيْهِمْ اٰيٰتُنَا قَالُوا قَدْ سَمِعْنَا لَوْ نَشَآءُ لَقُلْنَا مِثْلَ هٰذَآ ۙ اِنْ هٰذَآ اِلَّا اَسَاطِيرُ الْاَوَّلِيْنَ",
        "urdu_text": "اور جب ان پر ہماری آیتیں پڑھی جاتی ہیں تو وہ کہتے ہیں ہم نے سن لیا، اگر ہم چاہیں تو ہم بھی اس جیسا کہہ سکتے ہیں، یہ تو نہیں مگر اگلے لوگوں کی کہانیاں ہیں۔ ",
        "persian_text": "و هنگامی که آیات ما بر آنان خوانده می‌شود، می‌گویند: شنیدیم! اگر بخواهیم، ما نیز مانند این را می‌گوییم؛ این جز افسانه‌های پیشینیان نیست.",
        "english_text": "And when Our verses are recited to them, they say, 'We have heard. If we willed, we could say something like this. This is not but legends of the former peoples.'",
        "transliteration": "Wa iz tutlaa ‘alaihim aayaatunaa qaaloo qad sami’naa law nashaaa’u laqulnaa misla haazaaa in haazaaa illaaa asaateerul awwaleen.",
    },
    {
        "verse_number": "32",
        "arabic_text": "وَ اِذْ قَالُوا اللّٰهُمَّ اِنْ كَانَ هٰذَا هُوَ الْحَقَّ مِنْ عِنْدِكَ فَاَمْطِرْ عَلَيْنَا حِجَارَةً مِّنَ السَّمَآءِ اَوِ ائْتِنَا بِعَذَابٍ اَلِيْمٍ",
        "urdu_text": "اور جب انہوں نے کہا: اے اللہ! اگر یہ حق تیرے پاس سے ہے تو ہم پر آسمان سے پتھر برسایا یا ہمارے پاس کوئی دردناک عذاب لے آ۔ ",
        "persian_text": "و زمانی که گفتند: خدایا! اگر این حق از نزد توست، پس بر ما سنگی از آسمان ببار یا عذابی دردناک بر ما بیاور.",
        "english_text": "And [remember] when they said, 'O Allah, if this should be the truth from You, then rain down upon us stones from the sky or bring us a painful punishment.'",
        "transliteration": "Wa iz qaalul laahumma in kaana haazaa huwal haqqa min ‘indika fa amtir ‘alainaa hijaaratam minas samaaa’i awi’tinaa bi’azaabin aleem.",
    },
    {
        "verse_number": "33",
        "arabic_text": "وَ مَا كَانَ اللّٰهُ لِيُعَذِّبَهُمْ وَ اَنْتَ فِيْهِمْ ۚ وَ مَا كَانَ اللّٰهُ مُعَذِّبَهُمْ وَ هُمْ يَسْتَغْفِرُوْنَ",
        "urdu_text": "اور اللہ ایسا نہیں ہے کہ انہیں عذاب دے جب تک تم ان کے اندر ہو، اور اللہ ایسا نہیں ہے کہ انہیں عذاب دے جب وہ استغفار کر رہے ہوں۔ ",
        "persian_text": "و خدا هرگز آنان را عذاب نمی‌کند در حالی که تو در میان آنان هستی؛ و خدا هرگز آنان را عذاب‌کننده نیست در حالی که آنان آمرزش می‌خواهند.",
        "english_text": "But Allah would not punish them while you, [O Muhammad], are among them. And Allah would not punish them while they seek forgiveness.",
        "transliteration": "Wa maa kaanal laahu liyu’az zibahum wa anta feehim; wa maa kaanal laahu mu’az zibahum wa hum yastaghfiroon.",
    },
    {
        "verse_number": "34",
        "arabic_text": "وَ مَا لَهُمْ اَلَّا يُعَذِّبَهُمُ اللّٰهُ وَ هُمْ يَصُدُّوْنَ عَنِ الْمَسْجِدِ الْحَرَامِ وَ  مَا كَانُوا اَوْلِيَآءَهُ  اِنْ اَوْلِيَآؤُهُٓ اِلَّا الْمُتَّقُوْنَ وَ لٰكِنَّ اَكْثَرَهُمْ لَا يَعْلَمُونَ",
        "urdu_text": "اور ان کو کیا ہے کہ اللہ انہیں عذاب نہ دے جب کہ وہ مسجدِ حرام سے روکتے ہیں، حالانکہ وہ اس کے ولی نہیں ہیں۔ اس کے ولی تو صرف پرہیزگار ہیں لیکن ان میں اکثر نہیں جانتے۔ ",
        "persian_text": "و چه چیز آنان را بازمی‌دارد که خدا آنان را عذاب نکند، در حالی که آنان از مسجدالحرام بازمی‌دارند؟ در حالی که آنان سرپرستان آن نیستند! سرپرستان آن تنها پرهیزگارانند، ولی بیشترشان نمی‌دانند.",
        "english_text": "But why should Allah not punish them while they obstruct [people] from al-Masjid al-Haram, and they were not its guardians? Its true guardians are not but the righteous, but most of them do not know.",
        "transliteration": "Wa maa lahum allaa yu’az zibahumul laahu wa hum yasuddoona ‘anil masjidil haraami wa maa kaanooo awliyaaa’ahoo; in awliyaaa’ooo illal muttaqoona wa laakinna aksarahum laa ya’lamoon.",
    },
    {
        "verse_number": "35",
        "arabic_text": "وَ مَا كَانَ صَلَاتُهُمْ عِنْدَ الْبَيْتِ اِلَّا مُكَآءً وَ تَصْدِيَةً ۚ فَذُوْقُوْا الْعَذَابَ بِمَا كُنْتُمْ تَكْفُرُوْنَ",
        "urdu_text": "اور ان کی نماز بیت اللہ کے پاس کچھ نہ تھی مگر سیٹیاں بجانا اور تالیاں پیٹنا، سو اپنے کفر کے بدلے عذاب کا مزہ چکھو۔ (ترجمہ: حافظ سید فرمان علی)",
        "persian_text": "و نمازشان نزد خانه جز سوت و کف‌زدن نبود؛ پس به کیفر آنچه کفر می‌ورزیدید، عذاب را بچشید.",
        "english_text": "And their prayer at the House was not except whistling and handclapping. So taste the punishment for what you disbelieved.",
        "transliteration": "Wa maa kaana salaatuhum ‘indal bait illaa mukaaa’anw-wa tasdiyah; fazooqul ‘azaaba bimaa kuntum takfuroon.",
    },
    {
        "verse_number": "36",
        "arabic_text": "اِنَّ الَّذِينَ كَفَرُوا يُنْفِقُوْنَ اَمْوَالَهُمْ لِيَصُدُّوْا عَنْ سَبِيْلِ اللّٰهِ ۚ فَسَيُنْفِقُوْنَهَا ثُمَّ تَكُوْنُ عَلَيْهِمْ حَسْرَةً ثُمَّ يُغْلَبُونَ وَالَّذِيْنَ كَفَرُوْا اِلٰى جَهَنَّمَ يُحْشَرُوْنَ",
        "urdu_text": "یقیناً جو لوگ کافر ہیں وہ اپنے مال اس لیے خرچ کرتے ہیں کہ لوگوں کو اللہ کے راستے سے روکیں۔ پس وہ انہیں خرچ کرتے رہیں گے پھر وہ ان پر حسرت بن جائیں گے، پھر وہ مغلوب ہوں گے، اور کافر دوزخ کی طرف اکٹھے کیے جائیں گے۔ ",
        "persian_text": "کافران اموال خود را خرج می‌کنند تا از راه خدا بازدارند. به زودی آن را خرج خواهند کرد سپس مایه حسرت آنان خواهد شد، آنگاه شکست خواهند خورد، و کافران به سوی جهنم گردآوری می‌شوند.",
        "english_text": "Indeed, those who disbelieve spend their wealth to avert [people] from the way of Allah. So they will spend it; then it will be for them a [cause of] regret; then they will be overcome. And those who have disbelieved - unto Hell they will be gathered.",
        "transliteration": "Innal lazeena kafaroo yunfiqoona amwaalahum liyasuddoo 'an sabeelil laahi fasayunfiqoonahaa summa takoonu 'alaihim hasratan summa yughlaboon; wallazeena kafaroo ilaa jahannama yuhsharoon.",
    },
    {
        "verse_number": "37",
        "arabic_text": "لِيَمِيزَ اللّٰهُ الْخَبِيْثَ مِنَ الطَّيِّبِ وَ يَجْعَلَ الْخَبِيْثَ بَعْضَهُ عَلٰى بَعْضٍ فَيَرْكُمَهُ جَمِيْعًا فَيَجْعَلَهُ فِيْ جَهَنَّمَ ۚ اُولٰٓئِكَ هُمُ الْخٰسِرُوْنَ",
        "urdu_text": "تاکہ اللہ خبیث کو پاکیزہ سے الگ کرے اور خبیث کو ایک دوسرے پر ڈال کر سب کو اکٹھا کرے پھر اسے دوزخ میں ڈال دے۔ یہی لوگ نقصان اٹھانے والے ہیں۔ ",
        "persian_text": "تا خدا پلید را از پاک جدا کند و پلید را روی هم نهد و همه را جمع سازد و در دوزخ اندازد. آنان همان زیانکارانند.",
        "english_text": "That Allah may separate the impure from the pure and put the impure, some of them upon others, and heap them all together and put them into Hell. It is they who will be the losers.",
        "transliteration": "Liyameeza Allaahul khabeetha minat taiyibi wa yaj'ala alkhabeetha ba'dahu 'ala ba'din fayarkumahoo jamee'an faya ja'alahoo fee jahannam; ulaaa'ika humul khaasiroon.",
    },
    {
        "verse_number": "38",
        "arabic_text": "قُل لِّلَّذِينَ كَفَرُوْا اِنْ يَنْتَهُوْا يُغْفَرْ لَهُمْ مَّا قَدْ سَلَفَ وَ اِنْ يَّعُوْدُوْا فَقَدْ مَضَتْ سُنَّةُ الْاَوَّلِيْنَ",
        "urdu_text": "کافروں سے کہہ دو اگر وہ باز آجائیں تو ان کے پچھلے گناہ بخش دیے جائیں گے، اور اگر پھر وہ وہی کریں تو پہلوں کا طریقہ گزر چکا ہے۔ ",
        "persian_text": "به کافران بگو: اگر بازایستند، گذشته آنان آمرزیده خواهد شد؛ و اگر بازگردند، سنت پیشینیان گذشت.",
        "english_text": "Say to those who have disbelieved that if they cease, what has previously occurred will be forgiven for them; but if they return, then the precedent of the former peoples has already taken place.",
        "transliteration": "Qul lillazeena kafaroo in yantahoo yughfar lahum ma qad salaf wa in ya'oodoo faqad madat sunnatul awwaleen.",
    },
    {
        "verse_number": "39",
        "arabic_text": "وَ قَاتِلُوهُمْ حَتّٰى لَا تَكُوْنَ فِتْنَةٌ وَّ يَكُوْنَ الدِّيْنُ كُلُّهُ لِلّٰهِ ۚ فَاِنِ انْتَهَوْا فَاِنَّ اللّٰهَ بِمَا يَعْمَلُوْنَ بَصِيْرٌ",
        "urdu_text": "اور ان سے جنگ کرو یہاں تک کہ فتنہ باقی نہ رہے اور دین خالص اللہ ہی کا ہو جائے۔ پھر اگر وہ باز آجائیں تو اللہ ان کے اعمال کو خوب دیکھنے والا ہے۔",
        "persian_text": "و با آنان پیکار کنید تا فتنه‌ای نماند و دین یکسره از آنِ خدا شود. پس اگر بازایستند، خداوند به آنچه می‌کنند بیناست.",
        "english_text": "And fight them until there is no fitnah and [until] the religion, all of it, is for Allah. And if they cease, then indeed, Allah is Seeing of what they do.",
        "transliteration": "Waqaatiloohum hattaa laa takoona fitnatunw-wa yakoonad deenu kulluhoo lillaah; fa'inintahaw fa innal laaha bimaa ya'maloona baseer.",
    },
    {
        "verse_number": "40",
        "arabic_text": "وَ اِنْ تَوَلَّوْا فَاعْلَمُوْٓا اَنَّ اللّٰهَ مَوْلَاكُمْ ۚ نِعْمَ الْمَوْلٰى وَ نِعْمَ النَّصِيْرُ",
        "urdu_text": "اور اگر وہ منہ موڑیں تو جان لو کہ اللہ تمہارا کارساز ہے۔ وہ بہترین کارساز اور بہترین مددگار ہے۔ ",
        "persian_text": "و اگر روی بگردانند، بدانید که خدا سرپرست شماست. چه نیکو سرپرست و چه نیکو یاوری است.",
        "english_text": "And if they turn away - then know that Allah is your protector. Excellent is the protector, and excellent is the helper.",
        "transliteration": "Wa in tawallaw fa'lamooo annal laaha mawlaakum; ni'mal mawlaa wa ni'man naseer.",
    },
    {
        "verse_number": "41",
        "arabic_text": "وَ اعْلَمُوا اَنَّمَا غَنِمْتُم مِّنْ شَيْءٍ فَاَنَّ لِلّٰهِ خُمُسَهُ وَ لِلرَّسُولِ وَ لِذِي الْقُرْبٰى وَ الْيَتٰمٰى وَ الْمَسٰكِيْنِ وَ ابْنِ السَّبِيْلِ اِنْ كُنْتُمْ اٰمَنْتُم بِاللّٰهِ وَ مَآ اَنْزَلْنَا عَلٰى عَبْدِنَا يَوْمَ الْفُرْقَانِ يَوْمَ الْتَقَى الْجَمْعٰنِ وَ اللّٰهُ عَلٰى كُلِّ شَيْءٍ قَدِيْرٌ",
        "urdu_text": "اور جان لو کہ جو کچھ بھی تم غنیمت حاصل کرو تو اس کا پانچواں حصہ اللہ اور رسول کا اور قرابت داروں کا اور یتیموں کا اور مسکینوں کا اور مسافر کا ہے۔ اگر تم اللہ پر ایمان رکھتے ہو اور اس پر جو ہم نے اپنے بندے پر اتارا فیصلے کے دن جس دن دونوں جماعتیں آپس میں ملی تھیں، اور اللہ ہر چیز پر قادر ہے۔ ",
        "persian_text": "و بدانید هر آنچه غنیمت به دست آورید، یک‌پنجم آن برای خدا و رسول و خویشاوندان و یتیمان و بینوایان و در راه ماندگان است، اگر به خدا ایمان آورده‌اید و به آنچه بر بنده‌مان در روز فرقان نازل کردیم، روزی که دو گروه به هم رسیدند. و خدا بر هر چیزی تواناست.",
        "english_text": "And know that anything you obtain of war booty - then indeed, for Allah is one fifth of it and for the Messenger and for [his] near relatives and the orphans, the needy, and the [stranded] traveler, if you have believed in Allah and in that which We sent down to Our Servant on the day of criterion - the day when the two armies met. And Allah, over all things, is competent.",
        "transliteration": "Wa'lamooo annama ghanimtum min shai'in fa annal lillaahi khumusahoo wa lirrasooli wa liyee alqurbaa walyataamaa walmasaakeeni wabnis sabeel in kuntum aamantum billaahi wa maaa anzalnaa 'alaaa 'abdinaa yawmal furqaani yawmal taqal jam'aan; wallaahu 'alaaa kulli shai'in qadeer.",
    },
    {
        "verse_number": "42",
        "arabic_text": "اِذْ اَنْتُم بِالْعُدْوَةِ الدُّنْيَا وَ هُم بِالْعُدْوَةِ الْقُصْوٰى وَ الرَّكْبُ اَسْفَلَ مِنْكُمْ ۚ وَ لَوْ تَوَاعَدتُّمْ لَاخْتَلَفْتُمْ فِي الْمِيْعٰدِ وَ لٰكِنْ لِّيَقْضِيَ اللّٰهُ اَمْرًا كَانَ مَفْعُوْلًا لِّيَهْلِكَ مَنْ هَلَكَ عَنْ بَيِّنَةٍ وَّ يَحْيٰى مَنْ حَيَّ عَنْ بَيِّنَةٍ وَ اِنَّ اللّٰهَ لَسَمِيْعٌ عَلِيْمٌ",
        "urdu_text": "جب تم نچلی جانب میں تھے اور وہ اوپری جانب میں تھے اور قافلہ تم سے نیچے کی طرف تھا۔ اور اگر تم آپس میں وعدہ کرتے تو وقت پر اختلاف کر لیتے لیکن اللہ نے وہ کام کر دیا جو ہونا ہی تھا تاکہ وہ ہلاک کرے جو دلیل سے ہلاک ہو اور زندہ رہے جو دلیل سے زندہ رہے۔ اور بے شک اللہ خوب سننے والا جاننے والا ہے۔ ",
        "persian_text": "آنگاه که شما در دامنه نزدیک‌تر بودید و آنان در دامنه دورتر و کاروان پایین‌تر از شما بود، و اگر وعده می‌گذاشتید، در وعده اختلاف می‌کردید؛ ولی خدا کاری را که باید می‌شد، تحقق بخشید، تا آنکه هلاک گردد از روی دلیل و زنده بماند از روی دلیل. و خداوند شنوای داناست.",
        "english_text": "Remember when you were on the near side of the valley, and they were on the farther side, and the caravan was lower than you. If you had made an appointment, you would have differed over the appointment, but [it was] so that Allah might accomplish a matter already destined - that those who perished would perish upon evidence and those who lived would live upon evidence; and indeed, Allah is Hearing and Knowing.",
        "transliteration": "Iz antum bil'udwatid dunyaa wa hum bil'udwatil quswaa warrakbu asfala minkum; wa law tawaa'attum lakh talaftum fil mee'aadi wa laakin liyaqdiya Allahu amran kaana maf'oolan liyahlika man halaka 'an baiyinatinw-wa yahyaa man haayya 'an baiyina; wa innal laaha lasamee'un 'aleem.",
    },
    {
        "verse_number": "43",
        "arabic_text": "اِذْ يُرِيْكَهُمُ اللّٰهُ فِي مَنَامِكَ قَلِيْلًا وَ لَوْ اَرٰكَهُمْ كَثِيْرًا لَّفَشِلْتُمْ وَ لَتَنَازَعْتُمْ فِي الْاَمْرِ وَ لٰكِنَّ اللّٰهَ سَلَّمَ اِنَّهُ عَلِيْمٌ بِذَاتِ الصُّدُوْرِ",
        "urdu_text": "جب اللہ نے تمہیں خواب میں انہیں تھوڑا دکھایا، اور اگر وہ تمہیں زیادہ دکھاتا تو تم بزدل ہو جاتے اور تم اس معاملے میں جھگڑ پڑتے، لیکن اللہ نے (تمہیں) بچا لیا۔ بے شک وہ سینوں کے بھیدوں کو خوب جاننے والا ہے۔ ",
        "persian_text": "آنگاه که خدا آنان را در خواب تو اندک نمود، و اگر بسیارشان می‌نمود، سست می‌شدید و در کار اختلاف می‌کردید، ولی خداوند سلامت بخشید؛ او به رازهای سینه‌ها داناست.",
        "english_text": "When Allah showed them to you in your dream as few; and if He had shown them to you as many, you [believers] would have lost courage and would have disputed in the matter, but Allah saved [you from that]. Indeed, He is Knowing of that within the breasts.",
        "transliteration": "Iz yureekahumul laahu fee manaamika qaleelanw-wa law araakahum kaseeran la fashiltum wa latanaaza'tum fil amri wa laakinnal laaha sallam; innahoo 'aleemun bizaatis sudoor.",
    },
    {
        "verse_number": "44",
        "arabic_text": "وَ اِذْ يُرِيْكُمُوْهُمْ اِذِ الْتَقَيْتُمْ فِيٓ اَعْيُنِكُمْ قَلِيْلًا وَّ يُقَلِّلُكُمْ فِيٓ اَعْيُنِهِمْ لِيَقْضِيَ اللّٰهُ اَمْرًا كَانَ مَفْعُوْلًا وَ اِلَى اللّٰهِ تُرْجَعُ الْاُمُوْرُ",
        "urdu_text": "اور جب تم ان سے ملو تو اللہ تمہیں ان کی آنکھوں میں تھوڑا دکھاتا تھا اور انہیں تمہاری آنکھوں میں کم کرتا تھا تاکہ اللہ وہ بات پوری کر دے جو ہونی ہی تھی۔ اور سب کام اللہ ہی کی طرف لوٹائے جاتے ہیں۔",
        "persian_text": "و هنگامی که با آنان روبرو شدید، در دیده‌های شما اندکشان نمود و شما را نیز در دیده‌های آنان اندک نمود، تا خداوند کاری را که باید می‌شد تحقق بخشد. و کارها به سوی خدا بازگردانده می‌شود.",
        "english_text": "And [remember] when He showed them to you, when you met, as few in your eyes, and He made you appear as few in their eyes so that Allah might accomplish a matter already destined. And to Allah will be returned all matters.",
        "transliteration": "Wa iz yureekumoohum izil taqaitum fee a'yunikum qaleelanw-wa yuqallilukum fee a'yunihim liyaqdiya Allahu amran kaana maf'oolaa; wa ilal laahi turja'ul umoor.",
    },
    {
        "verse_number": "45",
        "arabic_text": "يٰٓاَيُّهَا الَّذِيْنَ آمَنُوْا اِذَا لَقِيْتُمْ فِئَةً فَاثْبُتُوْا وَ اذْكُرُوْا اللّٰهَ كَثِيْرًا لَّعَلَّكُمْ تُفْلِحُوْنَ",
        "urdu_text": "اے ایمان والو! جب تم کسی لشکر سے ملو تو ثابت قدم رہو اور اللہ کو کثرت سے یاد کرو تاکہ تم کامیاب ہو جاؤ۔ ",
        "persian_text": "ای کسانی که ایمان آورده‌اید! چون با گروهی روبرو شدید، پایدار باشید و خدا را بسیار یاد کنید، باشد که رستگار شوید.",
        "english_text": "O you who have believed, when you encounter a company [from the enemy forces], stand firm and remember Allah much that you may be successful.",
        "transliteration": "Yaaa aiyuhal lazeena aamanooo izaa laqeetum fi'atan fasbuitoo wadhkuroo Allaha katheeral la'allakum tuflihoon.",
    },
    {
        "verse_number": "46",
        "arabic_text": "وَ اَطِيْعُوْا اللّٰهَ وَ رَسُولَهُ وَ لَا تَنَازَعُوا فَتَفْشَلُوْا وَ تَذْهَبَ رِيْحُكُمْ وَ اصْبِرُوْا ۚ اِنَّ اللّٰهَ مَعَ الصّٰبِرِينَ",
        "urdu_text": "اور اللہ اور اس کے رسول کی اطاعت کرو اور آپس میں جھگڑا نہ کرو ورنہ تم کمزور ہو جاؤ گے اور تمہاری ہوا اکھڑ جائے گی، اور صبر کرو، بےشک اللہ صبر کرنے والوں کے ساتھ ہے۔ ",
        "persian_text": "و خدا و پیامبرش را اطاعت کنید و نزاع مکنید که سست شوید و قدرتتان از بین برود. و صبر کنید که خدا با صابران است.",
        "english_text": "And obey Allah and His Messenger, and do not dispute and [thus] lose courage and your strength would depart; and be patient. Indeed, Allah is with the patient.",
        "transliteration": "Wa atee'ul laaha wa Rasoolahoo wa laa tanaaza'oo fatafshaloo wa tazhaba reehu kum wasbiroo innal laaha ma'as saabireen.",
    },
    {
        "verse_number": "47",
        "arabic_text": "وَ لَا تَكُونُوا كَالَّذِينَ خَرَجُوا مِنْ دِيَارِهِم بَطَرًا وَّ رِئَآءَ النَّاسِ وَ يَصُدُّوْنَ عَنْ سَبِيْلِ اللّٰهِ ۚ وَ اللّٰهُ بِمَا يَعْمَلُوْنَ مُحِيْطٌ",
        "urdu_text": "اور ان لوگوں کی طرح نہ بنو جو اپنے گھروں سے اترائے ہوئے اور لوگوں کو دکھانے کے لیے نکلے اور اللہ کے راستے سے روکتے تھے، اور اللہ ان کے اعمال کو گھیرے ہوئے ہے۔",
        "persian_text": "و مانند کسانی نباشید که از خانه‌هایشان با تکبر و خودنمایی بیرون آمدند و از راه خدا باز می‌داشتند، و خدا به آنچه می‌کنند احاطه دارد.",
        "english_text": "And do not be like those who came out of their homes boastfully and to be seen by people and avert [them] from the way of Allah. And Allah is encompassing of what they do.",
        "transliteration": "Wa laa takoonoo kallazeena kharajoo min diyaarihim bataranw wa ri'aaa'an naasi wa yasuddoona 'an sabeelil laah; wallaahu bimaa ya'maloona muheet.",
    },
    {
        "verse_number": "48",
        "arabic_text": "وَ اِذْ زَيَّنَ لَهُمُ الشَّيْطٰنُ اَعْمَالَهُمْ وَ قَالَ لَا غَالِبَ لَكُمُ الْيَوْمَ مِنَ النَّاسِ وَ اِنِّي جَارٌ لَّكُمْ فَلَمَّا تَرَآءَتِ الْفِئَتٰنِ نَكَصَ عَلٰى عَقِبَيْهِ وَ قَالَ اِنِّي بَرِيْٓءٌ مِّنْكُمْ اِنِّي اَرٰى مَا لَا تَرَوْنَ اِنِّيْٓ اَخَافُ اللّٰهَ ۚ وَ اللّٰهُ شَدِيْدُ الْعِقَابِ",
        "urdu_text": "اور جب شیطان نے ان کے اعمال ان کے لئے خوشنما بنا دیے اور کہا: آج کوئی تم پر غالب آنے والا نہیں اور میں تمہارا مددگار ہوں، لیکن جب دونوں لشکر آمنے سامنے ہوئے تو وہ الٹے پاؤں پھر گیا اور کہا: میں تم سے بیزار ہوں، میں وہ دیکھ رہا ہوں جو تم نہیں دیکھ رہے، میں اللہ سے ڈرتا ہوں، اور اللہ سخت عذاب دینے والا ہے۔",
        "persian_text": "و آنگاه که شیطان اعمالشان را برایشان زیبا جلوه داد و گفت: امروز هیچ‌کس از مردم بر شما غالب نمی‌شود و من همسایه و یاور شما هستم. ولی هنگامی که دو گروه رویاروی شدند، به عقب برگشت و گفت: من از شما بیزارم، من چیزی را می‌بینم که شما نمی‌بینید، من از خدا می‌ترسم. و خدا سخت‌کیفر است.",
        "english_text": "And [remember] when Satan made their deeds pleasing to them and said, 'No one can overcome you today from among the people, and indeed, I am your protector.' But when the two armies sighted each other, he turned on his heels and said, 'Indeed, I am disassociated from you. Indeed, I see what you do not see; indeed I fear Allah. And Allah is severe in penalty.'",
        "transliteration": "Wa iz zaiyana lahumush Shaitaanu a'maalahum wa qaala laa ghaaliba lakumul yawma minannaasi wa innee jaarul lakum falammaa taraaa'atil fi'ataani nakasa 'alaaa 'aqibaihi wa qaala innee bareee'um minkum innee araaa maa laa taraona innee akhaafullaaha wallaahu shadeedul 'iqaab.",
    },
    {
        "verse_number": "49",
        "arabic_text": "اِذْ يَقُوْلُ الْمُنٰفِقُوْنَ وَ الَّذِيْنَ فِي قُلُوبِهِم مَّرَضٌ غَرَّ هٰٓؤُلَآءِ دِيْنُهُمْ وَ مَنْ يَّتَوَكَّلْ عَلَى اللّٰهِ فَاِنَّ اللّٰهَ عَزِيْزٌ حَكِيْمٌ",
        "urdu_text": "جب منافق اور وہ لوگ جن کے دلوں میں بیماری ہے کہنے لگے: ان لوگوں کا دین انہیں دھوکے میں ڈال گیا ہے۔ اور جو اللہ پر بھروسہ کرے تو یقیناً اللہ غالب حکمت والا ہے۔",
        "persian_text": "هنگامی که منافقان و کسانی که در دل‌هایشان بیماری است گفتند: دین اینان آنها را مغرور کرده است. و کسی که بر خدا توکل کند، پس خداوند شکست‌ناپذیر و حکیم است.",
        "english_text": "When the hypocrites and those in whose hearts was disease said, 'Their religion has deluded those [Muslims].' But whoever relies upon Allah - then indeed, Allah is Exalted in Might and Wise.",
        "transliteration": "Iz yaqoolul munaafiqoona wallazeena fee quloobihim maradun gharr haaa'ulaaa'i deenuhum; wa many yatawakkal 'alal laahi fa innal laaha 'azeezun hakeem.",
    },
    {
        "verse_number": "50",
        "arabic_text": "وَ لَوْ تَرٰٓى اِذْ يَتَوَفَّى الَّذِيْنَ كَفَرُوْا الْمَلٰٓئِكَةُ يَضْرِبُوْنَ وُجُوْهَهُمْ وَ اَدْبٰرَهُمْ وَ ذُوْقُوْا عَذَابَ الْحَرِيْقِ",
        "urdu_text": "اور کاش تم دیکھتے جب فرشتے کافروں کی جانیں نکالتے ہیں ان کے چہروں اور پیٹھوں پر مارتے ہوئے اور کہتے ہیں: جلنے والے عذاب کا مزہ چکھو۔",
        "persian_text": "و کاش می‌دیدی هنگامی که فرشتگان جان کافران را می‌گیرند، در حالی که به صورت‌ها و پشت‌هایشان می‌زنند و [می‌گویند]: عذاب سوزان را بچشید.",
        "english_text": "If you could but see when the angels take the souls of those who disbelieved, striking their faces and their backs and [saying], 'Taste the punishment of the Burning Fire.'",
        "transliteration": "Wa law taraaa iz yatawaffal lazeena kafarul malaaa'ikatu yadriboona wujoohahum wa adbaarahum wa zooqoo 'azaabal hareeq.",
    },
    {
        "verse_number": "51",
        "arabic_text": "ذٰلِكَ بِمَا قَدَّمَتْ اَيْدِيْكُمْ وَ اَنَّ اللّٰهَ لَيْسَ بِظَلَّامٍ لِّلْعَبِيْدِ",
        "urdu_text": "یہ اس لیے کہ تمہارے ہاتھوں نے آگے بھیجا اور اس لیے کہ اللہ اپنے بندوں پر ظلم کرنے والا نہیں ہے۔",
        "persian_text": "این به سبب چیزی است که دست‌های شما از پیش فرستاده است و خداوند به بندگان ستمگر نیست.",
        "english_text": "That is for what your hands have put forth and because Allah is not ever unjust to the servants.",
        "transliteration": "Zaalika bimaa qaddamat aideekum wa annal laaha laisa bizallaamil lil'abeed.",
    },
    {
        "verse_number": "52",
        "arabic_text": "كَدَاْبِ اٰلِ فِرْعَوْنَ وَ الَّذِيْنَ مِنْ قَبْلِهِمْ ۚ كَفَرُوْا بِاٰيٰتِ اللّٰهِ فَاَخَذَهُمُ اللّٰهُ بِذُنُوْبِهِمْ  اِنَّ اللّٰهَ قَوِيٌّ شَدِيْدُ الْعِقَابِ",
        "urdu_text": "یہ بھی فرعونیوں اور ان سے پہلے کے لوگوں کے طریقے کی طرح ہے۔ انہوں نے اللہ کی آیتوں کا انکار کیا تو اللہ نے ان کو ان کے گناہوں کے سبب پکڑ لیا، بے شک اللہ قوت والا سخت عذاب دینے والا ہے۔",
        "persian_text": "همانند روش فرعونیان و کسانی که پیش از آنان بودند. آنها به آیات خدا کفر ورزیدند، پس خداوند به سبب گناهانشان آنان را گرفت. بی‌گمان خداوند نیرومند و سخت‌کیفر است.",
        "english_text": "[Theirs is] like the way of the people of Pharaoh and of those before them. They disbelieved in the signs of Allah, so Allah seized them for their sins. Indeed, Allah is Powerful and severe in penalty.",
        "transliteration": "Kada'bi aali fir'awna wallazeena min qablihim; kafaroo bi aayaatil laahi fa akhazahumul laahu bizunoobihim; innal laaha qawiyyun shadeedul 'iqaab.",
    },
    {
        "verse_number": "53",
        "arabic_text": "ذٰلِكَ بِاَنَّ اللّٰهَ لَمْ يَكُ مُغَيِّرًا نِّعْمَةً اَنْعَمَهَا عَلٰى قَوْمٍ حَتّٰى يُغَيِّرُوْا مَا بِاَنفُسِهِمْ وَ اَنَّ اللّٰهَ سَمِيْعٌ عَلِيْمٌ",
        "urdu_text": "یہ اس لیے کہ اللہ کسی قوم پر کوئی نعمت جو اس نے انہیں دی ہو نہیں بدلتا جب تک وہ خود اپنی حالت کو نہ بدلیں، اور بے شک اللہ سننے والا جاننے والا ہے۔",
        "persian_text": "این به سبب آن است که خداوند نعمتی را که به قومی داده تغییر نمی‌دهد تا زمانی که خودشان آنچه در دل‌هایشان است تغییر دهند. و خدا شنوا و داناست.",
        "english_text": "That is because Allah would not change a favor which He had bestowed upon a people until they change what is within themselves. And indeed, Allah is Hearing and Knowing.",
        "transliteration": "Zaalika bi annal laaha lam yaku mughayyiran ni'matan an'amahaa 'alaaa qawmin hattaaa yughaiyiroo maa bi anfusihim wa annal laaha samee'un 'aleem.",
    },
    {
        "verse_number": "54",
        "arabic_text": "كَدَاْبِ اٰلِ فِرْعَوْنَ وَ الَّذِينَ مِن قَبْلِهِمْ ۚ كَذَّبُوْا بِاٰيٰتِ رَبِّهِمْ فَاَهْلَكْنٰهُم بِذُنُوبِْهِمْ وَ اَغْرَقْنَا اٰلَ فِرْعَوْنَ ۚ وَ كُلٌّ كَانُوا ظٰلِمِيْنَ",
        "urdu_text": "یہ بھی فرعونیوں اور ان سے پہلے کے لوگوں کے طریقے کی طرح ہے۔ انہوں نے اپنے رب کی آیتوں کو جھٹلایا تو ہم نے ان کو ان کے گناہوں کے سبب ہلاک کر دیا اور فرعونیوں کو غرق کر دیا اور سب ظالم تھے۔",
        "persian_text": "مانند روش فرعونیان و کسانی که پیش از آنان بودند. آنها آیات پروردگارشان را تکذیب کردند، پس آنان را به سبب گناهانشان هلاک کردیم و فرعونیان را غرق نمودیم و همه ستمکار بودند.",
        "english_text": "[Theirs is] like the way of the people of Pharaoh and those before them. They denied the signs of their Lord, so We destroyed them for their sins, and We drowned the people of Pharaoh. And all of them were wrongdoers.",
        "transliteration": "Kada'bi aali fir'awna wallazeena min qablihim; kazzaboo bi aayaatir rabbihim fa ahlaknaahum bizunoobihim wa aghraqnaa aala fir'awna wa kullun kaanoo zaalimeen.",
    },
    {
        "verse_number": "55",
        "arabic_text": "اِنَّ شَرَّ الدَّوَآبِّ عِنْدَ اللّٰهِ الَّذِيْنَ كَفَرُوْا فَهُمْ لَا يُؤْمِنُوْنَ",
        "urdu_text": "الله کے نزیک زمین پر چلنے والوں میں بدترین وہ ہیں جنہونے کفر اختیار کر لیا اور اب وہ امن لانے والے نہیں ہیں۔",
        "persian_text": "بی‌گمان بدترین جنبندگان نزد خدا کسانی هستند که کفر ورزیدند، پس ایمان نمی‌آورند.",
        "english_text": "Indeed, the worst of living creatures in the sight of Allah are those who have disbelieved, and they will not [ever] believe.",
        "transliteration": "Inna sharrad dawaaabbi 'indal laahillazeena kafaroo fahum laa yu'minoon.",
    },
    {
        "verse_number": "56",
        "arabic_text": "الَّذِيْنَ عٰهَدتَّ مِنْهُمْ ثُمَّ يَنْقُضُوْنَ عَهْدَهُمْ فِيْ كُلِّ مَرَّةٍ وَ هُمْ لَا يَتَّقُوْنَ",
        "urdu_text": "یہ وہ لوگ ہیں جن سے آپ نے معاہدہ کیا پھر وہ ہر بار اپنے عہد کو توڑ ڈالتے ہیں اور وہ (کسی عہد کی) پرواہ نہیں کرتے۔ ",
        "persian_text": "همان کسانی که با آنان پیمان بستی، سپس هر بار پیمانشان را می‌شکنند، و پرهیز نمی‌کنند.",
        "english_text": "They are those with whom you made a treaty, but every time they break their treaty, and they do not fear Allah.",
        "transliteration": "Allazeena 'aahadta minhum summa yanqudoona 'ahdahum fee kulli marrah, wa hum laa yattaqoon.",
    },
    {
        "verse_number": "57",
        "arabic_text": "فَاِمَّا تَثْقَفَنَّهُمْ فِيْ الْحَرْبِ فَشَرِّدْ بِهِم مَّنْ خَلْفَهُمْ لَعَلَّهُمْ يَذَّكَّرُوْنَ",
        "urdu_text": "پس اگر آپ کو جنگ میں ان پر غلبہ ملے تو ان کو ایسی سزا دیں کہ ان کے پیچھے رہنے والے بھی سبق حاصل کریں تاکہ وہ نصیحت حاصل کری",
        "persian_text": "پس اگر در جنگ بر آنان دست یافتی، آنان را چنان پراکنده ساز که کسانی که پشت سر آنانند پند گیرند.",
        "english_text": "So if you gain mastery over them in war, make an example of them for those who come after them, that perhaps they will be reminded.",
        "transliteration": "Fa-imma thaqafannahum fil harbi fasharrid bihim man khalfahum la'allahum yazzakkaroon.",
    },
    {
        "verse_number": "58",
        "arabic_text": "وَ اِمَّا تَخَافَنَّ مِنْ قَوْمٍ خِيَانَةً فَانْبِذْ اِلَيْهِمْ عَلٰى سَوَآءٍ ۚ اِنَّ اللّٰهَ لَا يُحِبُّ الْخَآئِنِيْنَ",
        "urdu_text": "اور اگر آپ کو کسی قوم کی طرف سے دغا بازی کا اندیشہ ہو تو ان کا عہد ان پر برابر پھینک دیں۔ بے شک اللہ دغا بازوں کو پسند نہیں کرتا۔ ",
        "persian_text": "و اگر از گروهی خیانت بیم داری، پیمانشان را به سویشان بیفکن، که خدا خیانتکاران را دوست ندارد.",
        "english_text": "And if you fear treachery from a people, throw back to them their treaty on equal terms. Indeed, Allah does not like traitors.",
        "transliteration": "Wa-imma takhaafanna min qawmin khiyaanatan fanbidh ilayhim 'ala sawaaa'; innal laaha laa yuhibbul khaaa'ineen.",
    },
    {
        "verse_number": "59",
        "arabic_text": "وَ لَا يَحْسَبَنَّ الَّذِيْنَ كَفَرُوْا سَبَقُوْا ۚ اِنَّهُمْ لَا يُعْجِزُوْنَ",
        "urdu_text": "اور کافر یہ گمان نہ کریں کہ وہ (ہم سے) آگے نکل گئے ہیں۔ بے شک وہ ہمیں عاجز کرنے والے نہیں ہیں۔ ",
        "persian_text": "و کسانی که کافر شدند، گمان نبرند که پیشی گرفته‌اند؛ آنان هرگز عاجزکننده نیستند.",
        "english_text": "And let not those who disbelieve think they will escape. Indeed, they will not cause failure to Allah.",
        "transliteration": "Wa laa yahsabannal lazeena kafaroo sabaqoo; innahum laa yu'jizoon.",
    },
    {
        "verse_number": "60",
        "arabic_text": "وَ اَعِدُّوْا لَهُم مَّا اسْتَطَعْتُم مِّنْ قُوَّةٍ وَ مِنْ رِّبَاطِ الْخَيْلِ تُرْهِبُوْنَ بِهِ عَدُوَّ اللّٰهِ وَ عَدُوَّكُمْ وَ اٰخَرِيْنَ مِنْ دُوْنِهِمْ لَا تَعْلَمُوْنَهُمُ اللّٰهُ يَعْلَمُهُمْ ۚ وَ مَا تُنْفِقُوا مِنْ شَيْءٍ فِيْ سَبِيْلِ اللّٰهِ يُوَفَّ اِلَيْكُمْ وَ اَنْتُمْ لَا تُظْلَمُوْنَ",
        "urdu_text": "اور ان کے لئے جتنا ہو سکے طاقت اور گھوڑوں کی تیاری کرو تاکہ اس سے اللہ کے دشمن اور تمہارے دشمن اور ان کے سوا دوسرے جنہیں تم نہیں جانتے اللہ جانتا ہے، مرعوب ہو جائیں۔ اور تم اللہ کی راہ میں جو کچھ خرچ کرو گے وہ تمہیں پورا دیا جائے گا اور تم پر ظلم نہیں ہوگا۔ ",
        "persian_text": "و هر نیرویی که توانستید برای مقابله با آنان آماده کنید، از اسب‌های بسته، تا بدان وسیله دشمن خدا و دشمن خود را بترسانید و دیگرانی را که شما نمی‌شناسید و خدا می‌شناسد. و هر چه در راه خدا انفاق کنید، تمام به شما بازگردانده می‌شود و بر شما ستم نخواهد شد.",
        "english_text": "And prepare against them whatever you are able of power and of steeds of war by which you may terrify the enemy of Allah and your enemy and others besides them whom you do not know but Allah knows them. And whatever you spend in the cause of Allah will be fully repaid to you, and you will not be wronged.",
        "transliteration": "Wa a'iddoo lahum mas tata'tum min quwwatinw-wa mir ribaatil khaili turhiboona bihee 'aduwwal laahi wa 'aduwwakum wa aakhareena min doonihim laa ta'lamoonahumul laahu ya'lamuhum; wa maa tunfiqoo min shai'in fee sabeelil laahi yuwaffa ilaikum wa antum laa tuzlamoon.",
    },
    {
        "verse_number": "61",
        "arabic_text": "وَ اِنْ جَنَحُوْا لِلسَّلْمِ فَاجْنَحْ لَهَا وَ تَوَكَّلْ عَلَى اللّٰهِ ۚ اِنَّهُ هُوَ السَّمِيْعُ الْعَلِيْمُ",
        "urdu_text": "اور اگر وہ صلح کی طرف جھکیں تو آپ بھی اس کی طرف جھک جائیں اور اللہ پر بھروسہ کریں۔ بے شک وہ سننے والا جاننے والا ہے۔ ",
        "persian_text": "و اگر آنان به صلح گراییدند، تو نیز بدان گرای و بر خدا توکل کن؛ که او شنوای داناست.",
        "english_text": "And if they incline to peace, then incline to it [also] and rely upon Allah. Indeed, it is He who is the Hearing, the Knowing.",
        "transliteration": "Wa in janahoo lissalmi fajnah lahaa wa tawakkal 'alal laah; innahoo Huwas Samee'ul 'Aleem.",
    },
    {
        "verse_number": "62",
        "arabic_text": "وَ اِنْ يُرِيْدُوا اَنْ يَخْدَعُوْكَ فَاِنَّ حَسْبَكَ اللّٰهُ ۚ هُوَ الَّذِيْٓ اَيَّدَكَ بِنَصْرِهِ وَ بِالْمُؤْمِنِيْنَ",
        "urdu_text": "اور اگر وہ آپ کو دھوکہ دینا چاہیں تو آپ کے لئے اللہ کافی ہے۔ وہی ہے جس نے اپنی مدد اور ایمان والوں کے ذریعے آپ کی تائید کی۔ ",
        "persian_text": "و اگر بخواهند تو را فریب دهند، خدا برایت کافی است؛ همان کسی که تو را به یاری خویش و مؤمنان تقویت کرد.",
        "english_text": "But if they intend to deceive you - then sufficient for you is Allah. It is He who supported you with His help and with the believers.",
        "transliteration": "Wa iny-yureedooo an yakhd'ooka fa innahasbakat laah; Huwal lazee ayyadaka binasrihee wa bilmu'mineen.",
    },
    {
        "verse_number": "63",
        "arabic_text": "وَ اَلَّفَ بَيْنَ قُلُوْبِهِمْ ۚ لَوْ اَنْفَقْتَ مَا فِي الْاَرْضِ جَمِيْعًا مَّا اَلَّفْتَ بَيْنَ قُلُوبِهِمْ وَ لٰكِنَّ اللّٰهَ اَلَّفَ بَيْنَهُمْ ۚ اِنَّهُ عَزِيْزٌ حَكِيْمٌ",
        "urdu_text": "اور ان کے دلوں میں الفت پیدا کی۔ اگر آپ زمین میں جو کچھ ہے سب خرچ کر ڈالتے تو بھی ان کے دلوں میں الفت پیدا نہ کر سکتے لیکن اللہ نے ان میں الفت ڈال دی۔ بے شک وہ غالب حکمت والا ہے۔ ",
        "persian_text": "و میان دل‌هایشان الفت انداخت؛ اگر همه آنچه در زمین است خرج می‌کردی، نمی‌توانستی میان دل‌هایشان الفت افکنی؛ ولی خدا میان آنان الفت انداخت. او شکست‌ناپذیر حکیم است.",
        "english_text": "And He brought their hearts together. If you had spent all that is in the earth, you could not have brought their hearts together; but Allah brought them together. Indeed, He is Exalted in Might and Wise.",
        "transliteration": "Wa allafa baina quloobihim; law anfaqta maafil ardi jamee'am maa allafta baina quloobihim wa laakinnal laaha allafa bainahum; innahoo 'azeezun hakeem.",
    },
    {
        "verse_number": "64",
        "arabic_text": "يٰٓاَيُّهَا النَّبِيُّ حَسْبُكَ اللّٰهُ وَ مَنِ اتَّبَعَكَ مِنَ الْمُؤْمِنِيْنَ",
        "urdu_text": "اے نبی! آپ کے لئے اللہ کافی ہے اور آپ کے پیروی کرنے والے مؤمنین بھی۔ ",
        "persian_text": "ای پیامبر! خدا برایت کافی است و نیز مؤمنانی که از تو پیروی کردند.",
        "english_text": "O Prophet, sufficient for you is Allah and for whoever follows you of the believers.",
        "transliteration": "Yaaa ayyuhan Nabiyyu hasbukal laahu wa manittaba'aka minal mu'mineen.",
    },
    {
        "verse_number": "65",
        "arabic_text": "يَٰاَيُّهَا النَّبِيُّ حَرِّضِ الْمُؤْمِنِيْنَ عَلَى الْقِتَالِ ۚ اِنْ يَّكُنْ مِّنْكُمْ عِشْرُوْنَ صٰبِرُونَ يَغْلِبُوْا مِائَتَيْنِ ۚ وَ اِنْ يَّكُنْ مِّنْكُم مِّائَةٌ يَّغْلِبُوْٓا اَلْفًا مِّنَ الَّذِيْنَ كَفَرُوْا بِاَنَّهُمْ قَوْمٌ لَّا يَفْقَهُوْنَ",
        "urdu_text": "اے نبی! ایمان والوں کو قتال پر ابھاریں۔ اگر تم میں سے بیس صبر کرنے والے ہوں تو وہ دو سو پر غالب آئیں گے اور اگر تم میں سے سو ہوں تو وہ کافروں کے ہزار پر غالب آئیں گے، کیونکہ وہ سمجھنے والے لوگ نہیں ہیں۔ ",
        "persian_text": "ای پیامبر! مؤمنان را به جنگ برانگیز. اگر از شما بیست تن شکیبا باشند، بر دویست تن پیروز می‌شوند؛ و اگر صد تن باشند، بر هزار تن از کافران پیروز می‌شوند، زیرا آنان قومی نادانند.",
        "english_text": "O Prophet, urge the believers to battle. If there are among you twenty who are steadfast, they will overcome two hundred. And if there are among you one hundred, they will overcome a thousand of those who disbelieve because they are a people who do not understand.",
        "transliteration": "Yaaa ayyuhan Nabiyyu harridil mu'mineena 'alal qitaal; iny-yakun minkum 'ishroona saabiroona yaghliboo mi'atain; wa iny-yakun minkum mi'atuny yaghliboo alfaam minal lazeena kafaroo bi annahum qawmul laa yafqahoon.",
    },
    {
        "verse_number": "66",
        "arabic_text": "اَلْئٰنَ خَفَّفَ اللّٰهُ عَنْكُمْ وَ عَلِمَ اَنَّ فِيْكُمْ ضَعْفًا فَاِنْ يَّكُنْ مِّنْكُم مِّائَةٌ صَابِرَةٌ يَغْلِبُوْاْ مِائَتَيْنِ ۚ وَ اِنْ يَّكُنْ مِّنْكُمْ اَلْفٌ يَّغْلِبُوْآ اَلْفَيْنِ بِاِذْنِ اللّٰهِ ۗ وَ اللّٰهُ مَعَ الصّٰبِرِيْنَ",
        "urdu_text": "اب اللہ نے تم سے بوجھ ہلکا کر دیا اور اس نے جان لیا کہ تم میں کمزوری ہے، پس اگر تم میں سے سو صبر کرنے والے ہوں تو وہ دو سو پر غالب آئیں گے اور اگر تم میں سے ایک ہزار ہوں تو اللہ کے حکم سے دو ہزار پر غالب آئیں گے، اور اللہ صبر کرنے والوں کے ساتھ ہے۔",
        "persian_text": "اکنون خدا بر شما تخفیف داد و دانست که در شما ضعفی است؛ پس اگر صد تن شکیبا باشید، بر دویست نفر چیره می‌شوید، و اگر هزار نفر باشید، به اذن خدا بر دو هزار غلبه می‌کنید، و خدا با شکیبایان است.",
        "english_text": "Now Allah has lightened for you, and He knows that there is weakness in you. So if there are a hundred steadfast among you, they will overcome two hundred. And if there are a thousand of you, they will overcome two thousand by permission of Allah. And Allah is with the steadfast.",
        "transliteration": "Al-āna khaffafa Allahu 'ankum wa 'alima anna feekum da'fan fa-in yakun minkum mi'atun saabiratun yaghliboo mi'atayn; wa in yakun minkum alfun yaghliboo alfayni bi-ithni Allahi wallahu ma'a as-saabireen.",
    },
    {
        "verse_number": "67",
        "arabic_text": "مَا كَانَ لِنَبِيٍّ اَنْ يَّكُوْنَ لَهُٓ اَسْرٰى حَتّٰى يُثْخِنَ فِىْ الْاَرْضِ ۚ تُرِيْدُوْنَ عَرَضَ الدُّنْيَا وَ اللّٰهُ يُرِيدُ الْاٰخِرَةَ ۗ وَ اللّٰهُ عَزِيْزٌ حَكِيْمٌ",
        "urdu_text": "کسی نبی کے لائق نہیں کہ اس کے پاس قیدی ہوں جب تک کہ وہ زمین میں اچھی طرح غالب نہ آ جائے، تم دنیا کا مال چاہتے ہو اور اللہ آخرت چاہتا ہے، اور اللہ غالب حکمت والا ہے۔",
        "persian_text": "برای هیچ پیامبری روا نیست که تا در زمین به اندازه کافی قدرت نیافته، اسیرانی داشته باشد؛ شما کالای دنیا را می‌خواهید و خدا آخرت را می‌خواهد؛ و خدا عزیز و حکیم است.",
        "english_text": "It is not for a prophet to have captives until he has thoroughly subdued in the land. You desire the commodities of this world, but Allah desires the Hereafter. And Allah is Exalted in Might, Wise.",
        "transliteration": "Ma kana li-nabiyyin an yakoona lahu asraa hatta yuthkhina fil-ardi tureedoona 'arada ad-dunya wallahu yureedu al-akhirata wallahu 'azeezun hakeem.",
    },
    {
        "verse_number": "68",
        "arabic_text": "لَّوْلَا كِتٰبٌ مِّنَ اللّٰهِ سَبَقَ لَمَسَّكُمْ فِيْمَآ اَخَذْتُمْ عَذَابٌ عَظِيْمٌ",
        "urdu_text": "اگر اللہ کی طرف سے پہلے لکھا ہوا نہ ہوتا تو جو کچھ تم نے لیا اس میں تمہیں بڑا عذاب آ پہنچتا۔",
        "persian_text": "اگر نوشتۀ خدا از پیش نبود، به سبب آنچه گرفتید، عذاب بزرگی شما را فرو می‌گرفت.",
        "english_text": "Had it not been for a decree from Allah that had already preceded, you would have been touched for what you took by a great punishment.",
        "transliteration": "Law la kitaabum mina Allahi sabaqa lamassakum feemaa akhathtum 'adhaabun 'azeem.",
    },
    {
        "verse_number": "69",
        "arabic_text": "فَكُلُوْاْ مِمَّا غَنِمْتُمْ حَلٰلًا طَيِّبًا ۚ وَّ اتَّقُوْاْ اللّٰهَ ۚ اِنَّ اللّٰهَ غَفُوْرٌ رَّحِيْمٌ",
        "urdu_text": "پس جو مالِ غنیمت تم نے حاصل کیا ہے اسے حلال اور پاکیزہ طور پر کھاؤ، اور اللہ سے ڈرو، بے شک اللہ بخشنے والا مہربان ہے۔",
        "persian_text": "پس از آنچه غنیمت گرفته‌اید، حلال و پاکیزه بخورید و از خدا پروا کنید؛ همانا خدا آمرزنده مهربان است.",
        "english_text": "So consume what you have taken of war booty as being lawful and good, and fear Allah. Indeed, Allah is Forgiving and Merciful.",
        "transliteration": "Fa kuloo mimma ghanimtum halaalan tayyiban wattaqoo Allaha innallaha ghafoorun raheem.",
    },
    {
        "verse_number": "70",
        "arabic_text": "يٰٓاَيُّهَا النَّبِىُّ قُل لِّمَنْ فِىْٓ اَيْدِيْكُم مِّنَ الْاَسْرٰٓى اِنْ يَّعْلَمِ اللّٰهُ فِىْ قُلُوْبِكُمْ خَيْرًا يُؤْتِكُمْ خَيْرًا مِّمَّآ اُخِذَ مِنْكُمْ وَ يَغْفِرْ لَكُمْ ۗ وَ اللّٰهُ غَفُوْرٌ رَّحِيْمٌ",
        "urdu_text": "اے نبی! ان قیدیوں سے کہہ دو جو تمہارے ہاتھوں میں ہیں، اگر اللہ تمہارے دلوں میں کوئی بھلائی دیکھے گا تو تمہیں اس سے بہتر دے گا جو تم سے لیا گیا ہے اور تمہیں بخش دے گا، اور اللہ بخشنے والا مہربان ہے۔",
        "persian_text": "ای پیامبر! به اسیرانی که در دست شما هستند بگو: اگر خدا در دل‌هایتان خیری بداند، بهتر از آنچه از شما گرفته شده به شما می‌دهد و شما را می‌آمرزد، و خدا آمرزنده مهربان است.",
        "english_text": "O Prophet, say to whoever is in your hands of the captives, 'If Allah knows any good in your hearts, He will give you something better than what was taken from you and He will forgive you.' And Allah is Forgiving and Merciful.",
        "transliteration": "Ya ayyuhan nabiyyu qul liman fee aideekum minal asraa in ya'lamillahu fee quloobikum khayran yu'tikum khayran mimma ukhitha minkum wayaghfir lakum wallahu ghafoorur raheem.",
    },
    {
        "verse_number": "71",
        "arabic_text": "ْوَ اِن يُّرِيْدُوْاْ خِيَانَتَكَ فَقَدْ خَانُوْاْ اللّٰهَ مِن قَبْلُ فَاَمْكَنَ مِنْهُمْ ۗ وَ اللّٰهُ عَلِيْمٌ حَكِيْمٌ",
        "urdu_text": "اور اگر وہ تمہارے ساتھ خیانت کرنا چاہیں تو وہ اس سے پہلے اللہ کے ساتھ خیانت کر چکے ہیں تو اس نے انہیں تمہارے قابو میں کر دیا، اور اللہ سب کچھ جاننے والا حکمت والا ہے۔",
        "persian_text": "و اگر بخواهند به تو خیانت کنند، پیش از این به خدا خیانت کردند، پس او آنان را در اختیار تو قرار داد؛ و خدا دانای حکیم است.",
        "english_text": "But if they intend to betray you, then they have already betrayed Allah before, and He empowered you over them. And Allah is Knowing and Wise.",
        "transliteration": "Wa in yureedoo khiyanataka faqad khaanoo Allaha min qablu fa-amkana minhum wallahu 'aleemun hakeem.",
    },
    {
        "verse_number": "72",
        "arabic_text": "اِنَّ الَّذِيْنَ اٰمَنُوْاْ وَ هَاجَرُوْاْ وَ جَاهَدُوْاْ بِاَمْوَالِهِمْ وَ اَنْفُسِهِمْ فِىْ سَبِيْلِ اللّٰهِ وَ الَّذِيْنَ اٰوَوْاْ وَّ نَصَرُوٓاْ اُوْلٰٓئِكَ بَعْضُهُمْ اَوْلِيَآءُ بَعْضٍ ۚ وَ الَّذِيْنَ اٰمَنُواْ وَ لَمْ يُهَاجِرُوْاْ مَا لَكُم مِّنْ وَّلَايَتِهِم مِّن شَىْءٍ حَتّٰى يُهَاجِرُواْ ۚ وَ اِنِ اسْتَنْصَرُوْكُمْ فِى الدِّيْنِ فَعَلَيْكُمُ النَّصْرُ اِلَّا عَلٰى قَوْمٍ بَيْنَكُمْ وَ بَيْنَهُمْ مِّيْثَاقٌ ۗ وَ اللّٰهُ بِمَا تَعْمَلُوْنَ بَصِيْرٌ",
        "urdu_text": "بیشک جو لوگ ایمان لائے اور ہجرت کی اور اللہ کی راہ میں اپنے مالوں اور اپنی جانوں سے جہاد کیا، اور جنہوں نے پناہ دی اور مدد کی، وہ سب ایک دوسرے کے رفیق ہیں، اور جو لوگ ایمان لائے اور ہجرت نہیں کی تمہارے لیے ان کی ولایت میں سے کچھ نہیں ہے جب تک وہ ہجرت نہ کریں، اور اگر وہ دین کے بارے میں تم سے مدد مانگیں تو تم پر مدد کرنا فرض ہے مگر اس قوم کے خلاف نہیں جن کے ساتھ تمہارا معاہدہ ہے، اور اللہ تمہارے عملوں کو خوب دیکھتا ہے۔",
        "persian_text": "کسانی که ایمان آوردند و هجرت کردند و با اموال و جان‌هایشان در راه خدا جهاد کردند، و آنان که پناه دادند و یاری کردند، ایشان دوستان یکدیگرند؛ و کسانی که ایمان آوردند و هجرت نکردند، هیچ گونه ولایتی از جانب شما بر آنان نیست تا زمانی که هجرت کنند؛ و اگر در دین از شما یاری بخواهند، بر شماست که یاریشان کنید، مگر بر ضد مردمی که میان شما و ایشان پیمانی باشد؛ و خداوند به آنچه انجام می‌دهید بیناست.",
        "english_text": "Indeed, those who have believed and emigrated and striven with their wealth and lives in the cause of Allah and those who gave shelter and aided—they are allies of one another. But those who believed and did not emigrate—for you there is no guardianship of them until they emigrate. But if they seek help of you in religion, then you must help them except against a people with whom you have a treaty. And Allah is Seeing of what you do.",
        "transliteration": "Inna allatheena amanoo wahajaroo wajahadoo bi-amwalihim waanfusihim fee sabeeli Allahi wallatheena awaw wanassaroo ola-ika baAAduhum awliyaa'u baAAd; wallatheena amanoo walam yuhajiroo ma lakum min walayatihim min shay-in hatta yuhajiroo wa-ini istansarookum fee ad-deeni faAAalaykumu annasru illa AAala qawmin baynakum wabaynahum meethaq; wallahu bima taAAmaloona baseer.",
    },
    {
        "verse_number": "73",
        "arabic_text": "وَ الَّذِيْنَ كَفَرُوْاْ بَعْضُهُمْ اَوْلِيَآءُ بَعْضٍ ۚ اِلَّا تَفْعَلُوْهُ تَكُنْ فِتْنَةٌ فِىْ الْاَرْضِ وَ فَسَادٌ كَبِيْرٌ",
        "urdu_text": "اور جو لوگ کافر ہیں وہ ایک دوسرے کے رفیق ہیں، اگر تم ایسا نہ کرو گے تو زمین میں فتنہ اور بڑا فساد ہو جائے گا۔",
        "persian_text": "و کسانی که کفر ورزیدند، دوستان یکدیگرند؛ اگر شما چنین نکنید، در زمین فتنه و فساد بزرگی پدید خواهد آمد.",
        "english_text": "And those who disbelieved are allies of one another. If you do not do so, there will be fitnah in the land and great corruption.",
        "transliteration": "Wallatheena kafaroo baAAduhum awliyaa'u baAAd; illa tafAAaloohu takun fitnatun fee al-ardi wafasadun kabeer.",
    },
    {
        "verse_number": "74",
        "arabic_text": "وَ الَّذِينَ اٰمَنُواْ وَ هَاجَرُوْاْ وَ جَاهَدُوْاْ فِىْ سَبِيْلِ اللّٰهِ وَ الَّذِيْنَ اوَوّاْ وَّ نَصَرُوْٓاْ اُوْلٰٓئِكَ هُمُ الْمُؤْمِنُوْنَ حَقًّا ۚ لَّهُمْ مَّغْفِرَةٌ وَّ رِزْقٌ كَرِيْمٌ",
        "urdu_text": "اور جو لوگ ایمان لائے اور ہجرت کی اور اللہ کی راہ میں جہاد کیا اور جنہوں نے پناہ دی اور مدد کی، یہی لوگ سچے مومن ہیں، ان کے لیے بخشش اور عزت کی روزی ہے۔",
        "persian_text": "و کسانی که ایمان آوردند و هجرت کردند و در راه خدا جهاد نمودند، و آنان که پناه دادند و یاری کردند، اینان مؤمنان راستین‌اند؛ برایشان آمرزش و روزی کریمانه است.",
        "english_text": "And those who believed and emigrated and strove in the cause of Allah and those who gave shelter and aided—it is they who are the true believers. For them is forgiveness and a noble provision.",
        "transliteration": "Wallatheena amanoo wahajaroo wajahadoo fee sabeeli Allahi wallatheena awaw wanassaroo ola-ika humu almu'minoona haqqan lahum maghfiratun warizqun kareem.",
    },
    {
        "verse_number": "75",
        "arabic_text": "وَ الَّذِيْنَ اٰمَنُوْاْ مِنْ بَعْدُ وَ هَاجَرُوْاْ وَ جَاهَدُوْاْ مَعَكُمْ فَاُوْلٰٓئِكَ مِنْكُمْ ۚ وَ اُوْلُوْاْ الْاَرْحَامِ بَعْضُهُمْ اَوْلٰى بِبَعْضٍ فِى كِتٰبِ اللّٰهِ ۗ اِنَّ اللّٰهَ بِكُلِّ شَىْءٍ عَلِيْمٌ",
        "urdu_text": "اور جو لوگ اس کے بعد ایمان لائے اور ہجرت کی اور تمہارے ساتھ جہاد کیا تو وہ تم میں سے ہیں، اور رشتہ دار اللہ کے حکم میں ایک دوسرے کے زیادہ حق دار ہیں، بے شک اللہ ہر چیز کو جاننے والا ہے۔",
        "persian_text": "و کسانی که پس از آن ایمان آوردند و هجرت کردند و همراه شما جهاد نمودند، آنان از شما هستند؛ و خویشاوندان در کتاب خدا نسبت به یکدیگر سزاوارترند؛ همانا خدا به هر چیزی داناست.",
        "english_text": "And those who believed afterward and emigrated and strove with you—they are of you. And those of blood relationship are more entitled to inheritance in the Book of Allah. Indeed, Allah is Knowing of all things.",
        "transliteration": "Wallatheena amanoo min baAAdu wahajaroo wajahadoo maAAakum faola-ika minkum wa-ooloo al-arhami baAAduhum awla bibaAAdin fee kitabi Allahi inna Allaha bikulli shay-in 'aleem.",
    },
]
