ayats = [
    {
        "verse_number": "1",
        "arabic_text": "وَالسَّمَاءِ ذَاتِ الْبُرُوجِ",
        "urdu_text": "قسم ہے آسمان کی جس میں بڑے بڑے برج ہیں",
        "persian_text": "سوگند به آسمان دارای برج‌های بزرگ",
        "english_text": "By the sky with its great constellations,",
        "transliteration": "Was-samā’i dhātil-burūj",
    },
    {
        "verse_number": "2",
        "arabic_text": "وَاليَوْمِ الْمَوْعُودِ",
        "urdu_text": "اور اس دن کی جو وعدہ کیا گیا ہے",
        "persian_text": "و به روز موعود",
        "english_text": "And [by] the promised Day,",
        "transliteration": "Wa alyawmi almawʿūd",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَشَاهِدٍ وَمَشْهُودٍ",
        "urdu_text": "اور حاضر ہونے والے اور جس کے سامنے حاضر ہوا جائے",
        "persian_text": "و به گواه و گواهی داده شده",
        "english_text": "And [by] the witness and what is witnessed,",
        "transliteration": "Wa shāhidin wa mashhūd",
    },
    {
        "verse_number": "4",
        "arabic_text": "قُتِلَ أَصْحَابُ الْأُخْدُودِ",
        "urdu_text": "مارے گئے خندقوں والے",
        "persian_text": "نابود باد یاران خندق",
        "english_text": "Cursed were the companions of the trench",
        "transliteration": "Qutila aṣḥābul-ukhdūd",
    },
    {
        "verse_number": "5",
        "arabic_text": "النَّارِ ذَاتِ الْوَقُودِ",
        "urdu_text": "جلتی آگ والے ایندھن سے",
        "persian_text": "آتش پر سوخته با هیزم فراوان",
        "english_text": "The fire full of fuel,",
        "transliteration": "An-nāri dhātil-waqūd",
    },
    {
        "verse_number": "6",
        "arabic_text": "إِذْ هُمْ عَلَيْهَا قُعُودٌ",
        "urdu_text": "جب وہ اس پر بیٹھے ہوئے تھے",
        "persian_text": "آنگاه که خود بر آن نشسته بودند",
        "english_text": "When they were sitting near it",
        "transliteration": "Idh hum ʿalayhā quʿūd",
    },
    {
        "verse_number": "7",
        "arabic_text": "وَهُمْ عَلَىٰ مَا يَفْعَلُونَ بِالْمُؤْمِنِينَ شُهُودٌ",
        "urdu_text": "اور وہ ایمان والوں کے ساتھ جو کچھ کر رہے تھے، گواہ تھے",
        "persian_text": "و بر آنچه با مؤمنان می‌کردند، گواه بودند",
        "english_text": "And they, to what they were doing against the believers, were witnesses.",
        "transliteration": "Wa hum ʿalā mā yafʿalūna bil-mu’minīn shuhūd",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَمَا نَقَمُوا مِنْهُمْ إِلَّا أَن يُؤْمِنُوا بِاللَّهِ الْعَزِيزِ الْحَمِيدِ",
        "urdu_text": "اور ان سے بدلہ صرف اس بات پر لیا گیا کہ وہ اللہ پر ایمان لائے تھے جو زبردست، تعریف کے لائق ہے",
        "persian_text": "و تنها به این جرم از ایشان کینه ورزیدند که به خدای عزیز و ستوده ایمان آورده بودند",
        "english_text": "And they resented them not except because they believed in Allah, the Exalted in Might, the Praiseworthy,",
        "transliteration": "Wa mā naqamu minhum illā an yu’minū billāhil-ʿazīzil-ḥamīd",
    },
    {
        "verse_number": "9",
        "arabic_text": "الَّذِي لَهُ مُلْكُ السَّمَاوَاتِ وَالْأَرْضِ ۚ وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ شَهِيدٌ",
        "urdu_text": "جس کے لیے آسمانوں اور زمین کی بادشاہی ہے، اور اللہ ہر چیز پر گواہ ہے",
        "persian_text": "آن کسی که فرمانروایی آسمان‌ها و زمین از آن اوست، و خدا بر هر چیز گواه است",
        "english_text": "To whom belongs the dominion of the heavens and the earth. And Allah, over all things, is Witness.",
        "transliteration": "Alladhī lahu mulkus-samāwāti wal-arḍ, wallāhu ʿalā kulli shay’in shahīd",
    },
    {
        "verse_number": "10",
        "arabic_text": "إِنَّ الَّذِينَ فَتَنُوا الْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ ثُمَّ لَمْ يَتُوبُوا فَلَهُمْ عَذَابُ جَهَنَّمَ وَلَهُمْ عَذَابُ الْحَرِيقِ",
        "urdu_text": "بے شک جن لوگوں نے مومن مردوں اور مومن عورتوں کو ستایا پھر توبہ نہ کی، ان کے لیے جہنم کا عذاب ہے اور ان کے لیے جلنے کا عذاب ہے",
        "persian_text": "همانا کسانی که مردان و زنان مؤمن را شکنجه دادند و توبه نکردند، عذاب دوزخ و آتش سوزان برای آنان است",
        "english_text": "Indeed, those who have tortured the believing men and believing women and then have not repented will have the punishment of Hell, and they will have the punishment of the Burning Fire.",
        "transliteration": "Inna alladhīna fatanul-mu’minīna wal-mu’mināti thumma lam yatūbū falahum ʿadhābu jahannama walahum ʿadhābul-ḥarīq",
    },
    {
        "verse_number": "85:11",
        "arabic_text": "إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ لَهُمْ جَنَّـٰتٌۭ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَـٰرُ ۚ ذَٰلِكَ ٱلْفَوْزُ ٱلْكَبِيرُ",
        "urdu_text": "بیشک جو لوگ ایمان لائے اور نیک عمل کیے، ان کے لیے باغات ہیں جن کے نیچے نہریں بہتی ہیں، یہی بڑی کامیابی ہے۔",
        "persian_text": "بی‌گمان آنان که ایمان آوردند و کارهای شایسته کردند، برای‌شان باغ‌هایی است که نهرها از زیر آن جاری است. این است رستگاری بزرگ.",
        "english_text": "Indeed, those who believe and do righteous deeds will have gardens beneath which rivers flow. That is the greatest success.",
        "transliteration": "Inna alladhīna āmanū wa ʿamilū aṣ-ṣāliḥāti lahum jannātun tajrī min taḥtihā al-anhāru dhālika al-fawzu al-kabīr",
    },
    {
        "verse_number": "85:12",
        "arabic_text": "إِنَّ بَطْشَ رَبِّكَ لَشَدِيدٌۭ",
        "urdu_text": "بیشک تیرے رب کی پکڑ بہت سخت ہے۔",
        "persian_text": "همانا گرفتن پروردگار تو بسیار سخت است.",
        "english_text": "Indeed, the punishment of your Lord is severe.",
        "transliteration": "Inna baṭsha rabbika lashadīd",
    },
    {
        "verse_number": "85:13",
        "arabic_text": "إِنَّ بَطْشَ رَبِّكَ لَشَدِيدٌ",
        "urdu_text": "بے شک تمہارے رب کی پکڑ بڑی سخت ہے۔",
        "persian_text": "همانا گرفتن پروردگارت سخت است.",
        "english_text": "Indeed, the punishment of your Lord is severe.",
        "transliteration": "Inna baṭsha rabbika lashadīd",
    },
    {
        "verse_number": "85:14",
        "arabic_text": "إِنَّهُۥ هُوَ يُبْدِئُ وَيُعِيدُ",
        "urdu_text": "بے شک وہی پہلی بار پیدا کرتا ہے اور دوبارہ زندہ کرے گا۔",
        "persian_text": "اوست که آغاز می‌کند و بازمی‌گرداند.",
        "english_text": "Indeed, it is He who originates [creation] and repeats.",
        "transliteration": "Innahu huwa yubdi'u wa yuʿīd",
    },
    {
        "verse_number": "85:15",
        "arabic_text": "وَهُوَ ٱلْغَفُورُ ٱلْوَدُودُ",
        "urdu_text": "اور وہی بڑا بخشنے والا، محبت کرنے والا ہے۔",
        "persian_text": "و اوست آمرزنده مهربان.",
        "english_text": "And He is the Forgiving, the Affectionate.",
        "transliteration": "Wa huwa al-ghafūru al-wadūd",
    },
    {
        "verse_number": "85:16",
        "arabic_text": "ذُو ٱلْعَرْشِ ٱلْمَجِيدُ",
        "urdu_text": "عرش والا، بزرگی والا۔",
        "persian_text": "صاحب عرش با شکوه.",
        "english_text": "Owner of the Glorious Throne.",
        "transliteration": "Dhū al-ʿarshi al-majīd",
    },
    {
        "verse_number": "85:17",
        "arabic_text": "فَعَّالٌۭ لِّمَا يُرِيدُ",
        "urdu_text": "جو چاہے کرنے والا ہے۔",
        "persian_text": "هر آنچه خواهد، انجام می‌دهد.",
        "english_text": "Executor of whatever He wills.",
        "transliteration": "Fāʿālun limā yurīd",
    },
    {
        "verse_number": "85:18",
        "arabic_text": "هَلْ أَتَىٰكَ حَدِيثُ ٱلْجُنُودِ",
        "urdu_text": "کیا تمہیں لشکروں کی خبر پہنچی ہے؟",
        "persian_text": "آیا خبر لشکرها به تو رسیده است؟",
        "english_text": "Has there reached you the story of the soldiers?",
        "transliteration": "Hal atāka ḥadīthu al-junūd",
    },
    {
        "verse_number": "85:19",
        "arabic_text": "فِرْعَوْنَ وَثَمُودَ",
        "urdu_text": "فرعون اور ثمود کے (لشکر)،",
        "persian_text": "فرعون و ثمود،",
        "english_text": "Of Pharaoh and Thamud?",
        "transliteration": "Firʿawna wa Thamūd",
    },
    {
        "verse_number": "85:20",
        "arabic_text": "بَلِ ٱلَّذِينَ كَفَرُوا۟ فِى تَكْذِيبٍۢ",
        "urdu_text": "بلکہ یہ کافر جھٹلانے میں لگے ہوئے ہیں۔",
        "persian_text": "بلکه کافران در تکذیب هستند.",
        "english_text": "But those who disbelieve are in [persistent] denial.",
        "transliteration": "Bali alladhīna kafarū fī takdhīb",
    },
    {
        "verse_number": "85:21",
        "arabic_text": "وَٱللَّهُ مِن وَرَآئِهِم مُّحِيطٌۭ",
        "urdu_text": "اور اللہ ان کے پیچھے سے انہیں گھیرے ہوئے ہے۔",
        "persian_text": "و خدا از پشت سرشان بر آنان احاطه دارد.",
        "english_text": "But Allah encompasses them from behind.",
        "transliteration": "Wa allāhu min warā'ihim muḥīṭ",
    },
    {
        "verse_number": "85:22",
        "arabic_text": "بَلْ هُوَ قُرْءَانٌۭ مَّجِيدٌۭ ﴿٢١﴾ فِى لَوْحٍۢ مَّحْفُوظٍۢ",
        "urdu_text": "بلکہ یہ قرآن بڑی شان والا ہے۔ لوح محفوظ میں (لکھا ہوا) ہے۔",
        "persian_text": "بلکه این قرآنی است بزرگوار، که در لوح محفوظ ثبت شده است.",
        "english_text": "But this is an honored Qur'an, [Inscribed] in a Preserved Tablet.",
        "transliteration": "Bal huwa Qur'ānun majīdun fī lawḥin maḥfūẓ",
    },
]
