ayats = [
    {
        "verse_number": "1",
        "arabic_text": "لَمْ يَكُنِ الَّذِينَ كَفَرُوا مِنْ اَهْلِ الْكِتَـٰبِ وَالْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَاْتِيَهُمُ الْبَيِّنَةُ",
        "urdu_text": "کافر لوگ، اہل کتاب اور مشرکین میں سے باز آنے والے نہ تھے جب تک کہ ان کے پاس کھلی دلیل نہ آ جائے",
        "persian_text": "کافران از اهل کتاب و مشرکان بازنمی‌گردند تا زمانی که دلیل روشنی برایشان بیاید.",
        "english_text": "The disbelievers among the People of the Book and the polytheists were not to desist until there came to them clear evidence.",
        "transliteration": "Lam yakuni alladhīna kafarū min ahli al-kitābi wa al-mushrikīna munfakkīna ḥattā ta’tiyahumu al-bayyinah",
    },
    {
        "verse_number": "2",
        "arabic_text": "رَسُولٌۭ مِّنَ اللَّهِ يَتْلُوا صُحُفًۭا مُّطَهَّرَةًۭ",
        "urdu_text": "اللہ کا ایک رسول جو پاکیزہ صحیفے پڑھ کر سناتا ہے",
        "persian_text": "فرستاده‌ای از سوی خدا که صحیفه‌های پاک را تلاوت می‌کند.",
        "english_text": "A messenger from Allah, reciting purified scriptures.",
        "transliteration": "Rasūlun mina Allāhi yatlū ṣuḥufan muṭahharah",
    },
    {
        "verse_number": "3",
        "arabic_text": "فِيهَا كُتُبٌ قَيِّمَةٌۭ",
        "urdu_text": "جن میں صحیح اور درست احکام درج ہیں",
        "persian_text": "که در آن‌ها نوشته‌هایی استوار و درست است.",
        "english_text": "Within which are correct and upright writings.",
        "transliteration": "Fīhā kutubun qayyimah",
    },
    {
        "verse_number": "4",
        "arabic_text": "وَمَا تَفَرَّقَ الَّذِينَ اُوتُوا الْكِتَـٰبَ اِلَّا مِن بَعْدِ مَا جَآءَتْهُمُ الْبَيِّنَةُ",
        "urdu_text": "اور اہل کتاب کے وہ لوگ فرقوں میں نہ بٹے تھے جب تک ان کے پاس کھلی دلیل نہ آ گئی",
        "persian_text": "و کسانی که کتاب به آنان داده شده بود، پراکنده نشدند مگر پس از آنکه دلیل روشن برایشان آمد.",
        "english_text": "Nor did those who were given the Scripture become divided until after there had come to them clear evidence.",
        "transliteration": "Wa mā tafarraqa alladhīna ūtū al-kitāba illā min baʿdi mā jā’athumu al-bayyinah",
    },
    {
        "verse_number": "5",
        "arabic_text": "وَمَآ اُمِرُوٓا اِلَّا لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ حُنَفَآءَ وَيُقِيمُوا الصَّلَوٰةَ وَيُؤْتُوا الزَّكَوٰةَ ۚ وَذَٰلِكَ دِينُ الْقَيِّمَةِ",
        "urdu_text": "حالانکہ ان کو حکم یہی دیا گیا تھا کہ اللہ کی عبادت کریں، اسی کے لیے دین کو خالص کرتے ہوئے، یکسو ہو کر، نماز قائم کریں اور زکٰوۃ دیں۔ یہی سیدھا دین ہے",
        "persian_text": "در حالی که به آنان فرمان داده نشده بود جز اینکه خدا را بپرستند در حالی که دین خود را برای او خالص می‌کنند، و نماز بپا دارند و زکات بدهند، و این است دین درست و استوار.",
        "english_text": "And they were not commanded except to worship Allah, [being] sincere to Him in religion, inclining to truth, and to establish prayer and to give zakah. And that is the correct religion.",
        "transliteration": "Wa mā umirū illā liyaʿbudū Allāha mukhliṣīna lahu al-dīna ḥunafā’a wa yuqīmū al-ṣalāta wa yu’tū al-zakāh; wa dhālika dīn al-qayyimah",
    },
    {
        "verse_number": "6",
        "arabic_text": "اِنَّ الَّذِينَ كَفَرُوا مِنْ اَهْلِ الْكِتَـٰبِ وَالْمُشْرِكِينَ فِى نَارِ جَهَنَّمَ خَـٰلِدِينَ فِيهَآ ۚ اُولَـٰٓئِكَ هُمْ شَرُّ الْبَرِيَّةِ",
        "urdu_text": "بیشک جن لوگوں نے کفر کیا، اہل کتاب میں سے اور مشرکین میں سے، وہ دوزخ کی آگ میں ہوں گے، ہمیشہ ہمیشہ اس میں رہیں گے۔ یہی لوگ بدترین مخلوق ہیں",
        "persian_text": "بی‌گمان کسانی از اهل کتاب و مشرکان که کفر ورزیدند، در آتش دوزخ خواهند بود؛ همیشه در آن می‌مانند. آنان بدترین مخلوقاتند.",
        "english_text": "Indeed, they who disbelieved among the People of the Book and the polytheists will be in the fire of Hell, abiding eternally therein. Those are the worst of creatures.",
        "transliteration": "Inna alladhīna kafarū min ahli al-kitābi wa al-mushrikīna fī nāri jahannama khālidīna fīhā, ūlā’ika hum sharru al-bariyyah",
    },
    {
        "verse_number": "7",
        "arabic_text": "اِنَّ الَّذِينَ ءَامَنُوا وَعَمِلُوا الصَّـٰلِحَـٰتِ اُولَـٰٓئِكَ هُمْ خَيْرُ الْبَرِيَّةِ",
        "urdu_text": "بیشک جو لوگ ایمان لائے اور نیک عمل کیے، وہی سب مخلوق میں بہتر ہیں",
        "persian_text": "بی‌گمان کسانی که ایمان آوردند و کارهای شایسته انجام دادند، بهترین آفریدگانند.",
        "english_text": "Indeed, those who have believed and done righteous deeds — those are the best of creatures.",
        "transliteration": "Inna alladhīna āmanū wa ʿamilū al-ṣāliḥāti ūlā’ika hum khayru al-bariyyah",
    },
    {
        "verse_number": "8",
        "arabic_text": "جَزَآؤُهُمْ عِندَ رَبِّهِمْ جَنَّـٰتُ عَدْنٍۢ تَجْرِى مِن تَحْتِهَا الْاَنْهَـٰرُ خَـٰلِدِينَ فِيهَآ اَبَدًا ۖ رَّضِىَ اللَّهُ عَنْهُمْ وَرَضُوا عَنْهُ ۚ ذَٰلِكَ لِمَنْ خَشِىَ رَبَّهُۥ",
        "urdu_text": "ان کا بدلہ ان کے رب کے ہاں ہمیشہ رہنے والی جنتیں ہیں، جن کے نیچے نہریں بہتی ہیں۔ وہ ان میں ہمیشہ رہیں گے۔ اللہ ان سے راضی ہو گیا اور وہ اس سے راضی ہو گئے۔ یہ ان کے لیے ہے جو اپنے رب سے ڈرتے ہیں",
        "persian_text": "پاداش آنان نزد پروردگارشان باغ‌های جاودانی است که از زیرشان نهرها جاری است، جاودانه در آن می‌مانند. خدا از آنان خشنود است و آنان از او خشنود. این [پاداش] برای کسی است که از پروردگارش بترسد.",
        "english_text": "Their reward with their Lord will be gardens of perpetual residence beneath which rivers flow, wherein they will abide forever. Allah is pleased with them, and they are pleased with Him — that is for whoever has feared his Lord.",
        "transliteration": "Jazā’uhum ʿinda rabbihim jannātu ʿadnin tajrī min taḥtihā al-anhāru khālidīna fīhā abadan, raḍiya Allāhu ʿanhum wa raḍū ʿanhu, dhālika liman khashiya rabbah",
    },
]
