ayats = [
    {
        "verse_number": 1,
        "arabic_text": "سَبَّحَ لِلَّهِ مَا فِي السَّمٰوٰتِ وَ مَا فِي الْاَرْضِ ۖ وَ هُوَ الْعَزِيزُ الْحَكِيمُ",
        "urdu_text": "اللہ کی تسبیح کی ہے ہر چیز نے جو آسمانوں اور زمین میں ہے، اور وہی غالب حکمت والا ہے۔",
        "persian_text": "آنچه در آسمان‌ها و زمین است، برای خدا تسبیح می‌گوید، و او شکست‌ناپذیر و حکیم است.",
        "english_text": "Whatever is in the heavens and whatever is on the earth glorifies Allah. And He is the Almighty, the All-Wise.",
        "transliteration": "Sabbaha lillahi maa fis-samaawaati wa maa fil-ard; wa Huwal-'Azeezul-Hakeem",
    },
    {
        "verse_number": 2,
        "arabic_text": "هُوَ الَّذِي اَخْرَجَ الَّذِينَ كَفَرُوا مِنْ اَهْلِ الْكِتٰبِ مِن دِيَارِهِمْ لِاَوَّلِ الْحَشْرِ ۚ مَا ظَنَنتُمْ اَن يَخْرُجُوا وَظَنُّوا اَنَّهُم مَّانِعَتُهُمْ حُصُونُهُم مِّنَ اللَّهِ فَاَتَاهُمُ اللَّهُ مِنْ حَيْثُ لَمْ يَحْتَسِبُوا وَقَذَفَ فِي قُلُوبِهِمُ الرُّعْبَ",
        "urdu_text": "وہی ہے جس نے اہلِ کتاب میں سے کافروں کو ان کے گھروں سے پہلے ہی حشر میں نکال باہر کیا۔ تمہیں گمان نہ تھا کہ وہ نکلیں گے، اور وہ بھی سمجھے تھے کہ ان کے قلعے انہیں اللہ سے بچا لیں گے، مگر اللہ ان پر ایسی جگہ سے آیا جس کا انہوں نے گمان بھی نہ کیا، اور ان کے دلوں میں رعب ڈال دیا۔",
        "persian_text": "او کسی است که کافران اهل کتاب را برای نخستین بار از خانه‌هایشان بیرون راند. شما گمان نمی‌کردید که بیرون روند، و آنها نیز می‌پنداشتند که دژهایشان آنها را از خدا بازمی‌دارند، اما خداوند از جایی که گمان نمی‌بردند بر آنان تاخت و در دل‌هایشان ترس افکند.",
        "english_text": "He it is Who expelled the disbelievers of the People of the Scripture from their homes at the first gathering. You did not think they would go out, and they thought that their fortresses would protect them from Allah. But Allah came upon them from where they had not expected, and He cast terror into their hearts.",
        "transliteration": "Huwal lazee akhrajal lazeena kafaroo min Ahlil Kitaabi min diyaarihim li awwalil hashri maa zannntum any yakhrujoo wa zannnooo annahum maa ni'atuhum husoonuhum minal laahi fa ataahumul laahu min haisu lam yahtasiboo wa qadhafa fee quloobihimur ru'b",
    },
    {
        "verse_number": 3,
        "arabic_text": "وَلَوْلَا اَن كَتَبَ ٱللَّهُ عَلَيْهِمُ ٱلْجَلَآءَ لَعَذَّبَهُمْ فِى ٱلدُّنْيَا ۖ وَلَهُمْ فِى ٱلْءَاخِرَةِ عَذَابُ ٱلنَّارِ",
        "urdu_text": "اور اگر اللہ نے ان کے لئے جلا وطنی مقرر نہ کی ہوتی تو وہ انہیں دنیا میں ہی عذاب دیتا، اور آخرت میں ان کے لیے آگ کا عذاب ہے۔",
        "persian_text": "و اگر خدا تبعید را برای آنان مقرر نکرده بود، قطعاً در دنیا آنان را عذاب می‌داد، و در آخرت برایشان عذاب آتش است.",
        "english_text": "And had Allah not decreed exile for them, He would have certainly punished them in this world. And in the Hereafter they will suffer the torment of the Fire.",
        "transliteration": "Wa law laaa an katabal laahu 'alaihimul jalaa-a la'azzabahum fid dunyaa; wa lahum fil Aakhirati 'azaabun Naar",
    },
    {
        "verse_number": 4,
        "arabic_text": "ذَٰلِكَ بِاَنَّهُمْ شَآقُّوا ٱللَّهَ وَرَسُولَهُۥ ۖ وَمَن يُشَآقِّ ٱللَّهَ فَاِنَّ ٱللَّهَ شَدِيدُ ٱلْعِقَابِ",
        "urdu_text": "یہ اس وجہ سے ہوا کہ انہوں نے اللہ اور اس کے رسول کی مخالفت کی، اور جو کوئی اللہ کی مخالفت کرے تو بے شک اللہ سخت سزا دینے والا ہے۔",
        "persian_text": "این به دلیل آن است که آنان با خدا و پیامبرش دشمنی کردند، و هر کس با خدا دشمنی کند، پس بی‌گمان خدا سخت کیفر دهنده است.",
        "english_text": "That is because they opposed Allah and His Messenger. And whoever opposes Allah, then indeed, Allah is severe in punishment.",
        "transliteration": "Zaalika bi annahum shaaqqool laaha wa Rasoolahoo wa mai yushaaqqil laaha fa innal laaha shadeedul 'iqaab",
    },
    {
        "verse_number": 5,
        "arabic_text": "مَا قَطَعْتُم مِّن لِّينَةٍ اَوْ تَرَكْتُمُوهَا قَآئِمَةً عَلَىٰۤ اُصُولِهَا فَبِاِذْنِ ٱللَّهِ وَلِيُخْزِىَ ٱلْفَـٰسِقِينَ",
        "urdu_text": "تم نے جو بھی کھجور کا درخت کاٹا یا جڑوں پر قائم چھوڑ دیا، وہ اللہ کے حکم سے تھا، تاکہ وہ نافرمانوں کو رسوا کرے۔",
        "persian_text": "هر درخت خرمایی را که بریدید یا آن را بر جای خود باقی گذاشتید، به فرمان خدا بود تا نافرمانان را رسوا سازد.",
        "english_text": "Whatever palm trees you cut down or left standing intact, it was by Allah’s permission, and so He might disgrace the rebellious.",
        "transliteration": "Maa qata'tum min leenatin aw taraktu moohaa qaaa'imatin 'alaa usooolihaa fabi iznil laahi wa liyukhziyal faasiqeen",
    },
    {
        "verse_number": 6,
        "arabic_text": "وَ مَا اَفَاءَ ٱللَّهُ عَلَىٰ رَسُولِهِۦ مِنْهُمْ فَمَآ اَوْجَفْتُمْ عَلَيْهِ مِنْ خَيْلٍۢ وَلَا رِكَابٍ وَلَٰكِنَّ ٱللَّهَ يُسَلِّطُ رُسُلَهُۥ عَلَىٰ مَن يَشَآءُ ۚ وَٱللَّهُ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌ",
        "urdu_text": "جو مال اللہ نے ان سے اپنے رسول کو عطا کیا، وہ ایسا مال نہیں تھا جس پر تم نے گھوڑے یا اونٹ دوڑائے ہوں، بلکہ اللہ اپنے رسولوں کو جس پر چاہے غالب کر دیتا ہے۔ اور اللہ ہر چیز پر قادر ہے۔",
        "persian_text": "آنچه خدا از آنان به پیامبر خود بازگرداند، چیزی نبود که شما برای آن اسب یا شتری به کار گرفته باشید، بلکه خدا پیامبرانش را بر هر کس بخواهد مسلط می‌سازد، و خدا بر هر چیزی تواناست.",
        "english_text": "And what Allah restored to His Messenger from them – you did not spur for it any horses or camels. But Allah gives authority to His messengers over whom He wills. And Allah is over all things competent.",
        "transliteration": "Wa maaa afa'al laahu 'alaa Rasoolihee minhum famaaa awjaftum 'alaihi min khailinw wa laa rikaabinw wa laakinnal laaha yusallitu Rusulahoo 'alaa many yashaaa'; wallaahu 'alaa kulli shai'in Qadeer",
    },
    {
        "verse_number": 7,
        "arabic_text": "مَّآ اَفَآءَ ٱللَّهُ عَلَىٰ رَسُولِهِۦ مِنْ اَهْلِ ٱلْقُرَىٰ فَلِلَّهِ وَلِلرَّسُولِ وَلِذِى ٱلْقُرْبَىٰ وَٱلْيَتَـٰمَىٰ وَٱلْمَسَـٰكِينِ وَٱبْنِ ٱلسَّبِيلِ كَىْ لَا يَكُونَ دُولَةًۢ بَيْنَ ٱلْاَغْنِيَآءِ مِنكُمْ ۚ وَمَآ ءَاتَىٰكُمُ ٱلرَّسُولُ فَخُذُوهُ ۖ وَ مَا نَهَىٰكُمْ عَنْهُ فَٱنتَهُوا۟ ۚ وَٱتَّقُوا۟ ٱللَّهَ ۖ اِنَّ ٱللَّهَ شَدِيدُ ٱلْعِقَابِ",
        "urdu_text": "جو مال اللہ نے اپنے رسول کو بستیوں والوں سے عطا کیا، وہ اللہ کا، رسول کا، قرابت داروں کا، یتیموں، مسکینوں اور مسافروں کا ہے۔ تاکہ مال صرف دولت مندوں کے درمیان گردش نہ کرے۔ اور جو کچھ رسول تمہیں دے، وہ لے لو، اور جس سے روکے، اس سے رک جاؤ، اور اللہ سے ڈرو۔ بے شک اللہ سخت عذاب دینے والا ہے۔",
        "persian_text": "آنچه خدا از اموال اهل آبادی‌ها به پیامبرش بازگرداند، از آنِ خدا و پیامبر و خویشاوندان و یتیمان و مسکینان و در راه‌ماندگان است، تا ثروت میان ثروتمندان شما دست‌به‌دست نگردد. آنچه رسول به شما داد، بگیرید، و از آنچه شما را نهی کرد، بازایستید؛ و از خدا پروا کنید، که خدا سخت کیفر دهنده است.",
        "english_text": "Whatever Allah has restored to His Messenger from the people of the towns – it is for Allah and for the Messenger and for [his] near relatives and orphans and the needy and the [stranded] traveler – so that it will not be a perpetual distribution among the rich from among you. And whatever the Messenger has given you – take; and what he has forbidden you – refrain from. And fear Allah; indeed, Allah is severe in penalty.",
        "transliteration": "Maaa afa'al laahu 'alaa Rasoolihee min ahlil quraa falillaahi wa lir Rasooli wa li zeeil qurbaa wal yataamaa wal masaakeeni wabnis sabeeli kai laa yakoona doolatan bainal aghniyaaa'i minkum; wa maaa aataakumur Rasoolu fakhuzoohu wa maa nahaakum 'anhu fantahoo; wattaqul laah; innal laaha shadeedul 'iqaab",
    },
    {
        "verse_number": 8,
        "arabic_text": "لِلْفُقَرَآءِ ٱلْمُهَـٰجِرِينَ ٱلَّذِينَ اُخْرِجُوا۟ مِن دِيَـٰرِهِمْ وَاَمْوَٰلِهِمْ يَبْتَغُونَ فَضْلًۭا مِّنَ ٱللَّهِ وَرِضْوَٰنًۭا وَيَنصُرُونَ ٱللَّهَ وَرَسُولَهُۥٓ ۚ اُو۟لَـٰٓئِكَ هُمُ ٱلصَّـٰدِقُونَ",
        "urdu_text": "یہ (مال) ان مہاجر فقیروں کے لیے ہے جنہیں ان کے گھروں اور مالوں سے نکال دیا گیا۔ وہ اللہ کا فضل اور رضا چاہتے ہیں اور اللہ اور اس کے رسول کی مدد کرتے ہیں۔ یہی لوگ سچے ہیں۔",
        "persian_text": "این مال برای فقیران مهاجری است که از خانه‌ها و اموالشان رانده شده‌اند، در حالی که فضل خدا و رضای او را می‌جویند و خدا و پیامبرش را یاری می‌کنند. آنان راستگویانند.",
        "english_text": "[It is] for the poor emigrants who were expelled from their homes and their properties, seeking bounty from Allah and [His] approval and supporting Allah and His Messenger. Those are the truthful.",
        "transliteration": "Lilfuqaraaa'il muhaajireenal lazeena ukhrijoo min diyaarihim wa amwaalihim yabtaghoona fadlam minal laahi wa ridwaananw-wa yansuroonal laaha wa Rasoolah; ulaaa'ika humus saadiqoon",
    },
    {
        "verse_number": 9,
        "arabic_text": "وَٱلَّذِينَ تَبَوَّءُوا ٱلدَّارَ وَٱلْاِيمَـٰنَ مِن قَبْلِهِمْ يُحِبُّونَ مَنْ هَاجَرَ اِلَيْهِمْ وَلَا يَجِدُونَ فِى صُدُورِهِمْ حَاجَةًۭ مِّمَّآ اُوتُوا۟ وَيُؤْثِرُونَ عَلَىٰٓ اَنفُسِهِمْ وَلَوْ كَانَ بِهِمْ خَصَاصَةٌۭ ۚ وَمَن يُوقَ شُحَّ نَفْسِهِۦ فَاُو۟لَـٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ",
        "urdu_text": "اور وہ لوگ جنہوں نے ان (مہاجرین) سے پہلے ہی ایمان لا کر مدینہ کو گھر بنایا، وہ ان سے محبت کرتے ہیں جو ان کے پاس ہجرت کر کے آتے ہیں، اور جو کچھ ان کو دیا جائے، اس پر اپنے دلوں میں کوئی رغبت نہیں رکھتے، اور ان کو اپنی جانوں پر ترجیح دیتے ہیں، چاہے خود محتاج ہوں۔ اور جو اپنے نفس کے بخل سے بچا لیا گیا، وہی کامیاب ہیں۔",
        "persian_text": "و کسانی که پیش از آنان در مدینه جای گرفتند و ایمان آوردند، کسانی را که به سوی آنان هجرت کرده‌اند دوست دارند، و در دل خود نیازی نسبت به آنچه به دیگران داده شده نمی‌یابند و آنان را بر خود ترجیح می‌دهند، هرچند خود نیازمند باشند؛ و هر کس از بخل نفس خود در امان باشد، بی‌گمان رستگار است.",
        "english_text": "And those who, before them, had homes [in Medina] and had accepted the faith – love those who emigrated to them and find not any want in their breasts of what the emigrants were given but give [them] preference over themselves, even though they are in privation. And whoever is protected from the stinginess of his soul – it is those who will be the successful.",
        "transliteration": "Wallazeena tabawwa'ud daara wal eemaana min qablihim yuhibboona man haajara ilaihim wa laa yajidoona fee sudoorihim haajatan mimmaa ootoo wa yusiroona 'alaaa anfusihim wa law kaana bihim khasaasah; wa mai yooqa shuha nafsihee fa ulaaa'ika humul muflihoon",
    },
    {
        "verse_number": 10,
        "arabic_text": "وَٱلَّذِينَ جَآءُوا۟ مِنۢ بَعْدِهِمْ يَقُولُونَ رَبَّنَا ٱغْفِرْ لَنَا وَلِاِخْوَٰنِنَا ٱلَّذِينَ سَبَقُونَا بِٱلْاِيمَـٰنِ وَلَا تَجْعَلْ فِى قُلُوبِنَا غِلًّۭا لِّلَّذِينَ ءَامَنُوا۟ ۚ رَبَّنَآ اِنَّكَ رَءُوفٌۭ رَّحِيمٌۭ",
        "urdu_text": "اور وہ جو ان کے بعد آئے، کہتے ہیں: اے ہمارے رب! ہمیں اور ہمارے ان بھائیوں کو بخش دے جو ہم سے پہلے ایمان لا چکے، اور ہمارے دلوں میں ایمان والوں کے لیے کینہ نہ رکھ۔ اے ہمارے رب! بے شک تو مہربان، نہایت رحم والا ہے۔",
        "persian_text": "و کسانی که پس از آنان آمدند می‌گویند: پروردگارا! ما را و برادرانمان را که پیش از ما ایمان آوردند، ببخش، و در دل‌های ما نسبت به اهل ایمان کینه‌ای قرار مده. پروردگارا! تو مهربان و بخشنده‌ای.",
        "english_text": "And those who came after them say, 'Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts [any] resentment toward those who have believed. Our Lord, indeed You are Kind and Merciful.'",
        "transliteration": "Wallazeena jaaa'oo mim ba'dihim yaqooloona Rabbanaaghfir lanaa wa li ikhwaaninallazeena sabaqoonaa bil eemaani wa laa taj'al fee quloobinaa ghillal lillazeena aamanoo; Rabbanaaa innaka Ra'oofur Raheem",
    },
    {
        "verse_number": 11,
        "arabic_text": "اَلَمْ تَرَ اِلَى ٱلَّذِينَ نَافَقُوا۟ يَقُولُونَ لِاِخْوَٰنِهِمُ ٱلَّذِينَ كَفَرُوا۟ مِنْ اَهْلِ ٱلْكِتَـٰبِ لَئِنْ اُخْرِجْتُمْ لَنَخْرُجَنَّ مَعَكُمْ وَلَا نُطِيعُ فِيكُمْ اَحَدًا اَبَدًۭا وَاِن قُوتِلْتُمْ لَنَنصُرَنَّكُمْ ۚ وَٱللَّهُ يَشْهَدُ اِنَّهُمْ لَكَـٰذِبُونَ",
        "urdu_text": "کیا آپ نے ان منافقوں کو نہیں دیکھا جو اپنے ان بھائیوں سے کہتے ہیں جو اہل کتاب میں سے کافر ہو گئے تھے: اگر تم نکالے گئے تو ہم بھی تمہارے ساتھ نکلیں گے، اور ہم کسی کی بات ہرگز نہ مانیں گے تمہارے خلاف، اور اگر تم سے جنگ کی گئی تو ہم ضرور تمہاری مدد کریں گے۔ حالانکہ اللہ گواہی دیتا ہے کہ وہ یقیناً جھوٹے ہیں۔",
        "persian_text": "آیا کسانی را که نفاق ورزیدند ندیدی که به برادران خود از کافران اهل کتاب گفتند: اگر شما رانده شوید، ما هم قطعاً با شما خواهیم رفت و هرگز از کسی دربارهٔ شما اطاعت نخواهیم کرد، و اگر با شما جنگ شود، یاری‌تان خواهیم کرد؟ در حالی که خدا گواهی می‌دهد که آنان دروغ‌گویانند.",
        "english_text": "Have you not seen those who practice hypocrisy saying to their disbelieving brothers among the People of the Scripture, 'If you are expelled, we will surely leave with you, and we will not obey, in regard to you, anyone – ever; and if you are fought, we will surely aid you.' But Allah testifies that they are liars.",
        "transliteration": "Alam tara ilal lazeena naafaqoo yaqooloona li ikhwaanihimul lazeena kafaroo min Ahlil Kitaabi la'in ukhrijtum lanakhrujanna ma'akum wa laa nutee'u feekum ahadan abadanw wa in qootiltum lanansurannakum; wallaahu yashhadu innahum lakaaziboon",
    },
    {
        "verse_number": 12,
        "arabic_text": "لَئِنْ اُخْرِجُوا۟ لَا يَخْرُجُونَ مَعَهُمْ ۖ وَلَئِن قُوتِلُوا۟ لَا يَنصُرُونَهُمْ ۖ وَلَئِن نَّصَرُوهُمْ لَيُوَلُّنَّ ٱلْاَدْبَـٰرَ ثُمَّ لَا يُنصَرُونَ",
        "urdu_text": "اگر وہ نکالے گئے تو یہ ان کے ساتھ ہرگز نہیں نکلیں گے، اور اگر ان سے جنگ کی گئی تو یہ ان کی مدد ہرگز نہیں کریں گے، اور اگر انہوں نے مدد کی بھی تو ضرور پیٹھ پھیر جائیں گے، پھر ان کی کوئی مدد نہیں کی جائے گی۔",
        "persian_text": "اگر آنان (یهود) رانده شوند، این‌ها (منافقان) هرگز با آنان نخواهند رفت، و اگر جنگی روی دهد، یاری‌شان نخواهند کرد، و اگر هم یاری کنند، پشت خواهند کرد، سپس کسی یاری‌شان نخواهد کرد.",
        "english_text": "If they are expelled, they will not leave with them; and if they are fought, they will not aid them. And [even] if they should aid them, they will surely turn their backs; then they will not be aided.",
        "transliteration": "La'in ukhrijoo laa yakhrujoona ma'ahum wa la'in qootiloo laa yansuroonahum wa la'in nasaroohum la yuwallunnal adbaara summa laa yunsaroon",
    },
    {
        "verse_number": 13,
        "arabic_text": "لَاَنتُمْ اَشَدُّ رَهْبَةًۭ فِى صُدُورِهِم مِّنَ ٱللَّهِ ۚ ذَٰلِكَ بِاَنَّهُمْ قَوْمٌۭ لَّا يَفْقَهُونَ",
        "urdu_text": "تمہارے دلوں میں ان کے دل اللہ سے زیادہ خوف رکھتے ہیں، یہ اس لیے ہے کہ وہ سمجھنے والے لوگ نہیں ہیں۔",
        "persian_text": "شما در دل‌های آنان، از خدا بیشتر ترس افکنده‌اید؛ این بدان سبب است که آنان مردمی نادان‌اند.",
        "english_text": "You are more fearful in their hearts than Allah. That is because they are a people who do not understand.",
        "transliteration": "La antum ashaddur rahbatan fee sudoorihim minal laah; zaalika bi annahum qawmul laa yafqahoon",
    },
    {
        "verse_number": 14,
        "arabic_text": "لَا يُقَـٰتِلُونَكُمْ جَمِيعًا اِلَّا فِى قُرًۭى مُّحَصَّنَةٍ اَوْ مِن وَرَآءِ جُدُرٍۢ ۚ بَأْسُهُم بَيْنَهُمْ شَدِيدٌۭ ۖ تَحْسَبُهُمْ جَمِيعًۭا وَقُلُوبُهُمْ شَتَّىٰ ۚ ذَٰلِكَ بِاَنَّهُمْ قَوْمٌۭ لَّا يَعْقِلُونَ",
        "urdu_text": "یہ تم سے اکٹھے ہو کر نہیں لڑیں گے، مگر قلعہ بند بستیوں میں یا دیواروں کے پیچھے چھپ کر۔ ان کی آپس کی دشمنی سخت ہے۔ تم انہیں اکٹھا سمجھتے ہو، حالانکہ ان کے دل مختلف ہیں۔ یہ اس لیے ہے کہ وہ سمجھ نہیں رکھتے۔",
        "persian_text": "آن‌ها هرگز همگی با شما نمی‌جنگند، جز در قلعه‌هایی محکم یا از پشت دیوارها. دشمنی میانشان سخت است. تو آنان را متحد می‌پنداری، در حالی که دل‌هایشان پراکنده است. این بدان سبب است که آنان خرد ندارند.",
        "english_text": "They will not fight you all except within fortified cities or from behind walls. Their enmity among themselves is severe. You think they are united, but their hearts are diverse_number. That is because they are a people who do not reason.",
        "transliteration": "Laa yuqaatiloonakum jamee'an illaa fee quran muhassanatin aw min waraaa'i judur; ba'suhum bainahum shadeed; tahsabuhum jamee'anw wa quloobuhum shattaa; zaalika bi annahum qawmul laa ya'qiloon",
    },
    {
        "verse_number": 15,
        "arabic_text": "كَمَثَلِ ٱلَّذِينَ مِن قَبْلِهِمْ قَرِيبًۭا ذَاقُوا۟ وَبَالَ اَمْرِهِمْ ۖ وَلَهُمْ عَذَابٌ اَلِيمٌۭ",
        "urdu_text": "ان کی مثال ان لوگوں کی طرح ہے جو ان سے تھوڑے ہی عرصہ پہلے تھے، جنہوں نے اپنے کاموں کا وبال چکھ لیا، اور ان کے لیے دردناک عذاب ہے۔",
        "persian_text": "آن‌ها مانند کسانی هستند که اندکی پیش از آنان بودند و کیفر کارهایشان را چشیدند، و برای آنان عذابی دردناک است.",
        "english_text": "[Their example is] like the example of those shortly before them; they tasted the bad consequence of their affair, and they will have a painful punishment.",
        "transliteration": "Kamathalil lazeena min qablihim qareeban zaaqoo waabaala amrihim wa lahum 'azaabun aleem",
    },
    {
        "verse_number": 16,
        "arabic_text": "كَمَثَلِ ٱلشَّيْطَـٰنِ اِذْ قَالَ لِلْاِنسَـٰنِ ٱكْفُرْ ۖ فَلَمَّا كَفَرَ قَالَ اِنِّى بَرِىٓءٌۭ مِّنكَ اِنِّىٓ اَخَافُ ٱللَّهَ رَبَّ ٱلْعَـٰلَمِينَ",
        "urdu_text": "یہ شیطان کی مثال ہے، جب وہ انسان سے کہتا ہے: کفر کر۔ پھر جب وہ کفر کرتا ہے، تو شیطان کہتا ہے: میں تجھ سے بری ہوں، میں اللہ رب العالمین سے ڈرتا ہوں۔",
        "persian_text": "مانند شیطان است که به انسان گفت: کفر بورز! اما وقتی او کافر شد، گفت: من از تو بیزارم، زیرا من از خداوند جهانیان می‌ترسم.",
        "english_text": "[They are] like Satan when he says to man, 'Disbelieve.' But when he disbelieves, he says, 'Indeed, I am disassociated from you. Indeed, I fear Allah, Lord of the worlds.'",
        "transliteration": "Kamathalish Shaitaani iz qaala lil insaani kufur, falammaa kafara qaala innee bareee'um minka innee akhaaful laaha Rabbal 'Aalameen",
    },
    {
        "verse_number": 17,
        "arabic_text": "فَكَانَ عَـٰقِبَتَهُمَآ اَنَّهُمَا فِى ٱلنَّارِ خَـٰلِدَيْنِ فِيهَا ۚ وَذَٰلِكَ جَزَٰٓؤُا۟ ٱلظَّـٰلِمِينَ",
        "urdu_text": "تو ان دونوں کا انجام یہ ہوا کہ وہ آگ میں ہمیشہ رہیں گے، اور یہ ظالموں کی سزا ہے۔",
        "persian_text": "سرانجام هر دوشان این شد که در آتش جاودانه باشند، و این است جزای ستمکاران.",
        "english_text": "So the outcome for both of them is that they will be in the Fire, abiding eternally therein. And that is the recompense of the wrongdoers.",
        "transliteration": "Fakaana 'aaqibatuhumaa annahumaa fin Naari khaalidayni feehaa; wa zaalika jazaaa'uz zaalimeen",
    },
    {
        "verse_number": 18,
        "arabic_text": "يَـٰٓاَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱتَّقُوا۟ ٱللَّهَ ۖ وَلْتَنظُرْ نَفْسٌۭ مَّا قَدَّمَتْ لِغَدٍۢ ۖ وَٱتَّقُوا۟ ٱللَّهَ ۚ اِنَّ ٱللَّهَ خَبِيرٌۢ بِمَا تَعْمَلُونَ",
        "urdu_text": "اے ایمان والو! اللہ سے ڈرو، اور ہر شخص یہ دیکھے کہ اس نے کل کے لیے کیا آگے بھیجا ہے۔ اور اللہ سے ڈرو، بے شک اللہ تمہارے اعمال سے باخبر ہے۔",
        "persian_text": "ای کسانی که ایمان آورده‌اید! از خدا پروا کنید، و هر کس بنگرد که برای فردایش چه پیش فرستاده است. و از خدا پروا کنید؛ بی‌گمان خدا به آنچه می‌کنید آگاه است.",
        "english_text": "O you who have believed, fear Allah. And let every soul look to what it has put forth for tomorrow – and fear Allah. Indeed, Allah is Acquainted with what you do.",
        "transliteration": "Yaaa ayyuhal lazeena aamanoo ittaqul laaha waltanzur nafsum maa qaddamat lighad; wattaqul laaha innal laaha khabeerum bimaa ta’maloon",
    },
    {
        "verse_number": 19,
        "arabic_text": "وَلَا تَكُونُوا۟ كَٱلَّذِينَ نَسُوا۟ ٱللَّهَ فَاَنسَىٰهُمْ اَنفُسَهُمْ ۚ اُو۟لَـٰٓئِكَ هُمُ ٱلْفَـٰسِقُونَ",
        "urdu_text": "اور ان لوگوں کی طرح نہ ہو جاؤ جنہوں نے اللہ کو بھلا دیا، تو اللہ نے انہیں خود ان کا آپ بھلا دیا۔ یہی لوگ فاسق ہیں۔",
        "persian_text": "مانند کسانی مباشید که خدا را فراموش کردند، پس خدا نیز آن‌ها را از خودشان غافل ساخت. آنان فاسق‌اند.",
        "english_text": "And be not like those who forgot Allah, so He made them forget themselves. Those are the defiantly disobedient.",
        "transliteration": "Wa laa takoonoo kallazeena nasul laaha fa ansaahum anfusahum; ulaaa'ika humul faasiqoon",
    },
    {
        "verse_number": 20,
        "arabic_text": "لَا يَسْتَوِىٓ اَصْحَـٰبُ ٱلنَّارِ وَاَصْحَـٰبُ ٱلْجَنَّةِ ۚ اَصْحَـٰبُ ٱلْجَنَّةِ هُمُ ٱلْفَآئِزُونَ",
        "urdu_text": "جہنمی اور جنتی برابر نہیں ہو سکتے۔ جنتی ہی کامیاب ہیں۔",
        "persian_text": "اهل دوزخ و اهل بهشت برابر نیستند. اهل بهشت همان رستگاران‌اند.",
        "english_text": "Not equal are the companions of the Fire and the companions of Paradise. The companions of Paradise – they are the attainers [of success].",
        "transliteration": "Laa yastawee as-haabun Naari wa as-haabul Jannah; as-haabul Jannati humul faa'izoon",
    },
    {
        "verse_number": 21,
        "arabic_text": "لَوْ اَنزَلْنَا هٰذَا ٱلْقُرْءَانَ عَلَىٰ جَبَلٍۢ لَّرَاَيْتَهُۥ خَـٰشِعًۭا مُّتَصَدِّعًۭا مِّنْ خَشْيَةِ ٱللَّهِ ۚ وَتِلْكَ ٱلْاَمْثَـٰلُ نَضْرِبُهَا لِلنَّاسِ لَعَلَّهُمْ يَتَفَكَّرُونَ",
        "urdu_text": "اگر ہم اس قرآن کو کسی پہاڑ پر نازل کرتے تو تم دیکھتے کہ وہ اللہ کے خوف سے جھک جاتا اور پھٹ جاتا۔ یہ مثالیں ہم لوگوں کے لیے بیان کرتے ہیں تاکہ وہ غور کریں۔",
        "persian_text": "اگر این قرآن را بر کوهی نازل می‌کردیم، می‌دیدی که آن از ترس خدا خاشع و شکافته می‌گردید. این مثال‌ها را برای مردم می‌زنیم، شاید بیندیشند.",
        "english_text": "Had We sent down this Qur'an upon a mountain, you would have seen it humbled and coming apart from fear of Allah. And these examples We present to the people that perhaps they will give thought.",
        "transliteration": "Lau anzalnaa haazal Qur'aana 'alaa jabalil lara-aitahoo khaashi'am mutasaddi'am min khashiyatil laah; wa tilkal amsaalu nadribuhaa linnaasi la'allahum yatafakkaroon",
    },
    {
        "verse_number": 22,
        "arabic_text": "هُوَ ٱللَّهُ ٱلَّذِى لَآ اِلَـٰهَ اِلَّا هُوَ ۖ عَـٰلِمُ ٱلْغَيْبِ وَٱلشَّهَـٰدَةِ ۖ هُوَ ٱلرَّحْمَـٰنُ ٱلرَّحِيمُ",
        "urdu_text": "وہی اللہ ہے جس کے سوا کوئی معبود نہیں، پوشیدہ اور ظاہر کا جاننے والا، وہی رحمٰن اور رحیم ہے۔",
        "persian_text": "اوست الله که جز او هیچ معبودی نیست، دانای نهان و آشکار، اوست بخشایندهٔ مهربان.",
        "english_text": "He is Allah, other than whom there is no deity, Knower of the unseen and the witnessed. He is the Entirely Merciful, the Especially Merciful.",
        "transliteration": "Huwal laahul lazee laaa ilaaha illaa huwa 'Aalimul Ghaibi wash shahaadah; Huwar Rahmaanur Raheem",
    },
    {
        "verse_number": 23,
        "arabic_text": "هُوَ ٱللَّهُ ٱلَّذِى لَآ اِلَـٰهَ اِلَّا هُوَ ٱلْمَلِكُ ٱلْقُدُّوسُ ٱلسَّلَـٰمُ ٱلْمُؤْمِنُ ٱلْمُهَيْمِنُ ٱلْعَزِيزُ ٱلْجَبَّارُ ٱلْمُتَكَبِّرُ ۚ سُبْحَـٰنَ ٱللَّهِ عَمَّا يُشْرِكُونَ",
        "urdu_text": "وہی اللہ ہے جس کے سوا کوئی معبود نہیں، بادشاہ، نہایت پاک، سلامتی والا، امان دینے والا، نگران، زبردست، جبار، بڑائی والا۔ اللہ ان کے شرک سے پاک ہے۔",
        "persian_text": "اوست الله که جز او معبودی نیست، پادشاه، پاک، سلامت‌دهنده، امان‌بخش، نگهبان، توانا، قهّار، بزرگ‌منش. خدا از آنچه شریک می‌سازند منزّه است.",
        "english_text": "He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Bestower of Faith, the Overse_numberer, the Exalted in Might, the Compeller, the Superior. Exalted is Allah above whatever they associate with Him.",
        "transliteration": "Huwal laahul lazee laaa ilaaha illaa Huwal Malikul Quddoosus Salaamul Mu’minul Muhaiminu ‘Azeezul Jabbaarul Mutakabbir; Subhaanallaahi ‘ammaa yushrikoon",
    },
    {
        "verse_number": 24,
        "arabic_text": "هُوَ ٱللَّهُ ٱلْخَـٰلِقُ ٱلْبَارِئُ ٱلْمُصَوِّرُ ۖ لَهُ ٱلْاَسْمَآءُ ٱلْحُسْنَىٰ ۚ يُسَبِّحُ لَهُۥ مَا فِى ٱلسَّمَـٰوَٰتِ وَٱلْاَرْضِ ۖ وَ هُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ",
        "urdu_text": "وہی اللہ ہے، پیدا کرنے والا، وجود بخشنے والا، صورت بنانے والا۔ اسی کے لیے اچھے اچھے نام ہیں۔ ہر چیز جو آسمانوں اور زمین میں ہے، اس کی تسبیح کرتی ہے، اور وہی زبردست، حکمت والا ہے۔",
        "persian_text": "اوست الله، آفریننده، پدیدآورنده، صورت‌گر. برای اوست نام‌های نیکو. هر چه در آسمان‌ها و زمین است، او را تسبیح می‌گوید، و اوست توانای حکیم.",
        "english_text": "He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names. Whatever is in the heavens and earth is exalting Him. And He is the Exalted in Might, the Wise.",
        "transliteration": "Huwal laahul Khaaliqul Baari'ul Musawwiru lahul asmaaa'ul husnaa; yusabbihu lahoo maa fissamaawaati wal ard; wa Huwal 'Azeezul Hakeem",
    },
]
