ayats = [
    {
        "verse_number": "1",
        "arabic_text": "إِذَا السَّمَاءُ انشَقَّتْ",
        "urdu_text": "جب آسمان پھٹ جائے گا",
        "persian_text": "وقتی آسمان شکافته شود",
        "english_text": "When the sky is split open,",
        "transliteration": "Idha al-samaaa'u inshaqqat",
    },
    {
        "verse_number": "2",
        "arabic_text": "وَأَذِنَتْ لِرَبِّهَا وَحُقَّتْ",
        "urdu_text": "اور اپنے رب کا حکم سن لے گی اور اس کا حق ہے",
        "persian_text": "و فرمان پروردگار خود را گوش فرا دارد، و سزاوار است",
        "english_text": "And listens to its Lord—and it must do so—",
        "transliteration": "Wa-adhinat li-rabbihaa wa huqqat",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَإِذَا الْأَرْضُ مُدَّتْ",
        "urdu_text": "اور جب زمین کھینچ دی جائے گی",
        "persian_text": "و هنگامی که زمین گسترده شود،",
        "english_text": "And when the earth is stretched out",
        "transliteration": "Wa idha al-ardu muddat",
    },
    {
        "verse_number": "4",
        "arabic_text": "وَأَلْقَتْ مَا فِيهَا وَتَخَلَّتْ",
        "urdu_text": "اور جو کچھ اس میں ہے باہر نکال دے گی اور خالی ہو جائے گی",
        "persian_text": "و آنچه در درون دارد بیرون اندازد و تهی گردد،",
        "english_text": "And has cast out whatever was in it and relinquished it",
        "transliteration": "Wa alqat ma feeha wa takhallat",
    },
    {
        "verse_number": "5",
        "arabic_text": "وَأَذِنَتْ لِرَبِّهَا وَحُقَّتْ",
        "urdu_text": "اور اپنے رب کا حکم سن لے گی اور اس کا حق ہے",
        "persian_text": "و فرمان پروردگار خود را گوش فرا دارد، و سزاوار است",
        "english_text": "And listens to its Lord—and it must do so—",
        "transliteration": "Wa-adhinat li-rabbihaa wa huqqat",
    },
    {
        "verse_number": "6",
        "arabic_text": "يَا أَيُّهَا الْإِنسَانُ إِنَّكَ كَادِحٌ إِلَىٰ رَبِّكَ كَدْحًا فَمُلَاقِيهِ",
        "urdu_text": "اے انسان! تو محنت کرتا ہے اپنے رب کی طرف تو اس سے جا ملے گا",
        "persian_text": "ای انسان! تو با رنج و کوشش به سوی پروردگارت می‌روی، پس او را ملاقات خواهی کرد",
        "english_text": "O mankind! You are laboring toward your Lord with great exertion and will meet Him.",
        "transliteration": "Ya ayyuhal-insaanu innaka kaadihun ilaa rabbika kadhan fa mulaaqeeh",
    },
    {
        "verse_number": "7",
        "arabic_text": "فَأَمَّا مَنْ أُوتِيَ كِتَابَهُ بِيَمِينِهِ",
        "urdu_text": "تو جس کو اس کا نامہ اعمال داہنے ہاتھ میں دیا جائے گا",
        "persian_text": "پس آنکه نامه‌اش به دست راستش داده شود،",
        "english_text": "Then as for he who is given his record in his right hand,",
        "transliteration": "Fa-amma man ootiya kitaabahu biyameenih",
    },
    {
        "verse_number": "8",
        "arabic_text": "فَسَوْفَ يُحَاسَبُ حِسَابًا يَسِيرًا",
        "urdu_text": "اس سے آسان حساب لیا جائے گا",
        "persian_text": "حساب آسانی برای او خواهد بود،",
        "english_text": "He will be judged with an easy account",
        "transliteration": "Fa-sawfa yuhasabu hisaaban yaseeran",
    },
    {
        "verse_number": "9",
        "arabic_text": "وَيَنقَلِبُ إِلَىٰ أَهْلِهِ مَسْرُورًا",
        "urdu_text": "اور وہ خوش ہو کر اپنے گھر والوں کی طرف لوٹے گا",
        "persian_text": "و شادمان به سوی خانواده‌اش بازمی‌گردد",
        "english_text": "And will return to his people in happiness.",
        "transliteration": "Wa yanqalibu ilaa ahlihi masrooran",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَأَمَّا مَنْ أُوتِيَ كِتَابَهُ وَرَاءَ ظَهْرِهِ",
        "urdu_text": "اور جس کو اس کا نامہ اعمال اس کی پیٹھ کے پیچھے سے دیا جائے گا",
        "persian_text": "و اما کسی که نامه‌اش از پشت سرش به او داده شود،",
        "english_text": "But as for he who is given his record behind his back,",
        "transliteration": "Wa amma man ootiya kitaabahu waraa'a zahrih",
    },
    {
        "verse_number": "11",
        "arabic_text": "فَسَوْفَ يَدْعُو ثُبُورًا",
        "urdu_text": "تو وہ ہلاکت پکارے گا",
        "persian_text": "او فریاد بر مرگ خواهد زد،",
        "english_text": "He will cry out for destruction",
        "transliteration": "Fa-sawfa yad'u thubooraa",
    },
    {
        "verse_number": "12",
        "arabic_text": "وَيَصْلَىٰ سَعِيرًا",
        "urdu_text": "اور وہ بھڑکتی آگ میں داخل ہوگا",
        "persian_text": "و به آتش سوزان درافکنده می‌شود،",
        "english_text": "And will enter a blazing fire.",
        "transliteration": "Wa yaslaa sa'eera",
    },
    {
        "verse_number": "13",
        "arabic_text": "إِنَّهُ كَانَ فِي أَهْلِهِ مَسْرُورًا",
        "urdu_text": "وہ اپنے گھر والوں میں خوش تھا",
        "persian_text": "او در میان خانواده‌اش شادمان بود،",
        "english_text": "Indeed, he had been among his people in happiness;",
        "transliteration": "Innahoo kaana fee ahlihi masrooran",
    },
    {
        "verse_number": "14",
        "arabic_text": "إِنَّهُ ظَنَّ أَن لَّن يَحُورَ",
        "urdu_text": "وہ سمجھتا تھا کہ وہ واپس نہیں لوٹے گا",
        "persian_text": "او گمان می‌کرد که هرگز بازنخواهد گشت،",
        "english_text": "Indeed, he had thought he would never return.",
        "transliteration": "Innahoo zanna allayy yahoor",
    },
    {
        "verse_number": "15",
        "arabic_text": "بَلَىٰ إِنَّ رَبَّهُ كَانَ بِهِ بَصِيرًا",
        "urdu_text": "کیوں نہیں! اس کا رب اسے خوب دیکھ رہا تھا",
        "persian_text": "آری! پروردگارش او را همواره می‌دید",
        "english_text": "Yes! Indeed, his Lord was ever of him, Seeing.",
        "transliteration": "Balaa inna rabbahu kaana bihi baseera",
    },
    {
        "verse_number": "16",
        "arabic_text": "فَلَا أُقْسِمُ بِالشَّفَقِ",
        "urdu_text": "پس میں شام کی سرخی کی قسم کھاتا ہوں",
        "persian_text": "سوگند به سرخی شامگاه،",
        "english_text": "But no! I swear by the twilight,",
        "transliteration": "Falaa uqsimu bish-shafaq",
    },
    {
        "verse_number": "17",
        "arabic_text": "وَاللَّيْلِ وَمَا وَسَقَ",
        "urdu_text": "اور رات اور جو کچھ وہ جمع کرتی ہے",
        "persian_text": "و به شب و آنچه در خود گرد می‌آورد،",
        "english_text": "And the night and what it envelops,",
        "transliteration": "Wal-layli wa maa wasaq",
    },
    {
        "verse_number": "18",
        "arabic_text": "وَالْقَمَرِ إِذَا اتَّسَقَ",
        "urdu_text": "اور چاند جب وہ پورا ہو جائے",
        "persian_text": "و به ماه هنگامی که کامل گردد،",
        "english_text": "And the moon when it becomes full,",
        "transliteration": "Wal-qamari idhaa ittasq",
    },
    {
        "verse_number": "19",
        "arabic_text": "لَتَرْكَبُنَّ طَبَقًا عَن طَبَقٍ",
        "urdu_text": "تم ضرور ایک حال سے دوسرے حال میں چلو گے",
        "persian_text": "بی‌تردید شما از حالی به حالی دیگر درخواهید آمد،",
        "english_text": "You will surely travel from stage to stage.",
        "transliteration": "Latarkabunna tabaqan 'an tabaq",
    },
    {
        "verse_number": "20",
        "arabic_text": "فَمَا لَهُمْ لَا يُؤْمِنُونَ",
        "urdu_text": "تو ان کو کیا ہوا کہ ایمان نہیں لاتے؟",
        "persian_text": "پس چه شده آنان را که ایمان نمی‌آورند؟",
        "english_text": "So what is [the matter] with them [that] they do not believe,",
        "transliteration": "Famaalahum laa yu’minoon",
    },
    {
        "verse_number": "21",
        "arabic_text": "وَإِذَا قُرِئَ عَلَيْهِمُ الْقُرْآنُ لَا يَسْجُدُونَ",
        "urdu_text": "اور جب ان کے سامنے قرآن پڑھا جاتا ہے تو سجدہ نہیں کرتے",
        "persian_text": "و چون قرآن بر آنان خوانده می‌شود، سجده نمی‌کنند؟",
        "english_text": "And when the Quran is recited to them, they do not prostrate?",
        "transliteration": "Wa idhaa quri’a ‘alaihimul Qur’aanu laa yasjudoon",
    },
    {
        "verse_number": "22",
        "arabic_text": "بَلِ الَّذِينَ كَفَرُوا يُكَذِّبُونَ",
        "urdu_text": "بلکہ کافر جھٹلاتے ہیں",
        "persian_text": "بلکه کسانی که کافر شدند، تکذیب می‌کنند،",
        "english_text": "But those who disbelieve deny,",
        "transliteration": "Balil-lazeena kafaroo yukazziboon",
    },
    {
        "verse_number": "23",
        "arabic_text": "وَاللَّهُ أَعْلَمُ بِمَا يُوعُونَ",
        "urdu_text": "اور اللہ خوب جانتا ہے جو کچھ وہ دلوں میں چھپاتے ہیں",
        "persian_text": "و خداوند به آنچه آنان در دل دارند، آگاه‌تر است،",
        "english_text": "And Allah is most knowing of what they keep within themselves.",
        "transliteration": "Wallaahu a’lamu bimaa yoo’oon",
    },
    {
        "verse_number": "24",
        "arabic_text": "فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ",
        "urdu_text": "تو ان کو دردناک عذاب کی خبر دے دو",
        "persian_text": "پس آنان را به عذابی دردناک بشارت ده،",
        "english_text": "So give them tidings of a painful punishment,",
        "transliteration": "Fabashshirhum bi’azaabin aleem",
    },
    {
        "verse_number": "25",
        "arabic_text": "إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ لَهُمْ أَجْرٌ غَيْرُ مَمْنُونٍ",
        "urdu_text": "مگر جو ایمان لائے اور نیک عمل کیے ان کے لیے بے انتہا اجر ہے",
        "persian_text": "مگر کسانی که ایمان آوردند و اعمال نیک انجام دادند، برای آنان پاداشی بی‌پایان است",
        "english_text": "Except for those who believe and do righteous deeds. For them is a reward uninterrupted.",
        "transliteration": "Illal-lazeena aamanoo wa ‘amilus-saalihaati lahum ajrun ghayru mamnoon",
    },
]
