ayats = [
    {
        "arabic_text": "قُلْ يَأَيُّهَا ٱلۡكَٰفِرُونَ",
        "urdu_text": "آپ کہہ دیجئے! اے کافرو",
        "persian_text": "بگو ای کافران!",
        "english_text": "Say: O disbelievers!",
        "transliteration": "Qul ya ayyuhal kafiroon",
        "verse_number": "1",
    },
    {
        "arabic_text": "لَا أَعْبُدُ مَا تَعْبُدُونَ",
        "urdu_text": "میں عبادت نہیں کرتا ان کی جن کی تم عبادت کرتے ہو",
        "persian_text": "من عبادت نمی‌کنم آنچه را که شما می‌پرستید",
        "english_text": "I do not worship what you worship.",
        "transliteration": "Laa a'budu maa ta'budoon",
        "verse_number": "2",
    },
    {
        "arabic_text": "وَلَا أَنتُمْ عَٰبِدُونَ مَا أَعْبُدُ",
        "urdu_text": "اور نہ ہی تم عبادت کرنے والے ہو جس کی میں عبادت کرتا ہوں",
        "persian_text": "و شما عبادت‌کننده آنچه من می‌پرستم نیستید",
        "english_text": "Nor are you worshippers of what I worship.",
        "transliteration": "Wa laa antum 'aabidoona maa a'bud",
        "verse_number": "3",
    },
    {
        "arabic_text": "وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ",
        "urdu_text": "اور نہ ہی میں عبادت کرنے والا ہوں ان کی جن کی تم عبادت کرتے ہو",
        "persian_text": "و من نیز پرستنده آنچه شما می‌پرستید نیستم",
        "english_text": "Nor will I be a worshipper of what you worship.",
        "transliteration": "Wa laa ana 'aabidum maa 'abattum",
        "verse_number": "4",
    },
    {
        "arabic_text": "وَلَا أَنتُمْ عَٰبِدُونَ مَا أَعْبُدُ",
        "urdu_text": "اور نہ ہی تم عبادت کرنے والے ہو جس کی میں عبادت کرتا ہوں",
        "persian_text": "و شما پرستنده آنچه من می‌پرستم نیستید",
        "english_text": "Nor are you worshippers of what I worship.",
        "transliteration": "Wa laa antum 'aabidoona maa a'bud",
        "verse_number": "5",
    },
    {
        "arabic_text": "لَكُمْ دِينُكُمْ وَلِيَ دِينِ",
        "urdu_text": "تمہارے لئے تمہارا دین ہے اور میرے لئے میرا دین",
        "persian_text": "دین شما برای خودتان و دین من برای خودم",
        "english_text": "For you is your religion, and for me is my religion.",
        "transliteration": "Lakum deenukum wa liya deen",
        "verse_number": "6",
    },
]
