ayats = [
    {
        "arabic_text": "وَاللَّيْلِ إِذَا يَغْشَىٰ",
        "urdu_text": "رات کی قسم جب وہ چھا جائے",
        "persian_text": "سوگند به شب هنگامی که فرو پوشد",
        "english_text": "By the night when it covers",
        "transliteration": "Wal-layli idha yaghshā",
        "verse_number": "1",
    },
    {
        "arabic_text": "وَالنَّهَارِ إِذَا تَجَلَّىٰ",
        "urdu_text": "اور دن کی قسم جب وہ روشن ہو",
        "persian_text": "و به روز، هنگامی که روشن شود",
        "english_text": "And [by] the day when it appears",
        "transliteration": "Wan-nahāri idha tajallā",
        "verse_number": "2",
    },
    {
        "arabic_text": "وَمَا خَلَقَ الذَّكَرَ وَالْأُنثَىٰ",
        "urdu_text": "اور اُس ذات کی قسم جس نے نر اور مادہ کو پیدا کیا",
        "persian_text": "و قسم به کسی که نر و ماده را آفرید",
        "english_text": "And [by] He who created the male and female",
        "transliteration": "Wa mā khalaqa adh-dhakara wal-unthā",
        "verse_number": "3",
    },
    {
        "arabic_text": "إِنَّ سَعْيَكُمْ لَشَتَّىٰ",
        "urdu_text": "بیشک تمہاری کوششیں مختلف قسم کی ہیں",
        "persian_text": "همانا تلاش شما گوناگون است",
        "english_text": "Indeed, your efforts are diverse",
        "transliteration": "Inna sa'yakum lashattā",
        "verse_number": "4",
    },
    {
        "arabic_text": "فَأَمَّا مَنْ أَعْطَىٰ وَاتَّقَىٰ",
        "urdu_text": "پھر جس نے (اللہ کی راہ میں) دیا اور تقویٰ اختیار کیا",
        "persian_text": "پس هر که داد و پرهیزکاری کرد",
        "english_text": "So as for he who gives and fears [Allah]",
        "transliteration": "Fa ammā man a'tā wattaqā",
        "verse_number": "5",
    },
    {
        "arabic_text": "وَصَدَّقَ بِالْحُسْنَىٰ",
        "urdu_text": "اور نیکی کو سچ مانا",
        "persian_text": "و نیکی را تصدیق کرد",
        "english_text": "And believes in the best [reward]",
        "transliteration": "Wa saddaqa bil-husnā",
        "verse_number": "6",
    },
    {
        "arabic_text": "فَسَنُيَسِّرُهُ لِلْيُسْرَىٰ",
        "urdu_text": "تو ہم اُس کے لیے آسانی کا راستہ سہل کر دیں گے",
        "persian_text": "پس ما راه آسانی را برایش مهیا می‌سازیم",
        "english_text": "We will ease him toward ease",
        "transliteration": "Fa sanu-yassiruhu lil-yusrā",
        "verse_number": "7",
    },
    {
        "arabic_text": "وَأَمَّا مَن بَخِلَ وَاسْتَغْنَىٰ",
        "urdu_text": "اور جس نے بخل کیا اور بے پرواہی برتی",
        "persian_text": "و اما کسی که بخل ورزید و بی‌نیازی کرد",
        "english_text": "But as for he who withholds and considers himself free of need",
        "transliteration": "Wa ammā man bakhila wastaghnā",
        "verse_number": "8",
    },
    {
        "arabic_text": "وَكَذَّبَ بِالْحُسْنَىٰ",
        "urdu_text": "اور نیکی کو جھٹلایا",
        "persian_text": "و نیکی را تکذیب کرد",
        "english_text": "And denies the best [reward]",
        "transliteration": "Wa kadhdhaba bil-husnā",
        "verse_number": "9",
    },
]
[
    {
        "arabic_text": "فَسَنُيَسِّرُهُ لِلْعُسْرَىٰ",
        "urdu_text": "تو ہم اسے سختی (مشکل) کے لیے سہولت دیں گے",
        "persian_text": "پس او را برای دشواری آماده خواهیم کرد",
        "english_text": "We will ease him toward hardship",
        "transliteration": "Fa sanu-yassiruhu lil-‘usrā",
        "verse_number": "10",
    },
    {
        "arabic_text": "وَمَا يُغْنِي عَنْهُ مَالُهُ إِذَا تَرَدَّىٰ",
        "urdu_text": "اور اس کا مال اس کے کچھ کام نہ آئے گا جب وہ ہلاکت میں پڑے گا",
        "persian_text": "و دارایی‌اش هنگامی که به هلاکت افتد، سودی نخواهد داد",
        "english_text": "And his wealth will not avail him when he falls",
        "transliteration": "Wa mā yughni ‘anhu māluhu idhā taraddā",
        "verse_number": "11",
    },
    {
        "arabic_text": "إِنَّ عَلَيْنَا لَلْهُدَىٰ",
        "urdu_text": "بے شک ہمارے ذمے ہدایت دینا ہے",
        "persian_text": "همانا راهنمایی بر عهده ماست",
        "english_text": "Indeed, upon Us is guidance",
        "transliteration": "Inna ‘alaynā lal-hudā",
        "verse_number": "12",
    },
    {
        "arabic_text": "وَإِنَّ لَنَا لَلْآخِرَةَ وَالْأُولَىٰ",
        "urdu_text": "اور بے شک ہمارے ہی لیے آخرت بھی ہے اور دنیا بھی",
        "persian_text": "و همانا آخرت و دنیا از آن ماست",
        "english_text": "And indeed, to Us belongs the Hereafter and the first [life]",
        "transliteration": "Wa inna lanā lal-ākhirata wal-ūlā",
        "verse_number": "13",
    },
    {
        "arabic_text": "فَأَنذَرْتُكُمْ نَارًا تَلَظَّىٰ",
        "urdu_text": "پھر میں نے تمہیں بھڑکتی ہوئی آگ سے ڈرایا",
        "persian_text": "پس شما را از آتشی شعله‌ور بیم دادم",
        "english_text": "So I have warned you of a Fire which is blazing",
        "transliteration": "Fa andhartukum nāran talazzā",
        "verse_number": "14",
    },
    {
        "arabic_text": "لَا يَصْلَاهَا إِلَّا الْأَشْقَى",
        "urdu_text": "اس میں نہیں داخل ہوگا مگر بدبخت",
        "persian_text": "در آن وارد نمی‌شود مگر تیره‌بخت‌ترین",
        "english_text": "None will burn in it except the most wretched one",
        "transliteration": "Lā yaṣlāhā illā al-ashqā",
        "verse_number": "15",
    },
    {
        "arabic_text": "الَّذِي كَذَّبَ وَتَوَلَّىٰ",
        "urdu_text": "جس نے جھٹلایا اور منہ موڑ لیا",
        "persian_text": "آن کسی که تکذیب کرد و روی برگرداند",
        "english_text": "Who had denied and turned away",
        "transliteration": "Allaḏī kadhdhaba wa tawallā",
        "verse_number": "16",
    },
    {
        "arabic_text": "وَسَيُجَنَّبُهَا الْأَتْقَى",
        "urdu_text": "اور اس سے دور رکھا جائے گا پرہیزگار",
        "persian_text": "و پرهیزگار از آن دور نگه‌داشته خواهد شد",
        "english_text": "But the righteous one will avoid it",
        "transliteration": "Wa sayujannabu-hal-atqā",
        "verse_number": "17",
    },
    {
        "arabic_text": "الَّذِي يُؤْتِي مَالَهُ يَتَزَكَّىٰ",
        "urdu_text": "جو اپنا مال دیتا ہے تاکہ پاک ہو جائے",
        "persian_text": "آن که مالش را می‌دهد تا پاک شود",
        "english_text": "He who gives his wealth to purify himself",
        "transliteration": "Allaḏī yu’tī mālahū yatazakkā",
        "verse_number": "18",
    },
    {
        "arabic_text": "وَمَا لِأَحَدٍ عِندَهُ مِن نِّعْمَةٍ تُجْزَىٰ",
        "urdu_text": "اور کسی کا اس پر کوئی احسان نہیں جس کا بدلہ دینا ہو",
        "persian_text": "و برای او نزد کسی نعمتی نیست که پاداش داده شود",
        "english_text": "And not [giving] for anyone who has [done him] a favor to be rewarded",
        "transliteration": "Wa mā li’ahadin ‘indahū min ni‘matin tujzā",
        "verse_number": "19",
    },
    {
        "arabic_text": "إِلَّا ابْتِغَاءَ وَجْهِ رَبِّهِ الْأَعْلَىٰ",
        "urdu_text": "سوائے اپنے ربِ اعلیٰ کی رضا کے طلب کے",
        "persian_text": "جز برای طلب رضای پروردگار والای خود",
        "english_text": "But only seeking the countenance of his Lord, Most High",
        "transliteration": "Illāb’tighā’a wajhi rabbihil-a‘lā",
        "verse_number": "20",
    },
    {
        "arabic_text": "وَلَسَوْفَ يَرْضَىٰ",
        "urdu_text": "اور عنقریب وہ راضی ہو جائے گا",
        "persian_text": "و به زودی خشنود خواهد شد",
        "english_text": "And he is going to be satisfied",
        "transliteration": "Wa lasawfa yarḍā",
        "verse_number": "21",
    },
]
