ayats = [
    {
        "arabic_text": "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ",
        "urdu_text": "کیا تم نے اسے دیکھا جو روزِ جزا کو جھٹلاتا ہے",
        "persian_text": "آیا کسی را که روز جزا را انکار می‌کند دیدی؟",
        "english_text": "Have you seen the one who denies the Recompense?",
        "transliteration": "Ara'ayta allathee yukazzibu biddin",
        "verse_number": "1",
    },
    {
        "arabic_text": "فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ",
        "urdu_text": "تو وہی ہے جو یتیم کو دھکے دیتا ہے",
        "persian_text": "پس او همان کسی است که یتیم را می‌راند",
        "english_text": "Then such is the one who repulses the orphan",
        "transliteration": "Fazalika allathee yad'uul yateem",
        "verse_number": "2",
    },
    {
        "arabic_text": "وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ",
        "urdu_text": "اور مسکین کو کھانا کھلانے کی ترغیب نہیں دیتا",
        "persian_text": "و دیگران را به اطعام نیازمندان تشویق نمی‌کند",
        "english_text": "And does not encourage the feeding of the poor",
        "transliteration": "Wala yahuddu 'ala ta'amil miskeen",
        "verse_number": "3",
    },
    {
        "arabic_text": "فَوَيْلٌ لِّلْمُصَلِّينَ",
        "urdu_text": "پس ان نمازیوں کے لیے افسوس ہے",
        "persian_text": "پس وای بر نمازگزاران",
        "english_text": "So woe to those who pray",
        "transliteration": "Fawaylul lil musalleen",
        "verse_number": "4",
    },
    {
        "arabic_text": "الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ",
        "urdu_text": "جو اپنی نماز سے غافل رہتے ہیں",
        "persian_text": "کسانی که از نمازشان غافلند",
        "english_text": "Those who are heedless of their prayers",
        "transliteration": "Alladheena hum 'an salatihim saahoon",
        "verse_number": "5",
    },
    {
        "arabic_text": "الَّذِينَ هُمْ يُرَاءُونَ",
        "urdu_text": "جو دکھاوا کرتے ہیں",
        "persian_text": "کسانی که ریاکاری می‌کنند",
        "english_text": "Those who make show (of their deeds)",
        "transliteration": "Alladheena hum yura'oon",
        "verse_number": "6",
    },
    {
        "arabic_text": "وَيَمْنَعُونَ الْمَاعُونَ",
        "urdu_text": "اور معمولی چیزیں دینے سے بھی گریز کرتے ہیں",
        "persian_text": "و از کمک‌های کوچک خودداری می‌کنند",
        "english_text": "And withhold simple assistance",
        "transliteration": "Wayamna'oonal maa'oon",
        "verse_number": "7",
    },
]
