ayats = [
    {
        "verse_number": "1",
        "arabic_text": "وَيْلٌۭ لِّلْمُطَفِّفِينَ",
        "urdu_text": "خرابی ہے ناپ تول میں کمی کرنے والوں کے لیے",
        "persian_text": "وای بر کم‌فروشان",
        "english_text": "Woe to those who give less [than due],",
        "transliteration": "Wailul lil-muṭaffifīn",
    },
    {
        "verse_number": "2",
        "arabic_text": "ٱلَّذِينَ إِذَا ٱكْتَالُواْ عَلَى ٱلنَّاسِ يَسْتَوْفُونَ",
        "urdu_text": "جو لوگوں سے ناپ کر لیتے ہیں تو پورا لیتے ہیں",
        "persian_text": "آنان که چون از مردم پیمانه می‌گیرند، تمام می‌گیرند",
        "english_text": "Who, when they take a measure from people, take in full.",
        "transliteration": "Alladhīna idhāk tālū ‘ala an-nāsi yastawfūn",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَإِذَا كَالُوهُمْ أَو وَّزَنُوهُمْ يُخْسِرُونَ",
        "urdu_text": "اور جب انہیں ناپ کر یا تول کر دیتے ہیں تو کم دیتے ہیں",
        "persian_text": "و چون برای آنان پیمانه یا وزن می‌کنند، کم می‌نهند",
        "english_text": "But if they give by measure or weight to them, they cause loss.",
        "transliteration": "Wa idhā kālūhum aw wazzanūhum yukhsirūn",
    },
    {
        "verse_number": "4",
        "arabic_text": "أَلَا يَظُنُّ أُو۟لَـٰٓئِكَ أَنَّهُم مَّبْعُوثُونَ",
        "urdu_text": "کیا یہ لوگ نہیں سمجھتے کہ انہیں اٹھایا جائے گا",
        "persian_text": "آیا اینان گمان نمی‌کنند که برانگیخته می‌شوند؟",
        "english_text": "Do they not think that they will be resurrected",
        "transliteration": "Alā yaẓunnu ūlā’ika annahum mab‘ūthūn",
    },
    {
        "verse_number": "5",
        "arabic_text": "لِيَوْمٍ عَظِيمٍۢ",
        "urdu_text": "ایک بڑے دن کے لیے",
        "persian_text": "برای روزی بزرگ",
        "english_text": "For a tremendous Day -",
        "transliteration": "Li-yawmin ‘aẓīm",
    },
    {
        "verse_number": "6",
        "arabic_text": "يَوْمَ يَقُومُ ٱلنَّاسُ لِرَبِّ ٱلْعَـٰلَمِينَ",
        "urdu_text": "جس دن لوگ رب العالمین کے حضور کھڑے ہوں گے",
        "persian_text": "روزی که مردم برای پروردگار جهانیان می‌ایستند",
        "english_text": "The Day when mankind will stand before the Lord of the worlds?",
        "transliteration": "Yawma yaqūmu an-nāsu li-Rabbi al-‘ālamīn",
    },
    {
        "verse_number": "7",
        "arabic_text": "كَلَّآ إِنَّ كِتَـٰبَ ٱلْفُجَّارِ لَفِى سِجِّينٍۢ",
        "urdu_text": "یقیناً بدکاروں کا نامہ اعمال سیجّین میں ہے",
        "persian_text": "هرگز چنین نیست، به‌راستی نامه عمل گناهکاران در سجّین است",
        "english_text": "No! Indeed, the record of the wicked is in sijjeen.",
        "transliteration": "Kallā inna kitāba al-fujjāri la fī sijjīn",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَمَآ أَدْرَىٰكَ مَا سِجِّينٌۭ",
        "urdu_text": "اور تمہیں کیا معلوم کہ سیجّین کیا ہے؟",
        "persian_text": "و چه می‌دانی سجّین چیست؟",
        "english_text": "And what can make you know what is sijjeen?",
        "transliteration": "Wa mā adrāka mā sijjīn",
    },
    {
        "verse_number": "9",
        "arabic_text": "كِتَـٰبٌۭ مَّرْقُومٌۭ",
        "urdu_text": "ایک لکھی ہوئی کتاب ہے",
        "persian_text": "کتابی نوشته شده",
        "english_text": "It is their destination recorded in a register inscribed.",
        "transliteration": "Kitābun marqūm",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَيْلٌۭ يَوْمَئِذٍۢ لِّلْمُكَذِّبِينَ",
        "urdu_text": "تباہی ہے اس دن جھٹلانے والوں کے لیے",
        "persian_text": "وای بر تکذیب‌کنندگان در آن روز",
        "english_text": "Woe, that Day, to the deniers,",
        "transliteration": "Wailun yawma’idhin lil-mukadhdhibīn",
    },
    {
        "verse_number": "83:11",
        "arabic_text": "ٱلَّذِينَ يُكَذِّبُونَ بِيَوْمِ ٱلدِّينِ",
        "urdu_text": "وہ جو جزا کے دن کو جھٹلاتے ہیں",
        "persian_text": "کسانی که روز جزا را انکار می‌کنند",
        "english_text": "Those who deny the Day of Judgment.",
        "transliteration": "Alladhīna yukadhdhibūna biyawmi ad-dīn",
    },
    {
        "verse_number": "83:12",
        "arabic_text": "وَمَا يُكَذِّبُ بِهِۦٓ إِلَّا كُلُّ مُعْتَدٍ أَثِيمٍ",
        "urdu_text": "اور اس کا انکار وہی کرتا ہے جو حد سے بڑھنے والا گناہگار ہے",
        "persian_text": "و آن را جز هر متجاوز گناهکارى انکار نمی‌کند",
        "english_text": "And none denies it except every sinful transgressor.",
        "transliteration": "Wa mā yukadhdhibu bihī illā kullu muʿ'tadin athīm",
    },
    {
        "verse_number": "83:13",
        "arabic_text": "إِذَا تُتْلَىٰ عَلَيْهِ ءَايَاتُنَا قَالَ أَسَٰطِيرُ ٱلْأَوَّلِينَ",
        "urdu_text": "جب اس پر ہماری آیات پڑھی جاتی ہیں تو کہتا ہے: یہ پہلوں کی کہانیاں ہیں",
        "persian_text": "چون آيات ما بر او خوانده می‌شود، می‌گويد: اين افسانه‌هاى گذشتگان است",
        "english_text": "When Our verses are recited to him, he says, 'Legends of the former peoples.'",
        "transliteration": "Idhā tutlā ʿalayhi āyātunā qāla asāṭīru l-awwalīn",
    },
    {
        "verse_number": "83:14",
        "arabic_text": "كَلَّا ۖ بَلْ ۜ رَانَ عَلَىٰ قُلُوبِهِم مَّا كَانُوا۟ يَكْسِبُونَ",
        "urdu_text": "ہرگز نہیں، بلکہ ان کے دلوں پر ان کے اعمال کا زنگ چڑھ گیا ہے",
        "persian_text": "چنین نیست، بلکه آنچه می‌کردند زنگار بر دل‌هایشان نهاده است",
        "english_text": "Nay! But on their hearts is the stain of that which they used to earn.",
        "transliteration": "Kallā bal rāna ʿalā qulūbihim mā kānū yaksibūn",
    },
    {
        "verse_number": "83:15",
        "arabic_text": "كَلَّآ إِنَّهُمْ عَن رَّبِّهِمْ يَوْمَئِذٍۢ لَّمَحْجُوبُونَ",
        "urdu_text": "ہرگز نہیں! یقیناً وہ اس دن اپنے رب سے اوٹ میں رکھے جائیں گے",
        "persian_text": "چنین نیست، در آن روز آنان از پروردگارشان محجوب‌اند",
        "english_text": "Nay! Surely, they will be veiled from their Lord that Day.",
        "transliteration": "Kallā innahum ʿan rabbihim yawma’idhin la-maḥjūbūn",
    },
    {
        "verse_number": "83:16",
        "arabic_text": "ثُمَّ إِنَّهُمْ لَصَالُوا۟ ٱلْجَحِيمِ",
        "urdu_text": "پھر وہ ضرور جہنم میں داخل ہوں گے",
        "persian_text": "سپس بی‌تردید وارد دوزخ خواهند شد",
        "english_text": "Then indeed, they will [enter and] burn in Hellfire.",
        "transliteration": "Thumma innahum laṣālū al-jaḥīm",
    },
    {
        "verse_number": "83:17",
        "arabic_text": "ثُمَّ يُقَالُ هَٰذَا ٱلَّذِى كُنتُم بِهِۦ تُكَذِّبُونَ",
        "urdu_text": "پھر کہا جائے گا: یہی وہ چیز ہے جسے تم جھٹلایا کرتے تھے",
        "persian_text": "سپس گفته می‌شود: اين همان چيزی است كه آن را انكار مى‌كرديد",
        "english_text": "Then it will be said, 'This is what you used to deny.'",
        "transliteration": "Thumma yuqālu hādhā alladhī kuntum bihi tukadhdhibūn",
    },
    {
        "verse_number": "83:18",
        "arabic_text": "كَلَّآ إِنَّ كِتَٰبَ ٱلْأَبْرَارِ لَفِى عِلِّيِّينَ",
        "urdu_text": "یقیناً نیک لوگوں کا ریکارڈ اعلیٰ مقام پر ہے",
        "persian_text": "بی‌گمان نامه اعمال نيكان در عليين است",
        "english_text": "Nay! Verily, the record of the righteous is in 'Illiyyīn.",
        "transliteration": "Kallā inna kitāba al-abrār la-fī ʿilliyyīn",
    },
    {
        "verse_number": "83:19",
        "arabic_text": "وَمَآ أَدْرَىٰكَ مَا عِلِّيُّونَ",
        "urdu_text": "اور تم کیا جانو کہ 'علیین' کیا ہے؟",
        "persian_text": "و تو چه دانی که عليين چيست؟",
        "english_text": "And what will make you know what 'Illiyyīn is?",
        "transliteration": "Wa mā adrāka mā ʿilliyyūn",
    },
    {
        "verse_number": "83:20",
        "arabic_text": "كِتَٰبٌۭ مَّرْقُومٌۭ",
        "urdu_text": "ایک لکھی ہوئی کتاب ہے",
        "persian_text": "نامه‌اى است نوشته شده",
        "english_text": "It is a written record.",
        "transliteration": "Kitābun marqūm",
    },
    {
        "verse_number": "83:21",
        "arabic_text": "يَشْهَدُهُ ٱلْمُقَرَّبُونَ",
        "urdu_text": "اس کے گواہ مقرب فرشتے ہوں گے",
        "persian_text": "مقربان گواه آن خواهند بود",
        "english_text": "Witnessed by those brought near [to Allah].",
        "transliteration": "Yashhaduhu al-muqarrabūn",
    },
    {
        "verse_number": "83:22",
        "arabic_text": "إِنَّ ٱلْأَبْرَارَ لَفِى نَعِيمٍۢ",
        "urdu_text": "یقیناً نیک لوگ نعمتوں میں ہوں گے",
        "persian_text": "بی‌گمان نيكان در نعمت خواهند بود",
        "english_text": "Indeed, the righteous will be in pleasure.",
        "transliteration": "Inna al-abrāra la-fī naʿīm",
    },
    {
        "verse_number": "83:23",
        "arabic_text": "عَلَى ٱلْأَرَآئِكِ يَنظُرُونَ",
        "urdu_text": "وہ تختوں پر بیٹھے نظارے کر رہے ہوں گے",
        "persian_text": "بر تخت‌ها تكيه زده نظاره می‌کنند",
        "english_text": "On adorned couches, observing.",
        "transliteration": "ʿAlā al-arā’iki yanẓurūn",
    },
    {
        "verse_number": "83:24",
        "arabic_text": "تَعْرِفُ فِى وُجُوهِهِمْ نَضْرَةَ ٱلنَّعِيمِ",
        "urdu_text": "تو ان کے چہروں پر نعمتوں کی تازگی پہچان لے گا",
        "persian_text": "در چهره‌هايشان طراوت نعمت را می‌بينى",
        "english_text": "You will recognize in their faces the radiance of pleasure.",
        "transliteration": "Taʿrifu fī wujūhihim naḍrata al-naʿīm",
    },
    {
        "verse_number": "83:25",
        "arabic_text": "يُسْقَوْنَ مِن رَّحِيقٍۢ مَّخْتُومٍۢ",
        "urdu_text": "انہیں بند کی ہوئی خالص شراب پلائی جائے گی",
        "persian_text": "از شرابی مهر شده نوشانده می‌شوند",
        "english_text": "They will be given to drink [pure] wine sealed.",
        "transliteration": "Yusqawna min raḥīqin makhtūm",
    },
    {
        "verse_number": "83:26",
        "arabic_text": "خِتَٰمُهُۥ مِسْكٌۭ ۚ وَفِى ذَٰلِكَ فَلْيَتَنَافَسِ ٱلْمُتَنَٰفِسُونَ",
        "urdu_text": "جس کا خاتمہ کستوری پر ہوگا، اور اسی میں ہوڑ کرنے والے مقابلہ کریں",
        "persian_text": "پايان آن مشک است، پس مشتاقان بايد در آن رقابت كنند",
        "english_text": "Its seal is musk – so for this let the competitors compete.",
        "transliteration": "Khitāmuhu misk, wa fī dhālika falyatanāfasi al-mutanāfisūn",
    },
    {
        "verse_number": "83:27",
        "arabic_text": "وَمِزَاجُهُۥ مِن تَسْنِيمٍۢ",
        "urdu_text": "اور اس میں تسنیم کی آمیزش ہوگی",
        "persian_text": "و آمیخته‌اش از چشمه تسنيم خواهد بود",
        "english_text": "And its mixture is of Tasneem,",
        "transliteration": "Wa mizājuhu min tasnīm",
    },
    {
        "verse_number": "83:28",
        "arabic_text": "عَيْنًۭا يَشْرَبُ بِهَا ٱلْمُقَرَّبُونَ",
        "urdu_text": "ایک چشمہ، جس سے مقربین پئیں گے",
        "persian_text": "چشمه‌اى كه نزديكان [خدا] از آن مى‌نوشند",
        "english_text": "A spring from which those near [to Allah] drink.",
        "transliteration": "ʿAynan yashrabu bihā al-muqarrabūn",
    },
    {
        "verse_number": "83:29",
        "arabic_text": "إِنَّ ٱلَّذِينَ أَجْرَمُوا۟ كَانُوا۟ مِنَ ٱلَّذِينَ ءَامَنُوا۟ يَضْحَكُونَ",
        "urdu_text": "بے شک جو مجرم تھے وہ ایمان والوں پر ہنسا کرتے تھے",
        "persian_text": "بی‌گمان گناهكاران بر مؤمنان مى‌خنديدند",
        "english_text": "Indeed, those who committed crimes used to laugh at those who believed.",
        "transliteration": "Inna alladhīna ajramū kānū mina alladhīna āmanū yaḍḥakūn",
    },
    {
        "verse_number": "83:30",
        "arabic_text": "وَإِذَا مَرُّوا۟ بِهِمْ يَتَغَامَزُونَ",
        "urdu_text": "اور جب ان کے پاس سے گزرتے تو آنکھوں سے اشارے کرتے",
        "persian_text": "و چون بر آنان مى‌گذشتند با اشاره و چشمك خنده مى‌كردند",
        "english_text": "And when they passed by them, they would exchange derisive glances.",
        "transliteration": "Wa idhā marrū bihim yataghāmazūn",
    },
    {
        "verse_number": "83:31",
        "arabic_text": "وَإِذَا ٱنقَلَبُوٓا۟ إِلَىٰٓ أَهْلِهِمُ ٱنقَلَبُوا۟ فَكِهِينَ",
        "urdu_text": "اور جب اپنے لوگوں کے پاس لوٹتے تو خوشی خوشی لوٹتے",
        "persian_text": "و چون به سوى خانواده‌شان باز مى‌گشتند شادمان باز مى‌گشتند",
        "english_text": "And when they returned to their people, they would return jesting.",
        "transliteration": "Wa idhā inqalabū ilā ahlihim inqalabū fakihīn",
    },
    {
        "verse_number": "83:32",
        "arabic_text": "وَإِذَا رَأَوْهُمْ قَالُوٓا۟ إِنَّ هَـٰٓؤُلَآءِ لَضَآلُّونَ",
        "urdu_text": "اور جب انہیں دیکھتے تو کہتے: یہ لوگ گمراہ ہیں",
        "persian_text": "و چون مؤمنان را مى‌ديدند مى‌گفتند: اينان گمراه‌اند",
        "english_text": "And when they saw them, they would say, 'Indeed, those are truly lost.'",
        "transliteration": "Wa idhā ra’awhum qālū inna hā’ulā’i la-ḍāllūn",
    },
    {
        "verse_number": "83:33",
        "arabic_text": "وَمَآ أُرْسِلُوا۟ عَلَيْهِمْ حَـٰفِظِينَ",
        "urdu_text": "حالانکہ وہ ان پر نگران بنا کر نہیں بھیجے گئے تھے",
        "persian_text": "در حالی که نگهبان آنان نبودند",
        "english_text": "But they had not been sent as guardians over them.",
        "transliteration": "Wa mā ursilū ʿalayhim ḥāfiẓīn",
    },
    {
        "verse_number": "83:34",
        "arabic_text": "فَٱلْيَوْمَ ٱلَّذِينَ ءَامَنُوا۟ مِنَ ٱلْكُفَّارِ يَضْحَكُونَ",
        "urdu_text": "پھر آج ایمان والے کافروں پر ہنس رہے ہیں",
        "persian_text": "پس امروز مؤمنان بر كافران مى‌خندند",
        "english_text": "But this Day those who believe are laughing at the disbelievers,",
        "transliteration": "Fa-l-yawma alladhīna āmanū mina al-kuffāri yaḍḥakūn",
    },
    {
        "verse_number": "83:35",
        "arabic_text": "عَلَى ٱلْأَرَآئِكِ يَنظُرُونَ",
        "urdu_text": "تختوں پر بیٹھے دیکھ رہے ہوں گے",
        "persian_text": "بر تخت‌ها نشسته، نظاره می‌کنند",
        "english_text": "On adorned couches, observing.",
        "transliteration": "ʿAlā al-arā’iki yanẓurūn",
    },
    {
        "verse_number": "83:36",
        "arabic_text": "هَلْ ثُوِّبَ ٱلْكُفَّارُ مَا كَانُوا۟ يَفْعَلُونَ",
        "urdu_text": "کیا کافروں کو ان کے اعمال کی پوری جزا دے دی گئی؟",
        "persian_text": "آيا كافران آنچه مى‌كردند پاداش داده شدند؟",
        "english_text": "Have the disbelievers [not] been repaid for what they used to do?",
        "transliteration": "Hal thūwwiba al-kuffāru mā kānū yafʿalūn",
    },
]
