ayats = [
    {
        "arabic_text": "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ",
        "urdu_text": "تباہ ہوں ابو لہب کے دونوں ہاتھ اور خود وہ بھی تباہ ہو جائے",
        "persian_text": "هلاک باد دو دستِ ابو لهب و خود او",
        "english_text": "Perish the hands of Abu Lahab, and perish he!",
        "transliteration": "Tabbat yaday abī lahabin wa tabb",
        "verse_number": 1,
    },
    {
        "Surah": "Al-Masad (Al-Lahab)",
        "arabic_text": "مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ",
        "urdu_text": "نہ اس کا مال کچھ فائدہ دے گا نہ جو وہ کمایا",
        "persian_text": "نه مالش سود بخشید و نه آنچه به دست آورد",
        "english_text": "His wealth will not avail him or that which he gained.",
        "transliteration": "Mā aghnā ‘anhu māluhu wamā kasab",
        "verse_number": 2,
    },
    {
        "Surah": "Al-Masad (Al-Lahab)",
        "arabic_text": "سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ",
        "urdu_text": "وہ ضرور شعلۂ آتش میں داخل ہوگا",
        "persian_text": "به زودی در آتشی شعله‌ور وارد خواهد شد",
        "english_text": "He will [enter to] burn in a Fire of blazing flame.",
        "transliteration": "Sayaslā nāran dhāta lahab",
        "verse_number": 3,
    },
    {
        "Surah": "Al-Masad (Al-Lahab)",
        "arabic_text": "وَامْرَأَتُهُۥ حَمَّالَةَ الْحَطَبِ",
        "urdu_text": "اور اس کی بیوی، جو ہیزم اٹھانے والی ہے",
        "persian_text": "و همسرش که هیزم‌کش است",
        "english_text": "And his wife [as well]—the carrier of firewood—",
        "transliteration": "Wa­imra’atuhu ḥammālata-l-ḥaṭab",
        "verse_number": 4,
    },
    {
        "Surah": "Al-Masad (Al-Lahab)",
        "arabic_text": "فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ",
        "urdu_text": "جو اس کی گردن میں رسی مسد کی بندھی ہوئی ہے",
        "persian_text": "در گردن او ریسمانی از لیف خرماست",
        "english_text": "Around her neck is a rope of twisted fiber.",
        "transliteration": "Fī jīdihā ḥablun min masad",
        "verse_number": 5,
    },
]
