ayats = [
    {
        "verse_number": "1",
        "arabic_text": "عَمَّ يَتَسَاءَلُونَ",
        "urdu_text": "کس چیز کے بارے میں آپس میں سوال کرتے ہیں؟",
        "persian_text": "از چه چیزی از یکدیگر می‌پرسند؟",
        "english_text": "What are they asking one another about?",
        "transliteration": "ʿAmma yatasaā'alūn",
    },
    {
        "verse_number": "2",
        "arabic_text": "عَنِ النَّبَإِ الْعَظِيمِ",
        "urdu_text": "اس بڑی خبر کے بارے میں",
        "persian_text": "درباره خبر بزرگ",
        "english_text": "About the momentous news,",
        "transliteration": "ʿAni n-naba'i l-ʿaẓīm",
    },
    {
        "verse_number": "3",
        "arabic_text": "الَّذِي هُمْ فِيهِ مُخْتَلِفُونَ",
        "urdu_text": "جس کے بارے میں وہ اختلاف کر رہے ہیں",
        "persian_text": "که در آن اختلاف دارند",
        "english_text": "Over which they disagree.",
        "transliteration": "Alladhī hum fīhi mukhtalifūn",
    },
    {
        "verse_number": "4",
        "arabic_text": "كَلَّا سَيَعْلَمُونَ",
        "urdu_text": "ہرگز نہیں، وہ عنقریب جان لیں گے",
        "persian_text": "نه چنین است، به زودی خواهند دانست",
        "english_text": "No! They will soon know.",
        "transliteration": "Kallā sayaʿlamūn",
    },
    {
        "verse_number": "5",
        "arabic_text": "ثُمَّ كَلَّا سَيَعْلَمُونَ",
        "urdu_text": "پھر ہرگز نہیں، وہ عنقریب جان لیں گے",
        "persian_text": "باز نه، به زودی خواهند دانست",
        "english_text": "Again, no! They will soon know.",
        "transliteration": "Thumma kallā sayaʿlamūn",
    },
    {
        "verse_number": "6",
        "arabic_text": "أَلَمْ نَجْعَلِ الْأَرْضَ مِهَـٰدًا",
        "urdu_text": "کیا ہم نے زمین کو فرش نہیں بنایا؟",
        "persian_text": "آیا زمین را بستر (آسایش) قرار ندادیم؟",
        "english_text": "Have We not made the earth as a cradle?",
        "transliteration": "Alam najʿali l-arḍa mihādā",
    },
    {
        "verse_number": "7",
        "arabic_text": "وَالْجِبَالَ أَوْتَادًا",
        "urdu_text": "اور پہاڑوں کو میخیں (نہیں بنایا)؟",
        "persian_text": "و کوه‌ها را میخ‌هایی (نگه‌دارنده) نساختیم؟",
        "english_text": "And the mountains as pegs?",
        "transliteration": "Wal-jibāla awtādā",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَخَلَقْنَـٰكُمْ أَزْوَاجًا",
        "urdu_text": "اور ہم نے تمہیں جوڑے جوڑے پیدا کیا",
        "persian_text": "و شما را جفت‌جفت آفریدیم",
        "english_text": "And We created you in pairs,",
        "transliteration": "Wa khalaqnākum azwājā",
    },
    {
        "verse_number": "9",
        "arabic_text": "وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا",
        "urdu_text": "اور تمہاری نیند کو آرام کا ذریعہ بنایا",
        "persian_text": "و خواب شما را مایه آرامش قرار دادیم",
        "english_text": "And made your sleep for rest,",
        "transliteration": "Wa jaʿalnā nawmakum subātā",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَجَعَلْنَا اللَّيْلَ لِبَاسًا",
        "urdu_text": "اور رات کو ہم نے پردہ (لباس) بنایا",
        "persian_text": "و شب را پوششی برای شما قرار دادیم",
        "english_text": "And made the night as a covering,",
        "transliteration": "Wa jaʿalnā l-layla libāsā",
    },
    {
        "verse_number": "11",
        "arabic_text": "وَجَعَلْنَا النَّهَارَ مَعَاشًا",
        "urdu_text": "اور دن کو ہم نے زندگی کا ذریعہ بنایا",
        "persian_text": "و روز را وسیله زندگی و کسب و کار قرار دادیم",
        "english_text": "And made the day for livelihood,",
        "transliteration": "Wa jaʿalnā n-nahāra maʿāshā",
    },
    {
        "verse_number": "12",
        "arabic_text": "وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًا",
        "urdu_text": "اور تمہارے اوپر ہم نے سات مضبوط آسمان بنائے",
        "persian_text": "و بالای سر شما هفت آسمان نیرومند بنا کردیم",
        "english_text": "And built above you seven strong heavens,",
        "transliteration": "Wa banaynā fawqakum sabʿan shidādā",
    },
    {
        "verse_number": "13",
        "arabic_text": "وَجَعَلْنَا سِرَاجًا وَهَّاجًا",
        "urdu_text": "اور ہم نے ایک چمکتا ہوا چراغ بنایا",
        "persian_text": "و چراغی فروزان (خورشید) قرار دادیم",
        "english_text": "And made a blazing lamp,",
        "transliteration": "Wa jaʿalnā sirājāw wahhājā",
    },
    {
        "verse_number": "14",
        "arabic_text": "وَأَنزَلْنَا مِنَ الْمُعْصِرـٰتِ مَاءً ثَجَّاجًا",
        "urdu_text": "اور ہم نے پانی والے بادلوں سے خوب برسنے والا پانی نازل کیا",
        "persian_text": "و از ابرهای فشرده، آبی فراوان نازل کردیم",
        "english_text": "And We sent down from the rain clouds pouring water,",
        "transliteration": "Wa anzalnā mina l-muʿṣirāti māʾan thajjājā",
    },
    {
        "verse_number": "15",
        "arabic_text": "لِّنُخْرِجَ بِهِۦ حَبّٗا وَنَبَاتٗا",
        "urdu_text": "تاکہ ہم اس سے اناج اور سبزہ اگائیں",
        "persian_text": "تا از آن دانه‌ها و گیاهان برویانیم",
        "english_text": "That We may bring forth thereby grain and vegetation,",
        "transliteration": "Linuḫrija bihī ḥabbāw wa nabātā",
    },
    {
        "verse_number": "16",
        "arabic_text": "وَجَنَّـٰتٍ أَلْفَافًا",
        "urdu_text": "اور گھنے باغات پیدا کریں",
        "persian_text": "و باغ‌هایی پرشاخ و برگ برویانیم",
        "english_text": "And gardens of thick growth.",
        "transliteration": "Wa jannātin alfāfā",
    },
    {
        "verse_number": "17",
        "arabic_text": "إِنَّ يَوْمَ الْفَصْلِ كَانَ مِيقَاتًا",
        "urdu_text": "بے شک فیصلے کا دن مقرر ہے",
        "persian_text": "همانا روز داوری (قیامت) زمانی معین دارد",
        "english_text": "Indeed, the Day of Decision is a fixed time.",
        "transliteration": "Inna yawma l-faṣli kāna mīqātā",
    },
    {
        "verse_number": "18",
        "arabic_text": "يَوْمَ يُنفَخُ فِي ٱلصُّورِ فَتَأْتُونَ أَفْوَاجًا",
        "urdu_text": "جس دن صور پھونکا جائے گا تو تم فوج در فوج آؤ گے",
        "persian_text": "روزی که در صور دمیده می‌شود و شما دسته دسته می‌آیید",
        "english_text": "The Day the Trumpet is blown and you will come forth in multitudes,",
        "transliteration": "Yawma yunfakhu fī ṣ-ṣūri fataʾtūna afwājā",
    },
    {
        "verse_number": "19",
        "arabic_text": "وَفُتِّحَتِ ٱلسَّمَآءُ فَكَانَتْ أَبْوَٰبٗا",
        "urdu_text": "اور آسمان کھولا جائے گا تو وہ دروازے بن جائے گا",
        "persian_text": "و آسمان گشوده می‌شود و به درهایی مبدل می‌گردد",
        "english_text": "And the sky is opened and becomes gateways,",
        "transliteration": "Wa futtiḥati s-samāʾu fakānat abwābā",
    },
    {
        "verse_number": "20",
        "arabic_text": "وَسُيِّرَتِ ٱلْجِبَالُ فَكَانَتْ سَرَابًا",
        "urdu_text": "اور پہاڑ چلائے جائیں گے تو وہ سراب بن جائیں گے",
        "persian_text": "و کوه‌ها به حرکت درمی‌آیند و به سراب تبدیل می‌شوند",
        "english_text": "And the mountains are set in motion and become a mirage.",
        "transliteration": "Wa suyyiratil-jibālu fakānat sarābā",
    },
    {
        "verse_number": "21",
        "arabic_text": "إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا",
        "urdu_text": "یقیناً جہنم گھات میں ہے",
        "persian_text": "بی‌گمان دوزخ در کمین است",
        "english_text": "Indeed, Hell has been lying in wait,",
        "transliteration": "Inna jahannama kānat mirṣādā",
    },
    {
        "verse_number": "22",
        "arabic_text": "لِّلطَّاغِينَ مَآبًا",
        "urdu_text": "سرکشوں کے لیے ٹھکانہ",
        "persian_text": "جایگاه بازگشت برای طغیان‌گران است",
        "english_text": "For the transgressors a place of return,",
        "transliteration": "Lil-ṭāghīna maʾābā",
    },
    {
        "verse_number": "23",
        "arabic_text": "لَّـٰبِثِينَ فِيهَا أَحْقَابًا",
        "urdu_text": "جس میں وہ مدتوں تک رہیں گے",
        "persian_text": "که در آن سال‌ها خواهند ماند",
        "english_text": "In which they will remain for ages,",
        "transliteration": "Lābithīna fīhā aḥqābā",
    },
    {
        "verse_number": "24",
        "arabic_text": "لَا يَذُوقُونَ فِيهَا بَرْدٗا وَلَا شَرَابًا",
        "urdu_text": "نہ وہ اس میں کوئی ٹھنڈک پائیں گے اور نہ کوئی مشروب",
        "persian_text": "در آن نه خنکی می‌چشند و نه نوشیدنی",
        "english_text": "They will not taste therein any coolness or drink,",
        "transliteration": "Lā yadhūqūna fīhā bardaw wa lā sharābā",
    },
    {
        "verse_number": "25",
        "arabic_text": "إِلَّا حَمِيمٗا وَغَسَّاقًا",
        "urdu_text": "سوائے کھولتے پانی اور پیپ کے",
        "persian_text": "جز آب داغ و چرکین چیزی نمی‌نوشند",
        "english_text": "Except scalding water and pus –",
        "transliteration": "Illā ḥamīman wa ghassāqā",
    },
    {
        "verse_number": "26",
        "arabic_text": "جَزَاءٗ وِفَاقًا",
        "urdu_text": "یہ بدلہ ان کے اعمال کے مطابق ہے",
        "persian_text": "پاداشی مناسب با کردارشان است",
        "english_text": "An appropriate recompense.",
        "transliteration": "Jazāʾan wifāqā",
    },
    {
        "verse_number": "27",
        "arabic_text": "إِنَّهُمْ كَانُوا لَا يَرْجُونَ حِسَابٗا",
        "urdu_text": "بے شک وہ حساب کی امید نہیں رکھتے تھے",
        "persian_text": "آنان به حساب‌رسی ایمان نداشتند",
        "english_text": "Indeed, they did not expect an account,",
        "transliteration": "Innahum kānū lā yarjūna ḥisābā",
    },
    {
        "verse_number": "28",
        "arabic_text": "وَكَذَّبُوا۟ بِـَٔايَٰتِنَا كِذَّابٗا",
        "urdu_text": "اور ہماری آیات کو جھٹلایا، جھٹلانے کی حد تک",
        "persian_text": "و آیات ما را شدیداً تکذیب کردند",
        "english_text": "And denied Our signs with [emphatic] denial.",
        "transliteration": "Wa kadhdhabū bi-āyātinā kidhdhābā",
    },
    {
        "verse_number": "29",
        "arabic_text": "وَكُلَّ شَيْءٍ أَحْصَيْنَٰهُ كِتَٰبٗا",
        "urdu_text": "اور ہم نے ہر چیز کو ایک کتاب میں گن رکھا ہے",
        "persian_text": "و هر چیز را در کتابی ثبت کرده‌ایم",
        "english_text": "But all things We have enumerated in writing.",
        "transliteration": "Wa kulla shay'in aḥṣaynāhu kitābā",
    },
    {
        "verse_number": "30",
        "arabic_text": "فَذُوقُوا۟ فَلَن نَّزِيدَكُمْ إِلَّا عَذَابًا",
        "urdu_text": "پس چکھو، ہم تمہیں عذاب ہی بڑھاتے جائیں گے",
        "persian_text": "پس بچشید، ما چیزی جز عذاب بر شما نمی‌افزاییم",
        "english_text": "So taste [the penalty], and We will not increase you except in punishment.",
        "transliteration": "Fa dhūqū fa lan nazeedakum illā ʿadhābā",
    },
    {
        "verse_number": "31",
        "arabic_text": "إِنَّ لِلْمُتَّقِينَ مَفَازًا",
        "urdu_text": "یقیناً پرہیزگاروں کے لیے کامیابی ہے",
        "persian_text": "بی‌گمان برای پرهیزگاران رستگاری است",
        "english_text": "Indeed, for the righteous is attainment –",
        "transliteration": "Inna lil-muttaqīna mafāzā",
    },
    {
        "verse_number": "32",
        "arabic_text": "حَدَآئِقَ وَأَعْنَابٗا",
        "urdu_text": "باغات اور انگور",
        "persian_text": "باغ‌ها و انگورهایی",
        "english_text": "Gardens and grapevines",
        "transliteration": "Ḥadāʾiqa wa aʿnābā",
    },
    {
        "verse_number": "33",
        "arabic_text": "وَكَوَاعِبَ أَتْرَابٗا",
        "urdu_text": "اور ہم عمر دوشیزائیں",
        "persian_text": "و دخترانی هم‌سن و سال",
        "english_text": "And full-breasted [companions] of equal age",
        "transliteration": "Wa kawāʿiba atrābā",
    },
    {
        "verse_number": "34",
        "arabic_text": "وَكَأْسٗا دِهَاقٗا",
        "urdu_text": "اور چھلکتے جام",
        "persian_text": "و جام‌هایی پر از شراب طهور",
        "english_text": "And a full cup.",
        "transliteration": "Wa kaʾsan dihāqā",
    },
    {
        "verse_number": "35",
        "arabic_text": "لَّا يَسْمَعُونَ فِيهَا لَغْوٗا وَلَا كِذَّٰبًا",
        "urdu_text": "جس میں وہ نہ کوئی لغو بات سنیں گے اور نہ جھوٹ",
        "persian_text": "که در آن نه سخن بیهوده می‌شنوند و نه دروغی",
        "english_text": "No ill speech will they hear therein or any falsehood –",
        "transliteration": "Lā yasmaʿūna fīhā laghwaw wa lā kidhdhābā",
    },
    {
        "verse_number": "36",
        "arabic_text": "جَزَآءٗ مِّن رَّبِّكَ عَطَآءً حِسَابٗا",
        "urdu_text": "یہ آپ کے رب کی طرف سے بدلہ ہے، کافی عطیہ",
        "persian_text": "پاداشی از پروردگارت، عطایی بسنده",
        "english_text": "A reward from your Lord, [a generous] gift [made due to] account,",
        "transliteration": "Jazāʾan min rabbika ʿaṭāʾan ḥisābā",
    },
    {
        "verse_number": "37",
        "arabic_text": "رَّبِّ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَمَا بَيْنَهُمَا ٱلرَّحْمَٰنِ لَا يَمْلِكُونَ مِنْهُ خِطَابٗا",
        "urdu_text": "جو آسمانوں اور زمین اور ان کے درمیان کی ہر چیز کا رب ہے، رحمٰن ہے، لوگ اس سے بات کرنے کا اختیار نہ رکھیں گے",
        "persian_text": "پروردگار آسمان‌ها و زمین و آنچه میان آن‌هاست، بخشاینده‌ای که کسی یارای سخن گفتن با او را ندارد",
        "english_text": "Lord of the heavens and the earth and whatever is between them – the Most Merciful. They do not possess from Him [the authority for] speech.",
        "transliteration": "Rabbis-samāwāti wal-arḍi wa mā baynahumā ar-Raḥmān, lā yamlikūna minhu khiṭābā",
    },
    {
        "verse_number": "38",
        "arabic_text": "يَوْمَ يَقُومُ ٱلرُّوحُ وَٱلْمَلَٰٓئِكَةُ صَفّٗاۖ لَّا يَتَكَلَّمُونَ إِلَّا مَنْ أَذِنَ لَهُ ٱلرَّحْمَٰنُ وَقَالَ صَوَابٗا",
        "urdu_text": "جس دن روح اور فرشتے صف باندھ کر کھڑے ہوں گے، کوئی نہیں بولے گا سوائے جسے رحمٰن اجازت دے اور وہ درست بات کہے",
        "persian_text": "روزی که روح و فرشتگان صف در صف می‌ایستند، جز کسی که خدای رحمان به او اجازه دهد و سخن راست بگوید، کسی سخن نگوید",
        "english_text": "The Day that the Spirit and the angels will stand in rows, they will not speak except for one whom the Most Merciful permits, and he will say what is correct.",
        "transliteration": "Yawma yaqūmu r-rūḥu wal-malāʾikatu ṣaffā, lā yatakallamūna illā man adhina lahur-Raḥmānu wa qāla ṣawābā",
    },
    {
        "verse_number": "39",
        "arabic_text": "ذَٰلِكَ ٱلْيَوْمُ ٱلْحَقُّۖ فَمَن شَآءَ ٱتَّخَذَ إِلَىٰ رَبِّهِۦ مَـَٔابًا",
        "urdu_text": "یہی دن برحق ہے، پس جو چاہے اپنے رب کی طرف پلٹنے کا راستہ بنا لے",
        "persian_text": "این روز، روز حق است؛ پس هر که بخواهد، راه بازگشت به سوی پروردگارش را در پیش گیرد",
        "english_text": "That is the True Day; so he who wills may take to his Lord a [way of] return.",
        "transliteration": "Dhālika l-yawmu l-ḥaqq, faman shāʾattakhadha ilā rabbihi maʾābā",
    },
    {
        "verse_number": "40",
        "arabic_text": "إِنَّآ أَنذَرْنَٰكُمْ عَذَابٗا قَرِيبٗاۖ يَوْمَ يَنظُرُ ٱلْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُولُ ٱلْكَـٰفِرُ يَٰلَيْتَنِي كُنتُ تُرَٰبٗا",
        "urdu_text": "بے شک ہم نے تمہیں ایک قریب آنے والے عذاب سے خبردار کیا ہے، جس دن انسان دیکھے گا جو اس کے ہاتھوں نے آگے بھیجا، اور کافر کہے گا، کاش میں مٹی ہوتا",
        "persian_text": "ما شما را از عذابی نزدیک هشدار دادیم؛ روزی که انسان آنچه را دست‌هایش پیش فرستاده‌اند می‌بیند و کافر می‌گوید: ای کاش خاک بودم!",
        "english_text": "Indeed, We have warned you of a near punishment – the Day when a man will observe what his hands have put forth and the disbeliever will say, 'Oh, I wish that I were dust!'",
        "transliteration": "Innā andharnākum ʿadhāban qarībā, yawma yanẓuru l-marʾu mā qaddamat yadāh, wa yaqūlu l-kāfiru yā laytanī kuntu turābā",
    },
]
