ayats = [
    {
        "arabic_text": "قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
        "urdu_text": "اے لوگوں کے پروردگار کی پناہ مانگتا ہوں",
        "persian_text": "بگو پناه می‌برم به پروردگار مردمان",
        "english_text": "Say, I seek refuge in the Lord of mankind,",
        "transliteration": "Qul a‘ūdhu bi-rabbi-n-nās",
        "verse_number": 1,
    },
    {
        "arabic_text": "مَلِكِ النَّاسِ",
        "urdu_text": "اے لوگوں کے بادشاہ کی پناہ مانگتا ہوں",
        "persian_text": "به پادشاه مردمان",
        "english_text": "The Sovereign of mankind,",
        "transliteration": "Maliki-n-nās",
        "verse_number": 2,
    },
    {
        "arabic_text": "إِلَٰهِ النَّاسِ",
        "urdu_text": "اے لوگوں کے معبود کی پناہ مانگتا ہوں",
        "persian_text": "به معبود مردمان",
        "english_text": "The God of mankind,",
        "transliteration": "Ilāhi-n-nās",
        "verse_number": 3,
    },
    {
        "arabic_text": "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ",
        "urdu_text": "بدی وسوسہ‌گرِ خناس کی",
        "persian_text": "از شر وسوسه‌گر نهان",
        "english_text": "From the evil of the whisperer who withdraws,",
        "transliteration": "Min sharri-l-waswāsi-l-khannās",
        "verse_number": 4,
    },
    {
        "arabic_text": "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ",
        "urdu_text": "جو (انسانوں کے) سینوں میں وسوسے ڈالتا ہے",
        "persian_text": "آن که در سینه‌های مردم وسوسه می‌کند",
        "english_text": "Who whispers in the breasts of mankind,",
        "transliteration": "Alladhī yuwaswisu fī ṣudūri-n-nās",
        "verse_number": 5,
    },
    {
        "arabic_text": "مِنَ الْجِنَّةِ وَالنَّاسِ",
        "urdu_text": "چاہے وہ جنوں میں سے ہو یا انسانوں میں سے",
        "persian_text": "چه از جن و چه از مردم",
        "english_text": "Among jinn and among mankind",
        "transliteration": "Minal-jinnati wann-naas",
        "verse_number": "6",
    },
]
