ayats = [
    {
        "verse_number": "1",
        "arabic_text": "وَٱلنّٰزِعٰتِ غَرْقًا",
        "urdu_text": "قسم ہے ان کی جو زور سے کھینچتے ہیں",
        "persian_text": "سوگند به آنانی که با شدت می‌کشند",
        "english_text": "By those who drag out (souls) with violence;",
        "transliteration": "Wan-nāzi‘āti gharqāan",
    },
    {
        "verse_number": "2",
        "arabic_text": "وَّٱلنّٰشِطٰتِ نَشْطًا",
        "urdu_text": "اور آہستگی سے کھولنے والوں کی",
        "persian_text": "و آنان که به نرمی رها می‌سازند",
        "english_text": "And by those who release gently;",
        "transliteration": "Wan-nāshitāti nashtāan",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَّٱلسّٰبِحٰتِ سَبْحًا",
        "urdu_text": "اور ان کی جو تیرتی ہیں",
        "persian_text": "و آنان که شناکنان می‌روند",
        "english_text": "And by those who glide along (on errands of mercy),",
        "transliteration": "Was-sābihāti sabhāan",
    },
    {
        "verse_number": "4",
        "arabic_text": "فَالسّٰبِقٰتِ سَبْقًا",
        "urdu_text": "پھر سبقت کرنے والوں کی",
        "persian_text": "پس آنانی که پیشی می‌گیرند",
        "english_text": "Then those who race ahead,",
        "transliteration": "Fas-sābiqāti sabqāan",
    },
    {
        "verse_number": "5",
        "arabic_text": "فَالْمُدَبِّرٰتِ أَمْرًا",
        "urdu_text": "پھر وہ جو کام کو سنوارتے ہیں",
        "persian_text": "و آنان که تدبیر می‌کنند کارها را",
        "english_text": "Then those who arrange affairs (according to a plan)",
        "transliteration": "Fal-mudabbirāti amrāan",
    },
    {
        "verse_number": "6",
        "arabic_text": "يَوْمَ تَرْجُفُ ٱلرَّاجِفَةُ",
        "urdu_text": "جس دن زمین کو جھٹکا دیا جایگا",
        "persian_text": "روزی که لرزاننده (زلزله بزرگ) بلرزد",
        "english_text": "On the Day the quaking one will quake,",
        "transliteration": "Yawma tarjufu ar-rājifah",
    },
    {
        "verse_number": "7",
        "arabic_text": "تَتْبَعُهَا ٱلرَّادِفَةُ",
        "urdu_text": "اسکے بعد ایک اور جھٹکا دیا جایگا",
        "persian_text": "و به دنبال آن، زلزله‌ای دیگر خواهد آمد",
        "english_text": "Followed by the subsequent one.",
        "transliteration": "Tatba‘uhā ar-rādifah",
    },
    {
        "verse_number": "8",
        "arabic_text": "قُلُوبٌۭ يَوْمَئِذٍۢ وَّاجِفَةٌ",
        "urdu_text": "اس دن دل لرز جایئنگے",
        "persian_text": "دل‌هایی در آن روز ترسان و لرزان خواهند بود",
        "english_text": "Hearts that Day will tremble,",
        "transliteration": "Qulūbun yawma’idhin wājifah",
    },
    {
        "verse_number": "9",
        "arabic_text": "أَبْصَـارُهَا خَـاشِعَةٌۭ",
        "urdu_text": "ان کی آنکھیں جھکی ہوئی ہوں گی",
        "persian_text": "چشمانشان فرو افتاده و خاضع خواهد بود",
        "english_text": "Their eyes humbled.",
        "transliteration": "Absāruhā khāshi‘ah",
    },
    {
        "verse_number": "10",
        "arabic_text": "يَقُولُونَ أَءِنَّا لَمَرْدُودُونَ فِى ٱلْحَافِرَةِ",
        "urdu_text": "یہ کفّار کہتے ہیں کیا ہم پلٹ کر اس دنیا میں پھر بھیجے جایئنگے ؟",
        "persian_text": "می‌گویند: آیا ما واقعاً به حالت نخستین بازگردانده می‌شویم؟",
        "english_text": "They say, 'Shall we indeed be returned to (our) former state?",
        "transliteration": "Yaqūlūna a-innā lamardūdūna fī al-ḥāfirah",
    },
    {
        "verse_number": "11",
        "arabic_text": "ءِاُِذَا كُنَّا عِظَـامًا نَّخِرَةًۭ",
        "urdu_text": "کیا جب ہم بوسیدہ ہڈیاں بن جائیں گے تو واپس آئیں گے؟",
        "persian_text": "آیا وقتی که ما استخوان‌هایی پوسیده شده باشیم (بازگردانده می‌شویم؟)",
        "english_text": "When we have become decayed bones?",
        "transliteration": "A-idhā kunnā ‘iẓāman nakhirah",
    },
    {
        "verse_number": "12",
        "arabic_text": "قَالُوا۟ تِلْكَ إِذًا كَرَّةٌ خَاسِرَةٌۭ",
        "urdu_text": "کہتے ہیں: یہ تو پھر نقصان کا لوٹایا جانا ہوگا",
        "persian_text": "می‌گویند: در این صورت این بازگشت، بازگشتی زیان‌بار خواهد بود",
        "english_text": "They say, 'Then that would be a losing return!'",
        "transliteration": "Qālū tilka idhan karratun khāsirah",
    },
    {
        "verse_number": "13",
        "arabic_text": "فَاِنَّمَا هِىَ زَجْرَةٌ وَاحِدَةٌۭ",
        "urdu_text": "تو وہ صرف ایک زوردار آواز ہوگی",
        "persian_text": "در حقیقت فقط یک صیحه (بانگ آسمانی) خواهد بود",
        "english_text": "But it will be only one shout,",
        "transliteration": "Fa-innamā hiya zajratun wāḥidah",
    },
    {
        "verse_number": "14",
        "arabic_text": "فَاِذَا هُم بِٱلسَّاهِرَةِ",
        "urdu_text": "جس کے بعد سب میدان حشر میں نظر آیینگے",
        "persian_text": "پس ناگهان آن‌ها در فضای باز (زمین زنده) خواهند بود",
        "english_text": "When behold, they will be on the surface (of the earth).",
        "transliteration": "Fa-idhā hum bissāhirah",
    },
    {
        "verse_number": "15",
        "arabic_text": "هَلْ أَتٰكَ حَدِيثُ مُوسىٰٓ",
        "urdu_text": "کیا تمہارے پاس موسیٰ کی خبر پہنچی؟",
        "persian_text": "آیا خبر موسیٰ به تو رسیده است؟",
        "english_text": "Has the story of Moses reached you?",
        "transliteration": "Hal atāka ḥadīthu Mūsā",
    },
    {
        "verse_number": "16",
        "arabic_text": "إِذْ نَادٰهُ رَبُّهُۥ بِٱلْوَادِ ٱلْمُقَدَّسِ طُوًى",
        "urdu_text": "جب اس کے رب نے اسے پاک وادی طویٰ میں پکارا",
        "persian_text": "هنگامی که پروردگارش او را در وادی مقدس طوی ندا داد",
        "english_text": "When his Lord called to him in the sacred valley of Tuwa:",
        "transliteration": "Idh nādāhu rabbuhu bil-wādi al-muqaddasi ṭuwā",
    },
    {
        "verse_number": "17",
        "arabic_text": "ٱذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُۥ طَغىٰ",
        "urdu_text": " فرعون کے پاس جا، بے شک وہ سرکشی ہو گیا ہے  ہے",
        "persian_text": "برو به سوی فرعون، زیرا که او طغیان کرده است",
        "english_text": "Go to Pharaoh. Indeed, he has transgressed.",
        "transliteration": "Idhhab ilā fir‘awna innahu ṭaghā",
    },
    {
        "verse_number": "18",
        "arabic_text": "فَقُلْ هَل لَّكَ اِلَىٰٓ اَن تَزَكّىٰ",
        "urdu_text": "کہو کیا یہ ممکن ہے تو پاکیزہ کردار ہو جاؤ",
        "persian_text": "پس بگو: آیا میل داری که پاک شوی؟",
        "english_text": "And say, 'Would you be willing to purify yourself",
        "transliteration": "Faqul hal laka ilā an tazakkā",
    },
    {
        "verse_number": "19",
        "arabic_text": "وَاَهْدِيَكَ اِلٰى رَبِّكَ فَتَخْشىٰ",
        "urdu_text": "اور میں تجھے تیرے رب کی طرف رہنمائی کروں تاکہ تو ڈر جائے؟",
        "persian_text": "و تو را به سوی پروردگارت هدایت کنم تا بترسی؟",
        "english_text": "And let me guide you to your Lord so you would fear [Him]?'",
        "transliteration": "Wa ahdiyaka ilā rabbika fatakhshā",
    },
    {
        "verse_number": "20",
        "arabic_text": "فَاَرٰهُ ٱلْاٰيَةَ ٱلْكُبْرىٰ",
        "urdu_text": "پھر اُس نے اسے بڑی نشانی دکھائی",
        "persian_text": "پس (موسیٰ) بزرگ‌ترین نشانه را به او نشان داد",
        "english_text": "And he showed him the greatest sign.",
        "transliteration": "Fa-arāhu al-āyata al-kubrā",
    },
    {
        "verse_number": "21",
        "arabic_text": "فَكَذَّبَ وَعَصىٰ",
        "urdu_text": "پس اس نے جھٹلایا اور نافرمانی کی",
        "persian_text": "اما او تکذیب کرد و نافرمانی نمود",
        "english_text": "But [Pharaoh] denied and disobeyed.",
        "transliteration": "Fakadhdhaba wa ‘aṣā",
    },
    {
        "verse_number": "22",
        "arabic_text": "ثُمَّ أَدْبَرَ يَسْعىٰ",
        "urdu_text": "پھر پیٹھ موڑ کر دوڑنے لگا",
        "persian_text": "سپس پشت کرد و کوشید (برای مخالفت)",
        "english_text": "Then he turned back, striving.",
        "transliteration": "Thumma adbara yas‘ā",
    },
    {
        "verse_number": "23",
        "arabic_text": "فَحَشَرَ فَنَادىٰ",
        "urdu_text": "پھر اس نے لوگوں کو جمع کیا اور پکارا",
        "persian_text": "آنگاه مردم را گرد آورد و ندا داد",
        "english_text": "And he gathered [his people] and called out",
        "transliteration": "Faḥashara fanādā",
    },
    {
        "verse_number": "24",
        "arabic_text": "فَقَالَ اَنَا رَبُّكُمُ ٱلْأَعْلىٰ",
        "urdu_text": "اور کہا: میں ہی تمہارا سب سے بڑا رب ہوں",
        "persian_text": "و گفت: من پروردگار برتر شما هستم",
        "english_text": "And said, 'I am your most exalted lord.'",
        "transliteration": "Faqāla anā rabbukumul-a‘lā",
    },
    {
        "verse_number": "25",
        "arabic_text": "فَاَخَذَهُ ٱللَّهُ نَكَالَ ٱلْاٰخِرَةِ وَٱلْأُولىٰٓ",
        "urdu_text": "تو اللہ نے اسے آخرت اور دنیا دونوں کی سزا میں پکڑ لیا",
        "persian_text": "پس خداوند او را به عذاب آخرت و دنیا گرفت",
        "english_text": "So Allah seized him for punishment in the Hereafter and the first [life].",
        "transliteration": "Fa-akhadhahu Allāhu nakāla al-ākhirati wal-ūlā",
    },
    {
        "verse_number": "26",
        "arabic_text": "اِنَّ فِى ذٰلِكَ لَعِبْرَةً لِِّمَن يَّخْشىٰ",
        "urdu_text": "یقیناً اس میں عبرت ہے اس کے لیے جو ڈرتا ہے",
        "persian_text": "در این ماجرا عبرتی است برای کسی که می‌ترسد",
        "english_text": "Indeed in that is a lesson for whoever would fear [Allah].",
        "transliteration": "Inna fī dhālika la‘ibratan liman yakhshā",
    },
    {
        "verse_number": "27",
        "arabic_text": "ءَاَنتُمْ اَشَدُّ خَلْقًا أَمِ ٱلسَّمَآءُۚ بَنٰهَا",
        "urdu_text": "کیا تمہارا بنانا زیادہ سخت ہے یا آسمان کا؟ اسی نے اسے بنایا",
        "persian_text": "آیا آفرینش شما سخت‌تر است یا آسمان؟ او آن را بنا کرد",
        "english_text": "Are you a more difficult creation or is the heaven? He constructed it.",
        "transliteration": "A-antum ashaddu khalqan amis-samā’u banāhā",
    },
    {
        "verse_number": "28",
        "arabic_text": "رَفَعَ سَمْكَهَا فَسَوّٰهَا",
        "urdu_text": "اس نے اسکی چھت کو بلند کیا اور پھر برابر کر دیا",
        "persian_text": "سقف آن را بالا برد و آن را نظم داد",
        "english_text": "He raised its ceiling and proportioned it.",
        "transliteration": "Rafa‘a samkahā fasawwāhā",
    },
    {
        "verse_number": "29",
        "arabic_text": "وَاَغْطَشَ لَيْلَهَا وَأَخْرَجَ ضُحٰهَا",
        "urdu_text": "اور اس کی رات کو تاریک بنایا اور اس کا دن نکالا",
        "persian_text": "شب آن را تیره و تار کرد و روز آن را آشکار ساخت",
        "english_text": "And He darkened its night and extracted its brightness.",
        "transliteration": "Wa aghṭasha laylahā wa akhraja ḍuḥāhā",
    },
    {
        "verse_number": "30",
        "arabic_text": "وَاَلْاَرْضَ بَعْدَ ذَٰلِكَ دَحٰهَآ",
        "urdu_text": "اور زمین کو اس کے بعد پھیلایا",
        "persian_text": "و زمین را بعد از آن گسترش داد",
        "english_text": "And after that He spread the earth.",
        "transliteration": "Wal-arḍa ba‘da dhālika daḥāhā",
    },
    {
        "verse_number": "31",
        "arabic_text": "اَخْرَجَ مِنْهَا مَآءَهَا وَمَرْعٰهَا",
        "urdu_text": "اس نے اس سے اس کا پانی اور چارہ نکالا",
        "persian_text": "از آن، آبش و چراگاهش را بیرون آورد",
        "english_text": "He brought forth from it its water and its pasture.",
        "transliteration": "Akhraja minhā mā’ahā wa mar‘āhā",
    },
    {
        "verse_number": "32",
        "arabic_text": "وَ اَلْجِبَالَ اَرْسٰهَا",
        "urdu_text": "اور پہاڑوں کو اس میں جما دیا",
        "persian_text": "و کوه‌ها را در آن پابرجا ساخت",
        "english_text": "And the mountains He firmly fixed.",
        "transliteration": "Wal-jibāla arsāhā",
    },
    {
        "verse_number": "33",
        "arabic_text": "مَتاعًا لَّكُمْ وَلِانْعامِكُمْ",
        "urdu_text": "یہ سب تمہارے اور تمہارے جانوروں کے فائدے کے لیے",
        "persian_text": "برای بهره‌برداری شما و دام‌هایتان",
        "english_text": "[As] provision for you and your grazing livestock.",
        "transliteration": "Matā‘an lakum wa li-an‘āmakum",
    },
    {
        "verse_number": "34",
        "arabic_text": "فَاِذَا جَآءَتِ اَلطَّآمَّةُ اَلْكُبْرىٰ",
        "urdu_text": "پھر جب وہ سب سے بڑی آفت آ جائے گی",
        "persian_text": "پس زمانی که آن فاجعه بزرگ فرا رسد",
        "english_text": "But when there comes the greatest overwhelming calamity –",
        "transliteration": "Fa-idhā jā’ati al-ṭāmmatu al-kubrā",
    },
    {
        "verse_number": "35",
        "arabic_text": "يَوْمَ يَتَذَكَّرُ الْاِنسَانُ مَا سَعٰى",
        "urdu_text": "اس دن انسان کو یاد آئے گا جو کچھ اُس نے کیا",
        "persian_text": "روزی که انسان به یاد می‌آورد آنچه را که کرده است",
        "english_text": "The Day when man will remember that for which he strove,",
        "transliteration": "Yawma yatadhakkaru al-insānu mā sa‘ā",
    },
    {
        "verse_number": "36",
        "arabic_text": "وَبُرِّزَتِ الْجَحِيمُ لِمَن يَّرٰى",
        "urdu_text": "اور جہنم ہر دیکھنے والے کے سامنے لائی جائے گی",
        "persian_text": "و دوزخ برای کسی که می‌بیند آشکار می‌گردد",
        "english_text": "And Hellfire will be exposed for [all] who see –",
        "transliteration": "Wa burrizat al-jaḥīmu liman yarā",
    },
    {
        "verse_number": "37",
        "arabic_text": "فَاَمَّا مَن طَغٰى",
        "urdu_text": "تو وہ شخص جس نے سرکشی کی",
        "persian_text": "پس کسی که طغیان کرده است",
        "english_text": "So as for he who transgressed",
        "transliteration": "Fa-ammā man ṭaghā",
    },
    {
        "verse_number": "38",
        "arabic_text": "وَاٰثَرَ ٱلْحَيٰوةَ الدُّنْيَا",
        "urdu_text": "اور دنیا کی زندگی کو ترجیح دی",
        "persian_text": "و زندگی دنیا را ترجیح داد",
        "english_text": "And preferred the life of the world,",
        "transliteration": "Wa āthara al-ḥayāta al-dunyā",
    },
    {
        "verse_number": "39",
        "arabic_text": "فَاِنَّ ٱلْجَحِيمَ هِىَ ٱلْمَأْوٰى",
        "urdu_text": "تو یقیناً جہنم ہی اس کا ٹھکانا ہے",
        "persian_text": "پس یقیناً دوزخ جایگاه او خواهد بود",
        "english_text": "Then indeed, Hellfire will be [his] refuge.",
        "transliteration": "Fa-inna al-jaḥīma hiya al-ma’wā",
    },
    {
        "verse_number": "40",
        "arabic_text": "وَاَمَّا مَنْ خَافَ مَقَامَ رَبِّهِۦ وَنَهَى اَلنَّفْسَ عَنِ ٱلْهَوٰى",
        "urdu_text": "اور وہ شخص جو اپنے رب کے سامنے کھڑے ہونے سے ڈرا اور نفس کو خواہش سے روکا",
        "persian_text": "و اما کسی که از ایستادن در برابر پروردگارش ترسید و نفس خود را از هوس بازداشت",
        "english_text": "But as for he who feared the standing before his Lord and restrained the soul from [its] desire,",
        "transliteration": "Wa ammā man khāfa maqāma rabbihi wa nahā al-nafsa ‘ani al-hawā",
    },
    {
        "verse_number": "41",
        "arabic_text": "فَاِنَّ الْجَنَّةَ هِىَ ٱلْمَأْوٰى",
        "urdu_text": "تو یقیناً جنت ہی اس کا ٹھکانا ہے",
        "persian_text": "پس یقیناً بهشت جایگاه او خواهد بود",
        "english_text": "Then indeed, Paradise will be [his] refuge.",
        "transliteration": "Fa-inna al-jannata hiya al-ma’wā",
    },
    {
        "verse_number": "42",
        "arabic_text": "يَسْـَٔلُونَكَ عَنِ ٱلسَّاعَةِ اَيَّانَ مُرْسٰهَا",
        "urdu_text": "وہ تم سے قیامت کے بارے میں پوچھتے ہیں، کہ وہ کب قائم ہوگی؟",
        "persian_text": "از تو درباره ساعت (قیامت) می‌پرسند که کی فرا خواهد رسید؟",
        "english_text": "They ask you, [O Muhammad], about the Hour: when is its arrival?",
        "transliteration": "Yas’alūnaka ‘ani al-sā‘ati ayyāna mursāhā",
    },
    {
        "verse_number": "43",
        "arabic_text": "فِيمَ أَنتَ مِن ذِكْرٰهَآ",
        "urdu_text": "تمہیں اس کا ذکر کرنے سے کیا واسطہ؟",
        "persian_text": "تو را چه کار که از آن یاد کنی؟",
        "english_text": "In what [position] are you that you should mention it?",
        "transliteration": "Fīma anta min dhik’rāhā",
    },
    {
        "verse_number": "44",
        "arabic_text": "اِلٰى رَبِّكَ مُنتَهٰهَا",
        "urdu_text": "اس کا علم تو تیرے رب ہی کے پاس ہے",
        "persian_text": "پایان آن تنها نزد پروردگار تو است",
        "english_text": "To your Lord is its finality.",
        "transliteration": "Ilā rabbika muntahāhā",
    },
    {
        "verse_number": "45",
        "arabic_text": "اِنَّمَآ اَنْتَ مُنذِرُ مَنْ يَخْشٰهَا",
        "urdu_text": "تم تو صرف اسے ڈرانے والے ہو جو اس سے ڈرے",
        "persian_text": "تو فقط هشدار دهنده‌ای برای کسی که از آن می‌ترسد",
        "english_text": "You are only a warner for those who fear it.",
        "transliteration": "Innamā anta mundhiru man yakhshāhā",
    },
    {
        "verse_number": "46",
        "arabic_text": "كَاَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوٓا اِلَّا عَشِيَّةً اَوْ ضُحٰهَا",
        "urdu_text": "جیسے وہ جس دن اسے دیکھیں گے، ایسا لگے گا کہ وہ صرف ایک شام یا اس کی صبح رہے تھے",
        "persian_text": "روزی که آن را ببینند، گویی جز یک شامگاه یا بامداد آن در دنیا نمانده‌اند",
        "english_text": "It will be, on the Day they see it, as though they had not remained [in the world] except for an afternoon or a morning thereof.",
        "transliteration": "Ka-annahum yawma yarawnahā lam yalbathū illā ‘ashiyyatan aw ḍuḥāhā",
    },
]
