ayats = [
    {
        "verse_number": "1",
        "arabic_text": "ٱلْقَارِعَةُ",
        "urdu_text": "کھڑکھڑانے والی (قیامت)",
        "persian_text": "کوبنده (روز قیامت)",
        "english_text": "The Striking Calamity!",
        "transliteration": "Al-Qāriʿah",
    },
    {
        "verse_number": "2",
        "arabic_text": "مَا ٱلْقَارِعَةُ",
        "urdu_text": "کیا ہے کھڑکھڑانے والی؟",
        "persian_text": "کوبنده چیست؟",
        "english_text": "What is the Striking Calamity?",
        "transliteration": "Mā al-Qāriʿah",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَمَآ أَدْرَىٰكَ مَا ٱلْقَارِعَةُ",
        "urdu_text": "اور تمہیں کیا معلوم کہ کھڑکھڑانے والی کیا ہے؟",
        "persian_text": "و تو چه می‌دانی که کوبنده چیست؟",
        "english_text": "And what can make you know what the Striking Calamity is?",
        "transliteration": "Wa mā adrāka mā al-Qāriʿah",
    },
    {
        "verse_number": "4",
        "arabic_text": "يَوْمَ يَكُونُ ٱلنَّاسُ كَٱلْفَرَاشِ ٱلْمَبْثُوثِ",
        "urdu_text": "جس دن لوگ بکھرے ہوئے پروانوں کی طرح ہوں گے",
        "persian_text": "روزی که مردم مانند پروانه‌های پراکنده خواهند بود",
        "english_text": "It is the Day when people will be like scattered moths.",
        "transliteration": "Yawma yakūnu al-nāsu ka-al-farāshi al-mabthūth",
    },
    {
        "verse_number": "5",
        "arabic_text": "وَتَكُونُ ٱلْجِبَالُ كَٱلْعِهْنِ ٱلْمَنفُوشِ",
        "urdu_text": "اور پہاڑ دھنکی ہوئی اون کی طرح ہوں گے",
        "persian_text": "و کوه‌ها مانند پشم حلاجی‌شده خواهند شد",
        "english_text": "And the mountains will be like fluffed wool.",
        "transliteration": "Wa takūnu al-jibālu ka-al-ʿihni al-manfūsh",
    },
    {
        "verse_number": "6",
        "arabic_text": "فَأَمَّا مَن ثَقُلَتْ مَوَٰزِينُهُۥ",
        "urdu_text": "پھر جس کا پلڑا بھاری ہوا",
        "persian_text": "پس هر که ترازوی اعمالش سنگین باشد",
        "english_text": "Then as for one whose scales are heavy [with good deeds],",
        "transliteration": "Fa-ammā man thaqulat mawāzīnuh",
    },
    {
        "verse_number": "7",
        "arabic_text": "فَهُوَ فِى عِيشَةٍۢ رَّاضِيَةٍۢ",
        "urdu_text": "تو وہ خوشحال زندگی میں ہوگا",
        "persian_text": "او در زندگی پسندیده‌ای خواهد بود",
        "english_text": "He will be in a pleasant life.",
        "transliteration": "Fahuwa fī ʿīshatin rāḍiyah",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَأَمَّا مَنْ خَفَّتْ مَوَٰزِينُهُۥ",
        "urdu_text": "اور جس کا پلڑا ہلکا ہوا",
        "persian_text": "و اما کسی که ترازویش سبک باشد",
        "english_text": "But as for one whose scales are light,",
        "transliteration": "Wa ammā man khaffat mawāzīnuh",
    },
    {
        "verse_number": "9",
        "arabic_text": "فَأُمُّهُۥ هَاوِيَةٌۭ",
        "urdu_text": "تو اس کا ٹھکانہ گہرا گڑھا ہے",
        "persian_text": "پس جایگاه او هاویه (دوزخ) است",
        "english_text": "His refuge will be an abyss.",
        "transliteration": "Fa-ummuhu hawiyah",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَمَآ أَدْرَىٰكَ مَا هِيَهْ",
        "urdu_text": "اور تمہیں کیا معلوم وہ کیا ہے؟",
        "persian_text": "و تو چه می‌دانی که آن چیست؟",
        "english_text": "And what can make you know what that is?",
        "transliteration": "Wa mā adrāka mā hiyah",
    },
    {
        "verse_number": "11",
        "arabic_text": "نَارٌ حَامِيَةٌۢ",
        "urdu_text": "وہ دہکتی ہوئی آگ ہے",
        "persian_text": "آن آتشی سوزان است",
        "english_text": "It is a blazing Fire.",
        "transliteration": "Nārun ḥāmiyah",
    },
]
