ayats = [
    {
        "arabic_text": "الرَّحْمَٰنُ",
        "urdu_text": "نہایت رحم والا",
        "persian_text": "بسیار مهربان",
        "english_text": "The Most Merciful",
        "transliteration": "Ar-Rahman",
        "verse_number": "55:1",
    },
    {
        "arabic_text": "عَلَّمَ الْقُرْآنَ",
        "urdu_text": "جس نے قرآن سکھایا",
        "persian_text": "قرآن را آموخت",
        "english_text": "Taught the Qur'an",
        "transliteration": "Allama al-Qur'an",
        "verse_number": "55:2",
    },
    {
        "arabic_text": "خَلَقَ الْإِنسَانَ",
        "urdu_text": "انسان کو پیدا کیا",
        "persian_text": "انسان را آفرید",
        "english_text": "Created man",
        "transliteration": "Khalaqa al-insan",
        "verse_number": "55:3",
    },
    {
        "arabic_text": "عَلَّمَهُ الْبَيَانَ",
        "urdu_text": "اسے بولنا سکھایا",
        "persian_text": "به او بیان آموخت",
        "english_text": "Taught him speech",
        "transliteration": "Allamahu al-bayan",
        "verse_number": "55:4",
    },
    {
        "arabic_text": "الشَّمْسُ وَالْقَمَرُ بِحُسْبَانٍ",
        "urdu_text": "سورج اور چاند ایک حساب سے چل رہے ہیں",
        "persian_text": "خورشید و ماه با حسابی دقیق",
        "english_text": "The sun and the moon [move] by precise calculation",
        "transliteration": "Ash-shamsu wal-qamaru bihusbaan",
        "verse_number": "55:5",
    },
    {
        "arabic_text": "وَالنَّجْمُ وَالشَّجَرُ يَسْجُدَانِ",
        "urdu_text": "اور درخت اور گھاس سجدہ کرتے ہیں",
        "persian_text": "ستارگان و درختان سجده می‌کنند",
        "english_text": "And the stars and trees prostrate",
        "transliteration": "Wa an-najmu wash-shajaru yasjudaan",
        "verse_number": "55:6",
    },
    {
        "arabic_text": "وَالسَّمَاءَ رَفَعَهَا وَوَضَعَ الْمِيزَانَ",
        "urdu_text": "اور آسمان کو بلند کیا اور ترازو رکھا",
        "persian_text": "آسمان را برافراشت و میزان را نهاد",
        "english_text": "And the heaven He raised and imposed the balance",
        "transliteration": "Was-samaa’a rafa’aha wa wada’a al-meezaan",
        "verse_number": "55:7",
    },
    {
        "arabic_text": "أَلَّا تَطْغَوْا فِي الْمِيزَانِ",
        "urdu_text": "تاکہ تم تولنے میں زیادتی نہ کرو",
        "persian_text": "تا در میزان زیاده‌روی نکنید",
        "english_text": "That you not transgress within the balance",
        "transliteration": "Alla tatghaw fil meezaan",
        "verse_number": "55:8",
    },
    {
        "arabic_text": "وَأَقِيمُوا الْوَزْنَ بِالْقِسْطِ وَلَا تُخْسِرُوا الْمِيزَانَ",
        "urdu_text": "اور انصاف کے ساتھ تول کو قائم رکھو، اور ترازو میں کمی نہ کرو",
        "persian_text": "وزن را با عدالت برپا دارید و در میزان کم نگذارید",
        "english_text": "And establish weight in justice and do not make deficient the balance",
        "transliteration": "Wa aqeemul wazna bilqist wa laa tukhsirul meezaan",
        "verse_number": "55:9",
    },
    {
        "verse_number": 10,
        "arabic_text": "وَٱلۡأَرۡضَ وَضَعَهَا لِلۡأَنَامِ",
        "urdu_text": "اور زمین کو اس نے مخلوق کے لیے بنایا",
        "persian_translation": "و زمین را برای آفریدگان گسترد",
        "english_translation": "And the earth He laid [out] for the creatures.",
        "transliteration": "Wal-arda wada'aha lil-anam",
    },
    {
        "verse_number": 11,
        "arabic_text": "فِيهَا فَٰكِهَةٞ وَٱلنَّخۡلُ ذَاتُ ٱلۡأَكۡمَامِ",
        "urdu_text": "اس میں میوے ہیں اور کھجور کے درخت ہیں جن کے خوشے غلافوں میں ہیں",
        "persian_translation": "در آن میوه‌ها و درخت خرما با خوشه‌های پیچیده وجود دارد",
        "english_translation": "Therein is fruit and palm trees having sheaths [of dates].",
        "transliteration": "Fīhā fākihatun wannakhlu dhātu al-akmām",
    },
    {
        "verse_number": 12,
        "arabic_text": "وَٱلۡحَبُّ ذُو ٱلۡعَصۡفِ وَٱلرَّيۡحَانُ",
        "urdu_text": "اور غلہ جس میں بھوسا ہوتا ہے اور خوشبودار پودے ہیں",
        "persian_translation": "و دانه‌هایی با کاه و گیاهان خوشبو",
        "english_translation": "And grain having husks and scented plants.",
        "transliteration": "Wal-ḥabbu dhū al-‘asfi war-rayḥān",
    },
    {
        "verse_number": 13,
        "arabic_text": "فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_translation": "پس کدامین نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_translation": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi-ayyi ālā’i rabbikumā tukadhdhibān",
    },
    {
        "verse_number": 14,
        "arabic_text": "خَلَقَ ٱلۡإِنسَٰنَ مِن صَلۡصَٰلٖ كَٱلۡفَخَّارِ",
        "urdu_text": "اس نے انسان کو ٹھیکری جیسے کھنکھناتے گارے سے پیدا کیا",
        "persian_translation": "او انسان را از گِلی خشک و چون سفال آفرید",
        "english_translation": "He created man from clay like [that of] pottery.",
        "transliteration": "Khalaqal-insāna min ṣalṣālin ka-al-fakhkhār",
    },
    {
        "verse_number": 15,
        "arabic_text": "وَخَلَقَ ٱلۡجَانَّ مِن مَّارِجٖ مِّن نَّارٖ",
        "urdu_text": "اور جنوں کو آگ کی لپٹ سے پیدا کیا",
        "persian_translation": "و جن را از شعله‌ای از آتش آفرید",
        "english_translation": "And He created the jinn from a smokeless flame of fire.",
        "transliteration": "Wakhalaqal-jānn min mārijim min nār",
    },
    {
        "verse_number": 16,
        "arabic_text": "فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_translation": "پس کدامین نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_translation": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi-ayyi ālā’i rabbikumā tukadhdhibān",
    },
    {
        "verse_number": 17,
        "arabic_text": "رَبُّ ٱلۡمَشۡرِقَيۡنِ وَرَبُّ ٱلۡمَغۡرِبَيۡنِ",
        "urdu_text": "وہ دونوں مشرقوں اور دونوں مغربوں کا رب ہے",
        "persian_translation": "پروردگار دو مشرق و دو مغرب است",
        "english_translation": "He is Lord of the two Easts and Lord of the two Wests.",
        "transliteration": "Rabbu al-mashriqayni wa rabbu al-maghribayn",
    },
    {
        "verse_number": 18,
        "arabic_text": "فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_translation": "پس کدامین نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_translation": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi-ayyi ālā’i rabbikumā tukadhdhibān",
    },
    {
        "verse_number": 19,
        "arabic_text": "مَرَجَ ٱلۡبَحۡرَيۡنِ يَلۡتَقِيَانِ",
        "urdu_text": "اس نے دو سمندروں کو ملا دیا جو باہم ملتے ہیں",
        "persian_translation": "او دو دریا را روان ساخت که به هم می‌پیوندند",
        "english_translation": "He released the two seas, meeting [side by side].",
        "transliteration": "Maraja al-baḥrayni yaltaqiyān",
    },
    {
        "verse_number": 20,
        "arabic_text": "بَيۡنَهُمَا بَرۡزَخٞ لَّا يَبۡغِيَانِ",
        "urdu_text": "ان کے درمیان ایک آڑ ہے، جو حد سے نہیں بڑھتے",
        "persian_translation": "میان آن دو مانعی است که از مرز نمی‌گذرند",
        "english_translation": "Between them is a barrier [so] neither of them transgresses.",
        "transliteration": "Baynahumā barzakhun lā yabghiyān",
    },
    {
        "arabic_text": "يَخْرُجُ مِنْهُمَا ٱللُّؤْلُؤُ وَٱلْمَرْجَانُ",
        "urdu_text": "ان دونوں سے موتی اور مونگے نکلتے ہیں",
        "persian_text": "از آن دو، مروارید و مرجان بیرون می‌آید",
        "english_text": "From both of them emerge pearls and coral.",
        "transliteration": "Yakhruju minhumā al-lu’lu’u wal-marjān",
        "verse_number": 22,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدامیک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 23,
    },
    {
        "arabic_text": "وَلَهُ ٱلْجَوَارِ ٱلْمُنشَـَٔاتُ فِى ٱلْبَحْرِ كَٱلْأَعْلَـٰمِ",
        "urdu_text": "اور اسی کے لیے ہیں وہ کشتیاں جو سمندر میں پہاڑوں کی طرح بلند ہوتی ہیں",
        "persian_text": "و کشتی‌های بزرگ در دریا چون کوه‌ها به فرمان او روان‌اند",
        "english_text": "And His are the ships elevated in the sea like mountains.",
        "transliteration": "Wa lahu al-jawāri al-munsha’ātu fī al-baḥri kal-aʿlām",
        "verse_number": 24,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدامیک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 25,
    },
    {
        "arabic_text": "كُلُّ مَنْ عَلَيْهَا فَانٍۢ",
        "urdu_text": "زمین پر جو بھی ہے فنا ہو جانے والا ہے",
        "persian_text": "هر که بر روی آن است فانی است",
        "english_text": "Everyone upon it [the earth] will perish.",
        "transliteration": "Kullu man ʿalayhā fān",
        "verse_number": 26,
    },
    {
        "arabic_text": "وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو ٱلْجَلَـٰلِ وَٱلْإِكْرَامِ",
        "urdu_text": "اور تمہارے رب کی ذات جو عظمت اور عزت والی ہے باقی رہے گی",
        "persian_text": "و تنها ذات پروردگارت که صاحب جلال و بزرگی است باقی می‌ماند",
        "english_text": "And the Face of your Lord full of Majesty and Honor will remain.",
        "transliteration": "Wa yabqā wajhu rabbika dhū al-jalāli wal-ikrām",
        "verse_number": 27,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 28,
    },
    {
        "arabic_text": "يَسْـَٔلُهُۥ مَن فِى ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ ۚ كُلَّ يَوْمٍ هُوَ فِى شَأْنٍۭ",
        "urdu_text": "اسی سے سوال کرتے ہیں وہ سب جو آسمانوں اور زمین میں ہیں، ہر روز وہ ایک شان میں ہوتا ہے",
        "persian_text": "هر که در آسمان‌ها و زمین است از او درخواست می‌کند؛ هر روز او در کاری است",
        "english_text": "Everyone in the heavens and earth asks Him; every day He is bringing about a matter.",
        "transliteration": "Yas’aluhu man fī as-samāwāti wal-arḍi, kulla yawmin huwa fī sha’n",
        "verse_number": 29,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 30,
    },
    {
        "arabic_text": "سَنَفْرُغُ لَكُمْ أَيُّهَ ٱلثَّقَلَانِ",
        "urdu_text": "اے بوجھ والو! ہم تمہارے حساب کے لیے فارغ ہو جائیں گے",
        "persian_text": "ای گروه جن و انس، به زودی به حساب شما خواهیم پرداخت",
        "english_text": "We will attend to you, O prominent beings.",
        "transliteration": "Sanafrughu lakum ayyuhā ath-thaqalān",
        "verse_number": 31,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 32,
    },
    {
        "arabic_text": "يَـٰمَعْشَرَ ٱلْجِنِّ وَٱلْإِنسِ إِنِ ٱسْتَطَعْتُمْ أَن تَنفُذُوا۟ مِنْ أَقْطَارِ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ فَٱنفُذُوا۟ ۚ لَا تَنفُذُونَ إِلَّا بِسُلْطَـٰنٍۢ",
        "urdu_text": "اے جنوں اور انسانوں کی جماعت! اگر تم آسمانوں اور زمین کے کناروں سے نکل سکتے ہو تو نکل جاؤ، تم طاقت کے بغیر نہیں نکل سکتے",
        "persian_text": "ای گروه جن و انس! اگر می‌توانید از مرزهای آسمان‌ها و زمین بگریزید، بگریزید، اما جز با قدرت، نمی‌گریزید",
        "english_text": "O company of jinn and mankind, if you are able to pass beyond the regions of the heavens and the earth, then pass. You will not pass except by authority.",
        "transliteration": "Yā maʿshara al-jinni wal-insi inis-taṭaʿtum an tanfudhū min aqṭāri as-samāwāti wal-arḍi fanfudhū, lā tanfudhūna illā bisulṭān",
        "verse_number": 33,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 34,
    },
    {
        "arabic_text": "يُرْسَلُ عَلَيْكُمَا شُوَاظٌۭ مِّن نَّارٍۢ وَنُحَاسٌۭ فَلَا تَنتَصِرَانِ",
        "urdu_text": "تم پر آگ کا شعلہ اور دھواں چھوڑا جائے گا، پھر تم بچ نہ سکو گے",
        "persian_text": "بر شما شعله‌ای از آتش و دود مسلط خواهد شد و نمی‌توانید یاری بجویید",
        "english_text": "There will be sent upon you a flame of fire and smoke, and you will not defend yourselves.",
        "transliteration": "Yursalu ʿalaykumā shuwāẓun min nārin wa nuḥāsun falā tantaṣirān",
        "verse_number": 35,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 36,
    },
    {
        "arabic_text": "فَإِذَا ٱنشَقَّتِ ٱلسَّمَآءُ فَكَانَتْ وَرْدَةًۭ كَٱلدِّهَانِ",
        "urdu_text": "پھر جب آسمان پھٹ جائے گا تو وہ گلابی ہو جائے گا جیسے تیل کی تلچھٹ",
        "persian_text": "پس آنگاه که آسمان شکافته شود و چون گل سرخ و روغن گداخته گردد",
        "english_text": "And when the heaven is split open and becomes rose-colored like oil.",
        "transliteration": "Fa idhā inshaqqati as-samā’u fakānat wardatan kaddihān",
        "verse_number": 37,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 38,
    },
    {
        "arabic_text": "فَيَوْمَئِذٍۢ لَّا يُسْـَٔلُ عَن ذَنبِهِۦٓ إِنسٌۭ وَلَا جَآنٌّۭ",
        "urdu_text": "پھر اس دن نہ انسان سے اور نہ جن سے ان کے گناہوں کے بارے میں سوال کیا جائے گا",
        "persian_text": "پس در آن روز از گناه هیچ انسانی و هیچ جنی پرسش نخواهد شد",
        "english_text": "Then on that Day none will be asked about his sin among men or jinn.",
        "transliteration": "Fayawma’idhilā yus’alu ʿan dhanbihi insun wa lā jān",
        "verse_number": 39,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
        "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "So which of the favors of your Lord would you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 40,
    },
    {
        "arabic_text": "يُعْرَفُ ٱلْمُجْرِمُونَ بِسِيمَـٰهُمْ فَيُؤْخَذُ بِٱلنَّوَاصِى وَٱلْأَقْدَامِ",
        "urdu_text": "مجرم اپنے چہروں سے پہچانے جائیں گے، پھر پیشانیوں اور پاؤں سے پکڑا جائے گا",
        "persian_text": "گناهکاران از چهره‌شان شناخته می‌شوند و از پیشانی و پاها گرفته می‌شوند",
        "english_text": "The sinners will be known by their marks, and they will be seized by the forelocks and the feet.",
        "transliteration": "Yuʿrafu al-mujrimūna bisīmāhum fa yu’khadhu bin-nawāṣī wal-aqdām",
        "verse_number": 41,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 42,
    },
    {
        "arabic_text": "هَـٰذِهِۦ جَهَنَّمُ ٱلَّتِى يُكَذِّبُ بِهَا ٱلْمُجْرِمُونَ",
        "urdu_text": "یہی ہے جہنم جسے مجرم جھٹلایا کرتے تھے",
        "persian_text": "این همان جهنمی است که گناهکاران آن را تکذیب می‌کردند",
        "english_text": "This is the Hell which the criminals denied.",
        "transliteration": "Hādhihi jahannamu allatī yukadhdhibu bihā al-mujrimūn",
        "verse_number": 43,
    },
    {
        "arabic_text": "يَطُوفُونَ بَيْنَهَا وَبَيْنَ حَمِيمٍ ءَانٍۢ",
        "urdu_text": "وہ اس کے درمیان اور کھولتے پانی کے درمیان چکر لگائیں گے",
        "persian_text": "میان آن و آب جوشان در رفت‌وآمد خواهند بود",
        "english_text": "They will go around between it and scalding water, heated to the utmost degree.",
        "transliteration": "Yaṭūfūna baynahā wa bayna ḥamīmin ān",
        "verse_number": 44,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 45,
    },
    {
        "arabic_text": "وَلِمَنْ خَافَ مَقَامَ رَبِّهِۦ جَنَّتَانِ",
        "urdu_text": "اور جو اپنے رب کے حضور کھڑے ہونے سے ڈرا، اس کے لیے دو جنتیں ہیں",
        "persian_text": "و برای کسی که از مقام پروردگارش ترسید، دو بهشت است",
        "english_text": "But for he who has feared the standing before his Lord are two gardens.",
        "transliteration": "Waliman khāfa maqāma rabbihi jannatān",
        "verse_number": 46,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 47,
    },
    {
        "arabic_text": "ذَوَاتَآ أَفْنَانٍۢ",
        "urdu_text": "جن کی شاخیں جھکی ہوئی ہوں گی",
        "persian_text": "دارای شاخه‌های بسیار",
        "english_text": "Having spreading branches.",
        "transliteration": "Dhāwātā afnān",
        "verse_number": 48,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 49,
    },
    {
        "arabic_text": "فِيهِمَا عَيْنَانِ تَجْرِيَانِ",
        "urdu_text": "ان دونوں میں دو چشمے بہہ رہے ہوں گے",
        "persian_text": "در آن دو، دو چشمه جاری است",
        "english_text": "In both of them are two flowing springs.",
        "transliteration": "Fīhimā ʿaynāni tajriyān",
        "verse_number": 50,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 51,
    },
    {
        "arabic_text": "فِيهِمَا مِن كُلِّ فَـٰكِهَةٍۢ زَوْجَانِ",
        "urdu_text": "ان میں ہر پھل کی دو قسمیں ہوں گی",
        "persian_text": "در آن دو، از هر میوه‌ای دو نوع است",
        "english_text": "In both of them are of every fruit two kinds.",
        "transliteration": "Fīhimā min kulli fākihatin zawjān",
        "verse_number": 52,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 53,
    },
    {
        "arabic_text": "مُتَّكِـِٔينَ عَلَىٰ فُرُشٍۢ بَطَآئِنُهَا مِنْ إِسْتَبْرَقٍۢ ۚ وَجَنَى ٱلْجَنَّتَيْنِ دَانٍۭ",
        "urdu_text": "وہ ٹیک لگائے ہوں گے مخملی کپڑے کے بستروں پر، اور دونوں جنتوں کے پھل قریب ہوں گے",
        "persian_text": "بر تخت‌هایی تکیه زده‌اند که آستری آن‌ها از دیباست، و میوه‌های دو بهشت در دسترس است",
        "english_text": "Reclining on beds whose linings are of silk brocade, and the fruit of the two gardens is hanging low.",
        "transliteration": "Muttaki’īna ʿalā furushin baṭā’inuhā min istabraq, wa janā al-jannatayni dān",
        "verse_number": 54,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 55,
    },
    {
        "arabic_text": "فِيهِنَّ قَـٰصِرَٰتُ ٱلطَّرْفِ لَمْ يَطْمِثْهُنَّ إِنسٌۭ قَبْلَهُمْ وَلَا جَآنٌّۭ",
        "urdu_text": "ان میں نیچی نظروں والی عورتیں ہوں گی، جنہیں ان سے پہلے کسی انسان یا جن نے نہ چھوا ہوگا",
        "persian_text": "در آن‌ها زنانی هستند که نگاه‌شان فروهشته است، که پیش از آن‌ها هیچ انسانی یا جنی به آن‌ها دست نزده است",
        "english_text": "In them are women limiting their glances, whom no man or jinn has touched before them.",
        "transliteration": "Fīhinna qāṣirātu aṭ-ṭarfi lam yaṭmith’hunna insun qab lahum walā jān",
        "verse_number": 56,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 57,
    },
    {
        "arabic_text": "كَأَنَّهُنَّ ٱلْيَاقُوتُ وَٱلْمَرْجَانُ",
        "urdu_text": "گویا وہ یاقوت اور مرجان کی مانند ہوں گی",
        "persian_text": "چنان‌اند که گویی یاقوت و مرجان‌اند",
        "english_text": "As if they were rubies and coral.",
        "transliteration": "Ka’annahunna al-yāqūtu wal-marjān",
        "verse_number": 58,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 59,
    },
    {
        "arabic_text": "هَلْ جَزَآءُ ٱلْإِحْسَـٰنِ إِلَّا ٱلْإِحْسَـٰنُ",
        "urdu_text": "نیکی کا بدلہ نیکی کے سوا اور کیا ہو سکتا ہے؟",
        "persian_text": "آیا پاداش نیکی چیزی جز نیکی است؟",
        "english_text": "Is the reward for good [anything] but good?",
        "transliteration": "Hal jazā’u al-iḥsāni illā al-iḥsān",
        "verse_number": 60,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 61,
    },
    {
        "arabic_text": "وَمِن دُونِهِمَا جَنَّتَانِ",
        "urdu_text": "اور ان دونوں کے علاوہ دو اور جنتیں ہوں گی",
        "persian_text": "و غیر از آن دو، دو بهشت دیگر است",
        "english_text": "And below them both are two other gardens.",
        "transliteration": "Wa min dūnihimā jannatān",
        "verse_number": 62,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 63,
    },
    {
        "arabic_text": "مُدْهَامَّتَانِ",
        "urdu_text": "وہ دونوں گہری سبز رنگ کی ہوں گی",
        "persian_text": "هر دو تیره و سرسبز خواهند بود",
        "english_text": "Dark green [in color].",
        "transliteration": "Mud’hāmmatān",
        "verse_number": 64,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 65,
    },
    {
        "arabic_text": "فِيهِمَا عَيْنَانِ نَضَّاخَتَانِ",
        "urdu_text": "ان میں دو چشمے پھوٹ رہے ہوں گے",
        "persian_text": "در آن‌ها دو چشمه جوشان است",
        "english_text": "In both of them are two springs, gushing forth.",
        "transliteration": "Fīhimā ʿaynāni naḍḍākhatān",
        "verse_number": 66,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 67,
    },
    {
        "arabic_text": "فِيهِمَا فَـٰكِهَةٌۭ وَنَخْلٌۭ وَرُمَّانٌۭ",
        "urdu_text": "ان میں پھل، کھجوریں اور انار ہوں گے",
        "persian_text": "در آن‌ها میوه‌ها، درختان خرما و انار است",
        "english_text": "In them are fruit and palm trees and pomegranates.",
        "transliteration": "Fīhimā fākihatun wa nakhlun wa rummān",
        "verse_number": 68,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 69,
    },
    {
        "arabic_text": "فِيهِنَّ خَيْرَٰتٌ حِسَانٌۭ",
        "urdu_text": "ان میں نیک سیرت خوبصورت بیبیاں ہوں گی",
        "persian_text": "در آن‌ها زنان نیکوخصال و زیبا هستند",
        "english_text": "In them are good and beautiful women.",
        "transliteration": "Fīhinna khayrātun ḥisān",
        "verse_number": 70,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 71,
    },
    {
        "arabic_text": "حُورٌۭ مَّقْصُورَٰتٌۭ فِى ٱلْخِيَامِ",
        "urdu_text": "حوریں ہوں گی جو خیموں میں رکھی گئی ہوں گی",
        "persian_text": "حورانی که در خیمه‌ها مستورند",
        "english_text": "Fair ones reserved in pavilions.",
        "transliteration": "Ḥūrun maqṣūrātun fī al-khiyām",
        "verse_number": 72,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 73,
    },
    {
        "arabic_text": "لَمْ يَطْمِثْهُنَّ إِنسٌۭ قَبْلَهُمْ وَلَا جَآنٌّۭ",
        "urdu_text": "انہیں ان سے پہلے نہ کسی انسان نے چھوا، نہ کسی جن نے",
        "persian_text": "که هیچ انسانی و جنی پیش از آنان آن‌ها را لمس نکرده است",
        "english_text": "Whom no man or jinn has touched before them.",
        "transliteration": "Lam yaṭmith’hunna insun qablahum walā jān",
        "verse_number": 74,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 75,
    },
    {
        "arabic_text": "مُتَّكِـِٔينَ عَلَىٰ رَفْرَفٍ خُضْرٍۢ وَعَبْقَرِىٍّ حِسَانٍۢ",
        "urdu_text": "وہ سبز قالینوں اور عمدہ فرشوں پر تکیہ لگائے ہوں گے",
        "persian_text": "بر بالش‌های سبز و فرش‌های نفیس تکیه زده‌اند",
        "english_text": "Reclining on green cushions and beautiful fine carpets.",
        "transliteration": "Muttaki’īna ʿalā rafrafin khuḍ’rin wa ʿabqariyyin ḥisān",
        "verse_number": 76,
    },
    {
        "arabic_text": "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
        "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
        "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
        "english_text": "Then which of the favors of your Lord will you deny?",
        "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
        "verse_number": 77,
    },
    {
        "arabic_text": "تَبَـٰرَكَ ٱسْمُ رَبِّكَ ذِى ٱلْجَلَـٰلِ وَٱلْإِكْرَامِ",
        "urdu_text": "بہت بابرکت ہے تیرے رب کا نام جو عظمت اور بزرگی والا ہے",
        "persian_text": "مبارک است نام پروردگار تو، صاحب جلال و بزرگواری",
        "english_text": "Blessed is the name of your Lord, Owner of Majesty and Honor.",
        "transliteration": "Tabāraka ismu rabbika dhī al-jalāli wal-ikrām",
        "verse_number": 78,
    },
]
