ayats = [
    {
        "verse_number": "1",
        "arabic_text": "وَ السَّمَآءِ وَ الطَّارِقِ",
        "urdu_text": "قسم ہے آسمان کی اور رات کو آنے والے کی",
        "persian_text": "سوگند به آسمان و شب‌آمده",
        "english_text": "By the sky and the night visitor—",
        "transliteration": "Was-samā’i wat-ṭāriq",
    },
    {
        "verse_number": "2",
        "arabic_text": "وَ مَآ اَدْرٰكَ مَا الطَّارِقُ",
        "urdu_text": "اور تم کیا جانو کہ رات کو آنے والا کیا ہے؟",
        "persian_text": "و چه چیز تو را آگاه ساخت که شب‌آمده چیست؟",
        "english_text": "And what will make you know what the night visitor is?",
        "transliteration": "Wa mā adrāka mat-ṭāriq",
    },
    {
        "verse_number": "3",
        "arabic_text": "النَّجْمُ الثَّاقِبُ",
        "urdu_text": "وہ چمکنے والا تارا ہے",
        "persian_text": "آن ستاره درخشان است",
        "english_text": "It is the piercing star—",
        "transliteration": "An-najmu ath-thāqib",
    },
    {
        "verse_number": "4",
        "arabic_text": "اِن كُلُّ نَفْسٍ لَّمَّا عَلَيْهَا حَافِظٌ",
        "urdu_text": "کوئی جان ایسی نہیں جس پر نگہبان نہ ہو",
        "persian_text": "هیچ نفسی نیست مگر آنکه نگهبانی بر آن گمارده شده است",
        "english_text": "Indeed, every soul has a guardian over it.",
        "transliteration": "In kullu nafsin lammā ‘alayhā ḥāfiẓ",
    },
    {
        "verse_number": "5",
        "arabic_text": "فَلْيَنظُرِ الْاِنسَانُ مِمَّ خُلِقَ",
        "urdu_text": "پس انسان کو دیکھنا چاہیے کہ وہ کس چیز سے پیدا ہوا ہے",
        "persian_text": "پس انسان باید بنگرد که از چه چیز آفریده شده است",
        "english_text": "So let man consider from what he is created.",
        "transliteration": "Falyanẓuril-insānu mimma khuliq",
    },
    {
        "verse_number": "6",
        "arabic_text": "خُلِقَ مِن مَّآءٍ دَافِقٍ",
        "urdu_text": "وہ ایک اچھلتے ہوئے پانی سے پیدا کیا گیا ہے",
        "persian_text": "از آبی جهنده آفریده شده است",
        "english_text": "He is created from a fluid, ejected—",
        "transliteration": "Khuliqa mim mā’in dāfiq",
    },
    {
        "verse_number": "7",
        "arabic_text": "يَخْرُجُ مِن بَيْنِ الصُّلْبِ وَ التَّرَآئِبِ",
        "urdu_text": "جو نکلتا ہے ریڑھ کی ہڈی اور سینے کی ہڈیوں کے درمیان سے",
        "persian_text": "که از میان پشت و سینه بیرون می‌آید",
        "english_text": "Emerging from between the backbone and the ribs.",
        "transliteration": "Yakhruju mim baynis-ṣulbi wat-tarā’ib",
    },
    {
        "verse_number": "8",
        "arabic_text": "اِنَّهُ عَلٰى رَجْعِهِ لَقَادِرٌ",
        "urdu_text": "یقیناً وہ اس کو واپس لانے پر قادر ہے",
        "persian_text": "بی‌گمان او بر بازگرداندن وی تواناست",
        "english_text": "Indeed, Allah is Able to bring him back [to life].",
        "transliteration": "Innahū ‘alā raj‘ihi laqādir",
    },
    {
        "verse_number": "9",
        "arabic_text": "يَوْمَ تُبْلَى السَّرَآئِرُ",
        "urdu_text": "جس دن سب چھپی باتیں ظاہر کر دی جائیں گی",
        "persian_text": "روزی که رازها آزموده شوند",
        "english_text": "On the Day when secrets will be put on trial,",
        "transliteration": "Yawma tublal-sarā’ir",
    },
    {
        "verse_number": "10",
        "arabic_text": "فَمَا لَهُ مِن قُوَّةٍ وَ لَا نَاصِرٍ",
        "urdu_text": "پھر انسان کے پاس نہ کوئی طاقت ہوگی اور نہ مددگار",
        "persian_text": "و برای او نه نیرویی خواهد بود و نه یاوری",
        "english_text": "Then man will have no power or any helper.",
        "transliteration": "Famā lahu min quwwatin wa lā nāṣir",
    },
    {
        "verse_number": "11",
        "arabic_text": "وَ السَّمَآءِ ذَاتِ الرَّجْعِ",
        "urdu_text": "قسم ہے اس آسمان کی جو بار بار برسنے والا ہے",
        "persian_text": "سوگند به آسمانِ باران‌دهنده",
        "english_text": "By the sky which returns (rain)",
        "transliteration": "Was-samā’i dhātir-raj‘",
    },
    {
        "verse_number": "12",
        "arabic_text": "وَ الْاَرْضِ ذَاتِ الصَّدْعِ",
        "urdu_text": "اور زمین کی جو پھٹنے والی ہے (پیداوار اگانے کے لیے)",
        "persian_text": "و زمینِ شکافنده (که گیاه می‌رویاند)",
        "english_text": "And the earth which cracks open (for vegetation)",
        "transliteration": "Wal-arḍi dhātis-ṣad‘",
    },
    {
        "verse_number": "13",
        "arabic_text": "اِنَّهُ لَقَوْلٌ فَصْلٌ",
        "urdu_text": "بے شک یہ (قرآن) فیصلہ کن بات ہے",
        "persian_text": "بی‌گمان این سخنی قاطع است",
        "english_text": "Indeed, this [Qur'an] is a decisive statement,",
        "transliteration": "Innahū la-qawlun faṣl",
    },
    {
        "verse_number": "14",
        "arabic_text": "وَ مَا هُوَ بِالْهَزْلِ",
        "urdu_text": "اور یہ کوئی مذاق نہیں ہے",
        "persian_text": "و این (سخن) شوخی و بازی نیست",
        "english_text": "And it is not amusement.",
        "transliteration": "Wa mā huwa bil-hazl",
    },
    {
        "verse_number": "15",
        "arabic_text": "اِنَّهُمْ يَكِيدُونَ كَيْدًا",
        "urdu_text": "بے شک یہ لوگ چالیں چل رہے ہیں",
        "persian_text": "بی‌گمان آنان نیرنگ می‌زنند",
        "english_text": "Indeed, they are planning a plan,",
        "transliteration": "Innahum yakīdūna kaidā",
    },
    {
        "verse_number": "16",
        "arabic_text": "وَ اَكِيدُ كَيْدًا",
        "urdu_text": "اور میں بھی چال چل رہا ہوں",
        "persian_text": "و من نیز نقشه می‌کشم",
        "english_text": "But I am also planning a plan.",
        "transliteration": "Wa akīdu kaidā",
    },
    {
        "verse_number": "17",
        "arabic_text": "فَمَهِّلِ الْكٰفِرِينَ اَمْهِلْهُمْ رُوَيْدًا",
        "urdu_text": "تو کافروں کو کچھ مہلت دے، انہیں تھوڑی سی ڈھیل دے",
        "persian_text": "پس کافران را مهلت ده، اندکی مهلتشان ده",
        "english_text": "So allow the disbelievers respite; let them have a little while.",
        "transliteration": "Famahhilil-kāfirīna amhilhum ruwaidā",
    },
]
