ayats = [
    {
        "arabic_text": "وَالتِّينِ وَالزَّيْتُونِ",
        "urdu_text": "انجیر اور زیتون کی قسم",
        "persian_text": "قسم به انجیر و زیتون",
        "english_text": "By the fig and the olive.",
        "transliteration": "Wa-t-teen-i wa-z-zaytoon.",
        "verse_number": "1",
    },
    {
        "arabic_text": "وَطُورِ سِينِينَ",
        "urdu_text": "اور طور سینین کی",
        "persian_text": "و قسم به کوه سینا",
        "english_text": "And by Mount Sinai.",
        "transliteration": "Wa-toor-i seenin.",
        "verse_number": "2",
    },
    {
        "arabic_text": "وَهَٰذَا الْبَلَدِ الْاَمِينِ",
        "urdu_text": "اور اس امن والے شہر مکہ کی",
        "persian_text": "و این شهر امن (مکه)",
        "english_text": "And by this secure city (Mecca).",
        "transliteration": "Wa-hadha al-balad-il-ameen.",
        "verse_number": "3",
    },
    {
        "arabic_text": "لَقَدْ خَلَقْنَا الْاِنسَٰنَ فِىٓ اَحْسَنِ تَقْوِيمٍ",
        "urdu_text": "ہم نے انسان کو بہترین صورت میں پیدا کیا",
        "persian_text": "ما انسان را در بهترین حالت آفریدیم.",
        "english_text": "We have certainly created man in the best of stature.",
        "transliteration": "Laqad khalaqna al-insana fi ahsani taqweem.",
        "verse_number": "4",
    },
    {
        "arabic_text": "ثُمَّ رَدَدْنَٰهُ اَسْفَلَ سَٰفِلِينَ",
        "urdu_text": "پھر ہم نے اسے سب سے نیچے کی حالت میں لوٹا دیا",
        "persian_text": "سپس او را به پایین‌ترین درجات برگرداندیم.",
        "english_text": "Then We returned him to the lowest of the low.",
        "transliteration": "Thumma radadnahu asfala safileen.",
        "verse_number": "5",
    },
    {
        "arabic_text": "اِلَّا الَّذِينَ ءَامَنُوا وَعَمِلُوا الصَّٰلِحَٰتِ فَلَهُمْ اَجْرٌ غَيْرُ مَمْنُونٍ",
        "urdu_text": "سوائے ان لوگوں کے جو ایمان لائے اور نیک عمل کیے، ان کے لیے بے انتہا اجر ہے",
        "persian_text": "مگر کسانی که ایمان آوردند و کارهای نیک کردند، برای آن‌ها پاداش بی‌پایان است.",
        "english_text": "Except for those who believe and do righteous deeds, for they will have a reward uninterrupted.",
        "transliteration": "Illa alladhina amanu wa-amilu as-salihat, falahum ajrun ghayru mamnoon.",
        "verse_number": "6",
    },
    {
        "arabic_text": "فَمَا يُكَذِّبُكَ بَعْدُ بِالدِّينِ",
        "urdu_text": "پھر تمہیں کیا چیز دین کی تکذیب پر آمادہ کرتی ہے؟",
        "persian_text": "پس چه چیزی تو را وادار می‌کند که دین را تکذیب کنی؟",
        "english_text": "So what yet causes you to deny the Recompense?",
        "transliteration": "Fama yukadh-dhibuka ba’du bid-deen.",
        "verse_number": "7",
    },
    {
        "arabic_text": "اَلَيْسَ اللَّهُ بِاَحْكَمِ الْحَٰكِمِينَ",
        "urdu_text": "کیا اللہ سب حاکموں سے بڑا حاکم نہیں ہے؟",
        "persian_text": "آیا خداوند، حاکم‌ترین حاکمان نیست؟",
        "english_text": "Is not Allah the most just of judges?",
        "transliteration": "Alaysa Allahu bi-ahkami al-hakimeen.",
        "verse_number": "8",
    },
]
