ayats = [
    {
        "verse_number": "1",
        "arabic_text": "اِذَا الشَّمْسُ كُوِّرَتْ",
        "urdu_text": "جب سورج لپیٹ دیا جائے گا",
        "persian_text": "هنگامی که خورشید در هم پیچیده شود",
        "english_text": "When the sun is wrapped up [in darkness]",
        "transliteration": "Idhā ash-shamsu kuwwirat",
    },
    {
        "verse_number": "2",
        "arabic_text": "وَ اِذَا النُّجُومُ انكَدَرَتْ",
        "urdu_text": "اور جب ستارے بے نور ہو جائیں گے",
        "persian_text": "و زمانی که ستارگان فرو ریزند",
        "english_text": "And when the stars fall, dispersing",
        "transliteration": "Wa idhā an-nujūmu inkadarat",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَ اِذَا الْجِبَالُ سُيِّرَتْ",
        "urdu_text": "اور جب پہاڑ حرکت میں آجایئن گے",
        "persian_text": "و زمانی که کوه‌ها به حرکت درآیند",
        "english_text": "And when the mountains are removed",
        "transliteration": "Wa idhā al-jibālu suyyirat",
    },
    {
        "verse_number": "4",
        "arabic_text": "وَ اِذَا الْعِشَارُ عُطِّلَتْ",
        "urdu_text": "اور جب دس مہینے کی حاملہ اونٹنیاں چھوڑ دی جائیں گی",
        "persian_text": "و زمانی که شتران آبستن رها شوند",
        "english_text": "And when full-term she-camels are neglected",
        "transliteration": "Wa idhā al-ʿishāru ʿuṭṭilat",
    },
    {
        "verse_number": "5",
        "arabic_text": "وَ اِذَا الْوُحُوشُ حُشِرَتْ",
        "urdu_text": "اور جب جانور جمع کیے جائیں گے",
        "persian_text": "و زمانی که وحوش گرد آورده شوند",
        "english_text": "And when the wild beasts are gathered",
        "transliteration": "Wa idhā al-wuḥūshu ḥushirat",
    },
    {
        "verse_number": "6",
        "arabic_text": "وَ اِذَا الْبِحَارُ سُجِّرَتْ",
        "urdu_text": "اور جب سمندر بھڑکائے جائیں گے",
        "persian_text": "و زمانی که دریاها شعله‌ور شوند",
        "english_text": "And when the seas are filled with flame",
        "transliteration": "Wa idhā al-biḥāru sujjirat",
    },
    {
        "verse_number": "7",
        "arabic_text": "وَ اِذَا النُّفُوسُ زُوِّجَتْ",
        "urdu_text": "اور جب روحوں کو جسموں سے جوڑ دیا جایگا",
        "persian_text": "و زمانی که نفوس جفت شوند",
        "english_text": "And when the souls are paired",
        "transliteration": "Wa idhā an-nufūsu zuwwijat",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَ اِذَا الْمَوْءُودَةُ سُئِلَتْ",
        "urdu_text": "اور جب زندہ دفن کی گئی لڑکیوں کے بارے میں پوچھا جائے گا",
        "persian_text": "و زمانی که از دختر زنده به گور شده پرسیده شود",
        "english_text": "And when [we] will ask about the girls [who were] buried alive",
        "transliteration": "Wa idhā al-maw’ūdatu su’ilat",
    },
    {
        "verse_number": "9",
        "arabic_text": "بِاَيِّ ذَنبٍ قُتِلَتْ",
        "urdu_text": "کے انہیں کس گناہ میں مرا گیا ہے ",
        "persian_text": "به کدامین گناه کشته شده است؟",
        "english_text": "For what sin they were killed",
        "transliteration": "Bi’ayyidhanbin qutilat",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَ اِذَا الصُّحُفُ نُشِرَتْ",
        "urdu_text": "اور جب نامہ اعمال کھولے جائیں گے",
        "persian_text": "و زمانی که صحیفه‌ها گشوده شوند",
        "english_text": "And when the pages are made public",
        "transliteration": "Wa idhā aṣ-ṣuḥufu nushirat",
    },
    {
        "verse_number": "11",
        "arabic_text": "وَ اِذَا السَّمَآءُ كُشِطَتْ",
        "urdu_text": "اور جب آسمان کی کھال اتاری جائے گی",
        "persian_text": "و زمانی که آسمان برکنده شود",
        "english_text": "And when the sky is stripped away",
        "transliteration": "Wa idhā as-samā’u kushitat",
    },
    {
        "verse_number": "12",
        "arabic_text": "وَ اِذَا الْجَحِيمُ سُعِّرَتْ",
        "urdu_text": "اور جب جہنم بھڑکائی جائے گی",
        "persian_text": "و زمانی که جهنم شعله‌ور شود",
        "english_text": "And when Hellfire is set ablaze",
        "transliteration": "Wa idhā al-jaḥīmu suʿʿirat",
    },
    {
        "verse_number": "13",
        "arabic_text": "وَ اِذَا الْجَنَّةُ اُزْلِفَتْ",
        "urdu_text": "اور جب جنت قریب لائی جائے گی",
        "persian_text": "و زمانی که بهشت نزدیک آورده شود",
        "english_text": "And when Paradise is brought near",
        "transliteration": "Wa idhā al-jannatu uzlifat",
    },
    {
        "verse_number": "14",
        "arabic_text": "عَلِمَتْ نَفْسٌ مَّا اَحْضَرَتْ",
        "urdu_text": "تب ہر نفس کو معلوم ہو جایگا کہ اسنے کیا حاضر کیا ہے",
        "persian_text": "هر نفسی خواهد دانست آنچه را که حاضر کرده است",
        "english_text": "A soul will [then] know what it has brought [with it]",
        "transliteration": "ʿAlimat nafsun mā aḥḍarat",
    },
    {
        "verse_number": "15",
        "arabic_text": "فَلَا اُقْسِمُ بِالْخُنَّسِ",
        "urdu_text": "پس میں قسم کھاتا ہوں پیچھے ہٹنے والے ستاروں کی",
        "persian_text": "پس سوگند می‌خورم به ستارگان بازگردنده",
        "english_text": "So I swear by the retreating stars",
        "transliteration": "Falā uqsimu bil-khunnas",
    },
    {
        "verse_number": "16",
        "arabic_text": "الْجَوَارِ الْكُنَّسِ",
        "urdu_text": "جو چلتے ہیں اور غائب ہو جاتے ہیں",
        "persian_text": "که در حرکتند و پنهان می‌شوند",
        "english_text": "Those that run [their courses] and disappear",
        "transliteration": "Al-jawāri al-kunnas",
    },
    {
        "verse_number": "17",
        "arabic_text": "وَ اللَّيْلِ اِذَا عَسْعَسَ",
        "urdu_text": "اور رات کی جب وہ چھا جائے",
        "persian_text": "و شب هنگامی که فرا رسد",
        "english_text": "And by the night as it closes in",
        "transliteration": "Wa al-layli idhā ʿasʿasa",
    },
    {
        "verse_number": "18",
        "arabic_text": "وَ الصُّبْحِ اِذَا تَنَفَّسَ",
        "urdu_text": "اور صبح کی جب وہ سانس لے",
        "persian_text": "و صبح هنگامی که نفس کشد",
        "english_text": "And by the dawn when it breathes",
        "transliteration": "Wa aṣ-ṣubḥi idhā tanaffasa",
    },
    {
        "verse_number": "19",
        "arabic_text": "اِنَّهُ لَقَوْلُ رَسُولٍ كَرِيمٍ",
        "urdu_text": "بیشک یہ ایک معزز رسول کا قول ہے",
        "persian_text": "بی‌گمان این سخن رسولی گرامی است",
        "english_text": "Indeed, the Qur'an is a word [conveyed by] a noble messenger",
        "transliteration": "Innahu laqawlu rasūlin karīm",
    },
    {
        "verse_number": "20",
        "arabic_text": "ذِي قُوَّةٍ عِندَ ذِي الْعَرْشِ مَكِينٍ",
        "urdu_text": "جو قوت والا ہے، عرش والے کے ہاں بلند مرتبہ ہے",
        "persian_text": "که دارای قوت است، نزد صاحب عرش دارای مقام استوار است",
        "english_text": "Endued with power, with the Lord of the Throne, secure in position.",
        "transliteration": "dhī quwwatin ʿinda dhī l-ʿarshi makīn",
    },
    {
        "verse_number": "21",
        "arabic_text": "مُّطَاعٍ ثَمَّ اَمِينٍ",
        "urdu_text": "وہاں (آسمان میں) عزت والا، امانت دار ہے",
        "persian_text": "مطاع است و امین در آنجا (نزد خدا)",
        "english_text": "Obeyed there [in the heavens] and trustworthy",
        "transliteration": "Muṭāʿin thamma amīn",
    },
    {
        "verse_number": "22",
        "arabic_text": "وَ مَا صَاحِبُكُم بِمَجْنُونٍ",
        "urdu_text": "اور تمہارا ساتھی نبی دیوانہ نہیں ہے",
        "persian_text": "و یار شما دیوانه نیست",
        "english_text": "And your companion is not [at all] mad",
        "transliteration": "Wa mā ṣāḥibukum bimajnūn",
    },
    {
        "verse_number": "23",
        "arabic_text": "وَ لَقَدْ رَآهُ بِالْاُفُقِ الْمُبِينِ",
        "urdu_text": "اور اسنے فرشتوں کو بلند افق پر دیکھا ہے",
        "persian_text": "و هر آینه او را در افق روشن دیده است",
        "english_text": "And he has already seen him in the clear horizon",
        "transliteration": "Wa laqad ra’āhu bil-ufuqil-mubīn",
    },
    {
        "verse_number": "24",
        "arabic_text": "وَ مَا هُوَ عَلَى الْغَيْبِ بِضَنِينٍ",
        "urdu_text": "اور وہ غیب کی باتوں پر بخیل نہیں ہے",
        "persian_text": "و او بر غیب بخیل نیست (آن را پنهان نمی‌کند)",
        "english_text": "And he is not a withholder of [knowledge of] the unseen",
        "transliteration": "Wa mā huwa ʿala al-ghaybi biḍanīn",
    },
    {
        "verse_number": "25",
        "arabic_text": "وَ مَا هُوَ بِقَوْلِ شَيْطٰنٍ رَّجِيمٍ",
        "urdu_text": "اور یہ قرآن کسی مردود شیطان کا قول نہیں ہے",
        "persian_text": "و این (قرآن) گفتار شیطان رانده شده نیست",
        "english_text": "And it is not the word of a devil, expelled [from the heavens]",
        "transliteration": "Wa mā huwa biqawli shayṭānin rajīm",
    },
    {
        "verse_number": "26",
        "arabic_text": "فَاَيْنَ تَذْهَبُونَ",
        "urdu_text": "تو تم کہاں جا رہے ہو؟",
        "persian_text": "پس کجا می‌روید؟",
        "english_text": "So where are you going?",
        "transliteration": "Fa ayna tadhhabūn",
    },
    {
        "verse_number": "27",
        "arabic_text": "اِنْ هُوَ اِلَّا ذِكْرٌ لِّلْعٰلَمِينَ",
        "urdu_text": "یہ الامین کہ لئے صرف نصیحت کا سامان ہے",
        "persian_text": "این فقط تذکری برای جهانیان است",
        "english_text": "It is nothing but a reminder to the worlds",
        "transliteration": "In huwa illā dhikrun lil-ʿālamīn",
    },
    {
        "verse_number": "28",
        "arabic_text": "لِمَن شَآءَ مِنكُمْ اَن يَّسْتَقِيمَ",
        "urdu_text": "اس کے لیے جو تم میں سے سیدھی راہ اختیار کرنا چاہے",
        "persian_text": "برای کسی از شما که بخواهد راست روَد",
        "english_text": "For whoever wills among you to take a right course",
        "transliteration": "Liman shā’a minkum an yastaqīm",
    },
    {
        "verse_number": "29",
        "arabic_text": "وَ مَا تَشَآءُوْنَ اِلَّا اَن يَّشَآءَ اللّٰهُ رَبُّ الْعٰلَمِينَ",
        "urdu_text": "اور تم کچھ نہیں چاہ سکتے مگر جو اللہ، رب العالمین چاہے",
        "persian_text": "و شما نمی‌خواهید مگر آنچه خدا، پروردگار جهانیان، بخواهد",
        "english_text": "And you do not will except that Allah wills – Lord of the worlds",
        "transliteration": "Wa mā tashā’ūna illā an yashā’a Allāhu rabbul-ʿālamīn",
    },
]
