ayats = [
    {
        "verse_number": "1",
        "arabic_text": "أَلْهَاكُمُ ٱلتَّكَاثُرُ",
        "urdu_text": "تمہیں زیادہ کی طلب نے غافل کر دیا",
        "persian_text": "افزون‌طلبی شما را غافل کرد",
        "english_text": "The craving for more and more distracted you.",
        "transliteration": "Alhākumu al-takāthur",
    },
    {
        "verse_number": "2",
        "arabic_text": "حَتَّىٰ زُرْتُمُ ٱلْمَقَابِرَ",
        "urdu_text": "یہاں تک کہ تم قبروں تک جا پہنچے",
        "persian_text": "تا آن‌گاه که به گورستان رفتید",
        "english_text": "Until you visited the graves.",
        "transliteration": "Ḥattā zurtumu al-maqābir",
    },
    {
        "verse_number": "3",
        "arabic_text": "كَلَّا سَوْفَ تَعْلَمُونَ",
        "urdu_text": "خبردار! تم جلد ہی جان لو گے",
        "persian_text": "هرگز! به‌زودی خواهید دانست",
        "english_text": "Nay! You shall soon know.",
        "transliteration": "Kallā sawfa taʿlamūn",
    },
    {
        "verse_number": "4",
        "arabic_text": "ثُمَّ كَلَّا سَوْفَ تَعْلَمُونَ",
        "urdu_text": "پھر خبردار! تم جلد ہی جان لو گے",
        "persian_text": "باز هم هرگز! به‌زودی خواهید دانست",
        "english_text": "Again, nay! You shall soon know.",
        "transliteration": "Thumma kallā sawfa taʿlamūn",
    },
    {
        "verse_number": "5",
        "arabic_text": "كَلَّا لَوْ تَعْلَمُونَ عِلْمَ ٱلْيَقِينِ",
        "urdu_text": "خبردار! اگر تم یقینی علم سے جانتے",
        "persian_text": "اگر با علم یقین می‌دانستید",
        "english_text": "Nay! If you knew with knowledge of certainty.",
        "transliteration": "Kallā law taʿlamūna ʿilma al-yaqīn",
    },
    {
        "verse_number": "6",
        "arabic_text": "لَتَرَوُنَّ ٱلْجَحِيمَ",
        "urdu_text": "تو ضرور تم جہنم دیکھو گے",
        "persian_text": "قطعاً دوزخ را خواهید دید",
        "english_text": "You will surely see the Hellfire.",
        "transliteration": "Latarawunna al-jaḥīm",
    },
    {
        "verse_number": "7",
        "arabic_text": "ثُمَّ لَتَرَوُنَّهَا عَيْنَ ٱلْيَقِينِ",
        "urdu_text": "پھر ضرور تم اسے یقین کی آنکھ سے دیکھو گے",
        "persian_text": "سپس آن را با چشم یقین خواهید دید",
        "english_text": "Then, you will surely see it with the eye of certainty.",
        "transliteration": "Thumma latarawunnahā ʿayna al-yaqīn",
    },
    {
        "verse_number": "8",
        "arabic_text": "ثُمَّ لَتُسْـَٔلُنَّ يَوْمَئِذٍ عَنِ ٱلنَّعِيمِ",
        "urdu_text": "پھر ضرور اس دن تم سے نعمتوں کے بارے میں پوچھا جائے گا",
        "persian_text": "سپس در آن روز از نعمت‌ها پرسیده خواهید شد",
        "english_text": "Then, on that Day, you will surely be asked about the pleasures.",
        "transliteration": "Thumma latus'alunna yawma'idhin ʿani al-naʿīm",
    },
]
