ayats = [
    {
        "arabic_text": "وَالضُّحَىٰ",
        "urdu_text": "قسم ہے چاشت کے وقت کی",
        "persian_text": "سوگند به هنگام چاشت",
        "english_text": "By the morning brightness",
        "transliteration": "Waḍ-ḍuḥā",
        "verse_number": "1",
    },
    {
        "arabic_text": "وَاللَّيْلِ إِذَا سَجَىٰ",
        "urdu_text": "اور رات کی جب وہ چھا جائے",
        "persian_text": "و سوگند به شب هنگامی که آرام گیرد",
        "english_text": "And [by] the night when it covers with darkness",
        "transliteration": "Wa-l-layli idhā sajā",
        "verse_number": "2",
    },
    {
        "arabic_text": "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ",
        "urdu_text": "تمہارے رب نے نہ تمہیں چھوڑا اور نہ ناراض ہوا",
        "persian_text": "پروردگارت نه تو را ترک کرده و نه دشمن داشته است",
        "english_text": "Your Lord has not forsaken you, nor has He become displeased",
        "transliteration": "Mā wadda‘aka rabbuka wa mā qalā",
        "verse_number": "3",
    },
    {
        "arabic_text": "وَلَلْآخِرَةُ خَيْرٌ لَّكَ مِنَ الْأُولَىٰ",
        "urdu_text": "اور بے شک تمہارے لیے آخرت بہتر ہے پہلی (زندگی) سے",
        "persian_text": "و آخرت برای تو بهتر از دنیاست",
        "english_text": "And the Hereafter is better for you than the first [life]",
        "transliteration": "Wa la-l-ākhiratu khayrun laka mina-l-ūlā",
        "verse_number": "4",
    },
    {
        "arabic_text": "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ",
        "urdu_text": "اور بے شک تمہارا رب تمہیں اتنا دے گا کہ تم راضی ہو جاؤ گے",
        "persian_text": "و به‌زودی پروردگارت به تو عطا خواهد کرد تا خشنود شوی",
        "english_text": "And your Lord is going to give you, and you will be satisfied",
        "transliteration": "Wa lasawfa yu‘ṭīka rabbuka fa tarḍā",
        "verse_number": "5",
    },
    {
        "arabic_text": "أَلَمْ يَجِدْكَ يَتِيمًا فَآوَىٰ",
        "urdu_text": "کیا اس نے تمہیں یتیم نہیں پایا، پھر پناہ دی؟",
        "persian_text": "آیا تو را یتیم نیافت، پس پناهت داد؟",
        "english_text": "Did He not find you an orphan and give [you] refuge?",
        "transliteration": "Alam yajidka yatīman fa āwā",
        "verse_number": "6",
    },
    {
        "arabic_text": "وَوَجَدَكَ ضَالًّا فَهَدَىٰ",
        "urdu_text": "اور اس نے تمہیں راستہ نہ جاننے والا پایا تو راہ دکھائی",
        "persian_text": "و تو را گمراه یافت، پس هدایتت کرد",
        "english_text": "And He found you lost and guided [you]",
        "transliteration": "Wa wajadaka ḍāllan fa hadā",
        "verse_number": "7",
    },
]
[
    {
        "arabic_text": "وَوَجَدَكَ عَائِلًا فَأَغْنَىٰ",
        "urdu_text": "اور اس نے تمہیں محتاج پایا، پھر غنی کر دیا",
        "persian_text": "و تو را نیازمند یافت، پس بی‌نیازت ساخت",
        "english_text": "And He found you poor and made [you] self-sufficient",
        "transliteration": "Wa wajadaka ‘āilan fa aghnā",
        "verse_number": "8",
    },
    {
        "arabic_text": "فَأَمَّا الْيَتِيمَ فَلَا تَقْهَرْ",
        "urdu_text": "پس یتیم پر سختی نہ کرنا",
        "persian_text": "پس یتیم را میازار",
        "english_text": "So as for the orphan, do not oppress [him]",
        "transliteration": "Fa ammā-l-yatīma fa lā taqhar",
        "verse_number": "9",
    },
    {
        "arabic_text": "وَأَمَّا السَّائِلَ فَلَا تَنْهَرْ",
        "urdu_text": "اور سوالی کو نہ جھڑکنا",
        "persian_text": "و گدا را از خود مران",
        "english_text": "And as for the petitioner, do not repel [him]",
        "transliteration": "Wa ammā-s-sā’ila fa lā tanhar",
        "verse_number": "10",
    },
    {
        "arabic_text": "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ",
        "urdu_text": "اور اپنے رب کی نعمت کا تذکرہ کیا کرو",
        "persian_text": "و از نعمت پروردگارت سخن گوی",
        "english_text": "But as for the favor of your Lord, report [it]",
        "transliteration": "Wa ammā bini‘mati rabbika fa ḥaddith",
        "verse_number": "11",
    },
]
