ayats = [
    {
        "verse_number": "1",
        "arabic_text": "اِذَا زُلْزِلَتِ الْاَرْضُ زِلْزَالَهَا",
        "urdu_text": "جب زمین کو اس کے بھونچال سے ہلا دیا جائے گا",
        "persian_text": "هنگامی که زمین با زلزله‌ی شدیدش بلرزد،",
        "english_text": "When the earth is shaken with its [final] earthquake.",
        "transliteration": "Idhā zulzilati al-arḍu zilzālahā",
    },
    {
        "verse_number": "2",
        "arabic_text": "وَ اَخْرَجَتِ الْاَرْضُ اَثْقَالَهَا",
        "urdu_text": "اور وہ سارے خزانے نکل دے گی",
        "persian_text": "و زمین بارهای سنگین خود را بیرون می‌ریزد،",
        "english_text": "And the earth discharges its burdens.",
        "transliteration": "Wa akhrajati al-arḍu athqālahā",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَ قَالَ الْاِنسَانُ مَا لَهَا",
        "urdu_text": "اور انسان کہے گا کہ اسے کیا ہو گیا ہے؟",
        "persian_text": "و انسان خواهد گفت: «چه بر سرش آمده است؟»",
        "english_text": "And man says, 'What is [wrong] with it?'",
        "transliteration": "Wa qāla al-insānu mā lahā",
    },
    {
        "verse_number": "4",
        "arabic_text": "يَوْمَئِذٍ تُحَدِّثُ اَخْبَارَهَا",
        "urdu_text": "اس دن زمین اپنی خبریں بیان کرے گی",
        "persian_text": "در آن روز زمین اخبار خود را بازگو خواهد کرد،",
        "english_text": "That Day, it will report its news.",
        "transliteration": "Yawma’idhin tuḥaddithu akhbārahā",
    },
    {
        "verse_number": "5",
        "arabic_text": "بِاَنَّ رَبَّكَ اَوْحٰى لَهَا",
        "urdu_text": "کیونکہ تیرے رب نے اسے حکم دیا ہوگا",
        "persian_text": "زیرا که پروردگارت به آن وحی کرده است.",
        "english_text": "Because your Lord has inspired it.",
        "transliteration": "Bi’anna rabbaka awḥā lahā",
    },
    {
        "verse_number": "6",
        "arabic_text": "يَوْمَئِذٍ يَصْدُرُ النَّاسُ اَشْتَاتًا لِّيُرَوْا۟ اَعْمَالَهُمْ",
        "urdu_text": "اس دن لوگ مختلف حالتوں میں لوٹیں گے تاکہ انہیں ان کے اعمال دکھائے جائیں",
        "persian_text": "در آن روز مردم گروه گروه باز می‌گردند تا اعمالشان به آنان نشان داده شود،",
        "english_text": "That Day, the people will depart separated [into categories] to be shown [the result of] their deeds.",
        "transliteration": "Yawma’idhin yaṣduru al-nāsu ashtātan liyuraw aʿmālahum",
    },
    {
        "verse_number": "7",
        "arabic_text": "فَمَن يَّعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَّرَهُۥ",
        "urdu_text": "تو جس نے ذرہ بھر نیکی کی ہوگی، وہ اسے دیکھ لے گا",
        "persian_text": "پس هر کس به اندازه ذره‌ای کار نیک انجام دهد، آن را خواهد دید،",
        "english_text": "So whoever does an atom's weight of good will see it.",
        "transliteration": "Faman yaʿmal mithqāla dharratin khayran yarah",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَ مَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَّرَهُۥ",
        "urdu_text": "اور جس نے ذرہ بھر برائی کی ہوگی، وہ اسے دیکھ لے گا",
        "persian_text": "و هر کس به اندازه ذره‌ای کار بد انجام دهد، آن را خواهد دید.",
        "english_text": "And whoever does an atom's weight of evil will see it.",
        "transliteration": "Wa man yaʿmal mithqāla dharratin sharran yarah",
    },
]
