ayats = [
  {
    "verse_number": 1,
    "english_text": "I swear by the light of the Sun.",
    "arabic_text": "وَ الشَّمْسِ وَ ضُحٰهَا",
    "urdu_text": "قسم ہے سورج کی اور اس کی روشنی کی",
    "persian_text": "سوگند به خورشید و روشنایی آن",
    "transliteration": "Wash-shamsi wa duhaha",
  },
  {
    "verse_number": 2,
    "english_text": "And I swear by the moon which follows it.",
    "arabic_text": "وَ الْقَمَرِ اِذَا تَلٰهَا",
    "urdu_text": "اور قسم ہے چاند کی جب وہ اس کے پیچھے آئے",
    "persian_text": "و سوگند به ماه هنگامی که آن را پیروی کند",
    "transliteration": "Wal-qamari idha talaha",
  },
  {
    "verse_number": 3,
    "english_text": "And I swear by the day when it gives brightness.",
    "arabic_text": "وَ النَّهَارِ اِذَا جَلّٰهَا",
    "urdu_text": "اور قسم ہے دن کی جب وہ اسے روشن کر دے",
    "persian_text": "و سوگند به روز هنگامی که آن را آشکار سازد",
    "transliteration": "Wan-nahari idha jallaha",
  },
  {
    "verse_number": 4,
    "english_text": "And I swear by the night when it covers up.",
    "arabic_text": "وَ الَّيْلِ اِذَا يَغْشٰهَا",
    "urdu_text": "اور قسم ہے رات کی جب وہ اسے ڈھانپ لے",
    "persian_text": "و سوگند به شب هنگامی که آن را بپوشاند",
    "transliteration": "Wal-layli idha yaghshaha",
  },
  {
    "verse_number": 5,
    "english_text": "And I swear by the sky, and of Him who made it.",
    "arabic_text": "وَ السَّمَآءِ وَ مَا بَنٰهَا",
    "urdu_text": "اور قسم ہے آسمان کی اور اس ذات کی جس نے اسے بنایا",
    "persian_text": "و سوگند به آسمان و آن کس که آن را بنا کرد",
    "transliteration": "Was-samaai wa ma banaha",
  },
  {
    "verse_number": 6,
    "english_text": "And I swear by the earth, and of Him who spread it.",
    "arabic_text": "وَ الْاَرْضِ وَ مَا طَحٰهَا",
    "urdu_text": "اور زمین کی قسم اور اس ذات کی جس نے اسے پھیلایا",
    "persian_text": "و سوگند به زمین و آن کس که آن را گسترانید",
    "transliteration": "Wal-ardi wa ma tahaha",
  },
  {
    "verse_number": 7,
    "english_text": "And I swear by the Soul, and of Him who perfected it.",
    "arabic_text": "وَ نَفْسٍ وَّ مَا سَوّٰهَا",
    "urdu_text": "اور نفس کی قسم اور اس ذات کی جس نے اسے درست بنایا",
    "persian_text": "و سوگند به نفس و آن کس که آن را متعادل آفرید",
    "transliteration": "Wa nafsin wa ma sawwaha",
  },
  {
    "verse_number": 8,
    "english_text": "Then guided about evil and righteousness.",
    "arabic_text": "فَاَلْهَمَهَا فُجُورَهَا وَ تَقْوٰهَا",
    "urdu_text": "پھر اسے اس کی بدی اور پرہیزگاری کی سمجھ عطا کی",
    "persian_text": "پس به آن الهام داد بدی و پرهیزگاری‌اش را",
    "transliteration": "Fa-alhamaha fujuraha wa taqwaha",
  },
  {
    "verse_number": 9,
    "english_text": "Verily, he is successful, who purified himself.",
    "arabic_text": "قَدْ اَفْلَحَ مَن زَكّٰهَا",
    "urdu_text": "یقیناً کامیاب ہوا وہ جس نے اپنے نفس کو پاک کیا",
    "persian_text": "به راستی رستگار شد کسی که آن را پاک کرد",
    "transliteration": "Qad aflaha man zakkaha",
  },
  {
    "verse_number": 10,
    "english_text": "And he became hopeless [of one] who polluted it.",
    "arabic_text": "وَ قَدْ خَابَ مَن دَسّٰهَا",
    "urdu_text": "اور نامراد ہوا وہ جس نے اسے آلودہ کیا",
    "persian_text": "و زیان‌کار شد کسی که آن را آلوده ساخت",
    "transliteration": "Wa qad khaba man dassaha",
  },
  {
    "verse_number": 11,
    "english_text": "Samood denied the prophet because of their rebelliousness.",
    "arabic_text": "كَذَّبَتْ ثَمُودُ بِطَغْوٰهَا",
    "urdu_text": "ثمود نے اپنی سرکشی کی وجہ سے جھٹلایا",
    "persian_text": "قوم ثمود به خاطر طغیان خود تکذیب کردند",
    "transliteration": "Kadhdhbat Thamoodu bi taghwaahaa",
  },
  {
    "verse_number": 12,
    "english_text": "When the most unfortunate of them stood up.",
    "arabic_text": "اِذِ انْبَعَثَ اَشْقٰهَا",
    "urdu_text": "جب ان میں سے سب سے بدبخت اٹھ کھڑا ہوا",
    "persian_text": "هنگامی که بدبخت‌ترین آنها برخاست",
    "transliteration": "Idhin ba'atha ashqaahaa",
  },
  {
    "verse_number": 13,
    "english_text": "So, the messenger of Allah said to take care of Allah's she-camel and let her drink.",
    "arabic_text": "فَقَالَ لَهُمْ رَسُولُ اللّٰهِ نَاقَةَ اللّٰهِ وَ سُقْيٰهَا",
    "urdu_text": "تو اللہ کے رسول نے ان سے کہا کہ اللہ کی اونٹنی اور اس کے پانی پینے کا خیال رکھو",
    "persian_text": "پس فرستاده خدا به آنها گفت: ناقه خدا و آب خوردن او را رعایت کنید",
    "transliteration": "Faqaala lahum Rasoolullaahi naaqatallaahi wa suqyaahaa",
  },
  {
    "verse_number": 14,
    "english_text": "So they denied him, and hamstrung her; so Allah sent down the punishment due to their sin and levelled them completely (to the ground).",
    "arabic_text": "فَكَذَّبُوهُ فَعَقَرُوهَا فدَمْدَمَ عَلَيْهِمْ رَبُّهُم بِذَنْبِهِمْ فَسَوّٰهَا",
    "urdu_text": "پھر انہوں نے اسے جھٹلایا اور اونٹنی کی کونچیں کاٹ دیں، تو ان کے رب نے ان کے گناہ کی وجہ سے ان پر عذاب نازل کیا اور انہیں برابر کر دیا",
    "persian_text": "پس او را تکذیب کردند و ناقه را پی کردند، آنگاه پروردگارشان به سبب گناهشان عذاب را بر آنها فرود آورد و همه را یکسان نابود ساخت",
    "transliteration": "Fakadhdhaboohu fa'aqaroohaa fadamdama 'alayhim Rabbuhum bidhanbihim fasawwaahaa",
  },
  {
    "verse_number": 15,
    "english_text": "And he does not have any fear of its consequences.",
    "arabic_text": "وَ لَا يَخَافُ عُقْبٰهَا",
    "urdu_text": "اور اسے اس کے انجام کا کوئی خوف نہیں",
    "persian_text": "و او از عاقبت آن نمی‌ترسد",
    "transliteration": "Wa laa yakhaafu 'uqbaahaa",
  },
]
