ayats = [
  {
    "verse_number": 1,
    "english_text": "(O Prophet!) Say: I seek refuge with the Lord of people.",
    "arabic_text": "قُلْ اَعُوذُ بِرَبِّ النَّاسِ",
    "urdu_text": "کہہ دیجیے کہ میں لوگوں کے رب کی پناہ مانگتا ہوں",
    "persian_text": "بگو که پناه می‌برم به پروردگار مردم",
    "transliteration": "Qul a'oodhu bi rabbil naas",
  },
  {
    "verse_number": 2,
    "english_text": "The Master of mankind.",
    "arabic_text": "مَلِكِ النَّاسِ",
    "urdu_text": "لوگوں کے بادشاہ",
    "persian_text": "پادشاه مردم",
    "transliteration": "Malikin naas",
  },
  {
    "verse_number": 3,
    "english_text": "The God of mankind.",
    "arabic_text": "اِلٰهِ النَّاسِ",
    "urdu_text": "لوگوں کے معبود",
    "persian_text": "معبود مردم",
    "transliteration": "Ilaahin naas",
  },
  {
    "verse_number": 4,
    "english_text": "(I) Seek refuge from the evil whispering of Satan, who withdraws (on hearing the name of Allah).",
    "arabic_text": "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ",
    "urdu_text": "وسوسہ ڈالنے والے پیچھے ہٹ جانے والے کے شر سے",
    "persian_text": "از شر وسوسه‌گر پنهان‌شونده",
    "transliteration": "Min sharril waswaasil khannaas",
  },
  {
    "verse_number": 5,
    "english_text": "Who creates whispering in the hearts of mankind.",
    "arabic_text": "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ",
    "urdu_text": "جو لوگوں کے دلوں میں وسوسے ڈالتا ہے",
    "persian_text": "که در سینه‌های مردم وسوسه می‌اندازد",
    "transliteration": "Allathee yuwaswisu fee sudoorin naas",
  },
  {
    "verse_number": 6,
    "english_text": "From among the Jinns and the men.",
    "arabic_text": "مِنَ الْجِنَّةِ وَ النَّاسِ",
    "urdu_text": "جنوں اور انسانوں میں سے",
    "persian_text": "از میان جن و انس",
    "transliteration": "Minal-jinnati wan-naas",
  },
]
