ayats = [
  {
    "verse_number": 1,
    "english_text": "'(O Prophet!) Say:' I seek refuge from the Master of the dawn.",
    "arabic_text": "قُلْ اَعُوذُ بِرَبِّ الْفَلَقِ",
    "urdu_text": "کهه دیجیے که میں صبح کے رب کی پناه مانگتا هوں",
    "persian_text": "بگو: پناه می‌برم به پروردگار سپیده‌دم",
    "transliteration": "Qul a'oodhu bi rabbil falaq",
  },
  {
    "verse_number": 2,
    "english_text": "From the evil of all the creatures.",
    "arabic_text": "مِن شَرِّ مَا خَلَقَ",
    "urdu_text": "هر اُس چیز کے شر سے جو اُس نے پیدا کی",
    "persian_text": "از شر آنچه آفریده است",
    "transliteration": "Min sharri ma khalaq",
  },
  {
    "verse_number": 3,
    "english_text": "And from the evil of darkness of night when darkness spreads",
    "arabic_text": "وَ مِن شَرِّ غَاسِقٍ اِذَا وَقَبَ",
    "urdu_text": "اور اندھیری رات کے شر سے جب وه چھا جائے",
    "persian_text": "و از شر تاریکی شب هنگامی که فرو رسد",
    "transliteration": "Wa min sharri ghasiqin idha waqab",
  },
  {
    "verse_number": 4,
    "english_text": "And from the evil of those who breath on the amulets.",
    "arabic_text": "وَ مِن شَرِّ النَّفّٰثّٰتِ فِى الْعُقَدِ",
    "urdu_text": "اور گرهوں میں پھونک مارنے والوں کے شر سے",
    "persian_text": "و از شر دمندگان بر گره‌ها",
    "transliteration": "Wa min sharrin naffathati fil 'uqad",
  },
  {
    "verse_number": 5,
    "english_text": "And from the evil of envy, when they envy.",
    "arabic_text": "وَ مِنْ شَرِّ حَاسِدٍ اِذَا حَسَدَ",
    "urdu_text": "اور حسد کرنے والے کے شر سے جب وه حسد کرے",
    "persian_text": "و از شر حسود هنگامی که حسد ورزد",
    "transliteration": "Wa min sharri hasidin idha hasad",
  },
]
