ayats = [
  {
    "verse_number": 1,
    "english_text": "Read in the name of your Lord Who created (you).",
    "arabic_text": "اقْرَاَ بِاسْمِ رَبِّكَ الَّذِى خَلَقَ",
    "urdu_text": "پڑھو اپنے رب کے نام سے جس نے پیدا کیا",
    "persian_text": "بخوان به نام پروردگارت که آفرید",
    "transliteration": "Iqra bismi rabbika allathee khalaq",
  },
  {
    "verse_number": 2,
    "english_text": "He created man from a blood clot.",
    "arabic_text": "خَلَقَ الْاِِنسَانَ مِنْ عَلَقٍ",
    "urdu_text": "اس نے انسان کو خون کے لوتھڑے سے پیدا کیا",
    "persian_text": "انسان را از خون بسته آفرید",
    "transliteration": "Khalaqa al-insana min 'alaq",
  },
  {
    "verse_number": 3,
    "english_text": "Read and your Lord is most Merciful.",
    "arabic_text": "اقْرَاْ وَ رَبُّكَ الْاَكْرَمُ",
    "urdu_text": "پڑھو اور تمہارا رب بڑا کریم ہے",
    "persian_text": "بخوان و پروردگارت بزرگوارترین است",
    "transliteration": "Iqra wa rabbuka al-akram",
  },
  {
    "verse_number": 4,
    "english_text": "Who taught (to write) through the pen.",
    "arabic_text": "الَّذِىْ عَلَّمَ بِالْقَلَمِ",
    "urdu_text": "جس نے قلم کے ذریعے سکھایا",
    "persian_text": "که به وسیله قلم آموخت",
    "transliteration": "Allathee 'allama bil-qalam",
  },
  {
    "verse_number": 5,
    "english_text": "And taught all that to the man what he had not known.",
    "arabic_text": "عَلَّمَ الْاِِنسَانَ مَا لَمْ يَعْلَمْ",
    "urdu_text": "اور انسان کو وہ سکھایا جو وہ نہیں جانتا تھا",
    "persian_text": "و به انسان آنچه را نمی‌دانست آموخت",
    "transliteration": "'Allama al-insana ma lam ya'lam",
  },
  {
    "verse_number": 6,
    "english_text": "Indeed, man does rebelliousness.",
    "arabic_text": "كَلَّآ اِنَّ الْاِِنسَانَ لَيَطْغٰٓى",
    "urdu_text": "ہرگز نہیں، بیشک انسان سرکشی کرتا ہے",
    "persian_text": "چنین نیست، همانا انسان طغیان می‌کند",
    "transliteration": "Kalla inna al-insana layatgha",
  },
  {
    "verse_number": 7,
    "english_text": "That he imagines himself to be needless.",
    "arabic_text": "اَن رَّاٰهُ اسْتَغْنٰى",
    "urdu_text": "کیونکہ وہ اپنے آپ کو بے نیاز سمجھتا ہے",
    "persian_text": "زیرا که خود را بی‌نیاز می‌بیند",
    "transliteration": "An ra-ahu istaghna",
  },
  {
    "verse_number": 8,
    "english_text": "Verily to your Lord is the return.",
    "arabic_text": "اِنَّ اِلَٰى رَبِّكَ الرُّجْعٰى",
    "urdu_text": "بیشک تیرے رب ہی کی طرف لوٹنا ہے",
    "persian_text": "همانا بازگشت به سوی پروردگار توست",
    "transliteration": "Inna ila rabbika ar-ruj'a",
  },
]
