ayats = [
  {
    "verse_number": 1,
    "english_text": "Mutual competition and abundance of wealth and children have made you negligent.",
    "arabic_text": "اَلْهٰكُمُ التَّكَاثُرُ",
    "urdu_text": "تمہیں کثرت کی طلب نے غافل کر دیا",
    "persian_text": "فزونی‌طلبی شما را غافل کرده است",
    "transliteration": "Alhakumu at-takathur",
  },
  {
    "verse_number": 2,
    "english_text": "Even until you meet your graves.",
    "arabic_text": "حَتّٰى زُرْتُمُ الْمَقَابِرَ",
    "urdu_text": "یہاں تک کہ تم قبروں میں پہنچ گئے",
    "persian_text": "تا آنگاه که به گورستان رفتید",
    "transliteration": "Hatta zurtumu al-maqabir",
  },
  {
    "verse_number": 3,
    "english_text": "Shortly you shall know.",
    "arabic_text": "كَلَّا سَوْفَ تَعْلَمُونَ",
    "urdu_text": "ہرگز نہیں، عنقریب تم جان لو گے",
    "persian_text": "هرگز چنین نیست، به زودی خواهید دانست",
    "transliteration": "Kalla sawfa ta'lamun",
  },
  {
    "verse_number": 4,
    "english_text": "Then you will very well know",
    "arabic_text": "ثُمَّ كَلَّا سَوْفَ تَعْلَمُونَ",
    "urdu_text": "پھر ہرگز نہیں، عنقریب تم ضرور جان لو گے",
    "persian_text": "باز هم هرگز چنین نیست، به زودی خواهید دانست",
    "transliteration": "Thumma kalla sawfa ta'lamun",
  },
  {
    "verse_number": 5,
    "english_text": "See! If you knew for sure.",
    "arabic_text": "كَلَّا لَوْ تَعْلَمُونَ عِلْمَ الْيَقِينِ",
    "urdu_text": "ہرگز نہیں، اگر تم یقینی علم رکھتے",
    "persian_text": "هرگز چنین نیست، اگر با علم یقین می‌دانستید",
    "transliteration": "Kalla law ta'lamuna 'ilma al-yaqin",
  },
  {
    "verse_number": 6,
    "english_text": "That you would surely see Hell;",
    "arabic_text": "لَتَرَوُنَّ الْجَحِيمَ",
    "urdu_text": "تم ضرور جہنم کو دیکھو گے",
    "persian_text": "به یقین جهنم را خواهید دید",
    "transliteration": "Latarawunna al-jaheem",
  },
  {
    "verse_number": 7,
    "english_text": "Then you will see it with your eyes and see it with certainty.",
    "arabic_text": "ثُمَّ لَتَرَوُنَّهَا عَيْنَ الْيَقِينِ",
    "urdu_text": "پھر تم اسے یقینی طور پر اپنی آنکھوں سے دیکھو گے",
    "persian_text": "سپس آن را با چشم یقین خواهید دید",
    "transliteration": "Thumma latarawunnaha 'ayna al-yaqeen",
  },
  {
    "verse_number": 8,
    "english_text": "Then on that day you shall be questioned about the bounties (of Allah).",
    "arabic_text": "ثُمَّ لَتُسْـَٔلُنَّ يَوْمَئِذٍ عَنِ النَّعِيمِ",
    "urdu_text": "پھر اس دن تم سے نعمتوں کے بارے میں ضرور پوچھا جائے گا",
    "persian_text": "سپس در آن روز از نعمت‌ها پرسیده خواهید شد",
    "transliteration": "Thumma latus'alunna yawma'idhin 'an an-na'eem",
  },
]
