ayats = [
  {
    "verse_number": 1,
    "english_text": "The quivering!",
    "arabic_text": "الْقَارِعَةُ",
    "urdu_text": "کھٹکھٹانے والی!",
    "persian_text": "واقعه کوبنده!",
    "transliteration": "Al-Qari'ah",
  },
  {
    "verse_number": 2,
    "english_text": "And such a terrible quivering!",
    "arabic_text": "مَا الْقَارِعَةُ",
    "urdu_text": "کیا هے وه کھٹکھٹانے والی!",
    "persian_text": "چیست آن واقعه کوبنده!",
    "transliteration": "Mal-Qari'ah",
  },
  {
    "verse_number": 3,
    "english_text": "And what will you comprehend how terrible the quivering is?",
    "arabic_text": "وَ مَآ اَدْرٰكَ مَا الْقَارِعَةُ",
    "urdu_text": "اور تمهیں کیا معلوم که وه کھٹکھٹانے والی کیا هے؟",
    "persian_text": "و تو چه می‌دانی که آن واقعه کوبنده چیست؟",
    "transliteration": "Wa ma adraka mal-Qari'ah",
  },
  {
    "verse_number": 4,
    "english_text": "The day on which people shall become like scattered moths.",
    "arabic_text": "يَوْمَ يَكُونُ النَّاسُ كَالْفَرَاشِ الْمَبْثُوثِ",
    "urdu_text": "جس دن لوگ بکھرے هوئے پروانوں کی طرح هوں گے",
    "persian_text": "روزی که مردم همچون پروانه‌های پراکنده خواهند بود",
    "transliteration": "Yawma yakoonun-nasu kal-farashil-mabthooth",
  },
  {
    "verse_number": 5,
    "english_text": "And the mountains shall be flying like beaten cotton.",
    "arabic_text": "وَ تَكُونُ الْجِبَالُ كَالْعِهْنِ الْمَنفُوشِ",
    "urdu_text": "اور پهاڑ دھنکی هوئی رنگین اون کی طرح هوں گے",
    "persian_text": "و کوه‌ها همچون پشم زده شده خواهند بود",
    "transliteration": "Wa takoonul-jibalu kal-'ihnil-manfoosh",
  },
  {
    "verse_number": 6,
    "english_text": "Then that day as for the one whose measure of good deeds will be heavy.",
    "arabic_text": "فَاَمَّا مَن ثَقُلَتْ مَوَازِينُهُ",
    "urdu_text": "پھر جس کے اعمال کا پلڑا بھاری هوگا",
    "persian_text": "پس آن کس که ترازوی اعمالش سنگین باشد",
    "transliteration": "Fa-amma man thaqulat mawazinuhu",
  },
  {
    "verse_number": 7,
    "english_text": "He will be in a pleasing luxury.",
    "arabic_text": "فَهُوَ فِى عِيشَةٍ رَّاضِيَةٍ",
    "urdu_text": "وه خوشگوار زندگی میں هوگا",
    "persian_text": "او در زندگانی خوشایندی خواهد بود",
    "transliteration": "Fahuwa fee 'ishatin radiyah",
  },
  {
    "verse_number": 8,
    "english_text": "And as for him whose measure of deeds will be light.",
    "arabic_text": "وَ اَمَّا مَنْ خَفَّتْ مَوَازِينُهُ",
    "urdu_text": "اور جس کے اعمال کا پلڑا هلکا هوگا",
    "persian_text": "و اما آن کس که ترازوی اعمالش سبک باشد",
    "transliteration": "Wa amma man khaffat mawazinuhu",
  },
  {
    "verse_number": 9,
    "english_text": "Then his center will be ‘Haviya’.",
    "arabic_text": "فَاُمُّهُ هَاوِيَةٌ",
    "urdu_text": "تو اس کا ٹھکانه هاویه هوگا",
    "persian_text": "پس جایگاهش هاویه خواهد بود",
    "transliteration": "Fa-ummuhu hawiyah",
  },
  {
    "verse_number": 10,
    "english_text": "And what will you know what a distress ‘Haviya’ is?",
    "arabic_text": "وَ مَآ اَدْرٰكَ مَا هِيَهْ",
    "urdu_text": "اور تم کیا جانو که وه کیا هے",
    "persian_text": "و تو چه می‌دانی که آن چیست",
    "transliteration": "Wa ma adraka ma hiyah",
  },
  {
    "verse_number": 11,
    "english_text": "This is a raging fire.",
    "arabic_text": "نَارٌ  حَامِيَةٌ",
    "urdu_text": "یه بھڑکتی هوئی آگ هے",
    "persian_text": "آتشی سوزان است",
    "transliteration": "Narun hamiyah",
  },
]
