ayats = [
  {
    "verse_number": 1,
    "english_text": "Did you see the man who denies the Day of Judgement.",
    "arabic_text": "اَرَءَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ",
    "urdu_text": "کیا تم نے اُس شخص کو دیکھا جو روزِ جزا کو جھٹلاتا ہے",
    "persian_text": "آیا دیدی کسی را که روز جزا را تکذیب می‌کند",
    "transliteration": "Ara'ayta allathee yukaththibu bid-deen",
  },
  {
    "verse_number": 2,
    "english_text": "He is the one to treat the orphan with harshness.",
    "arabic_text": "فَذٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ",
    "urdu_text": "پس وہی تو ہے جو یتیم کو دھکے دیتا ہے",
    "persian_text": "پس او همان کسی است که یتیم را با خشونت می‌راند",
    "transliteration": "Fathalika allathee yadu'ul-yateem",
  },
  {
    "verse_number": 3,
    "english_text": "And does not encourage anyone to feed the needy.",
    "arabic_text": "وَ لَا يَحُضُّ عَلَٰى طَعَامِ الْمِسْكِينِ",
    "urdu_text": "اور مسکین کو کھانا کھلانے کی ترغیب نہیں دیتا",
    "persian_text": "و دیگران را بر طعام دادن به مسکین ترغیب نمی‌کند",
    "transliteration": "Wa la yahuddu 'ala ta'amil-miskeen",
  },
  {
    "verse_number": 4,
    "english_text": "So destruction for those people who pray.",
    "arabic_text": "فَوَيْلٌ لِّلْمُصَلِّينَ",
    "urdu_text": "پس ہلاکت ہے ان نماز پڑھنے والوں کے لیے",
    "persian_text": "پس وای بر نمازگزاران",
    "transliteration": "Fa waylul-lil-musalleen",
  },
  {
    "verse_number": 5,
    "english_text": "Those who neglect their prayers.",
    "arabic_text": "الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ",
    "urdu_text": "جو اپنی نماز سے غافل رہتے ہیں",
    "persian_text": "آنان که از نماز خود غافل‌اند",
    "transliteration": "Allatheena hum 'an salatihim sahoon",
  },
  {
    "verse_number": 6,
    "english_text": "And do the deeds for show-off.",
    "arabic_text": "الَّذِينَ هُمْ يُرَآءُونَ",
    "urdu_text": "جو لوگ دکھاوے کے لیے عمل کرتے ہیں",
    "persian_text": "کسانی که ریاکاری می‌کنند",
    "transliteration": "Alladhīna hum yurā'ūn",
  },
  {
    "verse_number": 7,
    "english_text": "And they refuse to lend even the small things (to their neighbors).",
    "arabic_text": "وَ يَمْنَعُونَ الْمَاعُونَ",
    "urdu_text": "اور چھوٹی چھوٹی چیزیں دینے سے بھی انکار کرتے ہیں",
    "persian_text": "و از دادن چیزهای کوچک خودداری می‌کنند",
    "transliteration": "Wa yamna'ūna al-mā'ūn",
  },
]
