ayats = [
  {
    "verse_number": 1,
    "english_text": "I swear by the fig and the olive.",
    "arabic_text": "وَ التِّينِ وَ الزَّيْتُونِ",
    "urdu_text": "قسم ہے انجیر کی اور زیتون کی",
    "persian_text": "سوگند به انجیر و زیتون",
    "transliteration": "Wat-teeni waz-zaytoon",
  },
  {
    "verse_number": 2,
    "english_text": "And by Mount Sinai.",
    "arabic_text": "وَ طُورِ سِينِينَ",
    "urdu_text": "اور طور سینین کی",
    "persian_text": "و قسم به کوه سینا",
    "transliteration": "Wa-toor-i seenin.",
  },
  {
    "verse_number": 3,
    "english_text": "And by this peaceful city.",
    "arabic_text": "وَ هٰذَا الْبَلَدِ الْاَمِينِ",
    "urdu_text": "اور اس امن والے شہر کی",
    "persian_text": "و سوگند به این شهر امن",
    "transliteration": "Wa haazal-baladil-ameen",
  },
  {
    "verse_number": 4,
    "english_text": "We have created the man in the best creation.",
    "arabic_text": "لَقَدْ خَلَقْنَا الْاِنسَانَ فِىٓ اَحْسَنِ تَقْوِيمٍ",
    "urdu_text": "بیشک ہم نے انسان کو بہترین ساخت میں پیدا کیا",
    "persian_text": "به راستی انسان را در بهترین صورت آفریدیم",
    "transliteration": "Laqad khalaqnal-insaana fee ahsani taqweem",
  },
  {
    "verse_number": 5,
    "english_text": "Then We returned him to the lowest position.",
    "arabic_text": "ثُمَّ رَدَدْنٰهُ اَسْفَلَ سَافِلِينَ",
    "urdu_text": "پھر ہم نے اسے پست ترین حالت میں پہنچا دیا",
    "persian_text": "سپس او را به پست‌ترین مرتبه بازگرداندیم",
    "transliteration": "Thumma radadnaahu asfala saafileen",
  },
  {
    "verse_number": 6,
    "english_text": "Except those who believed, and they performed the good deeds, so they shall have a never-ending reward.",
    "arabic_text": "اِلَّا الَّذِينَ اٰمَنُوا وَ عَمِلُوا الصّٰلِحٰتِ فَلَهُمْ اَجْرٌ غَيْرُ مَمْنُونٍ",
    "urdu_text": "سوائے ان لوگوں کے جو ایمان لائے اور نیک اعمال کیے، تو ان کے لیے ایسا اجر ہے جو کبھی ختم نہیں ہوگا",
    "persian_text": "مگر کسانی که ایمان آوردند و کارهای شایسته انجام دادند، پس برای آنان پاداشی است که هرگز قطع نخواهد شد",
    "transliteration": "Illal-lazeena aamanoo wa 'amilus-saalihaati falahum ajrun ghayru mamnoon",
  },
  {
    "verse_number": 7,
    "english_text": "Then who can believe you about the Day of Judgment?",
    "arabic_text": "فَمَا يُكَذِّبُكَ بَعْدُ بِالدِّينِ",
    "urdu_text": "پھر اس کے بعد کون تمہیں روزِ جزا کے بارے میں جھٹلاتا ہے",
    "persian_text": "پس چه چیزی تو را بعد از این درباره روز جزا تکذیب می‌کند",
    "transliteration": "Famaa yukazzibu ka ba'du bid-deen",
  },
  {
    "verse_number": 8,
    "english_text": "Is Allah not the greatest of the Rulers and the one who judges.",
    "arabic_text": "اَلَيْسَ اللّٰهُ بِاَحْكَمِ الْحٰكِمِينَ",
    "urdu_text": "کیا اللہ سب حاکموں سے بڑا حاکم اور فیصلہ کرنے والا نہیں ہے",
    "persian_text": "آیا خداوند حکیم‌ترین حاکمان نیست",
    "transliteration": "Alaysal-laahu bi-ahkamil-haakimeen",
  },
]
