ayats = [
  {
    "verse_number": 1,
    "english_text": "I swear by the sky and visitor of the night.",
    "arabic_text": "وَ السَّمَآءِ وَ الطَّارِقِ",
    "urdu_text": "قسم ہے آسمان کی اور رات کو آنے والے کی",
    "persian_text": "سوگند به آسمان و ستاره شب‌آینده",
    "transliteration": "Was-samaaa'i wat-taariq",
  },
  {
    "verse_number": 2,
    "english_text": "And - What do you know - what is the visitor of night?",
    "arabic_text": "وَ مَآ اَدْرٰكَ مَا الطَّارِقُ",
    "urdu_text": "اور تمہیں کیا معلوم کہ رات کو آنے والا کیا ہے؟",
    "persian_text": "و تو چه می‌دانی که ستاره شب‌آینده چیست؟",
    "transliteration": "Wa maaa adraaka mat-taariq",
  },
  {
    "verse_number": 3,
    "english_text": "This is the brightest star.",
    "arabic_text": "النَّجْمُ الثَّاقِبُ",
    "urdu_text": "وہ چمکتا ہوا ستارہ ہے",
    "persian_text": "ستاره‌ای درخشان و نافذ",
    "transliteration": "An-najmuth-thaaqib",
  },
  {
    "verse_number": 4,
    "english_text": "There is no soul on which the watcher is not appointed.",
    "arabic_text": "اِن كُلُّ نَفْسٍ لَّمَّا عَلَيْهَا حَافِظٌ",
    "urdu_text": "کوئی جان ایسی نہیں جس پر نگہبان مقرر نہ ہو",
    "persian_text": "هیچ جانی نیست مگر آنکه نگهبانی بر او گماشته شده است",
    "transliteration": "In kullu nafsin lammaa 'alaihaa haafiz",
  },
  {
    "verse_number": 5,
    "english_text": "Then man should see from what thing he has been created from.",
    "arabic_text": "فَلْيَنظُرِ الْاِنسَانُ مِمَّ خُلِقَ",
    "urdu_text": "تو انسان کو دیکھنا چاہیے کہ وہ کس چیز سے پیدا کیا گیا ہے",
    "persian_text": "پس انسان باید بنگرد که از چه چیز آفریده شده است",
    "transliteration": "Falyanzuril-insaanu mimma khuliq",
  },
  {
    "verse_number": 6,
    "english_text": "He has been created from the bouncing water.",
    "arabic_text": "خُلِقَ مِن مَّآءٍ دَافِقٍ",
    "urdu_text": "وہ اچھلتے ہوئے پانی سے پیدا کیا گیا ہے",
    "persian_text": "از آبی جهنده آفریده شده است",
    "transliteration": "Khuliqa min ma'in dafiq",
  },
  {
    "verse_number": 7,
    "english_text": "Which comes out from between the bones of the back and chest.",
    "arabic_text": "يَخْرُجُ مِن بَيْنِ الصُّلْبِ وَ التَّرَآئِبِ",
    "urdu_text": "جو پیٹھ کی ہڈی اور سینے کی ہڈیوں کے درمیان سے نکلتا ہے",
    "persian_text": "که از میان ستون فقرات و استخوان‌های سینه بیرون می‌آید",
    "transliteration": "Yakhruju min baynis-sulbi wat-tara'ib",
  },
  {
    "verse_number": 8,
    "english_text": "Verily, that Allah is also capable to raise the man again.",
    "arabic_text": "اِنَّهُ عَلَٰى رَجْعِهِ لَقَادِرٌ",
    "urdu_text": "بیشک اللہ اسے دوبارہ زندہ کرنے پر قادر ہے",
    "persian_text": "به راستی که او بر بازگرداندن انسان قادر است",
    "transliteration": "Innahu 'ala raj'ihi laqadir",
  },
  {
    "verse_number": 9,
    "english_text": "When the secrets will be tested.",
    "arabic_text": "يَوْمَ تُبْلَى السَّرَآئِرُ",
    "urdu_text": "جس دن تمام بھیدوں کی جانچ ہوگی",
    "persian_text": "روزی که رازها آزموده خواهند شد",
    "transliteration": "Yawma tublas-sara'ir",
  },
  {
    "verse_number": 10,
    "english_text": "Then no one will have strength nor helper.",
    "arabic_text": "فَمَا لَهُ مِن قُوَّةٍ وَ لَا نَاصِرٍ",
    "urdu_text": "تو نہ اس کے پاس کوئی طاقت ہوگی اور نہ کوئی مددگار",
    "persian_text": "پس نه قدرتی خواهد داشت و نه یاوری",
    "transliteration": "Fama lahu min quwwatin wa la nasir",
  },
  {
    "verse_number": 11,
    "english_text": "Swear by the swiveling sky.",
    "arabic_text": "وَ السَّمَآءِ ذَاتِ الرَّجْعِ",
    "urdu_text": "قسم ہے آسمان کی جو بار بار لوٹتا ہے",
    "persian_text": "سوگند به آسمان بازگشت کننده",
    "transliteration": "Was-samaaa'i zaatir-raj'",
  },
  {
    "verse_number": 12,
    "english_text": "And by the splitting earth.",
    "arabic_text": "وَ الْاَرْضِ ذَاتِ الصَّدْعِ",
    "urdu_text": "اور زمین کی جو پھٹتی ہے",
    "persian_text": "و سوگند به زمین شکافنده",
    "transliteration": "Wal-ardi zaatis-sad'",
  },
  {
    "verse_number": 13,
    "english_text": "Verily it is a decisive word.",
    "arabic_text": "اِنَّهُ لَقَوْلٌ فَصْلٌ",
    "urdu_text": "بیشک یہ فیصلہ کن بات ہے",
    "persian_text": "به راستی این سخنی قاطع و جدا کننده است",
    "transliteration": "Innahu laqawlun fasl",
  },
  {
    "verse_number": 14,
    "english_text": "And not a joke.",
    "arabic_text": "وَ مَا هُوَ بِالْهَزْلِ",
    "urdu_text": "اور یہ کوئی مذاق نہیں ہے",
    "persian_text": "و این هیچ شوخی نیست",
    "transliteration": "Wa maa huwa bil-hazl",
  },
  {
    "verse_number": 15,
    "english_text": "These people are doing their planning.",
    "arabic_text": "اِنَّهُمْ يَكِيدُونَ كَيْدًا",
    "urdu_text": "بیشک یہ لوگ اپنی چالیں چل رہے ہیں",
    "persian_text": "به راستی آنان نقشه‌ای می‌کشند",
    "transliteration": "Innahum yakeedoona kaydaa",
  },
  {
    "verse_number": 16,
    "english_text": "And We are doing Our planning.",
    "arabic_text": "وَ اَكِيدُ كَيْدًا",
    "urdu_text": "اور میں بھی اپنی تدبیر کر رہا ہوں",
    "persian_text": "و من نیز تدبیر می‌کنم",
    "transliteration": "Wa akeedu kayda",
  },
  {
    "verse_number": 17,
    "english_text": "So, leave infidels and give them some respite.",
    "arabic_text": "فَمَهِّلِ الْكٰفِرِينَ اَمْهِلْهُمْ رُوَيْدًا",
    "urdu_text": "پس کافروں کو مہلت دو، انہیں تھوڑی دیر ڈھیل دے دو",
    "persian_text": "پس کافران را مهلت ده، آنان را اندکی فرصت بده",
    "transliteration": "Famahhilil kaafireena amhilhum ruwayda",
  },
]
