ayats = [
  {
    "verse_number": 1,
    "english_text": "When the sky will rend asunder.",
    "arabic_text": "اِذَا السَّمَآءُ انفَطَرَتْ",
    "urdu_text": "جب آسمان پھٹ جائے گا",
    "persian_text": "هنگامی که آسمان شکافته شود",
    "transliteration": "Izas-samaaa'un-fatarat",
  },
  {
    "verse_number": 2,
    "english_text": "And when the stars will be scattered.",
    "arabic_text": "وَ اِذَا الْكَوَاكِبُ انْتَثَرَتْ",
    "urdu_text": "اور جب ستارے بکھر جائیں گے",
    "persian_text": "و هنگامی که ستارگان پراکنده شوند",
    "transliteration": "Wa izal-kawaakibun-tatharat",
  },
  {
    "verse_number": 3,
    "english_text": "And when the oceans will mix with each other.",
    "arabic_text": "وَ اِذَا الْبِحَارُ فُجِّرَتْ",
    "urdu_text": "اور جب سمندر پھاڑ دیے جائیں گے",
    "persian_text": "و هنگامی که دریاها به هم ریخته شوند",
    "transliteration": "Wa izal-bihaaru fujjirat",
  },
  {
    "verse_number": 4,
    "english_text": "And when graves will be laid open.",
    "arabic_text": "وَ اِذَا الْقُبُورُ بُعْثِرَتْ",
    "urdu_text": "اور جب قبریں کھود ڈالی جائیں گی",
    "persian_text": "و هنگامی که گورها برانگیخته شوند",
    "transliteration": "Wa izal-qubooru bu'thirat",
  },
  {
    "verse_number": 5,
    "english_text": "Then every Self will know what it has sent before and what was left behind.",
    "arabic_text": "عَلِمَتْ نَفْسٌ مَّا قَدَّمَتْ وَ اَخَّرَتْ",
    "urdu_text": "تو ہر شخص جان لے گا جو اس نے آگے بھیجا اور جو پیچھے چھوڑا",
    "persian_text": "آنگاه هر کسی خواهد دانست چه پیش فرستاده و چه پس انداخته است",
    "transliteration": "Alimat nafsun maa qaddamat wa akhkharat",
  },
  {
    "verse_number": 6,
    "english_text": "O man, what has deceived you about the Gracious Lord?",
    "arabic_text": "يٰٓاَيُّهَا الْاِنسَـانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيمِ",
    "urdu_text": "اے انسان! کس چیز نے تجھے اپنے رب کریم کے بارے میں دھوکے میں ڈال دیا؟",
    "persian_text": "ای انسان! چه چیزی تو را نسبت به پروردگار بزرگوار خود فریفته ساخت؟",
    "transliteration": "Ya ayyuhal insanu ma gharraka bi rabbikal kareem",
  },
  {
    "verse_number": 7,
    "english_text": "He created you, perfected you and then balanced you.",
    "arabic_text": "الَّذِى خَلَقَكَ فَسَوّٰكَ فَعَدَلَكَ",
    "urdu_text": "جس نے تجھے پیدا کیا، پھر تجھے درست کیا، پھر تجھے متناسب بنایا",
    "persian_text": "همان که تو را آفرید، سپس تو را متناسب ساخت و سپس تو را متعادل گردانید",
    "transliteration": "Allazi khalaqaka fasawwaka fa'adalak",
  },
  {
    "verse_number": 8,
    "english_text": "He constituted your (body) parts as he pleases.",
    "arabic_text": "فِىٓ اَىِّ صُورَةٍ مَّا شَآءَ رَكَّبَكَ",
    "urdu_text": "جس صورت میں چاہا تجھے ترکیب دیا",
    "persian_text": "تو را در هر صورتی که خواست ترکیب داد",
    "transliteration": "Fi ayyi sooratin ma sha'a rakkabak",
  },
  {
    "verse_number": 9,
    "english_text": "But you people deny the reward (Day of Judgement).",
    "arabic_text": "كَلَّا بَلْ تُكَذِّبُونَ بِالدِّينِ",
    "urdu_text": "ہرگز نہیں! بلکہ تم لوگ جزا و سزا کو جھٹلاتے ہو",
    "persian_text": "هرگز چنین نیست! بلکه شما روز جزا را تکذیب می‌کنید",
    "transliteration": "Kalla bal tukazziboona bid deen",
  },
  {
    "verse_number": 10,
    "english_text": "And verily there are guards over your heads.",
    "arabic_text": "وَ اِنَّ عَلَيْكُمْ لَحٰفِظِينَ",
    "urdu_text": "اور بیشک تم پر نگہبان مقرر ہیں",
    "persian_text": "و به راستی بر شما نگهبانانی گمارده شده‌اند",
    "transliteration": "Wa inna 'alaykum lahafizeen",
  },
  {
    "verse_number": 11,
    "english_text": "Who are honorable recorders.",
    "arabic_text": "كِرَامًا كَاتِبِيْنَ",
    "urdu_text": "جو معزز لکھنے والے ہیں",
    "persian_text": "که نویسندگان گرامی هستند",
    "transliteration": "Kiraman katibeen",
  },
  {
    "verse_number": 12,
    "english_text": "They know your deeds well.",
    "arabic_text": "يَعْلَمُونَ مَا تَفْعَلُونَ",
    "urdu_text": "وہ جانتے ہیں جو کچھ تم کرتے ہو",
    "persian_text": "آنها می‌دانند آنچه را که شما انجام می‌دهید",
    "transliteration": "Ya'lamoona ma taf'aloon",
  },
  {
    "verse_number": 13,
    "english_text": "Verily, righteous people will be in bliss.",
    "arabic_text": "اِنَّ الْاَبْرَارَ لَفِى نَعِيمٍ",
    "urdu_text": "بیشک نیک لوگ نعمتوں میں ہوں گے",
    "persian_text": "به راستی نیکوکاران در نعمت خواهند بود",
    "transliteration": "Innal abrara lafee na'eem",
  },
  {
    "verse_number": 14,
    "english_text": "And wicked people will be in Hell.",
    "arabic_text": "وَ اِنَّ الْفُجَّارَ لَفِى جَحِيمٍ",
    "urdu_text": "اور بدکار لوگ دوزخ میں ہوں گے",
    "persian_text": "و همانا بدکاران در دوزخ خواهند بود",
    "transliteration": "Wa innal fujjara lafee jaheem",
  },
  {
    "verse_number": 15,
    "english_text": "They will be thrown into it (Hell) on the Day of Judgement.",
    "arabic_text": "يَصْلَوْنَهَا يَوْمَ الدِّينِ",
    "urdu_text": "وہ روز جزا میں اس میں داخل ہوں گے",
    "persian_text": "آنها در روز جزا در آن وارد خواهند شد",
    "transliteration": "Yaslawnaha yawmad deen",
  },
  {
    "verse_number": 16,
    "english_text": "And they cannot escape it.",
    "arabic_text": "وَ مَا هُمْ عَنْهَا بِغَآئِبِينَ",
    "urdu_text": "اور وہ اس سے بچ نہیں سکتے",
    "persian_text": "و آنان نمی‌توانند از آن دور شوند",
    "transliteration": "Wa ma hum 'anha bigha'ibeen",
  },
  {
    "verse_number": 17,
    "english_text": "And what do you know what the day of recompense is?",
    "arabic_text": "وَ مَآ اَدْرٰكَ مَا يَوْمُ الدِّينِ",
    "urdu_text": "اور تم کیا جانو کہ جزا کا دن کیا ہے؟",
    "persian_text": "و تو چه می‌دانی که روز جزا چیست؟",
    "transliteration": "Wa ma adraka ma yawmud-deen",
  },
  {
    "verse_number": 18,
    "english_text": "Then what do you know how the day of recompense is?",
    "arabic_text": "ثُمَّ مَآ اَدْرٰكَ مَا يَوْمُ الدِّينِ",
    "urdu_text": "پھر تم کیا جانو کہ جزا کا دن کیسا ہے؟",
    "persian_text": "باز تو چه می‌دانی که روز جزا چگونه است؟",
    "transliteration": "Thumma ma adraka ma yawmud-deen",
  },
  {
    "verse_number": 19,
    "english_text": "That day, no one will have any authority over anyone, all control will be in the hands of Allah.",
    "arabic_text": "يَوْمَ لَا تَمْلِكُ نَفْسٌ لِّنَفْسٍ شَيْئًا ۖ وَ الْاَمْرُ يَوْمَئِذٍ لِّلّٰهِ",
    "urdu_text": "وہ دن جب کوئی کسی کے لیے کچھ اختیار نہیں رکھے گا، اور اس دن تمام اختیار اللہ کے ہاتھ میں ہوگا",
    "persian_text": "روزی که هیچ کس برای دیگری اختیاری نخواهد داشت و فرمان آن روز از آنِ خداست",
    "transliteration": "Yawma la tamliku nafsul linafsin shay'an wal-amru yawma'idhin lillah",
  },
]
