ayats = [
  {
    "verse_number": 1,
    "english_text": "Did not you see what your Lord did to the companions of the Elephant?",
    "arabic_text": "اَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِاَصْحٰبِ الْفِيلِ",
    "urdu_text": "کیا تم نے نہیں دیکھا کہ تمہارے رب نے ہاتھی والوں کے ساتھ کیا کیا؟",
    "persian_text": "آیا ندیدی که پروردگارت با اصحاب فیل چه کرد؟",
    "transliteration": "Alam tara kayfa fa'ala rabbuka bi-as'habil-fil",
  },
  {
    "verse_number": 2,
    "english_text": "Did not He foil their plan?",
    "arabic_text": "اَلَمْ يَجْعَلْ كَيْدَهُمْ فِى تَضْلِيلٍ",
    "urdu_text": "کیا اس نے ان کی چال کو ناکام نہیں کر دیا؟",
    "persian_text": "آیا نقشه آنان را نابود نساخت؟",
    "transliteration": "Alam yaj'al kaydahum fee tadleel",
  },
  {
    "verse_number": 3,
    "english_text": "And sent upon them flocks of flying ababeel, (birds).",
    "arabic_text": "وَّ اَرْسَلَ عَلَيْهِمْ طَيْرًا اَبَابِيلَ",
    "urdu_text": "اور ان پر جھنڈ کے جھنڈ پرندے بھیجے",
    "persian_text": "و بر آنان پرندگانی دسته دسته فرستاد",
    "transliteration": "Wa arsala 'alayhim tayran ababeel",
  },
  {
    "verse_number": 4,
    "english_text": "Which showered upon them the stones of baked clay.",
    "arabic_text": "تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ",
    "urdu_text": "جو ان پر کنکریلے پتھر مارتے تھے",
    "persian_text": "که سنگ‌های گِلی بر آنان می‌انداختند",
    "transliteration": "Tarmeehim bi-hijaratin min sijjeel",
  },
  {
    "verse_number": 5,
    "english_text": "Then it made them like chewed straw.",
    "arabic_text": "فَجَعَلَهُمْ كَعَصْفٍ مَّاْكُولٍ",
    "urdu_text": "پھر اللہ نے انہیں کھائے ہوئے بھوسے کی طرح کر دیا",
    "persian_text": "پس آنان را همچون کاه خورده شده گردانید",
    "transliteration": "Fa-ja'alahum ka-'asfin ma'kool",
  },
]
