ayats = [
    {
        "arabic_text": "الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ",
        "urdu_text": "الف، لام، را۔ یہ واضح کتاب کی آیات ہیں۔",
        "persian_text": "الف، لام، را؛ اینها آیات کتاب روشن‌اند.",
        "english_text": "Alif, Lam, Ra. These are the verses of the clear Book.",
        "transliteration": "Alif Lām Rā; tilka āyātu al-kitābi al-mubeen",
        "verse_number": "1",
    },
    {
        "arabic_text": "إِنَّا أَنزَلْنَاهُ قُرْآنًا عَرَبِيًّا لَّعَلَّكُمْ تَعْقِلُونَ",
        "urdu_text": "بے شک ہم نے اسے عربی قرآن بنا کر نازل کیا ہے تاکہ تم سمجھو۔",
        "persian_text": "بی‌گمان ما آن را قرآنی عربی فرو فرستادیم تا شاید بیندیشید.",
        "english_text": "Indeed, We have sent it down as an Arabic Qur'an so that you may understand.",
        "transliteration": "Innā anzalnāhu qur’ānan ʿarabiyyan laʿallakum taʿqiloon",
        "verse_number": "2",
    },
    {
        "arabic_text": "نَحْنُ نَقُصُّ عَلَيْكَ أَحْسَنَ الْقَصَصِ بِمَا أَوْحَيْنَا إِلَيْكَ هَٰذَا الْقُرْآنَ وَإِن كُنتَ مِن قَبْلِهِ لَمِنَ الْغَافِلِينَ",
        "urdu_text": "ہم تمہیں بہترین قصہ سناتے ہیں اس قرآن کے ذریعہ جو ہم نے تمہاری طرف وحی کیا ہے، حالانکہ اس سے پہلے تم بے خبر لوگوں میں سے تھے۔",
        "persian_text": "ما بر تو نیکوترین داستان را به‌وسیله این قرآن که به تو وحی کردیم بازگو می‌کنیم، در حالی که پیش از آن از بی‌خبران بودی.",
        "english_text": "We relate to you the best of stories through Our revelation of this Qur'an, although you were, before it, among the unaware.",
        "transliteration": "Naḥnu naquṣṣu ʿalayka aḥsana al-qaṣaṣi bimā awḥaynā ilayka hādhā al-qur’ān; wa in kunta min qablihi lamina al-ghāfileen",
        "verse_number": "3",
    },
    {
        "arabic_text": "إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَا أَبَتِ إِنِّي رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا وَالشَّمْسَ وَالْقَمَرَ رَأَيْتُهُمْ لِي سَاجِدِينَ",
        "urdu_text": "جب یوسفؑ نے اپنے باپ سے کہا، ابا جان! میں نے خواب میں گیارہ ستاروں کو اور سورج اور چاند کو دیکھا کہ وہ مجھے سجدہ کر رہے ہیں۔",
        "persian_text": "آنگاه که یوسف به پدرش گفت: ای پدر من! در خواب دیدم یازده ستاره و خورشید و ماه را که مرا سجده می‌کنند.",
        "english_text": "When Joseph said to his father, 'O my father! Indeed I have seen eleven stars and the sun and the moon; I saw them prostrating to me.'",
        "transliteration": "Idh qāla Yoosufu li-abīhi yā abati innī ra’aytu aḥada ʿashara kawkaban wash-shamsa wal-qamara ra’aytuhum lī sājideen",
        "verse_number": "4",
    },
    {
        "arabic_text": "قَالَ يَا بُنَيَّ لَا تَقْصُصْ رُؤْيَاكَ عَلَىٰ إِخْوَتِكَ فَيَكِيدُوا لَكَ كَيْدًا ۖ إِنَّ الشَّيْطَانَ لِلْإِنسَانِ عَدُوٌّ مُّبِينٌ",
        "urdu_text": "اس نے کہا، اے میرے بیٹے! اپنا خواب اپنے بھائیوں سے بیان نہ کرنا ورنہ وہ تیرے خلاف کوئی چال چلیں گے، بے شک شیطان انسان کا کھلا دشمن ہے۔",
        "persian_text": "گفت: ای پسرکم! رؤیای خود را برای برادرانت بازگو مکن، که برایت نیرنگی خواهند ساخت؛ چرا که شیطان برای انسان دشمنی آشکار است.",
        "english_text": "He said, 'O my son! Do not relate your vision to your brothers or they will contrive a plot against you. Indeed Satan, to man, is a manifest enemy.'",
        "transliteration": "Qāla yā bunayya lā taqṣuṣ ru’yāka ʿalā ikhwatika faya’keedoo laka kaydā; inna ash-shayṭāna lil-insāni ʿaduwwun mubeen",
        "verse_number": "5",
    },
    {
        "arabic_text": "وَكَذَٰلِكَ يَجْتَبِيكَ رَبُّكَ وَيُعَلِّمُكَ مِن تَأْوِيلِ الْأَحَادِيثِ وَيُتِمُّ نِعْمَتَهُ عَلَيْكَ وَعَلَىٰ آلِ يَعْقُوبَ كَمَا أَتَمَّهَا عَلَىٰ أَبَوَيْكَ مِن قَبْلُ إِبْرَاهِيمَ وَإِسْحَاقَ ۚ إِنَّ رَبَّكَ عَلِيمٌ حَكِيمٌ",
        "urdu_text": "اور اسی طرح تیرا رب تجھے منتخب کرے گا اور تجھے خوابوں کی تعبیر سکھائے گا اور اپنی نعمت تجھ پر اور یعقوبؑ کے گھرانے پر پوری کرے گا، جیسے اس نے تیرے باپ دادا ابراہیمؑ اور اسحاقؑ پر پوری کی تھی، بے شک تیرا رب علم والا، حکمت والا ہے۔",
        "persian_text": "و بدین‌گونه پروردگارت تو را برمی‌گزیند و از تعبیر خواب‌ها به تو می‌آموزد، و نعمت خود را بر تو و خاندان یعقوب تمام می‌گرداند، چنان‌که پیش‌تر بر پدرانت ابراهیم و اسحاق تمام کرد؛ بی‌گمان پروردگارت دانا و حکیم است.",
        "english_text": "And thus will your Lord choose you and teach you the interpretation of narratives and complete His favor upon you and upon the family of Jacob, as He completed it upon your forefathers, Abraham and Isaac. Indeed, your Lord is Knowing and Wise.",
        "transliteration": "Wa kadhalika yajtabīka rabbuka wa yuʿallimuka min ta’wīlil-aḥādeeth wa yutim’u niʿmatahu ʿalayka wa ʿalā āli Yaʿqoob kamā atammuhā ʿalā abawayka min qablu Ibrāhīma wa Isḥāqa; inna rabbaka ʿaleemun ḥakeem",
        "verse_number": "6",
    },
    {
        "arabic_text": "لَّقَدْ كَانَ فِي يُوسُفَ وَإِخْوَتِهِ آيَاتٌ لِّلسَّائِلِينَ",
        "urdu_text": "یقیناً یوسف اور اس کے بھائیوں کے واقعہ میں پوچھنے والوں کے لیے نشانیاں ہیں۔",
        "persian_text": "بی‌گمان در داستان یوسف و برادرانش نشانه‌هایی است برای پرسشگران.",
        "english_text": "Certainly were there in Joseph and his brothers signs for those who ask.",
        "transliteration": "Laqad kāna fī Yoosufa wa ikhwatihi āyātun lis-sā’ileen",
        "verse_number": "7",
    },
    {
        "arabic_text": "إِذْ قَالُوا لَيُوسُفُ وَأَخُوهُ أَحَبُّ إِلَىٰ أَبِينَا مِنَّا وَنَحْنُ عُصْبَةٌ ۖ إِنَّ أَبَانَا لَفِي ضَلَالٍ مُّبِينٍ",
        "urdu_text": "جب انہوں نے کہا، یوسف اور اس کا بھائی ہمارے باپ کو ہم سے زیادہ محبوب ہیں حالانکہ ہم طاقتور جماعت ہیں۔ بے شک ہمارا باپ صریح گمراہی میں ہے۔",
        "persian_text": "آنگاه که گفتند: یوسف و برادرش نزد پدرمان از ما محبوب‌ترند، در حالی که ما گروهی نیرومندیم؛ به‌راستی پدرمان در گمراهی آشکاری است.",
        "english_text": "When they said, 'Joseph and his brother are more beloved to our father than we, while we are a strong group. Indeed, our father is in clear error.'",
        "transliteration": "Idh qālū laYoosufu wa akhoohu aḥabbu ilā abīnā minnā wa naḥnu ʿuṣbah; inna abānā lafee ḍalālin mubeen",
        "verse_number": "8",
    },
    {
        "arabic_text": "اقْتُلُوا يُوسُفَ أَوِ اطْرَحُوهُ أَرْضًا يَخْلُ لَكُمْ وَجْهُ أَبِيكُمْ وَتَكُونُوا مِن بَعْدِهِ قَوْمًا صَالِحِينَ",
        "urdu_text": "یوسف کو قتل کر دو یا اسے کسی زمین میں پھینک دو تاکہ تمہارے باپ کا دھیان صرف تمہاری طرف رہے، اور اس کے بعد تم نیک لوگ بن جانا۔",
        "persian_text": "یوسف را بکشید یا او را به سرزمینی بیندازید تا روی پدرتان فقط به سوی شما گردد، و پس از آن مردمی نیکو باشید.",
        "english_text": "Kill Joseph or cast him out to some land; the favor of your father will then be yours, and you will be after that a righteous people.",
        "transliteration": "Uqtulū Yoosufa aw iṭraḥūhu arḍan yakhlu lakum wajhu abīkum watakūnoo min baʿdihi qawman ṣāliheen",
        "verse_number": "9",
    },
    {
        "arabic_text": "قَالَ قَائِلٌ مِّنْهُمْ لَا تَقْتُلُوا يُوسُفَ وَأَلْقُوهُ فِي غَيَابَتِ الْجُبِّ يَلْتَقِطْهُ بَعْضُ السَّيَّارَةِ إِن كُنتُمْ فَاعِلِينَ",
        "urdu_text": "ان میں سے ایک نے کہا، یوسف کو قتل نہ کرو بلکہ اگر تم کچھ کرنا ہی چاہتے ہو تو اسے کسی کنوئیں کی گہرائی میں ڈال دو، کوئی قافلہ اُسے اٹھا لے جائے گا۔",
        "persian_text": "یکی از آنان گفت: یوسف را مکشید، بلکه اگر می‌خواهید کاری کنید، او را در ژرفای چاه بیفکنید تا کاروانی او را بردارد، اگر واقعاً می‌خواهید کاری بکنید.",
        "english_text": "One of them said, 'Do not kill Joseph but throw him into the bottom of the well; some travelers may pick him up, if you must do something.'",
        "transliteration": "Qāla qā’ilun minhum lā taqtulū Yoosufa wa alqūhu fī ghayābati al-jubb, yaltaqiṭhu ba‘ḍu as-sayyārah in kuntum fā‘ileen",
        "verse_number": "10",
    },
    {
        "arabic_text": "قَالُوا يَا أَبَانَا مَا لَكَ لَا تَأْمَنَّا عَلَىٰ يُوسُفَ وَإِنَّا لَهُ لَنَاصِحُونَ",
        "urdu_text": "انہوں نے کہا، اے ہمارے ابا! آپ کو کیا ہوا ہے کہ آپ ہم پر یوسف کے بارے میں اعتماد نہیں کرتے، حالانکہ ہم تو اس کے خیرخواہ ہیں۔",
        "persian_text": "گفتند: ای پدر ما! چرا بر یوسف ما را امین نمی‌دانی؟ و ما خیرخواه اوییم.",
        "english_text": "They said, 'O our father! Why do you not trust us with Joseph, while indeed we are his sincere well-wishers?'",
        "transliteration": "Qālū yā abānā mā laka lā ta’mannā ʿalā Yoosufa wa innā lahu lanaṣiḥūn",
        "verse_number": "11",
    },
    {
        "arabic_text": "أَرْسِلْهُ مَعَنَا غَدًا يَرْتَعْ وَيَلْعَبْ وَإِنَّا لَهُ لَحَافِظُونَ",
        "urdu_text": "کل اسے ہمارے ساتھ بھیج دیجیے، وہ خوش ہو جائے گا اور کھیلے گا، اور ہم یقیناً اس کے محافظ ہیں۔",
        "persian_text": "فردا او را با ما بفرست تا خوش بگذراند و بازی کند، و ما یقیناً نگهبان او خواهیم بود.",
        "english_text": "Send him with us tomorrow so he may enjoy himself and play, and indeed, we will surely be his guardians.",
        "transliteration": "Arsilhu ma‘anā ghadan yarta‘ wa yal‘ab wa innā lahu laḥāfiẓūn",
        "verse_number": "12",
    },
    {
        "arabic_text": "قَالَ إِنِّي لَيَحْزُنُنِي أَن تَذْهَبُوا بِهِ وَأَخَافُ أَن يَأْكُلَهُ الذِّئْبُ وَأَنتُمْ عَنْهُ غَافِلُونَ",
        "urdu_text": "اس نے کہا، مجھے یہ غم ہے کہ تم اسے لے جاؤ، اور ڈرتا ہوں کہ کہیں اسے بھیڑیا نہ کھا جائے جب تم اس کی طرف سے غافل ہو جاؤ۔",
        "persian_text": "گفت: مرا اندوهگین می‌کند که او را ببرید، و می‌ترسم که گرگ او را بخورد، در حالی که شما از او غافل باشید.",
        "english_text": "He said, 'Indeed, it saddens me that you should take him, and I fear that a wolf would eat him while you are unaware of him.'",
        "transliteration": "Qāla innī la-yaḥzununi an tadhhabū bihi wa akhāfu an ya’kulahu adh-dhi’bu wa antum ‘anhu ghāfilūn",
        "verse_number": "13",
    },
    {
        "arabic_text": "قَالُوا لَئِنْ أَكَلَهُ الذِّئْبُ وَنَحْنُ عُصْبَةٌ إِنَّا إِذًا لَّخَاسِرُونَ",
        "urdu_text": "انہوں نے کہا، اگر اسے بھیڑیا کھا جائے جبکہ ہم ایک مضبوط جماعت ہیں تو پھر تو ہم بڑے نقصان اٹھانے والے ہوں گے۔",
        "persian_text": "گفتند: اگر گرگ او را بخورد در حالی که ما گروهی نیرومندیم، آنگاه ما زیانکار خواهیم بود.",
        "english_text": "They said, 'If a wolf should eat him while we are a strong group, then indeed we would be losers.'",
        "transliteration": "Qālū la’in akalahu adh-dhi’bu wa naḥnu ʿuṣbah, innā idhan lakhāsirūn",
        "verse_number": "14",
    },
    {
        "arabic_text": "فَلَمَّا ذَهَبُوا بِهِ وَأَجْمَعُوا أَن يَجْعَلُوهُ فِي غَيَابَتِ الْجُبِّ وَأَوْحَيْنَا إِلَيْهِ لَتُنَبِّئَنَّهُم بِأَمْرِهِمْ هَٰذَا وَهُمْ لَا يَشْعُرُونَ",
        "urdu_text": "پھر جب وہ اسے لے گئے اور طے کر لیا کہ اسے کنوئیں کی گہرائی میں ڈال دیں، ہم نے یوسف کو وحی کی کہ ایک دن تو انہیں ان کے اس کام کی خبر دے گا اور وہ (ابھی) شعور نہیں رکھتے۔",
        "persian_text": "پس چون او را بردند و همداستان شدند تا او را در ژرفای چاه افکنند، به او وحی کردیم که بی‌گمان روزی آنان را از این کارشان آگاه خواهی ساخت، در حالی که آنان نمی‌دانند.",
        "english_text": "So when they took him and agreed to put him into the bottom of the well, We inspired him: 'You will surely inform them of this affair of theirs while they do not perceive.'",
        "transliteration": "Falammā dhahabū bihi wa ajma‘ū an yaj‘alūhu fī ghayābati al-jubb wa awḥaynā ilayhi latunabbi’annahum bi amrihim hādhā wa hum lā yash‘urūn",
        "verse_number": "15",
    },
    {
        "arabic_text": "وَجَاءُوا أَبَاهُمْ عِشَاءً يَبْكُونَ",
        "urdu_text": "اور وہ رات کے وقت اپنے باپ کے پاس روتے ہوئے آئے۔",
        "persian_text": "و شبانگاه نزد پدرشان گریان آمدند.",
        "english_text": "And they came to their father at night, weeping.",
        "transliteration": "Wa jā’ū abāhum ‘ishā’an yabkūn",
        "verse_number": "16",
    },
    {
        "arabic_text": "قَالُوا يَا أَبَانَا إِنَّا ذَهَبْنَا نَسْتَبِقُ وَتَرَكْنَا يُوسُفَ عِندَ مَتَاعِنَا فَأَكَلَهُ الذِّئْبُ وَمَا أَنتَ بِمُؤْمِنٍ لَّنَا وَلَوْ كُنَّا صَادِقِينَ",
        "urdu_text": "انہوں نے کہا، اے ہمارے ابا! ہم دوڑ میں لگ گئے تھے اور یوسف کو اپنے سامان کے پاس چھوڑ گئے تھے تو اسے بھیڑیا کھا گیا، اور آپ ہمیں یقین نہیں کریں گے، چاہے ہم سچے ہی کیوں نہ ہوں۔",
        "persian_text": "گفتند: ای پدر ما! ما برای مسابقه رفتیم و یوسف را نزد وسایلمان گذاشتیم، پس گرگ او را خورد، و تو ما را باور نخواهی کرد هرچند راستگو باشیم.",
        "english_text": "They said, 'O our father, indeed we went racing one another and left Joseph with our possessions, and a wolf ate him. But you would not believe us, even if we were truthful.'",
        "transliteration": "Qālū yā abānā innā dhahabnā nastabiq wa taraknā Yoosufa ‘inda matā‘inā fa akalahu adh-dhi’bu wa mā anta bimu’minin lanā wa law kunnā ṣādiqīn",
        "verse_number": "17",
    },
    {
        "arabic_text": "وَجَاءُوا عَلَىٰ قَمِيصِهِ بِدَمٍ كَذِبٍ ۚ قَالَ بَلْ سَوَّلَتْ لَكُمْ أَنفُسُكُمْ أَمْرًا ۖ فَصَبْرٌ جَمِيلٌ ۖ وَاللَّهُ الْمُسْتَعَانُ عَلَىٰ مَا تَصِفُونَ",
        "urdu_text": "اور وہ اس کی قمیص پر جھوٹا خون لگا لائے۔ (یعقوبؑ) نے کہا، بلکہ تمہارے نفسوں نے تمہیں کوئی بات سجھا دی ہے، پس اب صبر ہی بہتر ہے، اور جو تم بیان کر رہے ہو اس پر اللہ ہی سے مدد مانگی جا سکتی ہے۔",
        "persian_text": "و پیراهن او را با خونی دروغین آوردند. (یعقوب) گفت: بلکه نفس‌های شما کاری را برایتان آراسته است. پس شکیبایی نیکو لازم است، و خداست آن که در برابر آنچه وصف می‌کنید یاری خواسته می‌شود.",
        "english_text": "And they brought upon his shirt false blood. He said, 'Rather, your souls have enticed you to something, so patience is most fitting. And Allah is the one sought for help against that which you describe.'",
        "transliteration": "Wa jā’ū ‘alā qamīṣihi bidamin kadhib, qāla bal sawwalat lakum anfusukum amrā, fa ṣabrun jamīl, wallāhu al-musta‘ānu ‘alā mā taṣifūn",
        "verse_number": "18",
    },
    {
        "arabic_text": "وَجَاءَتْ سَيَّارَةٌ فَأَرْسَلُوا وَارِدَهُمْ فَأَدْلَىٰ دَلْوَهُ ۖ قَالَ يَا بُشْرَىٰ هَٰذَا غُلَامٌ ۚ وَأَسَرُّوهُ بِضَاعَةً ۚ وَاللَّهُ عَلِيمٌ بِمَا يَعْمَلُونَ",
        "urdu_text": "اور ایک قافلہ آیا، انہوں نے اپنا پانی بھرنے والا بھیجا، اس نے اپنی بالٹی لٹکائی، (پھر) کہا: خوشخبری ہو! یہ تو ایک لڑکا ہے، اور انہوں نے اسے مالِ تجارت کے طور پر چھپا لیا، اور اللہ ان کے کاموں سے خوب واقف تھا۔",
        "persian_text": "و کاروانی آمد، و آب‌کش خود را فرستادند، او دلو خود را فرو افکند، گفت: مژده که این پسری است! و او را متاعی پنهان داشتند، و خدا به آنچه می‌کردند داناست.",
        "english_text": "And there came a company of travelers; they sent their water drawer, and he let down his bucket. He said, 'Good news! Here is a boy.' And they concealed him as merchandise, but Allah was knowing of what they did.",
        "transliteration": "Wa jā’at sayyārah fa arsalū wāridahum fa adlā dalwah, qāla yā bushrā hādhā ghulām, wa asarrūhu biḍā‘ah, wallāhu ‘alīmun bimā ya‘malūn",
        "verse_number": "19",
    },
    {
        "arabic_text": "وَشَرَوْهُ بِثَمَنٍ بَخْسٍ دَرَاهِمَ مَعْدُودَةٍ وَكَانُوا فِيهِ مِنَ الزَّاهِدِينَ",
        "urdu_text": "اور انہوں نے اسے چند درہموں کی قلیل قیمت پر بیچ دیا، اور وہ اس کے بارے میں بے رغبت تھے۔",
        "persian_text": "و او را به بهایی اندک، درهم‌هایی معدود، فروختند، و آنان نسبت به او بی‌میل بودند.",
        "english_text": "And they sold him for a reduced price — a few dirhams — and they were, concerning him, of those content with little.",
        "transliteration": "Wa sharawhu bithamanin bakhsin darāhima ma‘dūdah, wa kānū fīhi mina az-zāhidīn",
        "verse_number": "20",
    },
    {
        "arabic_text": "وَقَالَ الَّذِي اشْتَرَاهُ مِن مِّصْرَ لِامْرَأَتِهِ أَكْرِمِي مَثْوَاهُ عَسَىٰ أَن يَنفَعَنَا أَوْ نَتَّخِذَهُ وَلَدًا ۚ وَكَذَٰلِكَ مَكَّنَّا لِيُوسُفَ فِي الْأَرْضِ وَلِنُعَلِّمَهُ مِن تَأْوِيلِ الْأَحَادِيثِ ۚ وَاللَّهُ غَالِبٌ عَلَىٰ أَمْرِهِ وَلَـٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ",
        "urdu_text": "اور جس شخص نے اسے مصر میں خریدا اس نے اپنی بیوی سے کہا: اس کا اچھی طرح خیال رکھو، ہو سکتا ہے کہ ہمیں نفع پہنچائے یا ہم اسے بیٹا بنا لیں۔ اور اس طرح ہم نے یوسف کو زمین میں جگہ دی تاکہ ہم اسے خوابوں کی تعبیر سکھائیں۔ اور اللہ اپنے کام پر غالب ہے لیکن اکثر لوگ نہیں جانتے۔",
        "persian_text": "و آن کس که او را در مصر خرید به همسرش گفت: جایگاهش را گرامی دار، شاید ما را سود رساند یا او را فرزند خود گیریم. و بدین‌سان یوسف را در زمین استوار داشتیم تا از تعبیر خواب‌ها به او بیاموزیم. و خدا بر کار خویش چیره است، ولی بیشتر مردم نمی‌دانند.",
        "english_text": "And the one from Egypt who bought him said to his wife, 'Make his stay honorable. Perhaps he may benefit us, or we may adopt him as a son.' And thus We established Joseph in the land that We might teach him the interpretation of events. And Allah is predominant over His affair, but most people do not know.",
        "transliteration": "Wa qāla alladhī ishtarāhu min Miṣra li imra’atihi akrimī mathwāhu ‘asā an yanfa‘anā aw nattakhidhahu waladā, wa kadhālika makkannā li Yoosufa fī al-arḍi wa li nu‘allimahu min ta’wīli al-aḥādīth, wallāhu ghālibun ‘alā amrihi walākinna akthara an-nāsi lā ya‘lamūn",
        "verse_number": "21",
    },
    {
        "arabic_text": "وَلَمَّا بَلَغَ أَشُدَّهُ آتَيْنَاهُ حُكْمًا وَعِلْمًا ۚ وَكَذَٰلِكَ نَجْزِي الْمُحْسِنِينَ",
        "urdu_text": "اور جب وہ اپنی پوری جوانی کو پہنچا تو ہم نے اسے حکمت اور علم عطا کیا، اور ہم نیکوکاروں کو اسی طرح بدلہ دیتے ہیں۔",
        "persian_text": "و چون به رشد کامل خود رسید، به او داوری و دانش دادیم، و چنین نیکوکاران را پاداش می‌دهیم.",
        "english_text": "And when he reached maturity, We gave him judgment and knowledge. And thus We reward the doers of good.",
        "transliteration": "Wa lammā balagha ashu-ddahu ātaynāhu ḥukman wa ‘ilman, wa kadhālika najzī al-muḥsinīn",
        "verse_number": "22",
    },
    {
        "arabic_text": "وَرَاوَدَتْهُ الَّتِي هُوَ فِي بَيْتِهَا عَن نَّفْسِهِ وَغَلَّقَتِ الْأَبْوَابَ وَقَالَتْ هَيْتَ لَكَ ۚ قَالَ مَعَاذَ اللَّهِ ۖ إِنَّهُ رَبِّي أَحْسَنَ مَثْوَايَ ۖ إِنَّهُ لَا يُفْلِحُ الظَّالِمُونَ",
        "urdu_text": "اور جس عورت کے گھر میں وہ تھا، اس نے اسے اپنی طرف مائل کرنے کی کوشش کی اور دروازے بند کر دیے اور کہا: آؤ۔ یوسف نے کہا: میں اللہ کی پناہ مانگتا ہوں! بے شک وہ میرا رب ہے، اس نے مجھے اچھا مقام دیا ہے، بے شک ظالم فلاح نہیں پاتے۔",
        "persian_text": "و زنی که در خانه‌اش بود، او را به خود فراخواند و درها را بست و گفت: بیا! گفت: پناه بر خدا! او پروردگار من است که جایگاهم را نیکو کرده، بی‌گمان ستمکاران رستگار نمی‌شوند.",
        "english_text": "And she, in whose house he was, sought to seduce him. She closed the doors and said, 'Come to me.' He said, 'I seek refuge in Allah! Indeed, He is my Lord, who has made my stay good. Indeed, wrongdoers will not succeed.'",
        "transliteration": "Wa rāwadat-hu allati huwa fī baytihā ‘an nafsihi wa ghallaqat al-abwāba wa qālat hayta laka, qāla ma‘ādhallāh, innahu rabbī aḥsana mathwāy, innahu lā yufliḥu adh-dhālimūn",
        "verse_number": "23",
    },
    {
        "arabic_text": "وَلَقَدْ هَمَّتْ بِهِ وَهَمَّ بِهَا لَوْلَا أَن رَّأَىٰ بُرْهَانَ رَبِّهِ ۚ كَذَٰلِكَ لِنَصْرِفَ عَنْهُ السُّوءَ وَالْفَحْشَاءَ ۚ إِنَّهُ مِنْ عِبَادِنَا الْمُخْلَصِينَ",
        "urdu_text": "اور وہ (عورت) اس کے ارادے میں تھی اور وہ بھی اس کے ارادے میں ہوتا اگر وہ اپنے رب کی دلیل نہ دیکھ لیتا۔ اسی طرح ہم نے اس سے برائی اور بے حیائی کو روک دیا۔ بے شک وہ ہمارے مخلص بندوں میں سے تھا۔",
        "persian_text": "و او قصد او کرد و او نیز اگر برهان پروردگار خود را نمی‌دید، قصد او می‌کرد. بدین‌سان بدی و زشتی را از او بازگرداندیم، بی‌گمان او از بندگان خالص ما بود.",
        "english_text": "And she certainly determined to seduce him, and he would have inclined to her had he not seen the proof of his Lord. Thus We averted from him evil and immorality. Indeed, he was of Our chosen servants.",
        "transliteration": "Wa laqad hamat bihī wa hamma bihā lawlā an ra’ā burhāna rabbih, kadhālika linaṣrifa ‘anhu as-sū’a wa al-faḥshā’, innahu min ‘ibādinā al-mukhlāṣīn",
        "verse_number": "24",
    },
    {
        "arabic_text": "وَاسْتَبَقَا الْبَابَ وَقَدَّتْ قَمِيصَهُ مِن دُبُرٍ وَأَلْفَيَا سَيِّدَهَا لَدَا الْبَابِ ۚ قَالَتْ مَا جَزَاءُ مَنْ أَرَادَ بِأَهْلِكَ سُوءًا إِلَّا أَن يُسْجَنَ أَوْ عَذَابٌ أَلِيمٌ",
        "urdu_text": "اور دونوں دروازے کی طرف دوڑے، اس نے یوسف کی قمیص پیچھے سے پھاڑ دی، اور دونوں نے اس کے شوہر کو دروازے پر پایا۔ اس عورت نے کہا: جو شخص تمہاری بیوی کے ساتھ برائی کا ارادہ کرے اس کی سزا قید ہے یا کوئی دردناک عذاب۔",
        "persian_text": "و هر دو به سوی در دویدند، و او پیراهن او را از پشت پاره کرد، و شوهرش را نزد در یافتند. گفت: پاداش کسی که به خانواده‌ات قصد بدی کند جز زندان یا عذابی دردناک چیست؟",
        "english_text": "And they both raced to the door, and she tore his shirt from the back, and they found her husband at the door. She said, 'What is the recompense of one who intended evil for your wife except that he be imprisoned or a painful punishment?'",
        "transliteration": "Wa istabaqā al-bāba wa qaddat qamīṣahu min dubur, wa alfayā sayyidahā ladā al-bāb, qālat mā jazā’u man arāda bi ahlika sū’an illā an yusjana aw ‘adhābun alīm",
        "verse_number": "25",
    },
    {
        "arabic_text": "قَالَ هِيَ رَاوَدَتْنِي عَن نَّفْسِي ۚ وَشَهِدَ شَاهِدٌ مِّنْ أَهْلِهَا ۚ إِن كَانَ قَمِيصُهُ قُدَّ مِن قُبُلٍ فَصَدَقَتْ وَهُوَ مِنَ الْكَاذِبِينَ",
        "urdu_text": "یوسف نے کہا: یہ عورت مجھے اپنے نفس کی طرف مائل کر رہی تھی۔ اور اس کے خاندان کے ایک شخص نے گواہی دی کہ اگر اس کی قمیص آگے سے پھٹی ہے تو وہ سچی ہے اور وہ جھوٹوں میں سے ہے۔",
        "persian_text": "گفت: او بود که مرا به خود فراخواند. و گواهی از خانواده‌اش شهادت داد که اگر پیراهن او از پیش پاره شده، زن راست گفته و او از دروغگویان است.",
        "english_text": "He said, 'It was she who sought to seduce me.' And a witness from her family testified: 'If his shirt is torn from the front, then she has told the truth, and he is of the liars.'",
        "transliteration": "Qāla hiya rāwadatnī ‘an nafsī, wa shahida shāhidun min ahlihā in kāna qamīṣuhu qudda min qubul fa ṣadaqat wa huwa mina al-kādhibīn",
        "verse_number": "26",
    },
    {
        "arabic_text": "وَإِن كَانَ قَمِيصُهُ قُدَّ مِن دُبُرٍ فَكَذَبَتْ وَهُوَ مِنَ الصَّادِقِينَ",
        "urdu_text": "اور اگر اس کی قمیص پیچھے سے پھٹی ہے تو وہ عورت جھوٹی ہے اور یوسف سچوں میں سے ہے۔",
        "persian_text": "و اگر پیراهنش از پشت پاره شده، زن دروغ گفته و او از راستگویان است.",
        "english_text": "But if his shirt is torn from the back, then she has lied, and he is of the truthful.",
        "transliteration": "Wa in kāna qamīṣuhu qudda min dubur fa kadhabat wa huwa mina aṣ-ṣādiqīn",
        "verse_number": "27",
    },
    {
        "arabic_text": "فَلَمَّا رَأَىٰ قَمِيصَهُ قُدَّ مِن دُبُرٍ قَالَ إِنَّهُ مِن كَيْدِكُنَّ ۖ إِنَّ كَيْدَكُنَّ عَظِيمٌ",
        "urdu_text": "پھر جب اس نے دیکھا کہ اس کی قمیص پیچھے سے پھٹی ہے تو کہا: یہ تم عورتوں کی چال ہے، بے شک تمہاری چال بڑی خطرناک ہے۔",
        "persian_text": "پس چون دید پیراهن او از پشت پاره شده، گفت: این از نیرنگ شما زنان است؛ بی‌گمان نیرنگ شما بزرگ است.",
        "english_text": "So when he saw that his shirt was torn from the back, he said, 'Indeed, it is of your women's plan. Truly, your plan is great.'",
        "transliteration": "Falammā ra’ā qamīṣahu qudda min dubur qāla innahu min kaydikum, inna kaydakunna ‘aẓīm",
        "verse_number": "28",
    },
    {
        "arabic_text": "يُوسُفُ أَعْرِضْ عَنْ هَٰذَا ۚ وَاسْتَغْفِرِي لِذَنبِكِ ۖ إِنَّكِ كُنتِ مِنَ الْخَاطِئِينَ",
        "urdu_text": "یوسف! اس بات سے درگزر کرو، اور (عورت سے کہا:) اپنے گناہ کی معافی مانگو، بے شک تم خطاکاروں میں سے ہو۔",
        "persian_text": "ای یوسف! از این موضوع درگذر، و تو (ای زن) از گناهت آمرزش بخواه، که تو از خطاکاران بودی.",
        "english_text": "'O Joseph, ignore this. And you, (O woman), ask forgiveness for your sin. Indeed, you were of the sinners.'",
        "transliteration": "Yoosufu a‘riḍ ‘an hādhā, wastaghfirī li dhanbik, innaki kunti mina al-khāṭi’īn",
        "verse_number": "29",
    },
    {
        "arabic_text": "وَقَالَ نِسْوَةٌ فِي الْمَدِينَةِ امْرَأَتُ الْعَزِيزِ تُرَاوِدُ فَتَاهَا عَن نَّفْسِهِ ۖ قَدْ شَغَفَهَا حُبًّا ۖ إِنَّا لَنَرَاهَا فِي ضَلَالٍ مُّبِينٍ",
        "urdu_text": "اور شہر میں عورتوں نے کہا: عزیز کی بیوی اپنے غلام کو اپنے نفس کی طرف مائل کر رہی ہے۔ اس کی محبت نے اسے دیوانہ کر دیا ہے، ہم یقیناً اسے کھلی گمراہی میں دیکھتے ہیں۔",
        "persian_text": "و زنانی در شهر گفتند: زن عزیز می‌خواهد غلام خود را به سوی خود کشد. عشق او دلش را شیفته کرده است، ما او را در گمراهی آشکار می‌بینیم.",
        "english_text": "And women in the city said, 'The wife of the Aziz is seeking to seduce her slave boy. He has impassioned her with love; indeed, we see her in clear error.'",
        "transliteration": "Wa qāla niswatun fī al-madīnati imra’atu al-‘azīzi turāwidu fatāhā ‘an nafsih, qad shaghafahā ḥubbā, innā lanarāhā fī ḍalālin mubīn",
        "verse_number": "30",
    },
    {
        "arabic_text": "فَلَمَّا سَمِعَتْ بِمَكْرِهِنَّ أَرْسَلَتْ إِلَيْهِنَّ وَأَعْتَدَتْ لَهُنَّ مُتَّكَأً وَآتَتْ كُلَّ وَاحِدَةٍ مِّنْهُنَّ سِكِّينًا وَقَالَتِ اخْرُجْ عَلَيْهِنَّ ۖ فَلَمَّا رَأَيْنَهُ أَكْبَرْنَهُ وَقَطَّعْنَ أَيْدِيَهُنَّ وَقُلْنَ حَاشَ لِلَّهِ مَا هَٰذَا بَشَرًا إِنْ هَٰذَا إِلَّا مَلَكٌ كَرِيمٌ",
        "urdu_text": "پھر جب اس نے ان کی چالاکیوں کی خبر سنی تو ان کو بلوا بھیجا اور ان کے لیے مجلس تیار کی اور ہر ایک کے ہاتھ میں ایک چھری دے دی، اور یوسف سے کہا: ان کے سامنے نکل آؤ۔ جب ان عورتوں نے اسے دیکھا تو وہ اس کی عظمت سے حیران رہ گئیں اور اپنے ہاتھ کاٹ لیے اور کہنے لگیں: اللہ پاک ہے! یہ کوئی انسان نہیں، یہ تو ایک معزز فرشتہ ہے۔",
        "persian_text": "چون زن عزیز از نیرنگ آنان آگاه شد، آنان را دعوت کرد و برایشان مجلسی آماده ساخت و به هر یک کاردی داد و گفت: بیرون بیا! چون او را دیدند، او را بزرگ شمردند و دست‌های خود را بریدند و گفتند: سبحان‌الله! این بشر نیست، او فرشته‌ای بزرگوار است.",
        "english_text": "So when she heard of their scheming, she sent for them and prepared for them a banquet and gave each one of them a knife and said, 'Come out before them.' When they saw him, they greatly admired him and cut their hands and said, 'Perfect is Allah! This is not a man; this is none but a noble angel.'",
        "transliteration": "Falammā sami‘at bimakrihinna arsalat ilayhinna wa a‘tat lahunna muttaka’an wa ātat kulla wāḥidatin minhunna sikkīnan wa qālat ukhruj ‘alayhinna, falammā ra’aynahu akbarnahu wa qaṭṭa‘na aydiyahunna wa qulna ḥāsha lillāh mā hādhā basharan in hādhā illā malakun karīm",
        "verse_number": "31",
    },
    {
        "arabic_text": "قَالَتْ فَذَٰلِكُنَّ الَّذِي لُمْتُنَّنِي فِيهِ ۖ وَلَقَدْ رَاوَدتُّهُ عَن نَّفْسِهِ فَاسْتَعْصَمَ ۖ وَلَئِن لَّمْ يَفْعَلْ مَا آمُرُهُ لَيُسْجَنَنَّ وَلَيَكُونًا مِّنَ الصَّاغِرِينَ",
        "urdu_text": "اس نے کہا: یہی وہ ہے جس کے بارے میں تم نے مجھے ملامت کی تھی۔ میں نے اسے اپنے نفس کی طرف مائل کرنے کی کوشش کی لیکن اس نے بچاؤ کیا، اور اگر یہ وہی نہ کرے گا جو میں اسے حکم دیتی ہوں تو ضرور قید کر دیا جائے گا اور ذلیل ہو کر رہے گا۔",
        "persian_text": "گفت: این همان است که مرا در باره‌اش سرزنش می‌کردید! من او را به خود فراخواندم و او خودداری کرد، و اگر آنچه به او فرمان می‌دهم انجام ندهد، بی‌گمان زندانی خواهد شد و از خوارشدگان می‌گردد.",
        "english_text": "She said, 'That is the one about whom you blamed me. I sought to seduce him, but he firmly refused; and if he does not do what I command, he will surely be imprisoned and will be of those debased.'",
        "transliteration": "Qālat fa dhālikunna alladhī lumtunnanī fīh, wa laqad rāwadttuhu ‘an nafsih fa ista‘ṣam, wa la’in lam yaf‘al mā āmuruhu la yusjananna wa la yakūnanna mina aṣ-ṣāghirīn",
        "verse_number": "32",
    },
    {
        "arabic_text": "قَالَ رَبِّ السِّجْنُ أَحَبُّ إِلَيَّ مِمَّا يَدْعُونَنِي إِلَيْهِ ۖ وَإِلَّا تَصْرِفْ عَنِّي كَيْدَهُنَّ أَصْبُ إِلَيْهِنَّ وَأَكُن مِّنَ الْجَاهِلِينَ",
        "urdu_text": "یوسف نے کہا: اے میرے رب! قید مجھے اس چیز سے زیادہ پسند ہے جس کی طرف وہ مجھے بلاتی ہیں، اور اگر تو ان کی چال مجھ سے نہ ہٹائے تو میں ان کی طرف مائل ہو جاؤں گا اور جاہلوں میں سے ہو جاؤں گا۔",
        "persian_text": "گفت: پروردگارا! زندان برای من دوست‌داشتنی‌تر است از آنچه مرا به سوی آن می‌خوانند، و اگر نیرنگشان را از من بازنگردانی، به سویشان گرایم و از نادانان شوم.",
        "english_text": "He said, 'My Lord, prison is more to my liking than that to which they invite me. And if You do not avert from me their plan, I might incline toward them and thus be of the ignorant.'",
        "transliteration": "Qāla rabbis-sijnu aḥabbu ilayya mimmā yad‘ūnanī ilayh, wa illā taṣrif ‘annī kaydahunna aṣbu ilayhinna wa akun mina al-jāhilīn",
        "verse_number": "33",
    },
    {
        "arabic_text": "فَاسْتَجَابَ لَهُ رَبُّهُ فَصَرَفَ عَنْهُ كَيْدَهُنَّ ۚ إِنَّهُ هُوَ السَّمِيعُ الْعَلِيمُ",
        "urdu_text": "پس اس کے رب نے اس کی دعا قبول کر لی اور ان عورتوں کی چال اس سے دور کر دی۔ بے شک وہی سننے والا، جاننے والا ہے۔",
        "persian_text": "پروردگارش دعایش را اجابت کرد و نیرنگ آنان را از او بازگردانید. بی‌گمان او شنوا و داناست.",
        "english_text": "So his Lord responded to him and averted from him their plan. Indeed, He is the Hearing, the Knowing.",
        "transliteration": "Fa istajāba lahu rabbuhu fa ṣarafa ‘anhu kaydahunna, innahu huwa as-samī‘u al-‘alīm",
        "verse_number": "34",
    },
    {
        "arabic_text": "ثُمَّ بَدَا لَهُم مِّن بَعْدِ مَا رَأَوُا الْآيَاتِ لَيَسْجُنُنَّهُ حَتَّىٰ حِينٍ",
        "urdu_text": "پھر ان لوگوں کو، باوجود ان نشانیاں دیکھنے کے، یہ مناسب معلوم ہوا کہ کچھ مدت کے لیے اسے قید کر دیں۔",
        "persian_text": "آنگاه پس از آنکه نشانه‌ها را دیدند، به نظرشان چنین آمد که تا مدتی او را به زندان افکنند.",
        "english_text": "Then it appeared to them, after they had seen the signs, that they should surely imprison him for a time.",
        "transliteration": "Thumma badā lahum min ba‘di mā ra’aw al-āyāti la yasjununnahu ḥattā ḥīn",
        "verse_number": "35",
    },
    {
        "arabic_text": "وَدَخَلَ مَعَهُ السِّجْنَ فَتَيَانِ ۖ قَالَ أَحَدُهُمَا إِنِّي أَرَانِي أَعْصِرُ خَمْرًا ۖ وَقَالَ الْآخَرُ إِنِّي أَرَانِي أَحْمِلُ فَوْقَ رَأْسِي خُبْزًا تَأْكُلُ الطَّيْرُ مِنْهُ ۖ نَبِّئْنَا بِتَأْوِيلِهِ ۖ إِنَّا نَرَاكَ مِنَ الْمُحْسِنِينَ",
        "urdu_text": "اور اس کے ساتھ دو جوان قید خانے میں داخل ہوئے۔ ان میں سے ایک نے کہا: میں نے خواب میں دیکھا کہ میں شراب نچوڑ رہا ہوں، اور دوسرے نے کہا: میں نے دیکھا کہ میں اپنے سر پر روٹی اٹھائے ہوں جس سے پرندے کھا رہے ہیں۔ ہمیں اس کی تعبیر بتاؤ، ہم تمہیں نیکوکاروں میں سے دیکھتے ہیں۔",
        "persian_text": "و با او دو جوان به زندان درآمدند. یکی از آن دو گفت: من خود را در خواب دیدم که شراب می‌فشارم، و دیگری گفت: من خود را دیدم که نانی بر سر دارم و پرندگان از آن می‌خورند. ما را از تعبیرش آگاه ساز، ما تو را از نیکوکاران می‌بینیم.",
        "english_text": "And there entered the prison with him two young men. One of them said, 'Indeed, I have seen myself pressing wine.' The other said, 'Indeed, I have seen myself carrying bread on my head, from which the birds were eating. Inform us of its interpretation; indeed, we see you to be of those who do good.'",
        "transliteration": "Wa dakhala ma‘ahu as-sijna fatayān, qāla aḥaduhumā innī arānī a‘ṣiru khamrā, wa qāla al-ākharu innī arānī aḥmilu fawqa ra’sī khubzan ta’kulu aṭ-ṭayru minhu, nabbi’nā bi ta’wīlih, innā narāka mina al-muḥsinīn",
        "verse_number": "36",
    },
    {
        "arabic_text": "قَالَ لَا يَأْتِيكُمَا طَعَامٌ تُرْزَقَانِهِ إِلَّا نَبَّأْتُكُمَا بِتَأْوِيلِهِ قَبْلَ أَن يَأْتِيَكُمَا ۚ ذَٰلِكُمَا مِمَّا عَلَّمَنِي رَبِّي ۚ إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَّا يُؤْمِنُونَ بِاللَّهِ وَهُم بِالْآخِرَةِ هُمْ كَافِرُونَ",
        "urdu_text": "یوسف نے کہا: تمہیں جو کھانا دیا جاتا ہے وہ تمہارے پاس آنے سے پہلے میں تمہیں اس کی تعبیر بتا دوں گا۔ یہ ان چیزوں میں سے ہے جو میرے رب نے مجھے سکھائیں۔ میں نے ان لوگوں کا دین چھوڑ دیا ہے جو اللہ پر ایمان نہیں رکھتے اور آخرت کے منکر ہیں۔",
        "persian_text": "گفت: هیچ غذایی به شما نمی‌رسد مگر آنکه پیش از آنکه نزد شما آید، تعبیرش را به شما می‌گویم. این از چیزهایی است که پروردگارم به من آموخته است. من آیین قومی را ترک گفته‌ام که به خدا ایمان ندارند و به آخرت کافرند.",
        "english_text": "He said, 'You will not receive food that is provided to you except that I will inform you of its interpretation before it comes to you. That is from what my Lord has taught me. Indeed, I have left the religion of a people who do not believe in Allah and who are disbelievers in the Hereafter.'",
        "transliteration": "Qāla lā ya’tīkumā ṭa‘āmun turzaqānihi illā nabba’tukumā bi ta’wīlih qabla an ya’tiyakumā, dhālikumā mimmā ‘allamanī rabbī, innī taraktu millata qawmin lā yu’minūna billāhi wa hum bil-ākhirati hum kāfirūn",
        "verse_number": "37",
    },
    {
        "arabic_text": "وَاتَّبَعْتُ مِلَّةَ آبَائِي إِبْرَاهِيمَ وَإِسْحَاقَ وَيَعْقُوبَ ۚ مَا كَانَ لَنَا أَن نُّشْرِكَ بِاللَّهِ مِن شَيْءٍ ۚ ذَٰلِكَ مِن فَضْلِ اللَّهِ عَلَيْنَا وَعَلَى النَّاسِ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَشْكُرُونَ",
        "urdu_text": "اور میں نے اپنے باپ دادا ابراہیم، اسحاق اور یعقوب کا دین اختیار کیا ہے۔ ہمارے لیے یہ ممکن نہیں کہ ہم کسی چیز کو اللہ کا شریک بنائیں۔ یہ اللہ کا فضل ہے ہم پر اور لوگوں پر، لیکن اکثر لوگ شکر ادا نہیں کرتے۔",
        "persian_text": "و از آیین پدرانم ابراهیم و اسحاق و یعقوب پیروی کرده‌ام. برای ما روا نیست که چیزی را با خدا شریک گردانیم. این از فضل خدا بر ما و بر مردم است، ولی بیشتر مردم سپاس نمی‌گزارند.",
        "english_text": "And I have followed the religion of my fathers, Abraham, Isaac, and Jacob. It was not for us to associate anything with Allah. That is from the favor of Allah upon us and upon the people, but most people are not grateful.",
        "transliteration": "Wa ittaba‘tu millata ābā’ī Ibrāhīma wa Isḥāqa wa Ya‘qūb, mā kāna lanā an nushrika billāhi min shay’, dhālika min faḍli llāhi ‘alaynā wa ‘alā an-nāsi walākinna akthara an-nāsi lā yashkurūn",
        "verse_number": "38",
    },
    {
        "arabic_text": "يَا صَاحِبَيِ السِّجْنِ أَأَرْبَابٌ مُّتَفَرِّقُونَ خَيْرٌ أَمِ اللَّهُ الْوَاحِدُ الْقَهَّارُ",
        "urdu_text": "اے میرے قید کے ساتھیو! کیا جدا جدا رب بہتر ہیں یا اللہ جو ایک ہے، سب پر غالب؟",
        "persian_text": "ای دو همراه زندان من! آیا خدایان گوناگون بهترند یا خدای یگانه چیره؟",
        "english_text": "O my two companions of prison, are separate lords better or Allah, the One, the Prevailing?",
        "transliteration": "Yā ṣāḥibayi as-sijni a’arbābun mutafarriqūna khayrun amillāhu al-wāḥidu al-qahhār",
        "verse_number": "39",
    },
    {
        "arabic_text": "مَا تَعْبُدُونَ مِن دُونِهِ إِلَّا أَسْمَاءً سَمَّيْتُمُوهَا أَنتُمْ وَآبَاؤُكُم مَّا أَنزَلَ اللَّهُ بِهَا مِن سُلْطَانٍ ۚ إِنِ الْحُكْمُ إِلَّا لِلَّهِ ۚ أَمَرَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ ۚ ذَٰلِكَ الدِّينُ الْقَيِّمُ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ",
        "urdu_text": "تم اس کے سوا جن کی عبادت کرتے ہو وہ صرف نام ہیں جو تم نے اور تمہارے باپ دادا نے رکھ لیے ہیں، اللہ نے ان کے لیے کوئی دلیل نازل نہیں کی۔ حکم تو صرف اللہ کا ہے۔ اس نے حکم دیا ہے کہ تم اس کے سوا کسی کی عبادت نہ کرو۔ یہی سیدھا دین ہے لیکن اکثر لوگ نہیں جانتے۔",
        "persian_text": "شما جز نام‌هایی که خود و پدرانتان نام نهاده‌اید، جز آن نمی‌پرستید؛ خدا هیچ دلیلی بر آنها فرو نفرستاده است. فرمان جز از آن خدا نیست؛ او فرمان داده که جز او را نپرستید. این است دین استوار، ولی بیشتر مردم نمی‌دانند.",
        "english_text": "You worship not besides Him except [mere] names you have named, you and your fathers, for which Allah has sent down no authority. The decision is only for Allah. He has commanded that you worship none but Him. That is the correct religion, but most of the people do not know.",
        "transliteration": "Mā ta‘budūna min dūnihi illā asmā’an sammaytumūhā antum wa ābā’ukum mā anzala llāhu bihā min sulṭān, inil-ḥukmu illā lillāh, amara allā ta‘budū illā iyyāh, dhālika ad-dīnu al-qayyim walākinna akthara an-nāsi lā ya‘lamūn",
        "verse_number": "40",
    },
    {
        "arabic_text": "يَا صَاحِبَيِ السِّجْنِ أَمَّا أَحَدُكُمَا فَيَسْقِي رَبَّهُ خَمْرًا وَأَمَّا الْآخَرُ فَيُصْلَبُ فَتَأْكُلُ الطَّيْرُ مِن رَّأْسِهِ ۚ قُضِيَ الْأَمْرُ الَّذِي فِيهِ تَسْتَفْتِيَانِ",
        "urdu_text": "اے میرے قید کے ساتھیو! تم میں سے ایک اپنے رب (بادشاہ) کو شراب پلائے گا، اور دوسرا سولی پر چڑھایا جائے گا اور پرندے اس کے سر سے کھائیں گے۔ وہ فیصلہ ہو چکا ہے جس کے بارے میں تم دونوں پوچھ رہے تھے۔",
        "persian_text": "ای دو همراه زندان من! یکی از شما به سرورش شراب خواهد نوشانید، و دیگری به دار آویخته خواهد شد و پرندگان از سر او خواهند خورد. کاری که از آن درباره‌اش می‌پرسیدید، پایان یافته است.",
        "english_text": "O two companions of prison, as for one of you, he will give drink to his master of wine; but as for the other, he will be crucified, and the birds will eat from his head. The matter has been decreed about which you both inquire.",
        "transliteration": "Yā ṣāḥibayi as-sijni ammā aḥadukumā fa yasqī rabbahu khamrā, wa ammā al-ākharu fa yuṣlabu fa ta’kulu aṭ-ṭayru min ra’sih, quḍiya al-amru alladhī fīhi tastaftiyān",
        "verse_number": "41",
    },
    {
        "arabic_text": "وَقَالَ لِلَّذِي ظَنَّ أَنَّهُ نَاجٍ مِّنْهُمَا اذْكُرْنِي عِندَ رَبِّكَ فَأَنسَاهُ الشَّيْطَانُ ذِكْرَ رَبِّهِ فَلَبِثَ فِي السِّجْنِ بِضْعَ سِنِينَ",
        "urdu_text": "اور اس نے ان دونوں میں سے جس کے متعلق گمان کیا کہ وہ بچ جائے گا، اس سے کہا: اپنے مالک کے حضور میرا ذکر کرنا۔ لیکن شیطان نے اسے اپنے مالک سے ذکر بھلا دیا، تو یوسف کئی سال قید میں رہے۔",
        "persian_text": "و به آنکه گمان می‌کرد که از آن دو نجات خواهد یافت، گفت: مرا نزد سرورت یاد کن. ولی شیطان یاد کردن او را از یادش برد، پس چند سالی در زندان ماند.",
        "english_text": "And he said to the one whom he knew would go free, 'Mention me before your master.' But Satan made him forget the mention to his master, and Joseph remained in prison for several years.",
        "transliteration": "Wa qāla lilladhī ẓanna annahu nājin minhumā udhkur’nī ‘inda rabbik, fa ansāhu ash-shayṭānu dhikra rabbih, fa labitha fī as-sijni biḍ‘a sinīn",
        "verse_number": "42",
    },
    {
        "arabic_text": "وَقَالَ الْمَلِكُ إِنِّي أَرَىٰ سَبْعَ بَقَرَاتٍ سِمَانٍ يَأْكُلُهُنَّ سَبْعٌ عِجَافٌ وَسَبْعَ سُنبُلَاتٍ خُضْرٍ وَأُخَرَ يَابِسَاتٍ ۖ يَا أَيُّهَا الْمَلَأُ أَفْتُونِي فِي رُؤْيَايَ إِن كُنتُمْ لِلرُّؤْيَا تَعْبُرُونَ",
        "urdu_text": "اور بادشاہ نے کہا: میں نے خواب میں دیکھا کہ سات موٹی گائیں ہیں جنہیں سات دبلی گائیں کھا رہی ہیں، اور سات سبز بالیاں ہیں اور سات خشک۔ اے درباریو! اگر تم خواب کی تعبیر جانتے ہو تو مجھے میرے خواب کی تعبیر بتاؤ۔",
        "persian_text": "و پادشاه گفت: من در خواب دیدم هفت گاو فربه را که هفت گاو لاغر آنها را می‌خورند، و هفت خوشه سبز و هفت خوشه خشک. ای بزرگان! اگر تعبیر خواب می‌دانید، در خواب من نظر دهید.",
        "english_text": "And the king said, 'Indeed, I have seen in a dream seven fat cows being eaten by seven thin ones, and seven green ears of grain and others dry. O eminent ones, explain to me my vision, if you should interpret visions.'",
        "transliteration": "Wa qāla al-maliku innī arā sab‘a baqarātin simānin ya’kuluhunna sab‘un ‘ijāf, wa sab‘a sunbulātin khuḍr wa ukhara yābisāt, yā ayyuhal-mala’u aftūnī fī ru’yāya in kuntum lil-ru’yā ta‘burūn",
        "verse_number": "43",
    },
    {
        "arabic_text": "قَالُوا أَضْغَاثُ أَحْلَامٍ وَمَا نَحْنُ بِتَأْوِيلِ الْأَحْلَامِ بِعَالِمِينَ",
        "urdu_text": "انہوں نے کہا: یہ تو الجھے ہوئے خواب ہیں، اور ہم خوابوں کی تعبیر نہیں جانتے۔",
        "persian_text": "گفتند: این خواب‌های پریشان است، و ما از تعبیر خواب‌ها آگاه نیستیم.",
        "english_text": "They said, 'It is but a mixture of false dreams, and we are not learned in the interpretation of dreams.'",
        "transliteration": "Qālū aḍghāthu aḥlām, wa mā naḥnu bi ta’wīli al-aḥlāmi bi ‘ālimīn",
        "verse_number": "44",
    },
    {
        "arabic_text": "وَقَالَ الَّذِي نَجَا مِنْهُمَا وَادَّكَرَ بَعْدَ أُمَّةٍ أَنَا أُنَبِّئُكُم بِتَأْوِيلِهِ فَأَرْسِلُونِ",
        "urdu_text": "اور ان دونوں میں سے جو بچ گیا تھا، اسے ایک عرصے کے بعد یاد آیا اور کہا: میں تمہیں اس کی تعبیر بتا دیتا ہوں، تو مجھے بھیجو۔",
        "persian_text": "و آن که از آن دو نجات یافته بود و پس از مدتی به یاد آورد، گفت: من شما را از تعبیر آن آگاه می‌کنم، مرا بفرستید.",
        "english_text": "But the one who was freed and remembered after a time said, 'I will inform you of its interpretation, so send me forth.'",
        "transliteration": "Wa qāla alladhī najā minhumā wa adh-dhakara ba‘da ummah, anā unabbi’ukum bi ta’wīlih fa arsilūn",
        "verse_number": "45",
    },
    {
        "arabic_text": "يُوسُفُ أَيُّهَا الصِّدِّيقُ أَفْتِنَا فِي سَبْعِ بَقَرَاتٍ سِمَانٍ يَأْكُلُهُنَّ سَبْعٌ عِجَافٌ وَسَبْعِ سُنبُلَاتٍ خُضْرٍ وَأُخَرَ يَابِسَاتٍ لَّعَلِّي أَرْجِعُ إِلَى النَّاسِ لَعَلَّهُمْ يَعْلَمُونَ",
        "urdu_text": "یوسف! اے سچے شخص! ہمیں بتاؤ سات موٹی گائیں جنہیں سات دبلی کھا رہی ہیں، اور سات سبز بالیاں اور دوسری خشک — اس کی کیا تعبیر ہے؟ تاکہ میں لوگوں کے پاس واپس جاؤں اور وہ جان لیں۔",
        "persian_text": "ای یوسف راستگو! درباره هفت گاو فربه که هفت گاو لاغر آنها را می‌خورند و هفت خوشه سبز و دیگر خشک برای ما بیان کن تا نزد مردم بازگردم، باشد که آنان بدانند.",
        "english_text": "Yusuf, O man of truth, explain to us about seven fat cows eaten by seven lean ones and seven green ears of grain and others dry, that I may return to the people; perhaps they will know.",
        "transliteration": "Yūsufu ayyuhā aṣ-ṣiddīqu aftinā fī sab‘i baqarātin simānin ya’kuluhunna sab‘un ‘ijāf wa sab‘i sunbulātin khuḍr wa ukhara yābisāt la‘allī arji‘u ilā an-nāsi la‘allahum ya‘lamūn",
        "verse_number": "46",
    },
    {
        "arabic_text": "قَالَ تَزْرَعُونَ سَبْعَ سِنِينَ دَأَبًا فَمَا حَصَدتُّمْ فَذَرُوهُ فِي سُنبُلِهِ إِلَّا قَلِيلًا مِّمَّا تَأْكُلُونَ",
        "urdu_text": "یوسف نے کہا: تم لگاتار سات سال کھیتی کرو گے، جو کچھ کاٹو اسے اس کی بالیوں میں ہی رہنے دو سوائے تھوڑے سے جسے تم کھاؤ گے۔",
        "persian_text": "گفت: هفت سال پی‌درپی کشت خواهید کرد و آنچه درو کردید، جز اندکی که می‌خورید، در خوشه‌اش بگذارید.",
        "english_text": "He said, 'You will plant for seven years consecutively, and what you harvest leave in its spikes, except a little from which you eat.'",
        "transliteration": "Qāla tazra‘ūna sab‘a sinīna da’abā, famā ḥaṣadtum fa dharūhu fī sunbulih illā qalīlan mimmā ta’kulūn",
        "verse_number": "47",
    },
    {
        "arabic_text": "ثُمَّ يَأْتِي مِن بَعْدِ ذَٰلِكَ سَبْعٌ شِدَادٌ يَأْكُلْنَ مَا قَدَّمْتُمْ لَهُنَّ إِلَّا قَلِيلًا مِّمَّا تُحْصِنُونَ",
        "urdu_text": "پھر اس کے بعد سات سخت سال آئیں گے جو کھا جائیں گے جو تم نے ان کے لیے پہلے جمع کیا ہوگا، سوائے تھوڑے سے جو تم محفوظ رکھو گے۔",
        "persian_text": "سپس پس از آن هفت سال سخت می‌آید که آنچه را برای آنها از پیش ذخیره کرده‌اید خواهند خورد، جز اندکی که نگاه می‌دارید.",
        "english_text": "Then will come after that seven difficult years which will consume what you saved for them, except a little from which you will store.",
        "transliteration": "Thumma ya’tī min ba‘di dhālika sab‘un shidādun ya’kulna mā qaddamtum lahunna illā qalīlan mimmā tuḥṣinūn",
        "verse_number": "48",
    },
    {
        "arabic_text": "ثُمَّ يَأْتِي مِن بَعْدِ ذَٰلِكَ عَامٌ فِيهِ يُغَاثُ النَّاسُ وَفِيهِ يَعْصِرُونَ",
        "urdu_text": "پھر اس کے بعد ایک سال آئے گا جس میں لوگوں پر بارش ہوگی اور اس میں فراوانی ہوگی۔",
        "persian_text": "سپس پس از آن سالی می‌آید که در آن مردم یاری می‌شوند و در آن می‌فشارند (شراب یا روغن).",
        "english_text": "Then will come after that a year in which the people will be given rain and in which they will press (juice).",
        "transliteration": "Thumma ya’tī min ba‘di dhālika ‘āmun fīhi yughāthu an-nāsu wa fīhi ya‘ṣirūn",
        "verse_number": "49",
    },
    {
        "arabic_text": "وَقَالَ الْمَلِكُ ائْتُونِي بِهِ ۖ فَلَمَّا جَاءَهُ الرَّسُولُ قَالَ ارْجِعْ إِلَىٰ رَبِّكَ فَسْأَلْهُ مَا بَالُ النِّسْوَةِ الَّاتِي قَطَّعْنَ أَيْدِيَهُنَّ ۚ إِنَّ رَبِّي بِكَيْدِهِنَّ عَلِيمٌ",
        "urdu_text": "اور بادشاہ نے کہا: اسے میرے پاس لے آؤ۔ جب قاصد اس کے پاس آیا تو یوسف نے کہا: اپنے رب کے پاس واپس جاؤ اور اس سے پوچھو ان عورتوں کا کیا معاملہ تھا جنہوں نے اپنے ہاتھ کاٹ لیے تھے؟ میرا رب ان کی چالوں سے خوب واقف ہے۔",
        "persian_text": "و پادشاه گفت: او را نزد من آورید. چون فرستاده نزد او آمد، گفت: نزد سرورت بازگرد و از او بپرس: حال آن زنانی که دست‌های خود را بریدند چه بود؟ بی‌گمان پروردگارم از نیرنگشان آگاه است.",
        "english_text": "And the king said, 'Bring him to me.' But when the messenger came to him, Joseph said, 'Return to your master and ask him, What is the case of the women who cut their hands? Indeed, my Lord is Knowing of their plan.'",
        "transliteration": "Wa qāla al-maliku i’tūnī bih, falammā jā’ahu ar-rasūlu qāla irji‘ ilā rabbika fa’s’alhu mā bālu an-niswati allatī qaṭṭa‘na aydiyahunna, inna rabbī bi kaydihinna ‘alīm",
        "verse_number": "50",
    },
    {
        "arabic_text": "قَالَ مَا خَطْبُكُنَّ إِذْ رَاوَدتُّنَّ يُوسُفَ عَن نَّفْسِهِ ۚ قُلْنَ حَاشَ لِلَّهِ مَا عَلِمْنَا عَلَيْهِ مِن سُوءٍ ۚ قَالَتِ امْرَأَةُ الْعَزِيزِ الْآنَ حَصْحَصَ الْحَقُّ أَنَا رَاوَدتُّهُ عَن نَّفْسِهِ وَإِنَّهُ لَمِنَ الصَّادِقِينَ",
        "urdu_text": "بادشاہ نے کہا: تمہارا کیا حال تھا جب تم نے یوسف کو اپنے نفس سے بہکانے کی کوشش کی تھی؟ انہوں نے کہا: اللہ کی پناہ! ہم نے اس میں کوئی برائی نہیں دیکھی۔ عزیز کی بیوی نے کہا: اب حق ظاہر ہوگیا، میں نے ہی اسے اپنے نفس کی طرف مائل کرنے کی کوشش کی تھی، اور وہ تو یقیناً سچا ہے۔",
        "persian_text": "پادشاه گفت: چه حالتان بود آنگاه که از یوسف خواستید او را بفریبید؟ گفتند: منزه است خدا! ما هیچ بدی در او نیافتیم. زن عزیز گفت: اکنون حقیقت آشکار شد، من از او کام خواستم و او از راستگویان است.",
        "english_text": "The king said, 'What was your condition when you sought to seduce Joseph?' They said, 'Exalted is Allah! We know about him no evil.' The wife of al-'Aziz said, 'Now the truth has become evident. It was I who sought to seduce him, and indeed, he is of the truthful.'",
        "transliteration": "Qāla mā khaṭbukunna idh rāwadttunna Yūsufa ‘an nafsih, qulna ḥāsha lillāh mā ‘alimnā ‘alayhi min sū’, qālat imra’atu al-‘Azīz al-āna ḥaṣḥaṣa al-ḥaqq, anā rāwadttuhu ‘an nafsih wa innahu lamina aṣ-ṣādiqīn",
        "verse_number": "51",
    },
    {
        "arabic_text": "ذَٰلِكَ لِيَعْلَمَ أَنِّي لَمْ أَخُنْهُ بِالْغَيْبِ وَأَنَّ اللَّهَ لَا يَهْدِي كَيْدَ الْخَائِنِينَ",
        "urdu_text": "یہ اس لیے ہے تاکہ وہ جان لے کہ میں نے اس کی غیر موجودگی میں اس کے ساتھ خیانت نہیں کی، اور بے شک اللہ خیانت کرنے والوں کی چال کو کامیاب نہیں کرتا۔",
        "persian_text": "این بدان سبب است که بداند من در نهان به او خیانت نکردم، و خدا نیرنگ خیانتکاران را به راه نمی‌برد.",
        "english_text": "That is so he may know that I did not betray him in his absence and that Allah does not guide the plan of betrayers.",
        "transliteration": "Dhālika liya‘lama annī lam akhunhu bil-ghayb wa anna Allāha lā yahdī kayda al-khā’inīn",
        "verse_number": "52",
    },
    {
        "arabic_text": "وَمَا أُبَرِّئُ نَفْسِي ۚ إِنَّ النَّفْسَ لَأَمَّارَةٌ بِالسُّوءِ إِلَّا مَا رَحِمَ رَبِّي ۚ إِنَّ رَبِّي غَفُورٌ رَّحِيمٌ",
        "urdu_text": "اور میں اپنے نفس کو بری نہیں ٹھہراتی، بے شک نفس برائی کا بہت حکم دینے والا ہے، مگر جس پر میرا رب رحم کرے۔ بے شک میرا رب بہت بخشنے والا، نہایت مہربان ہے۔",
        "persian_text": "و من نفس خود را تبرئه نمی‌کنم، زیرا نفس همواره به بدی فرمان می‌دهد، مگر آنکه پروردگارم بر او رحم کند. بی‌گمان پروردگارم آمرزنده و مهربان است.",
        "english_text": "And I do not acquit myself. Indeed, the soul is ever inclined to evil, except those upon which my Lord has mercy. Indeed, my Lord is Forgiving and Merciful.",
        "transliteration": "Wa mā ubarri’u nafsī inna an-nafsa la-ammāratun bis-sū’ illā mā raḥima rabbī, inna rabbī ghafūrun raḥīm",
        "verse_number": "53",
    },
    {
        "arabic_text": "وَقَالَ الْمَلِكُ ائْتُونِي بِهِ أَسْتَخْلِصْهُ لِنَفْسِي ۖ فَلَمَّا كَلَّمَهُ قَالَ إِنَّكَ الْيَوْمَ لَدَيْنَا مَكِينٌ أَمِينٌ",
        "urdu_text": "اور بادشاہ نے کہا: اسے میرے پاس لے آؤ تاکہ میں اسے اپنے لیے مخصوص کر لوں۔ پھر جب اس سے بات کی تو کہا: یقیناً آج سے تم ہمارے ہاں صاحبِ مقام اور امانتدار ہو۔",
        "persian_text": "و پادشاه گفت: او را نزد من آورید تا او را خاص خود گردانم. پس چون با او سخن گفت، گفت: امروز نزد ما دارای مقام و مورد اعتماد هستی.",
        "english_text": "And the king said, 'Bring him to me; I will appoint him exclusively for myself.' And when he spoke to him, he said, 'Indeed, you are today established [in position] and trusted.'",
        "transliteration": "Wa qāla al-maliku i’tūnī bih astakhliṣhu li-nafsī, falammā kallamah qāla innaka al-yawma ladaynā makīnun amīn",
        "verse_number": "54",
    },
    {
        "arabic_text": "قَالَ اجْعَلْنِي عَلَىٰ خَزَائِنِ الْأَرْضِ ۖ إِنِّي حَفِيظٌ عَلِيمٌ",
        "urdu_text": "یوسف نے کہا: مجھے زمین کے خزانوں پر مقرر کر دو، بے شک میں حفاظت کرنے والا اور علم رکھنے والا ہوں۔",
        "persian_text": "گفت: مرا بر خزائن این سرزمین بگمار، زیرا من نگهبان و دانا هستم.",
        "english_text": "He said, 'Appoint me over the storehouses of the land. Indeed, I will be a knowing guardian.'",
        "transliteration": "Qāla ij‘alnī ‘alā khazā’ini al-arḍ, innī ḥafīẓun ‘alīm",
        "verse_number": "55",
    },
    {
        "arabic_text": "وَكَذَٰلِكَ مَكَّنَّا لِيُوسُفَ فِي الْأَرْضِ يَتَبَوَّأُ مِنْهَا حَيْثُ يَشَاءُ ۚ نُصِيبُ بِرَحْمَتِنَا مَن نَّشَاءُ ۖ وَلَا نُضِيعُ أَجْرَ الْمُحْسِنِينَ",
        "urdu_text": "اور اسی طرح ہم نے یوسف کو اس زمین میں اقتدار دیا کہ وہ جہاں چاہے ٹھکانا بنائے۔ ہم اپنی رحمت جس پر چاہیں نازل کرتے ہیں، اور ہم نیکوکاروں کے اجر کو ضائع نہیں کرتے۔",
        "persian_text": "و بدین‌گونه یوسف را در آن سرزمین توانمند ساختیم تا در هر جا که بخواهد جای گیرد. رحمت خود را به هر که بخواهیم می‌رسانیم و پاداش نیکوکاران را تباه نمی‌سازیم.",
        "english_text": "And thus We established Joseph in the land to settle therein wherever he willed. We touch with Our mercy whom We will, and We do not allow to be lost the reward of those who do good.",
        "transliteration": "Wa kadhālika makkannā li-Yūsufa fī al-arḍ yatabawwa’u minhā ḥaythu yashā’, nuṣību bi raḥmatinā man nashā’, wa lā nuḍī‘u ajra al-muḥsinīn",
        "verse_number": "56",
    },
    {
        "arabic_text": "وَلَأَجْرُ الْآخِرَةِ خَيْرٌ لِّلَّذِينَ آمَنُوا وَكَانُوا يَتَّقُونَ",
        "urdu_text": "اور آخرت کا اجر ان لوگوں کے لیے بہتر ہے جو ایمان لائے اور پرہیزگاری اختیار کی۔",
        "persian_text": "و بی‌گمان پاداش آخرت برای کسانی که ایمان آوردند و پرهیزگاری کردند بهتر است.",
        "english_text": "And the reward of the Hereafter is better for those who believed and were fearing Allah.",
        "transliteration": "Wa la-ajru al-ākhirati khayrun lilladhīna āmanū wa kānū yattaqūn",
        "verse_number": "57",
    },
    {
        "arabic_text": "وَجَاءَ إِخْوَةُ يُوسُفَ فَدَخَلُوا عَلَيْهِ فَعَرَفَهُمْ وَهُمْ لَهُ مُنكِرُونَ",
        "urdu_text": "اور یوسف کے بھائی آئے اور اس کے پاس داخل ہوئے، تو اس نے انہیں پہچان لیا لیکن وہ اسے نہ پہچان سکے۔",
        "persian_text": "و برادران یوسف آمدند و بر او وارد شدند، پس او آنان را شناخت و آنان او را نشناختند.",
        "english_text": "And the brothers of Joseph came and entered upon him, and he recognized them, but they did not recognize him.",
        "transliteration": "Wa jā’a ikhwatū Yūsuf fa dakhala ‘alayhi fa ‘arafahum wa hum lahu munkirūn",
        "verse_number": "58",
    },
    {
        "arabic_text": "وَلَمَّا جَهَّزَهُم بِجَهَازِهِمْ قَالَ ائْتُونِي بِأَخٍ لَّكُم مِّنْ أَبِيكُمْ ۚ أَلَا تَرَوْنَ أَنِّي أُوفِي الْكَيْلَ وَأَنَا خَيْرُ الْمُنزِلِينَ",
        "urdu_text": "اور جب اس نے ان کا سامان تیار کر دیا تو کہا: اپنے باپ کی طرف سے اپنے ایک بھائی کو میرے پاس لے آؤ۔ کیا تم نہیں دیکھتے کہ میں پیمانہ پورا دیتا ہوں اور بہترین مہمان نواز ہوں؟",
        "persian_text": "و چون بار آنان را آماده ساخت، گفت: برادری از پدرتان برایم بیاورید. آیا نمی‌بینید که من پیمانه را کامل می‌دهم و بهترین میزبانم؟",
        "english_text": "And when he had furnished them with their supplies, he said, 'Bring me a brother of yours from your father. Do you not see that I give full measure and that I am the best of hosts?'",
        "transliteration": "Wa lammā jahhazahum bi jahāzihim qāla i’tūnī bi akhin lakum min abīkum, alā tarawna annī ūfī al-kayla wa anā khayru al-munzilīn",
        "verse_number": "59",
    },
    {
        "arabic_text": "فَإِن لَّمْ تَأْتُونِي بِهِ فَلَا كَيْلَ لَكُمْ عِندِي وَلَا تَقْرَبُونِ",
        "urdu_text": "پھر اگر تم اسے میرے پاس نہ لاؤ تو تمہارے لیے میرے پاس کوئی پیمانہ نہیں ہوگا، اور نہ ہی تم میرے قریب آنا۔",
        "persian_text": "پس اگر او را نزد من نیاورید، دیگر نزد من پیمانه‌ای نخواهید داشت و به من نزدیک نشوید.",
        "english_text": "But if you do not bring him to me, no measure will there be for you from me, nor will you approach me.",
        "transliteration": "Fa in lam ta’tūnī bih fa lā kayla lakum ‘indī wa lā taqrabūn",
        "verse_number": "60",
    },
    {
        "arabic_text": "قَالُوا سَنُرَاوِدُ عَنْهُ أَبَاهُ وَإِنَّا لَفَاعِلُونَ",
        "urdu_text": "انہوں نے کہا: ہم اس کے بارے میں اس کے باپ کو راضی کرنے کی کوشش کریں گے، اور یقیناً ہم ایسا ضرور کریں گے۔",
        "persian_text": "گفتند: پدرش را درباره‌ی او خواهیم فریفت و یقیناً ما این کار را انجام خواهیم داد.",
        "english_text": "They said, 'We will try to persuade his father about him, and indeed, we will do it.'",
        "transliteration": "Qālū sanurāwidu ‘anhu abāhu wa innā lafā‘ilūn",
        "verse_number": "61",
    },
    {
        "arabic_text": "وَقَالَ لِفِتْيَانِهِ اجْعَلُوا بِضَاعَتَهُمْ فِي رِحَالِهِمْ لَعَلَّهُمْ يَعْرِفُونَهَا إِذَا انقَلَبُوا إِلَىٰ أَهْلِهِمْ لَعَلَّهُمْ يَرْجِعُونَ",
        "urdu_text": "اور یوسف نے اپنے نوکروں سے کہا: ان کا مال ان کے سامان میں رکھ دو، تاکہ جب وہ اپنے گھر واپس جائیں تو اسے پہچان لیں، شاید وہ واپس آ جائیں۔",
        "persian_text": "و به غلامان خود گفت: کالای آنان را در بارشان بگذارید تا چون نزد خانواده‌شان بازگردند آن را بشناسند، شاید بازگردند.",
        "english_text": "And he said to his servants, 'Put their merchandise into their saddlebags so they might recognize it when they have gone back to their people, that perhaps they will return.'",
        "transliteration": "Wa qāla li fityānihi ij‘alū biḍā‘atahum fī riḥālihim la‘allahum ya‘rifūnahā idhā inqalabū ilā ahlihim la‘allahum yarji‘ūn",
        "verse_number": "62",
    },
    {
        "arabic_text": "فَلَمَّا رَجَعُوا إِلَىٰ أَبِيهِمْ قَالُوا يَا أَبَانَا مُنِعَ مِنَّا الْكَيْلُ فَأَرْسِلْ مَعَنَا أَخَانَا نَكْتَلْ وَإِنَّا لَهُ لَحَافِظُونَ",
        "urdu_text": "پھر جب وہ اپنے باپ کے پاس واپس آئے تو کہا: اے ہمارے ابا! ہمارے لیے غلہ روک دیا گیا ہے، لہٰذا ہمارے بھائی کو ہمارے ساتھ بھیج دیجیے تاکہ ہم غلہ حاصل کریں، اور ہم یقیناً اس کے محافظ ہیں۔",
        "persian_text": "پس چون نزد پدرشان بازگشتند، گفتند: ای پدر ما! پیمانه از ما بازداشته شده است، برادرمان را با ما بفرست تا پیمانه بگیریم، و ما نگهبان او خواهیم بود.",
        "english_text": "So when they returned to their father, they said, 'O our father, measure has been denied us, so send with us our brother that we may obtain measure, and indeed, we will be his guardians.'",
        "transliteration": "Falammā raja‘ū ilā abīhim qālū yā abānā muni‘a minnā al-kayl fa arsil ma‘anā akhānā naktal wa innā lahu laḥāfiẓūn",
        "verse_number": "63",
    },
    {
        "arabic_text": "قَالَ هَلْ آمَنُكُمْ عَلَيْهِ إِلَّا كَمَا أَمِنتُكُمْ عَلَىٰ أَخِيهِ مِن قَبْلُ ۖ فَاللَّهُ خَيْرٌ حَافِظًا وَهُوَ أَرْحَمُ الرَّاحِمِينَ",
        "urdu_text": "اس نے کہا: کیا میں تم پر اس کے بارے میں ویسا ہی اعتماد کروں جیسا اس کے بھائی کے بارے میں پہلے کیا تھا؟ اللہ ہی بہترین محافظ ہے، اور وہ سب سے زیادہ رحم کرنے والا ہے۔",
        "persian_text": "گفت: آیا بر او به شما اعتماد کنم همان‌گونه که پیش‌تر بر برادرش اعتماد کردم؟ پس خدا بهترین نگهبان است، و او مهربان‌ترین مهربانان است.",
        "english_text": "He said, 'Should I entrust him to you except as I entrusted his brother to you before? But Allah is the best guardian, and He is the Most Merciful of the merciful.'",
        "transliteration": "Qāla hal āmanukum ‘alayhi illā kamā amintukum ‘alā akhīhi min qabl, fa Allāhu khayrun ḥāfiẓā wa huwa arḥamu ar-rāḥimīn",
        "verse_number": "64",
    },
    {
        "arabic_text": "وَلَمَّا فَتَحُوا مَتَاعَهُمْ وَجَدُوا بِضَاعَتَهُمْ رُدَّتْ إِلَيْهِمْ ۖ قَالُوا يَا أَبَانَا مَا نَبْغِي ۖ هَٰذِهِ بِضَاعَتُنَا رُدَّتْ إِلَيْنَا وَنَمِيرُ أَهْلَنَا وَنَحْفَظُ أَخَانَا وَنَزْدَادُ كَيْلَ بَعِيرٍ ۖ ذَٰلِكَ كَيْلٌ يَسِيرٌ",
        "urdu_text": "اور جب انہوں نے اپنا سامان کھولا تو دیکھا کہ ان کا مال ان کو واپس کر دیا گیا ہے۔ انہوں نے کہا: اے ہمارے ابا! ہمیں اور کیا چاہیے؟ یہ ہمارا مال ہمیں واپس مل گیا ہے، اب ہم اپنے گھر والوں کے لیے غلہ لائیں گے، اپنے بھائی کی حفاظت کریں گے، اور ایک اونٹ کا بوجھ زیادہ حاصل کریں گے۔ یہ تو بہت آسان معاملہ ہے۔",
        "persian_text": "و چون بار خود را گشودند، دریافتند که کالای آنان به آنان بازگردانده شده است. گفتند: ای پدر ما! دیگر چه می‌خواهیم؟ این کالای ما به ما بازگردانده شده است، پس خانواده‌مان را آذوقه می‌دهیم و از برادرمان نگهبانی می‌کنیم و یک بار شتر بیشتر می‌آوریم، این پیمانه‌ای اندک است.",
        "english_text": "And when they opened their baggage, they found their merchandise returned to them. They said, 'O our father, what more could we desire? This is our merchandise returned to us; and we will get food for our family and protect our brother and obtain an extra measure of a camel’s load; that is an easy measure.'",
        "transliteration": "Wa lammā fataḥū matā‘ahum wajadū biḍā‘atahum ruddath ilayhim, qālū yā abānā mā nabghī, hādhihi biḍā‘atunā ruddath ilaynā wa namīru ahlanā wa naḥfaẓu akhānā wa nazdādu kayla ba‘īr, dhālika kaylun yasīr",
        "verse_number": "65",
    },
    {
        "arabic_text": "قَالَ لَنْ أُرْسِلَهُ مَعَكُمْ حَتَّىٰ تُؤْتُونِ مَوْثِقًا مِّنَ اللَّهِ لَتَأْتُنَّنِي بِهِ إِلَّا أَن يُحَاطَ بِكُمْ ۖ فَلَمَّا آتَوْهُ مَوْثِقَهُمْ قَالَ اللَّهُ عَلَىٰ مَا نَقُولُ وَكِيلٌ",
        "urdu_text": "اس نے کہا: میں اسے تمہارے ساتھ نہیں بھیجوں گا جب تک تم اللہ کی قسم سے پختہ عہد نہ دو کہ تم اسے میرے پاس واپس لاؤ گے، مگر یہ کہ تم سب گھیر لیے جاؤ۔ پھر جب انہوں نے اسے اپنا عہد دیا، تو اس نے کہا: اللہ اس پر نگہبان ہے جو ہم کہہ رہے ہیں۔",
        "persian_text": "گفت: او را با شما نخواهم فرستاد تا هنگامی که از خدا پیمان مؤکدی بیاورید که او را نزد من بازخواهید آورد، مگر آنکه گرفتار شوید. پس چون پیمانشان را به او دادند، گفت: خدا بر آنچه می‌گوییم نگهبان است.",
        "english_text": "He said, 'I will not send him with you until you give me a promise by Allah that you will bring him back to me, unless you should be surrounded.' And when they had given him their promise, he said, 'Allah is Guardian over what we say.'",
        "transliteration": "Qāla lan ursilahu ma‘akum ḥattā tu’tūnī mawthiqan mina Allāhi lata’tunnanī bih illā an yuḥāṭa bikum, falammā ātawhu mawthiqahum qāla Allāhu ‘alā mā naqūlu wakīl",
        "verse_number": "66",
    },
    {
        "arabic_text": "وَقَالَ يَا بَنِيَّ لَا تَدْخُلُوا مِن بَابٍ وَاحِدٍ وَادْخُلُوا مِنْ أَبْوَابٍ مُّتَفَرِّقَةٍ وَمَا أُغْنِي عَنكُم مِّنَ اللَّهِ مِن شَيْءٍ ۖ إِنِ الْحُكْمُ إِلَّا لِلَّهِ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَعَلَيْهِ فَلْيَتَوَكَّلِ الْمُتَوَكِّلُونَ",
        "urdu_text": "اور اس نے کہا: اے میرے بیٹو! ایک دروازے سے داخل نہ ہونا بلکہ مختلف دروازوں سے داخل ہونا، مگر میں تمہیں اللہ کے فیصلے سے کچھ بھی نہیں بچا سکتا۔ فیصلہ تو اللہ ہی کے ہاتھ میں ہے۔ میں نے اسی پر بھروسہ کیا ہے، اور اسی پر بھروسہ کرنے والوں کو بھروسہ کرنا چاہیے۔",
        "persian_text": "و گفت: ای پسران من! از یک در وارد نشوید بلکه از درهای گوناگون وارد شوید، و من هیچ از خدا در برابر شما بی‌نیاز نمی‌گردانم، حکم جز از آنِ خدا نیست، بر او توکل کردم و توکل‌کنندگان باید بر او توکل کنند.",
        "english_text": "And he said, 'O my sons, do not enter from one gate but enter from different gates; and I cannot avail you against Allah at all. The decision is only for Allah; upon Him I have relied, and upon Him let those who would rely indeed rely.'",
        "transliteration": "Wa qāla yā baniyya lā tadkhulū min bābin wāḥid wa adkhulū min abwābin mutafarriqah, wa mā ughnī ‘ankum mina Allāhi min shay’, inil ḥukmu illā lillāh, ‘alayhi tawakkaltu wa ‘alayhi falyatawakkalil mutawakkilūn",
        "verse_number": "67",
    },
    {
        "arabic_text": "وَلَمَّا دَخَلُوا مِنْ حَيْثُ أَمَرَهُمْ أَبُوهُمْ مَا كَانَ يُغْنِي عَنْهُم مِّنَ اللَّهِ مِن شَيْءٍ إِلَّا حَاجَةً فِي نَفْسِ يَعْقُوبَ قَضَاهَا ۚ وَإِنَّهُ لَذُو عِلْمٍ لِّمَا عَلَّمْنَاهُ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ",
        "urdu_text": "اور جب وہ اس راستے سے داخل ہوئے جس کا حکم ان کے باپ نے دیا تھا، تو یہ انہیں اللہ کے فیصلے سے کچھ بھی نہیں بچا سکتا تھا، مگر یعقوب کے دل کی ایک خواہش تھی جسے اس نے پورا کیا۔ یقیناً وہ علم والا تھا جو ہم نے اسے سکھایا، مگر اکثر لوگ نہیں جانتے۔",
        "persian_text": "و چون از همان راهی که پدرشان فرمان داده بود وارد شدند، این آنان را از چیزی که از خدا مقدر بود بی‌نیاز نساخت، جز آنکه نیازی در دل یعقوب بود که آن را برآورد. بی‌گمان او به آنچه ما بدو آموختیم دانا بود، ولی بیشتر مردم نمی‌دانند.",
        "english_text": "And when they entered from where their father had ordered them, it did not avail them against Allah at all except that it was a need within the soul of Jacob which he satisfied. And indeed, he was a possessor of knowledge because of what We had taught him, but most people do not know.",
        "transliteration": "Wa lammā dakhalū min ḥaythu amarahum abūhum mā kāna yughni ‘anhum mina Allāhi min shay’, illā ḥājatan fī nafs Ya‘qūba qaḍāhā, wa innahu la dhū ‘ilmin limā ‘allamnāhu wa lākinna akthara an-nāsi lā ya‘lamūn",
        "verse_number": "68",
    },
    {
        "arabic_text": "وَلَمَّا دَخَلُوا عَلَىٰ يُوسُفَ آوَىٰ إِلَيْهِ أَخَاهُ قَالَ إِنِّي أَنَا أَخُوكَ فَلَا تَبْتَئِسْ بِمَا كَانُوا يَعْمَلُونَ",
        "urdu_text": "اور جب وہ یوسف کے پاس داخل ہوئے تو اس نے اپنے بھائی کو اپنے پاس جگہ دی اور کہا: بے شک میں تمہارا بھائی ہوں، اس بات پر غم نہ کرو جو وہ کرتے رہے ہیں۔",
        "persian_text": "و چون بر یوسف وارد شدند، برادر خود را به سوی خویش کشید و گفت: من برادر توام، از آنچه آنان می‌کردند اندوهگین مباش.",
        "english_text": "And when they entered upon Joseph, he took his brother to himself; he said, 'Indeed, I am your brother, so do not despair over what they used to do.'",
        "transliteration": "Wa lammā dakhalū ‘alā Yūsufa āwā ilayhi akhāhu qāla innī anā akhūk fa lā tabta’is bimā kānū ya‘malūn",
        "verse_number": "69",
    },
    {
        "arabic_text": "فَلَمَّا جَهَّزَهُم بِجَهَازِهِمْ جَعَلَ السِّقَايَةَ فِي رَحْلِ أَخِيهِ ثُمَّ أَذَّنَ مُؤَذِّنٌ أَيَّتُهَا الْعِيرُ إِنَّكُمْ لَسَارِقُونَ",
        "urdu_text": "پھر جب اس نے ان کا سامان تیار کر دیا تو اپنے بھائی کے سامان میں پیمانہ رکھ دیا، پھر ایک منادی نے پکارا: اے قافلہ والو! یقیناً تم چور ہو۔",
        "persian_text": "پس چون بار آنان را آماده کرد، پیمانه را در بار برادرش نهاد، آنگاه منادی فریاد زد: ای کاروانیان! بی‌گمان شما دزد هستید.",
        "english_text": "Then when he had furnished them with their supplies, he put the drinking cup into his brother’s bag; then a caller announced, 'O caravan, indeed you are thieves!'",
        "transliteration": "Falammā jahhazahum bi jahāzihim ja‘ala as-siqāyata fī raḥli akhīh, thumma adh-dhana mu’adh-dhinun ayyatuha al-‘īr innakum lasāriqūn",
        "verse_number": "70",
    },
    {
        "arabic_text": "قَالُوا وَأَقْبَلُوا عَلَيْهِم مَّاذَا تَفْقِدُونَ",
        "urdu_text": "انہوں نے کہا اور ان کی طرف متوجہ ہو کر پوچھا: تمہیں کیا چیز گم ملی ہے؟",
        "persian_text": "گفتند و به سوی آنان روی آوردند: چه چیز را گم کرده‌اید؟",
        "english_text": "They said, and approached them, 'What is it that you are missing?'",
        "transliteration": "Qālū wa aqbalū ‘alayhim mādhā tafqidūn",
        "verse_number": "71",
    },
    {
        "arabic_text": "قَالُوا نَفْقِدُ صُوَاعَ الْمَلِكِ وَلِمَن جَاءَ بِهِ حِمْلُ بَعِيرٍ وَأَنَا بِهِ زَعِيمٌ",
        "urdu_text": "انہوں نے کہا: ہم بادشاہ کا پیمانہ گم کر بیٹھے ہیں، اور جو اسے لائے گا، اسے ایک اونٹ بھر اناج انعام میں ملے گا، اور میں اس کا ضامن ہوں۔",
        "persian_text": "گفتند: پیمانه‌ی پادشاه را گم کرده‌ایم، و هر که آن را بیاورد، بار یک شتر پاداش اوست، و من ضامنم.",
        "english_text": "They said, 'We are missing the king’s measuring bowl, and whoever brings it will have a camel’s load [of food], and I am responsible for it.'",
        "transliteration": "Qālū nafqidu ṣū‘a al-maliki wa liman jā’a bihi ḥimlu ba‘īr wa anā bihī za‘īm",
        "verse_number": "72",
    },
    {
        "arabic_text": "قَالُوا تَاللَّهِ لَقَدْ عَلِمْتُم مَّا جِئْنَا لِنُفْسِدَ فِي الْأَرْضِ وَمَا كُنَّا سَارِقِينَ",
        "urdu_text": "انہوں نے کہا: اللہ کی قسم! تم جانتے ہو کہ ہم زمین میں فساد کرنے نہیں آئے، اور نہ ہی ہم چور ہیں۔",
        "persian_text": "گفتند: به خدا سوگند، شما می‌دانید که ما برای فساد در زمین نیامده‌ایم و ما دزد نبوده‌ایم.",
        "english_text": "They said, 'By Allah, you certainly know that we did not come to cause corruption in the land, and we are not thieves.'",
        "transliteration": "Qālū tallāhi laqad ‘alimtum mā ji’nā linufsida fī al-arḍi wa mā kunnā sāriqīn",
        "verse_number": "73",
    },
    {
        "arabic_text": "قَالُوا فَمَا جَزَاؤُهُ إِن كُنتُمْ كَاذِبِينَ",
        "urdu_text": "انہوں نے کہا: اگر تم جھوٹے ہو تو اس کی سزا کیا ہوگی؟",
        "persian_text": "گفتند: پس اگر دروغ می‌گویید، کیفرش چیست؟",
        "english_text": "They said, 'Then what would be its recompense if you should be liars?'",
        "transliteration": "Qālū famā jazā’uhu in kuntum kādhibīn",
        "verse_number": "74",
    },
    {
        "arabic_text": "قَالُوا جَزَاؤُهُ مَن وُجِدَ فِي رَحْلِهِ فَهُوَ جَزَاؤُهُ ۚ كَذَٰلِكَ نَجْزِي الظَّالِمِينَ",
        "urdu_text": "انہوں نے کہا: اس کی سزا یہی ہے کہ جس کے سامان میں وہ چیز پائی جائے، وہی اس کی سزا میں روک لیا جائے۔ ہم ظالموں کو اسی طرح سزا دیتے ہیں۔",
        "persian_text": "گفتند: کیفرش آن است که هر کس در بارش یافت شود، خود او کیفر آن است، ما ستمکاران را چنین جزا می‌دهیم.",
        "english_text": "They said, 'Its recompense is that he in whose bag it is found—he himself will be its recompense. Thus do we recompense the wrongdoers.'",
        "transliteration": "Qālū jazā’uhu man wujida fī raḥlihi fahuwa jazā’uhu, kadhālika najzī aẓ-ẓālimīn",
        "verse_number": "75",
    },
    {
        "arabic_text": "فَبَدَأَ بِأَوْعِيَتِهِمْ قَبْلَ وِعَاءِ أَخِيهِ ثُمَّ اسْتَخْرَجَهَا مِن وِعَاءِ أَخِيهِ ۚ كَذَٰلِكَ كِدْنَا لِيُوسُفَ ۖ مَا كَانَ لِيَأْخُذَ أَخَاهُ فِي دِينِ الْمَلِكِ إِلَّا أَن يَشَاءَ اللَّهُ ۚ نَرْفَعُ دَرَجَاتٍ مَّن نَّشَاءُ ۗ وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ",
        "urdu_text": "پھر اس نے ان کے سامان کی تلاشی اپنے بھائی کے سامان سے پہلے شروع کی، پھر وہ پیمانہ اپنے بھائی کے سامان سے نکال لیا۔ ہم نے یوسف کے لیے اسی طرح تدبیر کی۔ وہ بادشاہ کے قانون کے تحت اپنے بھائی کو روک نہیں سکتا تھا، مگر یہ کہ اللہ چاہتا۔ ہم جسے چاہتے ہیں درجوں میں بلند کرتے ہیں، اور ہر علم والے کے اوپر ایک زیادہ علم رکھنے والا ہے۔",
        "persian_text": "پس از توشه‌هایشان پیش از توشه‌ی برادرش آغاز کرد، سپس آن را از توشه‌ی برادرش بیرون آورد. ما چنین برای یوسف چاره کردیم، او نمی‌توانست برادرش را به حکم پادشاه نگه دارد مگر آنکه خدا بخواهد. ما درجات را برای هر که بخواهیم بالا می‌بریم، و بر هر دانایی، داناتری است.",
        "english_text": "So he began with their bags before the bag of his brother; then he extracted it from his brother’s bag. Thus did We plan for Joseph. He could not have taken his brother under the law of the king except that Allah willed. We raise in degrees whom We will, but over every possessor of knowledge is one more knowing.",
        "transliteration": "Fabada’a bi aw‘iyatihim qabla wi‘ā’i akhīhi thumma istakhrajahā min wi‘ā’i akhīh, kadhālika kidnā li Yūsuf, mā kāna liya’khudha akhāhu fī dīnil maliki illā an yashā’a Allāh, narfa‘u darajātin man nashā’, wa fawqa kulli dhī ‘ilmin ‘alīm",
        "verse_number": "76",
    },
    {
        "arabic_text": "قَالُوا إِن يَسْرِقْ فَقَدْ سَرَقَ أَخٌ لَّهُ مِن قَبْلُ ۚ فَأَسَرَّهَا يُوسُفُ فِي نَفْسِهِ وَلَمْ يُبْدِهَا لَهُمْ ۚ قَالَ أَنتُمْ شَرٌّ مَّكَانًا وَاللَّهُ أَعْلَمُ بِمَا تَصِفُونَ",
        "urdu_text": "انہوں نے کہا: اگر اس نے چوری کی ہے تو اس کا ایک بھائی بھی پہلے چوری کر چکا ہے۔ یوسف نے یہ بات اپنے دل میں چھپائی اور ان پر ظاہر نہ کی۔ کہا: تمہارا حال بدتر ہے، اور اللہ خوب جانتا ہے جو تم بیان کرتے ہو۔",
        "persian_text": "گفتند: اگر او دزدی کرده است، برادری برای او بود که پیش‌تر دزدی کرده بود. یوسف این را در دل خود پنهان داشت و آن را بر آنان آشکار نکرد. گفت: جایگاه شما بدتر است و خدا داناتر است به آنچه وصف می‌کنید.",
        "english_text": "They said, 'If he steals, a brother of his has stolen before.' But Joseph kept it within himself and did not reveal it to them. He said, 'You are in a worse situation, and Allah is most knowing of what you describe.'",
        "transliteration": "Qālū in yasriq faqad saraqa akhun lahu min qablu fa asarrahā Yūsufu fī nafsihi wa lam yubdihā lahum, qāla antum sharrun makānan wa Allāhu a‘lamu bimā taṣifūn",
        "verse_number": "77",
    },
    {
        "arabic_text": "قَالُوا يَا أَيُّهَا الْعَزِيزُ إِنَّ لَهُ أَبًا شَيْخًا كَبِيرًا فَخُذْ أَحَدَنَا مَكَانَهُ ۖ إِنَّا نَرَاكَ مِنَ الْمُحْسِنِينَ",
        "urdu_text": "انہوں نے کہا: اے عزیزِ مصر! اس کا ایک بوڑھا باپ ہے، لہٰذا اسے چھوڑ کر ہم میں سے کسی ایک کو اس کی جگہ رکھ لیجیے۔ ہم آپ کو نیکوکاروں میں سے دیکھتے ہیں۔",
        "persian_text": "گفتند: ای عزیز! او پدری سالخورده دارد، پس یکی از ما را به جای او بگیر، بی‌گمان تو را از نیکوکاران می‌بینیم.",
        "english_text": "They said, 'O noble one, indeed he has a father, an old man, so take one of us in his place; indeed, we see you as one of the doers of good.'",
        "transliteration": "Qālū yā ayyuhal ‘azīzu innahu abān shaykhan kabīran fa khudh aḥadana makānahu, innā narāka minal muḥsinīn",
        "verse_number": "78",
    },
    {
        "arabic_text": "قَالَ مَعَاذَ اللَّهِ أَن نَّأْخُذَ إِلَّا مَن وَجَدْنَا مَتَاعَنَا عِندَهُ إِنَّا إِذًا لَّظَالِمُونَ",
        "urdu_text": "اس نے کہا: اللہ کی پناہ کہ ہم کسی کو پکڑیں سوائے اس کے جس کے پاس ہم نے اپنی چیز پائی، اگر ہم ایسا کریں تو ہم یقیناً ظالم ہوں گے۔",
        "persian_text": "گفت: پناه بر خدا که جز آن کسی را که کالای خود نزد او یافته‌ایم بگیریم، در آن صورت ستمکار خواهیم بود.",
        "english_text": "He said, 'I seek refuge in Allah from taking except him with whom we found our possession; indeed, we would then be unjust.'",
        "transliteration": "Qāla ma‘ādhallāhi an na’khudha illā man wajadnā matā‘anā ‘indahu innā idhan laẓ-ẓālimūn",
        "verse_number": "79",
    },
    {
        "arabic_text": "فَلَمَّا اسْتَيْأَسُوا مِنْهُ خَلَصُوا نَجِيًّا ۖ قَالَ كَبِيرُهُمْ أَلَمْ تَعْلَمُوا أَنَّ أَبَاكُمْ قَدْ أَخَذَ عَلَيْكُم مَّوْثِقًا مِّنَ اللَّهِ وَمِن قَبْلُ مَا فَرَّطتُمْ فِي يُوسُفَ ۖ فَلَنْ أَبْرَحَ الْأَرْضَ حَتَّىٰ يَأْذَنَ لِي أَبِي أَوْ يَحْكُمَ اللَّهُ لِي ۖ وَهُوَ خَيْرُ الْحَاكِمِينَ",
        "urdu_text": "پھر جب وہ اس سے مایوس ہو گئے تو الگ ہو کر مشورہ کرنے لگے۔ ان کے بڑے بھائی نے کہا: کیا تمہیں معلوم نہیں کہ تمہارے باپ نے تم سے اللہ کا پختہ عہد لیا تھا؟ اور اس سے پہلے تم یوسف کے معاملے میں کوتاہی کر چکے ہو۔ لہٰذا میں تو اس زمین سے نہیں جاؤں گا جب تک میرا باپ اجازت نہ دے یا اللہ میرے حق میں فیصلہ نہ کرے، اور وہ بہترین فیصلہ کرنے والا ہے۔",
        "persian_text": "پس چون از او نومید شدند، به خلوت نشستند. بزرگ‌ترشان گفت: آیا نمی‌دانید که پدرتان از شما پیمان خدا گرفته است، و پیش از این در حق یوسف کوتاهی کرده‌اید؟ من از این سرزمین بیرون نمی‌روم تا آنکه پدرم مرا اجازه دهد یا خدا درباره‌ام حکم کند، و او بهترین حکم‌کنندگان است.",
        "english_text": "So when they despaired of him, they secluded themselves in private consultation. The eldest of them said, 'Do you not know that your father took upon you an oath by Allah and before that you failed in your duty to Joseph? So I will never leave this land until my father permits me or Allah decides for me, and He is the best of judges.'",
        "transliteration": "Falammā istay’asū minhu khalasū najiyyā, qāla kabīruhum a lam ta‘lamū anna abākum qad akhadha ‘alaykum mawthiqan mina Allāhi wa min qablu mā farrattum fī Yūsuf, falan abraḥal arḍa ḥattā ya’dhana lī abī aw yaḥkuma Allāhu lī, wa huwa khayrul ḥākimīn",
        "verse_number": "80",
    },
    {
        "arabic_text": "ارْجِعُوا إِلَىٰ أَبِيكُمْ فَقُولُوا يَا أَبَانَا إِنَّ ابْنَكَ سَرَقَ وَمَا شَهِدْنَا إِلَّا بِمَا عَلِمْنَا وَمَا كُنَّا لِلْغَيْبِ حَافِظِينَ",
        "urdu_text": "تم اپنے باپ کے پاس لوٹ جاؤ اور کہو: اے ہمارے ابا! آپ کے بیٹے نے چوری کی ہے، ہم نے صرف وہی گواہی دی جو ہم جانتے تھے، اور ہم غیب کے نگہبان نہیں تھے۔",
        "persian_text": "بازگردید نزد پدرتان و بگویید: ای پدر ما! پسرت دزدی کرده است، و ما جز آنچه دانستیم گواهی ندادیم، و ما نگاهبان غیب نبودیم.",
        "english_text": "Return to your father and say, 'O our father, indeed your son has stolen, and we did not testify except to what we knew, and we were not guardians of the unseen.'",
        "transliteration": "Irji‘ū ilā abīkum fa qūlū yā abānā inna ibnak sarq, wa mā shahidnā illā bimā ‘alimnā wa mā kunnā lil-ghaybi ḥāfiẓīn",
        "verse_number": "81",
    },
    {
        "arabic_text": "وَاسْأَلِ الْقَرْيَةَ الَّتِي كُنَّا فِيهَا وَالْعِيرَ الَّتِي أَقْبَلْنَا فِيهَا وَإِنَّا لَصَادِقُونَ",
        "urdu_text": "اور اس بستی کے لوگوں سے پوچھ لیجیے جہاں ہم تھے، اور اس قافلے سے بھی جس میں ہم آئے ہیں، بے شک ہم سچے ہیں۔",
        "persian_text": "و از شهری که در آن بودیم بپرس، و از کاروانی که با آن آمدیم، که ما راستگوییم.",
        "english_text": "And ask the town in which we were and the caravan in which we came, and indeed, we are truthful.",
        "transliteration": "Was’alil qaryata allatī kunnā fīhā wal-‘īra allatī aqbalnā fīhā wa innā laṣādiqūn",
        "verse_number": "82",
    },
    {
        "arabic_text": "قَالَ بَلْ سَوَّلَتْ لَكُمْ أَنفُسُكُمْ أَمْرًا ۖ فَصَبْرٌ جَمِيلٌ ۖ عَسَى اللَّهُ أَن يَأْتِيَنِي بِهِمْ جَمِيعًا ۚ إِنَّهُ هُوَ الْعَلِيمُ الْحَكِيمُ",
        "urdu_text": "اس نے کہا: بلکہ تمہارے نفس نے تمہیں کوئی بات سمجھا دی ہے، پس صبر ہی بہتر ہے۔ امید ہے کہ اللہ ان سب کو میرے پاس لے آئے گا۔ بے شک وہی علم والا، حکمت والا ہے۔",
        "persian_text": "گفت: بلکه نفس‌های شما کاری را برایتان آراسته است. پس صبری نیکو لازم است، امید است خدا همه‌ی آنان را نزد من آورد، بی‌گمان او دانا و حکیم است.",
        "english_text": "He said, 'Rather, your souls have enticed you to something, so patience is most fitting. Perhaps Allah will bring them all to me; indeed, it is He who is the Knowing, the Wise.'",
        "transliteration": "Qāla bal sawwalat lakum anfusukum amrā, fa ṣabrun jamīl, ‘asā Allāhu an ya’tiyanī bihim jamī‘ā, innahu huwa al-‘alīmu al-ḥakīm",
        "verse_number": "83",
    },
    {
        "arabic_text": "وَتَوَلَّىٰ عَنْهُمْ وَقَالَ يَا أَسَفَىٰ عَلَىٰ يُوسُفَ وَابْيَضَّتْ عَيْنَاهُ مِنَ الْحُزْنِ فَهُوَ كَظِيمٌ",
        "urdu_text": "اور وہ ان سے منہ پھیر کر کہنے لگا: ہائے افسوس یوسف پر! اور غم کے مارے اس کی آنکھیں سفید ہو گئیں، وہ دل ہی دل میں غمگین رہتا تھا۔",
        "persian_text": "و از آنان روی گرداند و گفت: ای اندوه من بر یوسف! و از اندوه چشمانش سفید شد و اندوه خود را فرو می‌خورد.",
        "english_text": "And he turned away from them and said, 'Oh, my sorrow over Joseph!' and his eyes became white from grief, and he was of those who suppress [their sorrow].",
        "transliteration": "Wa tawallā ‘anhum wa qāla yā asafā ‘alā Yūsuf, wabyaḍḍat ‘aynāhu min al-ḥuzni fahuwa kaẓīm",
        "verse_number": "84",
    },
    {
        "arabic_text": "قَالُوا تَاللَّهِ تَفْتَأُ تَذْكُرُ يُوسُفَ حَتَّىٰ تَكُونَ حَرَضًا أَوْ تَكُونَ مِنَ الْهَالِكِينَ",
        "urdu_text": "انہوں نے کہا: اللہ کی قسم! آپ تو یوسف کو یاد کرتے ہی رہیں گے یہاں تک کہ بیمار ہو جائیں یا ہلاک ہو جائیں۔",
        "persian_text": "گفتند: به خدا سوگند، تو همواره یوسف را یاد می‌کنی تا آنکه بیمار یا از هلاک‌شدگان شوی.",
        "english_text": "They said, 'By Allah, you will not cease remembering Joseph until you become fatally ill or become of those who perish.'",
        "transliteration": "Qālū tallāhi tafta’u tadhkuru Yūsuf ḥattā takūna ḥaraḍan aw takūna minal hālikīn",
        "verse_number": "85",
    },
    {
        "arabic_text": "قَالَ إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ وَأَعْلَمُ مِنَ اللَّهِ مَا لَا تَعْلَمُونَ",
        "urdu_text": "اس نے کہا: میں تو اپنی پریشانی اور غم اللہ ہی سے بیان کرتا ہوں، اور میں اللہ کی طرف سے وہ جانتا ہوں جو تم نہیں جانتے۔",
        "persian_text": "گفت: من شکایت اندوه و غمم را تنها به خدا می‌برم، و از خدا چیزی می‌دانم که شما نمی‌دانید.",
        "english_text": "He said, 'I only complain of my suffering and my grief to Allah, and I know from Allah that which you do not know.'",
        "transliteration": "Qāla innamā ashkū baththī wa ḥuznī ilā Allāh, wa a‘lamu mina Allāhi mā lā ta‘lamūn",
        "verse_number": "86",
    },
    {
        "arabic_text": "يَا بَنِيَّ اذْهَبُوا فَتَحَسَّسُوا مِن يُوسُفَ وَأَخِيهِ وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ",
        "urdu_text": "اے میرے بیٹو! جاؤ اور یوسف اور اس کے بھائی کی تلاش کرو، اور اللہ کی رحمت سے نا امید مت ہو۔ یقیناً اللہ کی رحمت سے نا امید تو صرف کافر لوگ ہوتے ہیں۔",
        "persian_text": "ای پسران من! بروید و از یوسف و برادرش جستجو کنید، و از رحمت خدا نومید مشوید، زیرا جز کافران کسی از رحمت خدا نومید نمی‌شود.",
        "english_text": "O my sons, go and search for Joseph and his brother and despair not of relief from Allah. Indeed, none despairs of relief from Allah except the disbelieving people.",
        "transliteration": "Yā baniyya idhhabū fataḥassasū min Yūsufa wa akhīhi wa lā tay’asū min rawḥillāh, innahu lā yay’asu min rawḥillāhi illal qawmul kāfirūn",
        "verse_number": "87",
    },
    {
        "arabic_text": "فَلَمَّا دَخَلُوا عَلَيْهِ قَالُوا يَا أَيُّهَا الْعَزِيزُ مَسَّنَا وَأَهْلَنَا الضُّرُّ وَجِئْنَا بِبِضَاعَةٍ مُّزْجَاةٍ فَأَوْفِ لَنَا الْكَيْلَ وَتَصَدَّقْ عَلَيْنَا ۖ إِنَّ اللَّهَ يَجْزِي الْمُتَصَدِّقِينَ",
        "urdu_text": "پھر جب وہ اس کے پاس داخل ہوئے تو کہنے لگے: اے عزیزِ مصر! ہم اور ہمارے گھر والے سخت مصیبت میں ہیں، اور ہم تھوڑے سے ناقص مال کے ساتھ آئے ہیں، لہٰذا ہمارے لیے پورا پیمانہ دے دیجیے اور ہم پر صدقہ کیجیے، بے شک اللہ صدقہ کرنے والوں کو بدلہ دیتا ہے۔",
        "persian_text": "پس چون نزد او درآمدند، گفتند: ای عزیز! ما و خانواده‌مان گرفتار سختی شده‌ایم و کالای ناچیزی آورده‌ایم، پس پیمانه را برای ما کامل کن و بر ما صدقه ده، بی‌گمان خدا صدقه‌دهندگان را پاداش می‌دهد.",
        "english_text": "So when they entered upon him, they said, 'O noble one, adversity has touched us and our family, and we have come with goods poor in quality, so give us full measure and be charitable to us. Indeed, Allah rewards the charitable.'",
        "transliteration": "Falammā dakhalū ‘alayhi qālū yā ayyuhal ‘azīzu massanā wa ahlanā aḍ-ḍurr wa ji’nā bi biḍā‘atin muzjāh, fa awfi lanā al-kayl wa taṣaddaq ‘alaynā, inna Allāha yajzī al-mutaṣaddiqīn",
        "verse_number": "88",
    },
    {
        "arabic_text": "قَالَ هَلْ عَلِمْتُم مَّا فَعَلْتُم بِیُوسُفَ وَأَخِيهِ إِذْ أَنتُمْ جَاهِلُونَ",
        "urdu_text": "اس نے کہا: کیا تم جانتے ہو کہ تم نے یوسف اور اس کے بھائی کے ساتھ کیا کیا تھا جب تم نادان تھے؟",
        "persian_text": "گفت: آیا دانستید با یوسف و برادرش چه کردید هنگامی که نادان بودید؟",
        "english_text": "He said, 'Do you know what you did with Joseph and his brother when you were ignorant?'",
        "transliteration": "Qāla hal ‘alimtum mā fa‘altum bi Yūsufa wa akhīhi idh antum jāhilūn",
        "verse_number": "89",
    },
    {
        "arabic_text": "قَالُوا أَإِنَّكَ لَأَنتَ يُوسُفُ ۖ قَالَ أَنَا يُوسُفُ وَهَٰذَا أَخِي ۖ قَدْ مَنَّ اللَّهُ عَلَيْنَا ۖ إِنَّهُ مَن يَتَّقِ وَيَصْبِرْ فَإِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ",
        "urdu_text": "انہوں نے کہا: کیا تم واقعی یوسف ہو؟ اس نے کہا: میں ہی یوسف ہوں اور یہ میرا بھائی ہے، اللہ نے ہم پر احسان کیا ہے۔ بے شک جو تقویٰ اختیار کرے اور صبر کرے تو اللہ نیکی کرنے والوں کا اجر ضائع نہیں کرتا۔",
        "persian_text": "گفتند: آیا تو همان یوسفی؟ گفت: آری، من یوسفم و این برادر من است، خدا بر ما منت نهاده است. بی‌گمان هر که پرهیزکاری و شکیبایی کند، خدا پاداش نیکوکاران را ضایع نمی‌کند.",
        "english_text": "They said, 'Are you indeed Joseph?' He said, 'I am Joseph, and this is my brother. Allah has certainly favored us. Indeed, whoever fears Allah and is patient—then indeed, Allah does not allow to be lost the reward of those who do good.'",
        "transliteration": "Qālū a innaka la anta Yūsuf, qāla anā Yūsuf wa hādhā akhī, qad manna Allāhu ‘alaynā, innahu man yattaqi wa yaṣbir fa inna Allāha lā yuḍī‘u ajral muḥsinīn",
        "verse_number": "90",
    },
    {
        "arabic_text": "قَالُوا تَاللَّهِ لَقَدْ آثَرَكَ اللَّهُ عَلَيْنَا وَإِن كُنَّا لَخَاطِئِينَ",
        "urdu_text": "انہوں نے کہا: اللہ کی قسم! یقیناً اللہ نے آپ کو ہم پر فضیلت دی ہے، اور بے شک ہم خطا کار تھے۔",
        "persian_text": "گفتند: به خدا سوگند، خدا تو را بر ما برتری داده است، و بی‌گمان ما خطاکار بودیم.",
        "english_text": "They said, 'By Allah, certainly Allah has preferred you over us, and indeed we have been sinners.'",
        "transliteration": "Qālū tallāhi laqad ātharaka Allāhu ‘alaynā wa in kunnā lakhāṭi’īn",
        "verse_number": "91",
    },
    {
        "arabic_text": "قَالَ لَا تَثْرِيبَ عَلَيْكُمُ الْيَوْمَ ۖ يَغْفِرُ اللَّهُ لَكُمْ وَهُوَ أَرْحَمُ الرَّاحِمِينَ",
        "urdu_text": "یوسف نے کہا: آج تم پر کوئی ملامت نہیں، اللہ تمہیں معاف کرے، اور وہ سب رحم کرنے والوں میں سب سے زیادہ رحم کرنے والا ہے۔",
        "persian_text": "گفت: امروز بر شما هیچ سرزنشی نیست، خدا شما را بیامرزد، و او مهربان‌ترین مهربانان است.",
        "english_text": "He said, 'No blame will there be upon you today. Allah will forgive you; and He is the Most Merciful of the merciful.'",
        "transliteration": "Qāla lā tathrība ‘alaykum al-yawm, yaghfirullāhu lakum wa huwa arḥamur rāḥimīn",
        "verse_number": "92",
    },
    {
        "arabic_text": "اذْهَبُوا بِقَمِيصِي هَٰذَا فَأَلْقُوهُ عَلَىٰ وَجْهِ أَبِي يَأْتِ بَصِيرًا وَأْتُونِي بِأَهْلِكُمْ أَجْمَعِينَ",
        "urdu_text": "میرا یہ کرتا لے جاؤ اور میرے باپ کے چہرے پر ڈال دو، ان کی بینائی لوٹ آئے گی، اور اپنے سب گھر والوں کو میرے پاس لے آؤ۔",
        "persian_text": "این پیراهن مرا ببرید و بر چهره پدرم افکنید تا بینا گردد، و همه‌ی خانواده‌تان را نزد من بیاورید.",
        "english_text": "Take this shirt of mine and cast it over the face of my father; he will become seeing. And bring me your family, all together.",
        "transliteration": "Idhhabū biqamīṣī hādhā fa alqūhu ‘alā wajhi abī ya’ti baṣīrā, wa’tūnī bi ahlikum ajma‘īn",
        "verse_number": "93",
    },
    {
        "arabic_text": "وَلَمَّا فَصَلَتِ الْعِيرُ قَالَ أَبُوهُمْ إِنِّي لَأَجِدُ رِيحَ يُوسُفَ لَوْلَا أَن تُفَنِّدُونِ",
        "urdu_text": "اور جب قافلہ روانہ ہوا تو ان کے باپ نے کہا: میں یوسف کی خوشبو محسوس کر رہا ہوں اگر تم مجھے خبطی نہ کہو۔",
        "persian_text": "و چون کاروان روانه شد، پدرشان گفت: من بوی یوسف را احساس می‌کنم، اگر مرا دیوانه نخوانید.",
        "english_text": "And when the caravan departed [from Egypt], their father said, 'Indeed, I find the smell of Joseph [and would say that he was alive] if you did not think me weakened in mind.'",
        "transliteration": "Wa lammā faṣalatil ‘īru qāla abūhum innī la ajidu rīḥa Yūsuf law lā an tufannidūn",
        "verse_number": "94",
    },
    {
        "arabic_text": "قَالُوا تَاللَّهِ إِنَّكَ لَفِي ضَلَالِكَ الْقَدِيمِ",
        "urdu_text": "انہوں نے کہا: اللہ کی قسم! آپ تو اب بھی اپنی پرانی گمراہی میں ہیں۔",
        "persian_text": "گفتند: به خدا سوگند، تو هنوز در همان گمراهی دیرینه‌ی خودی.",
        "english_text": "They said, 'By Allah, indeed you are in your same old error.'",
        "transliteration": "Qālū tallāhi innaka lafī ḍalālika al-qadīm",
        "verse_number": "95",
    },
    {
        "arabic_text": "فَلَمَّا أَن جَاءَ الْبَشِيرُ أَلْقَاهُ عَلَىٰ وَجْهِهِ فَارْتَدَّ بَصِيرًا ۖ قَالَ أَلَمْ أَقُل لَّكُمْ إِنِّي أَعْلَمُ مِنَ اللَّهِ مَا لَا تَعْلَمُونَ",
        "urdu_text": "پھر جب خوشخبری لانے والا آیا اور اس نے وہ کرتا اس کے چہرے پر ڈال دیا تو وہ بینا ہو گیا، کہنے لگا: کیا میں نے تم سے نہیں کہا تھا کہ میں اللہ کی طرف سے وہ جانتا ہوں جو تم نہیں جانتے۔",
        "persian_text": "چون مژده‌رسان آمد و آن را بر چهره‌اش افکند، بینا شد، گفت: آیا به شما نگفتم که از خدا چیزی می‌دانم که شما نمی‌دانید؟",
        "english_text": "And when the bearer of good tidings arrived, he cast it over his face, and he returned [once again] seeing. He said, 'Did I not tell you that I know from Allah that which you do not know?'",
        "transliteration": "Falammā an jā’a al-bashīr alqāhu ‘alā wajhihi fartadda baṣīrā, qāla a lam aqul lakum innī a‘lamu mina Allāhi mā lā ta‘lamūn",
        "verse_number": "96",
    },
    {
        "arabic_text": "قَالُوا يَا أَبَانَا اسْتَغْفِرْ لَنَا ذُنُوبَنَا إِنَّا كُنَّا خَاطِئِينَ",
        "urdu_text": "انہوں نے کہا: اے ہمارے ابا! ہمارے گناہوں کی بخشش کے لیے دعا کیجیے، بے شک ہم خطا کار تھے۔",
        "persian_text": "گفتند: ای پدر ما! برای ما از گناهانمان آمرزش بخواه، که ما خطاکار بودیم.",
        "english_text": "They said, 'O our father, ask for us forgiveness of our sins; indeed, we have been sinners.'",
        "transliteration": "Qālū yā abānā istaghfir lanā dhunūbanā innā kunnā khāṭi’īn",
        "verse_number": "97",
    },
    {
        "arabic_text": "قَالَ سَوْفَ أَسْتَغْفِرُ لَكُمْ رَبِّي ۖ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ",
        "urdu_text": "اس نے کہا: میں جلد ہی تمہارے لیے اپنے رب سے بخشش مانگوں گا، بے شک وہی بڑا بخشنے والا، نہایت مہربان ہے۔",
        "persian_text": "گفت: به زودی برای شما از پروردگارم آمرزش خواهم خواست، که او آمرزنده و مهربان است.",
        "english_text": "He said, 'I will ask forgiveness for you from my Lord. Indeed, it is He who is the Forgiving, the Merciful.'",
        "transliteration": "Qāla sawfa astaghfiru lakum rabbī innahu huwa al-ghafūru ar-raḥīm",
        "verse_number": "98",
    },
    {
        "arabic_text": "فَلَمَّا دَخَلُوا عَلَىٰ يُوسُفَ آوَىٰ إِلَيْهِ أَبَوَيْهِ وَقَالَ ادْخُلُوا مِصْرَ إِن شَاءَ اللَّهُ آمِنِينَ",
        "urdu_text": "پھر جب وہ یوسف کے پاس آئے تو اس نے اپنے والدین کو اپنے پاس جگہ دی، اور کہا: ان شاء اللہ تم امن و امان کے ساتھ مصر میں داخل ہو جاؤ۔",
        "persian_text": "چون بر یوسف درآمدند، پدر و مادرش را نزد خود جای داد و گفت: به خواست خدا، در امنیت وارد مصر شوید.",
        "english_text": "And when they entered upon Joseph, he took his parents to himself and said, 'Enter Egypt, Allah willing, safe [and secure].'",
        "transliteration": "Falammā dakhalū ‘alā Yūsufa āwā ilayhi abawayhi wa qāla udkhulū Miṣra in shā’a Allāhu āminīn",
        "verse_number": "99",
    },
    {
        "arabic_text": "وَرَفَعَ أَبَوَيْهِ عَلَى الْعَرْشِ وَخَرُّوا لَهُ سُجَّدًا ۖ وَقَالَ يَا أَبَتِ هَٰذَا تَأْوِيلُ رُؤْيَايَ مِن قَبْلُ ۖ قَدْ جَعَلَهَا رَبِّي حَقًّا ۖ وَقَدْ أَحْسَنَ بِي إِذْ أَخْرَجَنِي مِنَ السِّجْنِ وَجَاءَ بِكُم مِّنَ الْبَدْوِ مِن بَعْدِ أَن نَّزَغَ الشَّيْطَانُ بَيْنِي وَبَيْنَ إِخْوَتِي ۚ إِنَّ رَبِّي لَطِيفٌ لِّمَا يَشَاءُ ۚ إِنَّهُ هُوَ الْعَلِيمُ الْحَكِيمُ",
        "urdu_text": "اور اس نے اپنے والدین کو تخت پر بٹھایا اور سب اس کے سامنے سجدہ میں گر پڑے۔ اس نے کہا: اے میرے ابا! یہ ہے میری وہ خواب کی تعبیر جو میں نے دیکھی تھی، میرے رب نے اسے سچ کر دکھایا اور مجھ پر احسان کیا جب اس نے مجھے قید سے نکالا اور تمہیں گاؤں سے لے آیا، بعد اس کے کہ شیطان نے میرے اور میرے بھائیوں کے درمیان فساد ڈال دیا تھا۔ بے شک میرا رب جس کے لیے چاہے لطف کرنے والا ہے، بے شک وہ علم والا، حکمت والا ہے۔",
        "persian_text": "و پدر و مادرش را بر تخت نشاند و آنان برای او به سجده افتادند. گفت: ای پدر! این است تعبیر خواب پیشین من، پروردگارم آن را راست گردانید و بر من نیکی کرد، هنگامی که مرا از زندان بیرون آورد و شما را از بادیه نزد من آورد، پس از آنکه شیطان میان من و برادرانم را به هم زد. بی‌گمان پروردگارم در آنچه بخواهد لطیف است؛ او دانا و حکیم است.",
        "english_text": "And he raised his parents upon the throne, and they bowed to him in prostration. And he said, 'O my father, this is the explanation of my vision of before. My Lord has made it reality. And He was certainly good to me when He took me out of prison and brought you from the desert after Satan had sown discord between me and my brothers. Indeed, my Lord is Subtle in what He wills. Indeed, it is He who is the Knowing, the Wise.'",
        "transliteration": "Wa rafa‘a abawayhi ‘alal ‘arshi wa kharrū lahu sujjadā, wa qāla yā abati hādhā ta’wīlu ru’yāya min qablu qad ja‘alahā rabbī ḥaqqā, wa qad aḥsana bī idh akhrajani minas-sijni wa jā’a bikum minal badwi min ba‘di an nazagha ash-shayṭānu baynī wa bayna ikhwatī, innā rabbī laṭīfun limā yashā’, innahu huwa al-‘alīmu al-ḥakīm",
        "verse_number": "100",
    },
    {
        "arabic_text": "رَبِّ قَدْ آتَيْتَنِي مِنَ الْمُلْكِ وَعَلَّمْتَنِي مِن تَأْوِيلِ الْأَحَادِيثِ ۚ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ ۖ أَنتَ وَلِيِّي فِي الدُّنْيَا وَالْآخِرَةِ ۖ تَوَفَّنِي مُسْلِمًا وَأَلْحِقْنِي بِالصَّالِحِينَ",
        "urdu_text": "اے میرے رب! تو نے مجھے حکومت میں سے حصہ دیا اور مجھے خوابوں کی تعبیر سکھائی، آسمانوں اور زمین کے پیدا کرنے والے! تو ہی دنیا و آخرت میں میرا کارساز ہے، مجھے اسلام کی حالت میں وفات دے اور نیکوں کے ساتھ ملا۔",
        "persian_text": "پروردگارا! تو بخشی از فرمانروایی به من دادی و از تعبیر خواب‌ها به من آموختی، ای آفریننده آسمان‌ها و زمین! تو در دنیا و آخرت سرپرست منی، مرا مسلمان بمیران و به شایستگان بپیوندان.",
        "english_text": "My Lord, You have given me something of sovereignty and taught me of the interpretation of dreams. Creator of the heavens and the earth, You are my protector in this world and the Hereafter. Cause me to die a Muslim and join me with the righteous.",
        "transliteration": "Rabbi qad ātaytanī mina al-mulki wa ‘allamtanī min ta’wīlil aḥādīth, fāṭiras-samāwāti wal-arḍ, anta waliyyī fid-dunyā wal-ākhirah, tawaffanī musliman wa alḥiqnī biṣ-ṣāliḥīn",
        "verse_number": "101",
    },
    {
        "arabic_text": "ذَٰلِكَ مِنْ أَنبَاءِ الْغَيْبِ نُوحِيهِ إِلَيْكَ ۖ وَمَا كُنتَ لَدَيْهِمْ إِذْ أَجْمَعُوا أَمْرَهُمْ وَهُمْ يَمْكُرُونَ",
        "urdu_text": "یہ غیب کی خبروں میں سے ہے جو ہم تمہاری طرف وحی کر رہے ہیں، اور تم ان کے پاس نہ تھے جب انہوں نے اپنے معاملے پر اتفاق کیا اور فریب کر رہے تھے۔",
        "persian_text": "این از خبرهای غیب است که ما آن را بر تو وحی می‌کنیم، و تو نزد آنان نبودی هنگامی که تصمیم گرفتند و مکر می‌کردند.",
        "english_text": "That is from the news of the unseen which We reveal to you, [O Muhammad]. And you were not with them when they put together their plan while they conspired.",
        "transliteration": "Dhālika min anba’il ghaybi nūḥīhi ilayk, wa mā kunta ladayhim idh ajma‘ū amrahum wa hum yamkurūn",
        "verse_number": "102",
    },
    {
        "arabic_text": "وَمَا أَكْثَرُ النَّاسِ وَلَوْ حَرَصْتَ بِمُؤْمِنِينَ",
        "urdu_text": "اور اکثر لوگ ایمان لانے والے نہیں، چاہے تم کتنی ہی کوشش کر لو۔",
        "persian_text": "و بیشتر انسان‌ها ایمان نخواهند آورد، هر چند تو بسیار بکوشی.",
        "english_text": "And most of the people, although you strive for it, are not believers.",
        "transliteration": "Wa mā aktharu an-nāsi walaw ḥaraṣta bimu’minīn",
        "verse_number": "103",
    },
    {
        "arabic_text": "وَمَا تَسْأَلُهُمْ عَلَيْهِ مِنْ أَجْرٍ ۚ إِنْ هُوَ إِلَّا ذِكْرٌ لِّلْعَالَمِينَ",
        "urdu_text": "اور تم ان سے اس پر کوئی اجرت نہیں مانگتے، یہ تو بس تمام جہانوں کے لیے ایک نصیحت ہے۔",
        "persian_text": "و تو از آنان مزدی بر آن نمی‌خواهی، این جز پندی برای جهانیان نیست.",
        "english_text": "And you do not ask of them for it any payment. It is not except a reminder to the worlds.",
        "transliteration": "Wa mā tas’aluhum ‘alayhi min ajr, in huwa illā dhikrun lil-‘ālamīn",
        "verse_number": "104",
    },
    {
        "arabic_text": "وَكَأَيِّن مِّنْ آيَةٍ فِي السَّمَاوَاتِ وَالْأَرْضِ يَمُرُّونَ عَلَيْهَا وَهُمْ عَنْهَا مُعْرِضُونَ",
        "urdu_text": "اور کتنی ہی نشانیاں ہیں آسمانوں اور زمین میں جن پر وہ گزرتے ہیں مگر ان سے منہ موڑ لیتے ہیں۔",
        "persian_text": "و چه بسیار نشانه‌ها در آسمان‌ها و زمین که بر آن می‌گذرند و از آن روی‌گردانند.",
        "english_text": "And how many a sign within the heavens and earth do they pass over while they, therefrom, are turning away.",
        "transliteration": "Wa ka’ayyin min āyatin fis-samāwāti wal-arḍi yamurrūna ‘alayhā wa hum ‘anhā mu‘riḍūn",
        "verse_number": "105",
    },
    {
        "arabic_text": "وَمَا يُؤْمِنُ أَكْثَرُهُم بِاللَّهِ إِلَّا وَهُم مُّشْرِكُونَ",
        "urdu_text": "اور ان میں سے اکثر لوگ اللہ پر ایمان نہیں رکھتے مگر شرک کرتے ہیں۔",
        "persian_text": "و بیشتر آنان به خدا ایمان نمی‌آورند مگر آنکه مشرک‌اند.",
        "english_text": "And most of them believe not in Allah except while they associate others with Him.",
        "transliteration": "Wa mā yu’minu aktharuhum billāhi illā wa hum mushrikūn",
        "verse_number": "106",
    },
    {
        "arabic_text": "أَفَأَمِنُوا أَن تَأْتِيَهُمْ غَاشِيَةٌ مِّنْ عَذَابِ اللَّهِ أَوْ تَأْتِيَهُمُ السَّاعَةُ بَغْتَةً وَهُمْ لَا يَشْعُرُونَ",
        "urdu_text": "کیا وہ اس بات سے بے خوف ہیں کہ ان پر اللہ کا عذاب چھا جائے یا قیامت اچانک آجائے اور وہ خبر بھی نہ لیں؟",
        "persian_text": "آیا ایمن شدند از آنکه عذابی فراگیر از سوی خدا بر آنان درآید، یا آنکه قیامت ناگهان بر آنان برسد در حالی که آگاه نباشند؟",
        "english_text": "Then do they feel secure that there will not come to them an overwhelming punishment of Allah or that the Hour will not come upon them suddenly while they do not perceive?",
        "transliteration": "Afa’aminū an ta’tiyahum ghāshiyatun min ‘adhābillāh aw ta’tiyahumus-sā‘atu baghtatan wa hum lā yash‘urūn",
        "verse_number": "107",
    },
    {
        "arabic_text": "قُلْ هَٰذِهِ سَبِيلِي أَدْعُو إِلَى اللَّهِ ۚ عَلَىٰ بَصِيرَةٍ أَنَا وَمَنِ اتَّبَعَنِي ۖ وَسُبْحَانَ اللَّهِ وَمَا أَنَا مِنَ الْمُشْرِكِينَ",
        "urdu_text": "کہہ دو: یہی میرا راستہ ہے، میں اللہ کی طرف بلاتا ہوں یقین کی بصیرت پر، میں اور وہ جو میرا پیرو ہے، اور اللہ پاک ہے، اور میں مشرکوں میں سے نہیں ہوں۔",
        "persian_text": "بگو: این است راه من، من و هر که مرا پیروی کند با بصیرت به سوی خدا دعوت می‌کنیم، و خدا را منزه می‌دانیم، و من از مشرکان نیستم.",
        "english_text": "Say, 'This is my way; I invite to Allah with insight, I and those who follow me. And exalted is Allah; and I am not of those who associate others with Him.'",
        "transliteration": "Qul hādhihi sabīlī ad‘ū ilallāhi ‘alā baṣīrah, anā wa mani-ttaba‘anī, wa subḥānallāhi wa mā anā minal mushrikīn",
        "verse_number": "108",
    },
    {
        "arabic_text": "وَمَا أَرْسَلْنَا مِن قَبْلِكَ إِلَّا رِجَالًا نُّوحِي إِلَيْهِم مِّنْ أَهْلِ الْقُرَىٰ ۗ أَفَلَمْ يَسِيرُوا فِي الْأَرْضِ فَيَنظُرُوا كَيْفَ كَانَ عَاقِبَةُ الَّذِينَ مِن قَبْلِهِمْ ۗ وَلَدَارُ الْآخِرَةِ خَيْرٌ لِّلَّذِينَ اتَّقَوْا ۗ أَفَلَا تَعْقِلُونَ",
        "urdu_text": "اور ہم نے تم سے پہلے بھی بستیوں کے رہنے والے مردوں کو ہی بھیجا جن کی طرف ہم وحی کرتے تھے، کیا وہ زمین میں چلے پھرے نہیں تاکہ دیکھ لیتے کہ ان سے پہلے والوں کا انجام کیا ہوا؟ اور یقیناً آخرت کا گھر ان لوگوں کے لیے بہتر ہے جنہوں نے تقویٰ اختیار کیا، کیا تم سمجھتے نہیں؟",
        "persian_text": "و پیش از تو جز مردانی از مردم شهرها نفرستادیم که بر آنان وحی می‌کردیم. آیا در زمین نگردیده‌اند تا ببینند سرانجام کسانی که پیش از آنان بودند چه شد؟ و بی‌گمان سرای آخرت برای پرهیزگاران بهتر است؛ آیا نمی‌اندیشید؟",
        "english_text": "And We sent not before you except men to whom We revealed from among the people of cities. So have they not traveled through the earth and observed how was the end of those before them? And the home of the Hereafter is best for those who fear Allah; then will you not reason?",
        "transliteration": "Wa mā arsalnā min qablika illā rijālan nūḥī ilayhim min ahli al-qurā, afa lam yasīrū fil arḍi fa yanẓurū kayfa kāna ‘āqibatul-ladhīna min qablihim, wa ladāru al-ākhirati khayrun lilladhīna ittaqaw, afalā ta‘qilūn",
        "verse_number": "109",
    },
    {
        "arabic_text": "حَتَّىٰ إِذَا اسْتَيْأَسَ الرُّسُلُ وَظَنُّوا أَنَّهُمْ قَدْ كُذِبُوا جَاءَهُمْ نَصْرُنَا فَنُجِّيَ مَن نَّشَاءُ ۖ وَلَا يُرَدُّ بَأْسُنَا عَنِ الْقَوْمِ الْمُجْرِمِينَ",
        "urdu_text": "یہاں تک کہ جب رسول نا امید ہو گئے اور انہوں نے گمان کیا کہ ان سے جھوٹ کہا گیا ہے تو ان کے پاس ہماری مدد آ گئی، پھر ہم نے جسے چاہا بچا لیا، اور ہمارا عذاب مجرم لوگوں سے نہیں ٹلتا۔",
        "persian_text": "تا آنگاه که پیامبران نومید شدند و پنداشتند که دروغ پنداشته شده‌اند، یاری ما به آنان رسید، پس هر که را خواستیم نجات دادیم، و عذاب ما از مردم گناهکار بازگردانده نمی‌شود.",
        "english_text": "Until when the messengers despaired and thought that they had been denied, there came to them Our victory, and whoever We willed was saved. And Our punishment cannot be repelled from the people who are criminals.",
        "transliteration": "Ḥattā idhā istay’asa ar-rusulu wa ẓannū annahum qad kudhibū jā’ahum naṣrunā fa nuzziya man nashā’, wa lā yuraddu ba’sunā ‘anil qawmi al-mujrimīn",
        "verse_number": "110",
    },
    {
        "arabic_text": "لَقَدْ كَانَ فِي قَصَصِهِمْ عِبْرَةٌ لِّأُولِي الْأَلْبَابِ ۗ مَا كَانَ حَدِيثًا يُفْتَرَىٰ وَلَٰكِن تَصْدِيقَ الَّذِي بَيْنَ يَدَيْهِ وَتَفْصِيلَ كُلِّ شَيْءٍ وَهُدًى وَرَحْمَةً لِّقَوْمٍ يُؤْمِنُونَ",
        "urdu_text": "یقیناً ان کے قصوں میں عقلمندوں کے لیے عبرت ہے، یہ (قرآن) کوئی گھڑا ہوا کلام نہیں بلکہ اس سے پہلے والی وحی کی تصدیق ہے، اور ہر چیز کی تفصیل، اور ایمان والوں کے لیے ہدایت اور رحمت ہے۔",
        "persian_text": "در سرگذشت آنان عبرتی برای خردمندان است؛ این سخنی ساختگی نیست، بلکه تصدیق آنچه پیش از آن است و شرح هر چیز و هدایت و رحمتی است برای مؤمنان.",
        "english_text": "There was certainly in their stories a lesson for those of understanding. Never was the Qur'an a narration invented, but a confirmation of what was before it and a detailed explanation of all things and guidance and mercy for a people who believe.",
        "transliteration": "Laqad kāna fī qaṣaṣihim ‘ibratun li’ulil albāb, mā kāna ḥadīthan yuftarā walākin taṣdīqa alladhī bayna yadayhi wa tafṣīla kulli shay’in wa hudan wa raḥmatan liqawmin yu’minūn",
        "verse_number": "111",
    },
]
