ayats = [
  {
    "verse_number": 1,
    "english_text": "Verily, We revealed it on the Grand Night.",
    "arabic_text": "اِنَّآ اَنزَلْنٰهُ فِي لَيْلَةِ الْقَدْرِ",
    "urdu_text": "بیشک ہم نے اسے شب قدر میں نازل کیا",
    "persian_text": "به راستی ما آن را در شب قدر نازل کردیم",
    "transliteration": "Innaa anzalnaahu fee laylatul-qadr",
  },
  {
    "verse_number": 2,
    "english_text": "And what do you know what a great thing this Grand Night is?",
    "arabic_text": "وَ مَآ اَدْرٰكَ مَا لَيْلَةُ الْقَدْرِ",
    "urdu_text": "اور تم کیا جانو کہ شب قدر کیا ہے",
    "persian_text": "و تو چه می‌دانی که شب قدر چیست",
    "transliteration": "Wa maa adraaka ma laylatul-qadr",
  },
  {
    "verse_number": 3,
    "english_text": "The Grand Night is better than a thousand months.",
    "arabic_text": "لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ اَلْفِ شَهْرٍ",
    "urdu_text": "شب قدر ہزار مہینوں سے بہتر ہے",
    "persian_text": "شب قدر بهتر از هزار ماه است",
    "transliteration": "Laylatul-qadri khayrum min alfi shahr",
  },
  {
    "verse_number": 4,
    "english_text": "The angels and the Holy Spirit descend in it by the permission of their Lord with all the affairs.",
    "arabic_text": "تَنَزَّلُ الْمَلٰٓئِكَةُ وَ الرُّوحُ فِيهَا بِاِذْنِ رَبِّهِم مِّن كُلِّ اَمْرٍ",
    "urdu_text": "اس میں فرشتے اور روح الامین اپنے رب کے حکم سے ہر کام کے لیے اترتے ہیں",
    "persian_text": "فرشتگان و روح در آن شب به اذن پروردگارشان برای هر کاری نازل می‌شوند",
    "transliteration": "Tanazzalul-malaa'ikatu war-roohu feehaa bi-idhni rabbihim min kulli amr",
  },
  {
    "verse_number": 5,
    "english_text": "Peace is this night until the rise of dawn.",
    "arabic_text": "سَلٰمٌ هِىَ حَتّٰى مَطْلَعِ الْفَجْرِ",
    "urdu_text": "یہ رات طلوع فجر تک سراسر سلامتی ہے",
    "persian_text": "این شب تا طلوع سپیده‌دم سراسر سلامتی است",
    "transliteration": "Salaamun hiya hattaa matla'il-fajr",
  },
]
