ayats = [
    {
        "verse_number": "1",
        "arabic_text": "وَيْلٌ لِّلْمُطَفِّفِينَ",
        "urdu_text": "خرابی هے ناپ تول میں کمی کرنے والوں کے لیے",
        "persian_text": "وای بر کم‌فروشان",
        "english_text": "Woe to those who give less [than due],",
        "transliteration": "Wailul lil-muṭaffifīn",
    },
    {
        "verse_number": "2",
        "arabic_text": "الَّذِينَ اِذَا اكْتَالُواْ عَلَى النَّاسِ يَسْتَوْفُونَ",
        "urdu_text": "جو لوگوں سے ناپ کر لیتے هیں تو پورا لیتے هیں",
        "persian_text": "آنان که چون از مردم پیمانه می‌گیرند، تمام می‌گیرند",
        "english_text": "Who, when they take a measure from people, take in full.",
        "transliteration": "Alladhīna idhāk tālū ‘ala an-nāsi yastawfūn",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَ اِذَا كَالُوهُمْ اَو وَّزَنُوهُمْ يُخْسِرُونَ",
        "urdu_text": "اور جب انهیں ناپ کر یا تول کر دیتے هیں تو کم دیتے هیں",
        "persian_text": "و چون برای آنان پیمانه یا وزن می‌کنند، کم می‌نهند",
        "english_text": "But if they give by measure or weight to them, they cause loss.",
        "transliteration": "Wa idhā kālūhum aw wazzanūhum yukhsirūn",
    },
    {
        "verse_number": "4",
        "arabic_text": "اَلَا يَظُنُّ اُولٰٓئِكَ اَنَّهُم مَّبْعُوثُونَ",
        "urdu_text": "کیا یه لوگ نهیں سمجھتے که انهیں اٹھایا جائے گا",
        "persian_text": "آیا اینان گمان نمی‌کنند که برانگیخته می‌شوند؟",
        "english_text": "Do they not think that they will be resurrected",
        "transliteration": "Alā yaẓunnu ūlā’ika annahum mab‘ūthūn",
    },
    {
        "verse_number": "5",
        "arabic_text": "لِيَوْمٍ عَظِيمٍ",
        "urdu_text": "ایک بڑے دن کے لیے",
        "persian_text": "برای روزی بزرگ",
        "english_text": "For a tremendous Day -",
        "transliteration": "Li-yawmin ‘aẓīm",
    },
    {
        "verse_number": "6",
        "arabic_text": "يَّوْمَ يَقُومُ النَّاسُ لِرَبِّ الْعٰلَمِينَ",
        "urdu_text": "جس دن لوگ رب العالمین کے حضور کھڑے هوں گے",
        "persian_text": "روزی که مردم برای پروردگار جهانیان می‌ایستند",
        "english_text": "The Day when mankind will stand before the Lord of the worlds?",
        "transliteration": "Yawma yaqūmu an-nāsu li-Rabbi al-‘ālamīn",
    },
    {
        "verse_number": "7",
        "arabic_text": "كَلَّآ اِنَّ كِتٰبَ الْفُجَّارِ لَفِى سِجِّينٍ",
        "urdu_text": "یقیناً بدکاروں کا نامه اعمال سیجّین میں هے",
        "persian_text": "هرگز چنین نیست، به‌راستی نامه عمل گناهکاران در سجّین است",
        "english_text": "No! Indeed, the record of the wicked is in sijjeen.",
        "transliteration": "Kallā inna kitāba al-fujjāri la fī sijjīn",
    },
    {
        "verse_number": "8",
        "arabic_text": "وَ مَآ اَدْرٰكَ مَا سِجِّينٍ",
        "urdu_text": "اور تمهیں کیا معلوم که سیجّین کیا هے؟",
        "persian_text": "و چه می‌دانی سجّین چیست؟",
        "english_text": "And what can make you know what is sijjeen?",
        "transliteration": "Wa mā adrāka mā sijjīn",
    },
    {
        "verse_number": "9",
        "arabic_text": "كِتٰبٌ مَّرْقُومٌ",
        "urdu_text": "ایک لکھی هوئی کتاب هے",
        "persian_text": "کتابی نوشته شده",
        "english_text": "It is their destination recorded in a register inscribed.",
        "transliteration": "Kitābun marqūm",
    },
    {
        "verse_number": "10",
        "arabic_text": "وَيْلٌ يَوْمَئِذٍ لِّلْمُكَذِّبِينَ",
        "urdu_text": "تباهی هے اس دن جھٹلانے والوں کے لیے",
        "persian_text": "وای بر تکذیب‌کنندگان در آن روز",
        "english_text": "Woe, that Day, to the deniers,",
        "transliteration": "Wailun yawma’idhin lil-mukadhdhibīn",
    },
    {
        "verse_number": "11",
        "arabic_text": "الَّذِينَ يُكَذِّبُونَ بِيَوْمِ الدِّينِ",
        "urdu_text": "وه جو جزا کے دن کو جھٹلاتے هیں",
        "persian_text": "کسانی که روز جزا را انکار می‌کنند",
        "english_text": "Those who deny the Day of Judgment.",
        "transliteration": "Alladhīna yukadhdhibūna biyawmi ad-dīn",
    },
    {
        "verse_number": "12",
        "arabic_text": "وَ مَا يُكَذِّبُ بِهِٓ اِلَّا كُلُّ مُعْتَدٍ اَثِيمٍ",
        "urdu_text": "اور اس کا انکار وهی کرتا هے جو حد سے بڑھنے والا گناهگار هے",
        "persian_text": "و آن را جز هر متجاوز گناهکارى انکار نمی‌کند",
        "english_text": "And none denies it except every sinful transgressor.",
        "transliteration": "Wa mā yukadhdhibu bihī illā kullu muʿ'tadin athīm",
    },
    {
        "verse_number": "13",
        "arabic_text": "اِذَا تُتْلَٰى عَلَيْهِ اٰيٰاتُنَا قَالَ اَسَاطِيرُ الْاَوَّلِينَ",
        "urdu_text": "جب اس پر هماری آیات پڑھی جاتی هیں تو کهتا هے: یه پهلوں کی کهانیاں هیں",
        "persian_text": "چون آيات ما بر او خوانده می‌شود، می‌گويد: اين افسانه‌هاى گذشتگان است",
        "english_text": "When Our verses are recited to him, he says, 'Legends of the former peoples.'",
        "transliteration": "Idhā tutlā ʿalayhi āyātunā qāla asāṭīru l-awwalīn",
    },
    {
        "verse_number": "14",
        "arabic_text": "كَلَّا ۖ بَلْ ۜ رَانَ عَلَٰى قُلُوبِهِم مَّا كَانُوا يَكْسِبُونَ",
        "urdu_text": "هرگز نهیں، بلکه ان کے دلوں پر ان کے اعمال کا زنگ چڑھ گیا هے",
        "persian_text": "چنین نیست، بلکه آنچه می‌کردند زنگار بر دل‌هایشان نهاده است",
        "english_text": "Nay! But on their hearts is the stain of that which they used to earn.",
        "transliteration": "Kallā bal rāna ʿalā qulūbihim mā kānū yaksibūn",
    },
    {
        "verse_number": "15",
        "arabic_text": "كَلَّآ اِنَّهُمْ عَن رَّبِّهِمْ يَوْمَئِذٍ لَّمَحْجُوبُونَ",
        "urdu_text": "هرگز نهیں! یقیناً وه اس دن اپنے رب سے اوٹ میں رکھے جائیں گے",
        "persian_text": "چنین نیست، در آن روز آنان از پروردگارشان محجوب‌اند",
        "english_text": "Nay! Surely, they will be veiled from their Lord that Day.",
        "transliteration": "Kallā innahum ʿan rabbihim yawma’idhin la-maḥjūbūn",
    },
    {
        "verse_number": "16",
        "arabic_text": "ثُمَّ اِنَّهُمْ لَصَالُوا الْجَحِيمِ",
        "urdu_text": "پھر وه ضرور جهنم میں داخل هوں گے",
        "persian_text": "سپس بی‌تردید وارد دوزخ خواهند شد",
        "english_text": "Then indeed, they will [enter and] burn in Hellfire.",
        "transliteration": "Thumma innahum laṣālū al-jaḥīm",
    },
    {
        "verse_number": "17",
        "arabic_text": "ثُمَّ يُقَالُ هٰذَا الَّذِى كُنتُم بِهِ تُكَذِّبُونَ",
        "urdu_text": "پھر کها جائے گا: یهی وه چیز هے جسے تم جھٹلایا کرتے تھے",
        "persian_text": "سپس گفته می‌شود: اين همان چيزی است كه آن را انكار مى‌كرديد",
        "english_text": "Then it will be said, 'This is what you used to deny.'",
        "transliteration": "Thumma yuqālu hādhā alladhī kuntum bihi tukadhdhibūn",
    },
    {
        "verse_number": "18",
        "arabic_text": "كَلَّآ اِنَّ كِتٰبَ الْاَبْرَارِ لَفِى عِلِّيِّينَ",
        "urdu_text": "یقیناً نیک لوگوں کا ریکارڈ اعلیٰ مقام پر هے",
        "persian_text": "بی‌گمان نامه اعمال نيكان در عليين است",
        "english_text": "Nay! Verily, the record of the righteous is in 'Illiyyīn.",
        "transliteration": "Kallā inna kitāba al-abrār la-fī ʿilliyyīn",
    },
    {
        "verse_number": "19",
        "arabic_text": "وَمَآ اَدْرٰكَ مَا عِلِّيُّونَ",
        "urdu_text": "اور تم کیا جانو که 'علیین' کیا هے؟",
        "persian_text": "و تو چه دانی که عليين چيست؟",
        "english_text": "And what will make you know what 'Illiyyīn is?",
        "transliteration": "Wa mā adrāka mā ʿilliyyūn",
    },
    {
        "verse_number": "20",
        "arabic_text": "كِتٰبٌ مَّرْقُومٌ",
        "urdu_text": "ایک لکھی هوئی کتاب هے",
        "persian_text": "نامه‌اى است نوشته شده",
        "english_text": "It is a written record.",
        "transliteration": "Kitābun marqūm",
    },
    {
        "verse_number": "21",
        "arabic_text": "يَّشْهَدُهُ الْمُقَرَّبُونَ",
        "urdu_text": "اس کے گواه مقرب فرشتے هوں گے",
        "persian_text": "مقربان گواه آن خواهند بود",
        "english_text": "Witnessed by those brought near [to Allah].",
        "transliteration": "Yashhaduhu al-muqarrabūn",
    },
    {
        "verse_number": "22",
        "arabic_text": "اِنَّ الْاَبْرَارَ لَفِى نَعِيمٍ",
        "urdu_text": "یقیناً نیک لوگ نعمتوں میں هوں گے",
        "persian_text": "بی‌گمان نيكان در نعمت خواهند بود",
        "english_text": "Indeed, the righteous will be in pleasure.",
        "transliteration": "Inna al-abrāra la-fī naʿīm",
    },
    {
        "verse_number": "23",
        "arabic_text": "عَلَى الْاَرَآئِكِ يَنظُرُونَ",
        "urdu_text": "وه تختوں پر بیٹھے نظارے کر رهے هوں گے",
        "persian_text": "بر تخت‌ها تكيه زده نظاره می‌کنند",
        "english_text": "On adorned couches, observing.",
        "transliteration": "ʿAlā al-arā’iki yanẓurūn",
    },
    {
        "verse_number": "24",
        "arabic_text": "تَعْرِفُ فِى وُجُوهِهِمْ نَضْرَةَ النَّعِيمِ",
        "urdu_text": "تو ان کے چهروں پر نعمتوں کی تازگی پهچان لے گا",
        "persian_text": "در چهره‌هايشان طراوت نعمت را می‌بينى",
        "english_text": "You will recognize in their faces the radiance of pleasure.",
        "transliteration": "Taʿrifu fī wujūhihim naḍrata al-naʿīm",
    },
    {
        "verse_number": "25",
        "arabic_text": "يُسْقَوْنَ مِن رَّحِيقٍ مَّخْتُومٍ",
        "urdu_text": "انهیں بند کی هوئی خالص شراب پلائی جائے گی",
        "persian_text": "از شرابی مهر شده نوشانده می‌شوند",
        "english_text": "They will be given to drink [pure] wine sealed.",
        "transliteration": "Yusqawna min raḥīqin makhtūm",
    },
    {
        "verse_number": "26",
        "arabic_text": "خِتٰمُهُ مِسْكٌ وَ فِى ذٰلِكَ فَلْيَتَنَافَسِ الْمُتَنافِسُونَ",
        "urdu_text": "جس کا خاتمه کستوری پر هوگا، اور اسی میں هوڑ کرنے والے مقابله کریں",
        "persian_text": "پايان آن مشک است، پس مشتاقان بايد در آن رقابت كنند",
        "english_text": "Its seal is musk – so for this let the competitors compete.",
        "transliteration": "Khitāmuhu misk, wa fī dhālika falyatanāfasi al-mutanāfisūn",
    },
    {
        "verse_number": "27",
        "arabic_text": "وَ مِزَاجُهُ مِن تَسْنِيمٍ",
        "urdu_text": "اور اس میں تسنیم کی آمیزش هوگی",
        "persian_text": "و آمیخته‌اش از چشمه تسنيم خواهد بود",
        "english_text": "And its mixture is of Tasneem,",
        "transliteration": "Wa mizājuhu min tasnīm",
    },
    {
        "verse_number": "28",
        "arabic_text": "عَيْنًا يَشْرَبُ بِهَا الْمُقَرَّبُونَ",
        "urdu_text": "ایک چشمه، جس سے مقربین پئیں گے",
        "persian_text": "چشمه‌اى كه نزديكان [خدا] از آن مى‌نوشند",
        "english_text": "A spring from which those near [to Allah] drink.",
        "transliteration": "ʿAynan yashrabu bihā al-muqarrabūn",
    },
    {
        "verse_number": "29",
        "arabic_text": "اِنَّ الَّذِينَ اَجْرَمُوا كَانُوا مِنَ الَّذِينَ اٰمَنُواْ يَضْحَكُونَ",
        "urdu_text": "بے شک جو مجرم تھے وه ایمان والوں پر هنسا کرتے تھے",
        "persian_text": "بی‌گمان گناهكاران بر مؤمنان مى‌خنديدند",
        "english_text": "Indeed, those who committed crimes used to laugh at those who believed.",
        "transliteration": "Inna alladhīna ajramū kānū mina alladhīna āmanū yaḍḥakūn",
    },
    {
        "verse_number": "30",
        "arabic_text": "وَ اِذَا مَرُّوا بِهِمْ يَتَغَامَزُوْنَ",
        "urdu_text": "اور جب ان کے پاس سے گزرتے تو آنکھوں سے اشارے کرتے",
        "persian_text": "و چون بر آنان مى‌گذشتند با اشاره و چشمك خنده مى‌كردند",
        "english_text": "And when they passed by them, they would exchange derisive glances.",
        "transliteration": "Wa idhā marrū bihim yataghāmazūn",
    },
    {
        "verse_number": "31",
        "arabic_text": "وَ اِذَا انْقَلَبُوٓا اِلَٰى اَهْلِهِمُ انْقَلَبُوا فَكِهِينَ",
        "urdu_text": "اور جب اپنے لوگوں کے پاس لوٹتے تو خوشی خوشی لوٹتے",
        "persian_text": "و چون به سوى خانواده‌شان باز مى‌گشتند شادمان باز مى‌گشتند",
        "english_text": "And when they returned to their people, they would return jesting.",
        "transliteration": "Wa idhā inqalabū ilā ahlihim inqalabū fakihīn",
    },
    {
        "verse_number": "32",
        "arabic_text": "وَ اِذَا رَاَوْهُمْ قَالُوٓا اِنَّ هٰٓؤُلَآءِ لَضَآلُّونَ",
        "urdu_text": "اور جب انهیں دیکھتے تو کهتے: یه لوگ گمراه هیں",
        "persian_text": "و چون مؤمنان را مى‌ديدند مى‌گفتند: اينان گمراه‌اند",
        "english_text": "And when they saw them, they would say, 'Indeed, those are truly lost.'",
        "transliteration": "Wa idhā ra’awhum qālū inna hā’ulā’i la-ḍāllūn",
    },
    {
        "verse_number": "33",
        "arabic_text": "وَمَآ اُرْسِلُوا عَلَيْهِمْ حٰفِظِينَ",
        "urdu_text": "حالانکه وه ان پر نگران بنا کر نهیں بھیجے گئے تھے",
        "persian_text": "در حالی که نگهبان آنان نبودند",
        "english_text": "But they had not been sent as guardians over them.",
        "transliteration": "Wa mā ursilū ʿalayhim ḥāfiẓīn",
    },
    {
        "verse_number": "34",
        "arabic_text": "فَالْيَوْمَ الَّذِينَ اٰمَنُوا مِنَ الْكُفَّارِ يَضْحَكُونَ",
        "urdu_text": "پھر آج ایمان والے کافروں پر هنس رهے هیں",
        "persian_text": "پس امروز مؤمنان بر كافران مى‌خندند",
        "english_text": "But this Day those who believe are laughing at the disbelievers,",
        "transliteration": "Fa-l-yawma alladhīna āmanū mina al-kuffāri yaḍḥakūn",
    },
    {
        "verse_number": "35",
        "arabic_text": "عَلَى الْاَرَآئِكِ يَنظُرُونَ",
        "urdu_text": "تختوں پر بیٹھے دیکھ رهے هوں گے",
        "persian_text": "بر تخت‌ها نشسته، نظاره می‌کنند",
        "english_text": "On adorned couches, observing.",
        "transliteration": "ʿAlā al-arā’iki yanẓurūn",
    },
    {
        "verse_number": "36",
        "arabic_text": "هَلْ ثُوِّبَ الْكُفَّارُ مَا كَانُوا يَفْعَلُونَ",
        "urdu_text": "کیا کافروں کو ان کے اعمال کی پوری جزا دے دی گئی؟",
        "persian_text": "آيا كافران آنچه مى‌كردند پاداش داده شدند؟",
        "english_text": "Have the disbelievers [not] been repaid for what they used to do?",
        "transliteration": "Hal thūwwiba al-kuffāru mā kānū yafʿalūn",
    },
]
