ayats = [
  {
    "verse_number": 1,
    "english_text": "When the Day of Judgement will be established.",
    "arabic_text": "اِذَا وَقَعَتِ الْوَاقِعَةُ",
    "urdu_text": "جب قیامت واقع ہو جائے گی",
    "persian_text": "هنگامی که واقعه (قیامت) رخ دهد",
    "transliteration": "Iza waqa'atil waqi'ah",
  },
  {
    "verse_number": 2,
    "english_text": "There is no lie in its establishment.",
    "arabic_text": "لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ",
    "urdu_text": "اس کے واقع ہونے میں کوئی جھوٹ نہیں",
    "persian_text": "در وقوع آن هیچ دروغی نیست",
    "transliteration": "Laysa liwaq'atiha kazibah",
  },
  {
    "verse_number": 3,
    "english_text": "It will make everything topsy-turvy.",
    "arabic_text": "خَافِضَةٌ رَّافِعَةٌ",
    "urdu_text": "وہ کسی کو پست کرنے والی اور کسی کو بلند کرنے والی ہے",
    "persian_text": "پست کننده و بلند کننده است",
    "transliteration": "Khafidatur rafi'ah",
  },
  {
    "verse_number": 4,
    "english_text": "When the earth will shake violently.",
    "arabic_text": "اِذَا رُجَّتِ الْاَرْضُ رَجًّا",
    "urdu_text": "جب زمین سخت جھٹکے سے ہلائی جائے گی",
    "persian_text": "هنگامی که زمین به شدت تکان داده شود",
    "transliteration": "Iza rujjatil ardu rajja",
  },
  {
    "verse_number": 5,
    "english_text": "And the mountains will completely crumble.",
    "arabic_text": "وَبُسَّتِ الْجِبَالُ بَسًّا",
    "urdu_text": "اور پہاڑ ریزہ ریزہ کر دیے جائیں گے",
    "persian_text": "و کوه‌ها کاملاً خرد شوند",
    "transliteration": "Wa bussatil jibalu bassa",
  },
  {
    "verse_number": 6,
    "english_text": "Then will scattered into particles.",
    "arabic_text": "فَكَانَتْ هَبَآءٗ مُّنۢبَثّٗا",
    "urdu_text": "پھر وہ بکھرے ہوئے ذرات ہو جائیں گے",
    "persian_text": "پس ذرات پراکنده خواهند شد",
    "transliteration": "Fakanat habaaa'am mumbaththa",
  },
  {
    "verse_number": 7,
    "english_text": "Then you will become three groups.",
    "arabic_text": "وَكُنتُمْ اَزْوَاجٗا ثَلَٰثَةٗ",
    "urdu_text": "اور تم تین گروہ ہو جاؤ گے",
    "persian_text": "و شما سه دسته خواهید شد",
    "transliteration": "Wa kuntum azwaajan thalaatha",
  },
  {
    "verse_number": 8,
    "english_text": "Then people of right hand, and what to say about right-handers.",
    "arabic_text": "فَاَصْحَٰبُ الْمَيْمَنَةِ مَا اَصْحَٰبُ الْمَيْمَنَةِ",
    "urdu_text": "تو دائیں ہاتھ والے، کیا ہی خوش نصیب ہیں دائیں ہاتھ والے",
    "persian_text": "پس یاران دست راست، چه کسانی هستند یاران دست راست",
    "transliteration": "Fa-as'haabul maymanati maa as'haabul maymanah",
  },
  {
    "verse_number": 9,
    "english_text": "And people of the left hand, and what to ask about left-handers.",
    "arabic_text": "وَاَصْحَٰبُ الْمَشْـَٔمَةِ مَا اَصْحَٰبُ الْمَشْـَٔمَةِ",
    "urdu_text": "اور بائیں ہاتھ والے، کیا ہی بدنصیب ہیں بائیں ہاتھ والے",
    "persian_text": "و یاران دست چپ، چه کسانی هستند یاران دست چپ",
    "transliteration": "Wa as'haabul mash'amati maa as'haabul mash'amah",
  },
  {
    "verse_number": 10,
    "english_text": "And the foremost ones (in faith), shall be the foremost ones (in the Hereafter).",
    "arabic_text": "وَالسَّٰبِقُونَ السَّٰبِقُونَ",
    "urdu_text": "اور سبقت لے جانے والے ہی سبقت لے جانے والے ہیں",
    "persian_text": "و پیشگامان همان پیشگامان خواهند بود",
    "transliteration": "Was-saabiqoonas-saabiqoon",
  },
  {
    "verse_number": 11,
    "english_text": "And they will be nearest in the presence of Allah.",
    "arabic_text": "اُوْلَٰٓئِكَ الْمُقَرَّبُونَ",
    "urdu_text": "یہی لوگ (اللہ کے) مقرب ہیں",
    "persian_text": "اینان همان مقربان درگاه خدا هستند",
    "transliteration": "Ulaa'ikal muqarraboon",
  },
  {
    "verse_number": 12,
    "english_text": "(They) shall be in the Paradises of full of Bliss.",
    "arabic_text": "فِى جَنَّٰتِ النَّعِيمِ",
    "urdu_text": "نعمتوں بھری جنتوں میں",
    "persian_text": "در باغ‌های پر نعمت بهشت",
    "transliteration": "Fee jannaatin na'eem",
  },
  {
    "verse_number": 13,
    "english_text": "Many people will be from the earlier ones (who first embraced Islam).",
    "arabic_text": "ثُلَّةٞ مِّنَ الْاَوَّلِينَ",
    "urdu_text": "ان میں سے اکثر پہلے لوگوں میں سے ہوں گے",
    "persian_text": "گروه بزرگی از پیشینیان",
    "transliteration": "Thullatun minal awwaleen",
  },
  {
    "verse_number": 14,
    "english_text": "And some of them will be from the last period.",
    "arabic_text": "وَقَلِيلٞ مِّنَ الْآخِرِينَ",
    "urdu_text": "اور تھوڑے سے بعد والوں میں سے",
    "persian_text": "و اندکی از آخرین",
    "transliteration": "Wa qaleelun minal aakhireen",
  },
  {
    "verse_number": 15,
    "english_text": "On the large thrones (of pearls and rubies).",
    "arabic_text": "عَلَٰى سُرُرٖ مَّوْضُونَةٖ",
    "urdu_text": "جڑاؤ کے تختوں پر",
    "persian_text": "بر تخت‌های زرنگار و نگین‌دار",
    "transliteration": "Alaa sururim mawdoonah",
  },
  {
    "verse_number": 16,
    "english_text": "They will be reclining on them, in front of each other.",
    "arabic_text": "مُّتَّكِـِٔينَ عَلَيْهَا مُتَقَٰبِلِينَ",
    "urdu_text": "وہ ان پر تکیہ لگائے ہوئے آمنے سامنے بیٹھے ہوں گے",
    "persian_text": "بر آنها تکیه زده و روبروی یکدیگر خواهند بود",
    "transliteration": "Muttaki'eena 'alayha mutaqabileen",
  },
  {
    "verse_number": 17,
    "english_text": "Youths, who will always remain young, will go roundabout (to serve) them.",
    "arabic_text": "يَطُوفُ عَلَيْهِمْ وِلْدَٰنٞ مُّخَلَّدُونَ",
    "urdu_text": "ان کے گرد ہمیشہ جوان رہنے والے لڑکے خدمت کے لیے پھریں گے",
    "persian_text": "غلامان جاودانه جوان بر گرد آنان می‌گردند",
    "transliteration": "Yatoofu 'alayhim wildanun mukhalladoon",
  },
  {
    "verse_number": 18,
    "english_text": "Shall be carrying goblets, jugs and cups of pure wine.",
    "arabic_text": "بِاَكْوَابٖ وَاَبَارِيقَ وَكَاْسٖ مِّن مَّعِينٖ",
    "urdu_text": "پیالے اور صراحیاں اور خالص شراب کے جام لیے ہوئے",
    "persian_text": "با جام‌ها و کوزه‌ها و پیاله‌هایی از شراب ناب",
    "transliteration": "Bi-akwabin wa abaareeqa wa ka'sin min ma'een",
  },
  {
    "verse_number": 19,
    "english_text": "From which there will not be any headache nor there will be any loss of consciousness.",
    "arabic_text": "لَا يُصَدَّعُونَ عَنْهَا وَ لَا يُنزِفُونَ",
    "urdu_text": "جس سے نہ سر درد ہوگا اور نہ عقل جاتی رہے گی",
    "persian_text": "که نه سردرد از آن خواهند داشت و نه مست خواهند شد",
    "transliteration": "La yusadda'oona 'anha wa la yunzifoon",
  },
  {
    "verse_number": 20,
    "english_text": "And shall be carrying fruits of their choice.",
    "arabic_text": "وَفَٰكِهَةٖ مِّمَّا يَتَخَيَّرُونَ",
    "urdu_text": "اور ان کی پسند کے میوے لیے ہوئے",
    "persian_text": "و میوه‌هایی از آنچه برمی‌گزینند",
    "transliteration": "Wa fakihatin mimma yatakhayyaroon",
  },
  {
    "verse_number": 21,
    "english_text": "And meat of those birds which they will desire.",
    "arabic_text": "وَلَحْمِ طَيْرٍ مِّمَّا يَشْتَهُونَ",
    "urdu_text": "اور پرندوں کا گوشت جو وہ چاہیں گے",
    "persian_text": "و گوشت پرندگانی که میل دارند",
    "transliteration": "Wa lahmi tayrim mimma yashtahoon",
  },
  {
    "verse_number": 22,
    "english_text": "And there will be wide-eyed Hoories.",
    "arabic_text": "وَحُورٌ عِينٌ",
    "urdu_text": "اور بڑی بڑی آنکھوں والی حوریں ہوں گی",
    "persian_text": "و حوریان درشت چشم",
    "transliteration": "Wa hoorun 'een",
  },
  {
    "verse_number": 23,
    "english_text": "Like well-guarded pearls.",
    "arabic_text": "كَاَمْثَالِ اللُّؤْلُؤِ الْمَكْنُونِ",
    "urdu_text": "چھپے ہوئے موتیوں کی طرح",
    "persian_text": "همچون مرواریدهای نگهداری شده",
    "transliteration": "Ka-amthalil lu'lu'il maknoon",
  },
  {
    "verse_number": 24,
    "english_text": "In fact all this will be as recompense and reward for their deeds.",
    "arabic_text": "جَزَاءً بِمَا كَانُوا يَعْمَلُونَ",
    "urdu_text": "یہ ان کے اعمال کا بدلہ اور انعام ہوگا",
    "persian_text": "پاداشی است برای آنچه انجام می‌دادند",
    "transliteration": "Jaza'am bima kanoo ya'maloon",
  },
  {
    "verse_number": 25,
    "english_text": "There they will not hear any vain talk or sinful-speech.",
    "arabic_text": "لَا يَسْمَعُونَ فِيهَا لَغْوًا وَ لَا تَاْثِيمًا",
    "urdu_text": "وہاں نہ کوئی بیہودہ بات سنیں گے اور نہ کوئی گناہ کی بات",
    "persian_text": "در آنجا نه سخن بیهوده‌ای می‌شنوند و نه سخن گناه‌آلودی",
    "transliteration": "La yasma'oona feeha laghwaw wa la ta'theema",
  },
  {
    "verse_number": 26,
    "english_text": "There only will be peace and greetings everywhere.",
    "arabic_text": "اِلَّا قِيلًا سَلٰمًا سَلٰمًا",
    "urdu_text": "سوائے اس کے کہ سلام ہی سلام ہوگا",
    "persian_text": "جز سخنی که سلام، سلام باشد",
    "transliteration": "Illa qeelan salaman salama",
  },
  {
    "verse_number": 27,
    "english_text": "And what to say about the companions of right hand; those companions of Right-Hand!",
    "arabic_text": "وَاَصْحَابُ الْيَمِينِ مَا اَصْحَابُ الْيَمِينِ",
    "urdu_text": "اور داہنے ہاتھ والے، کیا ہیں داہنے ہاتھ والے",
    "persian_text": "و یاران دست راست، چه کسانی هستند یاران دست راست",
    "transliteration": "Wa as-habu al-yameeni ma as-habu al-yameen",
  },
  {
    "verse_number": 28,
    "english_text": "(There will be) bores without thorns;",
    "arabic_text": "فِى سِدْرٍ مَّخْضُودٍ",
    "urdu_text": "بیریوں میں جن کے کانٹے اتار دیے گئے ہوں",
    "persian_text": "در میان درختان سدر بی‌خار",
    "transliteration": "Fee sidrin makhdhud",
  },
  {
    "verse_number": 29,
    "english_text": "Loaded bananas, one over another.",
    "arabic_text": "وَطَلْحٍ مَّنضُودٍ",
    "urdu_text": "اور کیلوں کے تہہ بہ تہہ خوشوں میں",
    "persian_text": "و درختان موز پر از میوه چیده شده",
    "transliteration": "Wa talhin mandhood",
  },
  {
    "verse_number": 30,
    "english_text": "Spreaded shades.",
    "arabic_text": "وَظِلٍّ مَّمْدُودٍ",
    "urdu_text": "اور پھیلے ہوئے سایوں میں",
    "persian_text": "و سایه‌های گسترده",
    "transliteration": "Wa dhillin mamdood",
  },
  {
    "verse_number": 31,
    "english_text": "Water falling from the Falls.",
    "arabic_text": "وَمَآءٍ مَّسْكُوبٍ",
    "urdu_text": "اور بہتا ہوا پانی",
    "persian_text": "و آب جاری",
    "transliteration": "Wa ma'im maskub",
  },
  {
    "verse_number": 32,
    "english_text": "They will be amidst the plentiful fruits.",
    "arabic_text": "وَفَٰكِهَةٖ كَثِيرَةٖ",
    "urdu_text": "اور بہت سے پھل",
    "persian_text": "و میوه‌های فراوان",
    "transliteration": "Wa fakihatin kathirah",
  },
  {
    "verse_number": 33,
    "english_text": "Whose continuance will never end and there won't be any hindrance.",
    "arabic_text": "لَّا مَقْطُوعَةٖ وَ لَا مَمْنُوعَةٖ",
    "urdu_text": "نہ ختم ہونے والے اور نہ ممنوع",
    "persian_text": "نه قطع شونده و نه ممنوع",
    "transliteration": "La maqtu'atin wa la mamnu'ah",
  },
  {
    "verse_number": 34,
    "english_text": "And there will be high quality mattresses.",
    "arabic_text": "وَفُرُشٖ مَّرْفُوعَةٍ",
    "urdu_text": "اور اونچے بچھونے",
    "persian_text": "و بسترهای بلند",
    "transliteration": "Wa furushin marfu'ah",
  },
  {
    "verse_number": 35,
    "english_text": "Indeed, We have created these Hoories.",
    "arabic_text": "اِنَّآ اَنشَاْنَٰهُنَّ اِنشَآءٗ",
    "urdu_text": "بیشک ہم نے ان حوروں کو خاص طور پر پیدا کیا",
    "persian_text": "به راستی ما آنان را به طور ویژه آفریدیم",
    "transliteration": "Inna ansha'nahunna insha'a",
  },
  {
    "verse_number": 36,
    "english_text": "We have created them all new.",
    "arabic_text": "فَجَعَلْنَٰهُنَّ اَبْكَارًا",
    "urdu_text": "پھر ہم نے انہیں کنواریاں بنا دیا",
    "persian_text": "پس آنان را باکره قرار دادیم",
    "transliteration": "Faja'alnahunna abkara",
  },
  {
    "verse_number": 37,
    "english_text": "These virgins will be companions among themselves.",
    "arabic_text": "عُرُبًا اَتْرَابًا",
    "urdu_text": "شوہروں سے محبت کرنے والیاں ہم عمر",
    "persian_text": "عاشق و هم‌سال",
    "transliteration": "Uruban atraba",
  },
  {
    "verse_number": 38,
    "english_text": "These are all for right handers.",
    "arabic_text": "لِّاَصْحَٰبِ الْيَمِينِ",
    "urdu_text": "یہ سب دائیں ہاتھ والوں کے لیے ہیں",
    "persian_text": "برای یاران راست",
    "transliteration": "Li-as'habil yameen",
  },
  {
    "verse_number": 39,
    "english_text": "Whose one group will be of earlier people.",
    "arabic_text": "ثُلَّةٞ مِّنَ الْاَوَّلِينَ",
    "urdu_text": "ان میں سے ایک گروہ پہلے لوگوں میں سے ہوگا",
    "persian_text": "گروهی از پیشینیان",
    "transliteration": "Thullatun minal awwaleen",
  },
  {
    "verse_number": 40,
    "english_text": "And one group will be of later people.",
    "arabic_text": "وَثُلَّةٞ مِّنَ الْآخِرِينَ",
    "urdu_text": "اور ایک گروہ بعد کے لوگوں میں سے ہوگا",
    "persian_text": "و گروهی از پسینیان",
    "transliteration": "Wa thullatun minal akhireen",
  },
  {
    "verse_number": 41,
    "english_text": "And companions of the left-hand; what to ask about the left-handers.",
    "arabic_text": "وَاَصْحَٰبُ الشِّمَالِ مَآ اَصْحَٰبُ الشِّمَالِ",
    "urdu_text": "اور بائیں ہاتھ والے، کیا ہیں بائیں ہاتھ والے",
    "persian_text": "و یاران دست چپ، چه حال دارند یاران دست چپ",
    "transliteration": "Wa as-habu ash-shimali ma as-habu ash-shimal",
  },
  {
    "verse_number": 42,
    "english_text": "Hot air and boiling water.",
    "arabic_text": "فِى سَمُومٖ وَحَمِيمٖ",
    "urdu_text": "گرم ہوا اور کھولتے ہوئے پانی میں",
    "persian_text": "در باد سوزان و آب جوشان",
    "transliteration": "Fi samoomin wa hameem",
  },
  {
    "verse_number": 43,
    "english_text": "Shade of black smoke.",
    "arabic_text": "وَظِلّٖ مِّن يَحْمُومٖ",
    "urdu_text": "اور کالے دھویں کے سائے میں",
    "persian_text": "و سایه‌ای از دود سیاه",
    "transliteration": "Wa zillin min yahmoom",
  },
  {
    "verse_number": 44,
    "english_text": "Which will not be cool and nor feel good.",
    "arabic_text": "لَّا بَارِدٖ وَ لَا كَرِيمٍ",
    "urdu_text": "نہ ٹھنڈا اور نہ خوشگوار",
    "persian_text": "نه خنک و نه دلپذیر",
    "transliteration": "La baridin wa la kareem",
  },
  {
    "verse_number": 45,
    "english_text": "These are the people who were living a very (lavish) luxurious life.",
    "arabic_text": "اِنَّهُمْ كَانُواْ قَبْلَ ذٰلِكَ مُتْرَفِينَ",
    "urdu_text": "بیشک یہ لوگ اس سے پہلے عیش و عشرت میں رہتے تھے",
    "persian_text": "آنان پیش از این در ناز و نعمت زندگی می‌کردند",
    "transliteration": "Innahum kanu qabla dhalika mutrafeen",
  },
  {
    "verse_number": 46,
    "english_text": "They were persistent on the great sins.",
    "arabic_text": "وَكَانُواْ يُصِرُّونَ عَلَى الْحِنثِ الْعَظِيمِ",
    "urdu_text": "اور وہ بڑے گناہ پر اصرار کرتے رہتے تھے",
    "persian_text": "و آنان بر گناه بزرگ اصرار می‌ورزیدند",
    "transliteration": "Wa kaanoo yusirroona 'alal hinthil 'azeem",
  },
  {
    "verse_number": 47,
    "english_text": "They said: when we die and become dust and bones, shall then we be raised up again.",
    "arabic_text": "وَكَانُواْ يَقُولُونَ اَئِذَا مِتْنَا وَكُنَّا تُرٰبٗا وَعِظَٰمًا ءَاِنَّا لَمَبْعُوثُونَ",
    "urdu_text": "اور وہ کہتے تھے کیا جب ہم مر جائیں گے اور مٹی اور ہڈیاں ہو جائیں گے تو کیا ہم دوبارہ اٹھائے جائیں گے",
    "persian_text": "و می‌گفتند آیا هنگامی که بمیریم و خاک و استخوان شویم، آیا ما دوباره برانگیخته خواهیم شد",
    "transliteration": "Wa kaanoo yaqooloona a-iza mitnaa wa kunnaa turaaban wa 'izaaman a-innaa lamab'oothoon",
  },
  {
    "verse_number": 48,
    "english_text": "Will our fathers be raised again?",
    "arabic_text": "اَوَ ءَابَآؤُنَا الْاَوَّلُونَ",
    "urdu_text": "کیا ہمارے اگلے باپ دادا بھی اٹھائے جائیں گے",
    "persian_text": "آیا پدران پیشین ما نیز برانگیخته خواهند شد",
    "transliteration": "Awa aabaaa'unal awwaloon",
  },
  {
    "verse_number": 49,
    "english_text": "Say: earlier ones and later ones, all.",
    "arabic_text": "قُلْ اِنَّ الْاَوَّلِينَ وَالْءَاخِرِينَ",
    "urdu_text": "کہہ دو کہ بیشک اگلے اور پچھلے سب",
    "persian_text": "بگو که همانا پیشینیان و پسینیان همه",
    "transliteration": "Qul innal awwaleena wal aakhireen",
  },
  {
    "verse_number": 50,
    "english_text": "They will all be collected on an appointed day at a promised place.",
    "arabic_text": "لَمَجْمُوعُونَ اِلـٰى مِيقَٰتِ يَوْمٖ مَّعْلُومٖ",
    "urdu_text": "ضرور ایک مقررہ دن کے وقت پر جمع کیے جائیں گے",
    "persian_text": "قطعاً در وقت معین روزی معلوم گرد آورده خواهند شد",
    "transliteration": "Lamajmoo'oona ilaa meeqaati yawmim ma'loom",
  },
  {
    "verse_number": 51,
    "english_text": "After that, O you who have gone astray and deniers.",
    "arabic_text": "ثُمَّ اِنَّكُمْ اَيُّهَا الضَّآلُّونَ الْمُكَذِّبُونَ",
    "urdu_text": "پھر اے گمراہو اور جھٹلانے والو!",
    "persian_text": "سپس ای گمراهان و تکذیب کنندگان!",
    "transliteration": "Thumma innakum ayyuha ad-daalloona al-mukadhdhiboon",
  },
  {
    "verse_number": 52,
    "english_text": "They shall eat the Thor tree.",
    "arabic_text": "لَآكِلُونَ مِن شَجَرٖ مِّن زَقُّومٖ",
    "urdu_text": "تم ضرور زقوم کے درخت سے کھانے والے ہو",
    "persian_text": "شما از درخت زقوم خواهید خورد",
    "transliteration": "La-akiloona min shajarin min zaqqoom",
  },
  {
    "verse_number": 53,
    "english_text": "Then you shall fill your bellies with it.",
    "arabic_text": "فَمَالِؤُونَ مِنْهَا الْبُطُونَ",
    "urdu_text": "پھر تم اس سے اپنے پیٹ بھرنے والے ہو",
    "persian_text": "پس شکم‌های خود را از آن پر خواهید کرد",
    "transliteration": "Fa-maali'oona minha al-butoon",
  },
  {
    "verse_number": 54,
    "english_text": "Then shall drink boiling water on top of it.",
    "arabic_text": "فَشَٰرِبُونَ عَلَيْهِ مِنَ الْحَمِيمِ",
    "urdu_text": "پھر تم اس کے اوپر کھولتا ہوا پانی پینے والے ہو",
    "persian_text": "سپس بر آن، از آب جوشان خواهید نوشید",
    "transliteration": "Fa-shaariboona 'alayhi mina al-hameem",
  },
  {
    "verse_number": 55,
    "english_text": "Then shall drink like thirsty camels drink.",
    "arabic_text": "فَشَٰرِبُونَ شُرْبَ الْهِيمِ",
    "urdu_text": "پھر تم پیاسے اونٹوں کی طرح پینے والے ہو",
    "persian_text": "پس مانند شتران تشنه خواهید نوشید",
    "transliteration": "Fa-shaariboona shurba al-heem",
  },
  {
    "verse_number": 56,
    "english_text": "This shall be their hospitality on the Day of Judgement.",
    "arabic_text": "هَٰذَا نُزُلُهُمْ يَوْمَ الدِّينِ",
    "urdu_text": "یہ ہے ان کی مہمان نوازی قیامت کے دن",
    "persian_text": "این است پذیرایی آنان در روز جزا",
    "transliteration": "Haazaa nuzuluhum yawmad-deen",
  },
  {
    "verse_number": 57,
    "english_text": "We have created you, then why don't you affirm the re-creation.",
    "arabic_text": "نَحْنُ خَلَقْنَٰكُمْ فَلَوْلَا تُصَدِّقُونَ",
    "urdu_text": "ہم نے تمہیں پیدا کیا ہے تو پھر تم دوبارہ زندہ ہونے کی تصدیق کیوں نہیں کرتے",
    "persian_text": "ما شما را آفریدیم پس چرا باز آفرینش را تصدیق نمی‌کنید",
    "transliteration": "Nahnu khalaqnaakum falaw laa tusaddiqoon",
  },
  {
    "verse_number": 58,
    "english_text": "Have you seen that sperm which you put in the womb.",
    "arabic_text": "اَفَرَءَيْتُم مَّا تُمْنُونَ",
    "urdu_text": "کیا تم نے اس نطفے کو دیکھا جو تم رحم میں ڈالتے ہو",
    "persian_text": "آیا آن نطفه‌ای را که می‌ریزید دیده‌اید",
    "transliteration": "Afara'aytum maa tumnoon",
  },
  {
    "verse_number": 59,
    "english_text": "Do you create that, or We are the Creator?",
    "arabic_text": "ءَاَنتُمْ تَخْلُقُونَهُٓ اَمْ نَحْنُ الْخَٰلِقُونَ",
    "urdu_text": "کیا تم اسے پیدا کرتے ہو یا ہم پیدا کرنے والے ہیں",
    "persian_text": "آیا شما آن را می‌آفرینید یا ما آفریننده‌ایم",
    "transliteration": "A-antum takhluqoonahoo am nahnul-khaaliqoon",
  },
  {
    "verse_number": 60,
    "english_text": "We have ordained death among you, and We are not unable to do this.",
    "arabic_text": "نَحْنُ قَدَّرْنَا بَيْنَكُمُ الْمَوْتَ وَ مَا نَحْنُ بِمَسْبُوقِينَ",
    "urdu_text": "ہم نے تمہارے درمیان موت مقرر کر دی ہے اور ہم اس سے عاجز نہیں ہیں",
    "persian_text": "ما مرگ را در میان شما مقرر کرده‌ایم و ما از این کار ناتوان نیستیم",
    "transliteration": "Nahnu qaddarnaa baynakumul-mawta wa maa nahnu bimasbooqeen",
  },
  {
    "verse_number": 61,
    "english_text": "That We may create other people like you; and transform you in such a form which even you do not know.",
    "arabic_text": "عَلَىٰٓ اَن نُّبَدِّلَ اَمْثَٰلَكُمْ وَنُنشِئَكُمْ فِى مَا لَا تَعْلَمُونَ",
    "urdu_text": "تاکہ ہم تمہاری جگہ تمہارے جیسے اور لوگ پیدا کر دیں اور تمہیں ایسی صورت میں بنا دیں جسے تم جانتے بھی نہیں",
    "persian_text": "تا مانند شما را تبدیل کنیم و شما را در صورتی که نمی‌دانید ایجاد نماییم",
    "transliteration": "'Ala an nubaddila amthalakum wa nunshi'akum fi ma la ta'lamun",
  },
  {
    "verse_number": 62,
    "english_text": "You know the first form of creation, so why don't you ponder over it.",
    "arabic_text": "وَ لَقَدْ عَلِمْتُمُ النَّشْاَةَ الْاُولَىٰ فَلَوْلَا تَذَكَّرُونَ",
    "urdu_text": "اور تم نے پہلی پیدائش کو جان لیا ہے تو کیوں نہیں سوچتے",
    "persian_text": "و شما آفرینش نخستین را دانستید پس چرا متذکر نمی‌شوید",
    "transliteration": "Wa laqad 'alimtumun-nash'atal-ula falaw la tathakkarun",
  },
  {
    "verse_number": 63,
    "english_text": "You have seen that seed also which you sow in the ground.",
    "arabic_text": "اَفَرَءَيْتُم مَّا تَحْرُثُونَ",
    "urdu_text": "کیا تم نے اس بیج کو دیکھا جسے تم زمین میں بوتے ہو",
    "persian_text": "آیا آنچه را که می‌کارید دیده‌اید",
    "transliteration": "Afara'aytum ma tahurthun",
  },
  {
    "verse_number": 64,
    "english_text": "Do you make it grow or We make it grow?",
    "arabic_text": "ءَاَنتُمْ تَزْرَعُونَهُٓ اَمْ نَحْنُ الزَّٰرِعُونَ",
    "urdu_text": "کیا تم اسے اُگاتے ہو یا ہم اُگانے والے ہیں",
    "persian_text": "آیا شما آن را می‌رویانید یا ما رویاننده‌ایم",
    "transliteration": "A'antum tazra'unahu am nahnuz-zari'un",
  },
  {
    "verse_number": 65,
    "english_text": "Had We pleased, We would have turned it into bits and you would have kept thinking.",
    "arabic_text": "لَوْ نَشَآءُ لَجَعَلْنَٰهُ حُطَٰمٗا فَظَلْتُمْ تَفَكَّهُونَ",
    "urdu_text": "اگر ہم چاہتے تو اسے ریزہ ریزہ کر دیتے پھر تم حیران رہ جاتے",
    "persian_text": "اگر بخواهیم آن را خرد و خاشاک می‌گردانیم و شما در حیرت می‌مانید",
    "transliteration": "Law nasha'u laja'alnahu hutaman fazaltum tafakkahun",
  },
  {
    "verse_number": 66,
    "english_text": "That we remain in great loss.",
    "arabic_text": "اِنَّا لَمُغْرَمُونَ",
    "urdu_text": "بیشک ہم تو بڑے نقصان میں پڑ گئے",
    "persian_text": "ما دچار زیان بزرگی شده‌ایم",
    "transliteration": "Inna la-mughramoon",
  },
  {
    "verse_number": 67,
    "english_text": "Rather we remained deprived.",
    "arabic_text": "بَلْ نَحْنُ مَحْرُومُونَ",
    "urdu_text": "بلکہ ہم تو محروم رہ گئے",
    "persian_text": "بلکه ما محروم مانده‌ایم",
    "transliteration": "Bal nahnu mahroomoon",
  },
  {
    "verse_number": 68,
    "english_text": "Did you see the water which you drink?",
    "arabic_text": "اَفَرَءَيْتُمُ الْمَآءَ الَّذِى تَشْرَبُونَ",
    "urdu_text": "کیا تم نے اس پانی کو دیکھا جو تم پیتے ہو؟",
    "persian_text": "آیا آبی را که می‌نوشید دیده‌اید؟",
    "transliteration": "Afa-ra'aytumul-ma'allazi tashraboon",
  },
  {
    "verse_number": 69,
    "english_text": "Did you rain it from the clouds, or is it We who sent down the rain?",
    "arabic_text": "ءَاَنتُمْ اَنزَلْتُمُوهُ مِنَ الْمُزْنِ اَمْ نَحْنُ الْمُنزِلُونَ",
    "urdu_text": "کیا تم نے اسے بادلوں سے برسایا یا ہم برسانے والے ہیں؟",
    "persian_text": "آیا شما آن را از ابرها نازل کردید یا ما نازل‌کننده هستیم؟",
    "transliteration": "A-antum anzaltumohu minal-muzni am nahnul-munziloon",
  },
  {
    "verse_number": 70,
    "english_text": "Had We pleased, We would have made it saline, then why don't you give thanks to Us?",
    "arabic_text": "لَوْ نَشَآءُ جَعَلْنَٰهُ اُجَاجٗا فَلَوْلَا تَشْكُرُونَ",
    "urdu_text": "اگر ہم چاہتے تو اسے کھاری بنا دیتے، پھر تم شکر کیوں نہیں کرتے؟",
    "persian_text": "اگر می‌خواستیم آن را شور می‌کردیم، پس چرا شکر نمی‌کنید؟",
    "transliteration": "Law nasha'u ja'alnahu ujajan fa-lawla tashkuroon",
  },
  {
    "verse_number": 71,
    "english_text": "Did you see the fire which you kindle from wood?",
    "arabic_text": "اَفَرَءَيْتُمُ النَّارَ الَّتِى تُورُونَ",
    "urdu_text": "کیا تم نے اس آگ کو دیکھا جسے تم جلاتے ہو؟",
    "persian_text": "آیا آتشی را که برمی‌افروزید دیده‌اید؟",
    "transliteration": "Afara'aytumun-naaral-latee tooroon",
  },
  {
    "verse_number": 72,
    "english_text": "Did you grow that tree, or We are its Creator.",
    "arabic_text": "ءَاَنتُمْ اَنشَاْتُمْ شَجَرَتَهَآ اَمْ نَحْنُ الْمُنشِـُٔونَ",
    "urdu_text": "کیا تم نے اس کے درخت کو پیدا کیا ہے یا ہم پیدا کرنے والے ہیں؟",
    "persian_text": "آیا شما درخت آن را پدید آوردید یا ما پدیدآورندگان آن هستیم؟",
    "transliteration": "A-antum ansha'tum shajaratahaa am nahnul-munshi'oon",
  },
  {
    "verse_number": 73,
    "english_text": "We made it a source of a reminder; and a profitable object for the travelers.",
    "arabic_text": "نَحْنُ جَعَلْنَٰهَا تَذْكِرَةٗ وَمَتَٰعٗا لِّلْمُقْوِينَ",
    "urdu_text": "ہم نے اسے یاد دہانی اور مسافروں کے لیے فائدہ بنایا ہے",
    "persian_text": "ما آن را یادآوری و متاعی برای مسافران قرار دادیم",
    "transliteration": "Nahnu ja'alnaahaa tadhkiratanw-wa mataa'al-lil-muqween",
  },
  {
    "verse_number": 74,
    "english_text": "Now you glorify the name of your Greatest Lord.",
    "arabic_text": "فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيمِ",
    "urdu_text": "پس اپنے عظیم رب کے نام کی تسبیح کرو",
    "persian_text": "پس نام پروردگار بزرگت را تسبیح گوی",
    "transliteration": "Fasabbih bismi Rabbikal-'Azeem",
  },
  {
    "verse_number": 75,
    "english_text": "And I swear by the phases of the stars.",
    "arabic_text": "فَلَآ اُقْسِمُ بِمَوٰقِعِ النُّجُومِ",
    "urdu_text": "پس میں ستاروں کے مقامات کی قسم کھاتا ہوں",
    "persian_text": "پس سوگند می‌خورم به جایگاه‌های ستارگان",
    "transliteration": "Falaaa uqsimu bimawaqi'in-nujoom",
  },
  {
    "verse_number": 76,
    "english_text": "And it is a great oath; if you know.",
    "arabic_text": "وَاِنَّهُ لَقَسَمٞ لَّوْ تَعْلَمُونَ عَظِيمٌ",
    "urdu_text": "اور بیشک یہ ایک بڑی قسم ہے اگر تم جانتے ہو",
    "persian_text": "و به راستی که این سوگندی بزرگ است اگر بدانید",
    "transliteration": "Wa innahu la-qasamul law ta'lamoona 'azeem",
  },
  {
    "verse_number": 77,
    "english_text": "This is the most honorable Quran.",
    "arabic_text": "اِنَّهُ لَقُرْءَانٞ كَرِيمٞ",
    "urdu_text": "بیشک یہ قرآن بڑی عزت والا ہے",
    "persian_text": "به راستی که این قرآنی گرامی است",
    "transliteration": "Innahu la-Qur'aanun kareem",
  },
  {
    "verse_number": 78,
    "english_text": "This has been kept in the hidden book.",
    "arabic_text": "فِى كِتَٰبٖ مَّكْنُونٖ",
    "urdu_text": "ایک محفوظ کتاب میں",
    "persian_text": "در کتابی نهان و محفوظ",
    "transliteration": "Fee kitaabim maknoon",
  },
  {
    "verse_number": 79,
    "english_text": "No one can touch it except those who are purified.",
    "arabic_text": "لَّا يَمَسُّهُٓ اِلَّا الْمُطَهَّرُونَ",
    "urdu_text": "اسے صرف پاک لوگ ہی چھوتے ہیں",
    "persian_text": "آن را جز پاکان کسی نمی‌تواند لمس کند",
    "transliteration": "Laa yamassuhu illal mutahharoon",
  },
  {
    "verse_number": 80,
    "english_text": "This is revealed by the Lord of the Worlds.",
    "arabic_text": "تَنزِيلٞ مِّن رَّبِّ الْعَٰلَمِينَ",
    "urdu_text": "یہ رب العالمین کی طرف سے نازل کیا گیا ہے",
    "persian_text": "نازل شده از جانب پروردگار جهانیان",
    "transliteration": "Tanzeelum mir Rabbil 'aalameen",
  },
  {
    "verse_number": 81,
    "english_text": "So do you people deny this talk (Quran).",
    "arabic_text": "اَفَبِهَٰذَا الْحَدِيثِ اَنتُم مُّدْهِنُونَ",
    "urdu_text": "تو کیا تم اس بات (قرآن) کو جھٹلاتے ہو",
    "persian_text": "آیا شما این سخن (قرآن) را انکار می‌کنید",
    "transliteration": "Afabihazal hadeethi antum mudhinoon",
  },
  {
    "verse_number": 82,
    "english_text": "And you have made it your profession to deny it.",
    "arabic_text": "وَتَجْعَلُونَ رِزْقَكُمْ اَنَّكُمْ تُكَذِّبُونَ",
    "urdu_text": "اور تم نے اپنا حصہ یہ بنایا ہے کہ تم جھٹلاتے ہو",
    "persian_text": "و روزی خود را در تکذیب آن قرار داده‌اید",
    "transliteration": "Wa taj'aloona rizqakum annakum tukadhzhiboon",
  },
  {
    "verse_number": 83,
    "english_text": "Then why does it not happen, when your soul reaches your throat.",
    "arabic_text": "فَلَوْلَآ اِذَا بَلَغَتِ الْحُلْقُومَ",
    "urdu_text": "پھر کیوں نہیں جب روح حلق تک پہنچ جائے",
    "persian_text": "پس چرا وقتی که جان به گلو می‌رسد",
    "transliteration": "Falawla iza balaghatil hulqoom",
  },
  {
    "verse_number": 84,
    "english_text": "And then you shall just keep looking on.",
    "arabic_text": "وَ اَنتُمْ حِينَئِذٖ تَنظُرُونَ",
    "urdu_text": "اور تم اس وقت دیکھتے رہتے ہو",
    "persian_text": "و شما در آن هنگام تنها نگاه می‌کنید",
    "transliteration": "Wa antum heena'izin tanzuroon",
  },
  {
    "verse_number": 85,
    "english_text": "We are nearer to the dying person than you, but you cannot see.",
    "arabic_text": "وَنَحْنُ اَقْرَبُ اِلَيْهِ مِنكُمْ وَلَٰكِن لَّا تُبْصِرُونَ",
    "urdu_text": "اور ہم تم سے زیادہ اس کے قریب ہیں لیکن تم دیکھ نہیں سکتے",
    "persian_text": "و ما به او نزدیکتر از شما هستیم ولی شما نمی‌بینید",
    "transliteration": "Wa nahnu aqrabu ilayhi minkum wa lakin la tubsiroon",
  },
  {
    "verse_number": 86,
    "english_text": "Then if you are not under pressure from anyone and are totally free.",
    "arabic_text": "فَلَوْلَآ اِن كُنتُمْ غَيْرَ مَدِينِينَ",
    "urdu_text": "تو پھر اگر تم کسی کے محتاج نہیں ہو اور آزاد ہو",
    "persian_text": "پس اگر شما تابع و محکوم کسی نیستید و کاملاً آزاد هستید",
    "transliteration": "Falawla in kuntum ghayra madeeneen",
  },
  {
    "verse_number": 87,
    "english_text": "Then why do you not return that soul, if you are truthful.",
    "arabic_text": "تَرْجِعُونَهَآ اِن كُنتُمْ صَٰدِقِينَ",
    "urdu_text": "تو اس روح کو واپس کیوں نہیں لوٹاتے اگر تم سچے ہو",
    "persian_text": "پس چرا آن را باز نمی‌گردانید اگر راستگو هستید",
    "transliteration": "Tarji'oonaha in kuntum sadiqeen",
  },
  {
    "verse_number": 88,
    "english_text": "Then if the dying person is from the nearest one to Allah.",
    "arabic_text": "فَاَمَّآ اِن كَانَ مِنَ الْمُقَرَّبِينَ",
    "urdu_text": "پھر اگر وہ مرنے والا مقربین میں سے ہو",
    "persian_text": "پس اگر او از مقربان درگاه الهی باشد",
    "transliteration": "Fa-amma in kana minal muqarrabeen",
  },
  {
    "verse_number": 89,
    "english_text": "Then for him is comfort, fragrant flowers, and gardens of bliss.",
    "arabic_text": "فَرَوْحٞ وَرَيْحَانٞ وَجَنَّتُ نَعِيمٍ",
    "urdu_text": "تو اس کے لیے آرام اور خوشبو اور نعمتوں والی جنتیں ہیں",
    "persian_text": "پس برای او آسایش و ریحان و بهشت پر نعمت است",
    "transliteration": "Farawhun wa rayhanun wa jannatu na'eem",
  },
  {
    "verse_number": 90,
    "english_text": "And if those are the right-hand people.",
    "arabic_text": "وَاَمَّآ اِن كَانَ مِنْ اَصْحَٰبِ الْيَمِينِ",
    "urdu_text": "اور اگر وہ اصحاب یمین میں سے ہو",
    "persian_text": "و اگر او از یاران راست باشد",
    "transliteration": "Wa amma in kana min as-habil yameen",
  },
  {
    "verse_number": 91,
    "english_text": "Then salutations are for you, from the companions of right-handers.",
    "arabic_text": "فَسَلَٰمٞ لَّكَ مِنْ اَصْحَٰبِ الْيَمِينِ",
    "urdu_text": "تو تیرے لیے سلامتی ہے اصحاب یمین کی طرف سے",
    "persian_text": "پس برای تو سلام و درود است از جانب یاران دست راست",
    "transliteration": "Fa-salaamul laka min as-haabil yameen",
  },
  {
    "verse_number": 92,
    "english_text": "And if he is of those who deny and have gone astray.",
    "arabic_text": "وَاَمَّآ اِن كَانَ مِنَ الْمُكَذِّبِينَ الضَّآلِّينَ",
    "urdu_text": "اور اگر وہ جھٹلانے والوں اور گمراہوں میں سے ہو",
    "persian_text": "و اما اگر از تکذیب کنندگان گمراه باشد",
    "transliteration": "Wa ammaa in kaana minal mukazzibeenad daalleen",
  },
  {
    "verse_number": 93,
    "english_text": "Then (for him) is hospitality of boiling water.",
    "arabic_text": "فَنُزُلٞ مِّنْ حَمِيمٖ",
    "urdu_text": "تو اس کی مہمان نوازی کھولتے ہوئے پانی سے ہوگی",
    "persian_text": "پس پذیرایی او با آب جوشان است",
    "transliteration": "Fa-nuzulum min hameem",
  },
  {
    "verse_number": 94,
    "english_text": "And the punishment of being thrown into Hell.",
    "arabic_text": "وَتَصْلِيَةُ جَحِيمٍ",
    "urdu_text": "اور دوزخ میں جلایا جانا",
    "persian_text": "و سوختن در آتش دوزخ",
    "transliteration": "Wa tasliyatu jaheem",
  },
  {
    "verse_number": 95,
    "english_text": "This is that talk which is the Truth and certainty.",
    "arabic_text": "اِنَّ هَٰذَا لَهُوَ حَقُّ الْيَقِينِ",
    "urdu_text": "بیشک یہی یقینی سچائی ہے",
    "persian_text": "به راستی این همان حق الیقین است",
    "transliteration": "Inna haazaa la-huwa haqqul yaqeen",
  },
  {
    "verse_number": 96,
    "english_text": "Then continue to glorify the name of your Greatest Lord.",
    "arabic_text": "فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيمِ",
    "urdu_text": "پس اپنے عظیم رب کے نام کی تسبیح کرو",
    "persian_text": "پس نام پروردگار بزرگت را تسبیح گوی",
    "transliteration": "Fasabbih bismi Rabbikal-Azeem",
  },
]
