ayats = [
    {
        "verse_number": 1,
        "arabic_text": "الٓمٓر ۚ تِلْكَ اٰيٰتُ الْكِتٰبِ ۗ وَالَّذِىٓ اُنزِلَ اِلَيْكَ مِن رَّبِّكَ الْحَقُّ وَلَـٰكِنَّ اَكْثَرَ النَّاسِ لَا يُؤْمِنُونَ",
        "english_text": "Alif Laam Meem Ra, these are the perfect verses of the Book which your Lord has revealed to you, but most of the people do not believe.",
        "urdu_text": "الف لام میم را، یه کامل کتاب کی آیات هیں جو تمهارے رب نے تم پر نازل کی هیں، لیکن اکثر لوگ ایمان نهیں لاتے۔",
        "persian_text": "الف لام میم را، این‌ها آیات کامل کتاب است که پروردگارت بر تو نازل کرده، اما بیشتر مردم ایمان نمی‌آورند.",
        "transliteration": "Alif Laam Meem Ra, tilka aayaatul Kitaab, wallazi unzila ilayka mir Rabbikal haqqu wa laakinna aksaran naasi laa yu'minoon",
    },
    {
        "verse_number": 2,
        "arabic_text": "اللّٰهُ الَّذِى رَفَعَ السَّمَـٰوَٰتِ بِغَيْرِ عَمَدٍۢ تَرَوْنَهَا ۖ ثُمَّ اسْتَوَىٰ عَلَى الْعَرْشِ ۖ وَسَخَّرَ الشَّمْسَ وَالْقَمَرَ ۖ كُلٌّۭ يَجْرِى لِاَجَلٍۢ مُّسَمًّۭى ۚ يُدَبِّرُ الْاَمْرَ يُفَصِّلُ الْـَٔايَـٰتِ لَعَلَّكُم بِلِقَآءِ رَبِّكُمْ تُوقِنُونَ",
        "english_text": "That is Allah which have raised the skies without any pillar which you see; He is firmly established on Throne; and He made sun and the moon to obey Him, that they rotate for fixed period, He regulates all affairs of the world and describes His verses with details so that you may believe that (one day) you will be presented before your Lord.",
        "urdu_text": "وه الله هے جس نے آسمانوں کو بغیر ستونوں کے بلند کیا جنهیں تم دیکھتے هو، پھر وه عرش پر مستوی هوا، اور اس نے سورج اور چاند کو مسخر کیا، هر ایک ایک مقرره مدت تک چلتا هے، وه تمام امور کی تدبیر کرتا هے اور آیات کو تفصیل سے بیان کرتا هے تاکه تم اپنے رب کی ملاقات پر یقین کرو۔",
        "persian_text": "او خداوندی است که آسمان‌ها را بدون ستون‌هایی که می‌بینید بلند کرد، سپس بر عرش مستقر شد، و خورشید و ماه را مسخر کرد، هر یک تا زمان معینی در گردش است، او همه کارها را تدبیر می‌کند و آیات را به تفصیل بیان می‌کند تا شما به دیدار پروردگارتان یقین کنید.",
        "transliteration": "Allahul lazi rafa'as samaawaati bi ghayri 'amadin tarawnaha, summas tawaa 'alal 'arsh, wa sakhkharash shamsa wal qamar, kullun yajri li ajalim musamman yudabbirul amra yufassilul aayaati la'allakum bi liqaaa'i Rabbikum tooqinoon",
    },
    {
        "verse_number": 3,
        "arabic_text": "وَهُوَ الَّذِى مَدَّ الْاَرْضَ وَجَعَلَ فِيهَا رَوَٰسِىَ وَاَنْهَـٰرًا ۖ وَمِن كُلِّ الثَّمَرَٰتِ جَعَلَ فِيهَا زَوْجَيْنِ اثْنَيْنِ ۖ يُغْشِى الَّيْلَ النَّهَارَ ۚ اِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍۢ لِّقَوْمٍۢ يَتَفَكَّرُونَ",
        "english_text": "He is Allah who spread the earth and established mountains on it, and made rivers to flow, and made pairs of fruits, and covers the day with the veil of night, and signs are found in it for the people who ponder.",
        "urdu_text": "وهی هے جس نے زمین کو پھیلایا اور اس میں پهاڑ اور دریا بنائے، اور هر پھل کی دو دو قسمیں پیدا کیں، وه رات سے دن کو ڈھانپ دیتا هے، بیشک اس میں غور و فکر کرنے والوں کے لیے نشانیاں هیں۔",
        "persian_text": "او کسی است که زمین را گسترد و در آن کوه‌ها و رودها قرار داد، و از همه میوه‌ها دو جفت در آن قرار داد، شب را بر روز می‌پوشاند، همانا در این نشانه‌هایی است برای مردمی که تفکر می‌کنند.",
        "transliteration": "Wa huwal lazi maddal arda wa ja'ala feeha rawaasiya wa anhara, wa min kullis samaraati ja'ala feeha zawjaynis nayni yughshil laylan nahaar, inna fee zaalika la aayaatil li qawmin yatafakkaroon",
    },
    {
        "verse_number": 4,
        "arabic_text": "وَفِى الْاَرْضِ قِطَعٌۭ مُّتَجَـٰوِرَٰتٌۭ وَجَنَّـٰتٌۭ مِّنْ اَعْنَـٰبٍۢ وَزَرْعٌۭ وَنَخِيلٌۭ صِنْوَانٌ وَغَيْرُ صِنْوَانٍۢ يُسْقَىٰ بِمَآءٍۢ وَٰحِدٍۢ وَنُفَضِّلُ بَعْضَهَا عَلَىٰ بَعْضٍۢ فِى الْاُكُلِ ۚ اِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍۢ لِّقَوْمٍۢ يَعْقِلُونَ",
        "english_text": "And different pieces of land which are adjacent to each other; and gardens of grapes are there and farming and date trees, some of them have two branches and some of them have single branch; and all of them are irrigated with one water; and We give preference to some fruits over some fruits for eating; and in it signs are also found for the wise people.",
        "urdu_text": "اور زمین میں مختلف قطعات هیں جو ایک دوسرے سے ملے هوئے هیں، اور انگور کے باغات هیں اور کھیتی اور کھجور کے درخت هیں، کچھ دو شاخوں والے اور کچھ ایک شاخ والے، سب ایک هی پانی سے سیراب هوتے هیں، اور هم کھانے میں بعض پھلوں کو بعض پر فضیلت دیتے هیں، بیشک اس میں عقل مندوں کے لیے نشانیاں هیں۔",
        "persian_text": "و در زمین قطعات همسایه هم هستند، و باغ‌های انگور و کشتزارها و درختان خرما که بعضی دو شاخه و بعضی تک شاخه هستند، همه با یک آب آبیاری می‌شوند، و برخی از میوه‌ها را در خوردن بر برخی دیگر برتری می‌دهیم، همانا در این نشانه‌هایی است برای مردم خردمند.",
        "transliteration": "Wa fil ardi qita'um mutajaawiratun wa jannaatum min a'naabiw wa zar'un wa nakhilun sinwaanun wa ghayru sinwaanin yusqaa bimaa'in waahid, wa nufaddilu ba'dahaa 'alaa ba'din fil ukul, inna fee zaalika la aayaatil li qawmin ya'qiloon",
    },
    {
        "verse_number": 5,
        "arabic_text": "۞ وَاِن تَعْجَبْ فَعَجَبٌۭ قَوْلُهُمْ اَءِذَا كُنَّا تُرَٰبًا اَءِنَّا لَفِى خَلْقٍۢ جَدِيدٍ ۗ اُو۟لَـٰٓئِكَ الَّذِينَ كَفَرُواْ بِرَبِّهِمْ ۖ وَاُو۟لَـٰٓئِكَ الْاَغْلَـٰلُ فِىٓ اَعْنَاقِهِمْ ۖ وَاُو۟لَـٰٓئِكَ اَصْحَـٰبُ النَّارِ ۖ هُمْ فِيهَا خَـٰلِدُونَ",
        "english_text": "If you wonder (on anything), then you should wonder, on saying of infidels that 'after mingling with dust how we will come to life again', these are the people who disbelieved in Allah, and there will be shackles in their necks (on the Day of Judgement), these are the Hellish people and shall abide in it forever.",
        "urdu_text": "اگر تم تعجب کرتے هو تو تعجب خیز ان کافروں کا یه قول هے که جب هم مٹی هو جائیں گے تو کیا هم نئی زندگی میں آئیں گے، یه وه لوگ هیں جنهوں نے اپنے رب کا انکار کیا، ان کی گردنوں میں طوق هوں گے، یه اهل دوزخ هیں اور وه اس میں همیشه رهنے والے هیں۔",
        "persian_text": "اگر تعجب می‌کنی پس سخن آنان شگفت‌انگیز است که می‌گویند آیا وقتی خاک شدیم دوباره زنده می‌شویم، اینان کسانی هستند که به پروردگارشان کفر ورزیدند، و غل‌ها در گردن‌هایشان خواهد بود، اینان اهل دوزخند و در آن جاودانه خواهند ماند.",
        "transliteration": "Wa in ta'jab fa'ajabun qawluhum a'iza kunna turaaban a'inna lafee khalqin jadeed, ulaa'ikal lazeena kafaroo bi Rabbihim wa ulaa'ikal aghlaalu feee a'naaqihim wa ulaa'ika ashaabun Naari hum feehaa khaalidoon",
    },
    {
        "verse_number": 6,
        "arabic_text": "وَيَسْتَعْجِلُونَكَ بِالسَّيِّئَةِ قَبْلَ الْحَسَنَةِ وَ قَدْ خَلَتْ مِن قَبْلِهِمُ الْمَثُلَـٰتُ ۗ وَاِنَّ رَبَّكَ لَذُو مَغْفِرَةٍۢ لِّلنَّاسِ عَلَىٰ ظُلْمِهِمْ ۖ وَاِنَّ رَبَّكَ لَشَدِيدُ الْعِقَابِ",
        "english_text": "And (O Prophet) they ask you for hastening on the evil before good; however, many punishments had earlier befallen earlier (on many people), and Verily your Lord is very Forgiving, in spite of people's injustice, and undoubtedly your Lord is giver of severe punishment also.",
        "urdu_text": "اے نبی! یه لوگ تم سے نیکی سے پهلے برائی کی جلدی کرتے هیں حالانکه ان سے پهلے بهت سی سزائیں آ چکی هیں، اور بیشک تمهارا رب لوگوں کے ظلم کے باوجود بڑا بخشنے والا هے، اور بیشک تمهارا رب سخت سزا دینے والا بھی هے۔",
        "persian_text": "ای پیامبر! آنان از تو شتاب در عذاب را پیش از رحمت می‌خواهند در حالی که پیش از آنان عبرت‌ها گذشته است، و همانا پروردگار تو با وجود ستم مردم بسیار آمرزنده است، و همانا پروردگار تو سخت کیفر است.",
        "transliteration": "Wa yasta'jiloonaka bis sayyi'ati qablal hasanati wa qad khalat min qablihimul masulaat, wa inna Rabbaka lazoo maghfiratil linnaasi 'alaa zulmihim wa inna Rabbaka la shadeedul 'iqaab",
    },
    {
        "verse_number": 7,
        "arabic_text": "وَيَقُولُ الَّذِينَ كَفَرُواْ لَوْلَآ اُنزِلَ عَلَيْهِ ءَايَةٌۭ مِّن رَّبِّهِٓ ۗ اِنَّمَآ اَنتَ مُنذِرٌۭ ۖ وَلِكُلِّ قَوْمٍ هَادٍ",
        "english_text": "And these infidels say why does not any sign come to them; then say: you are only a warner; and there is a guide for every nation.",
        "urdu_text": "اور یه کافر کهتے هیں که ان پر ان کے رب کی طرف سے کوئی نشانی کیوں نهیں اتری، تو کهه دو که تم صرف ڈرانے والے هو اور هر قوم کے لیے هدایت دینے والا هے۔",
        "persian_text": "و کافران می‌گویند چرا نشانه‌ای از پروردگارش بر او نازل نشده است، بگو تو فقط هشداردهنده‌ای و برای هر قومی راهنمایی است.",
        "transliteration": "Wa yaqoolul lazeena kafaroo law laaa unzila 'alayhi aayatum mir Rabbih, innamaaa anta munzirun wa likulli qawmin haad",
    },
    {
        "verse_number": 8,
        "arabic_text": "اللّٰهُ يَعْلَمُ مَا تَحْمِلُ كُلُّ اُنثَىٰ وَ مَا تَغِيضُ الْاَرْحَامُ وَ مَا تَزْدَادُ ۖ وَكُلُّ شَىْءٍ عِندَهُ بِمِقْدَارٍ",
        "english_text": "And Allah knows what is in the womb of a woman, and what things continue to decrease or continue to increase in her womb, and before Him everything is with a fixed measure.",
        "urdu_text": "اور الله جانتا هے جو هر ماده کے پیٹ میں هے اور جو کچھ رحموں میں کم یا زیاده هوتا هے، اور اس کے نزدیک هر چیز ایک مقرره اندازے کے ساتھ هے۔",
        "persian_text": "و خداوند می‌داند آنچه را که هر ماده‌ای حمل می‌کند و آنچه رحم‌ها کم یا زیاد می‌شود، و نزد او همه چیز با اندازه‌ای معین است.",
        "transliteration": "Allahu ya'lamu maa tahmilu kullu unsaa wa maa tagheedul arhaamu wa maa tazdaad, wa kullu shay'in 'indahoo bmiqdaar",
    },
    {
        "verse_number": 9,
        "arabic_text": "عَـٰلِمُ الْغَيْبِ وَالشَّهَـٰدَةِ الْكَبِيرُ الْمُتَعَالِ",
        "english_text": "He knows the hidden and the obvious, and He is the Great and Most High.",
        "urdu_text": "وه غیب اور ظاهر کا جاننے والا هے، وه بڑا اور بلند و بالا هے۔",
        "persian_text": "او دانای نهان و آشکار است، بزرگ و برتر است.",
        "transliteration": "Aalimul ghaybi wash shahaadatil Kabeerul Muta'aal",
    },
    {
        "verse_number": 10,
        "arabic_text": "سَوَآءٌۭ مِّنكُم مَّنْ اَسَرَّ الْقَوْلَ وَمَن جَهَرَ بِهِ وَ مَنْ هُوَ مُسْتَخْفٍۭ بِالَّيْلِ وَسَارِبٌۢ بِالنَّهَارِ",
        "english_text": "Anyone among you who calls upon Him silently or loudly, and who has hidden himself in the darkness of night, and is walking in daylight, everything is the same for Him. (He hears all and sees all).",
        "urdu_text": "تم میں سے جو بھی خاموشی سے پکارے یا بلند آواز سے، اور جو رات کی تاریکی میں چھپا هو یا دن میں چل رها هو، اس کے لیے سب برابر هے، وه سب کچھ سنتا اور دیکھتا هے۔",
        "persian_text": "از شما کسی که سخن را پنهان می‌کند و کسی که آشکار می‌کند و کسی که در شب پنهان است یا در روز آشکار، برای او یکسان است، او همه چیز را می‌شنود و می‌بیند.",
        "transliteration": "Sawaaa'um minkum man asarral qawla wa man jahara bihee wa man huwa mustakhfim bil layli wa saaribum bin nahaar",
    },
    {
        "verse_number": 11,
        "arabic_text": "لَهُ مُعَقِّبَـٰتٌۭ مِّنۢ بَيْنِ يَدَيْهِ وَمِنْ خَلْفِهِ يَحْفَظُونَهُ مِنْ اَمْرِ اللّٰهِ ۗ اِنَّ اللّٰهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُواْ مَا بِاَنفُسِهِمْ ۗ وَاِذَآ اَرَادَ اللّٰهُ بِقَوْمٍۢ سُوٓءًۭا فَلَا مَرَدَّ لَهُ ۚ وَ مَا لَهُم مِّن دُونِهِ مِن وَالٍ",
        "english_text": "(You may be in any condition), there are forces angels are appointed as guardians to protect him from front and from the back by His command; and He does not change condition of a people unless they themselves change; and when Allah decides to punish somebody then nobody can avert it and neither they do have any guardian except Him.",
        "urdu_text": "تم کسی بھی حالت میں هو، الله کے حکم سے محافظ فرشتے مقرر هیں جو آگے اور پیچھے سے حفاظت کرتے هیں، اور الله کسی قوم کی حالت نهیں بدلتا جب تک وه خود اپنی حالت نه بدلیں، اور جب الله کسی قوم پر عذاب کا اراده کر لے تو کوئی اسے روک نهیں سکتا اور اس کے سوا ان کا کوئی حمایتی نهیں۔",
        "persian_text": "شما در هر حالتی باشید، فرشتگان نگهبان به فرمان او از پیش و پس او محافظت می‌کنند، و خداوند حال قومی را تغییر نمی‌دهد مگر آنکه خودشان تغییر دهند، و هنگامی که خداوند بخواهد بر قومی بدی برساند کسی نمی‌تواند آن را بازگرداند و جز او سرپرستی ندارند.",
        "transliteration": "Lahoo mu'aqqibaatum mim bayni yadayhi wa min khalfihee yahfazoonahoo min amrillaah, innal laaha laa yughayyiru maa biqawmin hattaa yughayyiroo maa bi anfusihim, wa izaaa araadal laahu biqawmin sooo'an falaa maradda lah, wa maa lahum min doonihee min waal",
    },
    {
        "verse_number": 12,
        "arabic_text": "هُوَ الَّذِى يُرِيكُمُ الْبَرْقَ خَوْفًۭا وَطَمَعًۭا وَيُنشِئُ السَّحَابَ الثِّقَالَ",
        "english_text": "It is Allah who shows lightnings and creates water-laden heavy clouds as warning and luring.",
        "urdu_text": "وهی هے جو تمهیں بجلی دکھاتا هے خوف اور امید کے لیے، اور بھاری بادلوں کو پیدا کرتا هے۔",
        "persian_text": "او کسی است که برق را به شما نشان می‌دهد برای ترس و امید، و ابرهای سنگین را پدید می‌آورد.",
        "transliteration": "Huwal lazee yureekumul barqa khawfan wa tama'an wa yunshi'us sahaabas siqaal",
    },
    {
        "verse_number": 13,
        "arabic_text": "وَيُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَـٰٓئِكَةُ مِنْ خِيفَتِهِ وَيُرْسِلُ الصَّوَٰعِقَ فَيُصِيبُ بِهَا مَن يَشَآءُ وَهُمْ يُجَـٰدِلُونَ فِى اللّٰهِ وَهُوَ شَدِيدُ الْمِحَالِ",
        "english_text": "Thundering repeats His praise, and angels continue praising Him with His fear, and when He sends lightning, it strikes to whoever He pleases; and they talk for Allah with crookedness; whereas He has strong power and has mighty strength.",
        "urdu_text": "اور گرج اس کی تسبیح کرتی هے اور فرشتے اس کے خوف سے اس کی حمد کرتے هیں، اور وه بجلیاں بھیجتا هے اور جس پر چاهے گراتا هے، اور وه الله کے بارے میں جھگڑتے هیں حالانکه وه شدید طاقت اور بڑی قوت والا هے۔",
        "persian_text": "و رعد تسبیح او را می‌گوید و فرشتگان از ترس او حمد او می‌کنند، و صاعقه‌ها می‌فرستد و بر هر که بخواهد می‌زند، و آنان درباره خدا مجادله می‌کنند در حالی که او سخت نیرومند است.",
        "transliteration": "Wa yusabbihur ra'du bihamdihee walmalaa'ikatu min kheefatih, wa yurslus sawaa'iqa fa yusebu bihaa man yashaaa'u wa hum yujaadiluna fillaahi wa huwa shadeedul mihaal",
    },
    {
        "verse_number": 14,
        "arabic_text": "لَهُ دَعْوَةُ الْحَقِّ ۖ وَالَّذِينَ يَدْعُونَ مِن دُونِهِ لَا يَسْتَجِيبُونَ لَهُم بِشَىْءٍ اِلَّا كَبَـٰسِطِ كَفَّيْهِ اِلَى الْمَآءِ لِيَبْلُغَ فَاهُ وَ مَا هُوَ بِبَـٰلِغِهِ ۚ وَ مَا دُعَآءُ الْكَـٰفِرِينَ اِلَّا فِى ضَلَـٰلٍۢ",
        "english_text": "Calling is call to Allah only; and those people who call to others except Allah, nothing will be accepted from them; it is like the person who stretches his palm towards water that it may reach his mouth, but it will never reach, and prayers of infidels are always in misguidance.",
        "urdu_text": "دعا صرف الله هی سے کی جاتی هے، اور جو لوگ الله کے سوا دوسروں کو پکارتے هیں وه ان کی کوئی بات نهیں سنتے، یه ایسا هے جیسے کوئی اپنی هتھیلی پانی کی طرف پھیلائے که وه اس کے منه تک پهنچ جائے لیکن وه کبھی نهیں پهنچ سکتا، اور کافروں کی دعا گمراهی میں هے۔",
        "persian_text": "دعا فقط از خداست، و کسانی که غیر از او را می‌خوانند هیچ چیز از آنان پاسخ نمی‌دهند، مثل کسی که دستش را به سوی آب دراز کند تا به دهانش برسد ولی هرگز نمی‌رسد، و دعای کافران در گمراهی است.",
        "transliteration": "Lahoo da'watul haqq, wallazeena yad'oona min doonihee laa yastajeeboona lahum bishay'in illaa kabaasiti kaffayhi ilal maaa'i li yablugha faahu wa maa huwa bi baalighih, wa maa du'aaa'ul kaafireena illaa fee dalaal",
    },
    {
        "verse_number": 15,
        "arabic_text": "وَلِلَّهِ يَسْجُدُ مَن فِى السَّمَـٰوَٰتِ وَالْاَرْضِ طَوْعًۭا وَكَرْهًۭا وَظِلَـٰلُهُم بِالْغُدُوِّ وَالْـَٔاصَالِ ۩",
        "english_text": "All of the beings of skies and the earth are prostrating for Allah either willingly or unwillingly, and morning and evening their shadows are also prostrating.",
        "urdu_text": "اور آسمانوں اور زمین میں جو بھی هیں سب الله کو سجده کرتے هیں، خوشی سے یا ناخوشی سے، اور صبح و شام ان کے سائے بھی سجده کرتے هیں۔",
        "persian_text": "و برای خداوند هر که در آسمان‌ها و زمین است سجده می‌کند، خواه یا ناخواه، و سایه‌هایشان در صبح و شام سجده می‌کنند.",
        "transliteration": "Wa lillaahi yasjudu man fis samaawaati wal ardi taw'an wa karhan wa zilaaluhum bil ghuduwwi wal aasaal",
    },
    {
        "verse_number": 16,
        "arabic_text": "قُلْ مَن رَّبُّ السَّمَـٰوَٰتِ وَالْاَرْضِ قُلِ اللّٰهُ ۚ قُلْ اَفَاتَّخَذْتُم مِّن دُونِهِٓ اَوْلِيَآءَ لَا يَمْلِكُونَ لِاَنفُسِهِمْ نَفْعًۭا وَ لَا ضَرًّۭا ۚ قُلْ هَلْ يَسْتَوِى الْاَعْمَىٰ وَالْبَصِيرُ اَمْ هَلْ تَسْتَوِى الظُّلُمَـٰتُ وَالنُّورُ ۗ اَمْ جَعَلُواْ لِلَّهِ شُرَكَآءَ خَلَقُواْ كَخَلْقِهِ فَتَشَـٰبَهَ الْخَلْقُ عَلَيْهِمْ ۚ قُلِ اللّٰهُ خَـٰلِقُ كُلِّ شَىْءٍۢ وَهُوَ الْوَٰحِدُ الْقَهَّـٰرُ",
        "english_text": "{Prostrate, Non-Obligatory} O Prophet, ask: who is the Lord of skies and the earth? And inform them, that is only Allah, and say: to whom you adopt leaving Allah, they are neither beneficial nor harmful even for themselves, and ask (them): can blind and seeing-one be alike; or can light and darkness be equal; or whom they consider partner of Allah have they created a similar world, and (Our) creation have become doubtful (for them), say: only Allah has created everything; He is the One and Predominant over all.",
        "urdu_text": "اے نبی! پوچھو: آسمانوں اور زمین کا رب کون هے؟ کهه دو که الله، پھر کهو کیا تم نے الله کے سوا کچھ سرپرست بنا لیے هیں جو اپنے لیے بھی نفع یا نقصان کا اختیار نهیں رکھتے؟ پوچھو کیا اندھا اور بینا برابر هو سکتے هیں؟ یا کیا تاریکی اور روشنی برابر هو سکتی هے؟ یا کیا انهوں نے الله کے لیے ایسے شریک بنائے هیں جنهوں نے اس کی طرح پیدا کیا هو اور ان پر تخلیق مشتبه هو گئی؟ کهه دو که الله هی نے هر چیز کو پیدا کیا هے اور وه واحد اور غالب هے۔",
        "persian_text": "ای پیامبر! بگو: پروردگار آسمان‌ها و زمین کیست؟ بگو خداست، سپس بگو آیا جز او اولیایی برگزیده‌اید که برای خودشان نفع و ضرری ندارند؟ بگو آیا کور و بینا برابرند؟ یا تاریکی و نور برابرند؟ یا برای خدا شرکایی قرار داده‌اند که مانند او خلق کرده‌اند و خلقت بر آنان مشتبه شده است؟ بگو خداوند خالق همه چیز است و او یکتا و چیره بر همه است.",
        "transliteration": "Qul mar Rabbus samaawaati wal ard, qulil laah, qul afa ttakhaztum min doonihee awliyaaa'a laa yamlikoona li anfusihim naf'an wa laa darraa, qul hal yastawil a'maa wal baseer, am hal tastawiz zulumaatu wan noor, am ja'aloo lillaahi shurakaaa'a khalaqoo kakhalqihee fa tashaabhal khalqu 'alayhim, qulil laahu khaaliqu kulli shay'iw wa huwal waahidul Qahhaar",
    },
    {
        "verse_number": 17,
        "arabic_text": "اَنزَلَ مِنَ السَّمَآءِ مَآءًۭ فَسَالَتْ اَوْدِيَةٌۢ بِقَدَرِهَا فَاحْتَمَلَ السَّيْلُ زَبَدًۭا رَّابِيًۭا ۚ وَمِمَّا يُوقِدُونَ عَلَيْهِ فِى النَّارِ ابْتِغَآءَ حِلْيَةٍ اَوْ مَتَـٰعٍۢ زَبَدٌۭ مِّثْلُهُ ۚ كَذَٰلِكَ يَضْرِبُ اللّٰهُ الْحَقَّ وَالْبَـٰطِلَ ۚ فَاَمَّا الزَّبَدُ فَيَذْهَبُ جُفَآءًۭ ۖ وَاَمَّا مَا يَنفَعُ النَّاسَ فَيَمْكُثُ فِى الْاَرْضِ ۚ كَذَٰلِكَ يَضْرِبُ اللّٰهُ الْاَمْثَالَ",
        "english_text": "He rains water from the sky, then watercourses flow according to their measure; and it created waves in deluge and foam was formed, and foam formed from the metal which was melted in fire to make ornaments and other things; like this Allah describes the just and the unjust; foam dries and vanish away, and whatever is beneficial for mankind remains on the land; and likewise Allah describes the examples.",
        "urdu_text": "وه آسمان سے پانی برساتا هے تو نالے اپنے اندازے کے مطابق بهتے هیں، اور سیلاب جھاگ اٹھا لاتا هے، اور جو دھات زیورات یا دوسری چیزیں بنانے کے لیے آگ میں پگھلائی جاتی هے اس سے بھی ایسا هی جھاگ بنتا هے، الله اس طرح حق اور باطل کی مثال دیتا هے، جھاگ خشک هو کر اڑ جاتا هے اور جو چیز لوگوں کے لیے مفید هے وه زمین میں ٹھهرتی هے، الله اسی طرح مثالیں بیان کرتا هے۔",
        "persian_text": "او از آسمان آبی نازل می‌کند پس وادی‌ها به اندازه خود جاری می‌شوند، و سیل کف برمی‌دارد، و از آنچه در آتش می‌گدازند برای زینت یا متاعی کفی مانند آن است، اینگونه خداوند حق و باطل را بیان می‌کند، اما کف از میان می‌رود و آنچه مردم را سود می‌رساند در زمین می‌ماند، اینگونه خداوند مثال‌ها را بیان می‌کند.",
        "transliteration": "Anzala minas samaaa'i maaa'an fa saalat awdiyatum biqadarihaa fahtamalas saylu zabadan raabiyaa, wa mimmaa yooqidoona 'alayhi fin naari btighaaaa'a hilyatin aw mataa'in zabadun misluh, kazaalika yadribul laahul haqqa wal baatil, fa ammaz zabadu fa yazhabu jufaaa'an wa ammaa maa yanfa'un naasa fa yamkusu fil ard, kazaalika yadribul laahul amsaal",
    },
    {
        "verse_number": 18,
        "arabic_text": "لِلَّذِينَ اسْتَجَابُواْ لِرَبِّهِمُ الْحُسْنَىٰ ۚ وَالَّذِينَ لَمْ يَسْتَجِيبُواْ لَهُ لَوْ اَنَّ لَهُم مَّا فِى الْاَرْضِ جَمِيعًۭا وَمِثْلَهُ مَعَهُ لَافْتَدَوْاْ بِهِٓ ۚ اُو۟لَـٰٓئِكَ لَهُمْ سُوٓءُ الْحِسَابِ وَمَاْوَىٰهُمْ جَهَنَّمُ ۖ وَبِئْسَ الْمِهَادُ",
        "english_text": "Those who accept the words of Allah, there is good for them, those who do not accept His words, if they get all the treasures of the world, and they get similarly more, and they give everything as ransom; but their reckoning will be the worst, and their place is Hell, and it is a very evil place.",
        "urdu_text": "جنهوں نے اپنے رب کی بات مان لی ان کے لیے بھلائی هے، اور جنهوں نے اس کی بات نهیں مانی اگر ان کے پاس زمین کی تمام چیزیں هوں اور اتنی هی مزید بھی هوں اور وه سب فدیے میں دے دیں، تو ان کا حساب برا هوگا اور ان کا ٹھکانه جهنم هے اور وه بهت برا ٹھکانه هے۔",
        "persian_text": "کسانی که فرمان پروردگار را پذیرفتند نیکی برای آنهاست، و کسانی که نپذیرفتند اگر همه آنچه در زمین است از آن آنان باشد و دو برابرش نیز با آن، قطعاً آن را فدیه می‌دهند، اینان حساب بدی دارند و جایگاهشان جهنم است و بد جایگاهی است.",
        "transliteration": "Lillazeenas tajaaboo li Rabbihimul husnaa, wallazeena lam yastajeeboo lahoo law anna lahum maa fil ardi jamee'an wa mislahoo ma'ahoo laftadaw bih, ulaa'ika lahum sooo'ul hisaabi wa ma'waahum Jahannamu wa bi'sal mihaad",
    },
    {
        "verse_number": 19,
        "arabic_text": "۞ اَفَمَن يَعْلَمُ اَنَّمَآ اُنزِلَ اِلَيْكَ مِن رَّبِّكَ الْحَقُّ كَمَنْ هُوَ اَعْمَىٰٓ ۚ اِنَّمَا يَتَذَكَّرُ اُو۟لُواْ الْاَلْبَـٰبِ",
        "english_text": "Can the person who knows whatever has been revealed to you from the Lord is the truth, be like him who is blind? (Never, but) Only wise-ones would understand.",
        "urdu_text": "کیا وه شخص جو جانتا هے که جو تم پر تمهارے رب کی طرف سے نازل هوا هے وه حق هے، اس شخص کی طرح هو سکتا هے جو اندھا هے؟ کبھی نهیں، صرف عقل مند لوگ هی سمجھتے هیں۔",
        "persian_text": "آیا کسی که می‌داند آنچه از پروردگارت بر تو نازل شده حق است، مانند کسی است که کور است؟ هرگز نه، فقط خردمندان متذکر می‌شوند.",
        "transliteration": "Afa man ya'lamu annamaa unzila ilayka mir Rabbikal haqqu kaman huwa a'maa, innamaa yatazakkaru ulul albaab",
    },
    {
        "verse_number": 20,
        "arabic_text": "الَّذِينَ يُوفُونَ بِعَهْدِ اللّٰهِ وَ لَا يَنقُضُونَ الْمِيثَـٰقَ",
        "english_text": "Those who honor the covenant with Allah, they never break the covenant.",
        "urdu_text": "وه لوگ جو الله کے عهد کو پورا کرتے هیں اور عهد کو کبھی نهیں توڑتے۔",
        "persian_text": "کسانی که به عهد خداوند وفا می‌کنند و پیمان را نمی‌شکنند.",
        "transliteration": "Allazeena yoofoona bi'ahdil laahi wa laa yanqudoonal meesaaq",
    },
    {
        "verse_number": 21,
        "arabic_text": "وَالَّذِينَ يَصِلُونَ مَآ اَمَرَ اللّٰهُ بِهِٓ اَن يُوصَلَ وَيَخْشَوْنَ رَبَّهُمْ وَيَخَافُونَ سُوٓءَ الْحِسَابِ",
        "english_text": "Those who maintain such relations which have been commanded by Allah and are fearful of Him and fear the severe reckoning.",
        "urdu_text": "اور وه لوگ جو ایسے تعلقات کو قائم رکھتے هیں جن کو قائم رکھنے کا الله نے حکم دیا هے، اور اپنے رب سے ڈرتے هیں اور سخت حساب سے ڈرتے هیں۔",
        "persian_text": "و کسانی که آنچه را خداوند به پیوند آن فرمان داده پیوند می‌دهند و از پروردگارشان می‌ترسند و از حساب بد بیم دارند.",
        "transliteration": "Wallazeena yasiloona maaa amaral laahu biheee an yoosala wa yakhshawna Rabbahum wa yakhaafoona sooo'al hisaab",
    },
    {
        "verse_number": 22,
        "arabic_text": "وَالَّذِينَ صَبَرُواْ ابْتِغَآءَ وَجْهِ رَبِّهِمْ وَاَقَامُواْ الصَّلَوٰةَ وَاَنفَقُواْ مِمَّا رَزَقْنَـٰهُمْ سِرًّۭا وَعَلَانِيَةًۭ وَيَدْرَءُونَ بِالْحَسَنَةِ السَّيِّئَةَ اُو۟لَـٰٓئِكَ لَهُمْ عُقْبَى الدَّارِ",
        "english_text": "And those who had patience for the Will of Allah and established prayer; and (in the way of Allah) spends openly and secretly from the sustenance given by Us; and repels evil with good; abode of the Hereafter is for them only.",
        "urdu_text": "اور وه لوگ جنهوں نے الله کی رضا کے لیے صبر کیا اور نماز قائم کی، اور هماری دی هوئی روزی میں سے خفیه اور علانیه خرچ کیا، اور برائی کو بھلائی سے دفع کرتے هیں، آخرت کا گھر انهی کے لیے هے۔",
        "persian_text": "و کسانی که در طلب رضای پروردگارشان صبر کردند و نماز برپا داشتند، و از آنچه روزیشان داده‌ایم پنهان و آشکار انفاق کردند، و بدی را با نیکی دفع می‌کنند، سرای آخرت از آن آنهاست.",
        "transliteration": "Wallazeena sabarub tighaaaa'a wajhi Rabbihim wa aqaamus salaata wa anfaqoo mimmaa razaqnaahum sirran wa 'alaaniyatanw wa yadra'oona bil hasanatis sayyi'ata ulaa'ika lahum 'uqbad Daar",
    },
    {
        "verse_number": 23,
        "arabic_text": "جَنَّـٰتُ عَدْنٍۢ يَدْخُلُونَهَا وَمَن صَلَحَ مِنْ ءَابَآئِهِمْ وَاَزْوَٰجِهِمْ وَذُرِّيَّـٰتِهِمْ ۖ وَالْمَلَـٰٓئِكَةُ يَدْخُلُونَ عَلَيْهِم مِّن كُلِّ بَابٍۢ",
        "english_text": "These are the everlasting gardens, in which they will enter, and along with them from among their forefathers, ancestors, spouses and children the good servants (of Allah) will enter; and angels will be at their service from every door.",
        "urdu_text": "یه همیشه رهنے والی جنتیں هیں جن میں وه داخل هوں گے، اور ان کے ساتھ ان کے باپ دادا، بیوی بچوں میں سے نیک لوگ بھی داخل هوں گے، اور فرشتے هر دروازے سے ان کی خدمت کے لیے آئیں گے۔",
        "persian_text": "باغ‌های جاودان که در آن وارد می‌شوند و کسانی از پدران و همسران و فرزندانشان که صالح بودند، و فرشتگان از هر دری بر آنان وارد می‌شوند.",
        "transliteration": "Jannaatu 'Adnin yadkhuloonahaa wa man salaha min aabaaa'ihim wa azwaajihim wa zurriyyaatihim walmalaa'ikatu yadkhuloona 'alayhim min kulli baab",
    },
    {
        "verse_number": 24,
        "arabic_text": "سَلَـٰمٌ عَلَيْكُم بِمَا صَبَرْتُمْ ۚ فَنِعْمَ عُقْبَى الدَّارِ",
        "english_text": "They will say: salutations to you that you had patience, now abode of the Hereafter is your best destination.",
        "urdu_text": "وه کهیں گے: تم پر سلامتی هو که تم نے صبر کیا، اب آخرت کا گھر تمهارا بهترین ٹھکانه هے۔",
        "persian_text": "سلام بر شما به آنچه صبر کردید، پس چه خوب است سرای آخرت.",
        "transliteration": "Salaamun 'alaykum bimaa sabartum fani'ma 'uqbad Daar",
    },
    {
        "verse_number": 25,
        "arabic_text": "وَالَّذِينَ يَنقُضُونَ عَهْدَ اللّٰهِ مِنۢ بَعْدِ مِيثَـٰقِهِ وَيَقْطَعُونَ مَآ اَمَرَ اللّٰهُ بِهِٓ اَن يُوصَلَ وَيُفْسِدُونَ فِى الْاَرْضِ ۙ اُو۟لَـٰٓئِكَ لَهُمُ اللَّعْنَةُ وَلَهُمْ سُوٓءُ الدَّارِ",
        "english_text": "And those who break covenant, and breaks the relation from those, with whom they were commanded to maintain the relation, and create mischief in the land, for them there is curses and evil abode.",
        "urdu_text": "اور وه لوگ جو الله کے عهد کو توڑتے هیں اس کے پخته هونے کے بعد، اور جن رشتوں کو جوڑنے کا الله نے حکم دیا هے انهیں توڑتے هیں، اور زمین میں فساد مچاتے هیں، ان کے لیے لعنت هے اور برا گھر هے۔",
        "persian_text": "و کسانی که عهد خداوند را پس از محکم شدنش می‌شکنند و آنچه را خداوند به پیوند آن فرمان داده قطع می‌کنند و در زمین فساد می‌کنند، برای آنان لعنت و سرای بد است.",
        "transliteration": "Wallazeena yanqudoona 'ahdal laahi mim ba'di meesaaqihee wa yaqta'oona maaa amaral laahu biheee an yoosala wa yufsidoona fil ard, ulaa'ika lahumul la'natu wa lahum sooo'ud Daar",
    },
    {
        "verse_number": 26,
        "arabic_text": "اللّٰهُ يَبْسُطُ الرِّزْقَ لِمَن يَشَآءُ وَيَقْدِرُ ۚ وَفَرِحُواْ بِالْحَيَوٰةِ الدُّنْيَا وَ مَا الْحَيَوٰةُ الدُّنْيَا فِى الْـَٔاخِرَةِ اِلَّا مَتَـٰعٌۭ",
        "english_text": "Allah amplifies or straitens the sustenance for whom as He pleases; these people are happy on the life of this world; whereas in comparison to the Hereafter life of this world is a temporary enjoyment, and that's it.",
        "urdu_text": "الله جس کے لیے چاهتا هے روزی کو وسیع کرتا هے اور جس کے لیے چاهتا هے تنگ کرتا هے، اور یه لوگ دنیا کی زندگی پر خوش هیں، حالانکه آخرت کے مقابلے میں دنیا کی زندگی صرف ایک عارضی فائده هے۔",
        "persian_text": "خداوند روزی را برای هر که بخواهد گسترش می‌دهد و تنگ می‌کند، و آنان به زندگی دنیا شادمانند در حالی که زندگی دنیا در برابر آخرت جز متاعی موقت نیست.",
        "transliteration": "Allaahu yabsutur rizqa liman yashaaa'u wa yaqdir, wa farihoo bil hayaatid dunyaa wa mal hayaatud dunyaa fil aakhirati illaa mataa'",
    },
    {
        "verse_number": 27,
        "arabic_text": "وَيَقُولُ الَّذِينَ كَفَرُواْ لَوْلَآ اُنزِلَ عَلَيْهِ ءَايَةٌۭ مِّن رَّبِّهِ ۗ قُلْ اِنَّ اللّٰهَ يُضِلُّ مَن يَشَآءُ وَيَهْدِىٓ اِلَيْهِ مَنْ اَنَابَ",
        "english_text": "And infidels say why do not signs of their choice come to them, O Prophet say: to whoever Allah wills leave him in misguidance; and He guides those who turn to Him.",
        "urdu_text": "اور کافر کهتے هیں که ان پر ان کے رب کی طرف سے کوئی نشانی کیوں نهیں اتری، اے نبی! کهه دو که الله جسے چاهتا هے گمراهی میں چھوڑ دیتا هے اور جو اس کی طرف رجوع کرتا هے اسے هدایت دیتا هے۔",
        "persian_text": "و کافران می‌گویند چرا نشانه‌ای از پروردگارش بر او نازل نشده است، ای پیامبر بگو خداوند هر که را بخواهد گمراه می‌کند و کسی را که به سوی او بازگردد هدایت می‌کند.",
        "transliteration": "Wa yaqoolul lazeena kafaroo law laaa unzila 'alayhi aayatum mir Rabbih, qul innal laaha yudillu man yashaaa'u wa yahdeeee ilayhi man anaab",
    },
    {
        "verse_number": 28,
        "arabic_text": "الَّذِينَ ءَامَنُواْ وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللّٰهِ ۗ اَلَا بِذِكْرِ اللّٰهِ تَطْمَئِنُّ الْقُلُوبُ",
        "english_text": "These are the people who believed, and their hearts get satisfied with the remembrance of Allah, and be aware that satisfaction is with remembrance of Allah only.",
        "urdu_text": "یه وه لوگ هیں جو ایمان لائے اور ان کے دل الله کے ذکر سے مطمئن هوتے هیں، اور خبردار رهو که اطمینان صرف الله کے ذکر سے هی هے۔",
        "persian_text": "کسانی که ایمان آورده‌اند و دل‌هایشان با یاد خدا آرام می‌گیرد، آگاه باشید که فقط با یاد خداوند دل‌ها آرامش می‌یابد.",
        "transliteration": "Allazeena aamanoo wa tatma'innu quloobuhum bizikril laah, alaa bizikril laahi tatma'innul quloob",
    },
    {
        "verse_number": 29,
        "arabic_text": "الَّذِينَ ءَامَنُواْ وَعَمِلُواْ الصَّـٰلِحَـٰتِ طُوبَىٰ لَهُمْ وَحُسْنُ مَـَٔابٍۢ",
        "english_text": "Those who believed and did good works, for them is the best place (Paradise) and best return.",
        "urdu_text": "جو لوگ ایمان لائے اور نیک عمل کیے، ان کے لیے بهترین جگه (جنت) اور بهترین انجام هے۔",
        "persian_text": "کسانی که ایمان آوردند و کارهای شایسته کردند، برای آنان خوشبختی و بهترین بازگشت است.",
        "transliteration": "Allazeena aamanoo wa 'amilus saalihaati toobaa lahum wa husnu ma'aab",
    },
    {
        "verse_number": 30,
        "arabic_text": "كَذَٰلِكَ اَرْسَلْنَـٰكَ فِىٓ اُمَّةٍۢ قَدْ خَلَتْ مِن قَبْلِهَآ اُمَمٌۭ لِّتَتْلُوَاْ عَلَيْهِمُ الَّذِىٓ اَوْحَيْنَآ اِلَيْكَ وَهُمْ يَكْفُرُونَ بِالرَّحْمَـٰنِ ۚ قُلْ هُوَ رَبِّى لَآ اِلَـٰهَ اِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَ اِلَيْهِ مَتَابِ",
        "english_text": "Likewise, We sent you among a people where many a people have passed, so that you recite the things which We sent you through revelation, however, they will deny the Merciful, you say: He is my Lord and there is no god except Him, I rely on him and to Him is our return.",
        "urdu_text": "اسی طرح هم نے تمهیں ایک ایسی قوم میں بھیجا هے جس سے پهلے بهت سی قومیں گزر چکی هیں تاکه تم ان کو وه چیزیں پڑھ کر سناؤ جو هم نے تم پر وحی کی هیں، حالانکه وه رحمان کا انکار کرتے هیں، تم کهه دو: وهی میرا رب هے اور اس کے سوا کوئی معبود نهیں، میں اسی پر بھروسه کرتا هوں اور اسی کی طرف میری واپسی هے۔",
        "persian_text": "اینگونه تو را در میان امتی فرستادیم که پیش از آن امت‌هایی گذشته‌اند تا آنچه را به تو وحی کرده‌ایم بر آنان بخوانی، در حالی که به رحمان کفر می‌ورزند، بگو او پروردگار من است و جز او خدایی نیست، بر او توکل کرده‌ام و بازگشت من به سوی اوست.",
        "transliteration": "Kazaalika arsalnaaka feee ummatin qad khalat min qablihaaaa umamul litatluwa 'alayhimul lazeee awhaynaaa ilayka wa hum yakfuroona bir Rahmaan, qul huwa Rabbee laaa ilaaha illaa huwa 'alayhi tawakkaltu wa ilayhi mataab",
    },
    {
        "verse_number": 31,
        "arabic_text": "وَ لَوْ اَنَّ قُرْءَانًۭا سُيِّرَتْ بِهِ الْجِبَالُ اَوْ قُطِّعَتْ بِهِ الْاَرْضُ اَوْ كُلِّمَ بِهِ الْمَوْتَىٰ ۗ بَل لِّلَّهِ الْاَمْرُ جَمِيعًا ۗ اَفَلَمْ يَاْيْـَٔسِ الَّذِينَ ءَامَنُوٓاْ اَن لَّوْ يَشَآءُ اللّٰهُ لَهَدَى النَّاسَ جَمِيعًۭا ۗ وَ لَا يَزَالُ الَّذِينَ كَفَرُواْ تُصِيبُهُم بِمَا صَنَعُواْ قَارِعَةٌ اَوْ تَحُلُّ قَرِيبًا مِّن دَارِهِمْ حَتَّىٰ يَاْتِىَ وَعْدُ اللّٰهِ ۚ اِنَّ اللّٰهَ لَا يُخْلِفُ الْمِيعَادَ",
        "english_text": "If there is such Quran which can move mountains from their place, or can be travelled on the land, or dead can be talked with. (this is that Quran), however, all the affairs are for Allah, does it not became clear to the believers; that if Allah pleased He would have guided all the people; and on these infidels troubles of some kind or other will continue to befall them because of their deeds; or troubles shall befell on their region; until the time of promise of Allah comes, because Allah never does against His promise.",
        "urdu_text": "اگر کوئی ایسا قرآن هو جس سے پهاڑ اپنی جگه سے چل پڑیں، یا زمین کٹ جائے، یا مردوں سے بات کی جائے تو یه وهی قرآن هے، لیکن تمام امور الله کے لیے هیں، کیا مومنوں پر یه واضح نهیں هوا که اگر الله چاهتا تو تمام لوگوں کو هدایت دے دیتا، اور ان کافروں پر ان کے اعمال کی وجه سے مصیبتیں آتی رهیں گی، یا ان کے علاقے کے قریب مصیبت اتری گی، یهاں تک که الله کا وعده آ جائے، کیونکه الله اپنے وعدے کے خلاف نهیں کرتا۔",
        "persian_text": "اگر قرآنی باشد که با آن کوه‌ها جابجا شوند یا زمین پاره پاره گردد یا مردگان با آن سخن گویند این همان قرآن است، اما همه امور از آن خداست، آیا مؤمنان نفهمیده‌اند که اگر خدا می‌خواست همه مردم را هدایت می‌کرد؟ و بر کافران به خاطر اعمالشان بلایی می‌رسد یا نزدیک خانه‌شان فرود می‌آید تا وعده خدا بیاید، همانا خداوند وعده را خلف نمی‌کند.",
        "transliteration": "Wa law anna Qur'aanan suyyirat bihil jibaalu aw quttia't bihil ardu aw kullima bihil mawtaa, bal lillaahil amru jamee'aa, afalam yay'asil lazeena aamanooo an law yashaaa'ul laahu la hadaan naasa jamee'aa, wa laa yazaalul lazeena kafaroo tuseebuhum bimaa sana'oo qaari'atun aw tahullu qareeban min daarihim hattaa ya'tiya wa'dul laah, innal laaha laa yukhliful mee'aad",
    },
    {
        "verse_number": 32,
        "arabic_text": "وَلَقَدِ اسْتُهْزِئَ بِرُسُلٍۢ مِّن قَبْلِكَ فَاَمْلَيْتُ لِلَّذِينَ كَفَرُواْ ثُمَّ اَخَذْتُهُمْ ۖ فَكَيْفَ كَانَ عِقَابِ",
        "english_text": "O Prophet! Before you, many prophets were mocked at, We gave small respite to the infidels, and thereafter took them in Our grip, so what a severe punishment it was.",
        "urdu_text": "اے نبی! تم سے پهلے بهت سے پیغمبروں کا مذاق اڑایا گیا، هم نے کافروں کو تھوڑی مهلت دی، پھر انهیں اپنی گرفت میں لے لیا، تو کیسا سخت عذاب تھا۔",
        "persian_text": "ای پیامبر! پیش از تو پیامبران به استهزا گرفته شدند، پس به کافران مهلت دادیم سپس آنان را گرفتیم، پس چگونه بود عذاب من.",
        "transliteration": "Wa laqadis tuhzi'a bi Rusulim min qablika fa amlaytu lillazeena kafaroo summa akhaztuhum fakayfa kaana 'iqaab",
    },
    {
        "verse_number": 33,
        "arabic_text": "اَفَمَنْ هُوَ قَآئِمٌ عَلَىٰ كُلِّ نَفْسٍۭ بِمَا كَسَبَتْ ۗ وَجَعَلُواْ لِلَّهِ شُرَكَآءَ قُلْ سَمُّوهُمْ ۚ اَمْ تُنَبِّـُٔونَهُ بِمَا لَا يَعْلَمُ فِى الْاَرْضِ اَم بِظَـٰهِرٍۢ مِّنَ الْقَوْلِ ۗ بَلْ زُيِّنَ لِلَّذِينَ كَفَرُواْ مَكْرُهُمْ وَصُدُّواْ عَنِ السَّبِيلِ ۗ وَمَن يُضْلِلِ اللّٰهُ فَمَا لَهُ مِنْ هَادٍۢ",
        "english_text": "That is He Who watches the deeds of every soul; and they have forged partners for Him, then say: tell the names of His partners, you are informing Him about His partners, about whom He does not have any news in the whole land, these are only the words. (whereas) fact is that their planning has been decorated for them, and they have been barred from guidance, and to whom Allah does not guide, nobody can guide him.",
        "urdu_text": "کیا وه جو هر نفس کے اعمال پر نگران هے، اور انهوں نے الله کے لیے شریک بنائے هیں، تو کهو ان کے نام بتاؤ، کیا تم اسے ایسی چیز کی خبر دے رهے هو جو زمین میں اسے معلوم نهیں یا یه صرف زبان کی بات هے؟ بلکه ان کافروں کے لیے ان کی چال آراسته کر دی گئی هے اور انهیں راستے سے روک دیا گیا هے، اور جسے الله گمراه کر دے اسے کوئی هدایت نهیں دے سکتا۔",
        "persian_text": "آیا کسی که بر هر نفسی به آنچه کسب کرده نظارت دارد، و برای خدا شریکانی قرار داده‌اند، بگو نامشان را ببرید، یا او را از چیزی که در زمین نمی‌داند خبر می‌دهید یا فقط سخنی ظاهری است؟ بلکه برای کافران مکرشان زینت داده شده و از راه باز داشته شده‌اند، و هر کس را خدا گمراه کند هیچ راهنمایی ندارد.",
        "transliteration": "Afaman huwa qaaa'imun 'alaa kulli nafsim bimaa kasabat wa ja'aloo lillaahi shurakaaa'a qul sammoohum, am tunabi'oonahoo bimaa laa ya'lamu fil ardi am bizaahirim minal qawl, bal zuyyina lillazeena kafaroo makruhum wa suddoo 'anis sabeel, wa man yudlilil laahu famaa lahoo min haad",
    },
    {
        "verse_number": 34,
        "arabic_text": "لَّهُمْ عَذَابٌۭ فِى الْحَيَوٰةِ الدُّنْيَا ۖ وَلَعَذَابُ الْـَٔاخِرَةِ اَشَقُّ ۖ وَ مَا لَهُم مِّنَ اللّٰهِ مِن وَاقٍۢ",
        "english_text": "There is punishment for them in the life of this world also, and punishment of the Hereafter is even more severe, and then there is no one to save (them) from Allah.",
        "urdu_text": "ان کے لیے دنیا کی زندگی میں بھی عذاب هے اور آخرت کا عذاب اور بھی سخت تر هے، اور پھر ان کو الله سے بچانے والا کوئی نهیں۔",
        "persian_text": "برای آنان در زندگی دنیا عذابی است و عذاب آخرت سخت‌تر است، و برای آنان از خدا نگهبانی نیست.",
        "transliteration": "Lahum 'azaabun fil hayaatid dunyaa wa la'azaabul aakhirati ashaqq, wa maa lahum minal laahi min waaq",
    },
    {
        "verse_number": 35,
        "arabic_text": "۞ مَّثَلُ الْجَنَّةِ الَّتِى وُعِدَ الْمُتَّقُونَ ۖ تَجْرِى مِن تَحْتِهَا الْاَنْهَـٰرُ ۖ اُكُلُهَا دَآئِمٌۭ وَظِلُّهَا ۚ تِلْكَ عُقْبَى الَّذِينَ اتَّقَواْ ۖ وَّعُقْبَى الْكَـٰفِرِينَ النَّارُ",
        "english_text": "The Paradise, which the pious people have been promised, will be like this, that beneath which rivers will be flowing, and its fruits will be permanent; and shadow will be everlasting; such is the end of the pious ones, and the end of the infidels is Hell.",
        "urdu_text": "جنت جس کا پرهیزگاروں سے وعده کیا گیا هے ایسی هوگی که اس کے نیچے نهریں بهتی هوں گی، اور اس کے پھل همیشه رهنے والے هیں اور اس کا سایه دائمی هے، یه پرهیزگاروں کا انجام هے اور کافروں کا انجام آگ هے۔",
        "persian_text": "مثل بهشتی که به پرهیزگاران وعده داده شده، از زیر آن نهرها جاری است، میوه‌هایش پایدار است و سایه‌اش، این سرانجام پرهیزگاران است و سرانجام کافران آتش است.",
        "transliteration": "Masalul Jannatil latee wu'idal muttaqoon, tajree min tahtihal anhaar, ukuluhaa daaa'imunw wa zilluhaa, tilka 'uqbal lazeenattaqaw wa 'uqbal kaafireenun Naar",
    },
    {
        "verse_number": 36,
        "arabic_text": "وَالَّذِينَ ءَاتَيْنَـٰهُمُ الْكِتٰبَ يَفْرَحُونَ بِمَآ اُنزِلَ اِلَيْكَ ۖ وَمِنَ الْاَحْزَابِ مَن يُنكِرُ بَعْضَهُ ۚ قُلْ اِنَّمَآ اُمِرْتُ اَنْ اَعْبُدَ اللّٰهَ وَلَآ اُشْرِكَ بِهِٓ ۚ اِلَيْهِ اَدْعُواْ وَ اِلَيْهِ مَـَٔابِ",
        "english_text": "And to whom We gave the book they are happy with its revelation, and there are some groups which deny some part of it, so say: I have been ordained to worship Allah, and not to make anybody His partner, and to Him I invite (you), and to Him is the return of everybody.",
        "urdu_text": "اور جن لوگوں کو هم نے کتاب دی هے وه اس کے نازل هونے پر خوش هیں، اور کچھ گروه اس کے کچھ حصے کا انکار کرتے هیں، تو کهه دو که مجھے یه حکم دیا گیا هے که صرف الله کی عبادت کروں اور کسی کو اس کا شریک نه بناؤں، میں اسی کی طرف بلاتا هوں اور اسی کی طرف سب کی واپسی هے۔",
        "persian_text": "و کسانی که به آنان کتاب دادیم به آنچه بر تو نازل شده شادمانند، و از گروه‌ها کسانی هستند که بعضی از آن را انکار می‌کنند، بگو من فقط مامور شده‌ام که خدا را عبادت کنم و شریکی برای او قرار ندهم، به سوی او دعوت می‌کنم و بازگشت من به سوی اوست.",
        "transliteration": "Wallazeena aataynaahu mul Kitaaba yafrahoona bimaaa unzila ilayk, wa minal Ahzaabi man yunkiru ba'dah, qul innamaaa umirtu an a'budal laaha wa laaa ushrika bih, ilayhi ad'oo wa ilayhi ma'aab",
    },
    {
        "verse_number": 37,
        "arabic_text": "وَكَذَٰلِكَ اَنزَلْنَـٰهُ حُكْمًا عَرَبِيًّۭا ۚ وَلَئِنِ اتَّبَعْتَ اَهْوَآءَهُم بَعْدَ مَا جَآءَكَ مِنَ الْعِلْمِ مَا لَكَ مِنَ اللّٰهِ مِن وَلِىٍّۢ وَ لَا وَاقٍۢ",
        "english_text": "And thus We revealed the Quran as command in Arabic language, and after receiving knowledge if you will follow their desires; so there will not be any guardian and defender against Allah.",
        "urdu_text": "اور اسی طرح هم نے اسے عربی زبان میں حکم کے طور پر نازل کیا، اور اگر علم ملنے کے بعد تم ان کی خواهشات کی پیروی کرو گے تو الله کے مقابلے میں تمهارا کوئی حمایتی اور بچانے والا نهیں هوگا۔",
        "persian_text": "و اینگونه آن را حکمی عربی نازل کردیم، و اگر پس از آنکه دانش به تو رسید از هوای آنان پیروی کنی، از خدا برایت سرپرست و نگهبانی نخواهد بود.",
        "transliteration": "Wa kazaalika anzalnaahu hukman 'arabiyyaa, wa la'init taba'ta ahwaaa'ahum ba'da maa jaaa'aka minal 'ilmi maa laka minal laahi minw waliyinw wa laa waaq",
    },
    {
        "verse_number": 38,
        "arabic_text": "وَ لَقَدْ اَرْسَلْنَا رُسُلًا مِّن قَبْلِكَ وَجَعَلْنَا لَهُمْ اَزْوَٰجًۭا وَذُرِّيَّةًۭ ۚ وَ مَا كَانَ لِرَسُولٍ اَن يَاْتِىَ بِـَٔايَةٍ اِلَّا بِاِذْنِ اللّٰهِ ۗ لِكُلِّ اَجَلٍۢ كِتَابٌۭ",
        "english_text": "Before you, We have sent many messengers and given wives and children to them, and it is not possible for any messenger that without command of Allah he can bring any sign, and for every period and term there is decree (from Allah).",
        "urdu_text": "تم سے پهلے هم نے بهت سے رسول بھیجے اور ان کو بیویاں اور اولاد دی، اور کسی رسول کے لیے یه ممکن نهیں که وه الله کے حکم کے بغیر کوئی نشانی لائے، اور هر مدت اور مقرره وقت کے لیے ایک فیصله هے۔",
        "persian_text": "و پیش از تو پیامبرانی فرستادیم و برای آنان همسران و فرزندان قرار دادیم، و برای هیچ پیامبری نیست که بدون اذن خدا نشانه‌ای بیاورد، و برای هر مدتی حکمی است.",
        "transliteration": "Wa laqad arsalnaa Rusulan min qablika wa ja'alnaa lahum azwaajan wa zurriyyah, wa maa kaana li Rasoolim any ya'tiya bi aayatin illaa bi iznil laah, likulli ajalin kitaab",
    },
    {
        "verse_number": 39,
        "arabic_text": "يَمْحُواْ اللّٰهُ مَا يَشَآءُ وَيُثْبِتُ ۖ وَعِندَهُٓ اُمُّ الْكِتٰبِ",
        "english_text": "And whatever Allah pleases He erases or maintains, that the real Book is with Him only.",
        "urdu_text": "اور الله جو چاهتا هے مٹا دیتا هے یا برقرار رکھتا هے، اور اصل کتاب اسی کے پاس هے۔",
        "persian_text": "خداوند آنچه را بخواهد محو یا ثابت می‌کند، و نزد او ام الکتاب است.",
        "transliteration": "Yamhul laahu maa yashaaa'u wa yusbitu wa 'indahooo Ummul Kitaab",
    },
    {
        "verse_number": 40,
        "arabic_text": "وَاِن مَّا نُرِيَنَّكَ بَعْضَ الَّذِى نَعِدُهُمْ اَوْ نَتَوَفَّيَنَّكَ فَاِنَّمَا عَلَيْكَ الْبَلَـٰغُ وَعَلَيْنَا الْحِسَابُ",
        "english_text": "And O Prophet, whether We show you Our promise of punishment of infidels, or may cause death to you; your mission is only to deliver the command (of Allah), and their accounting is Our responsibility.",
        "urdu_text": "اور اے نبی! هم تمهیں ان سے جو وعده کیا هے اس میں سے کچھ دکھا دیں یا تمهیں وفات دے دیں، تمهارا کام صرف پیغام پهنچانا هے اور ان کا حساب همارے ذمے هے۔",
        "persian_text": "و ای پیامبر! خواه بعضی از آنچه به آنان وعده داده‌ایم به تو نشان دهیم یا تو را بمیرانیم، بر تو فقط ابلاغ است و بر ما حساب است.",
        "transliteration": "Wa im maa nuriyannaka ba'dal lazee na'iduhum aw natawaffayannaka fa innamaa 'alaykal balaaghu wa'alayn al hisaab",
    },
    {
        "verse_number": 41,
        "arabic_text": "اَوَلَمْ يَرَوْاْ اَنَّا نَاْتِى الْاَرْضَ نَنقُصُهَا مِنْ اَطْرَافِهَا ۚ وَاللّٰهُ يَحْكُمُ لَا مُعَقِّبَ لِحُكْمِهِ ۚ وَهُوَ سَرِيعُ الْحِسَابِ",
        "english_text": "Didn't they see how We reduce the land from all directions (with victory of Islam), and only Allah gives the command, no one can avert His command, and He is swift in taking account.",
        "urdu_text": "کیا انهوں نے نهیں دیکھا که هم زمین کو چاروں طرف سے کم کرتے جا رهے هیں (اسلام کی فتح کے ساتھ)، اور صرف الله فیصله کرتا هے، کوئی اس کے فیصلے کو ٹال نهیں سکتا، اور وه حساب لینے میں تیز هے۔",
        "persian_text": "آیا ندیدند که ما به زمین می‌آییم و آن را از اطراف کم می‌کنیم (با پیروزی اسلام)، و خداوند حکم می‌کند و کسی حکم او را باز نمی‌گرداند، و او سریع الحساب است.",
        "transliteration": "Awa lam yaraw annaa na'til arda nanqusuha min atraafihaa wallaahu yahkumu laa mu'aqqiba lihukmi wa huwa saree'ul hisaab",
    },
    {
        "verse_number": 42,
        "arabic_text": "وَقَدْ مَكَرَ الَّذِينَ مِن قَبْلِهِمْ فَلِلَّهِ الْمَكْرُ جَمِيعًۭا ۖ يَعْلَمُ مَا تَكْسِبُ كُلُّ نَفْسٍۢ ۗ وَسَيَعْلَمُ الْكُفَّـٰرُ لِمَنْ عُقْبَى الدَّارِ",
        "english_text": "And those who were before them Verily did they plan, but reward for their planning is with Allah, He is aware of the deeds of every soul, shortly infidels will also know that good of the Hereafter is for whom.",
        "urdu_text": "اور جو لوگ ان سے پهلے تھے انهوں نے بھی سازشیں کیں لیکن تمام سازشوں کا بدله الله کے پاس هے، وه هر نفس کے اعمال سے واقف هے، عنقریب کافر بھی جان لیں گے که آخرت کی بھلائی کس کے لیے هے۔",
        "persian_text": "و کسانی که پیش از آنان بودند نیز نیرنگ کردند، اما همه نیرنگ‌ها از آن خداست، او می‌داند هر نفسی چه کسب می‌کند، و کافران بزودی خواهند دانست سرای آخرت از آن کیست.",
        "transliteration": "Wa qad makaral lazeena min qablihim fa lillaahil makru jamee'aa, ya'lamu maa taksibu kullu nafs, wa saya'lamul kuffaaru liman 'uqbad Daar",
    },
    {
        "verse_number": 43,
        "arabic_text": "وَيَقُولُ الَّذِينَ كَفَرُواْ لَسْتَ مُرْسَلًا ۚ قُلْ كَفَىٰ بِاللّٰهِ شَهِيدًۢا بَيْنِى وَبَيْنَكُمْ وَ مَنْ عِندَهُ عِلْمُ الْكِتٰبِ",
        "english_text": "And (O Prophet), infidels say that you are not a Prophet, so say: Allah and the person who has knowledge of the Book is sufficient for witness between me and you.",
        "urdu_text": "اور اے نبی! کافر کهتے هیں که تم رسول نهیں هو، تو کهه دو که میرے اور تمهارے درمیان گواه کے طور پر الله اور وه شخص کافی هے جس کے پاس کتاب کا علم هے۔",
        "persian_text": "و ای پیامبر! کافران می‌گویند تو فرستاده نیستی، بگو خداوند و کسی که علم کتاب دارد برای گواهی میان من و شما کافی است.",
        "transliteration": "Wa yaqoolul lazeena kafaroo lasta mursalaa, qul kafaa billaahi shaheedam baynee wa baynakum wa man 'indahoo 'ilmul Kitaab",
    },
]
