ayats = [
    {
        "verse_number": 1,
        "arabic_text": "بِسْمِ اللّٰهِ الرَّحْمـٰنِ الرَّحِيْمِ",
        "urdu_text": "خُدا کے نام سے جو بڑا مهربان نهایت رحم والا هے",
        "persian_text": "به نام خداوند بخشنده مهربان",
        "english_text": "In the name of God, the Most Gracious, the Most Merciful",
        "transliteration": "Bismillāhi r-raḥmāni r-raḥīm",
    },
    {
        "verse_number": 2,
        "arabic_text": "الْحَمْدُ لِلّٰهِ رَبِّ الْعٰلَمِيْنَ",
        "urdu_text": "سب تعریفیں خُدا هی کے لیے هیں جو سارے جهانوں کا پالنے والا هے",
        "persian_text": "ستایش مخصوص خداوندی است که پروردگار جهانیان است",
        "english_text": "All praise is for God, Lord of all the worlds",
        "transliteration": "Al-ḥamdu lillāhi rabbil-ʿālamīn",
    },
    {
        "verse_number": 3,
        "arabic_text": "الرَّحْمـٰنِ الرَّحِيْمِ",
        "urdu_text": "جو بڑا مهربان نهایت رحم والا هے",
        "persian_text": "بخشنده مهربان",
        "english_text": "The Most Gracious, the Most Merciful",
        "transliteration": "Ar-raḥmāni r-raḥīm",
    },
    {
        "verse_number": 4,
        "arabic_text": "مٰلِكِ يَوْمِ الدِّيْنِ",
        "urdu_text": "روزِ جزا کا مالک هے",
        "persian_text": "مالک روز پاداش است",
        "english_text": "Master of the Day of Judgment",
        "transliteration": "Māliki yawmid-dīn",
    },
    {
        "verse_number": 5,
        "arabic_text": "اِيَّاكَ نَعْبُدُ وَ اِيَّاكَ نَسْتَعِيْنُ",
        "urdu_text": "هم تیری هی عبادت کرتے هیں اور تجھ هی سے مدد چاهتے هیں",
        "persian_text": "تنها تو را می‌پرستیم و تنها از تو یاری می‌جوییم",
        "english_text": "You alone we worship, and You alone we ask for help",
        "transliteration": "Iyyāka naʿbudu wa iyyāka nastaʿīn",
    },
    {
        "verse_number": 6,
        "arabic_text": "اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ",
        "urdu_text": "همیں سیدھا راسته دکھا",
        "persian_text": "ما را به راه راست هدایت فرما",
        "english_text": "Guide us on the Straight Path",
        "transliteration": "Ihdinaṣ-ṣirāṭ al-mustaqīm",
    },
    {
        "verse_number": 7,
        "arabic_text": "صِرَاطَ الَّذِيْنَ اَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَ لَا الضَّآلِّيْنَ",
        "urdu_text": "ان لوگوں کا راسته جن پر تونے اپنے نعمت عطا کی هے ، انکا راسته نهیں جن پر غضب نازل هوا هے یا جو گمراه هوے هیں",
        "persian_text": "راه کسانی که به آنان نعمت دادی، نه کسانی که خشمگین شدند و نه گمراهان",
        "english_text": "The path of those You have blessed, not of those who earned Your anger or went astray",
        "transliteration": "Ṣirāṭ al-ladhīna anʿamta ʿalayhim ghayril-maghḍūbi ʿalayhim walāḍ-ḍāllīn",
    },
]
