ayats = [
  {
    "verse_number": 1,
    "english_text": "Have We not expanded for you, your breast?",
    "arabic_text": "اَلَمْ نَشْرَحْ لَكَ صَدْرَكَ",
    "urdu_text": "کیا ہم نے آپ کا سینہ کھول نہیں دیا؟",
    "persian_text": "آیا سینه‌ات را برایت گشاده نکردیم؟",
    "transliteration": "Alam nashrah laka sadrak",
  },
  {
    "verse_number": 2,
    "english_text": "And have we not taken off your burden?",
    "arabic_text": "وَ وَضَعْنَا عَنكَ وِزْرَكَ",
    "urdu_text": "اور ہم نے آپ کا بوجھ اتار دیا",
    "persian_text": "و بار گرانت را از دوشت برداشتیم",
    "transliteration": "Wa wada'na 'anka wizrak",
  },
  {
    "verse_number": 3,
    "english_text": "Which had broken your back.",
    "arabic_text": "الَّذِىْٓ اَنْقَضَ ظَهْرَكَ",
    "urdu_text": "جس نے آپ کی کمر توڑ دی تھی",
    "persian_text": "که پشتت را خم کرده بود",
    "transliteration": "Allazi anqada zahrak",
  },
  {
    "verse_number": 4,
    "english_text": "And have exalted your remembrance?",
    "arabic_text": "وَ رَفَعْنَا لَكَ ذِكْرَكَ",
    "urdu_text": "اور ہم نے آپ کا ذکر بلند کر دیا",
    "persian_text": "و یاد تو را برایت بلند کردیم",
    "transliteration": "Wa rafa'na laka zikrak",
  },
  {
    "verse_number": 5,
    "english_text": "Yes! With difficulty is also the ease.",
    "arabic_text": "فَاِنَّ مَعَ الْعُسْرِ يُسْرًا",
    "urdu_text": "پس بے شک مشکل کے ساتھ آسانی ہے",
    "persian_text": "پس همانا با سختی آسانی است",
    "transliteration": "Fa inna ma'al 'usri yusra",
  },
  {
    "verse_number": 6,
    "english_text": "Verily with the difficulty, there is more relief.",
    "arabic_text": "اِنَّ مَعَ الْعُسْرِ يُسْرًا",
    "urdu_text": "بیشک مشکل کے ساتھ آسانی ہے",
    "persian_text": "همانا با سختی آسانی است",
    "transliteration": "Inna ma'al 'usri yusra",
  },
  {
    "verse_number": 7,
    "english_text": "So, when you become free (from your obligations), do nominate.",
    "arabic_text": "فَاِذَا فَرَغْتَ فَانصَبْ",
    "urdu_text": "پھر جب آپ فارغ ہوں تو عبادت میں محنت کریں",
    "persian_text": "پس چون فارغ شدی، به عبادت بپرداز",
    "transliteration": "Fa-idha faraghta fansab",
  },
  {
    "verse_number": 8,
    "english_text": "And turn to your Lord.",
    "arabic_text": "وَ اِلَٰى رَبِّكَ فَارْغَبْ",
    "urdu_text": "اور اپنے رب کی طرف راغب ہوں",
    "persian_text": "و به سوی پروردگارت رغبت کن",
    "transliteration": "Wa ila rabbika farghab",
  },
]
