ayats = [
  {
    "verse_number": 1,
    "english_text": "Whatever is in the skies and on the earth, everything is busy glorifying Allah, and He is Honorable and Owner of Wisdom.",
    "arabic_text": "سَبَّحَ لِلّٰهِ مَا فِى السَّمٰوٰتِ وَ مَا فِى الْاَرْضِ ۖ وَ هُوَ الْعَزِيزُ الْحَكِيمُ",
    "urdu_text": "جو کچھ آسمانوں میں ہے اور جو کچھ زمین میں ہے سب اللہ کی تسبیح کرتا ہے، اور وہ غالب اور حکمت والا ہے۔",
    "persian_text": "آنچه در آسمان‌ها و آنچه در زمین است، همه تسبیح الله می‌گویند و او عزیز و حکیم است.",
    "transliteration": "Sabbaha lillahi ma fis-samawati wa ma fil-ard, wa huwal-'Azizul-Hakim",
  },
  {
    "verse_number": 2,
    "english_text": "It is He who got out unbelievers among the People of the Book from their homes at the first gathering and you were not even imagining that they can be exiled, and they were also of the opinion that their forts will saved them from Allah, but Allah behaved in such a way that they could not had envisage about it, and cast terror in their hearts that they started to destroy their houses from their own hands and from the hands of the believers; so that people with the vision may take the lesson.",
    "arabic_text": "هُوَ الَّذِى اَخْرَجَ الَّذِينَ كَفَرُوا مِنْ اَهْلِ الْكِتٰبِ مِن دِيَارِهِمْ لِاَوَّلِ الْحَشْرِ ۚ مَا ظَنَنتُمْ اَن يَخْرُجُوا وَظَنُّوا اَنَّهُم مَّانِعَتُهُمْ حُصُونُهُم مِّنَ اللّٰهِ فَاَتَاهُمُ اللّٰهُ مِنْ حَيْثُ لَمْ يَحْتَسِبُوا وَقَذَفَ فِى قُلُوبِهِمُ الرُّعْبَ",
    "urdu_text": "وہی ہے جس نے اہل کتاب میں سے کافروں کو پہلی جلاوطنی میں ان کے گھروں سے نکال دیا، تم نے یہ گمان بھی نہیں کیا تھا کہ وہ نکل جائیں گے اور انہوں نے سمجھا تھا کہ ان کے قلعے انہیں اللہ سے بچا لیں گے، لیکن اللہ ان پر ایسی جگہ سے آیا جہاں سے انہوں نے گمان بھی نہیں کیا تھا اور ان کے دلوں میں رعب ڈال دیا۔",
    "persian_text": "او کسی است که کافران اهل کتاب را در اولین حشر از خانه‌هایشان بیرون کرد، شما گمان نمی‌بردید که آنها بیرون روند و آنها پنداشتند که قلعه‌هایشان آنها را از الله محافظت خواهد کرد، اما الله از جایی که گمان نمی‌بردند بر آنها آمد و در دل‌هایشان رعب افکند.",
    "transliteration": "Huwal-ladhi akhraja alladhina kafaru min ahlil-kitabi min diyarihim li-awwalil-hashr, ma zanantum an yakhruju wa zannu annahum mani'atuhum husunuhum minallahi fa-atahumullaahu min haythu lam yahtasibu wa qadhafa fi qulubihimur-ru'b",
  },
  {
    "verse_number": 3,
    "english_text": "If Allah would not have written exile in their fate, then He would have sent punishment on them in the world, and in the Hereafter punishment of Hell is certain.",
    "arabic_text": "وَ لَوْلَا اَن كَتَبَ اللّٰهُ عَلَيْهِمُ الْجَلَآءَ لَعَذَّبَهُمْ فِى الدُّنْيَا ۖ وَلَهُمْ فِى الْءَاخِرَةِ عَذَابُ النَّارِ",
    "urdu_text": "اور اگر اللہ نے ان کی تقدیر میں جلاوطنی نہ لکھی ہوتی تو انہیں دنیا میں عذاب دیتا، اور آخرت میں ان کے لیے آگ کا عذاب ہے۔",
    "persian_text": "و اگر الله تبعید را بر آنها مقرر نکرده بود، قطعاً در دنیا آنها را عذاب می‌داد و برای آنها در آخرت عذاب آتش است.",
    "transliteration": "Wa lawla an kataballahu 'alayhimul-jala'a la-'adhdhabahum fid-dunya, wa lahum fil-akhirati 'adhabun-nar",
  },
  {
    "verse_number": 4,
    "english_text": "This is because they disputed with Allah and His prophet, and those who dispute with Allah, then Allah is severe in punishment.",
    "arabic_text": "ذٰلِكَ بِاَنَّهُمْ شَآقُّوا اللّٰهَ وَرَسُولَهُ ۖ وَ مَن يُشَآقِّ اللّٰهَ فَاِنَّ اللّٰهَ شَدِيدُ الْعِقَابِ",
    "urdu_text": "یہ اس لیے کہ انہوں نے اللہ اور اس کے رسول سے مخالفت کی، اور جو اللہ سے مخالفت کرے تو بیشک اللہ سخت عذاب دینے والا ہے۔",
    "persian_text": "این بدان سبب است که آنها با الله و رسولش دشمنی کردند و هر کس با الله دشمنی کند، پس الله سخت‌کیفر است.",
    "transliteration": "Dhalika bi-annahum shaqqullaha wa Rasulah, wa man yushaqqillaha fa-innallaha shadid-ul-'iqab",
  },
  {
    "verse_number": 5,
    "english_text": "O Muslims! Whether you cut the palm-tree branches or left them on their roots, this was all with the permission of Allah, that Allah may disgrace the transgressors.",
    "arabic_text": "مَا قَطَعْتُم مِّن لِّينَةٍ اَوْ تَرَكْتُمُوهَا قَآئِمَةً عَلَىٰۤ اُصُولِهَا فَبِاِذْنِ اللّٰهِ وَلِيُخْزِىَ الْفَـٰسِقِينَ",
    "urdu_text": "اے مسلمانو! تم نے جو کھجور کے درخت کاٹے یا انہیں ان کی جڑوں پر کھڑا چھوڑ دیا، یہ سب اللہ کے حکم سے تھا تاکہ اللہ نافرمانوں کو رسوا کرے۔",
    "persian_text": "ای مسلمانان! آنچه از درختان خرما بریدید یا آنها را بر ریشه‌هایشان برپا گذاشتید، همه به اذن الله بود تا نافرمانان را خوار کند.",
    "transliteration": "Ma qata'tum mil-linatin aw taraktumuhaa qa'imatan 'ala usuliha fabi-idhnillahi wa liyukhziyal-fasiqin",
  },
  {
    "verse_number": 6,
    "english_text": "And whatever war booty Allah has made available from them to the Prophet, for that you made no expedition either through your horses or camels, but Allah gave domination to His prophet and Allah has power over everything.",
    "arabic_text": "وَ مَا اَفَاءَ اللّٰهُ عَلَٰى رَسُولِهِ مِنْهُمْ فَمَآ اَوْجَفْتُمْ عَلَيْهِ مِنْ خَيْلٍۢ وَ لَا رِكَابٍ وَ لَٰكِنَّ اللّٰهَ يُسَلِّطُ رُسُلَهُ عَلَٰى مَن يَشَآءُ ۚ وَاللّٰهُ عَلَٰى كُلِّ شَىْءٍۢ قَدِيرٌ",
    "urdu_text": "اور جو مال اللہ نے ان سے اپنے رسول کو دلوایا اس پر تم نے نہ گھوڑے دوڑائے اور نہ اونٹ، لیکن اللہ اپنے رسولوں کو جس پر چاہتا ہے غالب کر دیتا ہے، اور اللہ ہر چیز پر قادر ہے۔",
    "persian_text": "و آنچه خداوند از آنان به پیامبرش بازگردانید، شما برای آن نه اسبی تاختید و نه شتری، ولی خداوند پیامبرانش را بر هر که بخواهد چیره می‌گرداند، و خداوند بر هر چیزی تواناست.",
    "transliteration": "Wa maa afaa Allahu 'alaa Rasoolihi minhum famaa awjaftum 'alayhi min khaylin wa laa rikaab, wa laakinna Allaha yusallit Rusulahu 'alaa man yashaa, wa Allahu 'alaa kulli shay'in Qadeer",
  },
  {
    "verse_number": 7,
    "english_text": "Whatever Allah has made available from the people of the towns, all belong to Allah, to His prophet, relatives of the prophet, orphans, destitute and to poor-travelers; that all the wealth may not circulate and may not remain among the wealthy people only; and take whatever prophet give you, and refrain from whatever he prohibits you, and fear Allah; for Allah is strict in punishment.",
    "arabic_text": "مَّآ اَفَآءَ اللّٰهُ عَلَٰى رَسُولِهِ مِنْ اَهْلِ الْقُرٰى فَلِلّٰهِ وَلِلرَّسُولِ وَلِذِى الْقُرْبَىٰ وَالْيَتَـٰمَىٰ وَالْمَسَـٰكِينِ وَابْنِ السَّبِيلِ كَىْ لَا يَكُونَ دُولَةًۢ بَيْنَ الْاَغْنِيَآءِ مِنكُمْ ۚ وَمَآ ءَاتَىٰكُمُ الرَّسُولُ فَخُذُوهُ ۖ وَ مَا نَهَىٰكُمْ عَنْهُ فَانتَهُواْ ۚ وَاتَّقُواْ اللّٰهَ ۖ اِنَّ اللّٰهَ شَدِيدُ الْعِقَابِ",
    "urdu_text": "جو مال اللہ نے بستیوں والوں سے اپنے رسول کو دلوایا وہ اللہ کا ہے اور رسول کا ہے اور قرابت داروں کا اور یتیموں کا اور مسکینوں کا اور مسافروں کا، تاکہ وہ تمہارے دولت مندوں کے درمیان ہی گردش نہ کرتا رہے، اور جو کچھ رسول تمہیں دے وہ لے لو اور جس سے منع کرے اس سے رک جاؤ، اور اللہ سے ڈرو، بیشک اللہ سخت عذاب دینے والا ہے۔",
    "persian_text": "آنچه خداوند از اهل شهرها به پیامبرش بازگردانید، از آن خداست و پیامبر و خویشاوندان و یتیمان و بینوایان و در راه ماندگان، تا میان ثروتمندان شما دست به دست نگردد، و آنچه پیامبر به شما داد بگیرید و از آنچه نهی کرد خودداری کنید، و از خدا پروا کنید، همانا خداوند سخت کیفر است.",
    "transliteration": "Maa afaa Allahu 'alaa Rasoolihi min ahli al-quraa fa lillahi wa lir-Rasooli wa li dhil-qurbaa wal-yataamaa wal-masaakeeni wabni as-sabeeli kay laa yakoona doolatan bayna al-aghniyaa'i minkum, wa maa aataakumu ar-Rasoolu fa-khudhoohu wa maa nahaakum 'anhu fantahoo, wattaqoo Allah, inna Allaha shadeedu al-'iqaab",
  },
  {
    "verse_number": 8,
    "english_text": "This wealth belongs to the poor migrants also who have been expelled from their homes and property and they only desire the Grace and Pleasure of Allah and help Allah and His prophet, these are the people who are true to their claim in believing.",
    "arabic_text": "لِلْفُقَرَآءِ الْمُهٰجِرِينَ الَّذِينَ اُخْرِجُواْ مِن دِيَـٰرِهِمْ وَاَمْوَٰلِهِمْ يَبْتَغُونَ فَضْلًا مِّنَ اللّٰهِ وَرِضْوَٰنًۭا وَيَنصُرُونَ اللّٰهَ وَرَسُولَهُٓ ۚ اُو۟لَـٰٓئِكَ هُمُ الصَّـٰدِقُونَ",
    "urdu_text": "یہ مال ان غریب مہاجرین کے لیے بھی ہے جو اپنے گھروں اور اپنے مالوں سے نکال دیے گئے، وہ اللہ کا فضل اور اس کی رضا چاہتے ہیں اور اللہ اور اس کے رسول کی مدد کرتے ہیں، یہی لوگ سچے ہیں۔",
    "persian_text": "این مال برای مهاجران فقیری است که از خانه‌ها و اموالشان بیرون رانده شدند، آنان که فضل و خشنودی خدا را می‌جویند و خدا و پیامبرش را یاری می‌کنند، اینان همان راستگویانند.",
    "transliteration": "Lil-fuqaraa'i al-muhaajireena alladheena ukhrijoo min diyaarihim wa amwaalihim yabtaghoona fadlan mina Allahi wa ridwaanan wa yansuroona Allaha wa Rasoolahu, ulaa'ika humu as-saadiqoon",
  },
  {
    "verse_number": 9,
    "english_text": "And those who earlier had their homes (in Madina) and adopted faith before them and show affection to those who came to them after migration; and had no desire in their hearts for whatever was given to them and prefers others over themselves no matter how needful they themselves may be, and those who are saved from the greed of their Selves, they shall achieve the desires of their hearts.",
    "arabic_text": "وَ الَّذِينَ تَبَوَّءُوا الدَّارَ وَالْاِيمَـٰنَ مِن قَبْلِهِمْ يُحِبُّونَ مَنْ هَاجَرَ اِلَيْهِمْ وَ لَا يَجِدُونَ فِى صُدُورِهِمْ حَاجَةًۭ مِّمَّآ اُوتُواْ وَيُؤْثِرُونَ عَلَىٰٓ اَنفُسِهِمْ وَ لَوْ كَانَ بِهِمْ خَصَاصَةٌۭ ۚ وَ مَن يُوقَ شُحَّ نَفْسِهِ فَاُو۟لَـٰٓئِكَ هُمُ الْمُفْلِحُونَ",
    "urdu_text": "اور وہ لوگ جنہوں نے ان سے پہلے مدینہ میں گھر بنایا اور ایمان اختیار کیا، وہ ان سے محبت کرتے ہیں جو ان کی طرف ہجرت کر کے آئے، اور اپنے دلوں میں اس چیز کی کوئی حاجت نہیں پاتے جو انہیں دی گئی، اور اپنی جانوں پر دوسروں کو ترجیح دیتے ہیں اگرچہ خود محتاج ہوں، اور جو اپنے نفس کے لالچ سے بچا لیا گیا تو یہی لوگ کامیاب ہیں۔",
    "persian_text": "و آنان که پیش از آنان در این سرزمین و در ایمان جای گرفتند، کسانی را که به سوی آنان هجرت کردند دوست می‌دارند و در دلهایشان نیازی به آنچه به مهاجران داده شد نمی‌یابند، و دیگران را بر خود ترجیح می‌دهند هر چند خود نیازمند باشند، و کسانی که از بخل و حرص خویش نگاه داشته شوند، آنان همان رستگارانند.",
    "transliteration": "Walladheena tabawwa'oo ad-daara wal-eemaana min qablihim yuhibboona man haajara ilayhim wa laa yajidoona fee sudoorihim haajatan mimmaa ootoo wa yu'thiroona 'alaa anfusihim wa law kaana bihim khasaasah, wa man yooqa shuhha nafsihi fa-ulaa'ika humu al-muflihoon",
  },
  {
    "verse_number": 10,
    "english_text": "And those who came after them say: O Lord forgive us and also our brethren who accepted faith before us and do not let the malice take place in our hearts for the believers, O Lord, You are very Kind and Merciful.",
    "arabic_text": "وَ الَّذِينَ جَآءُواْ مِنۢ بَعْدِهِمْ يَقُولُونَ رَبَّنَا اغْفِرْ لَنَا وَلِاِخْوَٰنِنَا الَّذِينَ سَبَقُونَا بِالْاِيمَـٰنِ وَ لَا تَجْعَلْ فِى قُلُوبِنَا غِلًّۭا لِّلَّذِينَ ءَامَنُواْ ۚ رَبَّنَآ اِنَّكَ رَءُوفٌۭ رَّحِيمٌۭ",
    "urdu_text": "اور وہ لوگ جو ان کے بعد آئے کہتے ہیں: اے ہمارے رب! ہمیں بخش دے اور ہمارے ان بھائیوں کو بھی جو ایمان میں ہم سے پہلے گزر گئے، اور ہمارے دلوں میں مومنوں کے لیے کوئی کینہ نہ رکھ، اے ہمارے رب! بیشک تو بڑا مہربان نہایت رحم کرنے والا ہے۔",
    "persian_text": "و آنان که پس از ایشان آمدند می‌گویند: پروردگارا! ما و برادرانمان را که در ایمان بر ما پیشی گرفتند بیامرز، و در دلهای ما نسبت به مؤمنان کینه‌ای قرار مده، پروردگارا! تو مهربان و بخشنده‌ای.",
    "transliteration": "Walladheena jaa'oo min ba'dihim yaqooloona Rabbanagh-fir lanaa wa li-ikhwaanina alladheena sabaqoonaa bil-eemaani wa laa taj'al fee quloobinaa ghillan lilladheena aamanoo, Rabbanaa innaka Ra'oofun Raheem",
  },
  {
    "verse_number": 11,
    "english_text": "Did not you see the condition of the hypocrites that they say to their unbelieving brothers among the people of the book that if you are expelled, we will also go with you and will not obey anyone concerning you, and if you are attacked, we will help you; and Allah is witness that they are totally liars.",
    "arabic_text": "اَلَمْ تَرَ اِلَى الَّذِينَ نَافَقُواْ يَقُولُونَ لِاِخْوَٰنِهِمُ الَّذِينَ كَفَرُواْ مِنْ اَهْلِ الْكِتٰبِ لَئِنْ اُخْرِجْتُمْ لَنَخْرُجَنَّ مَعَكُمْ وَ لَا نُطِيعُ فِيكُمْ اَحَدًا اَبَدًۭا وَ اِن قُوتِلْتُمْ لَنَنصُرَنَّكُمْ ۚ وَاللّٰهُ يَشْهَدُ اِنَّهُمْ لَكَـٰذِبُونَ",
    "urdu_text": "کیا تم نے منافقوں کی حالت نہیں دیکھی کہ وہ اہل کتاب میں سے اپنے کافر بھائیوں سے کہتے ہیں کہ اگر تم نکالے گئے تو ہم بھی تمہارے ساتھ ضرور نکل جائیں گے اور تمہارے بارے میں کبھی کسی کی بات نہیں مانیں گے، اور اگر تم سے جنگ کی گئی تو ہم ضرور تمہاری مدد کریں گے، اور اللہ گواہی دیتا ہے کہ یہ بالکل جھوٹے ہیں",
    "persian_text": "آیا ندیدی حال منافقانی را که به برادران کافر خود از اهل کتاب می‌گویند که اگر شما بیرون رانده شوید، ما نیز با شما بیرون خواهیم رفت و هرگز در باره شما از کسی اطاعت نخواهیم کرد، و اگر با شما جنگ شود، حتماً شما را یاری خواهیم داد؛ و خداوند گواهی می‌دهد که آنها کاملاً دروغگو هستند",
    "transliteration": "Alam tara ilal-ladhina nafaqu yaquluna li-ikhwanihimul-ladhina kafaru min ahlil-kitabi la'in ukhrijtum lanakhrujanna ma'akum wa la nuti'u fikum ahadan abadan wa in qutiltum lanansurannakum wallahu yashhadu innahum lakathibun",
  },
  {
    "verse_number": 12,
    "english_text": "If they are expelled, they will not go with them; if they are attacked, they will never help them, and even if they help - they will turn their backs and run away, then no one will be there to help them.",
    "arabic_text": "لَئِنْ اُخْرِجُواْ لَا يَخْرُجُونَ مَعَهُمْ ۖ وَلَئِن قُوتِلُواْ لَا يَنصُرُونَهُمْ ۖ وَلَئِن نَّصَرُوهُمْ لَيُوَلُّنَّ الْاَدْبَـٰرَ ثُمَّ لَا يُنصَرُونَ",
    "urdu_text": "اگر وہ نکالے گئے تو یہ ان کے ساتھ نہیں نکلیں گے، اور اگر ان سے جنگ کی گئی تو یہ کبھی ان کی مدد نہیں کریں گے، اور اگر مدد بھی کریں تو پیٹھ پھیر کر بھاگ جائیں گے، پھر ان کی کوئی مدد نہیں کرے گا",
    "persian_text": "اگر آنها بیرون رانده شوند، اینها با آنها بیرون نخواهند رفت، و اگر با آنها جنگ شود، هرگز یاریشان نخواهند کرد، و اگر هم یاریشان کنند، حتماً پشت کرده فرار خواهند کرد، سپس کسی یاریشان نخواهد کرد",
    "transliteration": "La'in ukhriju la yakhrujna ma'ahum wa la'in qutilu la yansuruhum wa la'in nasaruhum layuwallunnal-adbara thumma la yunsarun",
  },
  {
    "verse_number": 13,
    "english_text": "O Muslims! You arouse greater fear in their hearts than Allah, this is because this nation is devoid of understanding.",
    "arabic_text": "لَاَنتُمْ اَشَدُّ رَهْبَةًۭ فِى صُدُورِهِم مِّنَ اللّٰهِ ۚ ذٰلِكَ بِاَنَّهُمْ قَوْمٌۭ لَّا يَفْقَهُونَ",
    "urdu_text": "اے مسلمانو! تم ان کے دلوں میں اللہ سے زیادہ خوف پیدا کرتے ہو، یہ اس لیے کہ یہ قوم سمجھ نہیں رکھتی",
    "persian_text": "ای مسلمانان! شما در دلهای آنها بیش از خدا ترس ایجاد می‌کنید، این بدان سبب است که آنها قومی هستند که درک نمی‌کنند",
    "transliteration": "La'antum ashaddu rahbatan fi sudurihim minallahi dhalika bi'annahum qawmul-la yafqahun",
  },
  {
    "verse_number": 14,
    "english_text": "They will never fight collectively with you except when they are in secured towns or from behind the walls, strong is their fighting spirit among them, you think they are united, never, there is severe discord in their hearts; and this is because this nation has no wisdom.",
    "arabic_text": "لَا يُقَـٰتِلُونَكُمْ جَمِيعًا اِلَّا فِى قُرًى مُّحَصَّنَةٍ اَوْ مِن وَرَآءِ جُدُرٍۢ ۚ بَاْسُهُم بَيْنَهُمْ شَدِيدٌۭ ۖ تَحْسَبُهُمْ جَمِيعًۭا وَقُلُوبُهُمْ شَتَّىٰ ۚ ذٰلِكَ بِاَنَّهُمْ قَوْمٌۭ لَّا يَعْقِلُونَ",
    "urdu_text": "یہ تم سے اکٹھے ہو کر کبھی نہیں لڑیں گے سوائے محفوظ بستیوں میں یا دیواروں کے پیچھے سے، ان میں آپس میں لڑنے کا جوش بہت سخت ہے، تم انہیں متحد سمجھتے ہو حالانکہ ان کے دل بکھرے ہوئے ہیں، یہ اس لیے کہ یہ قوم عقل نہیں رکھتی",
    "persian_text": "آنها هرگز با شما جمعی جنگ نخواهند کرد مگر در شهرهای محصن یا از پشت دیوارها، جنگاوری آنها در میان خودشان شدید است، تو آنها را متحد می‌پنداری ولی دلهایشان پراکنده است، این بدان سبب است که آنها قومی هستند که خرد ندارند",
    "transliteration": "La yuqatilunakum jami'an illa fi quran muhassanatin aw min wara'i judurin ba'suhum baynahum shadidun tahsabuhum jami'an wa qulubuhum shatta dhalika bi'annahum qawmul-la ya'qilun",
  },
  {
    "verse_number": 15,
    "english_text": "Like recently what has happened to the earlier people, they tasted the result of their conduct, and there is also painful punishment for them.",
    "arabic_text": "كَمَثَلِ الَّذِينَ مِن قَبْلِهِمْ قَرِيبًا ذَاقُواْ وَبَالَ اَمْرِهِمْ ۖ وَلَهُمْ عَذَابٌ اَلِيمٌۭ",
    "urdu_text": "ان سے پہلے لوگوں کی مثال کی طرح جو ابھی حال ہی میں ہوا، انہوں نے اپنے کام کا وبال چکھا، اور ان کے لیے دردناک عذاب بھی ہے",
    "persian_text": "همانند کسانی که پیش از آنها بودند که اخیراً عاقبت کار خود را چشیدند، و برای آنها عذاب دردناکی نیز هست",
    "transliteration": "Kamathali-lladhina min qablihim qariban dhaqu wabala amrihim wa lahum 'adhabun alim",
  },
  {
    "verse_number": 16,
    "english_text": "Their example is like Satan that he says to man: \"adopt infidelity\" and when he becomes infidel Satan says: I am free from you, I fear the Lord of the Worlds.",
    "arabic_text": "كَمَثَلِ الشَّيْطَـٰنِ اِذْ قَالَ لِلْاِنسَـٰنِ اكْفُرْ ۖ فَلَمَّا كَفَرَ قَالَ اِنِّى بَرِىٓءٌۭ مِّنكَ اِنِّىٓ اَخَافُ اللّٰهَ رَبَّ الْعَـٰلَمِينَ",
    "urdu_text": "ان کی مثال شیطان کی سی ہے جب اس نے انسان سے کہا کفر اختیار کرو، پھر جب وہ کافر ہو گیا تو کہنے لگا میں تجھ سے بیزار ہوں، میں اللہ رب العالمین سے ڈرتا ہوں",
    "persian_text": "مثل آنها مانند شیطان است که به انسان گفت کافر شو، پس چون کافر شد گفت من از تو بیزارم، من از خداوند جهانیان می‌ترسم",
    "transliteration": "Kamathali ash-shaytani idh qala lil-insani ukfur falamma kafara qala inni bari'un minka inni akhafu Allaha rabbal-'alamin",
  },
  {
    "verse_number": 17,
    "english_text": "So consequence of both of them is that both shall abide in the Hell forever; and this is really the punishment of the unjust.",
    "arabic_text": "فَكَانَ عَـٰقِبَتَهُمَآ اَنَّهُمَا فِى النَّارِ خَـٰلِدَيْنِ فِيهَا ۚ وَ ذٰلِكَ جَزَٰٓؤُاْ الظَّـٰلِمِينَ",
    "urdu_text": "پس ان دونوں کا انجام یہ ہوا کہ دونوں آگ میں ہمیشہ رہنے والے ہیں، اور یہی ظالموں کی سزا ہے",
    "persian_text": "پس عاقبت هر دوی آنها این است که هر دو در آتش جاودانه خواهند ماند و این است جزای ستمکاران",
    "transliteration": "Fakana 'aqibatahuma annahuma fin-nari khalidayni fiha wa dhalika jaza'u az-zalimin",
  },
  {
    "verse_number": 18,
    "english_text": "O you who believe! Fear Allah, and every person should see what he has sent for tomorrow (the Hereafter) and keep fearing Allah, He is indeed well aware of your deeds.",
    "arabic_text": "يَـٰٓاَيُّهَا الَّذِينَ ءَامَنُواْ اتَّقُواْ اللّٰهَ ۖ وَلْتَنظُرْ نَفْسٌۭ مَّا قَدَّمَتْ لِغَدٍۢ ۖ وَاتَّقُواْ اللّٰهَ ۚ اِنَّ اللّٰهَ خَبِيرٌۢ بِمَا تَعْمَلُونَ",
    "urdu_text": "اے ایمان والو! اللہ سے ڈرو، اور ہر شخص دیکھے کہ اس نے کل کے لیے کیا آگے بھیجا ہے، اور اللہ سے ڈرتے رہو، بیشک اللہ تمہارے اعمال سے خوب باخبر ہے",
    "persian_text": "ای کسانی که ایمان آورده‌اید از خدا بترسید و هر کسی بنگرد که برای فردا چه پیش فرستاده است و از خدا بترسید، همانا خدا به آنچه انجام می‌دهید آگاه است",
    "transliteration": "Ya ayyuha alladhina amanu ittaqu Allaha waltanzur nafsun ma qaddamat lighadin wattaqu Allah inna Allaha khabirun bima ta'malun",
  },
  {
    "verse_number": 19,
    "english_text": "And beware! do not be like those who have forgotten Allah; so Allah Himself have also forgotten their Selves, and indeed they are all transgressors.",
    "arabic_text": "وَ لَا تَكُونُواْ كَالَّذِينَ نَسُواْ اللّٰهَ فَاَنسَىٰهُمْ اَنفُسَهُمْ ۚ اُو۟لَـٰٓئِكَ هُمُ الْفَـٰسِقُونَ",
    "urdu_text": "اور تم ان لوگوں کی طرح نہ ہو جانا جنہوں نے اللہ کو بھلا دیا تو اللہ نے بھی انہیں ان کے نفسوں کو بھلا دیا، یہی لوگ نافرمان ہیں",
    "persian_text": "و مانند کسانی نباشید که خدا را فراموش کردند پس خدا هم آنها را از خودشان غافل ساخت، اینان همان نافرمانانند",
    "transliteration": "Wala takunu kalladhina nasu Allaha fa-ansahum anfusahum ula'ika humu al-fasiqun",
  },
  {
    "verse_number": 20,
    "english_text": "Companions of Paradise and Companions of Hell cannot be alike, Companions of Paradise are those who will achieve success.",
    "arabic_text": "لَا يَسْتَوِىٓ اَصْحَـٰبُ النَّارِ وَاَصْحَـٰبُ الْجَنَّةِ ۚ اَصْحَـٰبُ الْجَنَّةِ هُمُ الْفَآئِزُونَ",
    "urdu_text": "دوزخ والے اور جنت والے برابر نہیں ہو سکتے، جنت والے ہی کامیاب ہیں",
    "persian_text": "اهل آتش و اهل بهشت یکسان نیستند، اهل بهشت همان رستگارانند",
    "transliteration": "La yastawi as-habu an-nari wa as-habu al-jannah as-habu al-jannati humu al-fa'izun",
  },
  {
    "verse_number": 21,
    "english_text": "Had We revealed this Quran on a mountain then you would have seen it tremble and become pieces with the Fear of Allah, and We describe these examples for man that perhaps they may ponder about it.",
    "arabic_text": "لَوْ اَنزَلْنَا هٰذَا الْقُرْءَانَ عَلَٰى جَبَلٍۢ لَّرَاَيْتَهُ خَـٰشِعًۭا مُّتَصَدِّعًۭا مِّنْ خَشْيَةِ اللّٰهِ ۚ وَتِلْكَ الْاَمْثَـٰلُ نَضْرِبُهَا لِلنَّاسِ لَعَلَّهُمْ يَتَفَكَّرُونَ",
    "urdu_text": "اگر ہم نے یہ قرآن کسی پہاڑ پر نازل کیا ہوتا تو تم اسے دیکھتے کہ وہ اللہ کے خوف سے عاجزی کرتا اور ٹکڑے ٹکڑے ہو جاتا، اور یہ مثالیں ہم لوگوں کے لیے بیان کرتے ہیں تاکہ وہ غور و فکر کریں",
    "persian_text": "اگر این قرآن را بر کوهی نازل می‌کردیم، آن را می‌دیدی که از ترس خدا فروتن و متلاشی می‌شد، و این مثال‌ها را برای مردم می‌زنیم تا شاید تفکر کنند",
    "transliteration": "Law anzalna hadha al-Qur'ana 'ala jabalin lara'aytahu khashi'an mutasaddi'an min khashyatillah, wa tilka al-amthalu nadribuha linnasi la'allahum yatafakkarun",
  },
  {
    "verse_number": 22,
    "english_text": "That is Allah, there is no god but He, He is the knower of the Unseen and the seen; He is the Most Gracious, the All-compassionate.",
    "arabic_text": "هُوَ اللّٰهُ الَّذِى لَآ اِلَـٰهَ اِلَّا هُوَ ۖ عَـٰلِمُ الْغَيْبِ وَالشَّهٰدَةِ ۖ هُوَ الرَّحْمَـٰنُ الرَّحِيمُ",
    "urdu_text": "وہی اللہ ہے جس کے سوا کوئی معبود نہیں، وہ غیب اور حاضر کا جاننے والا ہے، وہ بڑا مہربان نہایت رحم والا ہے",
    "persian_text": "او خداوندی است که جز او معبودی نیست، دانای نهان و آشکار است، او بخشنده مهربان است",
    "transliteration": "Huwa Allahu alladhi la ilaha illa Huwa, 'alimu al-ghaybi wa ash-shahadah, Huwa ar-Rahmanu ar-Rahim",
  },
  {
    "verse_number": 23,
    "english_text": "That is Allah, there is no god but He. He is the King, Having Holy Attributes, Flawless, Giver of the Refuge, Guardian, Exalted in Honor, Greatest, Owner of Pride; He is above all the talk which polytheists do.",
    "arabic_text": "هُوَ اللّٰهُ الَّذِى لَآ اِلَـٰهَ اِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَـٰمُ الْمُؤْمِنُ الْمُهَيْمِنُ الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ ۚ سُبْحَـٰنَ اللّٰهِ عَمَّا يُشْرِكُونَ",
    "urdu_text": "وہی اللہ ہے جس کے سوا کوئی معبود نہیں، وہ بادشاہ ہے، پاک ہے، سلامتی دینے والا ہے، امن دینے والا ہے، نگہبان ہے، غالب ہے، زبردست ہے، بڑائی والا ہے، اللہ پاک ہے ان باتوں سے جو مشرک بیان کرتے ہیں",
    "persian_text": "او خداوندی است که جز او معبودی نیست، پادشاه، قدوس، سلام، مؤمن، مهیمن، عزیز، جبار، متکبر است، خداوند منزه است از آنچه مشرکان می‌گویند",
    "transliteration": "Huwa Allahu alladhi la ilaha illa Huwa al-Maliku al-Quddusu as-Salamu al-Mu'minu al-Muhaymin al-'Azizu al-Jabbaru al-Mutakabbir, Subhanallahi 'amma yushrikun",
  },
  {
    "verse_number": 24,
    "english_text": "That is Allah who creates, invents, and makes faces; to Him belong the Most Beautiful Names, every particle of the earth and the skies is busy glorifying him, and He is Honorable and has Wisdom.",
    "arabic_text": "هُوَ اللّٰهُ الْخَـٰلِقُ الْبَارِئُ الْمُصَوِّرُ ۖ لَهُ الْاَسْمَآءُ الْحُسْنَىٰ ۚ يُسَبِّحُ لَهُ مَا فِى السَّمَـٰوَٰتِ وَ الْاَرْضِ ۖ وَ هُوَ الْعَزِيزُ الْحَكِيمُ",
    "urdu_text": "وہی اللہ ہے جو پیدا کرنے والا، ایجاد کرنے والا، صورتیں بنانے والا ہے، اس کے لیے بہترین نام ہیں، آسمانوں اور زمین میں جو کچھ ہے اس کی تسبیح کرتا ہے، اور وہ غالب اور حکمت والا ہے",
    "persian_text": "او خداوندی است که آفریننده، بدیع‌آفرین و صورتگر است، نام‌های نیکو از آن اوست، آنچه در آسمان‌ها و زمین است او را تسبیح می‌گوید، و او عزیز حکیم است",
    "transliteration": "Huwa Allahu al-Khaliqu al-Bari'u al-Musawwir, lahu al-asma'u al-husna, yusabbihu lahu ma fi as-samawati wa al-ard, wa Huwa al-'Azizu al-Hakim",
  },
]
