ayats = [
    {
        "verse_number": "1",
        "arabic_text": "قَدْ سَمِعَ اللّٰهُ قَوْلَ الَّتِي تُجَادِلُكَ فِي زَوْجِهَا وَتَشْتَكِي اِلَى اللّٰهِ وَاللّٰهُ يَسْمَعُ تَحَاوُرَكُمَا ۚ اِنَّ اللّٰهَ سَمِيعٌ بَصِيرٌ",
        "urdu_text": "الله نے اس عورت کی بات سن لی جو تم سے اپنے شوهر کے بارے میں جھگڑ رهی تھی اور الله سے فریاد کر رهی تھی، اور الله تم دونوں کا مکالمه سن رها تھا۔ بے شک الله سب کچھ سننے والا، دیکھنے والا هے۔",
        "persian_text": "خدا سخن زنی را شنید که درباره شوهرش با تو گفتگو می‌کرد و به درگاه خدا شکایت می‌برد، و خدا گفتگوی شما را می‌شنید، بی‌گمان خدا شنوا و بیناست.",
        "english_text": "Allah has indeed heard the statement of the woman who pleads with you concerning her husband and complains to Allah. And Allah hears your conversation. Surely, Allah is All-Hearing, All-Seeing.",
        "transliteration": "Qad samiʿa allāhu qawla allatī tujādiluka fī zawjihā wa tashtakī ilā allāhi wallāhu yasmaʿu taḥāwurakumā inna allāha samīʿun baṣīr.",
    },
    {
        "verse_number": "2",
        "arabic_text": "الَّذِينَ يُظَٰهِرُونَ مِنكُم مِّن نِّسَآئِهِم مَّا هُنَّ اُمَّهَٰتِهِمْ ۖ اِنْ اُمَّهَٰتُهُمْ اِلَّا الَّٰـٓـِٔى وَلَدْنَهُمْ ۚ وَاِنَّهُمْ لَيَقُولُونَ مُنكَرًۭا مِّنَ الْقَوْلِ وَزُورًۭا ۚ وَاِنَّ اللّٰهَ لَعَفُوٌّ غَفُورٌۭ",
        "urdu_text": "جو لوگ اپنی بیویوں سے ظهار کرتے هیں وه ان کی مائیں نهیں بن جاتیں، ان کی مائیں تو وهی هیں جنهوں نے ان کو جنم دیا هے۔ بے شک وه نهایت ناپسندیده اور جھوٹی بات کهتے هیں، اور بے شک الله معاف کرنے والا، بخشنے والا هے۔",
        "persian_text": "کسانی که از شما نسبت به همسرانشان ظهار می‌کنند، آنان مادرانشان نمی‌شوند، مادرانشان فقط کسانی هستند که آنان را زاده‌اند. بی‌گمان آنان سخنی منکر و دروغ می‌گویند، و خداوند بخشنده و آمرزنده است.",
        "english_text": "Those among you who estrange their wives by saying they are like their mothers—they are not their mothers. Their mothers are only those who gave birth to them. Indeed, they utter an ill word and a lie. And surely, Allah is Pardoning and Forgiving.",
        "transliteration": "Allaḏīna yuẓāhirūna minkum min nisā’ihim mā hunna ummahātihim in ummahātuhum illā allā’ī waladnahum wa innahum layaqūlūna munkaran mina al-qawli wa zūran wa inna allāha la‘afuwwun ghafūr.",
    },
    {
        "verse_number": "3",
        "arabic_text": "وَالَّذِينَ يُظَٰهِرُونَ مِن نِّسَآئِهِمْ ثُمَّ يَعُودُونَ لِمَا قَالُواْ فَتَحْرِيرُ رَقَبَةٍۢ مِّن قَبْلِ اَن يَتَمَآسَّا ۚ ذَٰلِكُمْ تُوعَظُونَ بِهِ ۚ وَاللّٰهُ بِمَا تَعْمَلُونَ خَبِيرٌۭ",
        "urdu_text": "اور جو لوگ اپنی بیویوں سے ظهار کریں پھر اپنی بات سے رجوع کریں، تو انهیں ایک غلام آزاد کرنا هوگا اس سے پهلے که دونوں ایک دوسرے کو چھوئیں۔ تمهیں اس بات کی نصیحت کی جاتی هے، اور الله تمهارے اعمال سے خوب باخبر هے۔",
        "persian_text": "و کسانی که نسبت به همسرانشان ظهار کرده‌اند، سپس به آنچه گفته‌اند بازگردند، باید پیش از تماس، برده‌ای را آزاد کنند. این چیزی است که به آن پند داده می‌شوید و خداوند به آنچه انجام می‌دهید آگاه است.",
        "english_text": "And those who declare their wives as their mothers, then wish to go back on what they said, must free a slave before they touch one another. This is what you are advised, and Allah is All-Aware of what you do.",
        "transliteration": "Wa alladhīna yuẓāhirūna min nisā’ihim thumma yaʿūdūna limā qālū fa-taḥrīru raqabatin min qabli an yatamāssā dhālikum tūʿaẓūna bih wa allāhu bimā taʿmalūna khabīr.",
    },
    {
        "verse_number": "4",
        "arabic_text": "فَمَن لَّمْ يَجِدْ فَصِيَامُ شَهْرَيْنِ مُتَتَابِعَيْنِ مِن قَبْلِ اَن يَتَمَآسَّا ۖ فَمَن لَّمْ يَسْتَطِعْ فَاِطْعَامُ سِتِّينَ مِسْكِينًۭا ۚ ذَٰلِكَ لِتُؤْمِنُواْ بِاللّٰهِ وَرَسُولِهِ ۚ وَتِلْكَ حُدُودُ اللّٰهِ ۗ وَلِلْكَـٰفِرِينَ عَذَابٌ اَلِيمٌۭ",
        "urdu_text": "پھر جو غلام نه پائے، تو دو مهینے لگاتار روزے رکھے، اور اگر یه بھی نه کر سکے، تو ساٹھ مسکینوں کو کھانا کھلائے۔ یه اس لیے هے تاکه تم الله اور اس کے رسول پر ایمان لاؤ، اور یه الله کی حدیں هیں، اور کافروں کے لیے دردناک عذاب هے۔",
        "persian_text": "پس هر کس نیابد، باید دو ماه پی‌درپی روزه بگیرد، و اگر نتواند، شصت مسکین را غذا دهد. این برای آن است که به خدا و پیامبرش ایمان آورید. این‌ها حدود خداست، و برای کافران عذابی دردناک است.",
        "english_text": "But he who cannot afford it should fast for two consecutive months before they touch each other. And he who is unable to do so should feed sixty poor people. That is so you may believe in Allah and His Messenger. These are the limits set by Allah. And for disbelievers is a painful punishment.",
        "transliteration": "Fa-man lam yajid fa-ṣiyāmu shahrayn mutatābiʿayn min qabli an yatamāssā fa-man lam yastaṭiʿ fa-iṭʿāmu sittīna miskīnā dhālika li-tuʾminū bi-llāhi wa rasūlihi wa tilka ḥudūdu-llāh wa lil-kāfirīna ʿadhābun alīm.",
    },
    {
        "verse_number": "5",
        "arabic_text": "اِنَّ الَّذِينَ يُحَآدُّونَ اللّٰهَ وَرَسُولَهُ كُبِتُواْ كَمَا كُبِتَ الَّذِينَ مِن قَبْلِهِمْ ۚ وَ قَدْ اَنزَلْنَآ اٰيٰتٍۢ بَيِّنَـٰتٍۢ ۚ وَلِلْكَـٰفِرِينَ عَذَابٌۭ مُّهِينٌۭ",
        "urdu_text": "یقیناً جو لوگ الله اور اس کے رسول کی مخالفت کرتے هیں، وه اسی طرح ذلیل کیے گئے جیسے ان سے پهلے لوگ ذلیل کیے گئے تھے، اور هم نے واضح آیات نازل کی هیں، اور کافروں کے لیے ذلت کا عذاب هے۔",
        "persian_text": "بی‌گمان کسانی که با خدا و پیامبرش دشمنی می‌ورزند، همچون کسانی که پیش از آنان بودند، خوار شدند. ما آیات روشنی نازل کرده‌ایم، و برای کافران عذابی خوارکننده است.",
        "english_text": "Indeed, those who oppose Allah and His Messenger will be disgraced as those before them were disgraced. We have certainly sent down clear signs. And for the disbelievers is a humiliating punishment.",
        "transliteration": "Inna alladhīna yuḥāddūna allāha wa rasūlahu kubitū kamā kubita alladhīna min qablihim wa qad anzalnā āyātin bayyinātin wa lilkāfirīna ʿadhābun muhīn.",
    },
    {
        "verse_number": "6",
        "arabic_text": "يَوْمَ يَبْعَثُهُمُ اللّٰهُ جَمِيعًۭا فَيُنَبِّئُهُم بِمَا عَمِلُوٓاْ ۚ اَحْصَىٰهُ اللّٰهُ وَنَسُوهُ ۚ وَاللّٰهُ عَلَٰى كُلِّ شَىْءٍۢ شَهِيدٌ",
        "urdu_text": "جس دن الله ان سب کو اٹھائے گا، پھر انهیں ان کے اعمال سے آگاه کرے گا، الله نے ان سب کو شمار کر رکھا هے، حالانکه وه خود بھول چکے هیں، اور الله هر چیز پر گواه هے۔",
        "persian_text": "روزی که خداوند همه‌شان را برانگیزد و آنان را از آنچه کرده‌اند باخبر سازد. خدا همه را به حساب آورده، هرچند که خود فراموش کرده‌اند، و خدا بر هر چیزی گواه است.",
        "english_text": "On the Day Allah will resurrect them all, then inform them of what they did. Allah had recorded it all, while they forgot it. And Allah is Witness over all things.",
        "transliteration": "Yawma yabʿathuhumu allāhu jamīʿan fa-yunabbiʾuhum bimā ʿamilū aḥṣāhu allāhu wa nasūhu wa allāhu ʿalā kulli shayʾin shahīd.",
    },
    {
        "verse_number": "7",
        "arabic_text": "اَلَمْ تَرَ اَنَّ اللّٰهَ يَعْلَمُ مَا فِى السَّمَـٰوَٰتِ وَ مَا فِى الْاَرْضِ ۖ مَا يَكُونُ مِن نَّجْوَىٰ ثَلَـٰثَةٍ اِلَّا هُوَ رَابِعُهُمْ وَلَا خَمْسَةٍ اِلَّا هُوَ سَادِسُهُمْ وَلَا اَدْنَىٰ مِن ذَٰلِكَ وَلَآ اَكْثَرَ اِلَّا هُوَ مَعَهُمْ اَيْنَ مَا كَانُواْ ۖ ثُمَّ يُنَبِّئُهُم بِمَا عَمِلُواْ يَوْمَ الْقِيَـٰمَةِ ۚ اِنَّ اللّٰهَ بِكُلِّ شَىْءٍ عَلِيمٌۭ",
        "urdu_text": "کیا تم نے نهیں دیکھا که الله جانتا هے جو کچھ آسمانوں اور زمین میں هے؟ کوئی راز کی بات تین آدمیوں میں نهیں هوتی مگر وه چوتھا هوتا هے، اور نه پانچ میں مگر وه چھٹا هوتا هے، اور نه اس سے کم اور نه زیاده مگر وه ان کے ساتھ هوتا هے جهاں کهیں وه هوں، پھر قیامت کے دن وه انهیں بتائے گا جو کچھ انهوں نے کیا۔ بے شک الله هر چیز کو خوب جاننے والا هے۔",
        "persian_text": "آیا ندانستی که خداوند آنچه را در آسمان‌ها و زمین است، می‌داند؟ هیچ نجواکننده‌ای در میان سه نفر نیست مگر آن‌که او چهارمین آن‌هاست، و نه پنج نفر، مگر او ششمین‌شان است. و نه کمتر از آن و نه بیشتر، مگر او با آن‌هاست هر جا که باشند. سپس روز قیامت آنان را از آنچه کرده‌اند آگاه می‌سازد. بی‌گمان خداوند به هر چیزی داناست.",
        "english_text": "Have you not seen that Allah knows whatever is in the heavens and whatever is on the earth? Never is there any whispering among three but He is their fourth, nor among five but He is their sixth, nor fewer nor more, but He is with them wherever they may be. Then He will inform them of what they did on the Day of Judgment. Verily, Allah is Knowing of all things.",
        "transliteration": "Alam tara anna allāha yaʿlamu mā fī as-samāwāti wa mā fī al-arḍi mā yakūnu min najwā thalāthatin illā huwa rābiʿuhum wa lā khamsatin illā huwa sādisuhum wa lā adnà min dhālika wa lā akthara illā huwa maʿahum ayna mā kānū thumma yunabbiʾuhum bimā ʿamilū yawma al-qiyāmah inna allāha bikulli shayʾin ʿalīm.",
    },
    {
        "verse_number": "8",
        "arabic_text": "اَلَمْ تَرَ اِلَى الَّذِينَ نُهُواْ عَنِ النَّجْوَىٰ ثُمَّ يَعُودُونَ لِمَا نُهُواْ عَنْهُ وَيَتَنَـٰجَوْنَ بِالْاِثْمِ وَالْعُدْوَٰنِ وَمَعْصِيَتِ الرَّسُولِ ۖ وَاِذَا جَآءُوكَ حَيَّوْكَ بِمَا لَمْ يُحَيِّكَ بِهِ اللّٰهُ وَيَقُولُونَ فِىٓ اَنفُسِهِمْ لَوْلَا يُعَذِّبُنَا اللّٰهُ بِمَا نَقُولُ ۚ حَسْبُهُمْ جَهَنَّمُ ۚ يَصْلَوْنَهَا ۖ فَبِئْسَ الْمَصِيرُ",
        "urdu_text": "کیا تم نے ان لوگوں کو نهیں دیکھا جنهیں راز کی باتوں سے منع کیا گیا تھا، پھر وه وهی کرنے لگے جن سے روکے گئے تھے، اور گناه، زیادتی اور رسول کی نافرمانی کی باتیں کرتے هیں؟ اور جب تمهارے پاس آتے هیں تو تمهیں اس انداز میں سلام کرتے هیں جیسا الله نے نهیں سکھایا، اور اپنے دلوں میں کهتے هیں که الله همیں هماری باتوں پر سزا کیوں نهیں دیتا؟ ان کے لیے جهنم کافی هے، وه اسی میں جھونکے جائیں گے، اور وه بری جگه هے۔",
        "persian_text": "آیا ندیدی کسانی را که از نجوا نهی شدند، سپس به همانچه از آن نهی شده بودند بازمی‌گردند و در گناه و تجاوز و نافرمانی پیامبر به نجوا می‌پردازند؟ و هنگامی که نزد تو می‌آیند، تو را به گونه‌ای سلام می‌کنند که خدا سلام نکرده است، و در دل‌هایشان می‌گویند: چرا خدا ما را به آنچه می‌گوییم عذاب نمی‌دهد؟ جهنم برایشان بس است، در آن داخل خواهند شد، و چه بد سرانجامی است.",
        "english_text": "Have you not seen those who were forbidden from secret counsel, but they return to that which they were forbidden, and they conspire in sin and transgression and disobedience to the Messenger? And when they come to you, they greet you with words Allah has not greeted you with, and say within themselves: 'Why does Allah not punish us for what we say?' Hell will be sufficient for them—they will burn therein, and what an evil destination!",
        "transliteration": "Alam tara ilā alladhīna nuhū ʿani al-najwā thumma yaʿūdūna limā nuhū ʿanhu wa yatanājawna bil-ithmi wal-ʿudwāni wa maʿṣiyatir-rasūl wa idhā jāʾūka ḥayyawka bimā lam yuḥayyika bihillāh wa yaqūlūna fī anfusihim lawlā yuʿadhdhibunā allāhu bimā naqūl ḥasbuhum jahannamu yaṣlawnahā fabi’sa al-maṣīr.",
    },
    {
        "verse_number": "9",
        "arabic_text": "يَـٰٓاَيُّهَا الَّذِينَ ءَامَنُوٓاْ اِذَا تَنَـٰجَيْتُمْ فَلَا تَتَنَـٰجَوْاْ بِالْاِثْمِ وَالْعُدْوَٰنِ وَمَعْصِيَتِ الرَّسُولِ وَتَنَـٰجَوْاْ بِالْبِرِّ وَالتَّقْوَىٰ ۖ وَاتَّقُواْ اللّٰهَ الَّذِىٓ اِلَيْهِ تُحْشَرُونَ",
        "urdu_text": "اے ایمان والو! جب تم آپس میں سرگوشی کرو تو گناه، زیادتی اور رسول کی نافرمانی کی باتیں نه کرو بلکه نیکی اور پرهیزگاری کی باتیں کرو، اور الله سے ڈرو جس کی طرف تم جمع کیے جاؤ گے۔",
        "persian_text": "ای کسانی که ایمان آورده‌اید! هرگاه با هم نجوا می‌کنید، به گناه و دشمنی و نافرمانی پیامبر نجوا نکنید، بلکه به نیکی و پرهیزکاری نجوا کنید، و از خدایی پروا کنید که نزد او گرد آورده خواهید شد.",
        "english_text": "O you who believe! When you hold secret counsel, do not do so for sin and transgression and disobedience to the Messenger, but do so in righteousness and piety. And fear Allah, to whom you will be gathered.",
        "transliteration": "Yā ayyuhā alladhīna āmanū idhā tanājaytum fa-lā tatanājaw bil-ithmi wal-ʿudwān wa maʿṣiyati ar-rasūl wa tanājaw bil-birri wat-taqwā wa-ittaqullāha alladhī ilayhi tuḥsharūn.",
    },
    {
        "verse_number": "10",
        "arabic_text": "اِنَّمَا النَّجْوَىٰ مِنَ الشَّيْطَـٰنِ لِيَحْزُنَ الَّذِينَ ءَامَنُواْ وَلَيْسَ بِضَآرِّهِمْ شَيْـًٔا اِلَّا بِاِذْنِ اللّٰهِ ۚ وَعَلَى اللّٰهِ فَلْيَتَوَكَّلِ الْمُؤْمِنُونَ",
        "urdu_text": "یه سرگوشیاں تو شیطان کی طرف سے هوتی هیں تاکه وه ایمان والوں کو غمگین کرے، حالانکه وه الله کی اجازت کے بغیر انهیں کچھ نقصان نهیں پهنچا سکتا، اور مؤمنوں کو الله هی پر بھروسه کرنا چاهیے۔",
        "persian_text": "این نجوا فقط از سوی شیطان است تا مؤمنان را اندوهگین سازد، ولی او هرگز نمی‌تواند بدون اجازه خدا زیانی برساند، و مؤمنان باید تنها بر خدا توکل کنند.",
        "english_text": "Secret counsel is only from Satan, to grieve the believers. But he cannot harm them in the least without Allah’s permission. And in Allah let the believers put their trust.",
        "transliteration": "Innamā al-najwā mina ash-shayṭāni li-yaḥzuna alladhīna āmanū wa laysa bi-ḍārrihim shay’an illā bi-idhnillāh wa ʿala allāhi falyatawakkali al-mu’minūn.",
    },
    {
        "verse_number": "11",
        "arabic_text": "يَـٰٓاَيُّهَا الَّذِينَ ءَامَنُوٓاْ اِذَا قِيلَ لَكُمْ تَفَسَّحُواْ فِى الْمَجَـٰلِسِ فَافْسَحُواْ يَفْسَحِ اللّٰهُ لَكُمْ ۖ وَاِذَا قِيلَ انشُزُواْ فَانشُزُواْ يَرْفَعِ اللّٰهُ الَّذِينَ ءَامَنُواْ مِنكُمْ وَالَّذِينَ اُوتُواْ الْعِلْمَ دَرَجَـٰتٍۢ ۚ وَاللّٰهُ بِمَا تَعْمَلُونَ خَبِيرٌۭ",
        "urdu_text": "اے ایمان والو! جب تم سے کها جائے که مجلسوں میں کشادگی کرو، تو کشادگی کر دو، الله تمهیں کشادگی دے گا۔ اور جب کها جائے: اٹھ کھڑے هو، تو اٹھ کھڑے هو۔ الله تم میں سے ان لوگوں کے درجے بلند کرے گا جو ایمان لائے اور جنهیں علم دیا گیا۔ اور الله تمهارے اعمال سے باخبر هے۔",
        "persian_text": "ای کسانی که ایمان آورده‌اید! چون به شما گفته شود در مجلس جا باز کنید، جا باز کنید تا خدا نیز برای شما جا باز کند. و چون گفته شود برخیزید، برخیزید. خدا کسانی از شما را که ایمان آورده‌اند و دانش یافته‌اند، به درجاتی بالا می‌برد. و خدا به آنچه انجام می‌دهید، آگاه است.",
        "english_text": "O you who have believed, when you are told to make room in assemblies, then make room; Allah will make room for you. And when you are told, 'Arise,' then arise; Allah will raise those who have believed among you and those who were given knowledge, by degrees. And Allah is Aware of what you do.",
        "transliteration": "Yā ayyuhā alladhīna āmanū idhā qīla lakum tafassaḥū fī al-majālisi fa-afsaḥū yafsaḥi allāhu lakum wa idhā qīla unshuzū fa-unshuzū yarfaʿi allāhu alladhīna āmanū minkum wa alladhīna ūtu al-ʿilma darajāt wa allāhu bimā taʿmalūna khabīr.",
    },
    {
        "verse_number": "12",
        "arabic_text": "يَـٰٓاَيُّهَا الَّذِينَ ءَامَنُوٓاْ اِذَا نَـٰجَيْتُمُ الرَّسُولَ فَقَدِّمُواْ بَيْنَ يَدَىْ نَجْوَىٰكُمْ صَدَقَةًۭ ۚ ذَٰلِكَ خَيْرٌۭ لَّكُمْ وَاَطْهَرُ ۚ فَاِن لَّمْ تَجِدُواْ فَاِنَّ اللّٰهَ غَفُورٌۭ رَّحِيمٌ",
        "urdu_text": "اے ایمان والو! جب تم رسول سے تنهائی میں بات کرو، تو بات کرنے سے پهلے صدقه دیا کرو، یه تمهارے لیے بهتر اور زیاده پاکیزه هے۔ پھر اگر تمهیں وسعت نه هو تو بے شک الله بخشنے والا، رحم کرنے والا هے۔",
        "persian_text": "ای کسانی که ایمان آورده‌اید! چون با پیامبر نجوا کردید، پیش از نجوا صدقه‌ای دهید. این برای شما بهتر و پاکیزه‌تر است. و اگر نیافتید، بی‌گمان خدا آمرزنده و مهربان است.",
        "english_text": "O you who have believed, when you consult the Messenger in private, present before your consultation a charity. That is better for you and purer. But if you find not [the means] – then indeed, Allah is Forgiving and Merciful.",
        "transliteration": "Yā ayyuhā alladhīna āmanū idhā nājaytum ar-rasūla fa-qaddimū bayna yaday najwākum ṣadaqah dhālika khayrun lakum wa aṭhar fa-in lam tajidū fa-inna allāha ghafūrun raḥīm.",
    },
    {
        "verse_number": "13",
        "arabic_text": "ءَاَشْفَقْتُمْ اَن تُقَدِّمُواْ بَيْنَ يَدَىْ نَجْوَىٰكُمْ صَدَقَـٰتٍۢ ۚ فَاِذْ لَمْ تَفْعَلُواْ وَتَابَ اللّٰهُ عَلَيْكُمْ فَاَقِيمُواْ الصَّلَوٰةَ وَءَاتُواْ الزَّكَوٰةَ وَاَطِيعُواْ اللّٰهَ وَرَسُولَهُ ۚ وَاللّٰهُ خَبِيرٌۢ بِمَا تَعْمَلُونَ",
        "urdu_text": "کیا تم اس سے ڈر گئے که اپنی نجویٰ سے پهلے صدقات دو؟ اب جبکه تم نے ایسا نه کیا اور الله نے تم پر مهربانی فرمائی، تو نماز قائم کرو، زکوٰۃ دو اور الله اور اس کے رسول کی اطاعت کرو، اور الله تمهارے اعمال سے باخبر هے۔",
        "persian_text": "آیا از این که پیش از نجوا صدقه دهید، بیم داشتید؟ پس چون چنین نکردید و خدا بر شما بخشایش آورد، نماز برپا دارید، زکات دهید، و از خدا و پیامبرش فرمان برید، و خدا به آنچه انجام می‌دهید، آگاه است.",
        "english_text": "Do you fear that you will not [be able to] give charity before your consultation? Then when you do not and Allah has forgiven you, then establish prayer and give zakah and obey Allah and His Messenger. And Allah is Aware of what you do.",
        "transliteration": "A'ashfaqtum an tuqaddimū bayna yaday najwākum ṣadaqāt fa-idh lam tafʿalū wa tāba allāhu ʿalaykum fa-aqīmū aṣ-ṣalāta wa ātū az-zakāta wa aṭīʿū allāha wa rasūlahu wa allāhu khabīrun bimā taʿmalūn.",
    },
    {
        "verse_number": "14",
        "arabic_text": "اَلَمْ تَرَ اِلَى الَّذِينَ تَوَلَّوْاْ قَوْمًۭا غَضِبَ اللّٰهُ عَلَيْهِم مَّا هُم مِّنكُمْ وَلَا مِنْهُمْ وَيَحْلِفُونَ عَلَى الْكَذِبِ وَهُمْ يَعْلَمُونَ",
        "urdu_text": "کیا تم نے انهیں نهیں دیکھا جو ان لوگوں سے دوستی کرتے هیں جن پر الله نے غضب نازل کیا؟ وه نه تم میں سے هیں اور نه ان میں سے، اور وه جان بوجھ کر جھوٹی قسمیں کھاتے هیں۔",
        "persian_text": "آیا ندیدی کسانی را که با گروهی دوستی می‌گیرند که خدا بر آنان خشم گرفته است؟ آنان نه از شما هستند و نه از ایشان. و به دروغ سوگند می‌خورند، در حالی که خود می‌دانند.",
        "english_text": "Have you not seen those who make allies of a people with whom Allah is angry? They are neither of you nor of them, and they swear to falsehood while they know.",
        "transliteration": "Alam tara ilā alladhīna tawallaw qawman ghaḍiba allāhu ʿalayhim mā hum minkum wa lā minhum wa yaḥlifūna ʿala al-kadhibi wa hum yaʿlamūn.",
    },
    {
        "verse_number": "15",
        "arabic_text": "اَعَدَّ اللّٰهُ لَهُمْ عَذَابًۭا شَدِيدًا ۖ اِنَّهُمْ سَآءَ مَا كَانُواْ يَعْمَلُونَ",
        "urdu_text": "الله نے ان کے لیے سخت عذاب تیار کر رکھا هے۔ بے شک وه بهت برا کام کرتے رهے هیں۔",
        "persian_text": "خدا برایشان عذابی سخت آماده کرده است، چرا که کردارشان بسیار بد بوده است.",
        "english_text": "Allah has prepared for them a severe punishment. Evil indeed is that which they used to do.",
        "transliteration": "Aʿadda allāhu lahum ʿadhāban shadīdan innahum sāʾa mā kānū yaʿmalūn.",
    },
    {
        "verse_number": "16",
        "arabic_text": "اتَّخَذُوٓاْ اَيْمَـٰنَهُمْ جُنَّةًۭ فَصَدُّواْ عَن سَبِيلِ اللّٰهِ فَلَهُمْ عَذَابٌۭ مُّهِينٌۭ",
        "urdu_text": "انهوں نے اپنی قسموں کو ڈھال بنا لیا هے اور الله کے راستے سے روکتے هیں، تو ان کے لیے رسوا کن عذاب هے۔",
        "persian_text": "آنها سوگندهای خود را سپری قرار داده‌اند و [مردم را] از راه خدا باز می‌دارند؛ پس برایشان عذابی خوارکننده است.",
        "english_text": "They have taken their oaths as a cover, so they averted [people] from the way of Allah, and for them is a humiliating punishment.",
        "transliteration": "Ittakhadhū aymānahum junnatan faṣaddū ʿan sabīli allāhi falahum ʿadhābun muhīn.",
    },
    {
        "verse_number": "17",
        "arabic_text": "لَّن تُغْنِىَ عَنْهُمْ اَمْوَٰلُهُمْ وَلَآ اَوْلَـٰدُهُم مِّنَ اللّٰهِ شَيْـًۭٔا ۚ اُو۟لَـٰٓئِكَ اَصْحَـٰبُ النَّارِ ۖ هُمْ فِيهَا خَـٰلِدُونَ",
        "urdu_text": "نه ان کے مال اور نه ان کی اولاد الله کے مقابلے میں ان کے کچھ کام آئے گی۔ یهی لوگ دوزخ والے هیں، وه اس میں همیشه رهیں گے۔",
        "persian_text": "اموال و فرزندانشان هرگز آنان را در برابر خدا بی‌نیاز نمی‌سازد. آنان اهل آتشند و در آن جاودانند.",
        "english_text": "Their wealth and their children will not avail them against Allah at all. Those are the companions of the Fire; they will abide therein eternally.",
        "transliteration": "Lan tugh'nī ʿanhum amwāluhum wa lā awlāduhum mina allāhi shayʾā, ulāʾika aṣḥābu an-nāri hum fīhā khālidūn.",
    },
    {
        "verse_number": "18",
        "arabic_text": "يَوْمَ يَبْعَثُهُمُ اللّٰهُ جَمِيعًۭا فَيَحْلِفُونَ لَهُ كَمَا يَحْلِفُونَ لَكُمْ وَيَحْسَبُونَ اَنَّهُمْ عَلَٰى شَىْءٍ ۚ اَلَآ اِنَّهُمْ هُمُ الْكَـٰذِبُونَ",
        "urdu_text": "جس دن الله ان سب کو اٹھائے گا، تو وه اس کے سامنے بھی قسمیں کھائیں گے جیسے تمهارے سامنے کھاتے هیں، اور گمان کریں گے که وه کسی بنیاد پر هیں۔ خبردار! وه یقیناً جھوٹے هیں۔",
        "persian_text": "روزی که خدا همه آنان را برمی‌انگیزد، برای او نیز همان‌گونه که برای شما سوگند می‌خورند، سوگند خواهند خورد، و می‌پندارند که بر چیزی (محکم) تکیه دارند. آگاه باشید که آنان دروغگویانند.",
        "english_text": "On the Day Allah will resurrect them all, and they will swear to Him as they swear to you, thinking that they are [standing] on something. Unquestionably, it is they who are the liars.",
        "transliteration": "Yawma yabʿathuhumu allāhu jamīʿan fa-yaḥlifūna lahu kamā yaḥlifūna lakum wa yaḥsabūna annahum ʿalā shayʾ, alā innahum humu al-kādhibūn.",
    },
    {
        "verse_number": "19",
        "arabic_text": "اسْتَحْوَذَ عَلَيْهِمُ الشَّيْطَـٰنُ فَاَنسَىٰهُمْ ذِكْرَ اللّٰهِ ۚ اُو۟لَـٰٓئِكَ حِزْبُ الشَّيْطَـٰنِ ۚ اَلَآ اِنَّ حِزْبَ الشَّيْطَـٰنِ هُمُ الْخَـٰسِرُونَ",
        "urdu_text": "شیطان نے ان پر قابو پا لیا، پس انهیں الله کا ذکر بھلا دیا۔ یهی لوگ شیطان کا گروه هیں۔ خبردار! شیطان کا گروه هی خساره پانے والا هے۔",
        "persian_text": "شیطان بر آنان چیره شد و یاد خدا را از خاطرشان برد. آنان حزب شیطانند. آگاه باشید، حزب شیطان زیانکارانند.",
        "english_text": "Satan has overcome them and made them forget the remembrance of Allah. Those are the party of Satan. Unquestionably, the party of Satan – they will be the losers.",
        "transliteration": "Istahwadha ʿalayhimu ash-shayṭānu fa-ansāhum dhikra allāh, ulāʾika ḥizbu ash-shayṭān, alā inna ḥizba ash-shayṭāni humu al-khāsirūn.",
    },
    {
        "verse_number": "20",
        "arabic_text": "اِنَّ الَّذِينَ يُحَآدُّونَ اللّٰهَ وَرَسُولَهُٓ اُو۟لَـٰٓئِكَ فِى الْاَذَلِّينَ",
        "urdu_text": "بے شک جو لوگ الله اور اس کے رسول کی مخالفت کرتے هیں، وهی سب سے زیاده ذلیلوں میں سے هوں گے۔",
        "persian_text": "بی‌گمان کسانی که با خدا و پیامبرش دشمنی می‌ورزند، در زمره‌ی خوارترین‌ها خواهند بود.",
        "english_text": "Indeed, those who oppose Allah and His Messenger – they will be among the most humiliated.",
        "transliteration": "Inna alladhīna yuḥāddūna allāha wa rasūlahu ulāʾika fī al-adhallīn.",
    },
    {
        "verse_number": "21",
        "arabic_text": "كَتَبَ اللّٰهُ لَاَغْلِبَنَّ اَنَا۠ وَرُسُلِىٓ ۚ اِنَّ اللّٰهَ قَوِىٌّ عَزِيزٌۭ",
        "urdu_text": "الله نے لکھ دیا هے که میں اور میرے رسول هی غالب آ کر رهیں گے۔ بے شک الله زبردست اور غالب هے۔",
        "persian_text": "خدا مقرر کرده است که من و پیامبرانم پیروز خواهیم بود. بی‌گمان خدا نیرومند و شکست‌ناپذیر است.",
        "english_text": "Allah has decreed: 'Verily, I and My messengers will be the victorious.' Verily, Allah is All-Powerful, Almighty.",
        "transliteration": "Kataba allāhu la-aghlibanna anā wa rusulī, inna allāha qawiyyun ʿazīz.",
    },
    {
        "verse_number": "22",
        "arabic_text": "لَا تَجِدُ قَوْمًا يُؤْمِنُونَ بِاللّٰهِ وَالْيَوْمِ الْآخِرِ يُوَادُّونَ مَنْ حَادَّ اللّٰهَ وَرَسُولَهُ وَ لَوْ كَانُوا آبَاءَهُمْ اَوْ اَبْنَاءَهُمْ اَوْ اِخْوَانَهُمْ اَوْ عَشِيرَتَهُمْ ۚ اُولَٰئِكَ كَتَبَ فِي قُلُوبِهِمُ الْاِيمَانَ وَاَيَّدَهُم بِرُوحٍ مِّنْهُ ۖ وَيُدْخِلُهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْاَنْهَارُ خٰلِدِينَ فِيهَا ۚ رَضِيَ اللّٰهُ عَنْهُمْ وَرَضُوا عَنْهُ ۚ اُولَٰئِكَ حِزْبُ اللّٰهِ ۚ اَلَا اِنَّ حِزْبَ اللّٰهِ هُمُ الْمُفْلِحُونَ",
        "urdu_text": "تم هرگز اُن لوگوں کو نهیں پاؤ گے جو الله اور روزِ آخرت پر ایمان رکھتے هیں، که وه اُن لوگوں سے محبت کریں جو الله اور اُس کے رسول کے مخالف هیں، خواه وه اُن کے باپ هوں، یا بیٹے، یا بھائی، یا خاندان والے۔ یهی لوگ هیں جن کے دلوں میں الله نے ایمان ثبت کر دیا هے اور اپنی طرف سے ایک روح (یعنی قوتِ ایمانی) سے ان کی مدد فرمائی هے۔ اور انهیں ایسی جنتوں میں داخل کرے گا جن کے نیچے نهریں بهتی هیں، وه همیشه ان میں رهیں گے۔ الله ان سے راضی هوا اور وه الله سے راضی هوئے۔ یهی لوگ الله کی جماعت هیں۔ سن لو! بے شک الله کی جماعت هی کامیاب هونے والی هے۔",
        "english_text": "You will not find a people who believe in Allah and the Last Day loving those who oppose Allah and His Messenger, even if they were their fathers, or their sons, or their brothers, or their kindred. Those—He has inscribed faith upon their hearts and supported them with a spirit from Himself. And He will admit them to gardens beneath which rivers flow, wherein they will abide forever. Allah is pleased with them, and they are pleased with Him. They are the party of Allah. Indeed, the party of Allah—they are the successful.",
        "transliteration": "Lā tajidu qawman yu’minūna billāhi wal-yawmil-ākhiri yuwāddūna man ḥādda Allāha wa rasūlahu walaw kānū ābā’ahum aw abnā’ahum aw ikh’wānahum aw ‘ashīratahum; ulā’ika kataba fī qulūbihimu al-īmāna wa ayyadahum bi rūḥin minhu wa yud’khiluhum jannātin tajrī min taḥtihā al-anhāru khālidīna fīhā; raḍiya Allāhu ‘anhum wa raḍū ‘anhu; ulā’ika ḥizbu Allāh; alā inna ḥizba Allāhi humul-muf’liḥūn.",
        "persian_text": "هرگز مردمی را که به خدا و روز واپسین ایمان دارند نمی‌یابی که با کسانی که با خدا و فرستاده‌اش دشمنی می‌کنند، دوستی ورزند، هرچند پدرانشان یا پسرانشان یا برادرانشان یا خاندانشان باشند. آنان کسانی‌اند که خدا ایمان را در دل‌هایشان نگاشته و آنان را با روحی از جانب خویش نیرومند ساخته است. و ایشان را به بهشت‌هایی درآورد که نهرها از زیر آن روان است؛ جاودانه در آن خواهند ماند. خدا از آنان خشنود است و آنان نیز از او خشنودند. اینان حزب خدا هستند، آگاه باشید که حزب خدا همان رستگارانند.",
    },
]
