ayats = [
    
    [
        {
            "arabic_text": "الرَّحْمَٰنُ",
            "urdu_text": "نہایت رحم والا",
            "persian_text": "بسیار مهربان",
            "english_text": "The Most Merciful",
            "transliteration": "Ar-Rahman",
            "verse_number": "55:1",
        },
        {
            "arabic_text": "عَلَّمَ الْقُرْآنَ",
            "urdu_text": "جس نے قرآن سکھایا",
            "persian_text": "قرآن را آموخت",
            "english_text": "Taught the Qur'an",
            "transliteration": "Allama al-Qur'an",
            "verse_number": "55:2",
        },
        {
            "arabic_text": "خَلَقَ الْاِنسَانَ",
            "urdu_text": "انسان کو پیدا کیا",
            "persian_text": "انسان را آفرید",
            "english_text": "Created man",
            "transliteration": "Khalaqa al-insan",
            "verse_number": "55:3",
        },
        {
            "arabic_text": "عَلَّمَهُ الْبَيَانَ",
            "urdu_text": "اسے بولنا سکھایا",
            "persian_text": "به او بیان آموخت",
            "english_text": "Taught him speech",
            "transliteration": "Allamahu al-bayan",
            "verse_number": "55:4",
        },
        {
            "arabic_text": "الشَّمْسُ وَالْقَمَرُ بِحُسْبَانٍ",
            "urdu_text": "سورج اور چاند ایک حساب سے چل رہے ہیں",
            "persian_text": "خورشید و ماه با حسابی دقیق",
            "english_text": "The sun and the moon [move] by precise calculation",
            "transliteration": "Ash-shamsu wal-qamaru bihusbaan",
            "verse_number": "55:5",
        },
        {
            "arabic_text": "وَالنَّجْمُ وَالشَّجَرُ يَسْجُدَانِ",
            "urdu_text": "اور درخت اور گھاس سجدہ کرتے ہیں",
            "persian_text": "ستارگان و درختان سجده می‌کنند",
            "english_text": "And the stars and trees prostrate",
            "transliteration": "Wa an-najmu wash-shajaru yasjudaan",
            "verse_number": "55:6",
        },
        {
            "arabic_text": "وَالسَّمَاءَ رَفَعَهَا وَوَضَعَ الْمِيزَانَ",
            "urdu_text": "اور آسمان کو بلند کیا اور ترازو رکھا",
            "persian_text": "آسمان را برافراشت و میزان را نهاد",
            "english_text": "And the heaven He raised and imposed the balance",
            "transliteration": "Was-samaa’a rafa’aha wa wada’a al-meezaan",
            "verse_number": "55:7",
        },
        {
            "arabic_text": "اَلَّا تَطْغَوْا فِى الْمِيزَانِ",
            "urdu_text": "تاکہ تم تولنے میں زیادتی نہ کرو",
            "persian_text": "تا در میزان زیاده‌روی نکنید",
            "english_text": "That you not transgress within the balance",
            "transliteration": "Alla tatghaw fil meezaan",
            "verse_number": "55:8",
        },
        {
            "arabic_text": "وَاَقِيمُوا الْوَزْنَ بِالْقِسْطِ وَلَا تُخْسِرُوا الْمِيزَانَ",
            "urdu_text": "اور انصاف کے ساتھ تول کو قائم رکھو، اور ترازو میں کمی نہ کرو",
            "persian_text": "وزن را با عدالت برپا دارید و در میزان کم نگذارید",
            "english_text": "And establish weight in justice and do not make deficient the balance",
            "transliteration": "Wa aqeemul wazna bilqist wa laa tukhsirul meezaan",
            "verse_number": "55:9",
        },
        {
            "verse_number": 10,
            "arabic_text": "وَالْاَرْضَ وَضَعَهَا لِلْاَنَامِ",
            "urdu_text": "اور زمین کو اس نے مخلوق کے لیے بنایا",
            "persian_translation": "و زمین را برای آفریدگان گسترد",
            "english_translation": "And the earth He laid [out] for the creatures.",
            "transliteration": "Wal-arda wada'aha lil-anam",
        },
        {
            "verse_number": 11,
            "arabic_text": "فِيهَا فٰكِهَةٞ وَالنَّخۡلُ ذَاتُ الْاَكْمَامِ",
            "urdu_text": "اس میں میوے ہیں اور کھجور کے درخت ہیں جن کے خوشے غلافوں میں ہیں",
            "persian_translation": "در آن میوه‌ها و درخت خرما با خوشه‌های پیچیده وجود دارد",
            "english_translation": "Therein is fruit and palm trees having sheaths [of dates].",
            "transliteration": "Fīhā fākihatun wannakhlu dhātu al-akmām",
        },
        {
            "verse_number": 12,
            "arabic_text": "وَالْحَبُّ ذُو الْعَصۡفِ وَالرَّيْحَانُ",
            "urdu_text": "اور غلہ جس میں بھوسا ہوتا ہے اور خوشبودار پودے ہیں",
            "persian_translation": "و دانه‌هایی با کاه و گیاهان خوشبو",
            "english_translation": "And grain having husks and scented plants.",
            "transliteration": "Wal-ḥabbu dhū al-‘asfi war-rayḥān",
        },
        {
            "verse_number": 13,
            "arabic_text": "فَبِاَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_translation": "پس کدامین نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_translation": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi-ayyi ālā’i rabbikumā tukadhdhibān",
        },
        {
            "verse_number": 14,
            "arabic_text": "خَلَقَ الْاِنسٰنَ مِن صَلْصَٰلٖ كَالْفَخَّارِ",
            "urdu_text": "اس نے انسان کو ٹھیکری جیسے کھنکھناتے گارے سے پیدا کیا",
            "persian_translation": "او انسان را از گِلی خشک و چون سفال آفرید",
            "english_translation": "He created man from clay like [that of] pottery.",
            "transliteration": "Khalaqal-insāna min ṣalṣālin ka-al-fakhkhār",
        },
        {
            "verse_number": 15,
            "arabic_text": "وَخَلَقَ الْجَانَّ مِن مَّارِجٖ مِّن نَّارٖ",
            "urdu_text": "اور جنوں کو آگ کی لپٹ سے پیدا کیا",
            "persian_translation": "و جن را از شعله‌ای از آتش آفرید",
            "english_translation": "And He created the jinn from a smokeless flame of fire.",
            "transliteration": "Wakhalaqal-jānn min mārijim min nār",
        },
        {
            "verse_number": 16,
            "arabic_text": "فَبِاَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_translation": "پس کدامین نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_translation": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi-ayyi ālā’i rabbikumā tukadhdhibān",
        },
        {
            "verse_number": 17,
            "arabic_text": "رَبُّ الْمَشْرِقَيْنِ وَرَبُّ الْمَغْرِبَيْنِ",
            "urdu_text": "وہ دونوں مشرقوں اور دونوں مغربوں کا رب ہے",
            "persian_translation": "پروردگار دو مشرق و دو مغرب است",
            "english_translation": "He is Lord of the two Easts and Lord of the two Wests.",
            "transliteration": "Rabbu al-mashriqayni wa rabbu al-maghribayn",
        },
        {
            "verse_number": 18,
            "arabic_text": "فَبِاَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_translation": "پس کدامین نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_translation": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi-ayyi ālā’i rabbikumā tukadhdhibān",
        },
        {
            "verse_number": 19,
            "arabic_text": "مَرَجَ الْبَحْرَيْنِ يَلْتَقِيَانِ",
            "urdu_text": "اس نے دو سمندروں کو ملا دیا جو باہم ملتے ہیں",
            "persian_translation": "او دو دریا را روان ساخت که به هم می‌پیوندند",
            "english_translation": "He released the two seas, meeting [side by side].",
            "transliteration": "Maraja al-baḥrayni yaltaqiyān",
        },
        {
            "verse_number": 20,
            "arabic_text": "بَيْنَهُمَا بَرْزَخٞ لَّا يَبْغِيَانِ",
            "urdu_text": "ان کے درمیان ایک آڑ ہے، جو حد سے نہیں بڑھتے",
            "persian_translation": "میان آن دو مانعی است که از مرز نمی‌گذرند",
            "english_translation": "Between them is a barrier [so] neither of them transgresses.",
            "transliteration": "Baynahumā barzakhun lā yabghiyān",
        },
        {
            "arabic_text": "يَخْرُجُ مِنْهُمَا اللُّؤْلُؤُ وَالْمَرْجَانُ",
            "urdu_text": "ان دونوں سے موتی اور مونگے نکلتے ہیں",
            "persian_text": "از آن دو، مروارید و مرجان بیرون می‌آید",
            "english_text": "From both of them emerge pearls and coral.",
            "transliteration": "Yakhruju minhumā al-lu’lu’u wal-marjān",
            "verse_number": 22,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدامیک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 23,
        },
        {
            "arabic_text": "وَلَهُ الْجَوَارِ الْمُنشَـَٔاتُ فِى الْبَحْرِ كَالْاَعْلَـٰمِ",
            "urdu_text": "اور اسی کے لیے ہیں وہ کشتیاں جو سمندر میں پہاڑوں کی طرح بلند ہوتی ہیں",
            "persian_text": "و کشتی‌های بزرگ در دریا چون کوه‌ها به فرمان او روان‌اند",
            "english_text": "And His are the ships elevated in the sea like mountains.",
            "transliteration": "Wa lahu al-jawāri al-munsha’ātu fī al-baḥri kal-aʿlām",
            "verse_number": 24,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدامیک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 25,
        },
        {
            "arabic_text": "كُلُّ مَنْ عَلَيْهَا فَانٍۢ",
            "urdu_text": "زمین پر جو بھی ہے فنا ہو جانے والا ہے",
            "persian_text": "هر که بر روی آن است فانی است",
            "english_text": "Everyone upon it [the earth] will perish.",
            "transliteration": "Kullu man ʿalayhā fān",
            "verse_number": 26,
        },
        {
            "arabic_text": "وَيَبْقٰى وَجْهُ رَبِّكَ ذُو الْجَلَـٰلِ وَالْاِكْرَامِ",
            "urdu_text": "اور تمہارے رب کی ذات جو عظمت اور عزت والی ہے باقی رہے گی",
            "persian_text": "و تنها ذات پروردگارت که صاحب جلال و بزرگی است باقی می‌ماند",
            "english_text": "And the Face of your Lord full of Majesty and Honor will remain.",
            "transliteration": "Wa yabqā wajhu rabbika dhū al-jalāli wal-ikrām",
            "verse_number": 27,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 28,
        },
        {
            "arabic_text": "يَسْـَٔلُهُ مَن فِى السَّمٰوٰتِ وَالْاَرْضِ ۚ كُلَّ يَوْمٍ هُوَ فِى شَاْنٍۭ",
            "urdu_text": "اسی سے سوال کرتے ہیں وہ سب جو آسمانوں اور زمین میں ہیں، ہر روز وہ ایک شان میں ہوتا ہے",
            "persian_text": "هر که در آسمان‌ها و زمین است از او درخواست می‌کند؛ هر روز او در کاری است",
            "english_text": "Everyone in the heavens and earth asks Him; every day He is bringing about a matter.",
            "transliteration": "Yas’aluhu man fī as-samāwāti wal-arḍi, kulla yawmin huwa fī sha’n",
            "verse_number": 29,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 30,
        },
        {
            "arabic_text": "سَنَفْرُغُ لَكُمْ اَيُّهَ الثَّقَلَانِ",
            "urdu_text": "اے بوجھ والو! ہم تمہارے حساب کے لیے فارغ ہو جائیں گے",
            "persian_text": "ای گروه جن و انس، به زودی به حساب شما خواهیم پرداخت",
            "english_text": "We will attend to you, O prominent beings.",
            "transliteration": "Sanafrughu lakum ayyuhā ath-thaqalān",
            "verse_number": 31,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 32,
        },
        {
            "arabic_text": "يٰمَعْشَرَ الْجِنِّ وَالْاِنسِ اِنِ اسْتَطَعْتُمْ اَن تَنفُذُواْ مِنْ اَقْطَارِ السَّمٰوٰتِ وَالْاَرْضِ فَانفُذُواْ ۚ لَا تَنفُذُونَ اِلَّا بِسُلْطَـٰنٍۢ",
            "urdu_text": "اے جنوں اور انسانوں کی جماعت! اگر تم آسمانوں اور زمین کے کناروں سے نکل سکتے ہو تو نکل جاؤ، تم طاقت کے بغیر نہیں نکل سکتے",
            "persian_text": "ای گروه جن و انس! اگر می‌توانید از مرزهای آسمان‌ها و زمین بگریزید، بگریزید، اما جز با قدرت، نمی‌گریزید",
            "english_text": "O company of jinn and mankind, if you are able to pass beyond the regions of the heavens and the earth, then pass. You will not pass except by authority.",
            "transliteration": "Yā maʿshara al-jinni wal-insi inis-taṭaʿtum an tanfudhū min aqṭāri as-samāwāti wal-arḍi fanfudhū, lā tanfudhūna illā bisulṭān",
            "verse_number": 33,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 34,
        },
        {
            "arabic_text": "يُرْسَلُ عَلَيْكُمَا شُوَاظٌۭ مِّن نَّارٍۢ وَنُحَاسٌۭ فَلَا تَنتَصِرَانِ",
            "urdu_text": "تم پر آگ کا شعلہ اور دھواں چھوڑا جائے گا، پھر تم بچ نہ سکو گے",
            "persian_text": "بر شما شعله‌ای از آتش و دود مسلط خواهد شد و نمی‌توانید یاری بجویید",
            "english_text": "There will be sent upon you a flame of fire and smoke, and you will not defend yourselves.",
            "transliteration": "Yursalu ʿalaykumā shuwāẓun min nārin wa nuḥāsun falā tantaṣirān",
            "verse_number": 35,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 36,
        },
        {
            "arabic_text": "فَاِذَا انشَقَّتِ السَّمَآءُ فَكَانَتْ وَرْدَةًۭ كَالدِّهَانِ",
            "urdu_text": "پھر جب آسمان پھٹ جائے گا تو وہ گلابی ہو جائے گا جیسے تیل کی تلچھٹ",
            "persian_text": "پس آنگاه که آسمان شکافته شود و چون گل سرخ و روغن گداخته گردد",
            "english_text": "And when the heaven is split open and becomes rose-colored like oil.",
            "transliteration": "Fa idhā inshaqqati as-samā’u fakānat wardatan kaddihān",
            "verse_number": 37,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 38,
        },
        {
            "arabic_text": "فَيَوْمَئِذٍۢ لَّا يُسْـَٔلُ عَن ذَنبِهِٓ اِنسٌۭ وَلَا جَآنٌّۭ",
            "urdu_text": "پھر اس دن نہ انسان سے اور نہ جن سے ان کے گناہوں کے بارے میں سوال کیا جائے گا",
            "persian_text": "پس در آن روز از گناه هیچ انسانی و هیچ جنی پرسش نخواهد شد",
            "english_text": "Then on that Day none will be asked about his sin among men or jinn.",
            "transliteration": "Fayawma’idhilā yus’alu ʿan dhanbihi insun wa lā jān",
            "verse_number": 39,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے",
            "persian_text": "پس کدام یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "So which of the favors of your Lord would you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 40,
        },
        {
            "arabic_text": "يُعْرَفُ الْمُجْرِمُونَ بِسِيمَـٰهُمْ فَيُؤْخَذُ بِالنَّوَاصِى وَالْاَقْدَامِ",
            "urdu_text": "مجرم اپنے چہروں سے پہچانے جائیں گے، پھر پیشانیوں اور پاؤں سے پکڑا جائے گا",
            "persian_text": "گناهکاران از چهره‌شان شناخته می‌شوند و از پیشانی و پاها گرفته می‌شوند",
            "english_text": "The sinners will be known by their marks, and they will be seized by the forelocks and the feet.",
            "transliteration": "Yuʿrafu al-mujrimūna bisīmāhum fa yu’khadhu bin-nawāṣī wal-aqdām",
            "verse_number": 41,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 42,
        },
        {
            "arabic_text": "هَـٰذِهِ جَهَنَّمُ الَّتِى يُكَذِّبُ بِهَا الْمُجْرِمُونَ",
            "urdu_text": "یہی ہے جہنم جسے مجرم جھٹلایا کرتے تھے",
            "persian_text": "این همان جهنمی است که گناهکاران آن را تکذیب می‌کردند",
            "english_text": "This is the Hell which the criminals denied.",
            "transliteration": "Hādhihi jahannamu allatī yukadhdhibu bihā al-mujrimūn",
            "verse_number": 43,
        },
        {
            "arabic_text": "يَطُوفُونَ بَيْنَهَا وَبَيْنَ حَمِيمٍ ءَانٍۢ",
            "urdu_text": "وہ اس کے درمیان اور کھولتے پانی کے درمیان چکر لگائیں گے",
            "persian_text": "میان آن و آب جوشان در رفت‌وآمد خواهند بود",
            "english_text": "They will go around between it and scalding water, heated to the utmost degree.",
            "transliteration": "Yaṭūfūna baynahā wa bayna ḥamīmin ān",
            "verse_number": 44,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 45,
        },
        {
            "arabic_text": "وَلِمَنْ خَافَ مَقَامَ رَبِّهِ جَنَّتَانِ",
            "urdu_text": "اور جو اپنے رب کے حضور کھڑے ہونے سے ڈرا، اس کے لیے دو جنتیں ہیں",
            "persian_text": "و برای کسی که از مقام پروردگارش ترسید، دو بهشت است",
            "english_text": "But for he who has feared the standing before his Lord are two gardens.",
            "transliteration": "Waliman khāfa maqāma rabbihi jannatān",
            "verse_number": 46,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 47,
        },
        {
            "arabic_text": "ذَوَاتَآ اَفْنَانٍۢ",
            "urdu_text": "جن کی شاخیں جھکی ہوئی ہوں گی",
            "persian_text": "دارای شاخه‌های بسیار",
            "english_text": "Having spreading branches.",
            "transliteration": "Dhāwātā afnān",
            "verse_number": 48,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 49,
        },
        {
            "arabic_text": "فِيهِمَا عَيْنَانِ تَجْرِيَانِ",
            "urdu_text": "ان دونوں میں دو چشمے بہہ رہے ہوں گے",
            "persian_text": "در آن دو، دو چشمه جاری است",
            "english_text": "In both of them are two flowing springs.",
            "transliteration": "Fīhimā ʿaynāni tajriyān",
            "verse_number": 50,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 51,
        },
        {
            "arabic_text": "فِيهِمَا مِن كُلِّ فَـٰكِهَةٍۢ زَوْجَانِ",
            "urdu_text": "ان میں ہر پھل کی دو قسمیں ہوں گی",
            "persian_text": "در آن دو، از هر میوه‌ای دو نوع است",
            "english_text": "In both of them are of every fruit two kinds.",
            "transliteration": "Fīhimā min kulli fākihatin zawjān",
            "verse_number": 52,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 53,
        },
        {
            "arabic_text": "مُتَّكِـِٔينَ عَلٰى فُرُشٍۢ بَطَآئِنُهَا مِنْ اِسْتَبْرَقٍۢ ۚ وَجَنَى الْجَنَّتَيْنِ دَانٍۭ",
            "urdu_text": "وہ ٹیک لگائے ہوں گے مخملی کپڑے کے بستروں پر، اور دونوں جنتوں کے پھل قریب ہوں گے",
            "persian_text": "بر تخت‌هایی تکیه زده‌اند که آستری آن‌ها از دیباست، و میوه‌های دو بهشت در دسترس است",
            "english_text": "Reclining on beds whose linings are of silk brocade, and the fruit of the two gardens is hanging low.",
            "transliteration": "Muttaki’īna ʿalā furushin baṭā’inuhā min istabraq, wa janā al-jannatayni dān",
            "verse_number": 54,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 55,
        },
        {
            "arabic_text": "فِيهِنَّ قٰصِرٰتُ الطَّرْفِ لَمْ يَطْمِثْهُنَّ اِنسٌۭ قَبْلَهُمْ وَلَا جَآنٌّۭ",
            "urdu_text": "ان میں نیچی نظروں والی عورتیں ہوں گی، جنہیں ان سے پہلے کسی انسان یا جن نے نہ چھوا ہوگا",
            "persian_text": "در آن‌ها زنانی هستند که نگاه‌شان فروهشته است، که پیش از آن‌ها هیچ انسانی یا جنی به آن‌ها دست نزده است",
            "english_text": "In them are women limiting their glances, whom no man or jinn has touched before them.",
            "transliteration": "Fīhinna qāṣirātu aṭ-ṭarfi lam yaṭmith’hunna insun qab lahum walā jān",
            "verse_number": 56,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 57,
        },
        {
            "arabic_text": "كَاَنَّهُنَّ الْيَاقُوتُ وَالْمَرْجَانُ",
            "urdu_text": "گویا وہ یاقوت اور مرجان کی مانند ہوں گی",
            "persian_text": "چنان‌اند که گویی یاقوت و مرجان‌اند",
            "english_text": "As if they were rubies and coral.",
            "transliteration": "Ka’annahunna al-yāqūtu wal-marjān",
            "verse_number": 58,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 59,
        },
        {
            "arabic_text": "هَلْ جَزَآءُ الْاِحْسٰنِ اِلَّا الْاِحْسٰنُ",
            "urdu_text": "نیکی کا بدلہ نیکی کے سوا اور کیا ہو سکتا ہے؟",
            "persian_text": "آیا پاداش نیکی چیزی جز نیکی است؟",
            "english_text": "Is the reward for good [anything] but good?",
            "transliteration": "Hal jazā’u al-iḥsāni illā al-iḥsān",
            "verse_number": 60,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 61,
        },
        {
            "arabic_text": "وَمِن دُونِهِمَا جَنَّتَانِ",
            "urdu_text": "اور ان دونوں کے علاوہ دو اور جنتیں ہوں گی",
            "persian_text": "و غیر از آن دو، دو بهشت دیگر است",
            "english_text": "And below them both are two other gardens.",
            "transliteration": "Wa min dūnihimā jannatān",
            "verse_number": 62,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 63,
        },
        {
            "arabic_text": "مُدْهَامَّتَانِ",
            "urdu_text": "وہ دونوں گہری سبز رنگ کی ہوں گی",
            "persian_text": "هر دو تیره و سرسبز خواهند بود",
            "english_text": "Dark green [in color].",
            "transliteration": "Mud’hāmmatān",
            "verse_number": 64,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 65,
        },
        {
            "arabic_text": "فِيهِمَا عَيْنَانِ نَضَّاخَتَانِ",
            "urdu_text": "ان میں دو چشمے پھوٹ رہے ہوں گے",
            "persian_text": "در آن‌ها دو چشمه جوشان است",
            "english_text": "In both of them are two springs, gushing forth.",
            "transliteration": "Fīhimā ʿaynāni naḍḍākhatān",
            "verse_number": 66,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 67,
        },
        {
            "arabic_text": "فِيهِمَا فَـٰكِهَةٌۭ وَنَخْلٌۭ وَرُمَّانٌۭ",
            "urdu_text": "ان میں پھل، کھجوریں اور انار ہوں گے",
            "persian_text": "در آن‌ها میوه‌ها، درختان خرما و انار است",
            "english_text": "In them are fruit and palm trees and pomegranates.",
            "transliteration": "Fīhimā fākihatun wa nakhlun wa rummān",
            "verse_number": 68,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 69,
        },
        {
            "arabic_text": "فِيهِنَّ خَيْرٰتٌ حِسَانٌۭ",
            "urdu_text": "ان میں نیک سیرت خوبصورت بیبیاں ہوں گی",
            "persian_text": "در آن‌ها زنان نیکوخصال و زیبا هستند",
            "english_text": "In them are good and beautiful women.",
            "transliteration": "Fīhinna khayrātun ḥisān",
            "verse_number": 70,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 71,
        },
        {
            "arabic_text": "حُورٌۭ مَّقْصُورٰتٌۭ فِى الْخِيَامِ",
            "urdu_text": "حوریں ہوں گی جو خیموں میں رکھی گئی ہوں گی",
            "persian_text": "حورانی که در خیمه‌ها مستورند",
            "english_text": "Fair ones reserved in pavilions.",
            "transliteration": "Ḥūrun maqṣūrātun fī al-khiyām",
            "verse_number": 72,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 73,
        },
        {
            "arabic_text": "لَمْ يَطْمِثْهُنَّ اِنسٌۭ قَبْلَهُمْ وَلَا جَآنٌّۭ",
            "urdu_text": "انہیں ان سے پہلے نہ کسی انسان نے چھوا، نہ کسی جن نے",
            "persian_text": "که هیچ انسانی و جنی پیش از آنان آن‌ها را لمس نکرده است",
            "english_text": "Whom no man or jinn has touched before them.",
            "transliteration": "Lam yaṭmith’hunna insun qablahum walā jān",
            "verse_number": 74,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 75,
        },
        {
            "arabic_text": "مُتَّكِـِٔينَ عَلٰى رَفْرَفٍ خُضْرٍۢ وَعَبْقَرِىٍّ حِسَانٍۢ",
            "urdu_text": "وہ سبز قالینوں اور عمدہ فرشوں پر تکیہ لگائے ہوں گے",
            "persian_text": "بر بالش‌های سبز و فرش‌های نفیس تکیه زده‌اند",
            "english_text": "Reclining on green cushions and beautiful fine carpets.",
            "transliteration": "Muttaki’īna ʿalā rafrafin khuḍ’rin wa ʿabqariyyin ḥisān",
            "verse_number": 76,
        },
        {
            "arabic_text": "فَبِاَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ",
            "urdu_text": "پھر تم اپنے رب کی کون کون سی نعمتوں کو جھٹلاؤ گے؟",
            "persian_text": "پس کدام‌یک از نعمت‌های پروردگارتان را انکار می‌کنید؟",
            "english_text": "Then which of the favors of your Lord will you deny?",
            "transliteration": "Fabi ayyi ālā’i rabbikumā tukadhdhibān",
            "verse_number": 77,
        },
        {
            "arabic_text": "تَبَـٰرَكَ اسْمُ رَبِّكَ ذِى الْجَلَـٰلِ وَالْاِكْرَامِ",
            "urdu_text": "بہت بابرکت ہے تیرے رب کا نام جو عظمت اور بزرگی والا ہے",
            "persian_text": "مبارک است نام پروردگار تو، صاحب جلال و بزرگواری",
            "english_text": "Blessed is the name of your Lord, Owner of Majesty and Honor.",
            "transliteration": "Tabāraka ismu rabbika dhī al-jalāli wal-ikrām",
            "verse_number": 78,
        },
    ],
    [
        {
            "arabic_text": "اِذَا وَقَعَتِ الْوَاقِعَةُ",
            "urdu_text": "جب واقعہ رونما ہو گا",
            "persian_text": "هنگامی که آن واقعه رخ دهد",
            "english_text": "When the Event (the Day of Resurrection) befalls",
            "transliteration": "Iza waqaʿati al-waqiʿah",
            "verse_number": "56:1",
        },
        {
            "arabic_text": "لَيْسَ لِوَقْعَتِهَا كٰذِبَةٌ",
            "urdu_text": "اس کے واقع ہونے میں کوئی جھوٹ نہیں",
            "persian_text": "در وقوع آن هیچ دروغی نیست",
            "english_text": "There is no denial of its occurrence",
            "transliteration": "Laysa liwaqʿatiha kadhibah",
            "verse_number": "56:2",
        },
        {
            "arabic_text": "خَافِضَةٌ رَّافِعَةٌ",
            "urdu_text": "وہ پست کرنے والی اور بلند کرنے والی ہو گی",
            "persian_text": "پایین‌آورنده و بالا‌برنده است",
            "english_text": "It will bring down (some) and raise up (others)",
            "transliteration": "Khafidatun rafiʿah",
            "verse_number": "56:3",
        },
        {
            "arabic_text": "اِذَا رُجَّتِ الْاَرْضُ رَجًّا",
            "urdu_text": "جب زمین کو زور سے ہلا دیا جائے گا",
            "persian_text": "آنگاه که زمین به شدت لرزانده شود",
            "english_text": "When the earth will be shaken with a terrible shake",
            "transliteration": "Iza rujjati al-ardu rajja",
            "verse_number": "56:4",
        },
        {
            "arabic_text": "وَبُسَّتِ الْجِبَالُ بَسًّا",
            "urdu_text": "اور پہاڑ ریزہ ریزہ کر دیے جائیں گے",
            "persian_text": "و کوه‌ها خرد شوند",
            "english_text": "And the mountains will be crushed to pieces",
            "transliteration": "Wa bussatil-jibalu bassa",
            "verse_number": "56:5",
        },
        {
            "arabic_text": "فَكَانَتْ هَبَآءٗ مُّنۢبَثّٗا",
            "urdu_text": "تو وہ غبار کی طرح بکھر جائیں گے",
            "persian_text": "پس مانند غبار پراکنده خواهند شد",
            "english_text": "So they will become floating dust particles",
            "transliteration": "Fakanat haba'an munbaththa",
            "verse_number": "56:6",
        },
        {
            "arabic_text": "وَكُنتُمْ اَزْوَاجٗا ثَلٰثَةٌ",
            "urdu_text": "اور تم تین گروہوں میں تقسیم ہو جاؤ گے",
            "persian_text": "و شما سه گروه خواهید شد",
            "english_text": "And you will be in three groups",
            "transliteration": "Wa kuntum azwajan thalathah",
            "verse_number": "56:7",
        },
        {
            "arabic_text": "فَاَصْحَٰبُ الْمَيْمَنَةِ مَا اَصْحَٰبُ الْمَيْمَنَةِ",
            "urdu_text": "پس داہنے والے، کیا خوب ہیں داہنے والے",
            "persian_text": "پس یاران راست، چه نیکو هستند یاران راست",
            "english_text": "So those on the Right – what are those on the Right?",
            "transliteration": "Fa-as-habu al-maymanati ma as-habu al-maymanah",
            "verse_number": "56:8",
        },
        {
            "arabic_text": "وَاَصْحَٰبُ الْمَشْـَٔمَةِ مَا اَصْحَٰبُ الْمَشْـَٔمَةِ",
            "urdu_text": "اور بائیں والے، کیا ہی برے ہیں بائیں والے",
            "persian_text": "و یاران چپ، چه بدند یاران چپ",
            "english_text": "And those on the Left – what are those on the Left?",
            "transliteration": "Wa as-habu al-mash-amati ma as-habu al-mash-ama",
            "verse_number": "56:9",
        },
        {
            "arabic_text": "وَالسَّٰبِقُونَ السَّٰبِقُونَ",
            "urdu_text": "اور جو سبقت لے گئے، وہی سبقت لے جانے والے ہیں",
            "persian_text": "و پیشتازان، همان پیشتازانند",
            "english_text": "And the forerunners, the forerunners",
            "transliteration": "Wa as-sabiqoon as-sabiqoon",
            "verse_number": "56:10",
        },
        {
            "arabic_text": "اُوْلٰٓئِكَ الْمُقَرَّبُونَ",
            "urdu_text": "وہی ہیں جو قرب الٰہی والے ہوں گے",
            "persian_text": "آنان همان مقربانند",
            "english_text": "Those are the ones brought near (to Allah)",
            "transliteration": "Ulaaa'ikal-muqarraboon",
            "verse_number": "56:11",
        },
        {
            "arabic_text": "فِى جَنَّٰتِ النَّعِيمِ",
            "urdu_text": "نعمتوں والی جنتوں میں ہوں گے",
            "persian_text": "در باغ‌های پرنعمت خواهند بود",
            "english_text": "In Gardens of Pleasure",
            "transliteration": "Fee jannaatin-na'eem",
            "verse_number": "56:12",
        },
        {
            "arabic_text": "ثُلَّةٞ مِّنَ الْاَوَّلِينَ",
            "urdu_text": "اکثر اگلے لوگوں میں سے ہوں گے",
            "persian_text": "گروهی بسیار از پیشینیان",
            "english_text": "A large company from the former peoples",
            "transliteration": "Sullatum minal-awwaleen",
            "verse_number": "56:13",
        },
        {
            "arabic_text": "وَقَلِيلٞ مِّنَ الْاٰخِرِينَ",
            "urdu_text": "اور کچھ ہی پچھلے لوگوں میں سے",
            "persian_text": "و اندکی از پسینیان",
            "english_text": "And a few of the later peoples",
            "transliteration": "Wa qaleelum minal-aakhireen",
            "verse_number": "56:14",
        },
        {
            "arabic_text": "عَلٰى سُرُرٖ مَّوْضُونَةٖ",
            "urdu_text": "وہ جڑاؤ تختوں پر ہوں گے",
            "persian_text": "بر تخت‌های بافته‌شده خواهند بود",
            "english_text": "On thrones woven [with ornament]",
            "transliteration": "Alaa sururim mawdoonah",
            "verse_number": "56:15",
        },
        {
            "arabic_text": "مُّتَّكِـِٔينَ عَلَيْهَا مُتَقَٰبِلِينَ",
            "urdu_text": "ان پر تکیہ لگائے ہوئے، آمنے سامنے بیٹھے ہوں گے",
            "persian_text": "بر آن‌ها تکیه زده، روبروی یکدیگر خواهند بود",
            "english_text": "Reclining on them, facing each other",
            "transliteration": "Muttaki'eena 'alayhaa mutaqaabileen",
            "verse_number": "56:16",
        },
        {
            "arabic_text": "يَطُوفُ عَلَيْهِمْ وِلْدَٰنٞ مُّخَلَّدُونَ",
            "urdu_text": "ان کے گرد ہمیشہ کے نوجوان گردش کریں گے",
            "persian_text": "پیرامونشان پسران جاودان در گردش‌اند",
            "english_text": "There will circulate among them young boys made eternal",
            "transliteration": "Yatoofu 'alayhim wildaanum mukhalladoon",
            "verse_number": "56:17",
        },
        {
            "arabic_text": "بِاَكْوَابٖ وَاَبَارِيقَ وَكَاْسٖ مِّن مَّعِينٖ",
            "urdu_text": "پیالوں، جگوں اور ایک جاری چشمے سے بھرے ہوئے جاموں کے ساتھ",
            "persian_text": "با جام‌ها، کوزه‌ها و پیاله‌هایی از شراب جاری",
            "english_text": "With vessels, pitchers and a cup [of wine] from a flowing spring",
            "transliteration": "Bi-akwābin wa abāreeqa wa ka'sim mim ma'een",
            "verse_number": "56:18",
        },
        {
            "arabic_text": "لَا يُصَدَّعُونَ عَنْهَا وَلَا يُنزِفُونَ",
            "urdu_text": "نہ اس سے ان کا سر درد کرے گا اور نہ وہ بے ہوش ہوں گے",
            "persian_text": "نه از آن سردرد می‌گیرند و نه مست می‌شوند",
            "english_text": "No headache will they have therefrom, nor will they be intoxicated",
            "transliteration": "Laa yusadda'oona 'anhaa wa laa yunzifoon",
            "verse_number": "56:19",
        },
        {
            "arabic_text": "وَفٰكِهَةٖ مِّمَّا يَتَخَيَّرُونَ",
            "urdu_text": "اور ان کے لیے وہ میوے ہوں گے جو وہ پسند کریں گے",
            "persian_text": "و میوه‌هایی از آنچه انتخاب کنند",
            "english_text": "And fruit of what they select",
            "transliteration": "Wa faakihatim mimmaa yatakhayyaroon",
            "verse_number": "56:20",
        },
        {
            "arabic_text": "وَلَحْمِ طَيْرٍ مِّمَّا يَشْتَهُونَ",
            "urdu_text": "اور ایسے پرندوں کا گوشت جو وہ چاہیں",
            "persian_text": "و گوشت پرندگانی که میل دارند",
            "english_text": "And meat of fowls that they desire",
            "transliteration": "Wa lahmi tayrin mimma yashtahoon",
            "verse_number": "56:21",
        },
        {
            "arabic_text": "وَحُورٌ عِينٌ",
            "urdu_text": "اور بڑی بڑی آنکھوں والی حوریں",
            "persian_text": "و حوریانی با چشمان درشت",
            "english_text": "And [for them are] fair women with large, [beautiful] eyes",
            "transliteration": "Wa hoorun 'een",
            "verse_number": "56:22",
        },
        {
            "arabic_text": "كَاَمْثَالِ اللُّؤْلُؤِ الْمَكْنُونِ",
            "urdu_text": "جو چھپائے ہوئے موتیوں کی مانند ہیں",
            "persian_text": "مانند مرواریدهای پنهان",
            "english_text": "The likenesses of pearls well-protected",
            "transliteration": "Ka amsaalil lu'lu'il maknoon",
            "verse_number": "56:23",
        },
        {
            "arabic_text": "جَزَاءً بِمَا كَانُوا يَعْمَلُونَ",
            "urdu_text": "یہ بدلہ ہے ان کے اعمال کا جو وہ کرتے تھے",
            "persian_text": "پاداش کارهایی که انجام می‌دادند",
            "english_text": "[As] reward for what they used to do",
            "transliteration": "Jazaa’am bimaa kaanoo ya’maloon",
            "verse_number": "56:24",
        },
        {
            "arabic_text": "لَا يَسْمَعُونَ فِيهَا لَغْوًا وَلَا تَاْثِيمًا",
            "urdu_text": "نہ وہ وہاں کوئی بیہودہ بات سنیں گے نہ گناہ کی",
            "persian_text": "نه در آنجا سخن لغو می‌شنوند و نه گناه‌آلود",
            "english_text": "They will not hear therein ill speech or commission of sin",
            "transliteration": "Laa yasma’oona feehaa laghwan wa laa ta’theema",
            "verse_number": "56:25",
        },
        {
            "arabic_text": "اِلَّا قِيلًا سَلَامًا سَلَامًا",
            "urdu_text": "سوائے سلام، سلام کے",
            "persian_text": "جز سخن صلح و سلام، سلام",
            "english_text": "But only the saying of: 'Peace, peace.'",
            "transliteration": "Illaa qeelan salaaman salaama",
            "verse_number": "56:26",
        },
        {
            "arabic_text": "وَاَصْحٰبُ الْيَمِينِ مَا اَصْحٰبُ الْيَمِينِ",
            "urdu_text": "اور داہنے ہاتھ والے، کیا خوب ہیں داہنے ہاتھ والے!",
            "persian_text": "و یاران دست راست، چه نیکو یارانی‌اند!",
            "english_text": "And the companions of the right – what are the companions of the right?",
            "transliteration": "Wa as-haabul yameeni maa as-haabul yameen",
            "verse_number": "56:27",
        },
        {
            "arabic_text": "فِى سِدْرٍ مَّخْضُودٍ",
            "urdu_text": "وہ بیریوں میں ہوں گے جن میں کانٹے نہ ہوں گے",
            "persian_text": "در درختان سدر بی‌خار",
            "english_text": "They will be among lote trees with thorns removed",
            "transliteration": "Fee sidrin makhdood",
            "verse_number": "56:28",
        },
        {
            "arabic_text": "وَطَلْحٍ مَّنضُودٍ",
            "urdu_text": "اور کیلے کے تہہ بہ تہہ درختوں میں",
            "persian_text": "و در میان موزهای دسته‌دسته چیده‌شده",
            "english_text": "And [banana] trees layered [with fruit]",
            "transliteration": "Wa talhin mandood",
            "verse_number": "56:29",
        },
        {
            "arabic_text": "وَظِلٍّ مَّمْدُودٍ",
            "urdu_text": "اور پھیلی ہوئی چھاؤں میں",
            "persian_text": "و در سایه‌های گسترده",
            "english_text": "And shade extended",
            "transliteration": "Wa zillin mamdood",
            "verse_number": "56:30",
        },
        {
            "arabic_text": "وَمَاءٍ مَّسْكُوبٍ",
            "urdu_text": "اور بہتے ہوئے پانی میں",
            "persian_text": "و در آب روان",
            "english_text": "And water poured out",
            "transliteration": "Wa maaa’im maskoob",
            "verse_number": "56:31",
        },
        {
            "arabic_text": "وَفٰكِهَةٖ كَثِيرَةٖ",
            "urdu_text": "اور بکثرت میوے",
            "persian_text": "و میوه‌های فراوان",
            "english_text": "And abundant fruit",
            "transliteration": "Wa faakihatik katheerah",
            "verse_number": "56:32",
        },
        {
            "arabic_text": "لَّا مَقْطُوعَةٖ وَلَا مَمْنُوعَةٖ",
            "urdu_text": "جو نہ ختم ہوں گے اور نہ روکے جائیں گے",
            "persian_text": "نه قطع می‌شود و نه ممنوع است",
            "english_text": "Neither limited [to season] nor forbidden",
            "transliteration": "Laa maqtoo’atin wa laa mamnoo’ah",
            "verse_number": "56:33",
        },
        {
            "arabic_text": "وَفُرُشٖ مَّرْفُوعَةٍ",
            "urdu_text": "اور اونچے بچھونے ہوں گے",
            "persian_text": "و بسترهای بر افراشته",
            "english_text": "And [upon] beds raised high",
            "transliteration": "Wa furooshim marfoo’ah",
            "verse_number": "56:34",
        },
        {
            "arabic_text": "اِنَّآ اَنشَاْنَٰهُنَّ اِنشَآءٗ",
            "urdu_text": "ہم نے ان (بیویوں) کو خاص طور پر پیدا کیا",
            "persian_text": "ما آنان را آفرینشی نو بخشیدیم",
            "english_text": "Indeed, We have produced them [i.e., the women] in a [new] creation",
            "transliteration": "Innaaa ansha’naahunna inshaaa’a",
            "verse_number": "56:35",
        },
        {
            "arabic_text": "فَجَعَلْنَٰهُنَّ اَبْكَارًا",
            "urdu_text": "اور ہم نے انہیں کنواری بنایا",
            "persian_text": "و آنان را دوشیزه گردانیدیم",
            "english_text": "And made them virgins",
            "transliteration": "Faja’alnaahunna abkaaraa",
            "verse_number": "56:36",
        },
        {
            "arabic_text": "عُرُبًا اَتْرَابًا",
            "urdu_text": "پیار کرنے والیاں، ہم عمر",
            "persian_text": "مهربان و هم‌سن و سال",
            "english_text": "Devoted [to their husbands] and of equal age",
            "transliteration": "Urooban atraabaa",
            "verse_number": "56:37",
        },
        {
            "arabic_text": "لِّاَصْحَٰبِ الْيَمِينِ",
            "urdu_text": "یہ سب کچھ داہنے ہاتھ والوں کے لیے ہوگا",
            "persian_text": "برای یاران دست راست",
            "english_text": "For the companions of the right",
            "transliteration": "Li as-haabil yameen",
            "verse_number": "56:38",
        },
        {
            "arabic_text": "ثُلَّةٞ مِّنَ الْاَوَّلِينَ",
            "urdu_text": "ایک جماعت اگلے لوگوں میں سے ہوگی",
            "persian_text": "گروهی از پیشینیان",
            "english_text": "A company of the former peoples",
            "transliteration": "Sullatum minal awwaleen",
            "verse_number": "56:39",
        },
        {
            "arabic_text": "وَثُلَّةٞ مِّنَ الْاٰخِرِينَ",
            "urdu_text": "اور ایک جماعت پچھلے لوگوں میں سے ہوگی",
            "persian_text": "و گروهی از پسینیان",
            "english_text": "And a company of the later peoples",
            "transliteration": "Wa sullatum minal aakhireen",
            "verse_number": "56:40",
        },
        {
            "arabic_text": "وَاَصْحَٰبُ الشِّمَالِ مَآ اَصْحَٰبُ الشِّمَالِ",
            "urdu_text": "اور بائیں ہاتھ والے، کیا حال ہوگا بائیں ہاتھ والوں کا؟",
            "persian_text": "و یاران دست چپ، وای بر یاران دست چپ!",
            "english_text": "And the companions of the left – what are the companions of the left?",
            "transliteration": "Wa as-haabush shimaal, maa as-haabush shimaal",
            "verse_number": "56:41",
        },
        {
            "arabic_text": "فِى سَمُومٖ وَحَمِيمٖ",
            "urdu_text": "وہ جلتی ہوا اور کھولتے پانی میں ہوں گے",
            "persian_text": "در باد داغ و آب جوشان خواهند بود",
            "english_text": "They will be in scorching fire and scalding water",
            "transliteration": "Fee samoominw-wa hameem",
            "verse_number": "56:42",
        },
        {
            "arabic_text": "وَظِلّٖ مِّن يَحْمُومٖ",
            "urdu_text": "اور کالے دھوئیں کے سائے میں",
            "persian_text": "و در سایه‌ای از دود سیاه",
            "english_text": "And a shade of black smoke",
            "transliteration": "Wa zillin min yahmoom",
            "verse_number": "56:43",
        },
        {
            "arabic_text": "لَّا بَارِدٖ وَلَا كَرِيمٍ",
            "urdu_text": "نہ وہ ٹھنڈا ہوگا، نہ آرام دہ",
            "persian_text": "نه خنک است و نه دلپذیر",
            "english_text": "Neither cool nor beneficial",
            "transliteration": "Laa baaridinw-wa laa kareem",
            "verse_number": "56:44",
        },
        {
            "arabic_text": "اِنَّهُمْ كَانُواْ قَبْلَ ذَٰلِكَ مُتْرَفِينَ",
            "urdu_text": "وہ اس سے پہلے خوشحال تھے",
            "persian_text": "آنان پیش از این در ناز و نعمت بودند",
            "english_text": "Indeed they were, before that, indulging in affluence",
            "transliteration": "Innahum kaanoo qabla zaalika mutrafeen",
            "verse_number": "56:45",
        },
        {
            "arabic_text": "وَكَانُواْ يُصِرُّونَ عَلَى الْحِنثِ الْعَظِيمِ",
            "urdu_text": "اور وہ بڑے گناہ پر اصرار کرتے تھے",
            "persian_text": "و بر گناه بزرگ پافشاری می‌کردند",
            "english_text": "And they used to persist in the great violation",
            "transliteration": "Wa kaanoo yusirroona ‘alal hinthil ‘azeem",
            "verse_number": "56:46",
        },
        {
            "arabic_text": "وَكَانُواْ يَقُولُونَ اَئِذَا مِتْنَا وَكُنَّا تُرٰبٗا وَعِظَٰمًا اَءِنَّا لَمَبْعُوثُونَ",
            "urdu_text": "اور وہ کہتے تھے: جب ہم مرجائیں گے اور مٹی اور ہڈی بن جائیں گے، تو کیا ہم پھر اٹھائے جائیں گے؟",
            "persian_text": "و می‌گفتند: آیا زمانی که مردیم و خاک و استخوان شدیم، آیا ما برانگیخته خواهیم شد؟",
            "english_text": "And used to say, 'When we die and become dust and bones, are we indeed to be resurrected?'",
            "transliteration": "Wa kaanoo yaqooloona a’izaa mitnaa wa kunnaa turaabanw-wa ‘izaaman a’innaa lamab’oosoon",
            "verse_number": "56:47",
        },
        {
            "arabic_text": "اَوَ ءَابَآؤُنَا الْاَوَّلُونَ",
            "urdu_text": "کیا ہمارے باپ دادا بھی؟",
            "persian_text": "و آیا پدران نخستین ما نیز؟",
            "english_text": "And our forefathers as well?",
            "transliteration": "Awa aabaaa’unal awwaloon",
            "verse_number": "56:48",
        },
        {
            "arabic_text": "قُلْ اِنَّ الْاَوَّلِينَ وَالْءَاخِرِينَ",
            "urdu_text": "کہہ دو: یقیناً اگلے اور پچھلے سب",
            "persian_text": "بگو: به راستی پیشینیان و پسینیان",
            "english_text": "Say, 'Indeed, the former and the later peoples",
            "transliteration": "Qul innal awwaleena wal aakhireen",
            "verse_number": "56:49",
        },
        {
            "arabic_text": "لَمَجْمُوعُونَ اِلَىٰ مِيقَٰتِ يَوْمٖ مَّعْلُومٖ",
            "urdu_text": "ضرور ایک مقرر وقت کے دن جمع کیے جائیں گے",
            "persian_text": "همگی در وقت معیّنی از روزی معلوم گردآورده خواهند شد",
            "english_text": "Will surely be gathered together for the appointment of a known Day",
            "transliteration": "Lamajmoo’oona ilaa meeqaati Yawmim ma’loom",
            "verse_number": "56:50",
        },
        {
            "arabic_text": "ثُمَّ اِنَّكُمْ اَيُّهَا الضَّآلُّونَ الْمُكَذِّبُونَ",
            "urdu_text": "پھر اے گمراہو اور جھٹلانے والو!",
            "persian_text": "پس ای گمراهان و دروغ‌پنداران!",
            "english_text": "Then indeed you, O those astray who are deniers,",
            "transliteration": "Thumma innakum ayyuhad-daalloonal-mukazziboon",
            "verse_number": "56:51",
        },
        {
            "arabic_text": "لَآكِلُونَ مِن شَجَرٖ مِّن زَقُّومٖ",
            "urdu_text": "تم زقوم کے درخت میں سے کھانے والے ہو",
            "persian_text": "حتماً از درخت زقوم خواهید خورد",
            "english_text": "Will be eating from trees of zaqqum",
            "transliteration": "La aakiloona min shajarin min zaqqoom",
            "verse_number": "56:52",
        },
        {
            "arabic_text": "فَمَالِؤُونَ مِنْهَا الْبُطُونَ",
            "urdu_text": "اور تم اسی سے پیٹ بھرو گے",
            "persian_text": "و شکم‌هایتان را از آن پر خواهید کرد",
            "english_text": "And filling with it your bellies",
            "transliteration": "Famaali’oona minhaal-butoon",
            "verse_number": "56:53",
        },
        {
            "arabic_text": "فَشَٰرِبُونَ عَلَيْهِ مِنَ الْحَمِيمِ",
            "urdu_text": "پھر تم اس پر کھولتا پانی پیو گے",
            "persian_text": "سپس بر روی آن آب جوشان خواهید نوشید",
            "english_text": "And drinking on top of it from scalding water",
            "transliteration": "Fashaari-boona ‘alayhi minal-hameem",
            "verse_number": "56:54",
        },
        {
            "arabic_text": "فَشَٰرِبُونَ شُرْبَ الْهِيمِ",
            "urdu_text": "یوں پیو گے جیسے پیاسے اونٹ پیتے ہیں",
            "persian_text": "همانند شتران بسیار تشنه خواهید نوشید",
            "english_text": "And will drink as the drinking of thirsty camels",
            "transliteration": "Fashaari-boona shurbal-heem",
            "verse_number": "56:55",
        },
        {
            "arabic_text": "هٰذَا نُزُلُهُمْ يَوْمَ الدِّينِ",
            "urdu_text": "یہ ان کی مہمانی ہے جزا کے دن",
            "persian_text": "این است پذیرایی آنان در روز جزا",
            "english_text": "This is their hospitality on the Day of Recompense",
            "transliteration": "Haazaa nuzuluhum yawma ad-deen",
            "verse_number": "56:56",
        },
        {
            "arabic_text": "نَحْنُ خَلَقْنَٰكُمْ فَلَوْلَا تُصَدِّقُونَ",
            "urdu_text": "ہم نے تمہیں پیدا کیا، تو تم کیوں تصدیق نہیں کرتے؟",
            "persian_text": "ما شما را آفریدیم، پس چرا تصدیق نمی‌کنید؟",
            "english_text": "We created you, so why do you not believe?",
            "transliteration": "Nahnu khalaqnaakum falaawlaa tusaddiqoon",
            "verse_number": "56:57",
        },
        {
            "arabic_text": "اَفَرَءَيْتُم مَّا تُمْنُونَ",
            "urdu_text": "کیا تم نے دیکھا وہ (نطفہ) جو تم ٹپکاتے ہو؟",
            "persian_text": "آیا آنچه را که نطفه‌افشانی می‌کنید دیده‌اید؟",
            "english_text": "Then have you seen that which you emit?",
            "transliteration": "Afara’aytum maa tumnoon",
            "verse_number": "56:58",
        },
        {
            "arabic_text": "ءَاَنتُمْ تَخْلُقُونَهُٓ اَمْ نَحْنُ الْخٰلِقُونَ",
            "urdu_text": "کیا تم اسے پیدا کرتے ہو یا ہم پیدا کرنے والے ہیں؟",
            "persian_text": "آیا شما آن را می‌آفرینید یا ما آفرینندگانیم؟",
            "english_text": "Is it you who creates it, or are We the Creator?",
            "transliteration": "A’antum takhluqoonahu am nahnul-khaaliqoon",
            "verse_number": "56:59",
        },
        {
            "arabic_text": "نَحْنُ قَدَّرْنَا بَيْنَكُمُ الْمَوْتَ وَمَا نَحْنُ بِمَسْبُوقِينَ",
            "urdu_text": "ہم نے تمہارے درمیان موت کو مقرر کیا، اور ہم عاجز نہیں",
            "persian_text": "ما مرگ را میان شما مقدر داشتیم، و ما مغلوب شدنی نیستیم",
            "english_text": "We have decreed death among you, and We are not to be outdone",
            "transliteration": "Nahnu qaddarnaa bainakumul-mawta wa maa nahnu bimasbooqeen",
            "verse_number": "56:60",
        },
        {
            "arabic_text": "عَلٰىٓ اَن نُّبَدِّلَ اَمْثَٰلَكُمْ وَنُنشِئَكُمْ فِى مَا لَا تَعْلَمُونَ",
            "urdu_text": "ہم اس پر قادر ہیں کہ تم جیسی مخلوق بدل دیں اور تمہیں ایسی حالت میں پیدا کریں جسے تم نہیں جانتے",
            "persian_text": "ما تواناییم که همانندان شما را جایگزین کنیم و شما را در حالی دیگر که نمی‌دانید پدید آوریم",
            "english_text": "That We may change your likenesses and produce you in that [form] which you do not know",
            "transliteration": "Alaaa an nubaddila amsaalakum wa nunshi'akum fee maa laa ta’lamoon",
            "verse_number": "56:61",
        },
        {
            "arabic_text": "وَلَقَدْ عَلِمْتُمُ النَّشْاَةَ الْاُولَىٰ فَلَوْلَا تَذَكَّرُونَ",
            "urdu_text": "اور تم نے پہلی پیدائش دیکھی ہے، تو کیوں نصیحت حاصل نہیں کرتے؟",
            "persian_text": "و شما آفرینش نخستین را دانسته‌اید، پس چرا پند نمی‌گیرید؟",
            "english_text": "And you have already known the first creation, so will you not remember?",
            "transliteration": "Walaqad ‘alimtumn-nash’atal-oola falaaw laa tazzakkaroon",
            "verse_number": "56:62",
        },
        {
            "arabic_text": "اَفَرَءَيْتُم مَّا تَحْرُثُونَ",
            "urdu_text": "کیا تم نے غور کیا اس چیز پر جو تم بوتے ہو؟",
            "persian_text": "آیا نگریسته‌اید به آنچه می‌کارید؟",
            "english_text": "And have you seen that [seed] which you sow?",
            "transliteration": "Afara’aytum maa tahruthoon",
            "verse_number": "56:63",
        },
        {
            "arabic_text": "ءَاَنتُمْ تَزْرَعُونَهُٓ اَمْ نَحْنُ الزَّٰرِعُونَ",
            "urdu_text": "کیا تم اسے اگاتے ہو یا ہم اگانے والے ہیں؟",
            "persian_text": "آیا شما آن را می‌رویانید یا ما رویاننده‌ایم؟",
            "english_text": "Is it you who makes it grow, or are We the grower?",
            "transliteration": "A’antum tazra’oonahu am nahnuz-zaari’oon",
            "verse_number": "56:64",
        },
        {
            "arabic_text": "لَوْ نَشَآءُ لَجَعَلْنَٰهُ حُطٰمًا فَظَلْتُمْ تَفَكَّهُونَ",
            "urdu_text": "اگر ہم چاہیں تو اسے چورا چورا کر دیں، تو تم حیران رہ جاؤ گے",
            "persian_text": "اگر بخواهیم آن را ریز ریز می‌کنیم، پس شما در شگفت می‌مانید",
            "english_text": "If We willed, We could make it dry debris, and you would remain in wonder",
            "transliteration": "Law nashaaa’u laja’alnaahu hutaaman fazaltum tafakkahoon",
            "verse_number": "56:65",
        },
        {
            "arabic_text": "اِنَّا لَمُغْرَمُونَ",
            "urdu_text": "یقیناً ہم نقصان اٹھانے والے ہو گئے",
            "persian_text": "ما حتماً زیان دیده‌ایم",
            "english_text": "Indeed, we are [now] in debt [for what we have lost]",
            "transliteration": "Innaa lamughramoon",
            "verse_number": "56:66",
        },
        {
            "arabic_text": "بَلْ نَحْنُ مَحْرُومُونَ",
            "urdu_text": "بلکہ ہم تو محروم رہ گئے",
            "persian_text": "بلکه ما محروم مانده‌ایم",
            "english_text": "Rather, we have been deprived",
            "transliteration": "Bal nahnu mahroomoon",
            "verse_number": "56:67",
        },
        {
            "arabic_text": "اَفَرَءَيْتُمُ الْمَآءَ الَّذِى تَشْرَبُونَ",
            "urdu_text": "کیا تم نے اس پانی کو دیکھا جو تم پیتے ہو؟",
            "persian_text": "آیا به آبی که می‌نوشید نگریسته‌اید؟",
            "english_text": "Then have you seen the water that you drink?",
            "transliteration": "Afara’aytumul maaa’al lazee tashraboon",
            "verse_number": "56:68",
        },
        {
            "arabic_text": "ءَاَنتُمْ اَنزَلْتُمُوهُ مِنَ الْمُزْنِ اَمْ نَحْنُ الْمُنزِلُونَ",
            "urdu_text": "کیا تم نے اسے بادل سے اتارا ہے یا ہم اتارنے والے ہیں؟",
            "persian_text": "آیا شما آن را از ابر نازل کرده‌اید یا ما نازل‌کننده‌ایم؟",
            "english_text": "Is it you who brought it down from the clouds, or is it We who bring it down?",
            "transliteration": "A’antum anzaltumoohu minal muzni am nahnul munziloona",
            "verse_number": "56:69",
        },
        {
            "arabic_text": "لَوْ نَشَآءُ جَعَلْنَٰهُ اُجَاجٗا فَلَوْلَا تَشْكُرُونَ",
            "urdu_text": "اگر ہم چاہیں تو اسے کھارا بنا دیں، تو تم شکر کیوں نہیں کرتے؟",
            "persian_text": "اگر بخواهیم آن را شور می‌کنیم، پس چرا شکر نمی‌گزارید؟",
            "english_text": "If We willed, We could make it bitter, so why are you not grateful?",
            "transliteration": "Law nashaaa’u ja’alnaahu ujaajan falaawlaa tashkuroon",
            "verse_number": "56:70",
        },
        {
            "arabic_text": "اَفَرَءَيْتُمُ النَّارَ الَّتِى تُورُونَ",
            "urdu_text": "کیا تم نے اس آگ کو دیکھا جو تم بھڑکاتے ہو؟",
            "persian_text": "آیا به آتشی که می‌افروزید نگریسته‌اید؟",
            "english_text": "Have you seen the fire that you ignite?",
            "transliteration": "Afara’aytumu an-naaral-latee tooroon",
            "verse_number": "56:71",
        },
        {
            "arabic_text": "ءَاَنتُمْ اَنشَاْتُمْ شَجَرَتَهَآ اَمْ نَحْنُ الْمُنشِـُٔونَ",
            "urdu_text": "کیا تم نے اس کے درخت کو پیدا کیا ہے یا ہم پیدا کرنے والے ہیں؟",
            "persian_text": "آیا شما درخت آن را پدید آوردید یا ما پدید آورندگانیم؟",
            "english_text": "Is it you who produced its tree, or are We the producer?",
            "transliteration": "A’antum ansha’tum shajaratahaa am nahnul munshi’oon",
            "verse_number": "56:72",
        },
        {
            "arabic_text": "نَحْنُ جَعَلْنَٰهَا تَذْكِرَةٌ وَمَتَٰعٗا لِّلْمُقْوِينَ",
            "urdu_text": "ہم نے اسے نصیحت اور مسافروں کے لیے فائدہ مند بنایا",
            "persian_text": "ما آن را وسیله یادآوری و بهره‌ای برای مسافران قرار دادیم",
            "english_text": "We have made it a reminder and provision for the travelers",
            "transliteration": "Nahnu ja’alnaahaa tazkiratanw-wa mataa’al-lilmuqween",
            "verse_number": "56:73",
        },
        {
            "arabic_text": "فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيمِ",
            "urdu_text": "پس اپنے عظیم رب کے نام کی تسبیح کرو",
            "persian_text": "پس به نام پروردگار بزرگت تسبیح بگو",
            "english_text": "So exalt the name of your Lord, the Most Great",
            "transliteration": "Fasabbih bismi rabbikal ‘azeem",
            "verse_number": "56:74",
        },
        {
            "arabic_text": "فَلَآ اُقْسِمُ بِمَوَٰقِعِ النُّجُومِ",
            "urdu_text": "پس نہیں، میں قسم کھاتا ہوں ستاروں کے مقام کی",
            "persian_text": "نه، سوگند به جایگاه‌های ستارگان می‌خورم",
            "english_text": "But no! I swear by the positions of the stars",
            "transliteration": "Falaa uqsimu bimaawaaqi’in nujoom",
            "verse_number": "56:75",
        },
        {
            "arabic_text": "وَاِنَّهُ لَقَسَمٌ لَّوْ تَعْلَمُونَ عَظِيمٌ",
            "urdu_text": "اور بے شک یہ ایک عظیم قسم ہے اگر تم جان لو",
            "persian_text": "و همانا این سوگندی است بزرگ، اگر بدانید",
            "english_text": "And indeed, it is a great oath – if you could know",
            "transliteration": "Wa innahu laqasamul law ta’lamoona ‘azeem",
            "verse_number": "56:76",
        },
        {
            "arabic_text": "اِنَّهُ لَقُرْءَانٞ كَرِيمٌ",
            "urdu_text": "یقیناً یہ ایک باعزت قرآن ہے",
            "persian_text": "بی‌گمان این قرآن، قرآنی گرامی‌ست",
            "english_text": "Indeed, it is a noble Qur'an",
            "transliteration": "Innahoo laqur-aanun kareem",
            "verse_number": "56:77",
        },
        {
            "arabic_text": "فِى كِتَٰبٖ مَّكْنُونٖ",
            "urdu_text": "ایک محفوظ کتاب میں ہے",
            "persian_text": "در کتابی نهفته است",
            "english_text": "In a Register well-protected",
            "transliteration": "Fee kitaabim maknoon",
            "verse_number": "56:78",
        },
        {
            "arabic_text": "لَّا يَمَسُّهُٓ اِلَّا الْمُطَهَّرُونَ",
            "urdu_text": "اسے صرف پاک لوگ ہی چھو سکتے ہیں",
            "persian_text": "جز پاک‌شدگان آن را لمس نمی‌کنند",
            "english_text": "None touch it except the purified",
            "transliteration": "Laa yamassuhu illal mutahharoon",
            "verse_number": "56:79",
        },
        {
            "arabic_text": "تَنزِيلٞ مِّن رَّبِّ الْعَٰلَمِينَ",
            "urdu_text": "یہ رب العالمین کی طرف سے نازل کردہ ہے",
            "persian_text": "نازل شده از سوی پروردگار جهانیان است",
            "english_text": "A revelation from the Lord of the worlds",
            "transliteration": "Tanzeelum mir rabbil ‘aalameen",
            "verse_number": "56:80",
        },
        {
            "arabic_text": "اَفَبِهٰذَا الْحَدِيثِ اَنتُم مُّدْهِنُونَ",
            "urdu_text": "تو کیا تم اس کلام کو ہلکا لیتے ہو؟",
            "persian_text": "آیا شما این سخن را بی‌اهمیت می‌شمارید؟",
            "english_text": "Then is it to this statement that you are indifferent?",
            "transliteration": "Afabi haazal hadeesi antum mudhinoon",
            "verse_number": "56:81",
        },
        {
            "arabic_text": "وَتَجْعَلُونَ رِزْقَكُمْ اَنَّكُمْ تُكَذِّبُونَ",
            "urdu_text": "اور تم اپنے رزق کا انکار کرتے ہو؟",
            "persian_text": "و روزی خود را این می‌دانید که تکذیب می‌کنید؟",
            "english_text": "And make [the thanks for] your provision that you deny [the Provider]?",
            "transliteration": "Wa taj’aloona rizqakum annakum tukazziboon",
            "verse_number": "56:82",
        },
        {
            "arabic_text": "فَلَوْلَآ اِذَا بَلَغَتِ الْحُلْقُومَ",
            "urdu_text": "پھر کیوں نہیں، جب جان گلے تک پہنچتی ہے",
            "persian_text": "پس چرا هنگامی که جان به گلوگاه می‌رسد",
            "english_text": "Then why, when the soul reaches the throat",
            "transliteration": "Falaw laaa izaa balaghatil hulqoom",
            "verse_number": "56:83",
        },
        {
            "arabic_text": "وَاَنتُمْ حِينَئِذٖ تَنظُرُونَ",
            "urdu_text": "اور تم اُس وقت دیکھ رہے ہوتے ہو",
            "persian_text": "و شما در آن هنگام نظاره‌گر هستید",
            "english_text": "And you are at that time looking on",
            "transliteration": "Wa antum heena’izin tanziroon",
            "verse_number": "56:84",
        },
        {
            "arabic_text": "وَنَحْنُ اَقْرَبُ اِلَيْهِ مِنكُمْ وَلٰكِن لَّا تُبْصِرُونَ",
            "urdu_text": "اور ہم تم سے زیادہ اس کے قریب ہوتے ہیں، لیکن تم نہیں دیکھتے",
            "persian_text": "و ما به او نزدیک‌تریم از شما، ولی نمی‌بینید",
            "english_text": "And We are nearer to him than you, but you do not see",
            "transliteration": "Wa nahnu aqrabu ilaihi minkum wa laakil laa tubsiroon",
            "verse_number": "56:85",
        },
        {
            "arabic_text": "فَلَوْلَآ اِن كُنتُمْ غَيْرَ مَدِينِينَ",
            "urdu_text": "پھر کیوں نہیں، اگر تم جزا کے تابع نہیں ہو؟",
            "persian_text": "پس چرا اگر شما در برابر پاداش قرار ندارید؟",
            "english_text": "Then why do you not, if you are not to be recompensed,",
            "transliteration": "Falaw laaa in kuntum ghaira madeeneen",
            "verse_number": "56:86",
        },
        {
            "arabic_text": "تَرْجِعُونَهَآ اِن كُنتُمْ صَٰدِقِينَ",
            "urdu_text": "اس جان کو واپس لوٹا لاتے ہو اگر تم سچے ہو؟",
            "persian_text": "اگر راستگو هستید آن را بازگردانید",
            "english_text": "Bring it back, if you should be truthful",
            "transliteration": "Tarji’oonahaaa in kuntum saadiqeen",
            "verse_number": "56:87",
        },
        {
            "arabic_text": "فَاَمَّآ اِن كَانَ مِنَ الْمُقَرَّبِينَ",
            "urdu_text": "پس اگر وہ مقربین میں سے ہے",
            "persian_text": "پس اگر از مقربان باشد",
            "english_text": "And if the deceased was of those brought near to Allah,",
            "transliteration": "Fa ammaa in kaana minal muqarrabeen",
            "verse_number": "56:88",
        },
        {
            "arabic_text": "فَرَوْحٞ وَرَيْحَانٞ وَجَنَّتُ نَعِيمٍ",
            "urdu_text": "تو اس کے لیے راحت، خوشبو اور نعمتوں والی جنت ہے",
            "persian_text": "پس برای او آسایش و نعمت و بهشت پرنعمت خواهد بود",
            "english_text": "Then [for him is] rest and bounty and a garden of pleasure",
            "transliteration": "Farawhunw wa raihaanunw-wa jannatu na’eem",
            "verse_number": "56:89",
        },
        {
            "arabic_text": "وَاَمَّآ اِن كَانَ مِنْ اَصْحَٰبِ الْيَمِينِ",
            "urdu_text": "اور اگر وہ دائیں جانب والوں میں سے ہو",
            "persian_text": "و اگر از اصحاب یمین باشد",
            "english_text": "And if he was of the companions of the right",
            "transliteration": "Wa ammaa in kaana min ashaabil yameen",
            "verse_number": "56:90",
        },
        {
            "arabic_text": "فَسَلٰمٌ لَّكَ مِنْ اَصْحَٰبِ الْيَمِينِ",
            "urdu_text": "تو اس کے لیے دائیں جانب والوں کی طرف سے سلامتی ہے",
            "persian_text": "پس سلام بر تو از سوی اصحاب یمین",
            "english_text": "Then [the angels will say], 'Peace for you [from] the companions of the right'",
            "transliteration": "Fasalaamun laka min ashaabil yameen",
            "verse_number": "56:91",
        },
        {
            "arabic_text": "وَاَمَّآ اِن كَانَ مِنَ الْمُكَذِّبِينَ الضَّآلِّينَ",
            "urdu_text": "اور اگر وہ جھٹلانے والوں اور گمراہوں میں سے ہو",
            "persian_text": "و اگر از تکذیب‌کنندگان گمراه باشد",
            "english_text": "But if he was of the deniers [who were] astray,",
            "transliteration": "Wa ammaa in kaana minal mukazzibeenad daalleen",
            "verse_number": "56:92",
        },
        {
            "arabic_text": "فَنُزُلٞ مِّنْ حَمِيمٖ",
            "urdu_text": "تو اس کے لیے کھولتے پانی کی مہمانی ہے",
            "persian_text": "پس پذیرایی او از آب جوشان است",
            "english_text": "Then [for him is] accommodation of scalding water",
            "transliteration": "Fanuzulum min hameem",
            "verse_number": "56:93",
        },
        {
            "arabic_text": "وَتَصْلِيَةُ جَحِيمٍ",
            "urdu_text": "اور جہنم میں جلنا ہے",
            "persian_text": "و سوزاندن در آتش سوزان",
            "english_text": "And burning in Hellfire",
            "transliteration": "Wa tasliyatu jaheem",
            "verse_number": "56:94",
        },
        {
            "arabic_text": "اِنَّ هٰذَا لَهُوَ حَقُّ الْيَقِينِ",
            "urdu_text": "یقیناً یہ ہی یقینی سچائی ہے",
            "persian_text": "بی‌گمان این همان حقیقت قطعی است",
            "english_text": "Indeed, this is the true certainty",
            "transliteration": "Inna haazaa lahuwa haqqul yaqeen",
            "verse_number": "56:95",
        },
        {
            "arabic_text": "فَسَبِّحْ بِاسْمِ رَبِّكَ الْعَظِيمِ",
            "urdu_text": "پس اپنے عظیم رب کے نام کی تسبیح کرو",
            "persian_text": "پس به نام پروردگار بزرگت تسبیح گوی",
            "english_text": "So exalt the name of your Lord, the Most Great",
            "transliteration": "Fasabbih bismi rabbikal ‘azeem",
            "verse_number": "56:96",
        },
    ],
]
