ayats = [
    {
        "verse_number": 1,
        "arabic_text": "بِسْمِ اللّٰہِ الرَّحْمٰنِ الرَّحِیْمِ",
        "urdu_text": "خُدا کے نام سے جو بڑا مہربان نہایت رحم والا ہے",
        "persian_text": "به نام خداوند بخشنده مهربان",
        "english_text": "In the name of God, the Most Gracious, the Most Merciful",
        "transliteration": "Bismillāhi r-raḥmāni r-raḥīm",
    },
    {
        "verse_number": 2,
        "arabic_text": "الْـحَمْدُ لِلّٰہِ رَبِّ الْعٰلَمِیْنَ",
        "urdu_text": "سب تعریفیں خُدا ہی کے لیے ہیں جو سارے جہانوں کا پالنے والا ہے",
        "persian_text": "ستایش مخصوص خداوندی است که پروردگار جهانیان است",
        "english_text": "All praise is for God, Lord of all the worlds",
        "transliteration": "Al-ḥamdu lillāhi rabbil-ʿālamīn",
    },
    {
        "verse_number": 3,
        "arabic_text": "الرَّحْمٰنِ الرَّحِیْمِ",
        "urdu_text": "جو بڑا مہربان نہایت رحم والا ہے",
        "persian_text": "بخشنده مهربان",
        "english_text": "The Most Gracious, the Most Merciful",
        "transliteration": "Ar-raḥmāni r-raḥīm",
    },
    {
        "verse_number": 4,
        "arabic_text": "مٰلِكِ یَوْمِ الدِّیْنِ",
        "urdu_text": "روزِ جزا کا مالک ہے",
        "persian_text": "مالک روز پاداش است",
        "english_text": "Master of the Day of Judgment",
        "transliteration": "Māliki yawmid-dīn",
    },
    {
        "verse_number": 5,
        "arabic_text": "اِیَّاكَ نَعْبُدُ وَ اِیَّاكَ نَسْتَعِیْنُ",
        "urdu_text": "ہم تیری ہی عبادت کرتے ہیں اور تجھ ہی سے مدد چاہتے ہیں",
        "persian_text": "تنها تو را می‌پرستیم و تنها از تو یاری می‌جوییم",
        "english_text": "You alone we worship, and You alone we ask for help",
        "transliteration": "Iyyāka naʿbudu wa iyyāka nastaʿīn",
    },
    {
        "verse_number": 6,
        "arabic_text": "اِهْدِنَا الصِّرَاطَ الْمُسْتَقِیْمَ",
        "urdu_text": "ہمیں سیدھا راستہ دکھا",
        "persian_text": "ما را به راه راست هدایت فرما",
        "english_text": "Guide us on the Straight Path",
        "transliteration": "Ihdinaṣ-ṣirāṭ al-mustaqīm",
    },
    {
        "verse_number": 7,
        "arabic_text": "صِرَاطَ الَّذِیْنَ اَنْعَمْتَ عَلَیْهِمْ غَیْرِ الْمَغْضُوْبِ عَلَیْهِمْ وَ لَا الضَّآلِّیْنَ",
        "urdu_text": "ان لوگوں کا راستہ جن پر تونے اپنے نعمت عطا کی ہے ، انکا راستہ نہیں جن پر غضب نازل ہوا ہے یا جو گمراہ ہوے ہیں",
        "persian_text": "راه کسانی که به آنان نعمت دادی، نه کسانی که خشمگین شدند و نه گمراهان",
        "english_text": "The path of those You have blessed, not of those who earned Your anger or went astray",
        "transliteration": "Ṣirāṭ al-ladhīna anʿamta ʿalayhim ghayril-maghḍūbi ʿalayhim walāḍ-ḍāllīn",
    },
]
