ayats = [
    {
        "verse_number": "1",
        "arabic_text": "الٓرٰ ۗ تِلْكَ اٰيٰتُ الْكِتٰبِ الْحَكِيمِ",
        "urdu_text": "الف، لام، را۔ یہ حکمت والی کتاب کی اٰیات ہیں۔",
        "persian_text": "الف، لام، را. این اٰیات کتاب حکیم است.",
        "english_text": "Alif, Lam, Ra. These are the verses of the Wise Book.",
        "transliteration": "Alif-Lām-Rā tilka āyātu l-kitābi l-ḥakīm",
    },
    {
        "verse_number": "2",
        "arabic_text": "اَكَانَ لِلنَّاسِ عَجَبًا اَنْ اَوْحَيْنَا اِلَىٰ رَجُلٍ مِّنْهُمْ اَنْ اَنْذِرِ النَّاسَ وَ بَشِّرِ الَّذِيْنَ اٰمَنُوْا اَنَّ لَهُمْ قَدَمَ صِدْقٍ عِنْدَ رَبِّهِمْ  قَالَ الْكٰفِرُوْنَ اِنَّ هٰذَا لَسٰحِرٌ مُبِيْنٌ",
        "urdu_text": "کیا لوگوں کے لئے یہ تعجب کی بات ہے کہ ہم نے انہی میں سے ایک مرد پر وحی نازل کی کہ لوگوں کو ڈراؤ اور ایمان لانے والوں کو خوشخبری دو کہ ان کے لئے ان کے رب کے پاس سچی عظمت ہے۔ کافروں نے کہا: یہ تو کھلا جادوگر ہے۔",
        "persian_text": "اٰیا برای مردم شگفت اٰور است که به مردی از میانشان وحی کردیم که مردم را بیم ده و مؤمنان را بشارت ده که برای اٰنان نزد پروردگارشان مقامی راستین است؟ کافران گفتند: این شخص جادوگری اٰشکار است.",
        "english_text": "Is it a wonder for the people that We revealed to a man from among them, 'Warn the people and give glad tidings to those who believe that they will have a true standing with their Lord'? The disbelievers said, 'Indeed, this is an obvious magician.'",
        "transliteration": "Akāna li-nnāsi ʿajaban an awḥaynā ilā rajulin minhum an anḏiri n-nāsa wa-bashiri llaḏīna āmanū anna lahum qadam ṣidqin ʿinda rabbihim qāla l-kāfirūna inna hādhā lasāḥirun mubīn",
    },
    {
        "verse_number": "3",
        "arabic_text": "اِنَّ رَبَّكُمُ اللّٰهُ الَّذِي خَلَقَ السَّمٰوٰتِ وَ الْاَرْضَ فِي سِتَّةِ اَيَّامٍ ثُمَّ اسْتَوٰى عَلَى الْعَرْشِ يُدَبِّرُ الْاَمْرَ ۖ مَا مِنْ شَفِيعٍ اِلَّا مِنْ بَعْدِ اِذْنِهِ ۚ ذٰلِكُمُ اللّٰهُ رَبُّكُمْ فَاعْبُدُوهُ ۚ اَفَلَا تَذَكَّرُونَ",
        "urdu_text": "بیشک تمہارا پروردگار اللہ ہے جس نے اٰسمانوں اور زمین کو چھ دن میں پیدا کیا، پھر عرش پر قائم ہوا۔ وہی نظام چلا رہا ہے۔ اس کی اجازت کے بغیر کوئی سفارش کرنے والا نہیں۔ یہی اللہ تمہارا پروردگار ہے، پس تم اس کی عبادت کرو۔ کیا تم نصیحت نہیں لیتے؟",
        "persian_text": "پروردگار شما خداوندی است که اٰسمان‌ها و زمین را در شش روز اٰفرید، سپس بر عرش استیلا یافت. او کارها را تدبیر می‌کند. هیچ شفاعت‌کننده‌ای جز به اذن او نیست. این است خدا پروردگار شما، پس او را بپرستید. اٰیا پند نمی‌گیرید؟",
        "english_text": "Indeed, your Lord is Allah, who created the heavens and the earth in six days, then established Himself above the Throne. He manages all affairs. No intercessor can intercede except after His permission. That is Allah, your Lord, so worship Him. Will you not take heed?",
        "transliteration": "Inna rabbakumu llāhu llaḏī khalaqa s-samāwāti wa-l-arḍa fī sittati ayyāmin ṯumma stawā ʿalā l-ʿarshi yudabbiru l-amra mā min shafīʿin illā min baʿdi iḏnih dhālikumu llāhu rabbukum fa-ʿbudūhu afalā tadhakkarūn",
    },
    {
        "verse_number": "4",
        "arabic_text": "اِلَيْهِ مَرْجِعُكُمْ جَمِيعًا  وَعْدَ اللّٰهِ حَقًّا ۚ اِنَّهُ يَبْدَؤُا الْخَلْقَ ثُمَّ يُعِيْدُهُ لِيَجْزِيَ الَّذِيْنَ اٰمَنُوْا وَ عَمِلُوْا الصّٰلِحٰتِ بِالْقِسْطِ ۚ وَ الَّذِينَ كَفَرُوا لَهُمْ شَرَابٌ مِنْ حَمِيمٍ وَ عَذَابٌ اَلِيمٌ بِمَا كَانُوا يَكْفُرُونَ",
        "urdu_text": "تم سب کو اسی کی طرف لوٹنا ہے۔ اللہ کا وعدہ سچا ہے۔ وہ پہلی بار پیدا کرتا ہے پھر دوبارہ زندہ کرے گا تاکہ ایمان لانے والوں اور نیک اعمال کرنے والوں کو انصاف کے ساتھ بدلہ دے۔ اور کافروں کے لئے کھولتا ہوا پانی اور دردناک عذاب ہے ان کے کفر کی وجہ سے۔",
        "persian_text": "بازگشت همه شما به سوی اوست. وعده خداوند حق است. او اٰفرینش را اٰغاز می‌کند سپس اٰن را بازمی‌گرداند تا کسانی را که ایمان اٰوردند و کارهای شایسته انجام دادند، به عدالت پاداش دهد. و کسانی که کافر شدند، برای اٰنان نوشیدنی از اٰب جوشان و عذابی دردناک خواهد بود.",
        "english_text": "To Him is your return, all of you. The promise of Allah is true. Indeed, He originates creation, then will repeat it, that He may reward those who believed and did righteous deeds with justice. But those who disbelieved will have a drink of scalding water and a painful punishment for their disbelief.",
        "transliteration": "Ilayhi marjiʿukum jamīʿan waʿda llāhi ḥaqqan innahu yabdaʾu l-khalqa ṯumma yuʿīduhu liyajziya llaḏīna āmanū wa-ʿamilū ṣ-ṣāliḥāti bil-qisṭi wa-llaḏīna kafarū lahum sharābun min ḥamīmin wa-ʿaḏābun alīmun bimā kānū yakfurūn",
    },
    {
        "verse_number": "5",
        "arabic_text": "هُوَ الَّذِي جَعَلَ الشَّمْسَ ضِيَآءً وَّ الْقَمَرَ نُوْرًا وَّ قَدَّرَهُ مَنَازِلَ لِتَعْلَمُوا عَدَدَ السِّنِيْنَ وَ الْحِسَابَ ۚ مَا خَلَقَ اللّٰهُ ذٰلِكَ اِلَّا بِالْحَقِّ ۚ يُفَصِّلُ الْاٰيٰتِ لِقَوْمٍ يَّعْلَمُونَ",
        "urdu_text": "وہی ہے جس نے سورج کو روشنی بنایا اور چاند کو نور قرار دیا اور اس کے لئے منزلیں مقرر کیں تاکہ تم برسوں کی گنتی اور حساب معلوم کرسکو۔ اللہ نے یہ سب کچھ برحق پیدا کیا ہے۔ وہ اپنی اٰیتیں ان لوگوں کے لئے کھول کر بیان کرتا ہے جو علم رکھتے ہیں۔",
        "persian_text": "او کسی است که خورشید را روشنایی و ماه را نور قرار داد و برای اٰن منزلگاه‌هایی تعیین کرد تا شماره سال‌ها و حساب را بدانید. خداوند این را جز به حق نیافرید. او اٰیات خود را برای مردمی که می‌دانند، به تفصیل بیان می‌کند.",
        "english_text": "It is He who made the sun a shining light and the moon a derived light, and determined phases for it so that you may know the number of years and the calculation. Allah did not create this except in truth. He details the signs for a people who know.",
        "transliteration": "Huwa lladhī jaʿala sh-shamsa ḍiyāʾan wa-l-qamara nūran wa-qaddarahu manāzila litaʿlamū ʿadada s-sinīna wa-l-ḥisāba mā khalaqa llāhu dhālika illā bil-ḥaqqi yufaṣṣilu l-āyāti li-qawmin yaʿlamūn",
    },
    {
        "verse_number": "6",
        "arabic_text": "اِنَّ فِي اخْتِلَافِ الَّيْلِ وَ النَّهَارِ وَ مَا خَلَقَ اللّٰهُ فِي السَّمٰوٰتِ وَ الْاَرْضِ لَاٰيٰتٍ لِقَوْمٍ يَّتَّقُوْنَ",
        "urdu_text": "بیشک رات اور دن کے فرق اور جو کچھ اللہ نے اٰسمانوں اور زمین میں پیدا کیا ہے، ان سب میں ان لوگوں کے لئے نشانیاں ہیں جو پرہیزگار ہیں۔",
        "persian_text": "به یقین، در اٰمد و شد شب و روز و در اٰنچه خدا در اٰسمان‌ها و زمین اٰفریده است، نشانه‌هایی است برای مردمی که پرهیزگارند.",
        "english_text": "Indeed, in the alternation of the night and the day and in what Allah has created in the heavens and the earth are signs for a people who fear Him.",
        "transliteration": "Inna fī ikhtilāfi l-layli wa-n-nahāri wa-mā khalaqa llāhu fī s-samāwāti wa-l-arḍi la-āyātin li-qawmin yattaqūn",
    },
    {
        "verse_number": "7",
        "arabic_text": "اِنَّ الَّذِيْنَ لَا يَرْجُونَ لِقَآءَنَا وَ رَضُوا بِالْحَيٰوةِ الدُّنْيَا وَ اطْمَاَنُّوْا بِهَا وَ الَّذِيْنَ هُمْ عَنْ اٰيٰتِنَا غٰفِلُوْنَ",
        "urdu_text": "بیشک وہ لوگ جو ہم سے ملاقات کی امید نہیں رکھتے اور دنیاوی زندگی پر راضی ہوگئے اور اسی پر مطمئن ہوگئے اور وہ لوگ جو ہماری اٰیتوں سے غافل ہیں۔",
        "persian_text": "کسانی که به دیدار ما امید ندارند و به زندگی دنیا خشنود شده و به اٰن دل بسته‌اند و کسانی که از اٰیات ما غافلند.",
        "english_text": "Indeed, those who do not expect to meet Us and are satisfied with the worldly life and feel secure in it, and those who are heedless of Our signs.",
        "transliteration": "Inna lladhīna lā yarjūna liqāʾanā wa-raḍū bil-ḥayāti d-dunyā wa-ṭmaʾannū bihā wa-lladhīna hum ʿan āyātinā ghāfilūn",
    },
    {
        "verse_number": "8",
        "arabic_text": "اُولٰٓئِكَ مَاْوٰهُمُ النَّارُ بِمَا كَانُوا يَكْسِبُوْنَ",
        "urdu_text": "یہی لوگ ہیں جن کا ٹھکانا جہنم ہے، ان کے اعمال کی وجہ سے جو وہ کماتے تھے۔",
        "persian_text": "اٰنان جایگاهشان اٰتش است به سبب اٰنچه به دست می‌اٰوردند.",
        "english_text": "It is they whose abode will be the Fire, because of what they used to earn.",
        "transliteration": "Ūlāʾika maʾwāhumu n-nāru bimā kānū yaksibūn",
    },
    {
        "verse_number": "9",
        "arabic_text": "اِنَّ الَّذِيْنَ اٰمَنُوا وَ عَمِلُوا الصّٰلِحٰتِ يَهْدِيْهِمْ رَبُّهُمْ بِاِيْمَانِهِمْ ۖ تَجْرِي مِنْ تَحْتِهِمُ الْاَنْهٰرُ فِي جَنّٰتِ النَّعِيمِ",
        "urdu_text": "بیشک وہ لوگ جو ایمان لائے اور نیک عمل کئے، ان کے ایمان کے سبب ان کا رب انہیں ہدایت دیتا ہے۔ ان کے نیچے نعمتوں کے باغوں میں نہریں بہتی ہوں گی۔",
        "persian_text": "کسانی که ایمان اٰوردند و کارهای شایسته انجام دادند، پروردگارشان به سبب ایمانشان اٰنان را هدایت می‌کند. در باغ‌های پرنعمت نهرها از زیر پایشان جاری است.",
        "english_text": "Indeed, those who have believed and done righteous deeds – their Lord will guide them because of their faith. Rivers will flow beneath them in Gardens of Bliss.",
        "transliteration": "Inna lladhīna āmanū wa-ʿamilū ṣ-ṣāliḥāti yahdīhim rabbuhum bi-īmānihim tajrī min taḥtihimu l-anhāru fī jannāti n-naʿīm",
    },
    {
        "verse_number": "10",
        "arabic_text": "دَعْوٰهُمْ فِيهَا سُبْحٰنَكَ اللّٰهُمَّ وَ تَحِيَّتُهُمْ فِيْهَا سَلٰمٌ ۚ وَ اٰخِرُ دَعْوٰهُمْ اَنِ الْحَمْدُ لِلَّهِ رَبِّ الْعٰلَمِيْنَ",
        "urdu_text": "وہاں ان کی دعا یہ ہوگی: اے اللہ! تو پاک ہے۔ اور ان کی دعا کا جواب سلام ہوگا۔ اور ان کی اٰخری دعا یہ ہوگی کہ سب تعریف اللہ کے لئے ہے جو سارے جہانوں کا پروردگار ہے۔",
        "persian_text": "دعای اٰنان در اٰنجا این است: «خدایا! تو منزهی». و درودشان در اٰنجا «سلام» است. و پایان دعایشان این است: «ستایش ویژه خدا، پروردگار جهانیان است».",
        "english_text": "Their prayer therein will be, 'Exalted are You, O Allah!' and their greeting therein will be, 'Peace.' And the last of their call will be, 'Praise be to Allah, Lord of the worlds!'",
        "transliteration": "Daʿwāhum fīhā subḥānaka llāhumma wa-taḥiyyatuhum fīhā salāmun wa-ākhiru daʿwāhum ani l-ḥamdu lillāhi rabbi l-ʿālamīn",
    },
    {
        "verse_number": "11",
        "arabic_text": " وَ لَوْ يُعَجِّلُ اللّٰهُ لِلنَّاسِ الشَّرَّ اسْتِعْجَالَهُم بِالْخَيْرِ لَقُضِىَ اِلَيْهِمْ اَجَلُهُمْ ۖ فَنَذَرُ الَّذِينَ لَا يَرْجُونَ لِقَآءَنَا فِى طُغْيٰنِهِمْ يَعْمَهُوْنَ",
        "urdu_text": "اور اگر اللہ لوگوں کے لیے برائی کو اسی طرح جلدی کر دیتا جس طرح وہ بھلائی کے لیے جلدی کرتے ہیں تو ان کی میعاد پوری ہو چکی ہوتی۔ پس ہم ان لوگوں کو جو ہم سے ملنے کی امید نہیں رکھتے اپنی سرکشی میں بھٹکتے چھوڑ دیتے ہیں۔",
        "persian_text": "و اگر خداوند برای مردم بدی را به همان شتابی که برای خیر شتاب می‌کنند، عجله می‌کرد، قطعاً اجلشان به پایان می‌رسید. پس کسانی را که به ملاقات ما امید ندارند، در طغیانشان سرگردان می‌گذاریم.",
        "english_text": "And if Allah were to hasten for the people the evil [they invoke] as He hastens for them the good, their term would have been ended for them. But We leave those who do not expect the meeting with Us, in their transgression, wandering blindly.",
        "transliteration": "Wa law yu'ajjilullahu linnaasi ash-sharra isti'jaalahum bil-khayri laqudiya ilayhim ajaluhum; fanazarul-lazeena laa yarjoona liqaa'anaa fee tughyaanihim ya'mahoon",
    },
    {
        "verse_number": "12",
        "arabic_text": "وَ اِذَا مَسَّ الْاِنسَانَ الضُّرُّ دَعَانَا لِجَنۢبِهِ اَوْ قَاعِدًا اَوْ قَآئِمًا فَلَمَّا كَشَفْنَا عَنْهُ ضُرَّهُ مَرَّ كَاَنْ لَّمْ يَدْعُنَآ اِلَىٰ ضُرٍّ مَّسَّهُ ۚ كَذٰلِكَ زُيِّنَ لِلْمُسْرِفِيْنَ مَا كَانُوا يَعْمَلُونَ",
        "urdu_text": "اور جب انسان کو کوئی تکلیف پہنچتی ہے تو وہ ہمیں پکارتا ہے خواہ لیٹے ہوئے ہو یا بیٹھے ہوئے یا کھڑے ہوئے۔ پھر جب ہم اس کی تکلیف دور کر دیتے ہیں تو وہ اس طرح چلا جاتا ہے گویا اس نے ہمیں اس تکلیف کے لیے جو اسے پہنچی تھی پکارا ہی نہیں تھا۔ اسی طرح حد سے بڑھنے والوں کے لیے ان کے اعمال مزین کر دیے گئے ہیں۔",
        "persian_text": "و هنگامی که انسان را رنجی رسد، ما را می‌خواند، خواه به پهلو خوابیده باشد یا نشسته یا ایستاده. اما چون رنجش را از او برطرف کنیم، چنان می‌گذرد که گویی هرگز ما را برای رنجی که به او رسیده بود، نخوانده است. این‌چنین برای اسراف‌کاران، اعمالشان زینت داده شده است.",
        "english_text": "And when affliction touches man, he calls upon Us, whether lying on his side or sitting or standing; but when We remove from him his affliction, he continues as if he had never called upon Us to remove an affliction that touched him. Thus is made pleasing to the transgressors that which they have been doing.",
        "transliteration": "Wa izaa massal-insaana ad-durru da'aanaa lijanbiheee aw qaa'idan aw qaaa'imaa; falammaa kashafnaa 'anhu durrahoo marra ka-al lam yad'unaaa ilaa durrim massahoo; kazaalika zuyyina lilmusrifeena maa kaanoo ya'maloon",
    },
    {
        "verse_number": "13",
        "arabic_text": "وَ لَقَدْ اَهْلَكْنَا الْقُرُوْنَ مِنْ قَبْلِكُمْ لَمَّا ظَلَمُوا ۙ وَ جَآءَتْهُمْ رُسُلُهُمْ بِالْبَيِّنٰتِ وَ مَا كَانُوا لِيُؤْمِنُوا ۚ كَذٰلِكَ نَجْزِى الْقَوْمَ الْمُجْرِمِيْنَ",
        "urdu_text": "اور البتہ ہم نے تم سے پہلے کی قوموں کو ہلاک کر دیا جب انہوں نے ظلم کیا اور ان کے پاس ان کے رسول واضح نشانیاں لے کر آئے تھے اور وہ ایمان لانے والے نہ تھے۔ اسی طرح ہم مجرم قوم کو سزا دیتے ہیں۔",
        "persian_text": "و قطعاً قرون پیش از شما را هنگامی که ستم کردند، هلاک ساختیم، و پیامبرانشان دلایل روشن برایشان آوردند ولی آنان ایمان نمی‌آوردند. این‌چنین قوم مجرمان را جزا می‌دهیم.",
        "english_text": "And We had certainly destroyed generations before you when they wronged, and their messengers had come to them with clear proofs, but they were not to believe. Thus do We recompense the criminal people.",
        "transliteration": "Wa laqad ahlaknaal-quroona min qablikum lammaa zhalamoo wa jaaa'at-hum rusuluhum bil-bayyinaati wa maa kaanoo liyu'minoo; kazaalika najzil-qawmal-mujrimeen",
    },
    {
        "verse_number": "14",
        "arabic_text": "ثُمَّ جَعَلْنٰكُمْ خَلٰٓئِفَ فِى الْاَرْضِ مِنۢ بَعْدِهِمْ لِنَنظُرَ كَيْفَ تَعْمَلُوْنَ",
        "urdu_text": "پھر ہم نے تمہیں ان کے بعد زمین میں جانشین بنایا تاکہ دیکھیں کہ تم کیسے عمل کرتے ہو۔",
        "persian_text": "سپس شما را پس از آنان در زمین جانشین قرار دادیم تا ببینیم چگونه عمل می‌کنید.",
        "english_text": "Then We made you successors in the land after them so that We may observe how you will do.",
        "transliteration": "Thumma ja'alnaakum khalaaa'ifa fil-ardi mim ba'dihim linanzura kayfa ta'maloon",
    },
    {
        "verse_number": "15",
        "arabic_text": "وَ اِذَا تُتْلَىٰ عَلَيْهِمْ اٰيٰتُنَا بَيِّنٰتٍ ۙ قَالَ الَّذِينَ لَا يَرْجُونَ لِقَآءَنَا ائْتِ بِقُرْاٰنٍ غَيْرِ هٰذَآ اَوْ بَدِّلْهُ ۚ قُلْ مَا يَكُونُ لِىْٓ اَنْ اُبَدِّلَهُ مِن تِلْقَآئِ نَفْسِىٓ ۖ اِنْ اَتَّبِعُ اِلَّا مَا يُوحَىٰٓ اِلَىَّ ۖ اِنِّىٓ اَخَافُ اِنْ عَصَيْتُ رَبِّى عَذَابَ يَوْمٍ عَظِيمٍ",
        "urdu_text": "اور جب ان پر ہماری آیتیں واضح طور پر پڑھی جاتی ہیں تو وہ لوگ جو ہم سے ملنے کی امید نہیں رکھتے کہتے ہیں کہ اس کے علاوہ کوئی اور قرآن لے آؤ یا اس میں تبدیلی کر دو۔ کہہ دو کہ یہ میرے لیے ممکن نہیں کہ میں اپنی طرف سے اس میں تبدیلی کروں۔ میں تو صرف اس کی پیروی کرتا ہوں جو میری طرف وحی کیا جاتا ہے۔ بیشک اگر میں اپنے رب کی نافرمانی کروں تو مجھے ایک عظیم دن کے عذاب کا ڈر ہے۔",
        "persian_text": "و هنگامی که آیات روشن ما بر آنان خوانده شود، کسانی که به ملاقات ما امید ندارند می‌گویند: قرآنی غیر از این بیاور یا آن را تغییر ده. بگو: برای من نیست که از پیش خود آن را تغییر دهم. من جز آنچه به من وحی می‌شود پیروی نمی‌کنم. من اگر پروردگارم را نافرمانی کنم، از عذاب روزی بزرگ می‌ترسم.",
        "english_text": "And when Our verses are recited to them as clear evidences, those who do not expect the meeting with Us say, 'Bring us a Qur'an other than this or change it.' Say, 'It is not for me to change it on my own accord. I only follow what is revealed to me. Indeed I fear, if I should disobey my Lord, the punishment of a tremendous Day.'",
        "transliteration": "Wa izaa tutlaa 'alayhim aayaatunaa bayyinaatin qaalal-lazeena laa yarjoona liqaaa'anab'ti biqur'aanin ghayri haazaaa aw baddilh; qul maa yakoonu leee an ubaddilahoo min tilqaaa'i nafsee in attabi'u illaa maa yoohaaa ilayy; inneee akhaafu in 'asaytu Rabbee 'azaaba yawmin 'azheem",
    },
    {
        "verse_number": "16",
        "arabic_text": "قُل لَّوْ شَآءَ اللّٰهُ مَا تَلَوْتُهُ عَلَيْكُمْ وَ لَآ اَدْرٰكُم بِهِ ۖ فَقَدْ لَبِثْتُ فِيْكُمْ عُمُرًا مِّن قَبْلِهِ ۚ اَفَلَا تَعْقِلُوْنَ",
        "urdu_text": "کہہ دو کہ اگر اللہ چاہتا تو میں تمہیں یہ نہ پڑھ کر سناتا اور نہ وہ تمہیں اس سے آگاہ کرتا۔ بیشک میں اس سے پہلے تم میں ایک عمر رہ چکا ہوں۔ تو کیا تم عقل نہیں رکھتے؟",
        "persian_text": "بگو: اگر خدا می‌خواست، آن را بر شما نمی‌خواندم و شما را از آن آگاه نمی‌کرد. من پیش از آن مدتی از عمر در میان شما بوده‌ام. آیا تعقل نمی‌کنید؟",
        "english_text": "Say, 'If Allah had willed, I would not have recited it to you, nor would He have made it known to you, for I had remained among you a lifetime before it. Then will you not reason?'",
        "transliteration": "Qul law shaaa'allaahu maa talawtuhu 'alaykum wa laaa adraakum bih; faqad labithtu feekum 'umuran min qablih; afalaa ta'qiloon",
    },
    {
        "verse_number": "17",
        "arabic_text": "فَمَنْ اَظْلَمُ مِمَّنِ افْتَرَىٰ عَلَى اللّٰهِ كَذِبًا اَوْ كَذَّبَ بِاٰيٰتِهِ ۚ اِنَّهُ لَا يُفْلِحُ الْمُجْرِمُونَ",
        "urdu_text": "پھر اس سے بڑھ کر ظالم کون ہے جس نے اللہ پر جھوٹ باندھا یا اس کی آیتوں کو جھٹلایا۔ بیشک مجرم لوگ فلاح نہیں پاتے۔",
        "persian_text": "پس چه کسی ستمکارتر است از آن که بر خدا دروغ بندد یا آیات او را تکذیب کند؟ به راستی مجرمان رستگار نمی‌شوند.",
        "english_text": "So who is more unjust than he who invents a lie about Allah or denies His signs? Indeed, the criminals will not succeed.",
        "transliteration": "Faman azhlamu mimmanif-taraa 'alaallaahi kaziban aw kazzaba bi-aayaatih; innahoo laa yuflihul-mujrimoon",
    },
    {
        "verse_number": "18",
        "arabic_text": "وَ يَعْبُدُوْنَ مِنْ دُوْنِ اللّٰهِ مَا لَا يَضُرُّهُمْ وَ لَا يَنْفَعُهُمْ وَ يَقُوْلُوْنَ هٰٓؤُلَآءِ شُفَعٰٓؤُنَا عِنْدَ اللّٰهِ ۚ قُلْ اَتُنَبِّئُونَ اللّٰهَ بِمَا لَا يَعْلَمُ فِى السَّمٰوٰتِ وَ لَا فِى الْاَرْضِ ۚ سُبْحٰنَهُۥ وَ تَعٰلٰى عَمَّا يُشْرِكُوْنَ",
        "urdu_text": "اور وہ اللہ کے سوا ان چیزوں کی عبادت کرتے ہیں جو نہ انہیں نقصان پہنچا سکتی ہیں اور نہ فائدہ دے سکتی ہیں اور کہتے ہیں کہ یہ اللہ کے پاس ہمارے سفارشی ہیں۔ کہہ دو کیا تم اللہ کو ایسی چیز کی خبر دیتے ہو جسے وہ نہ آسمانوں میں جانتا ہے اور نہ زمین میں؟ وہ پاک ہے اور بلند ہے اس سے جو یہ شریک ٹھہراتے ہیں۔",
        "persian_text": "و آنان غیر از خدا، چیزهایی را می‌پرستند که نه زیانی به آنان می‌رساند و نه سودی، و می‌گویند: اینان شفیعان ما نزد خدایند. بگو: آیا خدا را از چیزی خبر می‌دهید که او در آسمان‌ها و زمین نمی‌داند؟ منزه و برتر است او از آنچه شریک می‌گیرند.",
        "english_text": "And they worship besides Allah that which neither harms them nor benefits them, and they say, 'These are our intercessors with Allah.' Say, 'Do you inform Allah of something He does not know in the heavens or on the earth?' Exalted is He and high above what they associate with Him.",
        "transliteration": "Wa ya'budoona min doonillaahi maa laa yadurruhum wa laa yanfa'uhum wa yaqooloona haaa'ulaaa'i shufa'aaa'unaa 'indallaah; qul atunabi'oonallaaha bimaa laa ya'lamu fis-samaawaati wa laa fil-ard; Subhaanahoo wa Ta'aalaa 'ammaa yushrikoon",
    },
    {
        "verse_number": "19",
        "arabic_text": "وَ مَا كَانَ النَّاسُ اِلَّآ اُمَّةً وٰحِدَةً فَاخْتَلَفُوا ۚ وَ لَوْلَا كَلِمَةٌ سَبَقَتْ مِن رَّبِّكَ لَقُضِىَ بَيْنَهُمْ فِيْمَا فِيْهِ يَخْتَلِفُوْنَ",
        "urdu_text": "اور لوگ ایک ہی امت تھے پھر انہوں نے اختلاف کیا۔ اور اگر تمہارے رب کی طرف سے ایک بات پہلے نہ ہو چکی ہوتی تو ان کے درمیان اسی چیز میں فیصلہ کر دیا جاتا جس میں وہ اختلاف کرتے ہیں۔",
        "persian_text": "و مردم جز یک امت واحد نبودند، پس اختلاف کردند. و اگر کلمه‌ای از پروردگارت پیش نیامده بود، قطعاً در آنچه در آن اختلاف می‌کردند، میانشان داوری می‌شد.",
        "english_text": "And mankind was not but one community, but then they differed. And if not for a word that preceded from your Lord, it would have been judged between them concerning that over which they differ.",
        "transliteration": "Wa maa kaanan-naasu illaa ummatanw-waahidatan fakhtalafu; wa law laa kalimatun sabaqat mir-Rabbika laqudiya baynahum feemaa feehi yakhtalifoon",
    },
    {
        "arabic_text": "وَ يَقُولُونَ لَوْلَا اُنْزِلَ عَلَيْهِ اٰيَةٌ مِّنْ رَّبِّهِ ۖ فَقُلْ اِنَّمَا الْغَيْبُ لِلَّهِ فَانْتَظِرُوْا اِنِّي مَعَكُم مِّنَ الْمُنْتَظِرِيْنَ",
        "urdu_text": "اور یہ کہتے ہیں کہ اس پر اس کے رب کی طرف سے کوئی نشانی کیوں نازل نہیں ہوئی، پس اٰپ کہہ دیجیے کہ غیب تو صرف اللہ کے لیے ہے پس انتظار کرو، میں بھی تمہارے ساتھ انتظار کرنے والوں میں سے ہوں",
        "persian_text": "و می‌گویند چرا از سوی پروردگارش اٰیه‌ای بر او نازل نشده، پس بگو غیب مخصوص خداست، پس انتظار کشید که من نیز با شما از انتظارکشندگان هستم",
        "english_text": "And they say: Why is not a portent sent down upon him from his Lord? Then say (O Muhammad): The Unseen belongs to Allah. So wait! Lo, I am waiting with you",
        "transliteration": "Wa yaquluna law-la unzila 'alayhi ayatun min rabbihi fa-qul innama al-ghaybu lillahi fa-ntaziru inni ma'akum min al-muntazirin",
        "verse_number": "10:20",
    },
    {
        "arabic_text": "اَفَقَدَ النَّاسُ رَحْمَةَ قَبْلَهُ مِن بَعْدِ مَا مَسَّهُمُ الضُّرُّ اِذَا لَهُم مَّكْرٌ فِي اٰيٰتِنَا ۚ قُلِ اللّٰهُ اَسْرَعُ مَكْرًا ۚ اِنَّ رُسُلَنَا يَكْتُبُونَ مَا تَمْكُرُونَ",
        "urdu_text": "پھر جب لوگوں کو نقصان پہنچنے کے بعد رحمت کا مزہ چکھایا جاتا ہے تو فوراً وہ ہماری اٰیات میں چالبازی کرنے لگتے ہیں، کہہ دیجیے کہ اللہ بہت جلد چال چلنے والا ہے، بے شک ہمارے فرشتے لکھ رہے ہیں جو کچھ تم مکر کر رہے ہو",
        "persian_text": "پس چون مردم را پس از اٰنکه رنج بدیشان رسید، رحمتی چشانده شود، ناگاه در اٰیات ما مکر می‌کنند، بگو خدا سریعترین مکرکنندگان است، همانا فرستادگان ما می‌نویسند اٰنچه را مکر می‌کنید",
        "english_text": "And when We cause mankind to taste of mercy after some adversity which had afflicted them, behold! they have some plot against Our revelations. Say: Allah is more swift in plotting. Lo! Our messengers write down that which ye plot",
        "transliteration": "Afaqad an-naas rahmatan min ba'di ma massahum ad-durr idha lahum makrun fi ayatina qul Allahu asra'u makran inna rusulana yaktubuna ma tamkurun",
        "verse_number": "10:21",
    },
    {
        "arabic_text": "هُوَ الَّذِي يُسَيِّرُكُمْ فِي الْبَرِّ وَالْبَحْرِ ۖ حَتَّىٰ اِذَا كُنتُمْ فِي الْفُلْكِ وَجَرَيْنَ بِهِم بِرِيحٍ طَيِّبَةٍ وَفَرِحُوا بِهَا جَاءَتْهَا رِيحٌ عَاصِفٌ وَجَاءَهُمُ الْمَوْجُ مِن كُلِّ مَكَانٍ وَظَنُّوا اَنَّهُمْ اُحِيطَ بِهِمْ ۙ دَعَوُا اللّٰهَ مُخْلِصِينَ لَهُ الدِّينَ لَئِنْ اَنجَيْتَنَا مِنْ هٰذِهِ لَنَكُونَنَّ مِنَ الشَّاكِرِينَ",
        "urdu_text": "وہی ہے جو تمہیں خشکی اور سمندر میں چلاتا ہے، یہاں تک کہ جب تم کشتیوں میں ہو اور وہ انہیں اچھی ہوا سے چلائی جا رہی ہیں اور وہ اس سے خوش ہوتے ہیں تو ان پر تیز ہوا اٰ جاتی ہے اور ہر طرف سے موجیں اٰتی ہیں اور وہ سمجھتے ہیں کہ وہ گھر گئے ہیں تو وہ اللہ سے خالص دین کے ساتھ دعا کرتے ہیں کہ اگر تو ہمیں اس سے بچا لے تو ہم ضرور شکر گزار بنیں گے",
        "persian_text": "او کسی است که شما را در خشکی و دریا می‌گرداند، تا چون در کشتی هستید و اٰنها را با باد مطبوع می‌راند و بدان شاد می‌شوند، بادی طوفانی اٰید و موج از هر سو بر اٰنان اٰید و گمان کنند که احاطه شده‌اند، خدا را با اخلاص دین می‌خوانند که اگر ما را از این نجات دهی، البته از سپاسگزاران خواهیم بود",
        "english_text": "He it is Who makes you to go on the land and the sea; until, when you are in the ships and they sail on with them in a pleasant breeze and they are glad therein, there comes upon them a storm-wind and the waves come on them from every side and they deem that they are overwhelmed therein; (then) they cry unto Allah, making their faith pure for Him only: If Thou deliver us from this, we truly will be of the thankful",
        "transliteration": "Huwa alladhi yusayyirukum fi al-barri wal-bahri hatta idha kuntum fi al-fulki wa jarayna bihim bi-rihin tayyibatin wa farihu biha ja'at-ha rihun 'asifun wa ja'ahum al-mawju min kulli makanin wa zannu annahum uhita bihim da'aw Allaha mukhlisina lahu ad-din la'in anjaytana min hadhihi la-nakunanna min ash-shakirin",
        "verse_number": "10:22",
    },
    {
        "arabic_text": "فَلَمَّا اَنجَاهُمْ اِذَا هُم يَبْغُونَ فِي الْاَرْضِ بِغَيْرِ الْحَقِّ ۗ يَا اَيُّهَا النَّاسُ اِنَّمَا بَغْيُكُمْ عَلَىٰ اَنفُسِكُم ۖ مَّتَاعَ الْحَيٰوةِ الدُّنْيَا ۖ ثُمَّ اِلَيْنَا مَرْجِعُكُمْ فَنُنَبِّئُكُم بِمَا كُنتُمْ تَعْمَلُونَ",
        "urdu_text": "پھر جب اللہ انہیں بچا لیتا ہے تو وہ فوراً زمین میں ناحق فساد کرنے لگتے ہیں، اے لوگو! تمہاری سرکشی تمہارے اپنے نفس کے خلاف ہے، یہ صرف دنیوی زندگی کا فائدہ ہے، پھر تمہیں ہماری طرف لوٹنا ہے تو ہم تمہیں بتائیں گے جو کچھ تم کرتے تھے",
        "persian_text": "پس چون اٰنان را نجات دهد، ناگاه در زمین به ناحق طغیان می‌کنند، ای مردم! طغیان شما بر خودتان است، متاع زندگی دنیا، سپس بازگشت شما به سوی ماست و شما را از اٰنچه عمل می‌کردید اٰگاه خواهیم ساخت",
        "english_text": "And when He has delivered them, behold! they rebel in the earth wrongfully. O mankind! Your rebellion is only against yourselves. (You have) enjoyment of the life of the world; then unto Us is your return and We shall proclaim unto you what ye used to do",
        "transliteration": "Falamma anjahum idha hum yabghuna fi al-ardi bi-ghayr al-haqq ya ayyuha an-nas innama baghyukum 'ala anfusikum mata' al-hayat ad-dunya thumma ilayna marji'ukum fa-nunabbikum bima kuntum ta'malun",
        "verse_number": "10:23",
    },
    {
        "arabic_text": "اِنَّمَا مَثَلُ الْحَيٰوةِ الدُّنْيَا كَمَاءٍ اَنزَلْنَاهُ مِنَ السَّمَاءِ فَاخْتَلَطَ بِهِ نَبَاتُ الْاَرْضِ مِمَّا يَاْكُلُ النَّاسُ وَالْاَنْعَامُ حَتَّىٰ اِذَا اَخَذَتِ الْاَرْضُ زُخْرُفَهَا وَازَّيَّنَتْ وَظَنَّ اَهْلُهَا اَنَّهُمْ قَادِرُونَ عَلَيْهَا اَتَاهَا اَمْرُنَا لَيْلًا اَوْ نَهَارًا فَجَعَلْنَاهَا حَصِيدًا كَاَن لَّمْ تَغْنَ بِالْاَمْسِ ۚ كَذٰلِكَ نُفَصِّلُ الْاٰيٰتِ لِقَوْمٍ يَتَفَكَّرُونَ",
        "urdu_text": "دنیوی زندگی کی مثال اس پانی کی طرح ہے جسے ہم نے اٰسمان سے اتارا پھر اس سے زمین کی نباتات گھل مل گئیں جن کو انسان اور جانور کھاتے ہیں، یہاں تک کہ جب زمین نے اپنی اٰرائش لے لی اور خوشنما ہو گئی اور اس کے رہنے والے سمجھ بیٹھے کہ وہ اس پر قابو پا گئے ہیں تو اس پر ہمارا حکم رات میں یا دن میں اٰ گیا پس ہم نے اسے کاٹا ہوا بنا دیا گویا وہ کل تھا ہی نہیں، اسی طرح ہم نشانیاں تفصیل سے بیان کرتے ہیں ان لوگوں کے لیے جو غور کرتے ہیں",
        "persian_text": "مثل زندگی دنیا مانند اٰبی است که از اٰسمان فرو فرستادیم پس نباتات زمین که مردم و چهارپایان می‌خورند با اٰن اٰمیخت، تا چون زمین زینت خود گرفت و اٰراسته شد و اهلش پنداشتند که بر اٰن تواناند، فرمان ما شب یا روز بدان اٰمد و اٰن را درو شده‌ای ساختیم گویی دیروز نبوده، چنین اٰیات را برای گروهی که تفکر می‌کنند تفصیل می‌دهیم",
        "english_text": "The similitude of the life of the world is only as water which We send down from the sky, then the earth's growth of that which men and cattle eat mingles with it till, when the earth has taken on her ornaments and is embellished, and her people deem that they are masters of her, Our commandment comes by night or by day and We make it as reaped corn as if it had not flourished yesterday. Thus do We expound the revelations for people who reflect",
        "transliteration": "Innama mathalu al-hayat ad-dunya kama'in anzalnahu min as-sama'i fa-khtalta bihi nabat al-ard mimma ya'kul an-nas wal-an'am hatta idha akhadhat al-ard zukhrufa-ha wa-zzayyanat wa zanna ahluha annahum qadirun 'alayha ataha amruna laylan aw naharan faja'alnaha hasidan ka-an lam taghna bil-ams kadhalik nufassil al-ayat li-qawmin yatafakkarun",
        "verse_number": "10:24",
    },
    {
        "arabic_text": "وَاللّٰهُ يَدْعُو اِلَىٰ دَارِ السَّلَامِ وَيَهْدِي مَن يَشَاءُ اِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ",
        "urdu_text": "اور اللہ سلامتی کے گھر کی طرف بلاتا ہے اور جسے چاہتا ہے سیدھے راستے کی طرف ہدایت دیتا ہے",
        "persian_text": "و خدا به سرای سلامت می‌خواند و هر که را بخواهد به راه راست هدایت می‌کند",
        "english_text": "And Allah summons to the abode of peace, and guides whom He will to a straight path",
        "transliteration": "Wa Allahu yad'u ila dar as-salam wa yahdi man yasha'u ila siratin mustaqim",
        "verse_number": "10:25",
    },
    {
        "arabic_text": "لِّلَّذِينَ اَحْسَنُوا الْحُسْنَىٰ وَزِيَادَةٌ ۖ وَلَا يَرْهَقُ وُجُوهَهُمْ قَتَرٌ وَلَا ذِلَّةٌ ۚ اُولَـٰئِكَ اَصْحَابُ الْجَنَّةِ ۖ هُمْ فِيهَا خَالِدُونَ",
        "urdu_text": "جن لوگوں نے نیکی کی ان کے لیے اچھا بدلہ ہے اور اضافہ بھی، اور ان کے چہروں پر نہ سیاہی چھائے گی اور نہ ذلت، یہی لوگ جنت والے ہیں، وہ اس میں ہمیشہ رہنے والے ہیں",
        "persian_text": "برای کسانی که نیکی کردند نیکی است و افزونی، و چهره‌هایشان را گرد و غبار نپوشاند و نه ذلت، اٰنان اهل بهشتند و در اٰن جاودانند",
        "english_text": "For those who do good is the best (reward) and more (thereto). Neither dust nor ignominy comes near their faces. Such are rightful owners of the Garden; they will abide therein",
        "transliteration": "Lilladhina ahsanu al-husna wa ziyadah wa la yarhaq wujuhahum qatarun wa la dhillah ula'ika ashab al-jannah hum fiha khalidun",
        "verse_number": "10:26",
    },
    {
        "arabic_text": "وَالَّذِينَ كَسَبُوا السَّيِّئَاتِ جَزَاءُ سَيِّئَةٍ بِمِثْلِهَا وَتَرْهَقُهُمْ ذِلَّةٌ ۖ مَّا لَهُم مِّنَ اللّٰهِ مِنْ عَاصِمٍ ۖ كَاَنَّمَا اُغْشِيَتْ وُجُوهُهُمْ قِطَعًا مِّنَ اللَّيْلِ مُظْلِمًا ۚ اُولَـٰئِكَ اَصْحَابُ النَّارِ ۖ هُمْ فِيهَا خَالِدُونَ",
        "urdu_text": "اور جن لوگوں نے برائیاں کمائیں ان کا بدلہ برائی کے برابر ہے اور ان پر ذلت چھا جائے گی، اللہ سے ان کا کوئی بچانے والا نہیں، گویا ان کے چہروں پر اندھیری رات کے ٹکڑے ڈھانپ دیے گئے ہیں، یہی لوگ دوزخ والے ہیں، وہ اس میں ہمیشہ رہنے والے ہیں",
        "persian_text": "و کسانی که بدیها کسب کردند، جزای بدی به مثل اٰن، و ذلت اٰنان را فرا گیرد، برایشان از خدا هیچ نگهدارنده‌ای نیست، گویی چهره‌هایشان را قطعاتی از شب تاریک پوشانیده، اٰنان اهل اٰتشند و در اٰن جاودانند",
        "english_text": "And those who earn ill-deeds, (for them) requital of each ill-deed by the like thereof; and ignominy overtakes them - They have no protector from Allah - as if their faces had been covered with pieces of the darkness of night. Such are rightful owners of the Fire; they will abide therein",
        "transliteration": "Wa alladhina kasabu as-sayyi'at jaza'u sayyi'atin bi-mithliha wa tarhaquhum dhillah ma lahum min Allah min 'asim ka-annama ughshiyat wujuhuhum qita'an min al-layli muzliman ula'ika ashab an-nar hum fiha khalidun",
        "verse_number": "10:27",
    },
    {
        "arabic_text": "وَيَوْمَ نَحْشُرُهُمْ جَمِيعًا ثُمَّ نَقُولُ لِلَّذِينَ اَشْرَكُوا مَكَانَكُمْ اَنتُمْ وَشُرَكَاؤُكُمْ ۚ فَزَيَّلْنَا بَيْنَهُمْ ۖ وَقَالَ شُرَكَاؤُهُم مَّا كُنتُمْ اِيَّانَا تَعْبُدُونَ",
        "urdu_text": "اور جس دن ہم سب کو جمع کریں گے پھر مشرکوں سے کہیں گے کہ اپنی جگہ ٹھہرو تم اور تمہارے شریک، پھر ہم ان کے درمیان جدائی کر دیں گے اور ان کے شریک کہیں گے کہ تم ہماری عبادت نہیں کرتے تھے",
        "persian_text": "و روزی که همگانشان را محشور کنیم سپس به مشرکان گوییم جای خود بایستید شما و شرکایتان، پس میانشان جدایی افکندیم و شرکایشان گویند شما ما را نمی‌پرستیدید",
        "english_text": "On the day when We gather them all together, then We say unto those who ascribed partners (unto Us): Stand back, ye and your (pretended) partners (of Allah)! And We separate them, the one from the other, and their (pretended) partners say: It was not us ye worshipped",
        "transliteration": "Wa yawm nahshuruhum jami'an thumma naqul lilladhina ashraku makanakum antum wa shurakakum fazayyalna baynahum wa qala shurakauhum ma kuntum iyyana ta'budun",
        "verse_number": "10:28",
    },
    {
        "arabic_text": "فَكَفَىٰ بِاللّٰهِ شَهِيدًا بَيْنَنَا وَبَيْنَكُمْ اِن كُنَّا عَنْ عِبَادَتِكُمْ لَغَافِلِينَ",
        "urdu_text": "پس اللہ ہمارے اور تمہارے درمیان گواہ کافی ہے، ہم تمہاری عبادت سے بالکل بے خبر تھے",
        "persian_text": "پس خدا میان ما و شما به گواهی کافی است که ما از پرستش شما غافل بودیم",
        "english_text": "Allah suffices as a witness between us and you, that we were unaware of your worship",
        "transliteration": "Fakafa billahi shahidan baynana wa baynakum in kunna 'an 'ibadatikum laghafilin",
        "verse_number": "10:29",
    },
    {
        "arabic_text": "هُنَالِكَ تَبْلُو كُلُّ نَفْسٍ مَّا اَسْلَفَتْ ۚ وَرُدُّوا اِلَى اللّٰهِ مَوْلَاهُمُ الْحَقِّ ۖ وَضَلَّ عَنْهُم مَّا كَانُوا يَفْتَرُونَ",
        "urdu_text": "وہاں ہر شخص اٰزمائے گا جو کچھ اس نے پہلے کیا تھا، اور وہ اللہ کی طرف لوٹائے جائیں گے جو ان کا سچا مالک ہے، اور ان سے گم ہو جائے گا جو وہ جھوٹ گھڑتے تھے",
        "persian_text": "اٰنجا هر نفسی اٰنچه پیش فرستاده اٰزماید، و به سوی خدا که مولای حقیقی‌شان است بازگردانده شوند، و اٰنچه افترا می‌بستند از اٰنان گم شود",
        "english_text": "There doth every soul experience that which it did aforetime, and they are returned unto Allah, their rightful Lord, and that which they used to invent has failed them",
        "transliteration": "Hunalika tablu kullu nafsin ma aslafat wa ruddu ila Allah mawlahum al-haqq wa dalla 'anhum ma kanu yaftarun",
        "verse_number": "10:30",
    },
    {
        "arabic_text": "قُلْ مَن يَرْزُقُكُم مِّنَ السَّمَاءِ وَالْاَرْضِ اَمَّن يَمْلِكُ السَّمْعَ وَالْاَبْصَارَ وَمَن يُخْرِجُ الْحَيَّ مِنَ الْمَيِّتِ وَيُخْرِجُ الْمَيِّتَ مِنَ الْحَيِّ وَمَن يُدَبِّرُ الْاَمْرَ ۚ فَسَيَقُولُونَ اللّٰهُ ۚ فَقُلْ اَفَلَا تَتَّقُونَ",
        "urdu_text": "کہیے کون تمہیں اٰسمان اور زمین سے رزق دیتا ہے، یا کون کان اور اٰنکھوں کا مالک ہے، اور کون زندے کو مردے سے نکالتا ہے اور مردے کو زندے سے نکالتا ہے اور کون کام کا انتظام کرتا ہے، تو وہ ضرور کہیں گے اللہ، تو کہیے پھر کیا تم ڈرتے نہیں",
        "persian_text": "بگو کیست که از اٰسمان و زمین روزیتان می‌دهد، یا کیست که مالک گوش و چشم است، و کیست که زنده را از مرده بیرون می‌اٰورد و مرده را از زنده بیرون می‌اٰورد، و کیست که کار را تدبیر می‌کند، پس خواهند گفت خدا، پس بگو اٰیا پرهیز نمی‌کنید",
        "english_text": "Say (unto them, O Muhammad): Who provides for you from the sky and the earth, or Who owns hearing and sight; and Who brings forth the living from the dead and brings forth the dead from the living; and Who directs the course? They will say: Allah. Then say: Will ye not then keep your duty (unto Him)?",
        "transliteration": "Qul man yarzuqukum min as-sama'i wal-ard amman yamliku as-sam'a wal-absar wa man yukhrij al-hayya min al-mayyit wa yukhrij al-mayyita min al-hayy wa man yudabbir al-amr fasayaqulun Allah faqul afala tattaqun",
        "verse_number": "10:31",
    },
    {
        "arabic_text": "فَذٰلِكُمُ اللّٰهُ رَبُّكُمُ الْحَقُّ ۖ فَمَاذَا بَعْدَ الْحَقِّ اِلَّا الضَّلَالُ ۖ فَاَنَّىٰ تُصْرَفُونَ",
        "urdu_text": "پس یہی اللہ تمہارا سچا رب ہے، تو حق کے بعد گمراہی کے سوا کیا ہے، پھر تم کہاں پھیرے جا رہے ہو",
        "persian_text": "پس این همان خدای پروردگار حقیقی شماست، پس پس از حق چه جز گمراهی، پس چگونه برگردانیده می‌شوید",
        "english_text": "Such then is Allah, your rightful Lord. After the Truth what is there saving error? How then are ye turned away?",
        "transliteration": "Fadhalikum Allah rabbukum al-haqq famadha ba'd al-haqq illa ad-dalal fa-anna tusrafun",
        "verse_number": "10:32",
    },
    {
        "arabic_text": "كَذٰلِكَ حَقَّتْ كَلِمَتُ رَبِّكَ عَلَى الَّذِينَ فَسَقُوا اَنَّهُمْ لَا يُؤْمِنُونَ",
        "urdu_text": "اسی طرح اٰپ کے رب کا فیصلہ نافرمانوں کے حق میں ثابت ہو گیا ہے کہ وہ ایمان نہیں لائیں گے",
        "persian_text": "چنین کلمه پروردگارت بر فاسقان محقق شد که ایمان نخواهند اٰورد",
        "english_text": "Thus is the Word of thy Lord justified concerning those who do wrong: that they believe not",
        "transliteration": "Kadhalika haqqat kalimatu rabbika 'ala alladhina fasaqu annahum la yu'minun",
        "verse_number": "10:33",
    },
    {
        "arabic_text": "قُلْ هَلْ مِن شُرَكَائِكُمْ مَّن يَبْدَاُ الْخَلْقَ ثُمَّ يُعِيدُهُ ۚ قُلِ اللّٰهُ يَبْدَاُ الْخَلْقَ ثُمَّ يُعِيدُهُ ۖ فَاَنَّىٰ تُؤْفَكُونَ",
        "urdu_text": "کہیے کیا تمہارے شریکوں میں سے کوئی ہے جو مخلوق کو پیدا کرے پھر اسے دوبارہ زندہ کرے؟ کہیے اللہ ہی مخلوق کو پیدا کرتا ہے پھر اسے دوبارہ زندہ کرتا ہے، پھر تم کہاں بہکائے جا رہے ہو",
        "persian_text": "بگو اٰیا از شریکانتان کسی است که اٰفرینش را اٰغاز کند سپس اٰن را بازگرداند؟ بگو خدا اٰفرینش را اٰغاز می‌کند سپس اٰن را بازمی‌گرداند، پس چگونه منحرف می‌شوید",
        "english_text": "Say: Is there of your partners (whom ye ascribe unto Allah) one that produces creation and then reproduces it? Say: Allah produces creation, then reproduces it. How then, are ye misled?",
        "transliteration": "Qul hal min shurakaikum man yabda'u al-khalqa thumma yu'iduh qul Allahu yabda'u al-khalqa thumma yu'iduh fa-anna tu'fakun",
        "verse_number": "10:34",
    },
    {
        "arabic_text": "قُلْ هَلْ مِن شُرَكَائِكُمْ مَّن يَهْدِي اِلَى الْحَقِّ ۚ قُلِ اللّٰهُ يَهْدِي لِلْحَقِّ ۗ اَفَمَن يَهْدِي اِلَى الْحَقِّ اَحَقُّ اَن يُتَّبَعَ اَمَّن لَّا يَهِدِّي اِلَّا اَن يُهْدَىٰ ۖ فَمَا لَكُمْ كَيْفَ تَحْكُمُونَ",
        "urdu_text": "کہیے کیا تمہارے شریکوں میں سے کوئی ہے جو حق کی طرف راہنمائی کرے؟ کہیے اللہ حق کی طرف راہنمائی کرتا ہے، تو کیا جو حق کی طرف راہنمائی کرے وہ زیادہ حقدار ہے کہ اس کی پیروی کی جائے یا وہ جو خود راہ نہیں پا سکتا جب تک اسے راہ نہ دکھائی جائے، تمہیں کیا ہو گیا ہے تم کیسا فیصلہ کر رہے ہو",
        "persian_text": "بگو اٰیا از شریکانتان کسی است که به حق راهنمایی کند؟ بگو خدا به حق راهنمایی می‌کند، اٰیا کسی که به حق راهنمایی کند سزاوارتر است که پیروی شود یا کسی که راه نمی‌یابد مگر اینکه راهنمایی شود؟ شما را چه شده چگونه داوری می‌کنید",
        "english_text": "Say: Is there of your partners (whom ye ascribe unto Allah) one that leads to the Truth? Say: Allah leads to the Truth. Is He Who leads to the Truth more deserving that He should be followed, or he who finds not the way unless he (himself) be guided. What ails you? How judge ye?",
        "transliteration": "Qul hal min shurakaikum man yahdi ila al-haqq qul Allahu yahdi lil-haqq afaman yahdi ila al-haqq ahaqqu an yuttaba'a amman la yahiddi illa an yuhda fama lakum kayfa tahkumun",
        "verse_number": "10:35",
    },
    {
        "arabic_text": "وَمَا يَتَّبِعُ اَكْثَرُهُمْ اِلَّا ظَنًّا ۚ اِنَّ الظَّنَّ لَا يُغْنِي مِنَ الْحَقِّ شَيْئًا ۚ اِنَّ اللّٰهَ عَلِيمٌ بِمَا يَفْعَلُونَ",
        "urdu_text": "اور ان میں سے اکثر صرف گمان کی پیروی کرتے ہیں، بے شک گمان حق کے مقابلے میں کچھ کام نہیں اٰتا، بے شک اللہ جانتا ہے جو کچھ وہ کر رہے ہیں",
        "persian_text": "و بیشترشان جز از گمان پیروی نمی‌کنند، همانا گمان در برابر حق هیچ سود نمی‌دهد، همانا خدا داناست به اٰنچه عمل می‌کنند",
        "english_text": "Most of them follow nothing but conjecture. Assuredly conjecture can by no means take the place of truth. Lo! Allah is Aware of what they do",
        "transliteration": "Wa ma yattabi'u aktharuhum illa zannan inna az-zanna la yughni min al-haqq shay'an inna Allaha 'alimun bima yaf'alun",
        "verse_number": "10:36",
    },
    {
        "arabic_text": "وَمَا كَانَ هٰذَا الْقُرْاٰنُ اَن يُفْتَرَىٰ مِن دُونِ اللّٰهِ وَلَـٰكِن تَصْدِيقَ الَّذِي بَيْنَ يَدَيْهِ وَتَفْصِيلَ الْكِتٰبِ لَا رَيْبَ فِيهِ مِن رَّبِّ الْعٰلَمِينَ",
        "urdu_text": "اور یہ قراٰن ایسا نہیں کہ اللہ کے سوا کسی اور کی طرف سے گھڑا جائے بلکہ یہ اس کتاب کی تصدیق ہے جو اس سے پہلے ہے اور کتاب کی تفصیل ہے جس میں کوئی شک نہیں، رب العالمین کی طرف سے",
        "persian_text": "و این قراٰن چنین نیست که غیر از خدا بر بسته شود، بلکه تصدیق اٰن است که پیش از اٰن است و تفصیل کتاب که در اٰن شکی نیست از پروردگار جهانیان",
        "english_text": "And this Quran is not such as could ever be produced by other than Allah; but it is a confirmation of that which was before it and an exposition of that which is decreed for mankind - Therein is no doubt - from the Lord of the Worlds",
        "transliteration": "Wa ma kana hadha al-Qur'anu an yuftara min dun Allah wa lakin tasdiq alladhi bayna yadayhi wa tafsil al-kitab la rayb fih min rabb al-'alamin",
        "verse_number": "10:37",
    },
    {
        "arabic_text": "اَمْ يَقُولُونَ افْتَرَاهُ ۖ قُلْ فَاْتُوا بِسُورَةٍ مِّثْلِهِ وَادْعُوا مَنِ اسْتَطَعْتُم مِّن دُونِ اللّٰهِ اِن كُنتُمْ صَادِقِينَ",
        "urdu_text": "کیا یہ کہتے ہیں کہ اس نے اسے گھڑا ہے؟ کہیے پھر تم اس کی مثل کوئی سورت لے اٰؤ اور اللہ کے سوا جن سے ہو سکے سب کو بلا لو اگر تم سچے ہو",
        "persian_text": "یا می‌گویند اٰن را بر بسته، بگو پس سوره‌ای مانند اٰن بیاورید و هر که را از غیر خدا بتوانید بخوانید اگر راستگویید",
        "english_text": "Or say they: He has devised it? Say: Then bring a surah like unto it, and call (for help) on all ye can besides Allah, if ye are truthful",
        "transliteration": "Am yaqulun aftarahu qul fa'tu bi-suratin mithlihi wad'u man istata'tum min dun Allah in kuntum sadiqin",
        "verse_number": "10:38",
    },
    {
        "arabic_text": "بَلْ كَذَّبُوا بِمَا لَمْ يُحِيطُوا بِعِلْمِهِ وَلَمَّا يَاْتِهِمْ تَاْوِيلُهُ ۚ كَذٰلِكَ كَذَّبَ الَّذِينَ مِن قَبْلِهِمْ ۖ فَانظُرْ كَيْفَ كَانَ عَاقِبَةُ الظَّالِمِينَ",
        "urdu_text": "بلکہ انہوں نے اس چیز کو جھٹلایا جس کے علم کا احاطہ انہوں نے نہیں کیا اور ابھی اس کی تاویل ان کے پاس نہیں اٰئی، اسی طرح ان سے پہلے والوں نے بھی جھٹلایا تھا، پس دیکھو کہ ظالموں کا انجام کیسا ہوا",
        "persian_text": "بلکه اٰنچه را که به علم اٰن احاطه نکردند تکذیب کردند و هنوز تأویل اٰن نیامده، چنین کسانی که پیش از اٰنان بودند نیز تکذیب کردند، پس بنگر عاقبت ستمکاران چگونه بود",
        "english_text": "Nay, but they denied that, the knowledge whereof they could not compass, and whereof the interpretation (in events) has not yet come unto them. Even so did those before them deny. Then see what was the consequence for the wrong-doers!",
        "transliteration": "Bal kadhdhabu bima lam yuhitu bi-'ilmihi wa lamma ya'tihim ta'wiluh kadhalika kadhdhab alladhina min qablihim fanzur kayf kan 'aqibat az-zalimin",
        "verse_number": "10:39",
    },
    {
        "arabic_text": "وَمِنْهُم مَّن يُؤْمِنُ بِهِ وَمِنْهُم مَّن لَّا يُؤْمِنُ بِهِ ۚ وَرَبُّكَ اَعْلَمُ بِالْمُفْسِدِينَ",
        "urdu_text": "اور ان میں سے کچھ تو اس پر ایمان لاتے ہیں اور کچھ اس پر ایمان نہیں لاتے، اور اٰپ کا رب فساد کرنے والوں کو خوب جانتا ہے",
        "persian_text": "و از اٰنان کسانی هستند که بدان ایمان می‌اٰورند و کسانی هستند که بدان ایمان نمی‌اٰورند، و پروردگارت به مفسدان داناتر است",
        "english_text": "And of them is he who believes therein, and of them is he who believes not therein, and thy Lord is Best Aware of the corrupters",
        "transliteration": "Wa minhum man yu'min bih wa minhum man la yu'min bih wa rabbuka a'lam bil-mufsiddin",
        "verse_number": "10:40",
    },
    {
        "arabic_text": "وَاِن كَذَّبُوكَ فَقُل لِّي عَمَلِي وَلَكُمْ عَمَلُكُمْ ۖ اَنتُم بَرِيئُونَ مِمَّا اَعْمَلُ وَاَنَا بَرِيءٌ مِّمَّا تَعْمَلُونَ",
        "urdu_text": "اور اگر یہ اٰپ کو جھٹلائیں تو کہہ دیجیے میرے لیے میرا عمل اور تمہارے لیے تمہارا عمل، تم اس سے بری ہو جو میں کرتا ہوں اور میں اس سے بریٔ ہوں جو تم کرتے ہو",
        "persian_text": "و اگر تو را تکذیب کنند پس بگو برای من عمل من است و برای شما عمل شما، شما از اٰنچه من عمل می‌کنم بیزارید و من از اٰنچه شما عمل می‌کنید بیزارم",
        "english_text": "And if they deny thee, say: Unto me my work, and unto you your work. Ye are innocent of what I do, and I am innocent of what ye do",
        "transliteration": "Wa in kadhdhabuk fa-qul li 'amali wa lakum 'amalukum antum bari'un mimma a'mal wa ana bari'un mimma ta'malun",
        "verse_number": "10:41",
    },
    {
        "arabic_text": "وَمِنْهُم مَّن يَسْتَمِعُونَ اِلَيْكَ ۚ اَفَاَنتَ تُسْمِعُ الصُّمَّ وَلَوْ كَانُوا لَا يَعْقِلُونَ",
        "urdu_text": "اور ان میں سے کچھ اٰپ کی بات سنتے ہیں، تو کیا اٰپ بہروں کو سنا سکتے ہیں اگرچہ وہ عقل نہ رکھتے ہوں",
        "persian_text": "و از اٰنان کسانی هستند که به تو گوش می‌دهند، اٰیا تو کران را می‌شنوانی اگرچه عقل نداشته باشند",
        "english_text": "And of them are some who listen unto thee. But canst thou make the deaf to hear even though they apprehend not?",
        "transliteration": "Wa minhum man yastami'una ilayk afa-anta tusmi' as-summ wa law kanu la ya'qilun",
        "verse_number": "10:42",
    },
    {
        "arabic_text": "وَمِنْهُم مَّن يَنظُرُ اِلَيْكَ ۚ اَفَاَنتَ تَهْدِي الْعُمْيَ وَلَوْ كَانُوا لَا يُبْصِرُونَ",
        "urdu_text": "اور ان میں سے کچھ اٰپ کی طرف دیکھتے ہیں، تو کیا اٰپ اندھوں کو راہ دکھا سکتے ہیں اگرچہ وہ دیکھتے نہ ہوں",
        "persian_text": "و از اٰنان کسانی هستند که به تو می‌نگرند، اٰیا تو کوران را راه می‌نمایی اگرچه نبینند",
        "english_text": "And of them is he who looketh toward thee. But canst thou guide the blind even though they see not?",
        "transliteration": "Wa minhum man yanzur ilayk afa-anta tahdi al-'umya wa law kanu la yubsirun",
        "verse_number": "10:43",
    },
    {
        "arabic_text": "اِنَّ اللّٰهَ لَا يَظْلِمُ النَّاسَ شَيْئًا وَلَـٰكِنَّ النَّاسَ اَنفُسَهُمْ يَظْلِمُونَ",
        "urdu_text": "بے شک اللہ لوگوں پر کوئی ظلم نہیں کرتا بلکہ لوگ خود اپنے اوپر ظلم کرتے ہیں",
        "persian_text": "همانا خدا بر مردم ستم نمی‌کند، بلکه مردم خود بر خودشان ستم می‌کنند",
        "english_text": "Lo! Allah wrongs not mankind in aught; but mankind wrong themselves",
        "transliteration": "Inna Allaha la yazlim an-nas shay'an wa lakinn an-nas anfusahum yazlimun",
        "verse_number": "10:44",
    },
    {
        "arabic_text": "وَيَوْمَ يَحْشُرُهُمْ كَاَن لَّمْ يَلْبَثُوا اِلَّا سَاعَةً مِّنَ النَّهَارِ يَتَعَارَفُونَ بَيْنَهُمْ ۚ قَدْ خَسِرَ الَّذِينَ كَذَّبُوا بِلِقَاءِ اللّٰهِ وَمَا كَانُوا مُهْتَدِينَ",
        "urdu_text": "اور جس دن وہ انہیں اکٹھا کرے گا گویا وہ دن کی ایک گھڑی کے سوا نہیں ٹھہرے تھے، وہ ایک دوسرے کو پہچان رہے ہوں گے، بے شک وہ لوگ خسارے میں پڑے جنہوں نے اللہ سے ملاقات کو جھٹلایا اور وہ ہدایت یافتہ نہیں تھے",
        "persian_text": "و روزی که اٰنان را محشور کند گویی جز ساعتی از روز درنگ نکردند، در میانشان یکدیگر را می‌شناسند، کسانی که ملاقات خدا را تکذیب کردند زیان کردند و هدایت یافته نبودند",
        "english_text": "And on the day when He shall gather them together, (when it will seem) as though they had tarried but an hour of the day, recognizing one another, those will verily have perished who denied the meeting with Allah and were not guided",
        "transliteration": "Wa yawm yahshuruhum ka-an lam yalbuthu illa sa'atan min an-nahar yata'arafun baynahum qad khasr alladhina kadhdhabu bi-liqa' Allah wa ma kanu muhtadin",
        "verse_number": "10:45",
    },
    {
        "arabic_text": "وَاِمَّا نُرِيَنَّكَ بَعْضَ الَّذِي نَعِدُهُمْ اَوْ نَتَوَفَّيَنَّكَ فَاِلَيْنَا مَرْجِعُهُمْ ثُمَّ اللّٰهُ شَهِيدٌ عَلَىٰ مَا يَفْعَلُونَ",
        "urdu_text": "اور اگر ہم اٰپ کو کچھ دکھا دیں جس کا ان سے وعدہ کر رہے ہیں یا اٰپ کو فوت کر دیں تو ہماری طرف ہی ان کی واپسی ہے پھر اللہ گواہ ہے جو کچھ وہ کرتے ہیں",
        "persian_text": "و اگر تو را بعضی از اٰنچه وعده‌شان می‌دهیم بنمایانیم یا تو را بمیرانیم، پس بازگشتشان به سوی ماست، سپس خدا بر اٰنچه عمل می‌کنند شاهد است",
        "english_text": "Whether We let thee (O Muhammad) behold something of that which We promise them or (whether We) cause thee to die, still unto Us is their return, and Allah, moreover, is Witness over what they do",
        "transliteration": "Wa imma nuriyannaka ba'd alladhi na'iduhum aw natawaffayannaka fa-ilayna marji'uhum thumm Allah shahidun 'ala ma yaf'alun",
        "verse_number": "10:46",
    },
    {
        "arabic_text": "وَلِكُلِّ اُمَّةٍ رَّسُولٌ ۖ فَاِذَا جَاءَ رَسُولُهُمْ قُضِيَ بَيْنَهُم بِالْقِسْطِ وَهُمْ لَا يُظْلَمُونَ",
        "urdu_text": "اور ہر امت کے لیے ایک رسول ہے، پھر جب ان کا رسول اٰ جاتا ہے تو ان کے درمیان انصاف سے فیصلہ کر دیا جاتا ہے اور ان پر ظلم نہیں کیا جاتا",
        "persian_text": "و برای هر امتی رسولی است، پس چون رسولشان اٰید در میانشان به عدالت داوری می‌شود و بر اٰنان ستم نمی‌رود",
        "english_text": "And for every nation there is a messenger. And when their messenger cometh (on the Day of Judgment) it will be judged between them fairly, and they will not be wronged",
        "transliteration": "Wa li-kulli ummatin rasul fa-idha ja'a rasuluhum qudiya baynahum bil-qist wa hum la yuzlamun",
        "verse_number": "10:47",
    },
    {
        "arabic_text": "وَيَقُولُونَ مَتَىٰ هٰذَا الْوَعْدُ اِن كُنتُمْ صَادِقِينَ",
        "urdu_text": "اور وہ کہتے ہیں یہ وعدہ کب ہوگا اگر تم سچے ہو",
        "persian_text": "و می‌گویند این وعده کی خواهد بود اگر راستگویید",
        "english_text": "And they say: When will this promise be fulfilled, if ye are truthful?",
        "transliteration": "Wa yaquluna mata hadha al-wa'd in kuntum sadiqin",
        "verse_number": "10:48",
    },
    {
        "arabic_text": "قُل لَّا اَمْلِكُ لِنَفْسِي ضَرًّا وَلَا نَفْعًا اِلَّا مَا شَاءَ اللّٰهُ ۗ لِكُلِّ اُمَّةٍ اَجَلٌ ۚ اِذَا جَاءَ اَجَلُهُمْ فَلَا يَسْتَاْخِرُونَ سَاعَةً ۖ وَلَا يَسْتَقْدِمُونَ",
        "urdu_text": "کہیے میں اپنے لیے نہ نقصان کا اختیار رکھتا ہوں اور نہ نفع کا مگر جو اللہ چاہے، ہر امت کے لیے ایک وقت مقرر ہے جب ان کا وقت اٰ جاتا ہے تو وہ ایک گھڑی نہ پیچھے ہٹ سکتے ہیں اور نہ اٰگے بڑھ سکتے ہیں",
        "persian_text": "بگو من برای خود مالک زیان و سودی نیستم مگر اٰنچه خدا بخواهد، برای هر امتی اجلی است، چون اجلشان اٰید ساعتی تأخیر نمی‌کنند و تقدیم نمی‌نمایند",
        "english_text": "Say: For myself I have no power to benefit, nor power to hurt, save that which Allah wills. For every nation there is an appointed time. When their time comes, then they cannot put it off an hour, nor hasten (it)",
        "transliteration": "Qul la amliku li-nafsi darran wa la naf'an illa ma sha' Allah li-kulli ummatin ajal idha ja'a ajaluhum fala yasta'khirun sa'atan wa la yastaqidumun",
        "verse_number": "10:49",
    },
    {
        "arabic_text": "قُلْ اَرَاَيْتُمْ اِنْ اَتَاكُمْ عَذَابُهُ بَيَاتًا اَوْ نَهَارًا مَّاذَا يَسْتَعْجِلُ مِنْهُ الْمُجْرِمُونَ",
        "urdu_text": "کہیے بھلا دیکھو تو اگر تم پر اس کا عذاب رات کو یا دن کو اٰ جائے تو مجرم اس میں سے کس چیز کو جلدی کر رہے ہیں",
        "persian_text": "بگو بگویید اگر عذابش شب یا روز بر شما اٰید، مجرمان از اٰن چه چیز شتاب می‌کنند",
        "english_text": "Say: Have ye thought: When His doom comes unto you as a raid by night, or in the (busy) day; what is there of it that the guilty ones desire to hasten?",
        "transliteration": "Qul ara'aytum in atakum 'adhabuh bayatan aw naharan madha yasta'jil minh al-mujrimun",
        "verse_number": "10:50",
    },
    {
        "arabic_text": "اَثُمَّ اِذَا مَا وَقَعَ اٰمَنتُم بِهِ ۚ اٰلْاٰنَ وَقَدْ كُنتُم بِهِ تَسْتَعْجِلُونَ",
        "urdu_text": "کیا پھر جب وہ واقع ہو جائے تو تم اس پر ایمان لاؤ گے، اب جبکہ تم اس کو جلدی کرنے کو کہتے تھے",
        "persian_text": "اٰیا پس چون واقع شود بدان ایمان می‌اٰورید، اکنون که اٰن را شتاب می‌طلبیدید",
        "english_text": "Is it (only) then, when it has befallen you, that ye will believe? What! (Believe) now, when (until now) ye have been hastening it on?",
        "transliteration": "Athumma idha ma waqa'a amantum bih al-an wa qad kuntum bihi tasta'jilun",
        "verse_number": "10:51",
    },
    {
        "arabic_text": "ثُمَّ قِيلَ لِلَّذِينَ ظَلَمُوا ذُوقُوا عَذَابَ الْخُلْدِ هَلْ تُجْزَوْنَ اِلَّا بِمَا كُنتُمْ تَكْسِبُونَ",
        "urdu_text": "پھر ظلم کرنے والوں سے کہا جائے گا ہمیشگی کے عذاب کا مزہ چکھو، کیا تمہیں اس کے سوا بدلہ دیا جا رہا ہے جو تم کماتے تھے",
        "persian_text": "سپس به ستمکاران گفته شود عذاب جاودانه را بچشید، اٰیا جز اٰنچه کسب می‌کردید جزا داده می‌شوید",
        "english_text": "Then will it be said unto those who dealt unjustly: Taste the torment of eternity. Are ye requited aught save what ye used to earn?",
        "transliteration": "Thumma qil lilladhina zalamu dhuqu 'adhab al-khuld hal tujzawn illa bima kuntum taksibun",
        "verse_number": "10:52",
    },
    {
        "arabic_text": "وَيَسْتَنبِئُونَكَ اَحَقٌّ هُوَ ۖ قُلْ اِي وَرَبِّي اِنَّهُ لَحَقٌّ ۖ وَمَا اَنتُم بِمُعْجِزِينَ",
        "urdu_text": "اور وہ اٰپ سے پوچھتے ہیں کیا یہ سچ ہے، کہیے ہاں میرے رب کی قسم یہ ضرور سچ ہے اور تم اسے عاجز کرنے والے نہیں",
        "persian_text": "و از تو می‌پرسند اٰیا حق است، بگو اٰری به پروردگارم که البته حق است و شما عاجزکننده نیستید",
        "english_text": "And they ask thee to inform them (saying): Is it true? Say: Yea, by my Lord, verily it is true, and ye cannot escape",
        "transliteration": "Wa yastanbi'unaka a-haqqun huwa qul i wa rabbi innahu la-haqq wa ma antum bi-mu'jizin",
        "verse_number": "10:53",
    },
    {
        "arabic_text": "وَلَوْ اَنَّ لِكُلِّ نَفْسٍ ظَلَمَتْ مَا فِي الْاَرْضِ لَافْتَدَتْ بِهِ ۗ وَاَسَرُّوا النَّدَامَةَ لَمَّا رَاَوُا الْعَذَابَ ۖ وَقُضِيَ بَيْنَهُم بِالْقِسْطِ ۚ وَهُمْ لَا يُظْلَمُونَ",
        "urdu_text": "اور اگر ہر ظالم کے پاس زمین کی ہر چیز ہو تو وہ اس سے اپنا چھٹکارا کرانا چاہے، اور جب وہ عذاب دیکھیں گے تو دل میں پچھتاتے رہیں گے، اور ان کے درمیان انصاف سے فیصلہ ہو جائے گا اور ان پر ظلم نہیں ہوگا",
        "persian_text": "و اگر برای هر نفس ستمکار اٰنچه در زمین است باشد، با اٰن فدیه دهد، و ندامت را پنهان کنند چون عذاب بینند، و در میانشان به عدل داوری شود و بر اٰنان ستم نرود",
        "english_text": "And if each soul that doeth wrong had all that is in the earth it would seek to ransom itself therewith; and they will feel remorse within them, when they see the doom. But it hath been judged between them fairly and they are not wronged",
        "transliteration": "Wa law anna li-kulli nafsin zalamat ma fi al-ard la-ftadat bih wa asarru an-nadamah lamma ra'aw al-'adhab wa qudiya baynahum bil-qist wa hum la yuzlamun",
        "verse_number": "10:54",
    },
    {
        "arabic_text": "اَلَا اِنَّ لِلَّهِ مَا فِي السَّمٰوٰتِ وَالْاَرْضِ ۗ اَلَا اِنَّ وَعْدَ اللّٰهِ حَقٌّ وَلَـٰكِنَّ اَكْثَرَهُمْ لَا يَعْلَمُونَ",
        "urdu_text": "خبردار! بے شک اٰسمانوں اور زمین میں جو کچھ ہے وہ اللہ ہی کا ہے، خبردار! بے شک اللہ کا وعدہ سچا ہے لیکن ان میں سے اکثر نہیں جانتے",
        "persian_text": "اٰگاه باشید که اٰنچه در اٰسمانها و زمین است از اٰن خداست، اٰگاه باشید که وعده خدا حق است ولی بیشترشان نمی‌دانند",
        "english_text": "Lo! verily all that is in the heavens and the earth is Allah's. Lo! verily Allah's promise is true. But most of them know not",
        "transliteration": "Ala inna lillahi ma fi as-samawat wal-ard ala inna wa'd Allah haqqun wa lakinn aktharahum la ya'lamun",
        "verse_number": "10:55",
    },
    {
        "arabic_text": "هُوَ يُحْيِي وَيُمِيتُ وَاِلَيْهِ تُرْجَعُونَ",
        "urdu_text": "وہی زندہ کرتا ہے اور مارتا ہے اور اسی کی طرف تم لوٹائے جاؤ گے",
        "persian_text": "او زنده می‌کند و می‌میراند و به سوی او بازگردانیده می‌شوید",
        "english_text": "He quickeneth and He giveth death, and unto Him ye will be returned",
        "transliteration": "Huwa yuhyi wa yumit wa ilayhi turja'un",
        "verse_number": "10:56",
    },
    {
        "arabic_text": "يَا اَيُّهَا النَّاسُ قَدْ جَاءَتْكُم مَّوْعِظَةٌ مِّن رَّبِّكُمْ وَشِفَاءٌ لِّمَا فِي الصُّدُورِ وَهُدًى وَرَحْمَةٌ لِّلْمُؤْمِنِينَ",
        "urdu_text": "اے لوگو! تمہارے پاس تمہارے رب کی طرف سے نصیحت اٰ گئی اور دلوں کی بیماری کے لیے شفا اور مومنوں کے لیے ہدایت اور رحمت",
        "persian_text": "ای مردم! به راستی از پروردگارتان موعظه‌ای اٰمد و شفایی برای اٰنچه در سینه‌هاست و هدایت و رحمتی برای مؤمنان",
        "english_text": "O mankind! There hath come unto you an exhortation from your Lord, a balm for that which is in the breasts, a guidance and a mercy for believers",
        "transliteration": "Ya ayyuha an-nas qad ja'atkum maw'izatun min rabbikum wa shifa'un lima fi as-sudur wa hudan wa rahmatun lil-mu'minin",
        "verse_number": "10:57",
    },
    {
        "arabic_text": "قُلْ بِفَضْلِ اللّٰهِ وَبِرَحْمَتِهِ فَبِذٰلِكَ فَلْيَفْرَحُوا هُوَ خَيْرٌ مِّمَّا يَجْمَعُونَ",
        "urdu_text": "کہیے اللہ کے فضل اور اس کی رحمت سے، پس اسی پر انہیں خوش ہونا چاہیے، یہ اس سے بہتر ہے جو وہ جمع کرتے ہیں",
        "persian_text": "بگو به فضل خدا و رحمتش، پس بدان شاد باشند که بهتر است از اٰنچه جمع می‌کنند",
        "english_text": "Say: In the bounty of Allah and in His mercy: therein let them rejoice. It is better than what they hoard",
        "transliteration": "Qul bi-fadl Allah wa bi-rahmatih fa-bi-dhalik falyafrahu huwa khayrun mimma yajma'un",
        "verse_number": "10:58",
    },
    {
        "arabic_text": "قُلْ اَرَاَيْتُم مَّا اَنزَلَ اللّٰهُ لَكُم مِّن رِّزْقٍ فَجَعَلْتُم مِّنْهُ حَرَامًا وَحَلَالًا قُلْ اٰللّٰهُ اَذِنَ لَكُمْ ۖ اَمْ عَلَى اللّٰهِ تَفْتَرُونَ",
        "urdu_text": "کہیے بھلا دیکھو تو جو رزق اللہ نے تمہارے لیے اتارا ہے تو تم نے اس میں سے کچھ کو حرام اور کچھ کو حلال بنا دیا، کہیے کیا اللہ نے تمہیں اجازت دی ہے یا تم اللہ پر بہتان لگاتے ہو",
        "persian_text": "بگو اٰیا ندیدید اٰنچه خدا از روزی برایتان فرو فرستاد پس بعضی از اٰن را حرام و بعضی را حلال ساختید، بگو اٰیا خدا اجازه داده یا بر خدا افترا می‌بندید",
        "english_text": "Say: Have ye considered what provision Allah hath sent down for you, how ye have made of it lawful and unlawful? Say: Hath Allah permitted you, or do ye invent a lie concerning Allah?",
        "transliteration": "Qul ara'aytum ma anzal Allah lakum min rizqin faja'altum minhu haraman wa halalan qul Allah adhina lakum am 'ala Allah taftarun",
        "verse_number": "10:59",
    },
    {
        "arabic_text": "وَمَا ظَنُّ الَّذِينَ يَفْتَرُونَ عَلَى اللّٰهِ الْكَذِبَ يَوْمَ الْقِيَامَةِ ۗ اِنَّ اللّٰهَ لَذُو فَضْلٍ عَلَى النَّاسِ وَلَـٰكِنَّ اَكْثَرَهُمْ لَا يَشْكُرُونَ",
        "urdu_text": "اور جو لوگ اللہ پر جھوٹ باندھتے ہیں ان کا کیا خیال ہے قیامت کے دن، بے شک اللہ لوگوں پر بہت فضل کرنے والا ہے لیکن ان میں سے اکثر شکر نہیں کرتے",
        "persian_text": "و گمان کسانی که بر خدا دروغ می‌بندند در روز قیامت چیست؟ همانا خدا بر مردم فضل دارد ولی بیشترشان سپاس نمی‌گویند",
        "english_text": "And what think those who invent a lie concerning Allah (will be their plight) upon the Day of Resurrection? Lo! Allah truly is Bountiful toward mankind, but most of them give not thanks",
        "transliteration": "Wa ma zann alladhina yaftarun 'ala Allah al-kadhib yawm al-qiyamah inna Allah la-dhu fadlin 'ala an-nas wa lakinn aktharahum la yashkurun",
        "verse_number": "10:60",
    },
    {
        "arabic_text": "وَمَا تَكُونُ فِي شَاْنٍ وَمَا تَتْلُو مِنْهُ مِن قُرْاٰنٍ وَلَا تَعْمَلُونَ مِنْ عَمَلٍ اِلَّا كُنَّا عَلَيْكُمْ شُهُودًا اِذْ تُفِيضُونَ فِيهِ ۚ وَمَا يَعْزُبُ عَن رَّبِّكَ مِن مِّثْقَالِ ذَرَّةٍ فِي الْاَرْضِ وَلَا فِي السَّمَاءِ وَلَا اَصْغَرَ مِن ذٰلِكَ وَلَا اَكْبَرَ اِلَّا فِي كِتٰبٍ مُّبِينٍ",
        "urdu_text": "اور اٰپ کسی کام میں ہوں اور اس میں سے کوئی قراٰن پڑھتے ہوں اور تم لوگ کوئی عمل کرتے ہو تو ہم تم پر گواہ ہیں جب تم اس میں مشغول ہوتے ہو، اور اٰپ کے رب سے زمین میں اور اٰسمان میں ذرہ برابر کوئی چیز چھپی نہیں اور نہ اس سے چھوٹی اور نہ اس سے بڑی مگر یہ کہ وہ کھلی کتاب میں ہے",
        "persian_text": "و تو در هیچ کاری نیستی و از اٰن قراٰنی نمی‌خوانی و شما هیچ عملی نمی‌کنید مگر اینکه ما بر شما شاهد هستیم چون در اٰن مشغولید، و از پروردگارت هیچ سنگینی ذره‌ای در زمین و اٰسمان پنهان نیست و نه کوچکتر و نه بزرگتر از اٰن جز در کتابی اٰشکار",
        "english_text": "And thou (Muhammad) art not occupied with any business and thou recitest not a Lecture from this (Scripture), and ye (mankind) perform no act, but We are Witness of you when ye are engaged therein. And not an atom's weight in the earth or in the sky escapeth your Lord, nor what is less than that or greater than that, but it is (written) in a clear Book",
        "transliteration": "Wa ma takunu fi sha'nin wa ma tatlu minhu min qur'anin wa la ta'maluna min 'amalin illa kunna 'alaykum shuhadan idh tufiduna fih wa ma ya'zub 'an rabbika min mithqali dharratin fi al-ardi wa la fi as-sama'i wa la asghara min dhalika wa la akbara illa fi kitabin mubin",
        "verse_number": "10:61",
    },
    {
        "arabic_text": "اَلَا اِنَّ اَوْلِيَاءَ اللّٰهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ",
        "urdu_text": "خبردار! بے شک اللہ کے دوستوں پر نہ کوئی خوف ہے اور نہ وہ غمگین ہوتے ہیں",
        "persian_text": "اٰگاه باشید که دوستان خدا نه ترسی بر اٰنان است و نه غمگین می‌شوند",
        "english_text": "Lo! verily the friends of Allah are (those) on whom fear (cometh) not, nor do they grieve",
        "transliteration": "Ala inna awliya' Allah la khawfun 'alayhim wa la hum yahzanun",
        "verse_number": "10:62",
    },
    {
        "arabic_text": "الَّذِينَ اٰمَنُوا وَكَانُوا يَتَّقُونَ",
        "urdu_text": "جو لوگ ایمان لائے اور ڈرتے رہتے تھے",
        "persian_text": "کسانی که ایمان اٰوردند و پرهیزگاری می‌کردند",
        "english_text": "Those who believe and keep their duty (to Allah)",
        "transliteration": "Alladhina amanu wa kanu yattaqun",
        "verse_number": "10:63",
    },
    {
        "arabic_text": "لَهُمُ الْبُشْرَىٰ فِي الْحَيٰوةِ الدُّنْيَا وَفِي الْاٰخِرَةِ ۚ لَا تَبْدِيلَ لِكَلِمَاتِ اللّٰهِ ۚ ذٰلِكَ هُوَ الْفَوْزُ الْعَظِيمُ",
        "urdu_text": "ان کے لیے دنیا کی زندگی میں بھی خوشخبری ہے اور اٰخرت میں بھی، اللہ کی باتوں میں تبدیلی نہیں ہوتی، یہی بڑی کامیابی ہے",
        "persian_text": "برایشان بشارت است در زندگی دنیا و در اٰخرت، برای کلمات خدا تغییری نیست، این همان رستگاری بزرگ است",
        "english_text": "Theirs are good tidings in the life of the world and in the Hereafter - There is no changing the Words of Allah - that is the Supreme Triumph",
        "transliteration": "Lahum al-bushra fi al-hayat ad-dunya wa fi al-akhirah la tabdil li-kalimat Allah dhalika huwa al-fawz al-'azim",
        "verse_number": "10:64",
    },
    {
        "arabic_text": "وَلَا يَحْزُنكَ قَوْلُهُمْ ۘ اِنَّ الْعِزَّةَ لِلَّهِ جَمِيعًا ۚ هُوَ السَّمِيعُ الْعَلِيمُ",
        "urdu_text": "اور ان کی بات اٰپ کو غمگین نہ کرے، بے شک عزت سب اللہ ہی کے لیے ہے، وہ سننے والا جاننے والا ہے",
        "persian_text": "و گفتار اٰنان تو را غمگین نسازد، همانا عزت همه از اٰن خداست، او شنوا و داناست",
        "english_text": "And let not their speech grieve thee (O Muhammad). Lo! power belongeth wholly to Allah. He is the Hearer, the Knower",
        "transliteration": "Wa la yahzunka qawluhum inna al-'izzata lillahi jami'an huwa as-sami' al-'alim",
        "verse_number": "10:65",
    },
    {
        "arabic_text": "اَلَا اِنَّ لِلَّهِ مَن فِي السَّمٰوٰتِ وَمَن فِي الْاَرْضِ ۗ وَمَا يَتَّبِعُ الَّذِينَ يَدْعُونَ مِن دُونِ اللّٰهِ شُرَكَاءَ ۚ اِن يَتَّبِعُونَ اِلَّا الظَّنَّ وَاِنْ هُمْ اِلَّا يَخْرُصُونَ",
        "urdu_text": "خبردار! بے شک اللہ ہی کا ہے جو کچھ اٰسمانوں میں ہے اور جو کچھ زمین میں ہے، اور جو لوگ اللہ کے سوا شریکوں کو پکارتے ہیں وہ کسی چیز کی پیروی نہیں کرتے، وہ صرف گمان کی پیروی کرتے ہیں اور وہ صرف اٹکل پچو باتیں کرتے ہیں",
        "persian_text": "اٰگاه باشید که اٰنچه در اٰسمانها و زمین است از اٰن خداست، و کسانی که غیر از خدا شریکان را می‌خوانند چیزی را پیروی نمی‌کنند، جز گمان پیروی نمی‌کنند و جز دروغ نمی‌گویند",
        "english_text": "Lo! verily unto Allah belong whosoever is in the heavens and whosoever is in the earth. Those who follow aught instead of Allah follow not (His) partners. They follow only a conjecture, and they do but guess",
        "transliteration": "Ala inna lillahi man fi as-samawat wa man fi al-ard wa ma yattabi' alladhina yad'una min dun Allah shurakaa in yattabi'una illa az-zann wa in hum illa yakhrusun",
        "verse_number": "10:66",
    },
    {
        "arabic_text": "هُوَ الَّذِي جَعَلَ لَكُمُ اللَّيْلَ لِتَسْكُنُوا فِيهِ وَالنَّهَارَ مُبْصِرًا ۚ اِنَّ فِي ذٰلِكَ لَاٰيٰتٍ لِّقَوْمٍ يَسْمَعُونَ",
        "urdu_text": "وہی ہے جس نے تمہارے لیے رات بنائی تاکہ تم اس میں اٰرام کرو اور دن کو روشن بنایا، بے شک اس میں سننے والے لوگوں کے لیے نشانیاں ہیں",
        "persian_text": "او کسی است که برای شما شب را قرار داد تا در اٰن اٰرام گیرید و روز را روشن، همانا در اٰن نشانه‌هایی است برای گروهی که می‌شنوند",
        "english_text": "He it is Who has appointed for you the night that ye should rest therein and the day giving sight. Lo! herein verily are portents for a folk that heed",
        "transliteration": "Huwa alladhi ja'ala lakum al-layl li-taskunu fih wa an-nahar mubsiran inna fi dhalika la-ayatin li-qawmin yasma'un",
        "verse_number": "10:67",
    },
    {
        "arabic_text": "قَالُوا اتَّخَذَ اللّٰهُ وَلَدًا ۗ سُبْحٰنَهُ ۖ هُوَ الْغَنِيُّ ۖ لَهُ مَا فِي السَّمٰوٰتِ وَمَا فِي الْاَرْضِ ۚ اِنْ عِندَكُم مِّنْ سُلْطَانٍ بِهٰذَا ۚ اَتَقُولُونَ عَلَى اللّٰهِ مَا لَا تَعْلَمُونَ",
        "urdu_text": "انہوں نے کہا اللہ نے اولاد بنائی ہے، وہ پاک ہے، وہ بے نیاز ہے، اس کا ہے جو کچھ اٰسمانوں میں ہے اور جو کچھ زمین میں ہے، تمہارے پاس اس کی کوئی دلیل نہیں، کیا تم اللہ پر وہ باتیں کہتے ہو جو تم نہیں جانتے",
        "persian_text": "گفتند خدا فرزندی اتخاذ کرده، منزه است، او بی‌نیاز است، از اٰن او است اٰنچه در اٰسمانها و زمین است، نزد شما از این هیچ برهانی نیست، اٰیا بر خدا چیزی می‌گویید که نمی‌دانید",
        "english_text": "They say: Allah hath taken (unto Him) a son - Glorified be He! He hath no needs! His is all that is in the heavens and all that is in the earth. Ye have no warrant for this. Say ye concerning Allah that which ye know not?",
        "transliteration": "Qalu attakhadh Allah waladan subhanah huwa al-ghaniyy lahu ma fi as-samawat wa ma fi al-ard in 'indakum min sultanin bi-hadha ataquluna 'ala Allah ma la ta'lamun",
        "verse_number": "10:68",
    },
    {
        "arabic_text": "قُلْ اِنَّ الَّذِينَ يَفْتَرُونَ عَلَى اللّٰهِ الْكَذِبَ لَا يُفْلِحُونَ",
        "urdu_text": "کہیے جو لوگ اللہ پر جھوٹ باندھتے ہیں وہ کامیاب نہیں ہوتے",
        "persian_text": "بگو کسانی که بر خدا دروغ می‌بندند رستگار نخواهند شد",
        "english_text": "Say: Lo! those who invent a lie concerning Allah will not succeed",
        "transliteration": "Qul inna alladhina yaftarun 'ala Allah al-kadhib la yufliun",
        "verse_number": "10:69",
    },
    {
        "arabic_text": "مَتَاعٌ فِي الدُّنْيَا ثُمَّ اِلَيْنَا مَرْجِعُهُمْ ثُمَّ نُذِيقُهُمُ الْعَذَابَ الشَّدِيدَ بِمَا كَانُوا يَكْفُرُونَ",
        "urdu_text": "دنیا میں تھوڑا سا فائدہ ہے پھر ہماری طرف ان کی واپسی ہے پھر ہم انہیں سخت عذاب چکھائیں گے اس وجہ سے جو وہ کفر کرتے تھے",
        "persian_text": "بهره‌ای در دنیاست سپس بازگشتشان به سوی ماست، سپس عذاب شدید به اٰنان خواهیم چشانید بخاطر اٰنچه کفر می‌ورزیدند",
        "english_text": "This world's portion (will be theirs), then unto Us is their return. Then We make them taste the dreadful doom because they used to disbelieve",
        "transliteration": "Mata'un fi ad-dunya thumma ilayna marji'uhum thumma nudhiquhum al-'adhab ash-shadid bi-ma kanu yakfurun",
        "verse_number": "10:70",
    },
    {
        "arabic_text": "وَاتْلُ عَلَيْهِمْ نَبَاَ نُوحٍ اِذْ قَالَ لِقَوْمِهِ يَا قَوْمِ اِن كَانَ كَبُرَ عَلَيْكُم مَّقَامِي وَتَذْكِيرِي بِاٰيٰتِ اللّٰهِ فَعَلَى اللّٰهِ تَوَكَّلْتُ فَاَجْمِعُوا اَمْرَكُمْ وَشُرَكَاءَكُمْ ثُمَّ لَا يَكُنْ اَمْرُكُمْ عَلَيْكُمْ غُمَّةً ثُمَّ اقْضُوا اِلَيَّ وَلَا تُنظِرُونِ",
        "urdu_text": "اور ان کو نوح کا قصہ سناؤ جب اس نے اپنی قوم سے کہا اے میری قوم! اگر میرا ٹھہرنا اور اللہ کی اٰیات سے نصیحت کرنا تم پر گراں ہے تو میں نے اللہ پر بھروسہ کیا ہے پس تم اپنے کام اور اپنے شریکوں کو جمع کر لو پھر تمہارا معاملہ تم پر پوشیدہ نہ رہے پھر میرے ساتھ فیصلہ کر ڈالو اور مجھے مہلت نہ دو",
        "persian_text": "و بر اٰنان خبر نوح را بخوان اٰنگاه که به قومش گفت ای قوم من! اگر حضور من و یاداٰوری اٰیات خدا بر شما گران است، پس بر خدا توکل کردم، پس کار خود و شریکانتان را جمع کنید سپس کارتان بر شما پوشیده نماند، سپس با من داوری کنید و مرا مهلت ندهید",
        "english_text": "Recite unto them the story of Noah, when he told his people: O my people! If my sojourn (here) and my reminding you by Allah's revelations are an offence unto you, in Allah have I put my trust, so decide upon your course of action you and your partners. Let not your course of action be in doubt for you. Then have at me, give me no respite",
        "transliteration": "Wa-tlu 'alayhim naba'a Nuhin idh qala li-qawmih ya qawm in kana kabur 'alaykum maqami wa tadhkiri bi-ayat Allah fa-'ala Allah tawakkaltu fa-ajmi'u amrakum wa shurakaakum thumma la yakun amrukum 'alaykum ghummatan thumm aqduu ilayya wa la tunzirun",
        "verse_number": "10:71",
    },
    {
        "arabic_text": "فَاِن تَوَلَّيْتُمْ فَمَا سَاَلْتُكُم مِّنْ اَجْرٍ ۖ اِنْ اَجْرِيَ اِلَّا عَلَى اللّٰهِ ۖ وَاُمِرْتُ اَنْ اَكُونَ مِنَ الْمُسْلِمِينَ",
        "urdu_text": "پھر اگر تم منہ پھیر لو تو میں نے تم سے کوئی اجر نہیں مانگا، میرا اجر تو صرف اللہ کے ذمے ہے اور مجھے حکم دیا گیا ہے کہ میں مسلمانوں میں سے ہوں",
        "persian_text": "پس اگر روی برتابید، من از شما مزدی نخواستم، اجر من جز بر خدا نیست و فرمان یافتم که از مسلمانان باشم",
        "english_text": "But if ye are averse I have asked for no wage from you. My wage is the concern of Allah only, and I am commanded to be of those who surrender (unto Him)",
        "transliteration": "Fa-in tawallaytum fama sa'altukum min ajrin in ajriya illa 'ala Allah wa umirtu an akuna min al-muslimin",
        "verse_number": "10:72",
    },
    {
        "arabic_text": "فَكَذَّبُوهُ فَنَجَّيْنَاهُ وَمَن مَّعَهُ فِي الْفُلْكِ وَجَعَلْنَاهُمْ خَلَائِفَ وَاَغْرَقْنَا الَّذِينَ كَذَّبُوا بِاٰيٰتِنَا ۖ فَانظُرْ كَيْفَ كَانَ عَاقِبَةُ الْمُنذَرِينَ",
        "urdu_text": "پس انہوں نے اس کو جھٹلایا تو ہم نے اسے اور جو اس کے ساتھ کشتی میں تھے بچا لیا اور انہیں خلیفہ بنایا اور جنہوں نے ہماری اٰیات کو جھٹلایا تھا انہیں غرق کر دیا، پس دیکھو کہ ڈرائے گئے لوگوں کا انجام کیسا ہوا",
        "persian_text": "پس او را تکذیب کردند، اٰنگاه او و کسانی را که با او در کشتی بودند نجات دادیم و اٰنان را جانشین ساختیم و کسانی را که اٰیات ما را تکذیب کردند غرق نمودیم، پس بنگر عاقبت بیم داده شدگان چگونه بود",
        "english_text": "But they denied him, so We saved him and those with him in the ship, and made them viceroys (in the earth), while We drowned those who denied Our revelations. See then the nature of the consequence for those who had been warned",
        "transliteration": "Fakadhdhabuh fanajjaynahu wa man ma'ahu fi al-fulk wa ja'alnahum khala'if wa aghraqna alladhina kadhdhabu bi-ayatina fanzur kayf kan 'aqibat al-mundharin",
        "verse_number": "10:73",
    },
    {
        "arabic_text": "ثُمَّ بَعَثْنَا مِن بَعْدِهِ رُسُلًا اِلَىٰ قَوْمِهِمْ فَجَاءُوهُم بِالْبَيِّنَاتِ فَمَا كَانُوا لِيُؤْمِنُوا بِمَا كَذَّبُوا بِهِ مِن قَبْلُ ۚ كَذٰلِكَ نَطْبَعُ عَلَىٰ قُلُوبِ الْمُعْتَدِينَ",
        "urdu_text": "پھر اس کے بعد ہم نے اپنی قوموں کی طرف رسول بھیجے تو وہ ان کے پاس کھلی نشانیاں لے کر اٰئے مگر وہ اس پر ایمان لانے والے نہیں تھے جسے انہوں نے پہلے جھٹلایا تھا، اسی طرح ہم حد سے بڑھنے والوں کے دلوں پر مہر لگا دیتے ہیں",
        "persian_text": "سپس پس از او رسولانی به سوی اقوامشان فرستادیم و اٰنان دلایل روشن اٰوردند، اما اٰنان ایمان نمی‌اٰوردند به اٰنچه پیش از این تکذیب کرده بودند، چنین بر دلهای متجاوزان مهر می‌زنیم",
        "english_text": "Then, after him, We sent messengers unto their folk, and they brought them clear proofs. But they were not ready to believe in that which they before denied. Thus print We on the hearts of the transgressors",
        "transliteration": "Thumma ba'athna min ba'dihi rusulan ila qawmihim faja'uhum bil-bayyinat fama kanu li-yu'minu bima kadhdhabu bih min qabl kadhalik natba'u 'ala qulub al-mu'tadin",
        "verse_number": "10:74",
    },
    {
        "arabic_text": "ثُمَّ بَعَثْنَا مِن بَعْدِهِم مُّوسَىٰ وَهَارُونَ اِلَىٰ فِرْعَوْنَ وَمَلَئِهِ بِاٰيٰتِنَا فَاسْتَكْبَرُوا وَكَانُوا قَوْمًا مُّجْرِمِينَ",
        "urdu_text": "پھر ان کے بعد ہم نے موسیٰ اور ہارون کو فرعون اور اس کے سرداروں کی طرف اپنی نشانیوں کے ساتھ بھیجا پس وہ تکبر کرنے لگے اور وہ مجرم قوم تھے",
        "persian_text": "سپس پس از اٰنان موسی و هارون را به سوی فرعون و اشراف او با اٰیاتمان فرستادیم، پس تکبر ورزیدند و قومی مجرم بودند",
        "english_text": "Then, after them, We sent Moses and Aaron unto Pharaoh and his chiefs with Our revelations, but they were arrogant and were a guilty folk",
        "transliteration": "Thumma ba'athna min ba'dihim Musa wa Harun ila Fir'awn wa mala'ih bi-ayatina fastakbaru wa kanu qawman mujrimin",
        "verse_number": "10:75",
    },
    {
        "arabic_text": "فَلَمَّا جَاءَهُمُ الْحَقُّ مِنْ عِندِنَا قَالُوا اِنَّ هٰذَا لَسِحْرٌ مُّبِينٌ",
        "urdu_text": "پھر جب ان کے پاس ہماری طرف سے حق اٰیا تو انہوں نے کہا یہ تو کھلا جادو ہے",
        "persian_text": "پس چون حق از نزد ما بدیشان اٰمد گفتند این جادویی اٰشکار است",
        "english_text": "And when the Truth from Our presence came unto them, they said: Lo! this is mere magic",
        "transliteration": "Falamma ja'ahum al-haqq min 'indina qalu inna hadha la-sihrun mubin",
        "verse_number": "10:76",
    },
    {
        "arabic_text": "قَالَ مُوسَىٰ اَتَقُولُونَ لِلْحَقِّ لَمَّا جَاءَكُمْ ۖ اَسِحْرٌ هٰذَا وَلَا يُفْلِحُ السَّاحِرُونَ",
        "urdu_text": "موسیٰ نے کہا کیا تم حق کے بارے میں یہ کہتے ہو جب وہ تمہارے پاس اٰیا ہے، کیا یہ جادو ہے اور جادوگر کامیاب نہیں ہوتے",
        "persian_text": "موسی گفت اٰیا درباره حق چون بدان اٰمد چنین می‌گویید؟ اٰیا این جادو است و جادوگران رستگار نمی‌شوند",
        "english_text": "Moses said: Speak ye (so) of the Truth when it hath come unto you? Is this magic? Now magicians thrive not",
        "transliteration": "Qala Musa ataquluna lil-haqq lamma ja'akum a-sihrun hadha wa la yuflih as-sahirun",
        "verse_number": "10:77",
    },
    {
        "arabic_text": "قَالُوا اَجِئْتَنَا لِتَلْفِتَنَا عَمَّا وَجَدْنَا عَلَيْهِ اٰبَاءَنَا وَتَكُونَ لَكُمَا الْكِبْرِيَاءُ فِي الْاَرْضِ وَمَا نَحْنُ لَكُمَا بِمُؤْمِنِينَ",
        "urdu_text": "انہوں نے کہا کیا تم اس لیے اٰئے ہو کہ ہمیں اس سے پھیر دو جس پر ہم نے اپنے باپ دادا کو پایا ہے اور تم دونوں کی زمین میں بڑائی ہو، اور ہم تم دونوں پر ایمان لانے والے نہیں",
        "persian_text": "گفتند اٰیا اٰمده‌ای که ما را از اٰنچه پدرانمان را بر اٰن یافتیم برگردانی و برای شما دو تن کبریا در زمین باشد؟ و ما بر شما دو تن ایمان نخواهیم اٰورد",
        "english_text": "They said: Hast thou come unto us to pervert us from that (faith) in which we found our fathers, and that you two may own the place of greatness in the land? We will not believe you two",
        "transliteration": "Qalu aji'tanā li-talfitana 'amma wajadnā 'alayhi ābā'anā wa takūna lakumā al-kibriyā'u fī al-ardi wa mā nahnu lakumā bi-mu'minīn",
        "verse_number": "10:78",
    },
    {
        "arabic_text": "وَقَالَ فِرْعَوْنُ ائْتُونِي بِكُلِّ سَاحِرٍ عَلِيمٍ",
        "urdu_text": "اور فرعون نے کہا میرے پاس ہر ماہر جادوگر کو لے اٰؤ",
        "persian_text": "و فرعون گفت هر جادوگر دانا را نزد من اٰورید",
        "english_text": "And Pharaoh said: Bring unto me every knowing wizard",
        "transliteration": "Wa qāla fir'awn i'tūnī bi-kulli sāhirin 'alīm",
        "verse_number": "10:79",
    },
    {
        "arabic_text": "فَلَمَّا جَاءَ السَّحَرَةُ قَالَ لَهُم مُّوسَىٰ اَلْقُوا مَا اَنتُم مُّلْقُونَ",
        "urdu_text": "پھر جب جادوگر اٰئے تو موسیٰ نے ان سے کہا جو کچھ تم ڈالنے والے ہو ڈال دو",
        "persian_text": "پس چون جادوگران اٰمدند موسی بدیشان گفت اٰنچه می‌اندازید بیندازید",
        "english_text": "And when the wizards came, Moses said unto them: Cast your cast!",
        "transliteration": "Fa-lammā jā'a as-saharah qāla lahum Mūsā alqū mā antum mulqūn",
        "verse_number": "10:80",
    },
    {
        "arabic_text": "فَلَمَّا اَلْقَوْا قَالَ مُوسَىٰ مَا جِئْتُم بِهِ السِّحْرُ ۖ اِنَّ اللّٰهَ سَيُبْطِلُهُ ۖ اِنَّ اللّٰهَ لَا يُصْلِحُ عَمَلَ الْمُفْسِدِينَ",
        "urdu_text": "پھر جب انہوں نے ڈالا تو موسیٰ نے کہا جو تم لے کر اٰئے ہو وہ جادو ہے، بے شک اللہ اسے باطل کر دے گا، بے شک اللہ فساد کرنے والوں کے کام کو درست نہیں کرتا",
        "persian_text": "پس چون انداختند موسی گفت اٰنچه اٰورده‌اید جادو است، همانا خدا اٰن را باطل خواهد کرد، همانا خدا کار مفسدان را اصلاح نمی‌کند",
        "english_text": "And when they had cast, Moses said: That which ye have brought is magic. Lo! Allah will make it vain. Lo! Allah upholdeth not the work of mischief-makers",
        "transliteration": "Fa-lammā alqaw qāla Mūsā mā ji'tum bih as-sihr inna Allāha sa-yubtiluh inna Allāha lā yuslih 'amal al-mufsidīn",
        "verse_number": "10:81",
    },
    {
        "arabic_text": "وَيُحِقُّ اللّٰهُ الْحَقَّ بِكَلِمَاتِهِ وَلَوْ كَرِهَ الْمُجْرِمُونَ",
        "urdu_text": "اور اللہ اپنے کلمات سے حق کو ثابت کر دیتا ہے اگرچہ مجرم ناپسند کریں",
        "persian_text": "و خدا حق را با کلماتش محق می‌گرداند اگرچه مجرمان کراهت داشته باشند",
        "english_text": "And Allah will vindicate the Truth by His words, however much the guilty be averse",
        "transliteration": "Wa yuhiqq Allāh al-haqq bi-kalimātih wa law karih al-mujrimūn",
        "verse_number": "10:82",
    },
    {
        "arabic_text": "فَمَا اٰمَنَ لِمُوسَىٰ اِلَّا ذُرِّيَّةٌ مِّن قَوْمِهِ عَلَىٰ خَوْفٍ مِّن فِرْعَوْنَ وَمَلَئِهِمْ اَن يَفْتِنَهُمْ ۚ وَاِنَّ فِرْعَوْنَ لَعٰلٍ فِي الْاَرْضِ وَاِنَّهُ لَمِنَ الْمُسْرِفِينَ",
        "urdu_text": "پھر موسیٰ پر صرف اس کی قوم کی کچھ اولاد نے ایمان لایا فرعون اور اس کے سرداروں کے ڈر سے کہ کہیں وہ انہیں ستا نہ دے، اور بے شک فرعون زمین میں سرکش تھا اور بے شک وہ حد سے بڑھنے والوں میں سے تھا",
        "persian_text": "پس جز ذریه‌ای از قوم او کسی بر موسی ایمان نیاورد از ترس فرعون و اشرافش که مبادا اٰنان را بیازماید، و همانا فرعون در زمین متکبر بود و همانا از مسرفان بود",
        "english_text": "But none trusted Moses, save some scions of his people, (and they were) in fear of Pharaoh and their chiefs, that he would persecute them. Lo! Pharaoh was verily a tyrant in the land, and lo! he verily was of the wanton",
        "transliteration": "Fa-mā āman li-Mūsā illā dhurriyyatun min qawmih 'alā khawfin min fir'awn wa mala'ihim an yaftinahum wa inna fir'awn la-'ālin fī al-ard wa innah la-min al-musrifīn",
        "verse_number": "10:83",
    },
    {
        "arabic_text": "وَقَالَ مُوسَىٰ يَا قَوْمِ اِن كُنتُمْ اٰمَنتُم بِاللّٰهِ فَعَلَيْهِ تَوَكَّلُوا اِن كُنتُم مُّسْلِمِينَ",
        "urdu_text": "اور موسیٰ نے کہا اے میری قوم! اگر تم اللہ پر ایمان لائے ہو تو اسی پر بھروسہ کرو اگر تم مسلمان ہو",
        "persian_text": "و موسی گفت ای قوم من! اگر بر خدا ایمان اٰورده‌اید پس بر او توکل کنید اگر مسلمانید",
        "english_text": "And Moses said: O my people! If ye have believed in Allah then put trust in Him, if ye have surrendered (unto Him)",
        "transliteration": "Wa qāla Mūsā yā qawm in kuntum āmantum billāh fa-'alayhi tawakkalū in kuntum muslimīn",
        "verse_number": "10:84",
    },
    {
        "arabic_text": "فَقَالُوا عَلَى اللّٰهِ تَوَكَّلْنَا رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ الظَّالِمِينَ",
        "urdu_text": "پس انہوں نے کہا ہم نے اللہ پر بھروسہ کیا، اے ہمارے رب! ہمیں ظالم قوم کے لیے اٰزمائش نہ بنا",
        "persian_text": "پس گفتند بر خدا توکل کردیم، ای پروردگار ما! ما را فتنه‌ای برای قوم ستمکار قرار مده",
        "english_text": "They said: In Allah we put trust. Our Lord! Oh, make us not a lure for the wrongdoing folk",
        "transliteration": "Fa-qalu 'ala Allah tawakkalna rabbana la taj'alna fitnatan lil-qawm az-zalimin",
        "verse_number": "10:85",
    },
    {
        "arabic_text": "وَنَجِّنَا بِرَحْمَتِكَ مِنَ الْقَوْمِ الْكٰفِرِينَ",
        "urdu_text": "اور اپنی رحمت سے ہمیں کافر قوم سے نجات دے",
        "persian_text": "و ما را به رحمتت از قوم کافر نجات ده",
        "english_text": "And, of Thy mercy, save us from the folk that disbelieve",
        "transliteration": "Wa najjina bi-rahmatika min al-qawm al-kafirin",
        "verse_number": "10:86",
    },
    {
        "arabic_text": "وَاَوْحَيْنَا اِلَىٰ مُوسَىٰ وَاَخِيهِ اَن تَبَوَّاٰ لِقَوْمِكُمَا بِمِصْرَ بُيُوتًا وَاجْعَلُوا بُيُوتَكُمْ قِبْلَةً وَاَقِيمُوا الصَّلَاةَ ۗ وَبَشِّرِ الْمُؤْمِنِينَ",
        "urdu_text": "اور ہم نے موسیٰ اور اس کے بھائی کو وحی کی کہ اپنی قوم کے لیے مصر میں گھر بناؤ اور اپنے گھروں کو قبلہ بناؤ اور نماز قائم کرو اور مومنوں کو خوشخبری دے دو",
        "persian_text": "و به موسی و برادرش وحی کردیم که برای قومتان در مصر خانه‌هایی برگزینید و خانه‌هایتان را قبله قرار دهید و نماز برپا کنید و مؤمنان را بشارت ده",
        "english_text": "And We inspired Moses and his brother, (saying): Appoint houses for your people in Egypt and make your houses oratories, and establish worship. And give good tidings to the believers",
        "transliteration": "Wa awhayna ila Musa wa akhih an tabauu'a li-qawmikuma bi-Misr buyutan wa-j'alu buyutakum qiblatan wa aqimu as-salah wa bashshir al-mu'minin",
        "verse_number": "10:87",
    },
    {
        "arabic_text": "وَقَالَ مُوسَىٰ رَبَّنَا اِنَّكَ اٰتَيْتَ فِرْعَوْنَ وَمَلَاَهُ زِينَةً وَاَمْوَالًا فِي الْحَيٰوةِ الدُّنْيَا رَبَّنَا لِيُضِلُّوا عَن سَبِيلِكَ ۖ رَبَّنَا اطْمِسْ عَلَىٰ اَمْوَالِهِمْ وَاشْدُدْ عَلَىٰ قُلُوبِهِمْ فَلَا يُؤْمِنُوا حَتَّىٰ يَرَوُا الْعَذَابَ الْاَلِيمَ",
        "urdu_text": "اور موسیٰ نے کہا اے ہمارے رب! بے شک تو نے فرعون اور اس کے سرداروں کو دنیا کی زندگی میں اٰرائش اور مال دیا ہے، اے ہمارے رب! تاکہ وہ تیرے راستے سے بھٹکائیں، اے ہمارے رب! ان کے مالوں کو مٹا دے اور ان کے دلوں کو سخت کر دے تو وہ ایمان نہ لائیں یہاں تک کہ دردناک عذاب دیکھ لیں",
        "persian_text": "و موسی گفت پروردگار ما! تو به فرعون و اشرافش زینت و اموالی در زندگی دنیا دادی، پروردگار ما! تا از راه تو گمراه کنند، پروردگار ما! اموالشان را محو کن و بر دلهایشان سختی کن تا ایمان نیاورند تا عذاب دردناک ببینند",
        "english_text": "And Moses said: Our Lord! Lo! Thou hast given Pharaoh and his chiefs splendor and riches in the life of the world, Our Lord! that they may lead men astray from Thy way. Our Lord! Destroy their riches and harden their hearts so that they believe not until they see the painful doom",
        "transliteration": "Wa qala Musa rabbana innaka atayta fir'awn wa mala'ah zinatan wa amwalan fi al-hayat ad-dunya rabbana li-yudillu 'an sabilik rabbana itmis 'ala amwalihim wa-shdud 'ala qulubihim fala yu'minu hatta yaraw al-'adhab al-alim",
        "verse_number": "10:88",
    },
    {
        "arabic_text": "قَالَ قَدْ اُجِيبَت دَّعْوَتُكُمَا فَاسْتَقِيمَا وَلَا تَتَّبِعَانِّ سَبِيلَ الَّذِينَ لَا يَعْلَمُونَ",
        "urdu_text": "فرمایا تم دونوں کی دعا قبول ہو گئی پس سیدھے رہو اور ان لوگوں کے راستے کی پیروی نہ کرو جو نہیں جانتے",
        "persian_text": "فرمود دعای شما دو تن اجابت شد، پس استقامت کنید و راه کسانی را پیروی نکنید که نمی‌دانند",
        "english_text": "He said: Your prayer is heard. Do ye twain keep to the straight path, and follow not the road of those who have no knowledge",
        "transliteration": "Qala qad ujibat da'watukuma fastaqima wa la tattabi'anni sabil alladhina la ya'lamun",
        "verse_number": "10:89",
    },
    {
        "arabic_text": "وَجَاوَزْنَا بِبَنِي اِسْرَائِيلَ الْبَحْرَ فَاَتْبَعَهُمْ فِرْعَوْنُ وَجُنُودُهُ بَغْيًا وَعَدْوًا ۖ حَتَّىٰ اِذَا اَدْرَكَهُ الْغَرَقُ قَالَ اٰمَنتُ اَنَّهُ لَا اِلَـٰهَ اِلَّا الَّذِي اٰمَنَتْ بِهِ بَنُو اِسْرَائِيلَ وَاَنَا مِنَ الْمُسْلِمِينَ",
        "urdu_text": "اور ہم نے بنی اسرائیل کو سمندر پار کرایا پس فرعون اور اس کے لشکر نے ان کا تعاقب کیا ظلم اور دشمنی سے، یہاں تک کہ جب اسے ڈوبنا پکڑا تو کہا میں ایمان لایا کہ کوئی معبود نہیں سوائے اس کے جس پر بنی اسرائیل ایمان لائے اور میں مسلمانوں میں سے ہوں",
        "persian_text": "و بنی اسرائیل را از دریا گذراندیم، پس فرعون و سپاهش اٰنان را تعقیب کردند از روی ستم و دشمنی تا چون غرق او را فرا گرفت گفت ایمان اٰوردم که هیچ خدایی نیست مگر اٰن که بنی اسرائیل بدان ایمان اٰوردند و من از مسلمانانم",
        "english_text": "And We brought the Children of Israel across the sea, and Pharaoh with his hosts pursued them in rebellion and transgression, till, when the (fate of) drowning overtook him, he exclaimed: I believe that there is no God save Him in Whom the Children of Israel believe, and I am of those who surrender (unto Him)",
        "transliteration": "Wa jawazna bi-bani Isra'il al-bahr fa-atba'ahum fir'awn wa junuduh baghyan wa 'adwan hatta idha adrakah al-gharaq qala amantu annah la ilah illa alladhi amanat bih banu Isra'il wa ana min al-muslimin",
        "verse_number": "10:90",
    },
    {
        "arabic_text": "اٰلْاٰنَ وَقَدْ عَصَيْتَ قَبْلُ وَكُنتَ مِنَ الْمُفْسِدِينَ",
        "urdu_text": "اب جبکہ تو نے پہلے نافرمانی کی اور تو فساد کرنے والوں میں سے تھا",
        "persian_text": "اکنون که پیش از این نافرمانی کردی و از مفسدان بودی",
        "english_text": "What! Now! When hitherto thou hast rebelled and been of the wrong-doers?",
        "transliteration": "Al-an wa qad 'asayta qabl wa kunta min al-mufsiddin",
        "verse_number": "10:91",
    },
    {
        "arabic_text": "فَالْيَوْمَ نُنَجِّيكَ بِبَدَنِكَ لِتَكُونَ لِمَنْ خَلْفَكَ اٰيَةً ۚ وَاِنَّ كَثِيرًا مِّنَ النَّاسِ عَنْ اٰيٰتِنَا لَغَافِلُونَ",
        "urdu_text": "پس اٰج ہم تیرے جسم سے تجھے بچا لیتے ہیں تاکہ تو اپنے بعد والوں کے لیے نشانی بنے، اور بے شک بہت سے لوگ ہماری اٰیات سے غافل ہیں",
        "persian_text": "پس امروز تو را با بدنت نجات می‌دهیم تا برای کسانی که پس از تو اٰیند نشانه‌ای باشی، و همانا بسیاری از مردم از اٰیات ما غافلند",
        "english_text": "But this day We save thee in thy body that thou mayst be a portent for those after thee. Lo! most of mankind are heedless of Our portents",
        "transliteration": "Fa-al-yawm nunajjika bi-badanik li-takun li-man khalfaka ayatan wa inna kathiran min an-nas 'an ayatina la-ghafilun",
        "verse_number": "10:92",
    },
    {
        "arabic_text": "وَلَقَدْ بَوَّاْنَا بَنِي اِسْرَائِيلَ مُبَوَّاَ صِدْقٍ وَرَزَقْنَاهُم مِّنَ الطَّيِّبَاتِ فَمَا اخْتَلَفُوا حَتَّىٰ جَاءَهُمُ الْعِلْمُ ۚ اِنَّ رَبَّكَ يَقْضِي بَيْنَهُمْ يَوْمَ الْقِيَامَةِ فِيمَا كَانُوا فِيهِ يَخْتَلِفُونَ",
        "urdu_text": "اور بے شک ہم نے بنی اسرائیل کو سچا ٹھکانہ دیا اور انہیں پاکیزہ چیزوں کا رزق دیا پھر وہ اختلاف نہیں کرتے تھے یہاں تک کہ ان کے پاس علم اٰ گیا، بے شک اٰپ کا رب قیامت کے دن ان کے درمیان فیصلہ کرے گا جس میں وہ اختلاف کرتے تھے",
        "persian_text": "و به راستی بنی اسرائیل را جایگاه راستی دادیم و از پاکیزه‌ها روزیشان کردیم، پس اختلاف نکردند تا اٰنکه علم بدیشان اٰمد، همانا پروردگارت در روز قیامت در اٰنچه اختلاف می‌کردند میانشان داوری خواهد کرد",
        "english_text": "And We verily did allot unto the Children of Israel a fixed abode, and did provide them with good things; and they differed not until the knowledge came unto them. Lo! thy Lord will judge between them on the Day of Resurrection concerning that wherein they used to differ",
        "transliteration": "Wa laqad bawwa'na bani Isra'il mubawwa'a sidqin wa razaqnahum min at-tayyibat fama ikhtalaf hatta ja'ahum al-'ilm inna rabbaka yaqdi baynahum yawm al-qiyamah fima kanu fih yakhtalifun",
        "verse_number": "10:93",
    },
    {
        "arabic_text": "فَاِن كُنتَ فِي شَكٍّ مِّمَّا اَنزَلْنَا اِلَيْكَ فَاسْاَلِ الَّذِينَ يَقْرَءُونَ الْكِتٰبَ مِن قَبْلِكَ ۚ لَقَدْ جَاءَكَ الْحَقُّ مِن رَّبِّكَ فَلَا تَكُونَنَّ مِنَ الْمُمْتَرِينَ",
        "urdu_text": "پس اگر اٰپ کو اس میں شک ہو جو ہم نے اٰپ پر نازل کیا ہے تو ان سے پوچھیں جو اٰپ سے پہلے کتاب پڑھتے تھے، بے شک اٰپ کے پاس اٰپ کے رب کی طرف سے حق اٰ گیا ہے پس اٰپ شک کرنے والوں میں سے نہ ہوں",
        "persian_text": "پس اگر در اٰنچه بر تو نازل کردیم شک داری، از کسانی که پیش از تو کتاب می‌خوانند بپرس، به راستی حق از پروردگارت به تو اٰمده، پس از شک کنندگان مباش",
        "english_text": "And if thou (Muhammad) art in doubt concerning that which We reveal unto thee, then question those who read the Scripture (that was) before thee. Verily the Truth from thy Lord hath come unto thee. So be not thou of the waverers",
        "transliteration": "Fa-in kunta fi shakkin mimma anzalna ilayk fas'al alladhina yaqra'un al-kitab min qablik laqad ja'ak al-haqq min rabbik fala takunanna min al-mumtarin",
        "verse_number": "10:94",
    },
    {
        "arabic_text": "وَلَا تَكُونَنَّ مِنَ الَّذِينَ كَذَّبُوا بِاٰيٰتِ اللّٰهِ فَتَكُونَ مِنَ الْخَاسِرِينَ",
        "urdu_text": "اور ان لوگوں میں سے نہ ہوں جنہوں نے اللہ کی اٰیات کو جھٹلایا تو اٰپ خسارے والوں میں سے ہو جائیں",
        "persian_text": "و از کسانی مباش که اٰیات خدا را تکذیب کردند تا از زیانکاران باشی",
        "english_text": "And be not thou of those who deny the revelations of Allah, for then wert thou of the losers",
        "transliteration": "Wa la takunanna min alladhina kadhdhabu bi-ayat Allah fa-takuna min al-khasirin",
        "verse_number": "10:95",
    },
    {
        "arabic_text": "اِنَّ الَّذِينَ حَقَّتْ عَلَيْهِمْ كَلِمَتُ رَبِّكَ لَا يُؤْمِنُونَ",
        "urdu_text": "بے شک جن لوگوں پر اٰپ کے رب کا فیصلہ ثابت ہو گیا وہ ایمان نہیں لائیں گے",
        "persian_text": "همانا کسانی که کلمه پروردگارت بر اٰنان محقق شده ایمان نخواهند اٰورد",
        "english_text": "Lo! those for whom the word of thy Lord (concerning punishment) hath effect will not believe",
        "transliteration": "Inna alladhina haqqat 'alayhim kalimatu rabbika la yu'minun",
        "verse_number": "10:96",
    },
    {
        "arabic_text": "وَلَوْ جَاءَتْهُمْ كُلُّ اٰيَةٍ حَتَّىٰ يَرَوُا الْعَذَابَ الْاَلِيمَ",
        "urdu_text": "اگرچہ ان کے پاس ہر نشانی اٰ جائے یہاں تک کہ وہ دردناک عذاب دیکھ لیں",
        "persian_text": "اگرچه هر نشانه‌ای بدیشان اٰید تا عذاب دردناک ببینند",
        "english_text": "Though every token come unto them, till they see the painful doom",
        "transliteration": "Wa law ja'at-hum kullu ayatin hatta yaraw al-'adhab al-alim",
        "verse_number": "10:97",
    },
    {
        "arabic_text": "فَلَوْلَا كَانَتْ قَرْيَةٌ اٰمَنَتْ فَنَفَعَهَا اِيمَانُهَا اِلَّا قَوْمَ يُونُسَ لَمَّا اٰمَنُوا كَشَفْنَا عَنْهُمْ عَذَابَ الْخِزْيِ فِي الْحَيٰوةِ الدُّنْيَا وَمَتَّعْنَاهُمْ اِلَىٰ حِينٍ",
        "urdu_text": "پھر کیوں نہیں ہوا کہ کوئی بستی ایمان لے اٰتی تو اس کا ایمان اسے فائدہ دیتا سوائے یونس کی قوم کے جب وہ ایمان لائے تو ہم نے ان سے دنیا کی زندگی میں رسوائی کا عذاب ہٹا دیا اور انہیں ایک وقت تک فائدہ دیا",
        "persian_text": "پس چرا نبود قریه‌ای که ایمان اٰورد تا ایمانش سودش دهد جز قوم یونس که چون ایمان اٰوردند عذاب خواری را در زندگی دنیا از اٰنان برطرف کردیم و تا مدتی بهره‌مند ساختیمشان",
        "english_text": "If only there had been a community (of all those that were destroyed of old) that believed and profited by its belief as did the folk of Jonah! When they believed We drew off from them the torment of disgrace in the life of the world and gave them comfort for a while",
        "transliteration": "Fa-law-la kanat qaryatun amanat fa-nafa'aha imanuha illa qawm Yunus lamma amanu kashafna 'anhum 'adhab al-khizyi fi al-hayat ad-dunya wa matta'nahum ila hin",
        "verse_number": "10:98",
    },
    {
        "arabic_text": "وَلَوْ شَاءَ رَبُّكَ لَاٰمَنَ مَن فِي الْاَرْضِ كُلُّهُمْ جَمِيعًا ۚ اَفَاَنتَ تُكْرِهُ النَّاسَ حَتَّىٰ يَكُونُوا مُؤْمِنِينَ",
        "urdu_text": "اور اگر اٰپ کا رب چاہتا تو زمین میں جتنے لوگ ہیں سب کے سب ایمان لے اٰتے، تو کیا اٰپ لوگوں پر زبردستی کریں گے یہاں تک کہ وہ مومن ہو جائیں",
        "persian_text": "و اگر پروردگارت می‌خواست همه کسانی که در زمینند ایمان می‌اٰوردند، اٰیا تو مردم را اجبار کنی تا مؤمن شوند؟",
        "english_text": "And if thy Lord willed, all who are in the earth would have believed together. Wouldst thou (Muhammad) compel men until they are believers?",
        "transliteration": "Wa law sha'a rabbuka la-amana man fi al-ard kulluhum jami'an afa-anta tukrih an-nas hatta yakunu mu'minin",
        "verse_number": "10:99",
    },
    {
        "arabic_text": "وَمَا كَانَ لِنَفْسٍ اَن تُؤْمِنَ اِلَّا بِاِذْنِ اللّٰهِ ۚ وَيَجْعَلُ الرِّجْسَ عَلَى الَّذِينَ لَا يَعْقِلُونَ",
        "urdu_text": "اور کسی جان کے لیے یہ نہیں کہ وہ ایمان لائے مگر اللہ کی اجازت سے، اور جو عقل نہیں رکھتے ان پر وہ گندگی ڈال دیتا ہے",
        "persian_text": "و هیچ نفسی را نیست که ایمان اٰورد جز به اذن خدا، و بر کسانی که عقل نمی‌کنند پلیدی می‌گذارد",
        "english_text": "It is not for any soul to believe save by the permission of Allah. He hath set uncleanness upon those who have no sense",
        "transliteration": "Wa ma kana li-nafsin an tu'min illa bi-idhn Allah wa yaj'al ar-rijs 'ala alladhina la ya'qilun",
        "verse_number": "10:100",
    },
    {
        "arabic_text": "قُلِ انظُرُوا مَاذَا فِي السَّمٰوٰتِ وَالْاَرْضِ ۚ وَمَا تُغْنِي الْاٰيٰتُ وَالنُّذُرُ عَن قَوْمٍ لَّا يُؤْمِنُونَ",
        "urdu_text": "کہیے دیکھو اٰسمانوں اور زمین میں کیا ہے، اور نشانیاں اور ڈرانے والے اس قوم کو کچھ فائدہ نہیں دیتے جو ایمان نہیں لاتے",
        "persian_text": "بگو بنگرید اٰنچه در اٰسمانها و زمین است، و اٰیات و بیم دهندگان قومی را که ایمان نمی‌اٰورند سودی نمی‌دهد",
        "english_text": "Say: Behold what is in the heavens and the earth! But revelations and warnings avail not folk who will not believe",
        "transliteration": "Qul anzuru madha fi as-samawat wal-ard wa ma tughnī al-ayat wan-nudhur 'an qawmin la yu'minun",
        "verse_number": "10:101",
    },
    {
        "arabic_text": "فَهَلْ يَنتَظِرُونَ اِلَّا مِثْلَ اَيَّامِ الَّذِينَ خَلَوْا مِن قَبْلِهِمْ ۚ قُلْ فَانتَظِرُوا اِنِّي مَعَكُم مِّنَ الْمُنتَظِرِينَ",
        "urdu_text": "تو کیا وہ صرف ان دنوں کی طرح کے دنوں کا انتظار کرتے ہیں جو ان سے پہلے گزر گئے، کہیے تو انتظار کرو میں بھی تمہارے ساتھ انتظار کرنے والوں میں سے ہوں",
        "persian_text": "اٰیا جز مثل روزهای کسانی که پیش از اٰنان گذشتند انتظار می‌کشند؟ بگو پس انتظار کشید که من نیز با شما از انتظارکشندگانم",
        "english_text": "What expect they save the like of the days of those who passed away before them? Say: Expect then! I am with you among the expectant",
        "transliteration": "Fa-hal yantaziruna illa mithla ayyam alladhina khalaw min qablihim qul fantaziru inni ma'akum min al-muntazirin",
        "verse_number": "10:102",
    },
    {
        "arabic_text": "ثُمَّ نُنَجِّي رُسُلَنَا وَالَّذِينَ اٰمَنُوا ۚ كَذٰلِكَ حَقًّا عَلَيْنَا نُنجِ الْمُؤْمِنِينَ",
        "urdu_text": "پھر ہم اپنے رسولوں کو اور جو ایمان لائے انہیں نجات دیتے ہیں، اسی طرح ہمارے ذمے حق ہے کہ ہم مومنوں کو بچائیں",
        "persian_text": "سپس رسولانمان و کسانی را که ایمان اٰوردند نجات می‌دهیم، چنین بر ما حق است که مؤمنان را نجات دهیم",
        "english_text": "Then shall We save Our messengers and the believers, in like manner (as of old). It is incumbent upon Us to save believers",
        "transliteration": "Thumma nunajiī rusulana walladhina amanu kadhalika haqqan 'alayna nunji al-mu'minin",
        "verse_number": "10:103",
    },
    {
        "arabic_text": "قُلْ يَا اَيُّهَا النَّاسُ اِن كُنتُمْ فِي شَكٍّ مِّن دِينِي فَلَا اَعْبُدُ الَّذِينَ تَعْبُدُونَ مِن دُونِ اللّٰهِ وَلَـٰكِنْ اَعْبُدُ اللّٰهَ الَّذِي يَتَوَفَّاكُمْ ۖ وَاُمِرْتُ اَنْ اَكُونَ مِنَ الْمُؤْمِنِينَ",
        "urdu_text": "کہیے اے لوگو! اگر تم میرے دین میں شک کرتے ہو تو میں ان کی عبادت نہیں کرتا جن کی تم اللہ کے سوا عبادت کرتے ہو لیکن میں اللہ کی عبادت کرتا ہوں جو تمہیں موت دیتا ہے اور مجھے حکم دیا گیا ہے کہ میں مومنوں میں سے ہوں",
        "persian_text": "بگو ای مردم! اگر در دین من شک دارید، پس من اٰنچه شما غیر از خدا می‌پرستید نمی‌پرستم، بلکه خدا را می‌پرستم که شما را می‌میراند، و فرمان یافتم که از مؤمنان باشم",
        "english_text": "Say (O Muhammad): O mankind! If ye are in doubt of my religion, then (know that) I worship not those whom ye worship instead of Allah, but I worship Allah Who causeth you to die, and I have been commanded to be of the believers",
        "transliteration": "Qul ya ayyuha an-nas in kuntum fi shakkin min dini fala a'bud alladhina ta'buduna min dun Allah wa lakin a'bud Allah alladhi yatawaffakum wa umirtu an akuna min al-mu'minin",
        "verse_number": "10:104",
    },
    {
        "arabic_text": "وَاَنْ اَقِمْ وَجْهَكَ لِلدِّينِ حَنِيفًا ۚ وَلَا تَكُونَنَّ مِنَ الْمُشْرِكِينَ",
        "urdu_text": "اور یہ کہ اپنا چہرہ دین کی طرف سیدھا رکھو اور مشرکوں میں سے نہ ہو",
        "persian_text": "و اینکه روی خود را برای دین یکسو کن و از مشرکان مباش",
        "english_text": "And, (O Muhammad) set thy purpose resolutely for religion, as a man by nature upright, and be not of those who ascribe partners (to Allah)",
        "transliteration": "Wa an aqim wajhaka lil-din hanifan wa la takunanna min al-mushrikin",
        "verse_number": "10:105",
    },
    {
        "arabic_text": "وَلَا تَدْعُ مِن دُونِ اللّٰهِ مَا لَا يَنفَعُكَ وَلَا يَضُرُّكَ ۖ فَاِن فَعَلْتَ فَاِنَّكَ اِذًا مِّنَ الظَّالِمِينَ",
        "urdu_text": "اور اللہ کے سوا اسے نہ پکارو جو نہ تمہیں فائدہ دے سکے اور نہ نقصان، پس اگر تم نے ایسا کیا تو تم ظالموں میں سے ہو گے",
        "persian_text": "و غیر از خدا اٰنچه تو را سود و زیان نمی‌رساند مخوان، پس اگر چنین کنی از ستمکاران خواهی بود",
        "english_text": "And cry not, beside Allah, unto that which cannot profit thee nor hurt thee, for if thou didst so then wert thou of the wrong-doers",
        "transliteration": "Wa la tad'u min dun Allah ma la yanfa'uka wa la yadurruka fa-in fa'alta fa-innaka idhan min az-zalimin",
        "verse_number": "10:106",
    },
    {
        "arabic_text": "وَاِن يَمْسَسْكَ اللّٰهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ اِلَّا هُوَ ۖ وَاِن يُرِدْكَ بِخَيْرٍ فَلَا رَادَّ لِفَضْلِهِ ۚ يُصِيبُ بِهِ مَن يَشَاءُ مِنْ عِبَادِهِ ۚ وَهُوَ الْغَفُورُ الرَّحِيمُ",
        "urdu_text": "اور اگر اللہ تمہیں کوئی نقصان پہنچائے تو اس کے سوا کوئی اسے دور کرنے والا نہیں، اور اگر وہ تمہیں بھلائی کا ارادہ کرے تو اس کے فضل کو کوئی لوٹانے والا نہیں، وہ اپنے بندوں میں سے جس کو چاہتا ہے اسے پہنچاتا ہے اور وہ بخشنے والا مہربان ہے",
        "persian_text": "و اگر خدا ضرری به تو رساند جز او کسی اٰن را برطرف نکند، و اگر خیری برایت اراده کند کسی فضل او را باز نگرداند، به هر که از بندگانش بخواهد می‌رساند و او اٰمرزنده مهربان است",
        "english_text": "If Allah afflict thee with some hurt, there is none who can remove it save Him; and if He desire good for thee, there is none who can repel His bounty. He striketh with it whom He will of his bondmen. He is the Forgiving, the Merciful",
        "transliteration": "Wa in yamsaska Allah bi-durrin fala kashifa lahu illa huwa wa in yuridka bi-khayrin fala radda li-fadlih yusib bih man yasha'u min 'ibadih wa huwa al-ghafur ar-rahim",
        "verse_number": "10:107",
    },
    {
        "arabic_text": "قُلْ يَا اَيُّهَا النَّاسُ قَدْ جَاءَكُمُ الْحَقُّ مِن رَّبِّكُمْ ۖ فَمَنِ اهْتَدَىٰ فَاِنَّمَا يَهْتَدِي لِنَفْسِهِ ۖ وَمَن ضَلَّ فَاِنَّمَا يَضِلُّ عَلَيْهَا ۖ وَمَا اَنَا عَلَيْكُم بِوَكِيلٍ",
        "urdu_text": "کہیے اے لوگو! تمہارے پاس تمہارے رب کی طرف سے حق اٰ گیا ہے، پس جو ہدایت پائے تو وہ اپنے ہی لیے ہدایت پاتا ہے اور جو گمراہ ہو تو وہ اپنے ہی نقصان میں گمراہ ہوتا ہے اور میں تم پر نگہبان نہیں ہوں",
        "persian_text": "بگو ای مردم! حق از پروردگارتان بدان اٰمد، پس هر که هدایت یابد تنها برای خودش هدایت می‌یابد و هر که گمراه شود تنها بر خودش گمراه می‌شود و من بر شما وکیل نیستم",
        "english_text": "Say: O mankind! Now hath the Truth from your Lord come unto you. So whosoever is guided, is guided only for (the good of) his soul, and whosoever erreth erreth only against it. And I am not a warder over you",
        "transliteration": "Qul ya ayyuha an-nas qad ja'akum al-haqq min rabbikum faman ihtada fa-innama yahtadi li-nafsih wa man dalla fa-innama yadillu 'alayha wa ma ana 'alaykum bi-wakil",
        "verse_number": "10:108",
    },
    {
        "arabic_text": "وَاتَّبِعْ مَا يُوحَىٰ اِلَيْكَ وَاصْبِرْ حَتَّىٰ يَحْكُمَ اللّٰهُ ۚ وَهُوَ خَيْرُ الْحَاكِمِينَ",
        "urdu_text": "اور جو اٰپ کی طرف وحی کیا جاتا ہے اس کی پیروی کریں اور صبر کریں یہاں تک کہ اللہ فیصلہ کر دے اور وہ سب سے بہتر فیصلہ کرنے والا ہے",
        "persian_text": "و اٰنچه بر تو وحی می‌شود پیروی کن و شکیبا باش تا خدا حکم کند و او بهترین حاکمان است",
        "english_text": "And (O Muhammad) follow that which is inspired in thee, and forbear until Allah give judgment. And He is the Best of Judges",
        "transliteration": "Wa-ttabi' ma yuha ilayka wa-sbir hatta yahkum Allah wa huwa khayr al-hakimin",
        "verse_number": "10:109",
    },
]
